### ISSUE TITLE
Feature Request: Application Title Update Suggestion

### ISSUE THREAD

**Issue by loneregister** [dcs-liberation/dcs_liberation#100]
I am seeing more and more video's with your software on it.  Which is fantastic.

I'd love to see the following added to the title bar:

The version of the application at the end.  And then a pipe | with a short URL that brings people to this github.

For example
DCS Liberation 2.0.11a | https:/tiny.url/dfafaf

This would be marketing for your product - and the url above might be seen in a youtube video (or twitch stream) that people could copy and arrive here.

**Comment by Khopa** [comment]
Yes, good idea, the next version will have the version number in windows title;

I think the url is a bit too much though, as usually youtubers put the link in the video description or someone will ask for it in the comments section.
