### ISSUE TITLE
Move package waypoints

### ISSUE THREAD

**Issue by alexkrebiehl** [dcs-liberation/dcs_liberation#1000]
Sometimes Liberation plans flights that put the package in danger. The ability to move/drag waypoints so the flight will stay out of harms way would be a great addition. This opens up the ability to do "deep strike" missions, where a package can circle around known threat areas to take out strategic targets. Additionally, the ability to add waypoints before/after the target's waypoint allows fine control over which direction a package will ingress/egress from, further reducing the chance of getting in harms way.

![image](https://user-images.githubusercontent.com/3046596/115481547-d6b57e00-a21a-11eb-9e2e-266371189050.png)

**Comment by DanAlbert** [comment]
https://github.com/Khopa/dcs_liberation/issues/560
