### ISSUE TITLE
[Build 1391/1394] Clicking on the Transfer Button Doesn't work When No Units are Transferring

### ISSUE THREAD

**Issue by Mustang-25** [dcs-liberation/dcs_liberation#1006]
Clicking the Transfer button in the misc section of the info bar does not open a window and generates the error shown in the pic below:

![image](https://user-images.githubusercontent.com/72566076/115603261-cb9f3400-a294-11eb-9553-3006d09d7f90.png)

This occurs at Turn 0 and Turn 1 after units have already been purchased. From Turn 2 and onwards, the menu does seem to work and you can see that units are transferring. We infer from this that the menu will not open when there are no transfers actively occurring.

Expected behavior would be to produce a menu even if there are no transfers pending and it's blank.

**Comment by Hornet2041** [comment]
works in #1394 tho

**Comment by Mustang-25** [comment]
> works in #1394 tho

negative, it does not for me.

**Comment by Hornet2041** [comment]
seems to be a campaign issue. works fine in Peace Spring by Starfire <_<

**Comment by Mustang-25** [comment]
After more testing, @Hornet2041 can also reproduce this in build 1394 with the Inherent Resolve campaign but his Peace Spring campaign does show that menu in turn 3 when units are being transferred. My own attempt at starting the Peace Spring campaign produces the same error so it seems to occur only when there are no units being transferred during that particular turn.

**Comment by Hornet2041** [comment]
hmmmmmmmmmmmmm D:

**Comment by Hornet2041** [comment]
looks like it will generate that error when the AI/player does not have any departing convoys

**Comment by DanAlbert** [comment]
Fixed. Accidentally removed a check when I was cleaning something up. It's back now.
