### ISSUE TITLE
Splash damage script deprecated

### ISSUE THREAD

**Issue by LazyBoot** [dcs-liberation/dcs_liberation#1009]
The "new" splash damage script in the latest release has been deprecated... Should probably use the new replacement instead

https://github.com/wheelyjoe/DCS-Scripts

**Comment by Starfire13** [comment]
Updated the files:
[splashdamage.zip](https://github.com/Khopa/dcs_liberation/files/6354767/splashdamage.zip)

**Comment by DanAlbert** [comment]
Was merged to develop.
