### ISSUE TITLE
Cold start problems it forces me to start in air

### ISSUE THREAD

**Issue by ToKeNeRd** [dcs-liberation/dcs_liberation#101]

**Comment by Meyomyx** [comment]
Agreed - Syrian campaign - Turkish Invasion from the Abe Lincoln - all units air start. If you go back to the Liberation Mission Planner, the menu option has changed to "air". 2.1.0

**Comment by Khopa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Big issue with air start in current version](https://trello.com/c/TKLptLE5/131-big-issue-with-air-start-in-current-version)

**Comment by Meyomyx** [comment]
I'm simply changing the start behaviour in the mission editor (before I fly) as a workaround

**Comment by DanAlbert** [comment]
Mostly fixed in 2.1.1. It will still happen if you have more aircraft assigned to take off at a given airfield than it has room for though.

**Comment by davidp57** [comment]
Yes, I confirm, fixed in 2.1.1
