### ISSUE TITLE
Campaign picked more distant EWR to be CP EWR

### ISSUE THREAD

**Issue by Hornet2041** [dcs-liberation/dcs_liberation#1011]
Build 1394, planner generated a strike and DEAD mission against a sole EWR site. The unit exists in-game as evidenced by the .miz file but Liberation shows no icon on its' campaign map.

![image](https://user-images.githubusercontent.com/55866858/115644718-0b920580-a2ed-11eb-8072-fb45a16b8849.png)
[peace spring frog not a target.zip](https://github.com/Khopa/dcs_liberation/files/6354967/peace.spring.frog.not.a.target.zip)

**Comment by Hornet2041** [comment]
from discord: 

"So it looks to me like it has taken the EWR I placed for the CP as an extra EWR. You can see the icon practically on top of the CP.
And taken the one I placed further away as the CP's EWR."

https://discord.com/channels/595702951800995872/782361390954053643/834610559432261693

**Comment by DanAlbert** [comment]
Was fixed in 2.5.1.
