### ISSUE TITLE
Bullseye on kneeboard

### ISSUE THREAD

**Issue by jojom4n** [dcs-liberation/dcs_liberation#1014]
I think it would be really useful to have bullseye coordinates on kneeboard, without having to look for BE on F10 map.

**Comment by DanAlbert** [comment]
Not really doable. All we have is X/Y and we don't have the projection parameters to convert that to anything you can use.

**Comment by DanAlbert** [comment]
I found a way to infer what we needed for the other maps, so this is possible now.

**Comment by jojom4n** [comment]
Great! Thank you very much!
