### ISSUE TITLE
Catapult issue

### ISSUE THREAD

**Issue by Ryanwtod** [dcs-liberation/dcs_liberation#1017]
I was using the DCS Liberation just now. I noticed something. I don't know if it's a Liberation issue or a DCS issue. If you have more than 1 Tomcat in the same flight they won't both setup on CAT 1 and 2 at the same time. The first one will setup on Cat 1. The second one will park behind Cat 2 and wait until the first one launches before he approaches the second cat and hooks up. Aircraft should be able to setup and hook up to Cat 1 and Cat 2 at the same time. I am currently using 2.5. The F-14s could hook up to Cat 1 and Cat 2 at the same time in 2.4. Again unsure if it maybe a DCS issue or not

**Comment by DanAlbert** [comment]
We have no control over taxi behavior.
