### ISSUE TITLE
[Build 1405] Campaign Creation - No Factories at FOBs

### ISSUE THREAD

**Issue by Mustang-25** [dcs-liberation/dcs_liberation#1021]
Placing Workshop A's at FOBs will not generate a factory for the new logistics system (placing them by Airfields works though). Campaign miz attached for reference. 

[Factories at FOB campaign.zip](https://github.com/Khopa/dcs_liberation/files/6366280/Factories.at.FOB.campaign.zip)

**Comment by DanAlbert** [comment]
https://github.com/dcs-liberation/dcs_liberation/pull/1077 would fix this, but want @walterroach to weigh in since it looks like the limitation may have been intentional.

**Comment by walterroach** [comment]
I believe the only reason for giving `FobDefenseGenerator` a different `generate` method than `BaseDefenseGenerator` was to prevent random long range SAM generation from being triggered by a FOB.

Adding factories to it should be fine.
