### ISSUE TITLE
Unable to select APKWS with A10C II

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#1023]
**Describe the bug**
Within the custom payload menu of Liberation for `A10C Thunderbolt II (Suite 7)`, there is no option to choose APKWS rockets.

**To Reproduce**
1. Purchase `A10C Thunderbolt II (Suite 7)` at any airfiled.
2. Plan a flight for the plane
3. Make a custom payload for A10C II.
4. Confirm unable to select guided rockets.  (APKWS)

**Expected behavior**
APKWS rockets should be available for A10C II.

**Additional information**

Used converted campaign from 2.5 preview to 2.5.0.

**Version information (please complete the following information):**
 - DCS Liberation 2.5.0.

**Comment by DanAlbert** [comment]
Works now.
