### ISSUE TITLE
F-18 OCA/Aircraft and BAI should have a fuel tank.

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#1024]
**Is your feature request related to a problem? Please describe.**
`USA 2005` F-18 `BAI` and `OCA/Aircraft` loadouts do not have any fuel tanks.  This may lead to AI running out of fuel.

**Describe the solution you'd like**
Replace the empty center slot of the default BAI + OCA/Aircraft loadout with a fuel tank.

**Comment by DanAlbert** [comment]
I redid a bunch of hornet loadouts in 3.0 and the CAS loadout (which BAI and OCA/Aircraft fall back to since they aren't specialized) has one bag now.
