### ISSUE TITLE
Exiting the Airbase screen before saving mission package disables those assigned aircraft from being used that turn

### ISSUE THREAD

**Issue by Hornet2041** [dcs-liberation/dcs_liberation#1027]
Before filing, please search the issue tracker to see if the issue has already been reported.

**Describe the bug**
Exiting the airbase screen before saving a package with aircraft assigned to it hides? disables? the aircraft from being used in that mission, as in you cannot select it in dropdown lists or sell them - Liberation thinks they're assigned.

**To Reproduce**
Open airbase menu.
Create a package to attack the airfield
Select all available aircraft for a mission
Immediately close the airbase screen without saving the mission
Observe that the aircraft are no longer selectable for anything

**Additional information**
build 1428

[syriaslyborked.zip](https://github.com/Khopa/dcs_liberation/files/6368951/syriaslyborked.zip)
[peacespring.zip](https://github.com/Khopa/dcs_liberation/files/6368953/peacespring.zip)
campaign attached if you need that too

**Comment by DanAlbert** [comment]
Fixing this elegantly would be a pain, so for now the new package dialog is modal to avoid it being destroyed in strange ways.
