### ISSUE TITLE
[Build 1437] Unit Transfers in Pending Transfer Window but not shown in Departing Convoys Window or Miz Itself

### ISSUE THREAD

**Issue by Mustang-25** [dcs-liberation/dcs_liberation#1030]
The unit transfer system seems to only be occurring behind the scenes within Liberation. The units that are supposed to convoy are not generated in the miz or shown in the departing convoy window of the departing CP. I can confirm though that passing the turn will reinforce the frontline with the correct amount of units that were transferring.

Miz and Liberation save attached.

![image](https://user-images.githubusercontent.com/72566076/115971573-03f57b00-a4fe-11eb-9845-0ddc1e8da703.png)

[Transfers Not Generating.zip](https://github.com/Khopa/dcs_liberation/files/6370557/Transfers.Not.Generating.zip)

**Comment by DanAlbert** [comment]
Fixed by https://github.com/Khopa/dcs_liberation/commit/17751e52fd6253910660d0935fb0c8a5989ede86. I'd tested pretty heavily but I guess I didn't retest this part after one last cleanup :(
