### ISSUE TITLE
Purchase from airfield allows negative budget

### ISSUE THREAD

**Issue by HerrTom** [dcs-liberation/dcs_liberation#1032]
**Describe the bug**
The available budget does not actually limit the player from buying vehicles and aircraft from airfields.

**To Reproduce**
1. Open an airfield
2. Purchase units until you don't have enough budget left to continue buying
3. Buy more anyway
4. Budget will go negative
5. Pass Turn or Take Off will still allow mission to be flown.

**Expected behavior**
Available budget should limit the player's purchases.

**Additional information**

N/A

**Version information (please complete the following information):**
 - Version 3.0 preview build 1445

**Comment by DanAlbert** [comment]
https://github.com/Khopa/dcs_liberation/pull/1042 fixes this. Thanks @alrik11es!

**Comment by Hornet2041** [comment]
re-appeared in build #1470

**Comment by Hornet2041** [comment]
Bug fixed as of build #1507

**Comment by DanAlbert** [comment]
Interesting, because we've done nothing to address this between when you said it reappeared and now... Any chance you were accidentally _not_ on build 1470 when you saw the bug reappear? Wondering if this is just flaky, somehow.

**Comment by Hornet2041** [comment]
> Interesting, because we've done nothing to address this between when you said it reappeared and now... Any chance you were accidentally _not_ on build 1470 when you saw the bug reappear? Wondering if this is just flaky, somehow.

Aha. I did some more testing on both build 1470 and 1507. 
Only **front-line units** can be purchased over-budget. Aircraft on both can not. 

![image](https://user-images.githubusercontent.com/55866858/117856167-4981aa00-b259-11eb-9e20-bc8556ee9c19.png)
