### ISSUE TITLE
Have a way to restrict the type of aircraft that can be bought at a CP

### ISSUE THREAD

**Issue by Moguy164** [dcs-liberation/dcs_liberation#1038]
Before filing, please search the issue tracker to see if this feature has already been requested.

**Is your feature request related to a problem? Please describe.**
I'd like to use the islands in the PG as a helo-only base since that's what they'd realistically be used for, especially with their proximity to the mainland however if I make it a normal airbase then fighters can be bought there that would best be left for other locations

**Describe the solution you'd like**
have a way to restrict the type of aircraft that can be bought, for example placing a Huey would restrict it to Helos only, placing a F-16 would restrict it to long range fighters as well, placing a A-10 would limit it to the purebred ground attackers and so on
**Additional context**

**Comment by DanAlbert** [comment]
Was thinking about this myself recently because it looks like a _lot_ of the airports won't let a cargo plane park there (at least for Syria that was the case). Given that DCS is able to reject the thing there, we probably can surface that data and use it.

It won't be perfect because this is actually a parking space by parking space thing and that's just not practical, but we can at least rule out airports that have _no_ parking for certain types.

(https://github.com/Khopa/dcs_liberation/issues/1018, by the way)

**Comment by DanAlbert** [comment]
Looks like we have pretty fine grained data from pydcs: https://github.com/pydcs/dcs/blob/84247a9fa108174b4f9696136a413d53cee23533/dcs/terrain/syria.py#L18-L20

We can pretty easily disallow whole types based on the base having _no_ compatible parking.

I'm guessing a follow up question here is whether or not we could use the individual parking data to limit bases to certain amounts for specific aircraft types (i.e. only 2 cargo planes, but as many helicopters as you want). That's a much larger task. It's theoretically doable but the benefit/cost ratio is quite a bit lower. Not going to consider that within scope here.

**Comment by DanAlbert** [comment]
On the other hand not a single parking space in any map sets `large=True` or `shelter=True`, so those properties are useless. I think this is still useful for identifying heliports vs real airports but it's useless for determining if a cargo plane can park there, or where we should avoid spawning F-14s.

Given that, this is just a dup of #1018. Duping that over here though since I've dumped the detail into this one.

> placing a F-16 would restrict it to long range fighters as well, placing a A-10 would limit it to the purebred ground attackers and so on

This seems unnecessarily restrictive on players.

**Comment by Moguy164** [comment]
> This seems unnecessarily restrictive on players

I mean for this to be a way for the campaign designer to restrict what type of aircraft could be placed at an airfield. (should note that in this system you'd be able  to group multiple types at the same airfield)

**Comment by DanAlbert** [comment]
I guess I don't understand how what you're proposing would work. I don't see how restricting an airfield to operate only A-10s when it's perfectly capable of operating an F-18 or F-14 makes the game any better.

**Comment by Moguy164** [comment]
> I guess I don't understand how what you're proposing would work. I don't see how restricting an airfield to operate only A-10s when it's perfectly capable of operating an F-18 or F-14 makes the game any better.

say for example there are two airfields, airfield A which is much closer to the front line and Airfield B which is futher away, if both were capable of spawning both types of aircraft then one would F-18s there because it's closer to target, but that may not be the best or most realistic approach since it would cluster everything together so maybe the campaign designer could want to restrict it to CAS planes only. alternatively you could lock which types of missions an aircraft taking off from so and so airfield can do

**Comment by DanAlbert** [comment]
But the front line isn't static, so once either coalition progresses the airbase closest to the front stops being A-10s and starts being F-14s.

I think I hear what you're saying: it'd be good to have a reason to use more than a single airbase, or possibly just that airbases farther back from the front ought to be used. I'm on board with both, but I don't think flagging airbases as ground attack only or interceptor only accomplished that in a way that isn't frustrating for players.

I'm digressing pretty far from the core of the report here, but I think you'd be interested in https://github.com/Khopa/dcs_liberation/issues/276 (where we could limit the number of squadrons that each base can host). @Malakhit and I were also talking about maybe having maintenance limits on airbases, so regardless of how many aircraft can park there, the crews can only turn around so many used aircraft each turn.

Am I on the right track here, or did I misunderstand?

**Comment by Moguy164** [comment]
> Am I on the right track here, or did I misunderstand?

pretty much, i'd like to have a reason to use more then one base or further away bases and stop the clustering that often happens in liberation campaigns, for the clustering it _could_ be fixed by using FOBs instead of airfields but i for example would still like to spawn helos there, but not larger aircraft

**Comment by Hornet2041** [comment]
#1078 seems like in Syria at least needs some restrictions to prevent airplanes spawning and blowing up at these airfields

**Comment by Metal-121** [comment]
Restrictions like this should not be in the core, I see it is a campaign strart implement. Maintanance restriction... no t in the core. If I choose to play with a high tech faction with plenty of personal, or a low tech poor faction it should be set then and there not in the core where it will add restrictions into the mission that some just don't wan't. Realism is a very personal thing and how and why is not to be controled in the core. Then it stray away from the freedom of creation that make this so good.

**Comment by Starfire13** [comment]
> Restrictions like this should not be in the core

This feature request is obsolete anyway considering we now have squadrons and FARPs.
