### ISSUE TITLE
AMRAAMs being assinged on "None" pylons on F-15C

### ISSUE THREAD

**Issue by JeffreyCor** [dcs-liberation/dcs_liberation#1039]
Trying with weapons restricted by date on, in 1984 campaign, the loadout on the F-15C has "None" for points 3 and 9. However, in the actual mission AIM-120Cs are on both points. Oddest part I think is missiles being put on the points that were set to None in the flight editor.Before filing, please search the issue tracker to see if the issue has already been reported.

**To Reproduce**
(Unsure if all steps are needed)
Have a campaign with weapons restricted by date and in a pre-AMRAAM campaign date:
Purchase and have available F-15C to assign a flight
Set up F-15C flight of any A2A type. Default loadout has pylons 3 and 9 listed as "None"
Go into DCS
Check F-15C flight loadout (Flying the plane or view in mission editor)
Pylons 3 and 9 will have AIM-120C loaded on them

**Expected behavior**
Would expect pylons 3 and 9 to be empty as listed in the Liberation flight editor 

**Additional information**

[F-15C loadout error.zip](https://github.com/Khopa/dcs_liberation/files/6381736/F-15C.loadout.error.zip)

[liberation_nextturn.zip](https://github.com/Khopa/dcs_liberation/files/6381744/liberation_nextturn.zip)

**Version information (please complete the following information):**
 - DCS Liberation v2.5-1389, DCS v.2.7.0.5118

**Comment by DanAlbert** [comment]
Fixed now. I redid the loadout system the other night, so probably fixed it then?

**Comment by JeffreyCor** [comment]
Sounds like that should do it :) when it comes out if the problem comes up I'll be sure to post about it.
