### ISSUE TITLE
[Build 1459] Naval Strike Targets Attached to Carriers/LHAs not Generating

### ISSUE THREAD

**Issue by Mustang-25** [dcs-liberation/dcs_liberation#1040]
**Describe the bug**

Naval strike targets are not generating when they are associated with a Carrier or LHA. Naval targets that are attached to land-based CPs, however, will generate as expected.

**To Reproduce**

Pick any up-to-date campaign, verify in the ME that a CJTF Blue Arleigh Burke is placed next to a carrier, generate that campaign and note that there are no strike targets spawned near the carriers.

**Expected behavior**
Placing a CJTF Blue Arleigh Burke in the campaign miz should generate naval strike targets when associated with carrier CPs.

**Comment by DanAlbert** [comment]
Doesn't appear to be a problem any more.
