### ISSUE TITLE
AI Strike on Factory only target one building

### ISSUE THREAD

**Issue by Qiou87** [dcs-liberation/dcs_liberation#1046]
When setting up an AI strike flight on an enemy target, only the first building gets hit. For example the factory which features 4 buildings, only one building (main) will be hit, the remaining 3 are not targeted.

I tried with F-16s and F-15Es, both with standard loadout or custom (LGBs, Mavericks...). In all cases, AI does not engage the remaining building.

Those missions are therefore quite useless: 4x 10M$ for a factory, if they only destroy 1 building it is still generating 30M$ per turn after the strike.

On the next turn, a new strike will still hit the first (destroyed) building. The are still not attacking the other 3 buildings.

If I assign the strike to a player flight, I do get 4 waypoints (one of each building). My wingman will behave it the same way as other AI and only engage the main building, regardless if it is damaged/destroyed or not.

AI strike flights on a building group (like factory, petrol tanks...) should try and destroy all buildings. At least for the factory, this is not happening right now (2.7.0.5118).

**Comment by Starfire13** [comment]
This is a known issue and is due to mission editor limitations when targeting structures rather than unit groups. The AI isn't smart enough to know how to drop one bomb on each waypoint. It'll drop them all on the first one.

**Comment by DanAlbert** [comment]
Duplicate.
