### ISSUE TITLE
supercarrier deck crew ignores client aircraft after cold start

### ISSUE THREAD

**Issue by HILOK** [dcs-liberation/dcs_liberation#1047]
**Describe the bug**
deck crew fails to react to client aircraft on SC after a cold start. also AI wingmen dont start taxi after client aircraft does. all this use to work fine before DCS 2.7 + LIB 2.5 combo. "request launch" command doesnt solve the issue.

**To Reproduce**
1. load attached .liberation file
2. click on 'take-off' & start mission
3. do your cold start
4. observe situation as described above

**Expected behavior**
wingmen & deck crew react correctly to client (start taxi & prepare cat launch), as soon as he starts to taxi on the deck or approaches one of the cats

**Additional information**
~~no issues when warm starting;~~
also in this context: tower called me ford23, where my allocated callsign was pontiac11

We will usually need more information for debugging. Include as much of the following as you are able:
- DCS Liberation save file
- The generated mission file
- The state.json file from before mission start

**Version information (please complete the following information):**
 - DCS Liberation 2.5

**Additional context**
cold start, hornet, SC, syria, invasion of turkey, 1995

[attached files.zip](https://github.com/Khopa/dcs_liberation/files/6405870/attached.files.zip)

**Comment by Ryanwtod** [comment]
There is a thread in the ED Forums regarding Supercarrier deck/cat issues. unsure if it's related

**Comment by renehasp** [comment]
We are experiencing the same thing. Can't take off from the carrier after 2.7 with liberation.

**Comment by HILOK** [comment]
@Ryanwtod thanks! it's probably the one i looked up already. however, don't think it's related to this, because i didn't change my routine between dcs2.5/lib2.4 and the new versions. this issue never occured to me outside liberation. also warm start solves the issue. additionally, when i call for startup, tower (carrier) replies using the wrong callsign (ford23 instead pontiac11).

i am suspecting it has to do with the liberation scripts running in background, maybe the "never delay player flights" option. but i leave that for the experts here to decide.

**Comment by DanAlbert** [comment]
> this issue never occured to me outside liberation. also warm start solves the issue.

I've seen this in other missions (round table, iirc), and in Liberation with warm start.

> i am suspecting it has to do with the liberation scripts running in background, maybe the "never delay player flights" option. but i leave that for the experts here to decide.

The only thing our lua scripts do is listen for death/capture events and record them to a file. "Never delay" only decides whether or not player slots get the late activation/uncontrolled checkbox from the ME. There's no scripting involved.

**Comment by HILOK** [comment]
yep, warm start unfortunately only resolves the issue about 50% of the time.

what i can add though, is that my whole package won't move on the carrier deck. just took off dirty using the whole deck to see, if that would trigger wingman or escort, but no...they were just holding on the deck with their engines running. after some time though, about 40 min past planned take-off time, they all of a sudden decided to finally get airborne.

what made me think there would be scripts involved is that anytime i start a liberation mission without liberation GUI running in background, i get lots of error messages.

**Comment by HILOK** [comment]
@renehasp is this also happening to you on syria?

**Comment by DanAlbert** [comment]
It's very unlikely that this is a liberation bug. We have no control over minute AI behavior like this.

**Comment by HILOK** [comment]
ok. if anyone knows a remedy to this, it would be highly appreciated : )

**Comment by Hornet2041** [comment]
This is a DCS bug. Suggest you set supercarrier AI flights to spawn airborne.

**Comment by renehasp** [comment]
> @renehasp is this also happening to you on syria?

Yes, this happens on the Syria map.

**Comment by HILOK** [comment]
what seems to work is to make sure any other flights spawn on the deck after you first move your aircraft, even just a few centimeters.
more on this here https://forums.eagle.ru/topic/254020-carrier-crew-ignores-new-aircraft-taxing-to-catapult/?tab=comments#comment-4653605
