### ISSUE TITLE
Vegas/NTTR

### ISSUE THREAD

**Issue by Ryanwtod** [dcs-liberation/dcs_liberation#1048]
Before filing, please search the issue tracker to see if this feature has already been requested.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by Ryanwtod** [comment]
I apologize for the bad layout here. I didn't format this well. Would it be able to get a new bigger campaign for the Vegas map? I also liked  the old campaign that was replaced by the current one? Can that be added back again?

**Comment by DanAlbert** [comment]
You can make your own campaigns: https://github.com/Khopa/dcs_liberation/wiki/Custom-Campaigns
