### ISSUE TITLE
Preview builds #1466 and #1468 crashing on launch

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#1049]
**Describe the bug**
Liberation crashes to desktop with the following error in at least #1466 and #1468. Works fine in #1458.

![Untitled](https://user-images.githubusercontent.com/72491792/116771628-6c110780-aa90-11eb-85b3-a2f852f1fdae.png)

**Expected behavior**
No crashy crashy

**Comment by DanAlbert** [comment]
Looks like a break in one of our dependencies rather than something we did... Will need to fix either way.

**Comment by Starfire13** [comment]
I just tested each build starting from the latest one. Looks like #1459 is the last build that runs fine.
