### ISSUE TITLE
Add a slider or multiplier for amount of smoke on frontline

### ISSUE THREAD

**Issue by NeelKulkarni6** [dcs-liberation/dcs_liberation#1050]
The smoke on the frontline is one of the prettiest parts of liberation imo, as it makes the theater's combat seem more authentic and real. It's also a big performance hog (10-20% on my machine). I think a slider/multiplier setting (similar to the income slider) for the amount of smoke there is on the front line could be very useful. 

In the mission editor I always notice there's a lot of smoke effects, If i remove 50% of them I gain ~10% higher framerate and it still looks good and 'like a combat theater'.

**Comment by Mustang-25** [comment]
+1 for this! I love the smoke but I hate the impact on my frames.

**Comment by Khopa** [comment]
Thanks.

I added a new parameter in performance settings, on develop branch : 

![image](https://user-images.githubusercontent.com/2546901/117439269-f34bf880-af32-11eb-9f80-4a9943734d85.png)


Examples below : 

![image](https://user-images.githubusercontent.com/2546901/117439312-fcd56080-af32-11eb-930a-90660705ee59.png)

*(800 was the previous default value, new default value for campaigns will be 1600)*

![image](https://user-images.githubusercontent.com/2546901/117439560-46be4680-af33-11eb-82c3-d8ab27e4b5b1.png)

![image](https://user-images.githubusercontent.com/2546901/117439579-4de55480-af33-11eb-99a2-fad9ac9b4dc3.png)

**Comment by NeelKulkarni6** [comment]
looks good thanks
