### ISSUE TITLE
Aircraft Spawning on top of eachother

### ISSUE THREAD

**Issue by Ryanwtod** [dcs-liberation/dcs_liberation#1052]
Using DCS 2.7 and the current DCS Liberation I've set the player aircraft and wingman as F/A-18s at Incirlick in the Invasion from Turkey campaign. In multiple different attempts both the player and wingman spawn in the same location which causes both aircraft to be destroyed on the ground in an explosion. Aircraft should spawn separately and not explode.

[Airpor BAI.zip](https://github.com/Khopa/dcs_liberation/files/6410001/Airpor.BAI.zip)

**Comment by Mustang-25** [comment]
Which flight/which parking spot does this occur and does it consistently happen at that spot?

**Comment by DanAlbert** [comment]
Both slots were assigned parking space 122. The data uploaded only includes a track file, so nothing I can do to investigate.

**Comment by CptBean** [comment]
I know it's closed but I've had the same issue. And it appears there are two parking spots with number 121 and 122 on Incirlik, so that's probably why.

<img width="630" alt="Knipsel" src="https://user-images.githubusercontent.com/3929399/125462761-001f8255-56c2-4013-9187-344a60bf673b.PNG">

**Comment by DanAlbert** [comment]
That's a map bug then. Nothing we can do, you need to report it to Ugra.
