### ISSUE TITLE
Slider for weather

### ISSUE THREAD

**Issue by Ryanwtod** [dcs-liberation/dcs_liberation#1054]
Would some sort of slider or other toggle be available for the weather in a campaign? The clouds are wonderful and it's awesome to get some weather variables. Maybe it's just me but it always seems to pouring rain with very low visibility. This makes it very difficult to fly some aircraft and employ some of the weapons. Some bad weather is great but a partly cloudy or sunny day is nice too.

**Comment by Mustang-25** [comment]
The weather generation gives you a 20:101 chance of rain. You might just be getting unlucky with your weather. You can manually change the percentages in the weather.py file if you want it to favor more clear days.

**Comment by HILOK** [comment]
@Ryanwtod i had this happening occasionally too, 2 or 3 days of rain, but be assured it's definitely just temporary. personally i find it adds a certain charm to the campaign : )

**Comment by HILOK** [comment]
have to agree with #1066 though: it might not be realistic during every season depending on map. here's an example for syria (weatherspark.com) -just had 3 rainy days in june... : )
![E5078245-CC18-4030-A60D-D2648508AF4F](https://user-images.githubusercontent.com/76898536/118089221-6be60580-b3c8-11eb-95a7-f3de98e09f77.jpeg)

**Comment by magwo** [comment]
Here is a beginning for supporting theater-and-season based random weather:
https://github.com/dcs-liberation/dcs_liberation/pull/1428

When that code is enhanced with theater/seasonal pressure/temperature characteristics, it would become quite natural to also add theater/seasonal rain/clouds variations.

**Comment by magwo** [comment]
https://github.com/dcs-liberation/dcs_liberation/pull/1438

**Comment by atom1285** [comment]
> The weather generation gives you a 20:101 chance of rain. You might just be getting unlucky with your weather. You can manually change the percentages in the weather.py file if you want it to favor more clear days.

Hi, where can I please find the weather.py file? Or can I adjust the weather somewhere else? Thanks a lot! Amazing work on this app!

**Comment by Starfire13** [comment]
> Hi, where can I please find the weather.py file? Or can I adjust the weather somewhere else? Thanks a lot! Amazing work on this app!

https://github.com/dcs-liberation/dcs_liberation/blob/develop/game/weather.py

Also, old closed FRs is hardly the place to ask such questions. I suggest doing so on Discord.

**Comment by atom1285** [comment]
> > Hi, where can I please find the weather.py file? Or can I adjust the weather somewhere else? Thanks a lot! Amazing work on this app!
> 
> https://github.com/dcs-liberation/dcs_liberation/blob/develop/game/weather.py
> 
> Also, old closed FRs is hardly the place to ask such questions. I suggest doing so on Discord.

Thanks. But where can I find the file in liberation installation folder on my PC,  so I can replace it.
Yeah, will ask on discord next time.
