### ISSUE TITLE
Special character 'Ş' or 'ş' breaks state.json reading

### ISSUE THREAD

**Issue by ccuh** [dcs-liberation/dcs_liberation#1055]
Give a flight a custom name that includes the letter Ş or ş or both. This character exists in Romanian and Turkish alphabets. We had a flight with a custom name called "Şimşek". The mission had no problem, the state.json file was saved correctly with that letter. Reading the state.json file was giving an error. The results did not show up. Then I checked the error log from the terminal. The problem was with Ş character. Then I opened the state.json, changed the letter to S, then manually submit the state.json file. Everything worked fine.

You may want to add extra support for special characters in state.json reader. ISO/IEC 8859-9 is the standard I guess.

**Comment by DanAlbert** [comment]
We need the files that the bug template asks for.

**Comment by RndName** [comment]
When some one is working on it also look into #1774

**Comment by RndName** [comment]
Could be potentially fixed already by #1538

**Comment by RndName** [comment]
Made a short test with `"Şimşek|80|5|30|F-16CM Fighting Falcon (Block 50)| Pilot #1"` which was recognized correctly when submitting the state.json with **V5** which has the fix mentioned above. Closing this for now.
