### ISSUE TITLE
Customise mission length

### ISSUE THREAD

**Issue by Schneefl0cke** [dcs-liberation/dcs_liberation#1056]
Currently the mission length is set hard to 90 minutes. Some players take longer or less time.

Missions, especially BARCAP is planned for 90 minutes of playtime. This means, that after 90 minutes there is no more opposition and if someone finishes a mission in 60 minutes, the ai has less planes for different tasks.

One way to solve this issue would be, that a user can provide an estimated mission time (default can stay 90 minutes).
Missions from the ai are then planned with this time schedule.

**Comment by DanAlbert** [comment]
Merged into 3.0.
