### ISSUE TITLE
Rearm Vehicles + Vehicles locations

### ISSUE THREAD

**Issue by VAGGOSST** [dcs-liberation/dcs_liberation#1060]
Hello.

I am =GR= Spanker form [LockOn Greece - DCS World Greece](https://lockon-greece.forumotion.net/)
We have started playing as a Squadron and we have noticed a couple of things that are important in our opion.

1. At SAM locations and at ground units (groups) there are not any ammo-resupply vehicles with the result once the SAM or ground units are out of ammo that is that..We thing it is a key feature SAMs & ground groups to be able to resupply..Also we have notince a couple of bases to have that problem (maybe the coalition to be set was forgotten.Once we reproduce we will make another report)
2. Especially in Caucasus the units of quite a few groups are set or start within a forest (pic attached)
![Screen_210506_200904](https://user-images.githubusercontent.com/31065901/117353884-5f8a1600-aeb9-11eb-8c0c-54aef0d580cc.png)

Looking forward for your answer!

**Comment by Hornet2041** [comment]
1) There is a feature request open for this already here:

https://github.com/dcs-liberation/dcs_liberation/issues/429

2) sounds like the problem described here https://github.com/dcs-liberation/dcs_liberation/issues/638 . possibly the campaign needs to be updated for current campaign design methods?

**Comment by DanAlbert** [comment]
Closing because this is a campaign bug with random spawn locations. Those don't exist any more.
