### ISSUE TITLE
Change the Probability of Rain depending on the Map

### ISSUE THREAD

**Issue by NeelKulkarni6** [dcs-liberation/dcs_liberation#1066]
I heard on the discord that the probability of rain/heavy clouds is something like 3/10 or 4/10. I think on Maps like PG, Nevada, and even Syria this should be much lower. I feel like I'm getting too many missions where its raining in PG map which doesn't make sense because its a desert.  

Also sorry if its already a thing

**Comment by ThatOneguyC6** [comment]
Also sorry if its already a thing

**Comment by alcmann** [comment]
Like this !,  Very rarely it seems on any playthrough , any VFR turns seem to be rare .  Constant tweaking of weather is needed.

**Comment by magwo** [comment]
+1 from me! Way too much rain + clouds on Syria.

**Comment by magwo** [comment]
Here is a beginning for supporting theater-and-season based random weather:
#1428

When that code is enhanced with theater/seasonal pressure/temperature characteristics, it would become quite natural to also add theater/seasonal rain/clouds variations.

**Comment by magwo** [comment]
This PR should close this issue :) https://github.com/dcs-liberation/dcs_liberation/pull/1438
