### ISSUE TITLE
front line bounds shown in liberation are not accurate

### ISSUE THREAD

**Issue by Hornet2041** [dcs-liberation/dcs_liberation#1067]
Before filing, please search the issue tracker to see if the issue has already been reported.

**Describe the bug**
The actual ingame frontline that is spawned is set completely different than what is shown on the campaign map.

**To Reproduce**
1) Play Operation Peace Spring campaign as inverted, starting from Turkey
2) Advance frontline enough so that it gets close to the FARP/strike object near Gaziantep
3) Observe any frontline shenanigans occurring

**Expected behavior**
For the in-game frontline to appear where the marked frontline is.

**Additional information**
[frontlineconfusion.zip](https://github.com/dcs-liberation/dcs_liberation/files/6445288/frontlineconfusion.zip)
.lib and .miz attached.
Also, see screenshots demonstrating error:

![lib bug 1](https://user-images.githubusercontent.com/55866858/117528132-a3a31680-af9e-11eb-8378-9444c6f2a95d.jpg)
![lib bug 2](https://user-images.githubusercontent.com/55866858/117528136-a69e0700-af9e-11eb-8a81-b3fd73750df4.jpg)
![lib bug 3](https://user-images.githubusercontent.com/55866858/117528138-a867ca80-af9e-11eb-80b5-05e5944b8301.jpg)

As you can see, the marked frontline is out of the map exclusion zone, so I don't know whats going on here...

**Version information (please complete the following information):**
Build #1495

**Comment by DanAlbert** [comment]
The line drawn on the map is curved to make it not ugly as hell. It doesn't represent the actual path. The bar for the front line is accurate as long as "Display actual frontline location" is used.

I suspect this campaign has actually driven the path through that exclusion zone though.

**Comment by Hornet2041** [comment]
Display actual frontline location **_is_** on in those pictures though

**Comment by Hornet2041** [comment]
![image](https://user-images.githubusercontent.com/55866858/117529244-84a78300-afa4-11eb-9461-5f11357b22e8.png)
Additionally, AI missions are planned around where the campaign says the frontline is, but unfortunately in DCS, the front line is not there D:

**Comment by DanAlbert** [comment]
Actually iirc it's only semi-accurate (and that's why there's another option that is the default). If the front line is split it will only show one of the splits.

**Comment by DanAlbert** [comment]
@walterroach this is the behavior we regret but expect, right?

**Comment by walterroach** [comment]
The display can end up weird when the frontline is driving right through an exclusion zone, but the flight plans should always end up in the same spot as the units.  I'm pretty sure I prevented splitting the frontline to each side of an exclusion zone to prevent this issue. 

It looks to me like the result of `Conflict.frontline_vector` was different for the ground unit spawns than it was for the flight plans; which is a bug.

**Comment by DanAlbert** [comment]
@Hornet2041 any idea if this is a regression? I made some changes to the data structure that backs front lines in that build, but it should have been behavior preserving aside from the bugs I fixed.

**Comment by Hornet2041** [comment]
Not sure if you meant to ping me but the turn previous to the one i posted above, the frontline managed to squeeze itself successfully in that super narrow corridor just a bit to the west of the buggy one.

**Comment by DanAlbert** [comment]
The current generation of this bug is that we just show an arbitrary 4NM line rather than computing the bounds: https://github.com/dcs-liberation/dcs_liberation/blob/c4358daccc16d092d6c9528322647704b485ecb4/game/server/frontlines/models.py#L25-L33

The ugliness of how front line data was stored (or rather wasn't) was fixed a while back though so this should be pretty easy to solve now.
