### ISSUE TITLE
Unit Transfer System UI Improvements

### ISSUE THREAD

**Issue by Mustang-25** [dcs-liberation/dcs_liberation#1069]
After playing with the new logistics system for a number of turns I have a couple UI suggestions that I think can improve the system:

1. Differentiate blue and red transfers in the transfer menu
2. Choose a more prominent icon for the factories or otherwise make more obvious that a CP has a factory attached to it
3. Move transfer units from bottom of CP window to place it next to the units breakdown at the top and/or at least change the color of the button to make it more prominent.

**Comment by DanAlbert** [comment]
Re 3, do you actually find yourself creating them manually often?

**Comment by Mustang-25** [comment]
I haven't yet. But that being said, I didn't even see that button existed until turn 2 or 3.

**Comment by DanAlbert** [comment]
A bit more obvious than that may be worthwhile. I honestly don't expect people to need it often since purchases auto transfer, but there will be time's that it's needed. Color change is probably the way to go.

**Comment by DanAlbert** [comment]
1 and 3 fixed. 2 obviously needs some work, since every icon is just a map pin atm :)

**Comment by DanAlbert** [comment]
The subtypes of TGOs (to an extent) can now be independently toggled on and off, so it's easy to show _only_ factories.
