### ISSUE TITLE
add F-4E to list of CAS-capable planes for Liberation

### ISSUE THREAD

**Issue by Hornet2041** [dcs-liberation/dcs_liberation#1072]
Before filing, please search the issue tracker to see if this feature has already been requested.

**Is your feature request related to a problem? Please describe.**
F-4 can carry a _lot_ of air to ground munitions but in Liberation is not in the list of CAS-capable planes.

**Describe the solution you'd like**
To add the said aircraft to that list.

**Comment by DanAlbert** [comment]
Fixed by https://github.com/dcs-liberation/dcs_liberation/pull/1073
