### ISSUE TITLE
AEW&C missions are not being auto-generated

### ISSUE THREAD

**Issue by Hornet2041** [dcs-liberation/dcs_liberation#1074]
Before filing, please search the issue tracker to see if the issue has already been reported.

**Describe the bug**
AEW&C missions are not being auto-generated.

**To Reproduce**
1) Start new campaign of Operation Peace Spring, inverted, with USN 1985 faction
2) proceed through new game wizard with "disable invulnerable AEW&C" option checked
3) buy an E-2 on turn 0
4) observe that AWACS mission is not generated

**Expected behavior**
expected Liberation to generate an AWACS mission automatically D:

**Additional information**

Build #1507

[no awacs generated.zip](https://github.com/dcs-liberation/dcs_liberation/files/6456409/no.awacs.generated.zip)

**Comment by DanAlbert** [comment]
Triaging for 3.0 as the lack of message in the log makes me think this is related to https://github.com/dcs-liberation/dcs_liberation/commit/36b2f24de97bdd2905decad49d8266d0a62762b2, but if this is a problem in 2.5.1 then we should cherry-pick back in case we do a 2.5.2.

**Comment by Hornet2041** [comment]
AEWC missions were being generated as far back as build 1490 and stopped as of build 1491

https://github.com/dcs-liberation/dcs_liberation/commit/2ca875192af296a1a687ef309c6439e30e6841d4

**Comment by DanAlbert** [comment]
Fixed. I improved error handling on faction definitions as a part of this, so keep any eye on the log if base menus seem to crash.
