### ISSUE TITLE
BARCAP route wrong

### ISSUE THREAD

**Issue by 17721250181** [dcs-liberation/dcs_liberation#1075]
**Describe the bug**
The route of the BARCAP is far away from the combat area. Is it a bug or setting?

**To Reproduce*
Star a new game, buy some A2A plane, passturn
https://ibb.co/nCRfQDX

vision: 2.5.1

**Comment by DanAlbert** [comment]
Looks correct to me. Any closer than that and it'd be a sweep.

**Comment by DanAlbert** [comment]
There's room for improvement that's covered in a feature request.

Duplicate of #777
