### ISSUE TITLE
Have campaigns define a default start date

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#1079]
**Is your feature request related to a problem? Please describe.**
Campaigns do not have any suggested start date.  The campaign designer might design the campaign around a certain time frame (seasons, availability of GPS, availability of weapons) and has no way to suggest or enforce that into the campaign.

**Describe the solution you'd like**
Similar to how there are `Default Factions` there should be a `Default Start Date`.

**Comment by DanAlbert** [comment]
SGTM. Rather than pulling this from the JSON file (where the format is a string that people just have to hope they formatted correctly), we could pull this from the mission date in the campaign miz.

**Comment by DanAlbert** [comment]
(if no one else picks this up in 5.x I will)
