### ISSUE TITLE
BUG: TACAN for tankers in briefing is wrong

### ISSUE THREAD

**Issue by rabauke80** [dcs-liberation/dcs_liberation#108]
Tankers on PG light are on AA TACAN "Y" instead of "X" as stated in the briefing. Also the TACAN ID's as shown in the left DDI are not matching to the callsigns/briefing information.

[Briefing](https://paste.pics/9XUOV)
[Screenshot#1](https://paste.pics/9XUNY)
[Screenshot#2](https://paste.pics/9XUOJ)

Version: 2.1.0

**Comment by DanAlbert** [comment]
Fixed in 2.1.1.
