### ISSUE TITLE
Hornet's OCA/Aircraft loadout shows correctly in Liberation, but is changed to Mavericks in DCS

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#1081]
**Describe the bug**
My default OCA loadout is 4 JDAMs. This displays fine in Liberation. However, the loadout in the mission editor after mission generation gives me Mavericks instead.

**To Reproduce**
1. Create OCA/Aircraft flight
2. Use default loadout
3. Fly mission
4. Get wrong weapon

Liberation #1528

**Comment by DanAlbert** [comment]
Mind verifying this on a recent build? I redid everything about loadouts since this was filed.

**Comment by Starfire13** [comment]
The redo has fixed it. I am no longer encountering this problem on #1656
