### ISSUE TITLE
Operation Peace Spring has unit transfer convoy spawn on runway at Ramat David

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#1083]
**Describe the bug**
Unit transfers spawned through purchases at the front line airbase cause units to be spawned in the middle of the runway at Ramat David.

**To Reproduce**
1.  Create Operation Peace Spring scenario
2.  Capture Damascus
3.  Order front line units at Damascus/Tiyas front line.
4.  Generate mission (or skip mission then generate the next one) whichever one spawns the unit convoy.
5.  Observe convoy spawned on Ramat David runway.

**Expected behavior**
Convoy to not spawn directly on Ramat-David runway.

**Additional information**
[OperationPeaceSpringSpawningOnRunway.zip](https://github.com/dcs-liberation/dcs_liberation/files/6488479/OperationPeaceSpringSpawningOnRunway.zip)

**Version information (please complete the following information):**
 - DCS Liberation Build 1538

**Comment by Starfire13** [comment]
Hmm. Not sure why it's doing that because the waypoint isn't actually on the runway. Will look into it. Thanks.

![Capture](https://user-images.githubusercontent.com/72491792/118382388-2fb8dc00-b638-11eb-812f-d94fb8bafbd8.JPG)

**Comment by DanAlbert** [comment]
Cheating (or maybe the base capture) is actually what caused this.

Before: 
![image](https://user-images.githubusercontent.com/315852/119279336-e5a79b80-bbdf-11eb-9b52-dcca25298ebf.png)

After: 
![image](https://user-images.githubusercontent.com/315852/119279324-d4f72580-bbdf-11eb-96e6-6feb4337cfe7.png)

idk why yet, but this one's pretty clearly on me :)

**Comment by DanAlbert** [comment]
I don't know why and I suspect I don't want to, but this only happens in the old UI 😐

**Comment by DanAlbert** [comment]
Hmm, the UI quirk is only present when I cheat in the old UI. If I cheat in the new UI the supply route doesn't change on the map, but they still spawn on the runway...

**Comment by DanAlbert** [comment]
I honestly don't know why this wasn't  _more_ broken. It should have been breaking every supply route with an active front line every time one was looked at by the game for any reason, since doing so was modifying the list (which really should have been immutable). Oh well, it's fixed.
