### ISSUE TITLE
DEAD flight with B52 or F117 does not create attack task in mission editor

### ISSUE THREAD

**Issue by Zwibber** [dcs-liberation/dcs_liberation#1086]
Related discussion: #774

When creating a DEAD flight with either B-52s or F-117s, their flight routes are created without an attack task as can be seen in the mission editor in DCS. As a result, these flights will never attack their target and move from ingress to egress immediately.

**Steps to reproduce:**

1. Create game and choose faction with B-52s or F-117s+
2. Buy B-52s or F-117s 
3. Pass turn
4. Plan DEAD flight with B-52 or F-117 on any enemy air defence group
5. TAKE OFF
6. Open mission in mission editor and see created flight's waypoints

**Expected behavior**
Task to attack the predefined group in the ingress waypoint's advanced waypoint options.

**Additional information**

[DEAD_B52_F117_NOACTIONS.zip](https://github.com/dcs-liberation/dcs_liberation/files/6490208/DEAD_B52_F117_NOACTIONS.zip)
![F117NOACTIONS](https://user-images.githubusercontent.com/29946458/118415579-667c0a00-b6ab-11eb-9731-2c9dfa43a873.png)

**Version information (please complete the following information):**
 - DCS Liberation 2.5.1

**Additional context**
My guess is that this happens with all aircraft that are not capable of the SEAD task as per mission editor in DCS as they do not have dedicated anti-radiation weapons. Instead, the 'pinpoint strike' task is chosen, but no target is created. In my opinion, the easiest way to fix this is to remove the SEAD and DEAD roles from these aircraft and have them execute these types of flights with 'Strike' as default.

**Comment by DanAlbert** [comment]
Thanks. I'll take a look in a couple hours.

**Comment by DanAlbert** [comment]
The F-117 is incapable of performing the Attack Group action. The B-52 is capable of using it, but only with the CAS task type. We assign DEAD flights to the SEAD DCS task type, but the B-52 isn't capable of that role in DCS so it's getting downgraded to Ground Attack, which doesn't support attack group.

This is essentially another form of https://github.com/dcs-liberation/dcs_liberation/issues/269. Nothing we can do but remove the B-52 and F-117 from the DEAD capable lists until someone has the time to do that.
