### ISSUE TITLE
Limit number of units

### ISSUE THREAD

**Issue by Goliathus-21** [dcs-liberation/dcs_liberation#1088]
Hi,

I´ve been using the Liberation campaign in DCS for several months now. I play on an OK gaming PC, but I can see its limits when there are plenty of units on the map. Culling doesn´t work for this issue all the time and I´ll try to explain why.

When I run a new campaign with some budget, I buy ground/air units in number I see reasonable, mainly because there is no reason to maintain let´s say 100 aircrafts on 5 airfields, if I´m only in need of 35 - 50 aircrafts on two airfields, nearest to frontline or near where I can expect to find enemies.

But the AI is different. Usually AI spend tons o money on buying aircraft, most of them are usually grounded and it buys only few ground units, which is easy to kill after few missions. Then I get a situation, where there is almost no enemy frontline ground units, but there is plenty enemy aircraft, some of it in the air, some stays grounded. But it has a huge impact on CPU performance, at least on my PC and I get sometimes very low FPS near frontline or airfields even if there are mostly grounded thus absolutly omisible planes. So this brings me to my idea :-)

Would it be possible to make a setting for the campaign, which could limit the max. number of air units (red and blue force) and ground limits, so the AI (and player) could buy only certain number of units and refill them only if there is a need for reinforcements?

That would definintely help for players with CPU limits. For me personally I have high FPS (+100) when playing dogfights with few planes, but Liberation campaign can bgring it to 15 - 20 FPS in situations, when there are 150 planes bought by the AI even though they aren´t in the air and I lack ground units, cause AI is so stupid, that it always prefer to buy new planes even if it doesn´t need them and I can run through frontline with ground units like if there was just some kind of military parade going on. 

Usually I have to overcome this issue by cutting AI budget, so it can´t afford any reinforcements and thus I don´t get overcrowded map ruining my CPU. But then if I refill AI budget again, it buys new planes instead of soooo needed ground units.

I really love Liberation campaign, it gives DCS life and it is the main reason to play DCS at all.

Thank you for bringing us the Liberation dynamic campaign.

**Comment by DanAlbert** [comment]
Other FRs are already open for this.
