### ISSUE TITLE
F/A 18 data link doesn´t work properly if player flight gets delayed

### ISSUE THREAD

**Issue by Goliathus-21** [dcs-liberation/dcs_liberation#1090]
Maybe I found a bug, maybe I just didn´t find a way to solve this issue. I couldn´t even find any solution via google, so I´m opening this new thread.

I find quite often that if my flight gets delayed, my data-link in F/A-18 doesn´t work properly. It comes pretty obvious when using jhmcs, because I don´t see my wingman marked as "B" and I don´t see other flights also. It is like if I have almost no information shared through the data-link. I´m not used to start in a cold F/A-18, usually I start warmed up, maybe it is related to the issue, I´m not sure.

Is there any way to overcome this issue or is it a known bug? Data link is supposed to work regardless to flightplan :-P

Thank you!

**Comment by Mustang-25** [comment]
Delayed start should have no effect on datalink and you're the first person to report this issue as it relates to Liberation. Since you're not used to cold starting, I would recommend you verify your cold start procedures to make sure it's not something you're doing wrong first.

**Comment by DanAlbert** [comment]
The only thing delay does is start aircraft late activation or uncontrolled. If that's breaking data link it's a DCS bug that we have no power to fix.
