### ISSUE TITLE
[Build 1583] Show Tooltip for Clusters

### ISSUE THREAD

**Issue by Mustang-25** [dcs-liberation/dcs_liberation#1094]
Currently, tooltips are only displayed for individual objectives.

![image](https://user-images.githubusercontent.com/72566076/118871122-1dd77300-b89c-11eb-8f4d-8dfcfc8904d6.png)

But are not displayed for clusters: 

![image](https://user-images.githubusercontent.com/72566076/118871167-2b8cf880-b89c-11eb-8a06-b8cee4185a2e.png)

Adding tooltips for clusters will help improve player's situational awareness at higher map zoom levels.

**Comment by DanAlbert** [comment]
(I'll probably be the one that ends up doing this but unassigning myself to make it clear that it's fair game if someone else wants to)

**Comment by DanAlbert** [comment]
Clusters are gone.
