### ISSUE TITLE
[Build 1583] Improve Display of CP Labels

### ISSUE THREAD

**Issue by Mustang-25** [dcs-liberation/dcs_liberation#1095]
In my opinion, the tooltip labels for the CPs are a little too intrusive and can get in the way of other map elements as illustrated below:

![image](https://user-images.githubusercontent.com/72566076/118876642-59753b80-b8a2-11eb-974c-8351a9976e00.png)

As discussed on Discord, some ideas to alleviate this problem would be:
- adjust the opacity of the text bubble to allow seeing the map elements below it
- make it such that CP labels only display when hovered over
- CP labels are toggled on/off as display option

**Comment by DanAlbert** [comment]
Removed the forced tooltip display.
