### ISSUE TITLE
Fouled deck, aircraft cannot land after missions.  Using Supercarrier

### ISSUE THREAD

**Issue by PappyGunn** [dcs-liberation/dcs_liberation#1096]
First bug report, not sure about the format.  While paying Liberation v2.5, using Supercarrier, Iran campaign, USA 2005 and Iran 2015.  Flying F-18.  Whenever I come back from a mission, there is ALWAYS an aircraft fouling the deck.  Usually an F-14, but if I delete all the F-14 missions, it will be an F-18.  It is lined up behind catapult #3, but so far back it blocks part of the diagonal landing deck.  Maybe the deck crew ignored it and it is stranded there.  All arriving aircraft get waived off.  Pretty sure they run out of fuel and crash too.  I get authorization to land, but also get waived off.  If you're good :-} you can land right of the runway and avoid colliding with the aircraft, but it's a PITA.  This is an aircraft generated after all initial packages take off (I don't wait), when I leave the carrier the deck is usually clear.  Could not attach a file (newb).  In one game I noticed the aircraft was PUMA2, a strike escort aircraft  scheduled to escort Harriers from another ship, TOT 1:23:02, so pretty late in the day.

Another smaller bug is that the AI schedules all F-14 missions until it runs out, even on BAI or stike missions, leaving up to 22 F-18s on the carrier without anything to do.

**Comment by DanAlbert** [comment]
> First bug report, not sure about the format

Did the template not show? How did you file this that you didn't get the template?

I'm not really sure what you expect us to do here though. We have no way of altering DCS AI taxi/landing/takeoff behavior.

**Comment by PappyGunn** [comment]
OK.  I thought it might have been related to the very high number of sorties being generated by Liberation and how they interact with each other, maybe interfering with each other.  I’ll test that theory on my own.  Anyways, I like this mission/campaign generator and lot and while it has a few flaws, I’ll take this opportunity to give you guys some kudos.

Steph Fortier
