### ISSUE TITLE
[Build 1590] Unable to Accept Results and Proceed to Next Turn

### ISSUE THREAD

**Issue by Mustang-25** [dcs-liberation/dcs_liberation#1098]
In build 1590 I am unable to proceed to the next turn. It let's you submit state.json and shows the first results page but does not let you accept results. The log error is shown below.

json, save, and miz also attached.

![](https://cdn.discordapp.com/attachments/684237466211057685/845156558685601792/unknown.png)

[Build_1590_Results_Bug.zip](https://github.com/dcs-liberation/dcs_liberation/files/6520146/Build_1590_Results_Bug.zip)

**Comment by DanAlbert** [comment]
Was fixed after the build you're on.
