### ISSUE TITLE
Unit group is displayed as damaged when should be destroyed

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#1099]
**Describe the bug**
Several destroyed BAI targets are displayed as damaged (yellow underline) when they should be destroyed (red underline).

**Additional information**

The objectives shown below (west of Allepo) should have red underlines instead of yellow underlines.

https://media.discordapp.net/attachments/790195984105734165/845154201675890708/unknown.png

**Version information (please complete the following information):**
 - DCS Liberation `Build 1604`

**Additional context**
Campaign: 
[1604_Inherent_Resolve.zip](https://github.com/dcs-liberation/dcs_liberation/files/6520223/1604_Inherent_Resolve.zip)

**Comment by DanAlbert** [comment]
You saves still don't load on my machine. Try https://github.com/dcs-liberation/dcs_liberation/actions/runs/862985565 and lmk.
