### ISSUE TITLE
JU-88 don't appear in game

### ISSUE THREAD

**Issue by fransschuijt** [dcs-liberation/dcs_liberation#110]
Hi Khopa, first of all great job, love the dynamic campaign! Thanks!
I'm playing in Normandy with the ww2 allies against ww2 germany. My issue is that the opponent has multiple Ju-88, but they don't appear in game. 

And i would really like it if you could send CAS/Sead/strike missions to the enemy/allied bases and not just the frontline.

And some small things: the flakk searchlights light up during daytime and planes on the ground are almost indestructible (but that might be a dcs issue?)
Keep it up and kind regards!

**Comment by Khopa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Flak searchlight are up even in daylight](https://trello.com/c/FQDrcfJB/132-flak-searchlight-are-up-even-in-daylight)

**Comment by Khopa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Ju-88 does not have any possible missions](https://trello.com/c/9yz4POWK/133-ju-88-does-not-have-any-possible-missions)

**Comment by Khopa** [comment]
The current problem with the JU-88 is that in game i think it can only do antiship missions, and antiship missions are not really generated yet. 

But this will be fixed, when i'll add antiship missions :)

> And some small things: the flakk searchlights light up during daytime and planes on the ground are almost indestructible (but that might be a dcs issue?)

I believe this is a DCS issue, i could try to disable them if it is a day mission though, not sure if it possible

**Comment by DanAlbert** [comment]
All the additional mission types discussed here were added in 2.3 and 2.2.

**Comment by fransschuijt** [comment]
Awesome! Thanks a lot!!
Greetings, Frans

Op ma 7 dec. 2020 10:42 schreef Dan Albert <notifications@github.com>:
