### ISSUE TITLE
Inherent Resolve convoy from Tabqa to Jirah does not move

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#1101]
**Describe the bug**
A convoy departing from Tabqa to Jirah does not move from spawned position in the Inherent Resolve campaign.

**To Reproduce**
1) Create default Inherent Resolve campaign
2) Destroy factory and lots of targets at Jirah to trigger a departing convoy next turn
3) Observe convoy from Tabqa to Jirah does not move.

**Expected behavior**
Convoy from Tabqa to Jirah to move.

**Additional information**
Campaign and Mission:
[ConvoyNotMovingTabqaToJirah.zip](https://github.com/dcs-liberation/dcs_liberation/files/6523994/ConvoyNotMovingTabqaToJirah.zip)

**Version information (please complete the following information):**
 - DCS Liberation Build 1604

**Comment by DanAlbert** [comment]
![20210521175052_1](https://user-images.githubusercontent.com/315852/119209721-29be6300-ba5d-11eb-9478-b0d666a6a276.jpg)

If the convoy is moved to the other side of that break in the road the game is able to do on-road routing. This is a map bug, but we can work around it by moving the convoy start location.

**Comment by DanAlbert** [comment]
Pushed a change that should fix it.
