### ISSUE TITLE
Creating a CAS Front line Mission Package does not generate Waypoints

### ISSUE THREAD

**Issue by gatorman22** [dcs-liberation/dcs_liberation#1102]
**Describe the bug**
When creating a new CAS Front line Mission Package, Waypoints are not generated for the flight(s)

**To Reproduce**
1. In active Liberation mission, create a new CAS Front line Mission Package by right-clicking on the orange Front line marker
2. Add a flight with Task: CAS (Tested with F16 and F18, both with and without Player slot)
3. Right-click on the newly created flight and select Edit
4. Click on the Waypoints tab
5. Waypoints are empty
6. Additionally, Generate: Recreate as CAS has no effect

**Expected behavior**
Waypoints for Takeoff, Hold, Ingress, Egress, Split, Land are expected (roughly from memory) as in previous Liberation releases

**Additional information**
I haven't included a save file as it can be easily replicated at-will.  But I'm happy to if it turns out I'm incorrect.

**Version information (please complete the following information):**
 - DCS Liberation 3.0-Build #1592

**Comment by DanAlbert** [comment]
> I haven't included a save file as it can be easily replicated at-will. But I'm happy to if it turns out I'm incorrect.

Please do this by default. Things that are obvious on your machine aren't always obvious on mine. Usually the reason a bug exists is because it isn't happening for us. It's always a pain when I have to look at a bug twice because I don't have the data I need. This is why we ask for these things.

**Comment by gatorman22** [comment]
I understand, I will make the effort going forward.  Included screenshot, .Liberation and .miz files (in zip)

![image](https://user-images.githubusercontent.com/17415205/119187409-4e0f4500-ba47-11eb-9603-234223de75eb.png)

[3-1592.zip](https://github.com/dcs-liberation/dcs_liberation/files/6524641/3-1592.zip)

**Comment by DanAlbert** [comment]
This was fixed by 1c32ae1227595f291d10d503501b909165ccc003. It's something I'd actually fixed before you'd filed the bug, so I'd have had a hell of a time trying to repro this without the save game, and instead it took only a minute to figure out what happened :) Thanks!
