### ISSUE TITLE
Ships on convoy transfer do not actually move in-mission

### ISSUE THREAD

**Issue by Hornet2041** [dcs-liberation/dcs_liberation#1104]
Before filing, please search the issue tracker to see if the issue has already been reported.

If reporting a DCS AI bug, check https://github.com/dcs-liberation/dcs_liberation#dcs-bugs.

**Describe the bug**
Unit transfer via cargo ship do not move when the mission is playing.

**To Reproduce**
1. Start new campaign of Battle of Abu Dhabi
2. Buy units at bandar abbas
3. create transfer order to khasab when able
4. start mission, see that ship does not move.

**Expected behavior**
for the ship to move

[AI abu dhabi invasion.zip](https://github.com/dcs-liberation/dcs_liberation/files/6525627/AI.abu.dhabi.invasion.zip)

**Version information (please complete the following information):**
 - DCS Liberation: 3.0 preview build #1602

**Comment by Hornet2041** [comment]
Also can't get it to move via Combined Arms move/speed orders. Not sure if DCS bug or not....

**Comment by DanAlbert** [comment]
Sounds like a DCS bug. Maybe a problem with the type of ship. Will have a look.

**Comment by Hornet2041** [comment]
after some testing, the Handy Wind ship unit needs a depth of -32 feet for it to move
