### ISSUE TITLE
Cannot edit E-2 flight settings

### ISSUE THREAD

**Issue by Hornet2041** [dcs-liberation/dcs_liberation#1107]
Before filing, please search the issue tracker to see if the issue has already been reported.

If reporting a DCS AI bug, check https://github.com/dcs-liberation/dcs_liberation#dcs-bugs.

**Describe the bug**
I was trying to change the Hawkeye's start spawn from runway to air and it would not let me. Log entry is:

> Traceback (most recent call last):
>   File "widgets\ato.py", line 195, in on_double_click
>   File "widgets\ato.py", line 200, in edit_flight
>   File "dialogs.py", line 57, in open_edit_flight_dialog
>   File "windows\mission\QEditFlightDialog.py", line 33, in __init__
>   File "windows\mission\flight\QFlightPlanner.py", line 20, in __init__
>   File "windows\mission\flight\payload\QFlightPayloadTab.py", line 35, in __init__
>   File "windows\mission\flight\payload\QFlightPayloadTab.py", line 13, in __init__
>   File "gen\flights\loadouts.py", line 60, in iter_for
> TypeError: 'NoneType' object is not subscriptable

**To Reproduce**
1. Start new campaign on build 1602 in battle for abu dhabi
2. enable carrier, buy an E-2
3. try to open flight settings
4. observe cannot

[hawkeye.zip](https://github.com/dcs-liberation/dcs_liberation/files/6527303/hawkeye.zip)

build #1602

**Comment by DanAlbert** [comment]
I coincidentally fixed this while fixing something unrelated, but we need pydcs to merge my fix first: https://github.com/pydcs/dcs/pull/146
