### ISSUE TITLE
[Build 1652] ASAP AEW&C Missions do not actually ASAP

### ISSUE THREAD

**Issue by Mustang-25** [dcs-liberation/dcs_liberation#1117]
The default AEW&C missions do not actually ASAP their ToTs even when the ASAP box is checked as shown below. Tested with a couple different 3.0 compatible campaigns with the same results.

![image](https://user-images.githubusercontent.com/72566076/119568957-f896a900-bd62-11eb-8053-b14a5bcbdbb7.png)

**Comment by DanAlbert** [comment]
Gonna need a save. Works for me.

**Comment by DanAlbert** [comment]
Huh. But only in one of my games, it seems. Not sure why. Never mind.
