### ISSUE TITLE
Deprecate the Old AEW&C Option

### ISSUE THREAD

**Issue by Mustang-25** [dcs-liberation/dcs_liberation#1118]
With the addition of the taskable AEW&C option, the old feature that spawns the invisible and invulnerable AWACS should be deprecated. As discussed on Discord, this can probably be done when HAVCAP missions are implemented.

![image](https://user-images.githubusercontent.com/72566076/119573051-8c1ea880-bd68-11eb-89b2-93503c6f23de.png)

**Comment by DanAlbert** [comment]
(3.0 to flip the default, won't remove the option until HAVCAP is ready)
