### ISSUE TITLE
No Flight Plans Rendered Over Map for Syria

### ISSUE THREAD

**Issue by fearlessfrog** [dcs-liberation/dcs_liberation#1121]
When using the Syria map theatre the flight plan lines don't appear over the map for the develop branch preview build. 
Other maps seems to work ok (Nevada, PG etc) so this just seems just Syria map related.

If I hit 'Reload' from the right mouse button on the Map then they will appear with default options.

**To Reproduce**
1. Create a new campaign - Syria - Inherent Resolve
2. Choose Auto Purchase options.
3. Pass Turn to move from turn 0
4. Don't see any flight plans on map, or have the ability to select flights for display on map from list.

**Expected behavior**
Other maps show flight plan lines correctly, so was expecting that on Syria map as well.

**Version information (please complete the following information):**
 - DCS Liberation 3.0 - 1657 preview

[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/6542886/liberation.log)

**Comment by DanAlbert** [comment]
> 1. Create a new campaign - Syria - Inherent Resolve
> 2. Choose Auto Purchase options.
> 3. Pass Turn to move from turn 0

You need to enable that _during_ campaign generation. The purchase phase happens at the start of the turn. If you enable it after turn zero starts it doesn't run until turn 1.

**Comment by DanAlbert** [comment]
If that's not it, we do need the save game the template asked for. This doesn't happen on my machine. Bugs that are obvious on your machine may not be on mine.

**Comment by DanAlbert** [comment]
Hmm. Seems that the problem only occurs when creating the Syria campaign if another campaign is already loaded? (which would be why I hadn't seen it; I was generating from scratch with no campaign loaded)

**Comment by fearlessfrog** [comment]
> You need to enable that during campaign generation. The purchase phase happens at the start of the turn. If you enable it after turn zero starts it doesn't run until turn 1.

I do, as in I tick the boxes as part of the New Campaign wizard steps and not afterwards.

> Seems that the problem only occurs when creating the Syria campaign if another campaign is already loaded? (which would be why I hadn't seen it; I was generating from scratch with no campaign loaded)

For me I see it with a fresh install, no save game and creating a new Syria campaign. It is good that you've recreated it anyway, but for me anyway, it was from generating from scratch. The logs hopefully shows this.

**Comment by fearlessfrog** [comment]
> If that's not it, we do need the save game the template asked for

I'm just choosing the campaign that came with the build 'Syria - Inherent Resolve'. 

Is there anything else I can provide to help, files etc? I did chat with some others in the Discord, so some more info in here - https://discord.com/channels/595702951800995872/782361390954053643/846876699752792104

**Comment by DanAlbert** [comment]
> For me I see it with a fresh install, no save game and creating a new Syria campaign. It is good that you've recreated it anyway, but for me anyway, it was from generating from scratch. The logs hopefully shows this.

Huh. Weird.

> Is there anything else I can provide to help, files etc?

Don't think so. I'll have a look. I'm not really sure what's going on yet.

**Comment by fearlessfrog** [comment]
Could it be related to swapping from stable to preview build? I took a look in liberation_preferences.json and it looks like info good between both, but there must be some state that's hanging around. I wonder if I've sort of corrupted my test steps from going between a stable to a develop branch build, and that might explain why we see it a bit differently. I can clean out my DCS Saved Games folder and recheck.

**Comment by DanAlbert** [comment]
From the quick glance I had it seems to be that the events to update the map are firing out of order, but I have no idea why that would be specific to Syria (which does seem to be the case, though I only tested one Syria campaign).

**Comment by DanAlbert** [comment]
> Could it be related to swapping from stable to preview build?

(I wasn't explicit earlier, but I basically never run the stable build so unlikely given that I can repro it too)

**Comment by DanAlbert** [comment]
I copy/pasted some code from the old map and forgot to make a tweak that was needed for the new one (and because it's in the UI code, the type checker can't work there so it didn't spot the obvious bug).

The reason this _appeared_ to be unique to Syria is because Inherent Resolve defaults to opfor as Insurgents, who have no SAMs, and an empty threat zone is what caused the problem. The actual difference between me not seeing this after generating Syria missions all day and finally seeing the repro was because I had a different default opfor faction with the workflow I was using :)

**Comment by DanAlbert** [comment]
Fixed now. Thanks for filing. I think someone had actually seen this the other day but hadn't been able to repro 👍

**Comment by fearlessfrog** [comment]
Great - thanks for all this. Loving Liberation in our group.
