### ISSUE TITLE
A20 and B17 no default payloads

### ISSUE THREAD

**Issue by clutchtomcat** [dcs-liberation/dcs_liberation#1122]
**Describe the bug**
A20 and B17 in all ground attack tasks are spawned empty

**To Reproduce**
1. Task A20 or B17 with OCA runway strike, strike, or DEAD
2. Check payload
3. Confirm payload is empty

**Expected behavior**
Default payloads are present for most aircraft, and had been present on A20s and B17s in previous iterations.

**Version information (please complete the following information):**
 - DCS Liberation 2.5
[WW2_Liberation_Bugs.zip](https://github.com/dcs-liberation/dcs_liberation/files/6543588/WW2_Liberation_Bugs.zip)

**Comment by Mustang-25** [comment]
Checked on the latest build and the issue is resolved, both A-20 and B-17 are generating loadouts for all above mentioned taskings. Marking this report as closed.
