### ISSUE TITLE
WW2: DEAD, BAI Advanced Waypoint Actions - Guided munitions

### ISSUE THREAD

**Issue by clutchtomcat** [dcs-liberation/dcs_liberation#1123]
**Describe the bug**
WW2 aircraft set to CAS in DCS (from DEAD or BAI in Liberation) will have their advanced waypoint action "attack group" set to employ guided munitions. Guided munitions do not exist in DCS WW2, and the group RTB's at their ingress point, failing to hit their target.

**To Reproduce**
1. Task an aircraft with DEAD or BAI
2. Check aircraft's advanced waypoint action on their ingress waypoint
3. Open the advanced waypoint action "attack group"

**Expected behavior**
I assume Liberation needs a one-size-fits-all approach to generating waypoints and advanced waypoint actions for both WW2 and modern aircraft. I believe in past iterations the advanced waypoint action was set to auto. 

**Version information (please complete the following information):**
 - DCS Liberation 2.5

[WW2_Liberation_Bugs.zip](https://github.com/dcs-liberation/dcs_liberation/files/6543606/WW2_Liberation_Bugs.zip)

**Comment by DanAlbert** [comment]
Already fixed in 3.0.
