### ISSUE TITLE
Sweeps and Escorts set to ignore multi-role fighters

### ISSUE THREAD

**Issue by clutchtomcat** [dcs-liberation/dcs_liberation#1124]
**Describe the bug**
Sweep and Escorts have their advanced waypoint action "search then engage" set to engage only fighters, ignoring all other aircraft types. With the majority of aircraft being multirole fighters, this means that the Sweeps and Escorts hardly engage anything, and any multirole fighter (P-47, Fw190A8) can fly with near impunity. 

**To Reproduce**
1. Create Sweep or Escort flight
2. Check advanced waypoint action "search then engage"
3. See error

**Expected behavior**
Sweep and Escort should be set to engage both fighters and multirole fighters, as there are few purebred fighters in DCS, and the majority of aircraft in the AO are multirole.

**Additional information**
Most noticeable in WW2; unsure if it also affects modern campaigns.

**Version information (please complete the following information):**
 - DCS Liberation 2.5
[WW2_Liberation_Bugs.zip](https://github.com/dcs-liberation/dcs_liberation/files/6543633/WW2_Liberation_Bugs.zip)

**Comment by Mustang-25** [comment]
43010779d41cdff951ec493214ab478bdf2e4f83 should fix this for the next release.

**Comment by DanAlbert** [comment]
(I'd actually missed sweep when I fixed escort a while ago, but it's fixed now, good catch)
