### ISSUE TITLE
Add an option for the Auto aircraft purchase system to only buy aircraft you own

### ISSUE THREAD

**Issue by NeelKulkarni6** [dcs-liberation/dcs_liberation#1125]
I think the Aircraft auto-purchase option is really great and helps people who don't like micromanaging a lot (like me), but one gripe I have with it is it often doesn't buy the Aircraft I like/own. I think if there was an option to limit it to buying aircraft you own (which could maybe be selected in the settings somewhere), then it would be a lot more useful. I think this is important because most people own ~1-4 modules and when aircraft that aren't owned are purchased, it kinda sucks. 

Add an option for the Auto aircraft purchase system to only buy aircraft you own (with a setting to check off aircraft you own).

**Comment by DanAlbert** [comment]
No AWACS? No tankers? No cargo planes? I don't think that's what you want. You can make a custom faction that doesn't include the aircraft you can't fly.

I don't think we have any way of knowing which aircraft you own, and the factions are already the way to signal to the game which types of aircraft to buy.
