### ISSUE TITLE
STRIKE objective map markers only generate 1 in-game marker regardless of number of buildings

### ISSUE THREAD

**Issue by Hornet2041** [dcs-liberation/dcs_liberation#1126]
**Describe the bug**
Objective markers on the map do not include every building designated for a map scenery object strike objective.

**To Reproduce**
1) start a new campaign with scenery objectives on a build that supports the feature
2) get to turn 1 and boot up DCS
3) observe that the scenery objective map marker is only located where the icon is located on the Liberation campaign map

**Expected behavior**
map markers for every building in the designated objective

This is the current result in every build up to 1664:

![bugpic1](https://user-images.githubusercontent.com/55866858/119609543-c702f980-bdc5-11eb-8518-f88f6906abef.jpg)
![bugpic2](https://user-images.githubusercontent.com/55866858/119609555-c9655380-bdc5-11eb-8602-24d78c154d64.jpg)

**Comment by Hornet2041** [comment]
[mapmarker.zip](https://github.com/dcs-liberation/dcs_liberation/files/6544131/mapmarker.zip)

**Comment by SnappyComebacks** [comment]
@DanAlbert This has always been the behavior.  Adding scenery objects had nothing to do with this.

Here's a semi random strike target from `build 1533`.

![image](https://user-images.githubusercontent.com/74509817/119658456-676b1500-bdea-11eb-9613-a516e3f7a289.png)
![image](https://user-images.githubusercontent.com/74509817/119658563-85d11080-bdea-11eb-9781-c34148c356df.png)

**Comment by DanAlbert** [comment]
Got it. Fixing one would fix both then. Thanks for the heads up.
