### ISSUE TITLE
Base - Base Defenses tab unpopulated

### ISSUE THREAD

**Issue by gatorman22** [dcs-liberation/dcs_liberation#1130]
**Describe the bug**
Within the friendly Base dialog, the Base Defenses tab is unpopulated.

**To Reproduce**
1. Create a new campaign
2. Click on any friendly base
3. Click Base Defenses tab - empty

**Expected behavior**
Expect to see base defenses automatically populated and able to be added/replaced/removed like in 2.x

**Additional information**
Included images for 2.x and 3.0 build 1652.  Included Lib and Miz files from 3.0 build 1652

![Screenshot 2021-05-26 134445](https://user-images.githubusercontent.com/17415205/119707998-cd2ac180-be29-11eb-8324-f7b0306488fe.jpg)

![Screenshot 2021-05-26 135014](https://user-images.githubusercontent.com/17415205/119708017-d320a280-be29-11eb-99fa-05c16ae93738.jpg)

Liberation and Mission Files:
[3-1652.zip](https://github.com/dcs-liberation/dcs_liberation/files/6548720/3-1652.zip)

**Version information (please complete the following information):**
 - DCS Liberation [e.g. 2.3.1]: 3.0 build 1652

**Additional context**
Maybe this is being phased out?  I did searches for 'defense', 'defenses' and 'base defenses' before submitting.

**Comment by DanAlbert** [comment]
The tab has no purpose any more. Base defenses were only separate from the other objectives because the old map lacked the fidelity to draw base defenses without making the base impossible to click.

We'll be removing the tab after I remove the possibility for generating them with older (broken) campaigns.

**Comment by gatorman22** [comment]
Just noticed today on build 1668 the Base Defenses tab is populated for FOB Sochi.  I guess it's treating bases and FOBs differently.  Just mentioning it in case someone gets bogged down in details and forgets to check both conditions when phasing out.

![image](https://user-images.githubusercontent.com/17415205/119886855-71cc0280-bf01-11eb-9409-4851c8008624.png)

[3-1668.zip](https://github.com/dcs-liberation/dcs_liberation/files/6556387/3-1668.zip)
