### ISSUE TITLE
Scenario / Turn progress or "finish" time

### ISSUE THREAD

**Issue by Meyomyx** [dcs-liberation/dcs_liberation#1135]
It would be useful for a scenario / turn "finish time" to be displayed on the UI and the Mission Status window, either as a time or a percentage.

**Rationale:**
Often, your mission finishes after a limited period of time or, for example, you have been shot down. You can quit DCS at that time and, of course, the scenario, along with any progress, will be recorded. However, many of the missions will be in progress or will not even have commenced which can have quite a distorting effect on the theatre. The choice is up to you of course, but it would be useful to know how long you can leave the scenario running for "all" the planned missions to have completed.

The time can be based on the last strike package arrival or TOT. Obviously you could leave it running for hours, but essentially, the objectives will have been largely completed at around this time.

**Example**
After 50 minutes, I land and shut down. I can see that I need to leave DCS running for another 35 minutes for the planned missions to complete (or strike) - I'm 60% through the scenario. I can use time compression if I want but the scenario will play out to a "conclusion" as planned.

**Comment by DanAlbert** [comment]
The last takeoff time is configurable in 3.0 so you can line the latest missions up with your typical mission time. Is that sufficient?

FWIW, we don't _expect_ you to wait for all missions to finish. The last missions to take off are there to provide ambiance, not results.

**Comment by Meyomyx** [comment]
v3 looks promising!

Yes - I suppose that helps. Not sure I agree with your last point, however. In my instance, I was shot down early into a mission. There had been very few engagements or progress .. and then the packages relocated. I get that you wouldn't always leave it running for a few hours BUT there would be some "critical" tasking that I might elect to complete. Some strikes or critical SEAD packages and some front line progression may be more than a little useful.

Maybe it's simply a question of keeping an eye on F10

**Comment by DanAlbert** [comment]
Oh right, dying. I'm generally frustrated enough with myself that I don't wait after that :)

> Maybe it's simply a question of keeping an eye on F10

What I do is open F10 after I've parked, look for any flights that seem close to their targets, and close as soon as there's a break in the action. That also answers the question of how much time is left, because you can see what the last TOT is in the liberation UI and there's a clock in the F10 map.

**Comment by Meyomyx** [comment]
Yeah. I concur

It's Occam's razor

**Comment by DanAlbert** [comment]
Cool, I'll close this then. Thanks for confirming 👍
