### ISSUE TITLE
Squadron size caps and limited replenishment rates

### ISSUE THREAD

**Issue by DanAlbert** [dcs-liberation/dcs_liberation#1136]
Forking from https://github.com/dcs-liberation/dcs_liberation/issues/276

Squadrons should have a maximum size and KIA pilots should take time to replace.

An open question is whether pilot replenishment happen at a per-squadron rate, or a coalition-wide rate. I'm leaning toward coalition-wide, with some other mechanics being able to alter the replenishment rate (perhaps a use for one of the building types?)

**Comment by Slowdive1123** [comment]
I commented on this elsewhere, but I just noticed that work was still ongoing on this feature. In my test on the latest build I created 4 custom squadrons of the same aircraft type, but noticed that only the first squadron was populated with aircraft allowing liberation to auto-purchase. It would be nice if purchases and reinforcements were evenly distributed among the squadrons of the same type.

Perhaps replenishment should be set in the faction config? You could specify the optimum replacement rate for each aircraft type and then they would just be distributed to the squadrons based on need. As infrastructure is destroyed, you could just reduce the replacement rate by a percentage.

**Comment by DanAlbert** [comment]
Nothing has been done for this yet.
