### ISSUE TITLE
Single base operation for squadrons

### ISSUE THREAD

**Issue by DanAlbert** [dcs-liberation/dcs_liberation#1145]
Forking from https://github.com/dcs-liberation/dcs_liberation/issues/276 since it would require non-trivial AI work.

Squadrons should have a single base that they operate from. They'd be able to relocate, but they'd move the whole squadron and they'd need to be ferried to the new locations before they could be used for new missions.

This probably supersedes https://github.com/dcs-liberation/dcs_liberation/issues/508, but won't know until we decide whether aircraft and squadrons are coupled or not.

- [x] Squadrons have bases.
- [x] Squadrons only operate out of their assigned bases.
- [x] Restrict purchase of aircraft at bases based on the squadrons located at the base.
- [x] Default air wing configuration specified by the campaign.
- [x] Squadrons can be relocated manually.
- [x] Squadrons relocate automatically when retreating.
- [x] Squadrons own their aircraft.
- [x] Relocating squadrons create ferry missions.
- [x] Initial squadron locations can be chosen in air wing configuration.
- [x] Auto-purchase obeys squadron locations.

**Comment by KeeseAF** [comment]
Add being able to set squadrons per airfield, at least making it to where hornet pilots aren't taking slots from land based hornet pilots when they have a shipful
