### ISSUE TITLE
Roland Generator does not produce random number of launchers

### ISSUE THREAD

**Issue by docofmur** [dcs-liberation/dcs_liberation#1151]
Roland Generator only ever produces 1 Roland

1. any faction with Roland
2. generate a campaign
3. roland site has SAM Roland EWR, Roland 2, Truck M818 6x6

random generation of Roland 2 chassis' just as with other SHORADS

 - DCS Liberation 2.5.1 Main Release & dev branch build #1560

**Comment by docofmur** [comment]
I noticed this with Tor's also, this might be planned, i'll leave this open incase it is not planned. Sorry I should have tested more before posting the report

**Comment by DanAlbert** [comment]
I don't understand the bug here. This is just now the generator is for that site. What's the problem?

**Comment by docofmur** [comment]
ok sorry I didn't think a single launcher was the intended result as all other types have random number of launchers. I'll close this.
