### ISSUE TITLE
channel map - bombers auto-assigned to runways that are too short. 

### ISSUE THREAD

**Issue by inexus888** [dcs-liberation/dcs_liberation#1159]
Before filing, please search the issue tracker to see if the issue has already been reported.

If reporting a DCS AI bug, check https://github.com/dcs-liberation/dcs_liberation#dcs-bugs.

**Describe the bug**
Bomber planes assigned to airports where the runways are too short to support takeoff. 
Examples: 
1. Ju88 taking off from Saint Omer Longuenesse. 
2. A-20G taking off from Dunkirk Mardyck

**To Reproduce**
1. Start new campaign for the channel map using "operation dynamo". 
2. In the screen for difficulty and automation options tick the boxes for automate runway repairs, automate frontline purchases and automate aircraft purchases. 
3. Finish and launch the campaign. 
4. Select "pass turn". 
5. Select "take off" and go into DCS mission editor.
6. You can either see it here or run the mission to see how bombers are trying to take off from runways that are too short. 

**Expected behavior**
I was hoping bombers would only be able to be assigned to places where the runway is long enough. 

**Additional information**
I can provide a mission if it helps but i think it should be very easy/fast to reproduce this issue.

**Comment by DanAlbert** [comment]
Obsolete with squadron changes in 5.
