### ISSUE TITLE
[Campaigns v6] Failure to Generate Custom Campaign

### ISSUE THREAD

**Issue by Mustang-25** [dcs-liberation/dcs_liberation#1162]
As reported on Discord, I am having trouble generating one of my custom campaigns after updating it to v.6. Log and campaign itself attached below.

![image](https://user-images.githubusercontent.com/72566076/120245608-89b5c600-c222-11eb-8ff2-6c1923e30447.png)

[Operation Mole Cricket 2010.zip](https://github.com/dcs-liberation/dcs_liberation/files/6572386/Operation.Mole.Cricket.2010.zip)

**Comment by DanAlbert** [comment]
Should be fixed.
