### ISSUE TITLE
totals on top of intelligence window

### ISSUE THREAD

**Issue by HILOK** [dcs-liberation/dcs_liberation#1167]
**Is your feature request related to a problem? Please describe.**
in order to get to the totals the user has to scroll all way down in each tab.

**Describe the solution you'd like**
place totals on top of each frame, see pic f.ex.
![lib stats](https://user-images.githubusercontent.com/76898536/120306526-3a2ed300-c2d2-11eb-831a-b21b86996fd4.JPG)

**Additional context**
i know you guys have your hands full, so thanks for considering!

**Comment by Mustang-25** [comment]
Feature has been added, closing this request.
