### ISSUE TITLE
Feature request: Random Szenario

### ISSUE THREAD

**Issue by Emme187** [dcs-liberation/dcs_liberation#117]
Hello there.

Appreciate your great work. First time having a fun solo experience with DCS.

I'd like to suggest to be able to build own fictive szenarios where we can set own factions.

For example I'd like to do a TopGun themed campaign where I can mainly fight Mig28's (F-5e) with the black paint like in the movie. So I was wondering if it would be possible to add an easy option to select factions and what planes and skins they use?

**Comment by DanAlbert** [comment]
Custom factions and campaigns are in 2.2.
