### ISSUE TITLE
[Build 1768] Multiple TARCAP Flights in the Same Package Will TARCAP Themselves

### ISSUE THREAD

**Issue by Mustang-25** [dcs-liberation/dcs_liberation#1175]
Adding multiple TARCAP flights into a package of just TARCAPs will change their TOTs as if they were a package with mixed mission types.

Expected Behavior:
A package of just TARCAP should not have offset TOTs even with multiple flights if the package is only TARCAP.

To Replicate:
1. Create a new package
2. Add one TARCAP flight
3. Add second TARCAP flight
4. Observe change in TOT

![image](https://user-images.githubusercontent.com/72566076/120836606-9c7a1480-c51a-11eb-9540-f3cef6349a53.png)

**Comment by DanAlbert** [comment]
Works for me. Need the data the template asked for. I'd guess that one of these is a different start type than the other, or has taken a different route. The start time is irrelevant here.
