### ISSUE TITLE
UI label change

### ISSUE THREAD

**Issue by Meyomyx** [dcs-liberation/dcs_liberation#1177]
**Describe the bug**
Weather described as "Sunny" at night

**Expected behaviour**
Change text to time inspecific "Clear Skies" or "CAVOK"

**Additional information**
Details, details :)

**Comment by DanAlbert** [comment]
We do actually need those details. I have no idea why this happened and can't figure it out without help.

**Comment by Meyomyx** [comment]
Dan it's permanent - clear conditions are described as "sunny" whether day or night. Just the text "sunny" needs to be replaced with "clear" or "CAVOK". Not much of an issue I grant you! :)

**Comment by DanAlbert** [comment]
But I don't know what you're talking about. Upload the save game.

**Comment by Meyomyx** [comment]
![sunny](https://user-images.githubusercontent.com/70166005/120931342-06481900-c6e9-11eb-94bf-6d5982732014.jpg)
[Desert Invasion.zip](https://github.com/dcs-liberation/dcs_liberation/files/6604468/Desert.Invasion.zip)

**Comment by DanAlbert** [comment]
Yes, that's what I needed, thanks. Please follow the template next time, it'll save both of us time.
