### ISSUE TITLE
Dedicated server

### ISSUE THREAD

**Issue by alcmann** [dcs-liberation/dcs_liberation#118]
Greetings,

Is there any thoughts on getting this to run on a dedicated server ? have tried installing it and running fine on dedicated machine , however its unable to monitor the json file. 

Is there any thoughts or plans or maybe a workaround for running this on a dedicated server ? 

Thanks

**Comment by slasse** [comment]
as a workaround:
there is an option to import the json file manually. when you have the screen open after clicking the 'take off' button
on the bottom of the 'waiting for mission completion' you can click the button 'manually submit' there you can upload a json file which is generated from a mission that has been running on a separate machine.

but there are some things to keep in mind:
If you generate the mission on pc A in the mission trigger the path for the json library which needs to be loaded and the location where the json file is saved is stored as an absolute path so if you start the mission from pc B the json library needs to be there in the correct location and also the location where the json file will be written has to exist. i tried updating the path's in the mission editor but for some reason it would not save correctly. i had to edit the .miz file manually.

it's not ideal but we where able to generate a mission on one pc, run it on another and get the results back on the original pc. for us the use case was more so we could generate the mission beforehand so we could plan our mission and make kneeboards before we would fly it. 

for us it seemed to work but maybe one of the developers will see an issue with this way of doing it

**Comment by DanAlbert** [comment]
https://github.com/Khopa/dcs_liberation/wiki/Dedicated-Server-Guide

There's another bug open for a client/server architecture.
