### ISSUE TITLE
Update for Vegas Nerve, Peace Spring, Vectron's Claw

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#1181]
* Campaign names: Exercise Vegas Nerve, Operation Peace Spring, Operation Vectron's Claw
* Also including Jordan 2010 faction
[campaigns.zip](https://github.com/dcs-liberation/dcs_liberation/files/6603502/campaigns.zip)

**Comment by DanAlbert** [comment]
This faction was more or less completely non functional in terms of ground units (a bunch of names that matched nothing). Am removing it.
