### ISSUE TITLE
Carrier or Other Base Ship Iconography

### ISSUE THREAD

**Issue by jeetsukumaran** [dcs-liberation/dcs_liberation#1184]
**Is your feature request related to a problem? Please describe.**

(1) It would be nice to have the ships that function as airbases (carrier/LHA) have an augmented icon -- e.g., a darker shade, like land CP's -- so it's clear that these are "special" vs other ships
(2) When we move the carrier/LHA, the (next turn) destination icon is identical to the current position icon. Sometimes this can cause confusion. Maybe this should be semi-transparent to disambiguate? 

**Describe the solution you'd like**

(1) Carrier/LHA/"base" ship icons darker color like land CP's
(2) Moved ship destination icon more transparent, or something else to disambiguate from current location

**Comment by Malakhit** [comment]
Hi @jeetsukumaran - this should now be done.
