### ISSUE TITLE
Flight comm frequency outside of F-16 VHF channel

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#1186]
**Describe the bug**
The flight comm channel is outside the valid frequency range for F16s.  This leads to the appropriate F16 channel not getting assigned properly.

**To Reproduce**
1. Create flight with F16.
2. View Kneeboard Flight comm channel
3. Compare to F16 VHF channel

**Expected behavior**
Flight comms for F16 to be in range of VHF comm.

**Additional information**

We will usually need more information for debugging. Include as much of the following as you are able:
[Bad_F16_Flight_Comm.zip](https://github.com/dcs-liberation/dcs_liberation/files/6605072/Bad_F16_Flight_Comm.zip)

**Version information (please complete the following information):**
 - DCS Liberation Build 1827 (My PR branch)  (Though viewing the commits since 3.0 branch, this is probably possible in 3.0-preview too.)

**Additional context**
![Screen_210606_160728](https://user-images.githubusercontent.com/74509817/120942221-b49d8f80-c6e4-11eb-9a38-d8865cfb63c4.png)

**Comment by DanAlbert** [comment]
This is only in your branch:

```
        if flight.flight_type == FlightType.AEWC or FlightType.REFUELING:
```

`FlightType.REFUELING` is always true, so every single flight is now on UHF.

**Comment by SnappyComebacks** [comment]
Thank you for investigating.

**Comment by SnappyComebacks** [comment]
> 
> 
> This is only in your branch:
> 
> ```
>         if flight.flight_type == FlightType.AEWC or FlightType.REFUELING:
> ```
> 
> `FlightType.REFUELING` is always true, so every single flight is now on UHF.

I went and looked at this finally.  This was like programming 101, lol.  I think I was just trying to quickly march through all the necessary changes.  =p

**Comment by DanAlbert** [comment]
Maybe one of these days I'll go through the drudge work of making us pylint clean. I think it would have caught this for you.
