### ISSUE TITLE
Curly braces replace value of 0 in inventroy management

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#1187]
**Describe the bug**
In the `Airfield Command` tab at an airfield, inside `(0 present)`, if the value is 0, it is displayed as `({} present)`.

**To Reproduce**
1. Create any campaign
2. Open player airfield to purchase aircraft
3. Observe `({} present)`

**Expected behavior**
`(0 present)` instead of  `({} present)`

**Additional information**
[1825_curly_brace_airfield.zip](https://github.com/dcs-liberation/dcs_liberation/files/6605098/1825_curly_brace_airfield.zip)

**Version information (please complete the following information):**
 - DCS Liberation Build 1825  (Latest 3.0-preview)

**Additional context**
![image](https://user-images.githubusercontent.com/74509817/120942673-bfa5ef00-c6e7-11eb-9ca3-b32e34d5705e.png)

**Comment by DanAlbert** [comment]
Fixed earlier today.
