### ISSUE TITLE
Campaign submission: Operation Allied Sword

### ISSUE THREAD

**Issue by sgtfuzzle17** [dcs-liberation/dcs_liberation#1196]
* Campaign name: Syria - Operation Allied Sword
* Files: [Operation Allied Sword files.zip](https://github.com/dcs-liberation/dcs_liberation/files/6624019/Operation.Allied.Sword.files.zip)
* Update summary (optional): Submission for my Operation Allied Sword campaign with accompanying faction files. Campaign is built around a fictional counter-offensive by a joint US-Israeli coalition fighting against a Syrian-Lebanese coalition with Russian materiel backing. Updated for 3.0 release.

**Comment by DanAlbert** [comment]
FYI your factions contain a bunch of units that don't exist. I'm removing the factions and moving the campaign to something else.

**Comment by sgtfuzzle17** [comment]
Which factions have issues? All of the units for the USN/Israeli faction seem to work. If there's problems with the OPFOR faction I can take a look at them and fix it. Which units are causing problems?
I'm having a look and the only things not showing up are the 2S9 and the BM-27, which were pulled from other factions - I can remove them and resubmit the files for that faction if you'd like.

________________________________

**Comment by DanAlbert** [comment]
iirc all of the infantry and several other units. Yours weren't the only broken factions and it would have taken too long to itemize the problems. The next version will yell loudly if something is wrong (which is how I noticed), so sit tight for now and try sending them again when that's ready.

**Comment by sgtfuzzle17** [comment]
Sure thing. I submitted a revised faction just now after hunting down the offending units and have removed them, but no worries if it's not implemented for now.

As an aside, I've got a new US Navy 2005 faction to submit as well as a Cyprus showcase campaign for whenever the new update is ready. Would submitting them seperately be better, and should I submit the Cyprus campaign so it can be included with the next update or wait until said update is out?

________________________________
