### ISSUE TITLE
Add ATC frequency to briefing. 

### ISSUE THREAD

**Issue by MedievalBunny** [dcs-liberation/dcs_liberation#12]
It would be great to have the ATC radio frequency in the briefing, especially for the carrier where we can't find it on the F10 map.

**Comment by Khopa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ATC Frequency to briefing](https://trello.com/c/9emCC34e/108-atc-frequency-to-briefing)

**Comment by Khopa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Carrier frequency in briefing](https://trello.com/c/ahl1G2cj/101-carrier-frequency-in-briefing)

**Comment by DanAlbert** [comment]
Fixed in 2.1.1. Not in the briefing proper, but it's in the kneeboard.
