### ISSUE TITLE
Unit purchase "+" button is greyed out if purchase fails due to insufficient funds, but does not revert back to green if funds are made available elsewhere

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#1207]
**Describe the bug**
If I buy, for example, F-15Cs till I run out of money, the "+" button is greyed out. However, if I free up some money by reducing purchases of other units, the "+" button stays grey until I press "-". This is a problem if you click on "+" for a unit that you have a current count of 0 when you have no money. Because it greys out the "+" button. But since you can't press "-" (as you have 0), you can no longer buy units of that type even when you free up money for it.

#1900 preview

**Comment by DanAlbert** [comment]
Anyone running into this problem in the 3.0.0 release: you can work around it by closing and reopening the window. It will be fixed in 3.0.1.

**Comment by dasrehzockt** [comment]
you can also try to press the '-' button to give the order to sell a unit, as long as you already have at least one available already.

after you press minus, the plus should revert back to green and can be pressed again to buy more aircraft, until it becomes grey again.
EDIT: this even works if the current unit count is 0, just press the '-', it will throw an error but the '+' becomes available again.
