### ISSUE TITLE
A-4E Custom Squadrons break campaign generation

### ISSUE THREAD

**Issue by clutchtomcat** [dcs-liberation/dcs_liberation#1210]
Creating a custom squadron .yam file for the A-4E-C in Saved Games/DCS/Liberation/Squadrons appears to break campaign generation; Clicking the finish button will not generate anything. 

Custom squadron .yam files for other aircraft work fine. It's just the A-4E-C. I suspect it might have something to do with the A-4 liveries not being in the Saved Games/Liveries directory like all other liveries are.

`---
name: VMA-211
nickname: Avengers
country: USA
role: Strike Fighter
aircraft: A_4E_C
livery: USMC VMA-211 Avengers
mission_types:
  - Anti-ship
  - BAI
  - BARCAP
  - CAS
  - DEAD
  - Escort
  - Intercept
  - OCA/Aircraft
  - OCA/Runway
  - SEAD
  - SEAD Escort
  - Strike
  - Fighter sweep
  - TARCAP`

**Comment by clutchtomcat** [comment]
Can't confirm if the livery directory is the issue. I moved the A-4 liveries to Saved Games/DCS/Liveries to test and it still wouldn't work. I can't spot any errors in my .yam file either.

**Comment by DanAlbert** [comment]
Yaml. Not yam.

**Comment by DanAlbert** [comment]
What does the log say?

**Comment by clutchtomcat** [comment]
Not sure what relevance the typo has to the issue but here's the log.

[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/6638305/liberation.log)

**Comment by Hornet2041** [comment]
I recreated your custom squadron file and generated this error in the log when trying to start a new campaign:

Traceback (most recent call last):
  File "game\squadrons.py", line 284, in load_squadrons_from
  File "game\squadrons.py", line 197, in from_yaml
  File "yaml\__init__.py", line 162, in safe_load
  File "yaml\__init__.py", line 114, in load
  File "yaml\constructor.py", line 49, in get_single_data
  File "yaml\composer.py", line 36, in get_single_node
  File "yaml\composer.py", line 55, in compose_document
  File "yaml\composer.py", line 84, in compose_node
  File "yaml\composer.py", line 133, in compose_mapping_node
  File "yaml\composer.py", line 64, in compose_node
  File "yaml\parser.py", line 98, in check_event
  File "yaml\parser.py", line 449, in parse_block_mapping_value
  File "yaml\scanner.py", line 115, in check_token
  File "yaml\scanner.py", line 152, in need_more_tokens
  File "yaml\scanner.py", line 291, in stale_possible_simple_keys
yaml.scanner.ScannerError: while scanning a simple key
  in "C:\Users\3rd windows install\Saved Games\DCS.openbeta\Liberation\Squadrons\A-4\VMA-211.yaml", line 10, column 1
could not find expected ':'
  in "C:\Users\3rd windows install\Saved Games\DCS.openbeta\Liberation\Squadrons\A-4\VMA-211.yaml", line 11, column 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "windows\newgame\QNewGameWizard.py", line 115, in accept
  File "game\theater\start_generator.py", line 101, in generate
  File "game\game.py", line 146, in __init__
  File "game\squadrons.py", line 299, in __init__
  File "game\squadrons.py", line 254, in load
  File "game\squadrons.py", line 288, in load_squadrons_from
RuntimeError: Failed to load squadron defined by C:\Users\3rd windows install\Saved Games\DCS.openbeta\Liberation\Squadrons\A-4\VMA-211.yaml

**Comment by Hornet2041** [comment]
damn github to .yaml screwed the mission type formatting. restoring the indents and dashes before each mission generated this error instead:

Traceback (most recent call last):
  File "game\squadrons.py", line 284, in load_squadrons_from
  File "game\squadrons.py", line 201, in from_yaml
KeyError: 'Could not find any aircraft with the ID None'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "windows\newgame\QNewGameWizard.py", line 115, in accept
  File "game\theater\start_generator.py", line 101, in generate
  File "game\game.py", line 146, in __init__
  File "game\squadrons.py", line 299, in __init__
  File "game\squadrons.py", line 254, in load
  File "game\squadrons.py", line 288, in load_squadrons_from
RuntimeError: Failed to load squadron defined by C:\Users\3rd windows install\Saved Games\DCS.openbeta\Liberation\Squadrons\A-4\VMA-211.yaml

**Comment by DanAlbert** [comment]
> Not sure what relevance the typo has to the issue

Well, if you name the file wrong it won't work.

**Comment by DanAlbert** [comment]
Modded aircraft weren't covered by the docs. Looks like you tried to guess at the name and missed :)

https://github.com/dcs-liberation/dcs_liberation/wiki/Squadrons-and-pilots is updated to cover modded aircraft now. Try again and lmk if it's not clear.

**Comment by clutchtomcat** [comment]
> Modded aircraft weren't covered by the docs. Looks like you tried to guess at the name and missed :)
> 
> https://github.com/dcs-liberation/dcs_liberation/wiki/Squadrons-and-pilots is updated to cover modded aircraft now. Try again and lmk if it's not clear.

The Wiki says the aircraft name should be A_4E_C. As you can see in my first post, the aircraft name is exactly the same as it appears in the Wiki, and exactly the same as it appears in faction files. I also did not alter the file extension. It was copy-pasted from an existing Hornet yaml file with only the name, nickname, aircraft, and livery sections changed.

**Comment by DanAlbert** [comment]
> The Wiki says the aircraft name should be A_4E_C.

Share a screenshot of the part you're looking at? That's not what I'm seeing, so we're not looking at the same place.

**Comment by clutchtomcat** [comment]
Wiki page: https://i.imgur.com/7EWoKPX.png

Link from the wiki page showing the code: https://i.imgur.com/R2Nxwh2.png

I also can't find the db.py file on my system to crosscheck. There's no game/ directory in my Liberation folders.

I tried remaking the yaml file but it still doesn't work, with no errors in the logs. 
[VMA-311.zip](https://github.com/dcs-liberation/dcs_liberation/files/6641598/VMA-311.zip)

**Comment by DanAlbert** [comment]
Okay, so you're looking at the section but you missed part of it:

> The aircraft should match the key (**the value in quotes**) of the aircraft

But your yaml file says: `aircraft: A_4E_C`. The value in quotes is `A-4E-C`, not `A_4E_C`.

> I also can't find the db.py file. There's no game/ directory in my Liberation folders.

There's a link to it right afterward. It's not a thing that's shipped because it gets compiled into the executable.

**Comment by clutchtomcat** [comment]
That worked. All these inconsistencies are driving me nuts. Makes it impossible to extrapolate and make correct guesses when there isn't documentation on something, then the documentation doesn't get 100% processed by the brain when it doesn't match the majority of other cases.

**Comment by DanAlbert** [comment]
It's a work in progress. It'll get there.

**Comment by clutchtomcat** [comment]
> It's a work in progress. It'll get there.

Doesn't help that ED's base code is inconsistent too lol. 

If the value in quotations is the "key," what is the value (A_4E_C, etc.) called?

**Comment by DanAlbert** [comment]
The value. https://en.wikipedia.org/wiki/Name%E2%80%93value_pair

Note that the value here is really uninteresting to players; it's just a variable name and has absolutely no meaning outside the python code. One of these days someone will find the time to generate these lists or build an editor or something, but I don't see that being our biggest problem any time soon.

**Comment by DanAlbert** [comment]
(reformatted some of that section to remove clutter and focus the bit about quotes; should help)
