### ISSUE TITLE
Super Carrier Selected Still Places Stennis

### ISSUE THREAD

**Issue by blglenn-sec** [dcs-liberation/dcs_liberation#1214]
Before filing, please search the issue tracker to see if the issue has already been reported.

If reporting a DCS AI bug, check https://github.com/dcs-liberation/dcs_liberation#dcs-bugs.

**Describe the bug**

**To Reproduce**
1. File -> New
2. Click on Next, Select Syria - Operation Mole Cricket 2010, Start Date  Modern-Spring 2010
3. Click Next, Get to Generator Settings, Select User Supercarrier Module
4. Click Next, Next, Finish
5. 
**Expected behavior**
A super Carrier should be on the map and in the mission editor when launched. 

**Additional information**

We will usually need more information for debugging. Include as much of the following as you are able:

- DCS Liberation save file
[SuperCarrierMissing.zip](https://github.com/dcs-liberation/dcs_liberation/files/6641567/SuperCarrierMissing.zip)

**Version information (please complete the following information):**
 - DCS Liberation 3

**Additional context**
Pretty straight forward, still shows up as the Stennis.

![image](https://user-images.githubusercontent.com/80610198/121763338-d2ae2a00-cb00-11eb-8842-3253a4485704.png)

**Comment by DanAlbert** [comment]
The carrier generated in the mission should be a supercarrier. The name that appears in the Liberation map is meaningless since you can toggle supercarrier on and off whenever you want, but the name of the "base" needs to stay the same.

**Comment by DanAlbert** [comment]
https://github.com/dcs-liberation/dcs_liberation/issues/156 is the bug that covers trying to name things more consistently, FYI.
