### ISSUE TITLE
Cannot Progress: Liberation 3.0 does not connect to DCS and creates no State.JSON

### ISSUE THREAD

**Issue by dasrehzockt** [dcs-liberation/dcs_liberation#1219]
Since 3.0, Liberation does not seem to recognize or connect to my ingame progress and also does not create a state.json file in its directory that i could use to manually progress the campaign. the window saying "waiting for mission completion" stays as it is when you have not startet the mission yet. even after flying the mission, it's still the same, leaving me only with the option to abort mission or manually submit results, which would require a state.json.
it is a new and compatible campaign, everything set pretty much as standard, only changed income multipliers, factions & date and activated most of the scripts available. 

(the mission itself worked out flawlessly)

never had this problem before, hope theres an easy fix or workaround :)

**Comment by DanAlbert** [comment]
Probably forgot to launch Liberation before DCS, or forgot to override the MissionScripting.lua file manually if using a dedicated server.

If it's neither of those things there's not enough information here. All we can do for bugs we can't reproduce is guess, and that's the only guess I have.

**Comment by dasrehzockt** [comment]
thanks a lot for your very rapid response!
i have checked multiple times and liberation was launched before DCS and it is not a dedicated server.
This seems to be related to the following bug and seems to only happen with campaigns, that are affected by the following bug already reported: 
https://github.com/dcs-liberation/dcs_liberation/issues/1218
mainly affecting Humble Helper campaign and probably other Syria campaigns involving Al Tha'Lah AB as strategic node are broken as well.

So this is reproducable by doing as follows, i did it three times to be shure:
- Create a new campaign in liberation that includes Al Tha'Lah AB (Humble Helper)
- Press Take off
- Start the mission in DCS
- While loading it will throw the error showcased in ticket 1218 my guess is that this seems to prevent liberation from hooking up with DCS in some way
- After the mission has loaded completely in DCS and you are in cockpit go back to the liberation window and you will see, that the window saying 'waiting for mission completion' stays as it is, as if you have not startet the mission yet. it does not show any progress and leaves you only the option to 'abort mission' or submit results manually, which is not possible, since state.json does not get generated at all, when bug 1218 occurs

So to conclude, the Humble Helper Campaign seems to be broken and other syria campaigns might be affected as well (i did not check, since this could become a problem not right from the beginning but mid or even late in game after capturing nodes)

Workaround: play camapaigns that exclude Al Tha'Lah AB
