### ISSUE TITLE
Set Liveries for Squadrons

### ISSUE THREAD

**Issue by dasrehzockt** [dcs-liberation/dcs_liberation#1222]
i would really like to set certain liveries for my flights. at first i thought this could be done in the loadout menu. however, doing this for every package would be very tedious.
BUT, since 3.0 we have squadrons! it would be really cool, to assign certain skins to each squadron or maybe even custom skins for single pilots, that are consistent for the whole campaign. so in theory, i can assign a personal livery for each of my wingmates at the beginning of a campaign and am done, instead of doing this either in Mission Editor or just being able to change my own livery when ingame.
i also thought that it might not really possible for Liberation to get a list of what liveries would be available on machine, but since 3.0 the loadout menu grabs my custom loadouts as well and so i thought this should be doable for liveries as well.

i hope this can be done in some way and keep up the good work :)

**Comment by DanAlbert** [comment]
That's already a thing: https://github.com/dcs-liberation/dcs_liberation/wiki/Squadrons-and-pilots

**Comment by dasrehzockt** [comment]
awesome! but i'd like to add, that it would be nice to change squadrons and create new ones via the liberation UI. would love to see this in the near future! thx alot
