### ISSUE TITLE
AI ground purchasing system does not work if faction does not have a tank

### ISSUE THREAD

**Issue by docofmur** [dcs-liberation/dcs_liberation#1225]
Before filing, please search the issue tracker to see if the issue has already been reported.

If reporting a DCS AI bug, check https://github.com/dcs-liberation/dcs_liberation#dcs-bugs.

**Describe the bug**
I tried this on multiple campaigns and factions, the AI will not purchase vehicles correctly if the faction does not have a Tank type vehicle. I will upload the 2 test factions I used, it is the standard PMC Russian faction and a copy with the T-55 added in. This happened with other non-tank factions this is just the testing bed I used to confirm the Bug

**To Reproduce**
1.   Load up any campaign with any blue faction. Use standard PMC - Russian faction. Don't worry about buying your vehicles, just click skip turn. You will see that every time they have bought the same 6 vehicles. You can check the enemy income intel and see they have extra money but won't use it. multiple skipped turns and nothing changes.
2.   Load up the same settings except use the faction provided which is exactly the same except the T-55 has been added. repeat procedure for skipping the first turn and you will see the enemy has bought multiple vehicles, and subsequent turns shows them spending more up the limits of the campaign.

**Expected behavior**
Either we need clear information of what vehicle classes MUST be in factions so they can be modified and fixed in an update or the enemy should be able to function without certain vehicles. 

**Uploaded files**
I am adding a clean log file with only the non-tank faction, creation of campaign, and the skipping of 4 turns.
No mission file was ever created, so there is nothing to upload from that.
Both Factions I used for testing are added as a txt documents since we can't upload json files here.

[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/6643094/liberation.log)
[pmc_russian.txt](https://github.com/dcs-liberation/dcs_liberation/files/6643096/pmc_russian.txt)
[pmc_russian_tank.txt](https://github.com/dcs-liberation/dcs_liberation/files/6643098/pmc_russian_tank.txt)

**Version information (please complete the following information):**
 - DCS Liberation 3.0 release

**Additional context**
Faction customization is pushed heavily on the discord as a simple thing people can do to change their Liberation experience, we either need info added to the wiki explaining what vehicles are what type and which types must be needed and so on, or the system needs to work.

**Comment by docofmur** [comment]
further testing shows its the MBT OR Tank sub-categories of the mission editor that are required to make a faction work, not certain on if any others are needed yet, will test that more later and update on here

**Comment by docofmur** [comment]
This was solved by build #1933 already tested and a tank is no longer required

**Comment by DanAlbert** [comment]
That hasn't merged.
