### ISSUE TITLE
AI will not buy aircraft correctly if faction is missing a CAP capable aircraft

### ISSUE THREAD

**Issue by docofmur** [dcs-liberation/dcs_liberation#1228]
Before filing, please search the issue tracker to see if the issue has already been reported.

If reporting a DCS AI bug, check https://github.com/dcs-liberation/dcs_liberation#dcs-bugs.

**Describe the bug**
Basically what the title says, if you have a faction that does not have a CAP capable aircraft then it will only buy a few aircraft and just stop buying them, even if they have lots of money and spaces available. This is very similar to the Tank issue with buying vehicles. 

**To Reproduce**
Create a faction with any aircraft makeup as long as there isn't a CAP capable aircraft in the faction. I tried multiple configurations and while the exact number they buy might change the same thing happens. They will stop before they are full up on slots.

**Expected behavior**
AI factions should buy aircraft till slots are full and utilize them to their capability. Obviously there is a buying priority order and that should still be followed but we need exceptions for non-standard factions

**Version information (please complete the following information):**
 - DCS Liberation 3.0 and build # 1932 (current when finding this bug)

**Additional context**
I think this is part of what is broken about helicopters also. DCS AI obviously has an issue with helo's also but since the factions won't buy them in any quantity its hard to test what might be the problem.

I left out log files as there really isn't anything to find, pretty sure there just needs to be an exception added in to the buying system to allow for no CAP planes.

**Comment by DanAlbert** [comment]
Submitted a probably fix. lmk if it's still an issue.

**Comment by docofmur** [comment]
I just tested this with build #2056 and the same issue is happening, If you don't have a CAP plane in the faction the AI doesn't buy aircraft correctly. Basically it seems to be reserving parking slots on airbases for CAP planes and not allowing anymore to be bought. Thats all I can think of for why its happening.

**Comment by DanAlbert** [comment]
Can you give an example of a faction with this problem?

**Comment by docofmur** [comment]
yeah I had to make a custom one to test this, the premise I am working on is a helo style campaign with only AI helo's and cas. In this case I just modified 1970  russian air just as a test bed. Had to upload as a txt file since this support JSON. 

Bascially any faction with the CAP planes (planes that have the BARCAP task) removed causes this problem. You can run a few turns and see that they only buy a few CAS and Helo's and leave everything else empty. I've tried with multiple campaigns testing to see if its a distance thing, doesn't seem to make a difference.

[russia_1970_limited_air.txt](https://github.com/dcs-liberation/dcs_liberation/files/6682934/russia_1970_limited_air.txt)

**Comment by DanAlbert** [comment]
Works for me

![image](https://user-images.githubusercontent.com/315852/122688455-21c71f80-d1d1-11eb-98c6-a85b4962e002.png)

[helo only.liberation.txt](https://github.com/dcs-liberation/dcs_liberation/files/6683081/helo.only.liberation.txt)
[russia_1970_helo_only.json.txt](https://github.com/dcs-liberation/dcs_liberation/files/6683082/russia_1970_helo_only.json.txt)

**Comment by docofmur** [comment]
ummm ok I guess AI means the automated buying for player faction. I meant enemy AI, the enemy faction, the enemy won't buy aircraft....which I just tested with latest build, and it still doesn't work

**Comment by DanAlbert** [comment]
![image](https://user-images.githubusercontent.com/315852/122689693-81292d80-d1d9-11eb-8334-117c405cb058.png)

![image](https://user-images.githubusercontent.com/315852/122689704-930ad080-d1d9-11eb-8d2d-0e8e656f01e7.png)

**Comment by docofmur** [comment]
alright idk guess its me i'll figure it out
