### ISSUE TITLE
Liberation 3.0 can't generate inverted Normandy campaign

### ISSUE THREAD

**Issue by ali4000** [dcs-liberation/dcs_liberation#1232]
**Describe the bug**
Trying to generate a Normandy campaign with the "invert map" option in order to play as Germans will fail with the "Incompatible Save game" message, despite no save game existing.

**To Reproduce**
1. Start new Normandy campaign, check invert map, select e.g. summer 1944 period
2. Select player faction = Germany 1944 and Enemy faction = Allies 1944
3. Continue to select No Carriers, No LHAs, No player navy, No enemy navy etc in campaign options (doesn't matter)
4. On clicking Finish, the frontlines are shown on the map but the "incompatible save game" popup appears. When clicking Ok, all units disappear from map again.

**Expected behavior**
Normandy campaign can be played as Germans with inverted map.

**Additional information**
- The error only occurs if using the "invert map" option on Normandy
- The exact same time period/faction/option settings work with "invert map" on e.g. Caucasus and Syria.
- Python console log 'liberation3.txt' attached.
- Error message popup 'liberation3.png' attached.

[liberation3.txt](https://github.com/dcs-liberation/dcs_liberation/files/6644632/liberation3.txt)
![liberation3](https://user-images.githubusercontent.com/48153528/121821576-2bfd9100-cc9a-11eb-85cc-78f27b981e1c.png)

**Version information (please complete the following information):**
 - DCS Liberation Open Beta 2.7.1.7139

**Additional context**

**Comment by DanAlbert** [comment]
This campaign apparently doesn't support inversion. You can briefly see this before closing the error window (at which point it clears the UI because the game failed to load):

![image](https://user-images.githubusercontent.com/315852/122628930-068fcf00-d06e-11eb-86ff-a08da224b612.png)

Over to @Khopa since he's the campaign owner.
