### ISSUE TITLE
Aircraft Missing EPLRS(on) Waypoint Action

### ISSUE THREAD

**Issue by jeetsukumaran** [dcs-liberation/dcs_liberation#1237]
**Describe the bug**

At least as of build #1936, all aircraft are missing the "EPLRS(on)" waypoint action. This action is typically added at the first waypoint (under "Perform Command" in the ME). It joins the aircraft to the data link network.

**To Reproduce**
1. Generate a mission using build #1936
2. Confirm no aircraft have "EPLRS(on)" actions in the ME
3. In the game, no friendly aircraft are visible in the SA display (in, for e.g. the Hornet), whether or not there is an AWACS

**Expected behavior**
All aircraft need to have Perform Command > EPLRS(on) as one of their first waypoint actions for datalink functionality,

**Additional information**

We will usually need more information for debugging. Include as much of the following as you are able:

**Version information (please complete the following information):**
 - DCS Liberation [e.g. 2.3.1]: Build #1936

[Current.00.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/6662301/Current.00.liberation.zip)
[liberation_nextturn.zip](https://github.com/dcs-liberation/dcs_liberation/files/6662304/liberation_nextturn.zip)

**Comment by jeetsukumaran** [comment]
For what it's worth, Build #1919 is the last one in which EPLRS was correctly activated for all aircraft. 

By Build #1923, this bug has been introduced. 

I could not pin it down more narrowly thanthat, due to not having any factions with datalink-capable aircraft available in the intervening builds.

I guess since the builds in this range (1920, 1921, 1923) mostly have to do with wrapping PyDCS units, it makes sense.

**Comment by DanAlbert** [comment]
I already found the problem. The DCS update today means I haven't had time to fix it.
