### ISSUE TITLE
Add the Targeting Pods to the Date Restrictions (litening and atflir)

### ISSUE THREAD

**Issue by NeelKulkarni6** [dcs-liberation/dcs_liberation#1240]
The targeting pods ATFLIR and LITENING II are not affected by the date restrictions option as of version 3.0. 

The ATFLIR was made in December of 1999 and LITENING II in 2003.

![image](https://user-images.githubusercontent.com/77650484/122282778-a5ff6700-cea0-11eb-931b-21214a4eab3a.png)
atflir targeting pod equipped in 1995, with the restrict weapons by date option on

**Comment by DanAlbert** [comment]
They are (or at least were; I've seen them removed in my games), but whoever filled out that data disagrees on the dates. Source?

**Comment by Mustang-25** [comment]
As far as LITENING goes, here's the [Air Force fact sheet](https://www.af.mil/About-Us/Fact-Sheets/Display/Article/104571/litening-advance-targeting/) which has it IOCing in 1999 with the initial version of the LITENING II and the ER version IOCing in 2003. Given the lack of these distinct versions, I think we should just set it at '99 to give the players more flexibility.

I haven't seen any primary source documentation on the ATFLIR IOC date yet though.

**Comment by NeelKulkarni6** [comment]
For the ATFLIR, I have a pretty reliable source saying it was initially tested on [December of 1999, then was supposed to have its IOC on **May 2002**, but due to funding it got pushed back](https://fas.org/man/dod-101/sys/smart/atflir.htm). 

[Another Source ](https://www.deagel.com/Sensor%20Systems/ANASQ-228%20ATFLIR/a001647) says it had its IOC in **2003.** The problems with this one are; 1.  it doesn't give a specific date or even month, 2. it cites no sources.

Whether it should be Dec 1999 or 2002/3  is up to you guys, but I think some sort of restriction needs to be added. As the picture shows, it shouldn't be an option in 1995. If the aftflir is currently restricted then it's definitely at too early a time.

**Comment by Mustang-25** [comment]
Dates have been updated and will be reflected in the next release.
