### ISSUE TITLE
Bug since DCS 2.7.2.7910.1

### ISSUE THREAD

**Issue by Meyomyx** [dcs-liberation/dcs_liberation#1245]
**Describe the bug**
"Player" aircraft are set as AI aircraft in ME since DCS 2.7.2.7910.1 Open Beta

**To Reproduce**
1. Create a turn in Liberation with a player flight
2. Check ME. The player aircraft shows as "Veteran", yet if you use the drop down, "Player" is highlighted in yellow
3. If not corrected, there are no player flights. Can be corrected in ME by actually selecting the player flight

**Additional information**

It's not clear if this is a quirk of the new DCS release or the way player flight assignments in Liberation are transferred to the new version .... but you should be aware of the issue in case changes are needed

**Version information (please complete the following information):**
 - DCS Liberation 3.0

**Additional context**

![bug1](https://user-images.githubusercontent.com/70166005/122379290-a2321a00-cf5e-11eb-9bf1-aec5d5dd2e7a.jpg)

![bug2](https://user-images.githubusercontent.com/70166005/122379336-ae1ddc00-cf5e-11eb-9786-51ed9ae998e4.jpg)

[liberation_nextturn.zip](https://github.com/dcs-liberation/dcs_liberation/files/6669377/liberation_nextturn.zip)

**Comment by kevotosmart** [comment]
Can confirm I’ve had this happen a couple times, thought it was user error

**Comment by Hornet2041** [comment]
the mission works fine if you dont check the mission editor first, it'll let you spawn as normal. I do get the mission editor bug, but I'm also unable to reproduce the .miz error when generating a mission from either Liberation v3.0 or the current dev builds.

could you also upload the .liberation campaign save file? thanks

**Comment by Meyomyx** [comment]
.liberation file is in the attached zip.

I did delete a flight with a "player" flight and then created another - just in case this is significant

**Comment by Hornet2041** [comment]
only the .miz mission file is in the zip, not the actual campaign file that liberation generates when you save a campaign

**Comment by Meyomyx** [comment]
[UAE Assault Bug.zip](https://github.com/dcs-liberation/dcs_liberation/files/6679945/UAE.Assault.Bug.zip)

This should have been in the zip - apologies

**Comment by DanAlbert** [comment]
Not happening on current builds. Assuming this was just a pydcs-out-of-date issue.
