### ISSUE TITLE
Update for Operation Allied Sword (faction)

### ISSUE THREAD

**Issue by sgtfuzzle17** [dcs-liberation/dcs_liberation#1249]
* Campaign name: Operation Allied Sword (faction)
* Files: 
[Syria-Lebanon_2005_Allied_Sword.zip](https://github.com/dcs-liberation/dcs_liberation/files/6674562/Syria-Lebanon_2005_Allied_Sword.zip)
* Update summary (optional): Removed non-existent units from Syria-Lebanon 2005 (Allied Sword) faction list. All units listed should be properly available now.

**Comment by DanAlbert** [comment]
> All units listed should be properly available now.

Except the DCS update is going to rebreak all of them :( That's is why I suggested waiting for the next release. Sorry, I should have been more explicit.

**Comment by sgtfuzzle17** [comment]
Ah, my bad. I'll keep an eye out for the next update.

________________________________

**Comment by DanAlbert** [comment]
No worries, just wish I could have saved you the trouble!

**Comment by sgtfuzzle17** [comment]
All good, only took me 5 minutes. When would be a good time to submit the new Cyprus campaign I've built?

________________________________

**Comment by DanAlbert** [comment]
I'll notify the campaign maintenance channel in discord once we think it's time to start poking. Should be this weekend.

**Comment by DanAlbert** [comment]
(not sure if you saw in the channel but should be good to go now)

**Comment by sgtfuzzle17** [comment]
Update files for Allied Sword campaign/factions for 4.0 release:
[resources.zip](https://github.com/dcs-liberation/dcs_liberation/files/6698890/resources.zip)
**Changelog:**
Moved frontlines to better work with updated exclusion zones and to avoid urban areas, [see other issue](https://github.com/dcs-liberation/dcs_liberation/issues/1263)
Updated campaign .json file for 4.0 version number (6.1)
Updated faction files to work with 4.0 system/naming conventions
