### ISSUE TITLE
[Build 1971] Payload Display Shows Underscores Instead of Spaces (again)

### ISSUE THREAD

**Issue by Mustang-25** [dcs-liberation/dcs_liberation#1257]
The Payload UI is back to showing spaces as underscores again. Picture below.

**To Reproduce**
1. generate new campaign
2. use default settings
3. automate purchasing
4. click on any flight and observe payload tab.

**Expected behavior**

**Additional information**

Save attached below.

![image](https://user-images.githubusercontent.com/72566076/122578782-14f7cf80-d009-11eb-87c1-42d0d3e37fc6.png)

[Build 1971 Payload Underscore Bug.zip](https://github.com/dcs-liberation/dcs_liberation/files/6677757/Build.1971.Payload.Underscore.Bug.zip)

**Comment by Hornet2041** [comment]
#993 duplicate thread :P

**Comment by Mustang-25** [comment]
Ah ok. Didn't see that you had reopened it. I'll close this one out.
