### ISSUE TITLE
[Build 1971] Carrier and LHA Improperly Show Red Damage Bar

### ISSUE THREAD

**Issue by Mustang-25** [dcs-liberation/dcs_liberation#1258]
The carrier and LHA will show the red dead bar even when they are newly spawned. Campaign save on turn one attached below (file name for another bug but this bug is also present).

**To Reproduce**
1. generate any campaign with a carrier
2. observe red bar even on the first turn

**Expected behavior**
Red bar should only be present when carrier is destroyed.

![image](https://user-images.githubusercontent.com/72566076/122584078-c6e5ca80-d00e-11eb-9e49-46b550984965.png)

[Build 1971 Payload Underscore Bug.zip](https://github.com/dcs-liberation/dcs_liberation/files/6678005/Build.1971.Payload.Underscore.Bug.zip)

**Comment by Hornet2041** [comment]
The carrier is correctly showing a red bar because it is incorrectly spawning dead? / runway damaged 

![image](https://user-images.githubusercontent.com/55866858/122598983-9b2d0980-d03b-11eb-9089-bcb94ce77e95.png)

**Comment by Hornet2041** [comment]
The Chinese LHA spawns damaged in Liberation v4. The other LHA units do not spawn damaged still. 


![image](https://user-images.githubusercontent.com/55866858/124016517-bdb41080-d9b3-11eb-8a7a-d591b1f7ed09.png)
![image](https://user-images.githubusercontent.com/55866858/124016529-c278c480-d9b3-11eb-8950-065ea146d3d3.png)

**Comment by Hornet2041** [comment]
factions using the Chinese type 071 need to have their names updated to

"helicopter_carrier": [
    "Type_071"
