### ISSUE TITLE
[Build 1971] Blue AI Purchaser not Purchasing AEW&C Aircraft in Battle for UAE

### ISSUE THREAD

**Issue by Mustang-25** [dcs-liberation/dcs_liberation#1259]
The Blue auto purchaser is not buying any AEW&C aircraft in this campaign. It seems to be specific to this campaign because I've tried generating other campaigns and all of them will auto-purchase some AEW&C aircraft. 

**To Reproduce**
1. Generate Battle for the UAE campaign
2. Default settings but include supercarrier
3. select auto-purchase ground and air units
4. observe lack of AEW&C aircraft
5. Generate and repeat with any other campaign
6. observe purchasing of AEW&C aircraft

**Expected behavior**
Blue should be purchasing E-2s or E-3s like in any other campaign.

**Additional information**
Campaign Save attached below:

[Build 1971 Campaign no AWACS Bug.zip](https://github.com/dcs-liberation/dcs_liberation/files/6678500/Build.1971.Campaign.no.AWACS.Bug.zip)

**Comment by Hornet2041** [comment]
Its not spawning or buying any carrier aircraft because the carrier spawns dead/runway damaged in build 1971.

#1258

**Comment by DanAlbert** [comment]
That'd be a reason to not buy an E-2 at the CV, but it I'd think it'd fall back to an E-3 at an airfield, so probably still a second problem here.

**Comment by Mustang-25** [comment]
> but it I'd think it'd fall back to an E-3 at an airfield

Is the AWACS at the bottom of the purchasing priority list and the air base fills up before it can get to it on the list?

**Comment by Hornet2041** [comment]
nah, i get awacs being bought fine on invasion of dubai campaign fine, but that might be because the carrier spawns in the hormuz strait instead of on the other side of the map.

**Comment by Hornet2041** [comment]
from discord discussion:

seems like if a campaign has a carrier group and its not within range of any other friendly airbases, the purchaser wont buy it, and if a player buys it then it won't even task it

demonstration campaign files attached
[awacs.zip](https://github.com/dcs-liberation/dcs_liberation/files/6679734/awacs.zip)

on the before save, i sold some aircraft at Incirlik to make room for awacs and have money. on the after save, you can see that it did not buy any awacs

to reproduce, start new campaign of syria full map or battle for dubai, then move the carrier group about 200 miles or more from the closest friendly base. you'll see that AWACS stops being tasked and it won't even buy it.
