### ISSUE TITLE
Operation Allied Sword has units spawn in water, on runway, and on rooftops

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#1263]
**Describe the bug**
A number of different spawn locations has units spawn on runways, the ocean, and rooftops.  It's possible there are more, but I had culling enabled.

**To Reproduce**
1. Start Operation Allied Sword campaign with default factions.

**Expected behavior**
Units to not appear in water.

**Additional information**
[CampaignAndMission.zip](https://github.com/dcs-liberation/dcs_liberation/files/6679724/CampaignAndMission.zip)

**Version information (please complete the following information):**
 - DCS Liberation 3.0.0:
 
![Screen_210618_155743](https://user-images.githubusercontent.com/74509817/122625648-882e2f80-d063-11eb-904c-bf44e119f4b8.png)

![Screen_210618_155746](https://user-images.githubusercontent.com/74509817/122625658-8cf2e380-d063-11eb-90a8-cb4f60265818.png)

![Screen_210618_160010](https://user-images.githubusercontent.com/74509817/122625663-92e8c480-d063-11eb-947e-0a7dd76194a3.png)

![Screen_210618_155754](https://user-images.githubusercontent.com/74509817/122625660-8fedd400-d063-11eb-884b-53612052729b.png)

![Screen_210618_155712](https://user-images.githubusercontent.com/74509817/122625666-95e3b500-d063-11eb-9690-d5f64103bdc8.png)

![Screen_210618_155721](https://user-images.githubusercontent.com/74509817/122625668-97ad7880-d063-11eb-95f4-1c0f313182f8.png)

**Comment by DanAlbert** [comment]
@sgtfuzzle17

**Comment by sgtfuzzle17** [comment]
I’ll look into revising the path markers once the new exclusion zones are in.

On 19 Jun 2021, at 10:38 am, Dan Albert ***@***.***> wrote:

﻿

@sgtfuzzle17<https://github.com/sgtfuzzle17>

**Comment by Khopa** [comment]
Note : Preset units do not use the exclusions zones. The generator assume that the chosen location can contains any SAM sites.

For long range air defenses, you should have a 1000 ft radius of open ground around the chosen location (Max possible size for such sites (e.g : Patriot, S-300)
For short range air defense : a ~800 ft radius of open ground
...

We failed to document that in the custom campaign page.
I edited the [wiki page](https://github.com/dcs-liberation/dcs_liberation/wiki/Custom-campaigns), and added recommended value in the quick reference table.
