### ISSUE TITLE
Could not find QTWebEngineProcess.exe

### ISSUE THREAD

**Issue by VAGGOSST** [dcs-liberation/dcs_liberation#1265]
Hello.
Just downloaded version 3.0.0 (twice to make double sure) and i have the same problem both times.
Any suggestions?

![liberation ptoblem](https://user-images.githubusercontent.com/31065901/122631157-2bb62900-d0d2-11eb-982c-35957518c68c.jpg)

**Comment by DanAlbert** [comment]
If you install it outside your user directory (maybe to `C:\liberation`) does it work? No one else has reported it and it wouldn't be the first time software has issues with non-latin character sets :( (it's outside our code, so it'll that is a problem there's nothing we can do to fix it, so would be good to rule out if nothing else)

**Comment by VAGGOSST** [comment]
> If you install it outside your user directory (maybe to `C:\liberation`) does it work? No one else has reported it and it wouldn't be the first time software has issues with non-latin character sets :( (it's outside our code, so it'll that is a problem there's nothing we can do to fix it, so would be good to rule out if nothing else)

No i haven't. (will do and report back)

Version 2.5 is installed outside C: directory and works like a charm

**Comment by VAGGOSST** [comment]
Extracted to C: and works!

**Comment by DanAlbert** [comment]
Ugh. That's a really annoying bug that I'm pretty sure we have little control over. Glad you have a workaround, sorry something here doesn't seem to work with Greek.

**Comment by VAGGOSST** [comment]
> Ugh. That's a really annoying bug that I'm pretty sure we have little control over. Glad you have a workaround, sorry something here doesn't seem to work with Greek.

I haven't used any Greek, but don't worry about it..
It works..so..fine by me!

**Comment by DanAlbert** [comment]
> I haven't used any Greek, but don't worry about it..

I'm referring to the path name in the title of the command window in your screenshot rather than anything you'd done in Liberation. It looks like the directory you originally installed Liberation to has Greek characters in the path, and I'm guessing that is tripping up something that only works with ASCII.
