### ISSUE TITLE
[Build 2011] CVN and LHA Inventory Won't Update Without Closing the Window

### ISSUE THREAD

**Issue by Mustang-25** [dcs-liberation/dcs_liberation#1275]
**Describe the bug**

Purchasing/selling aircraft on the carriers will not update any elements on the window. This includes the total inventory, number of aircraft purchased, and the "+" and "-" buttons do not actuate at all when clicked.

Closing and re-opening the windows will show the updated totals. This behavior does not exist for land bases.

The log shows the following error:

![image](https://user-images.githubusercontent.com/72566076/122649888-f7983380-d0e4-11eb-9e5e-0541dfa1593c.png)

**To Reproduce**
1. generate any campaign with carriers on this build
2. On turn 0, attempt to purchase aircraft on the carriers
3. observe reported bug

**Expected behavior**
Inventory should be updated without cycling the window.

Save attached below:
[Build 2011 Carrier UI bug.zip](https://github.com/dcs-liberation/dcs_liberation/files/6681051/Build.2011.Carrier.UI.bug.zip)

**Comment by DanAlbert** [comment]
https://github.com/dcs-liberation/dcs_liberation/pull/1273
