### ISSUE TITLE
Support Aircraft Missions Should Default to Single Aircraft

### ISSUE THREAD

**Issue by jeetsukumaran** [dcs-liberation/dcs_liberation#1279]
**Is your feature request related to a problem? Please describe.**

When scheduling a new mission, the dialog prepopulates with a default of 2 aircraft assigned to the mission.  

**Describe the solution you'd like**

This default works for most missions. However, for support missions -- AWACS/AEW and refueling -- it would be nice if it defaulted to single.

**Additional context**

This is just a QOL enhancement and a low priority one at that, as it is easy enough to change. (Though also easy to overlook as well!)

(If the OPFOR AI frags two aircraft per support mission, however, then it's a bug and not just a QOL thing).

**Comment by DanAlbert** [comment]
(assigning @SnappyComebacks since it sounded like they were looking at this earlier)

**Comment by jeetsukumaran** [comment]
This may need to be re-opened; in at least build #2826, support missions default to two aircraft
