### ISSUE TITLE
Around the Mountain campaign update request 

### ISSUE THREAD

**Issue by docofmur** [dcs-liberation/dcs_liberation#1280]
@DillieKoe
Please update this campaign when able or let us know in discord if you don't have the time, and we can find someone to help.
This campaign is missing required items to make it a playable campaign. It needs Factories and Ammo depots added in as a minimum to be playable. If you were trying to design something specific a more in-depth description would help too. Look at the wiki if you have any questions on these items.

**Comment by DillieKoe** [comment]
[around_the_mountain.zip](https://github.com/dcs-liberation/dcs_liberation/files/6688298/around_the_mountain.zip)
Tried to fix it tell me if it still misses something

**Comment by docofmur** [comment]
I'll check it out and let you know

**Comment by docofmur** [comment]
very nice update, i'll add it in today, It was odd playing from the russian side for me but really has an interesting twist too it with so few SAM's

**Comment by DanAlbert** [comment]
I don't see this merged anywhere. Why was it closed?

**Comment by docofmur** [comment]
working it now putting a bunch of them in sorry i'll leave them open from now on

**Comment by DanAlbert** [comment]
Gotcha. If bugs are closed we can't see that the release is missing them.

**Comment by docofmur** [comment]
so should I close these once I make a PR with the files fixing them? @DanAlbert

**Comment by DanAlbert** [comment]
No, I will close them once I've made sure the fixes are in all the appropriate branches.

I took a quick peek and I don't see a single ammo depot anywhere on the map. Did you intend for all the front lines to be limited to  15 units? @DillieKoe

**Comment by docofmur** [comment]
last enemy base has an ammo depot, I assumed as a boss fight. Its different but actually plays kinda nice having such a small frontline, more air based

**Comment by DanAlbert** [comment]
Ah, I'd overlooked that. Definitely fine to not include them, I just wanted to make sure it was intentional :)
