### ISSUE TITLE
liberation 3.0 missing wepons

### ISSUE THREAD

**Issue by Tinchus2009** [dcs-liberation/dcs_liberation#1284]
Before filing, please search the issue tracker to see if the issue has already been reported.

If reporting a DCS AI bug, check https://github.com/dcs-liberation/dcs_liberation#dcs-bugs.

**Describe the bug**
 I have just installed version 3.0 and Im seeing some aircrafts like the su-25 have missing eapons on they lodouts. For example, there is no VIKHR missles on the su-25, or KH anti radar missiles.

The faction I have chosen is the REDFOR (russia)2010

**To Reproduce**

**Expected behavior**

**Additional information**

We will usually need more information for debugging. Include as much of the following as you are able:

- DCS Liberation save file (the `.liberation` file you save from the DCS Liberation window). By default these are located in your DCS saved games directory (`%USERPROFILE%/Saved Games/DCS`).
- The generated mission file (the `.miz` file that you load in DCS to play the turn). By default these are located in your missions directory (`%USERPROFILE%/Saved Games/DCS/Missions`).
- A tacview track file, especially when demonstrating an issue with AI behavior. By default these are located in your Tacview tracks directory (`%USERPROFILE%/Documents/Tacview`).
- The state.json file from the finished mission when the problem is related to results processing. By default these are located in your Liberation install directory.

**Version information (please complete the following information):**
 - DCS Liberation3.0 latest

**Additional context**

**Comment by MaHuJa** [comment]
I think the weapons mentioned are available on Su-25T only. The plain Su-25 is supposedly all dumb weapons.

**Comment by docofmur** [comment]
Can not duplicate, Checked the Su-25T and anti-radiation missiles and VIKHR missiles are present and used. The Su-25 does not have these as they are not equipped on the aircraft. Confirmed with DCS ME for loadout restrictions
