### ISSUE TITLE
Cannot create new Campaign in 4.0.0-2042 build

### ISSUE THREAD

**Issue by dasrehzockt** [dcs-liberation/dcs_liberation#1286]
steps to reproduce:

try to create a new campaign

when trying to press the 'finish' button, nothing happens. the gamecreation window does not disappear and no campaign is generated. tried multiple campaigns on caucasus and syria so far, none working. also could not load my old saved ones, just nothing when tryin to load.

**Comment by Malakhit** [comment]
Hi @dasrehzockt - do you have any logs from the terminal window for these instances of failed campaign creation? They'd help us to determine what's going wrong.

**Comment by dasrehzockt** [comment]
yeah, i found the problem, i just got the same idea right now (dunno why i haven't looked earlier, sry) and it seems to be my custom squadrons is copied over from the previous build.

KeyError: 'Could not find any aircraft named FA-18C_hornet'

that seems to be the problem, however i don't know how i should name it now, instead of what was working until this very moment.

here's more of the errors it gave me, hope it's enough to clear this up:


> The above exception was the direct cause of the following exception:

>Traceback (most recent call last):
>  File "game\squadrons.py", line 332, in load_squadrons_from
>  File "game\squadrons.py", line 249, in from_yaml
>KeyError: 'Could not find any aircraft named FA-18C_hornet'

>The above exception was the direct cause of the following exception:

>Traceback (most recent call last):
>  File "windows\newgame\QNewGameWizard.py", line 115, in accept
>  File "game\theater\start_generator.py", line 101, in generate
>  File "game\game.py", line 147, in __init__
>  File "game\squadrons.py", line 347, in __init__
>  File "game\squadrons.py", line 302, in load
>  File "game\squadrons.py", line 336, in load_squadrons_from
>RuntimeError: Failed to load squadron defined by resources\squadrons\hornet\Jagdbombergeschwader 31.yaml

EDIT: ok, i have now updated the files to the namingconvention of F/A-18C Hornet (Lot 20). the '(Lot 20)' seemed to be the problem, however, now i have this same issue with the JF-17 squadrons, but in this case i've got no sample squadrons to look up what these should be named atm.
so it would be pretty neat, to have some kind of documentation in the wiki, for how every single unit should be adressed currently.

**Comment by Malakhit** [comment]
The JF-17 should be called `JF-17 Thunder` - you can find the unit names under the either the campaign `json` files, or the `resources/units/aircraft/${aircraft}.yaml` files.

**Comment by dasrehzockt** [comment]
thx alot for you support! now everything works fine!

EDIT: however the files you referenced do NOT mention any of the new names. hornet ist still without the (Lot 20) and the JF-17 is not mentioning the thunder besides in its discription. so looking up there does not help unfortunately.

**Comment by DanAlbert** [comment]
(changes in 4.x are mentioned in the docs https://github.com/dcs-liberation/dcs_liberation/wiki/Custom-Factions)
