### ISSUE TITLE
Some Squadron Liveries do not Work

### ISSUE THREAD

**Issue by dasrehzockt** [dcs-liberation/dcs_liberation#1287]
Some liveries i cannot get to work via Liberation. they work just fine when selecting via either mission editor or by rearming. however, while most ones seem to work just fine, i cannot figure out what the problem might be with those not showing up. they spawn with standard livery (first in the list).
i spent quite a lot of time trying to fix this e.g. by renaming inside the description.lua of each livery not working, however this did not help either.

these are examples not working for no reason:
https://www.digitalcombatsimulator.com/de/files/3303764/
https://www.digitalcombatsimulator.com/de/files/3302383/

but there are others, that are practically the same, done by the same author and those work just fine:
https://www.digitalcombatsimulator.com/de/files/3306957/

i could not spot the difference between these, that could potentially be causing this.

i hope you might have an idea why some planes show up with the standard livery and some do show up just as intended. since the skins seem to work fine without liberation i assume the problem might be with liberation. 
i could just change the skin when i am in mission, however, this obviously only works for my own plane and in a scenario not involving the US, this can be a real bummer. only way right now is to avoid these liveries.

**Comment by DanAlbert** [comment]
The easy answer would be that you used the wrong ID in the squadron file. There's not enough data here for us to investigate anything. If my guess is wrong provide the squadron file and we'll reopen.
