### ISSUE TITLE
Unable to write DCS Liberation state to [nil]

### ISSUE THREAD

**Issue by KBin87** [dcs-liberation/dcs_liberation#1293]
Hello all,

I am having trouble playing the latest version of DCS Liberation. When ever i start a mission I receive the following:
Unable to write DCS Liberation state to [nil]
then i goes on to tell me how to fix the issue but i am at a lost for what it is telling me. I admit, I am a novice when it comes to this. Can some on please help me out with a roadmap to make the requested repairs. 

Thank you all for your help.

R,

K

**Comment by RndName** [comment]
#730

**Comment by KBin87** [comment]
thank you all for the help. Issues resolved.
