### ISSUE TITLE
[Build #2087] Exception when clicking on AA ground object after reload

### ISSUE THREAD

**Issue by RndName** [dcs-liberation/dcs_liberation#1299]
**Describe the bug**
Exception when i click on a AA ground object after i reopenend liberation and loaded my fresh created campaign
`File "D:\workspace\dcs_liberation\qt_ui\windows\groundobject\QGroundObjectMenu.py", line 232, in update_total_value
    unit_type = next(GroundUnitType.for_dcs_type(vehicles.vehicle_map[u.type]))
StopIteration`

Seems to be happening only with AA Groups

This only occurs after the 2nd time opening the application! Directly after creation it works perfectly.
Fun Fact: If you freshly open liberation, create a random campaign, close this one and reopen the previous campaign its working.

I think something was not initialized when no campaign generation is hit...

**To Reproduce**
1. Create new campaign (I used Caucasus Full)
2. Click on AA Ground object (Example a patriot battery)
3. Save the game as new file
4. Completly close liberation
5. Open liberation again
6. load the saved file
7. Click on the AA Ground Object again -> Exception

**Expected behavior**
No Exception

**Additional information**
[test-V4-AA-T00.zip](https://github.com/dcs-liberation/dcs_liberation/files/6686141/test-V4-AA-T00.zip)

**Version information (please complete the following information):**
 - develop on commit https://github.com/dcs-liberation/dcs_liberation/commit/47e038c9fac61f0d04924dc1f2ea19b52de89c46

**Comment by DanAlbert** [comment]
> I think something was not initialized when no campaign generation is hit...

Good guess! The API for fetching unit types by name was calling the init, the one for fetching them by unit types was not.
