### ISSUE TITLE
No flight comms if player is selected on any slot other than top 3.0

### ISSUE THREAD

**Issue by InDiCa83** [dcs-liberation/dcs_liberation#1302]
**Description**
When editing a flight to add a player, if a player is added to any slot other than the top position you will have no comms with your flight, the game acts as though you are lead but you are not, the flight goes about its way without you.

**To Reproduce**
1. Edit any flight
2. Add player to any slot other than top "lead"
3. Start flight
4. Give flight commands but receive no response

**Expected behaviour**
Was not sure if this was unexpected behaviour so asked in discord and forwarded to post the issue here.
I would expect some sort of flight comms from selecting any other role than comms.

**Comment by DanAlbert** [comment]
Isn't this just DCS behavior?
