### ISSUE TITLE
Carrier planes should start at +1s

### ISSUE THREAD

**Issue by MaHuJa** [dcs-liberation/dcs_liberation#1309]
This is a workaround for a DCS problem.

**Is your feature request related to a problem? Please describe.**

When starting many planes from the carrier at the start of the mission (many ASAP missions), a traffic jam is almost inevitable, meaning perhaps none of the planes take off. The jam happens because the first planes to taxi want to go through the 'sixpack', where other planes are spawned, and waiting for the first plane to finish taxiing to a catapult before they take off.

**Describe the solution you'd like**

Planes only spawn in the sixpack when spawned at mission start.
I've come to start all carrier planes at one second past mission start, by unchecking ASAP and incrementing the second field.
I'd like ASAP to start carrier planes at 1 second by default.

There are still other causes for flight deck traffic jams, but they are relatively rare.

**Applying to players**

I have been doing this to the player flight as well, without the 'set player to start at 0' option - or even hopping into spectator for a few seconds. There is however, a case where this may be less appropriate - in multiplayer, with pause on load manual resume, with multiple players wanting to load into their cockpits before the mission timer starts.

A player without an AI wingman can move out of the way after other AI starts taxi, but may feel pressured to move because he's holding up flight ops while having an actual startup procedure to do.

**Comment by DanAlbert** [comment]
I'm missing something. How does a one second delay fix anything?

**Comment by clutchtomcat** [comment]
> I'm missing something. How does a one second delay fix anything?

The delay prevents any aircraft from spawning on the Sixpac, thus minimizing or preventing traffic jams with the AI, which have to taxi through the Sixpac to launch.

**Comment by KeithGadgetUK** [comment]
I've experienced this when AV8's take off from a carrier, they just sit in the middle of the flight deck stopping anything else from taking off or getting to the catapults.  

The way I get around this is to edit the carrier AV8 flights so they spawn in the air, not on the deck.  This stops there being a jam on the deck.

**Comment by clutchtomcat** [comment]
Harriers never operate from CV/CVNs except on a few rare exercises. Those should always be placed on LHAs/

**Comment by KeithGadgetUK** [comment]
> Harriers never operate from CV/CVNs except on a few rare exercises. Those should always be placed on LHAs/

Perhaps.  But then the game should not allow them to be purchased there.  Or allow the air assets to be transferred.  With the carriers all the transfer options are greyed-out for me.  :-)

**Comment by MetalStormGhost** [comment]
@MaHuJa could you verify that the build https://github.com/dcs-liberation/dcs_liberation/actions/runs/1206967117 / PR #1600 fixes the original issue?
