### ISSUE TITLE
Error in JSON Decoder preventing recognition of mission end

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#1313]
**Describe the bug**
This error appeared in the log window after ending a mission. Liberation did not detect mission end. State.json attached. Campaign is Exercise Vegas Nerve.

2021-06-22 15:29:17,842 :: INFO :: On Debriefing update
2021-06-22 15:29:17,842 :: DEBUG :: <game.debriefing.Debriefing object at 0x0000019C0945AD60>
Exception in thread Thread-308:
Traceback (most recent call last):
  File "threading.py", line 954, in _bootstrap_inner
  File "game\debriefing.py", line 390, in run
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
  json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

[state.json.zip](https://github.com/dcs-liberation/dcs_liberation/files/6691318/state.json.zip)

**Version information (please complete the following information):**
#2087

**Comment by Starfire13** [comment]
Manual selection of the state.json file did work, by the way.

I don't know if this is in any way related to my using Combined Arms to get some F-15Es to bomb a custom-defined strike target which I hadn't tasked a flight for (they had bombs left over and I figured, why not). The F-15Es dropped their bombs and hit the targets, but target destruction was not carried over to Liberation.

**Comment by DanAlbert** [comment]
I think we've seen cases where the state file starts being read before it's finished being written, which would explain why it caught an invalid parse that was fine later. If the manual submit of the state.json you submitted here is fine then I'm not sure what to investigate.

**Comment by Starfire13** [comment]
Hmm. Possibly. Any way we could delay the read of the file till it is no longer being written to? Or perhaps, to try again in, say, 3 seconds, if it doesn't work the first time?

**Comment by DanAlbert** [comment]
Added the retry behavior. No idea if that was actually the problem or not but seems plausible.
