### ISSUE TITLE
Can't save mission results after capturing Sukhumi Babushara airfield

### ISSUE THREAD

**Issue by KeithGadgetUK** [dcs-liberation/dcs_liberation#1317]
Liberation 3.0

No matter how many different ways I try, when playing the Caucuses map I cannot accept the mission totals if I capture the Red airfield Sukhumi Babushara.

Every time I try, the log shows the same error message "ValueError: Sukhumi-Babushara is not in the transit network."
Liberation sticks stating it is waiting for the mission to complete and will not allow me to progress.  I just cannot save any progress if I capture this airport.

Please advise what is wrong?

Thanks

**Comment by DanAlbert** [comment]
Can't do anything without the info the bug template asks for. Provide that and we'll reopen.

**Comment by KeithGadgetUK** [comment]
Sorry, I wasn't aware of a template.

**Describe the bug**
No matter how many different ways I try, when playing the Caucuses map I cannot accept the mission totals if I capture the Red airfield Sukhumi Babushara.

Every time I try, the log shows the same error message "ValueError: Sukhumi-Babushara is not in the transit network."
Liberation sticks stating it is waiting for the mission to complete and will not allow me to progress. I just cannot save any progress if I capture this airport.

**To Reproduce**
Run the attached mission.  Capture Sukhumi-Babushara with the blue forces,  Exit and accept the mission results.  Nothing should happen, it will not accept the results.  Switch to the command window type view and read the error messages.

**Additional information**
[liberation_nextturn - KAB Turn 17.zip](https://github.com/dcs-liberation/dcs_liberation/files/6703883/liberation_nextturn.-.KAB.Turn.17.zip)

**Version information (please complete the following information):**
DCS Liberation 3.0

**Additional context**
If you do not capture the Sukhumi-Babushara airbase, the mission results will save as expected.

**Comment by KeithGadgetUK** [comment]
> Can't do anything without the info the bug template asks for. Provide that and we'll reopen.

Template added, please re-open

**Comment by DanAlbert** [comment]
> Sorry, I wasn't aware of a template.

How did you file a bug without going through a template? The New Issue button takes you straight to template selection. Do we have a bad URL somewhere pointing at a templateless new bug? Would love to fix that.

**Comment by KeithGadgetUK** [comment]
I pressed the new issue button and it brought me to a blank input box.
I just tried it again and I received a form with button options, but that's not what I saw the first time.  I presume this is what I should have seen the first time.

**Comment by KeithGadgetUK** [comment]
> > Sorry, I wasn't aware of a template.
> 
> How did you file a bug without going through a template? The New Issue button takes you straight to template selection. Do we have a bad URL somewhere pointing at a templateless new bug? Would love to fix that.

I pressed the new issue button and it brought me to a blank input box.
I just tried it again and I received a form with button options, but that's not what I saw the first time. I presume this is what I should have seen the first time.

**Comment by DanAlbert** [comment]
> I pressed the new issue button and it brought me to a blank input box.
> I just tried it again and I received a form with button options, but that's not what I saw the first time. I presume this is what I should have seen the first time.

Huh, that's bizarre. Anyway, thanks for the info. We'll have a look.

**Comment by DanAlbert** [comment]
Need the state.json too.

**Comment by DanAlbert** [comment]
Oh, and the save game.

**Comment by KeithGadgetUK** [comment]
Please see attached the Liberation saved game and state.json file as requested.

[Liberation files 2.zip](https://github.com/dcs-liberation/dcs_liberation/files/6720130/Liberation.files.2.zip)

**Comment by KeithGadgetUK** [comment]
So fixed in version 4?  fantastic, thanks  :-)

**Comment by DanAlbert** [comment]
Yep!
