### ISSUE TITLE
Syria - Humble Helper bugs

### ISSUE THREAD

**Issue by sevenfifty777** [dcs-liberation/dcs_liberation#1322]
Describe the bug:
the bugs happen in : Syria - Humble Helper
1st bug
the bug happen after launching mission in mission editor when script are loaded
ERROR   SCRIPTING: Mission script error: [string "..."]:26: '}' expected near 'lah'
seems error is due to name of the frontline in syria map : Rosh Pina/Tha'lah that contain character '
        -- list the JTACs generated by Liberation
        dcsLiberation.JTACs = {
            {dcsGroupName='JTAC345', callsign='Uzi', zone='Frontline Rosh Pina/Tha'lah', laserCode='1688', dcsUnit='JTAC345' }, 

temporary solution is to escape character ' in the script: 'Frontline Rosh `Pina/Tha\'lah'`
also because of this bug the state,json is not moved to dcs-libeartion folder but stay in temp folder

2nd bug
immediatly after start of the mission red faction has 12 aircraft crash without any reason

{"base_capture_events":[],"destroyed_objects_positions":[{"orientation":258.64473569672,"x":-210625.20629883,"y":713.38531494141,"z":13366.978759766},{"orientation":161.02251394666,"x":-210620.15307617,"y":713.53735351563,"z":13367.039916992},{"orientation":340.8895347665,"type":"WALL_CONCR_GRAY_CRASH","x":-210614.33618164,"y":714.08129882813,"z":13333.811401367}],"killed_aircrafts":["SHRIMP Escort|81|49|25|Su-30| Pilot #2","SHRIMP DEAD|81|47|25|Su-34| Pilot #2","SHRIMP SEAD|81|48|25|Su-34| Pilot #1","ALPACA DEAD|81|50|25|Su-34| Pilot #1","ALPACA SEAD Escort|81|51|25|Su-30| Pilot #1","ALPACA SEAD Escort|81|51|25|Su-30| Pilot #2","SHRIMP DEAD|81|47|25|Su-34| Pilot #1","SHRIMP SEAD|81|48|25|Su-34| Pilot #2","BUTTERFLY SEAD Escort|81|45|25|Su-24M| Pilot #2","ALPACA DEAD|81|50|25|Su-34| Pilot #2","BUTTERFLY SEAD Escort|81|45|25|Su-24M| Pilot #1","SHRIMP Escort|81|49|25|Su-30| Pilot #1"],"killed_ground_units":[699728480,699728472,297009943],"mission_ended":true}

**Comment by DanAlbert** [comment]
Please search first: https://github.com/dcs-liberation/dcs_liberation/issues?q=is%3Aissue+lah+is%3Aclosed
