### ISSUE TITLE
Submission: Persian Gulf "Scenic Route" campaign

### ISSUE THREAD

**Issue by sgtfuzzle17** [dcs-liberation/dcs_liberation#1334]
* Campaign name: Persian Gulf - Scenic Route
* Files: 
[scenic_route.zip](https://github.com/dcs-liberation/dcs_liberation/files/6707755/scenic_route.zip)

* Update summary (optional): A lightweight naval-based campaign for Persian Gulf, set on the northern side of the map due to a lack of available content for that area. Fully set up for 4.0 release including version number and relevant frontline/exclusion zone checks etc.

**Comment by docofmur** [comment]
Good to Go @DanAlbert 
Very well made and interesting

**Comment by HILOK** [comment]
hi! very nice (and long...) campaign, thanks : ) 
i captured the last base before kish. now there is no connecting path to kish. 
how do i capture kish without ground troups to win the campaign?

**Comment by Starfire13** [comment]
@HILOK I suggest getting in touch with the campaign designer Fuzzle on Discord. It's more effective than posting a comment on an 8 month old PR. 🙂

**Comment by sgtfuzzle17** [comment]
Hi @HILOK,

Kish is disconnected due to being a far chunkier airbase with a lot of defences. Treat it like a final boss for the campaign - once you’ve knocked out the defences and runway, call it a win.

**Comment by HILOK** [comment]
thanks both of you. @sgtfuzzle17 so there wont be a message saying "today you win" or something similar?

**Comment by Starfire13** [comment]
Once you have knocked out the runway on the final airfield, you will get a small "you have won" message in the message pane in Liberation.

**Comment by HILOK** [comment]
well the RWY is already dead, but still some "half-dead" stuff around on the island...yet no message : )
[state.zip](https://github.com/dcs-liberation/dcs_liberation/files/8130766/state.zip)

**Comment by Starfire13** [comment]
The message is pretty much irrelevant. If the enemy has no way to attack you, you have won.

**Comment by HILOK** [comment]
ok my bad -just noticed that little message in the info panel: "you have been victorious...". so there IS a message after all  : )
thanks @sgtfuzzle17 and all devs! playing the campaign has been a very enjoyable experience, besides the typical DCS quirks. looking forward to a follow-up
