### ISSUE TITLE
Bug with campaign Humble Helper on Syrian map

### ISSUE THREAD

**Issue by Jiphou** [dcs-liberation/dcs_liberation#1348]
**Describe the bug**
Launching a campaign with Humble helper on syrian theater generate an error in DCS when launching the flight whatever the selected player aircraft
All other maps and all other campaign are OK

**To Reproduce**
1. Create a campaign with Humble helper 
2. Select a player role
[TEST_SYRIA.zip](https://github.com/dcs-liberation/dcs_liberation/files/6715535/TEST_SYRIA.zip)
[TEST_SYRIA.zip](https://github.com/dcs-liberation/dcs_liberation/files/6715537/TEST_SYRIA.zip)
 any kind of aircraft 
3.  click take off
4. go to DCS ME
5. open the liberation nextturn
6. fly
7. get an error message (see under)

**Expected behavior**
No error message

**Additional information**

We will usually need more information for debugging. Include as much of the following as you are able:

- DCS Liberation save file (the `.liberation` file you save from the DCS Liberation window). By default these are located in your DCS saved games directory (`%USERPROFILE%/Saved Games/DCS`).
- The generated mission file (the `.miz` file that you load in DCS to play the turn). By default these are located in your missions directory (`%USERPROFILE%/Saved Games/DCS/Missions`).
- A tacview track file, especially when demonstrating an issue with AI behavior. By default these are located in your Tacview tracks directory (`%USERPROFILE%/Documents/Tacview`).
- The state.json file from the finished mission when the problem is related to results processing. By default these are located in your Liberation install directory.

**Version information (please complete the following information):**
 - DCS Liberation [e.g. 2.3.1]:3.0
![IMG_2516 1867](https://user-images.githubusercontent.com/78730674/123410930-2a906a80-d5b0-11eb-8491-17b2c2eff227.jpg)

**Additional context**

**Comment by DanAlbert** [comment]
Please search before filing. This has been filed and closed a half dozen times now.
