### ISSUE TITLE
bad SAM placement in Campaign Humble helper

### ISSUE THREAD

**Issue by Jiphou** [dcs-liberation/dcs_liberation#1350]
**Describe the bug**
Once campaign launched on syrian theater observation of ennemy SAMs position shows curious things

**To Reproduce**
1. Create  campaign on syrian theater (humble helper probably)
2. select a player aircraft 
3. take off
4. go to DCS ME
5. open liberation next turn
6. fly
7. look at ground assets cyclingly
8. observe the joined photo

**Expected behavior**
Correct positionning

**Additional information**

We will usually need more information for debugging. Include as much of the following as you are able:

- DCS Liberation save file (the `.liberation` file you save from the DCS Liberation window). By default these are located in your DCS saved games directory (`%USERPROFILE%/Saved Games/DCS`).
- The generated mission file (the `.miz` file that you load in DCS to play the turn). By default these are located in your missions directory (`%USERPROFILE%/Saved Games/DCS/Missions`).
- A tacview track file, especially when demonstrating an issue with AI behavior. By default these are located in your Tacview tracks directory (`%USERPROFILE%/Documents/Tacview`).
- The state.json file from the finished mission when the problem is related to results processing. By default these are located in your Liberation install directory.

**Version information (please complete the following information):**
 - DCS Liberation [e.g. 2.3.1]:3.0

**Additional context**
![IMG_2515](https://user-images.githubusercontent.com/78730674/123412997-85c35c80-d5b2-11eb-8734-e5f17a10e1ff.jpg)
[SYR_2012_F18_V2.zip](https://github.com/dcs-liberation/dcs_liberation/files/6715594/SYR_2012_F18_V2.zip)

**Comment by DanAlbert** [comment]
How's this an AI bug? I'm missing something.

**Comment by Jiphou** [comment]
My fault sorry about that
 it is a bad wording
 it is NOT an AI bug but a campaign red side assets generation and location bug...

**Comment by DanAlbert** [comment]
@Sir-Headiii

**Comment by docofmur** [comment]
This campaign has not been updated for 4.0 release. Also the direction and composition of SAM sites in 3.0 is still random, there is no way the designer could adjust this to fit perfectly in the revampments every time.

**Comment by DanAlbert** [comment]
Yeah, the fix here is to move the SAM outside the location meant for SAMs :(

**Comment by Jiphou** [comment]
yep anyway it is very funny 🤣

🤣🤣🤣

Envoyé de mon iPhone

**Comment by Sir-Headiii** [comment]
Will fix asap when I have my PC and internet up and running. Currently renovating and moving into a new apartment. It will probably take a few weeks.
