### ISSUE TITLE
new mission won´t load

### ISSUE THREAD

**Issue by Klap0** [dcs-liberation/dcs_liberation#1354]
**Describe the bug**
when i tried to load second mission and click on take off it did not overwrite a previous mission
when i took look to log it write keyerror 29

**Additional information**
i was trying just some AI planning so i was cheating money and I wanted to try how nighthawks will be usefull against radars

**Version information**
 - DCS Liberation 3.0.0 campaingn battle of UAE
 - start date gulf war spring 1990
 - player faction NATO desert storm enemy faction Iraq 1991

**Comment by DanAlbert** [comment]
Please upload the files the template asked for. Will reopen when we get them.
