### ISSUE TITLE
[Build #2202] Liberation fails to generate campaign using Operation Blackball preset using some player factions

### ISSUE THREAD

**Issue by RealChirs** [dcs-liberation/dcs_liberation#1355]
When attempting to generate a campaign using the Operation Blackball preset, using some player faction presets (such as Syria 2011 or Syria 2012'ish) with the default settings leads to liberation throwing an incompatible version error:

> The save game you have loaded is incompatible with this version of DCS Liberation.
> 
> Traceback (most recent call last):
>   File "windows\QLiberationWindow.py", line 296, in setGame
>   File "widgets\map\QLiberationMap.py", line 58, in set_game
>   File "widgets\map\mapmodel.py", line 834, in reset
>   File "widgets\map\mapmodel.py", line 963, in reset_threat_zones
>   File "game\game.py", line 511, in threat_zone_for
> AttributeError: 'Game' object has no attribute 'blue_threat_zone'

Interestingly enough, the same error does **not appear** when using Syria 2011 or Syria 2012'ish as the enemy faction.

1. Attempt to generate new campaign
2. Choose player faction Syria 2011 or Syria 2012'ish
3. Leave settings at default and click 'Finish'

**Additional information**
[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/6718762/liberation.log)

Liberation version: v.4.0.0-2202

EDIT: Issue originally discovered on build 2214, but also present on 4.0.0-2202 build

**Comment by DanAlbert** [comment]
It sounds like a similar problem to https://github.com/dcs-liberation/dcs_liberation/issues/1232, but with a different cause? Sounds like for some reason you've already won, but that really shouldn't depend on the faction.

**Comment by DanAlbert** [comment]
![image](https://user-images.githubusercontent.com/315852/123493901-de0a5680-d5d2-11eb-8104-f82f52d30db6.png)

This campaign only works if the player has a carrier, and those factions don't. This is working as expected, but I've added a note to the description: 
![image](https://user-images.githubusercontent.com/315852/123494020-46f1ce80-d5d3-11eb-9a8e-a03c0873ad3a.png)
