### ISSUE TITLE
Pre-release Campaign Clean-up

### ISSUE THREAD

**Issue by docofmur** [dcs-liberation/dcs_liberation#1359]
These will not work and need to be removed:

- [X] Syria: battle for golan heights - strike objects - needs to be removed
- [X] Syria: Inherent Resolve - strike objects - needs to be removed
- [x] Syria: Operation Atilla - strike objects - needs to be removed
- [x] Syria: Russian Intervention - strike objects - super broken, all bases are control points - remove

These have no visible map strike objects and just needs the campaign version changed from 6.0 to 7.0 
- [X] Caucasus: Russia Small
- [X] Syria: Humber helper - no strike objects - update the version

**Comment by Khopa** [comment]
- I updated "Battle For Golan Heights" to 7.0 (recreated all custom strike objects)
- I also updated "Caucasus Russia small", renamed it to "From Mozdok to Maykop". Note : it does have custom strike objects, i recreated them to be sure, but seems to me that id haven't changed on Caucasus ?

**Comment by DanAlbert** [comment]
Updated the version for Humble Helper and removed Inherent Resolve. Waiting for a response from @Malakhit before removing his campaigns because I think those are actually new enough to have the correct IDs anyway and they just need the version bump.

**Comment by Malakhit** [comment]
My campaigns are brand new - not sure what it is I need to do here?

**Comment by DanAlbert** [comment]
Probably nothing. The 6.0 -> 7.0 campaign version was to account of map target IDs changing in the Syria map update that added Cyprus. If you'd built the campaigns with a version of DCS that didn't have those, all the IDs are wrong and the death of those buildings can't be tracked.

Sounds like nothing to do then and we just need to bump the version? I'm not sure what @docofmur meant by "super broken" though. It looks fine to me?
