### ISSUE TITLE
set up bullseye waypoint for appropriate aircraft

### ISSUE THREAD

**Issue by DanAlbert** [dcs-liberation/dcs_liberation#136]
Some aircraft (like the hornet) can give bullseye coordinates if they have a waypoint matching the bullseye. Right now I don't think we don't create such a waypoint. Would be nice to have.

**Comment by MedievalBunny** [comment]
You can do it in the Mission Editor before flying the mission, but agreed, it would be cool to be able to set that in Liberation.

**Comment by DanAlbert** [comment]
Also put the coordinates in the kneeboard.

**Comment by walterroach** [comment]
We should put bullseye somewhere intentional.  Currently it's over the center of active frontline, which means it moves around and is essentially random when there's multiple frontlines.  Maybe define bulls with the campaign?

**Comment by DanAlbert** [comment]
In the campaign is a good idea if we want it to be static throughout the campaign. Only other idea would be to put it over the next enemy base, which will still move from time to time but won't as constantly.

**Comment by walterroach** [comment]
> Only other idea would be to put it over the next enemy base, which will still move from time to time but won't as constantly.

I like this idea.  Bullseye should be somewhere you can intuitively know the location of, even if you're not flying a modern jet with a helper waypoint.  

Pilots ought to know where they are in relation to the closest enemy base to the frontline.  In air war only campaigns we can pick the closest enemy airfield.

**Comment by ninchistudios** [comment]
I'd like to add a +1 for this enhancement. Having the final WP be on top of the bullseye will be very useful and save having to do that manually each time (either in ME or in the cockpit). 

In terms of where it should be placed - I can understand the desire to have it placed semi-randomly but for practical purposes having bulls on top of the next objective is a helpful reference.
