### ISSUE TITLE
涂装无法使用，从2.50开始就无法使用，占领机场很容易导致任务无法继续

### ISSUE THREAD

**Issue by lizhaobei85032** [dcs-liberation/dcs_liberation#1360]
Before filing, please search the issue tracker to see if the issue has already been reported.

If reporting a DCS AI bug, check https://github.com/dcs-liberation/dcs_liberation#dcs-bugs.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Additional information**

We will usually need more information for debugging. Include as much of the following as you are able:

- DCS Liberation save file (the `.liberation` file you save from the DCS Liberation window). By default these are located in your DCS saved games directory (`%USERPROFILE%/Saved Games/DCS`).
- The generated mission file (the `.miz` file that you load in DCS to play the turn). By default these are located in your missions directory (`%USERPROFILE%/Saved Games/DCS/Missions`).
- A tacview track file, especially when demonstrating an issue with AI behavior. By default these are located in your Tacview tracks directory (`%USERPROFILE%/Documents/Tacview`).
- The state.json file from the finished mission when the problem is related to results processing. By default these are located in your Liberation install directory.

**Version information (please complete the following information):**
 - DCS Liberation [e.g. 2.3.1]:

**Additional context**

**Comment by DanAlbert** [comment]
Google Translate says "The camouflage can’t be used. It can’t be used since 2.50. Occupying the airport can easily lead to the mission’s failure to continue."

Can't do anything without the data the template asks for. Provide that and we'll reopen.
