### ISSUE TITLE
MIG-31无法使用，F15E无法使用，我在本地可以使用

### ISSUE THREAD

**Issue by lizhaobei85032** [dcs-liberation/dcs_liberation#1361]
Before filing, please search the issue tracker to see if the issue has already been reported.

If reporting a DCS AI bug, check https://github.com/dcs-liberation/dcs_liberation#dcs-bugs.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Additional information**

We will usually need more information for debugging. Include as much of the following as you are able:

- DCS Liberation save file (the `.liberation` file you save from the DCS Liberation window). By default these are located in your DCS saved games directory (`%USERPROFILE%/Saved Games/DCS`).
- The generated mission file (the `.miz` file that you load in DCS to play the turn). By default these are located in your missions directory (`%USERPROFILE%/Saved Games/DCS/Missions`).
- A tacview track file, especially when demonstrating an issue with AI behavior. By default these are located in your Tacview tracks directory (`%USERPROFILE%/Documents/Tacview`).
- The state.json file from the finished mission when the problem is related to results processing. By default these are located in your Liberation install directory.

**Version information (please complete the following information):**
 - DCS Liberation [e.g. 2.3.1]:

**Additional context**

**Comment by DanAlbert** [comment]
Google Translate says "MIG-31 cannot be used, F15E cannot be used, I can use it locally"

Need the data the template asks for. Provide that and we'll reopen.
