### ISSUE TITLE
SU-33 Should be taskable for BAI

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#1367]
**Describe the bug**
SU-33-D is unable to be tasked as BAI, but is able to be tasked as `Strike`.

**To Reproduce**
1.  Purchase SU-33
2.  Try to plan as BAI

**Expected behavior**
Enable ability for SU-33 to plan as `BAI`.

**Version information (please complete the following information):**
 - DCS Liberation `4.0.0`

**Comment by SnappyComebacks** [comment]
Should this be considered done, now that mission types are customizable?  Or should this become a default mission type?

**Comment by DanAlbert** [comment]
The customization has no effect on the priority list, so if it's not in the default list it'll never be used by the auto planner.

**Comment by Mustang-25** [comment]
I have a bunch of changes I want to propose for the hierarchies in the AI flight planner lists so I can tackle this one and also #1372 when I submit a PR for it.
