### ISSUE TITLE
limit aircraft stationed to an airfield by the number of parking space

### ISSUE THREAD

**Issue by DanAlbert** [dcs-liberation/dcs_liberation#137]
Can avoid issues with planned ground starts becoming in-air starts by ensuring that we can't assign more aircraft to an airfield than it has room for. Also puts an upper bound on the number of aircraft that can be deployed, one that is sufficiently high enough that it won't be annoying for the player but will cap the AI going nuts.

Carriers might need to be a bit different, since not all of their parking space is modeled, but maybe they already have sufficient parking spaces such that we don't need to worry about it?

**Comment by Khopa** [comment]
Partly implemented in 2.1.3

But there is still no limit for the enemy aircrafts, and no upper bound.

**Comment by DanAlbert** [comment]
AI aircraft purchases are now limited by available parking.
