### ISSUE TITLE
Enable CAS tasking for MiG-21

### ISSUE THREAD

**Issue by dankwilliams** [dcs-liberation/dcs_liberation#1372]
**Is your feature request related to a problem? Please describe.**
I bought a bunch of MiG-21's and was hoping to use them in a CAS role.

**Describe the solution you'd like**
1. Enable CAS tasking for MiG-21
2. CAS preset loadout with cluster bombs/rockets

**Additional context**
MiG-21's have been used in a CAS role IRL by multiple countries so it would not be unrealistic.
https://en.wikipedia.org/wiki/Mikoyan-Gurevich_MiG-21#Syrian_civil_war
https://en.wikipedia.org/wiki/Mikoyan-Gurevich_MiG-21#Libyan_Civil_War_(2014%E2%80%93present)
https://en.wikipedia.org/wiki/Mikoyan-Gurevich_MiG-21#Angola

Thank you!

**Comment by bgreman** [comment]
@dankwilliams We'd need a default CAS loadout if you have one.
