### ISSUE TITLE
Operation Atilla Campaign - Lakatamia unsuitable for fixed wing aircraft.

### ISSUE THREAD

**Issue by BennySouthSt** [dcs-liberation/dcs_liberation#1381]
Before filing, please search the issue tracker to see if the issue has already been reported.

If reporting a DCS AI bug, check https://github.com/dcs-liberation/dcs_liberation#dcs-bugs.

**Describe the bug**
Lakatamia (central Cyprus) is a small helicopter base. Obv. the campaign has no way of knowing this, so the AI will base fixed wing aircraft there, which are unable to take off.

**To Reproduce**
1. Create an Operation Atilla Campaign (tested with default factions, reduced money/income)
2. Start the campaign, and check the intel for Lakatamia to make sure fixed wing aircraft have been based there.
3. Launch the mission in DCS.
4. See the AI attempt to take off from Lakatamia - usually resulting in the first aircraft crashing, and subsequent aircraft sitting there.

**Expected behavior**
Campaign shouldn't base fixed wing aircraft out of Lakatamia, although i'm aware this is probably currently a limitation in Liberation or DCS - might have to just remove it from places you can base aircraft?

**Additional information**
[liberation_nextturn.zip](https://github.com/dcs-liberation/dcs_liberation/files/6727400/liberation_nextturn.zip)
[airfield_bug.zip](https://github.com/dcs-liberation/dcs_liberation/files/6727431/airfield_bug.zip)

![image](https://user-images.githubusercontent.com/18265865/123662454-65eb9d00-d82d-11eb-9d59-b424da488e09.png)
![image](https://user-images.githubusercontent.com/18265865/123662516-756ae600-d82d-11eb-9305-149f38e6bfdb.png)

**Version information (please complete the following information):**
 - DCS Liberation 4.0.0

**Comment by lizhaobei85032** [comment]
朋友，请问你是怎么开始飞行的，我的4.0.0版本很多错误，无法点击TAKE OFF,能说一下吗

**Comment by DanAlbert** [comment]
Campaign was abandoned, so removed and this bug is obsolete.
