### ISSUE TITLE
Campaign generates A-10C mission instead of A-10 II

### ISSUE THREAD

**Issue by Dunbal** [dcs-liberation/dcs_liberation#1389]
While running a Georgia campaign with Blueforce Modern, the game generates missions for the A-10 II Thunderbolt (suite 3), however when loading the mission in DCS the regular A-10 C is loaded. Included campaign save file.
[deh.zip](https://github.com/dcs-liberation/dcs_liberation/files/6741824/deh.zip)

**Comment by Mustang-25** [comment]
Not a bug, suite 3 is the regular A-10C. Suite 7 is the A-10C II.
