### ISSUE TITLE
Base Recaptured? 

### ISSUE THREAD

**Issue by MedievalBunny** [dcs-liberation/dcs_liberation#139]
I just flew a mission against an airbase we've been reducing down to almost nothing, we wrecked every ground unit at an enemy airbase, then a column of Abrams drove across the runway and poured MG fire into a pair of Su-30s trying to take off. It pretty solidly looked captured. Two flaming Su-30 wrecks, 10+ Abrams driving all around. We flew home. 

We accepted the mission results and noticed that not only was the base not captured, the front line had moved back from where it had been. Now there's dozens of units at the base, arty, and a SAM site that wasn't there before. Looking at the logs it looks like we captured it, and then the enemy recaptured it in the same turn? How did that happen? Did the flaming Su-30s with no wings capture it back?

Campaign save attached.
[AlexSteve.zip](https://github.com/Khopa/dcs_liberation/files/5249234/AlexSteve.zip)

**Comment by Nomadzy** [comment]
Same here with the latest version (2.1.2) no matter how much mavs I drop over, it still uncaptured. 
Did you find any work around ? I wanted to added that base manually to the captured bases in the JSON file, but I couldn't find the correct Id for it ..

**Comment by DanAlbert** [comment]
I don't think this happens any more. Some changes to capture processing happened in 2.2.
