### ISSUE TITLE
very poor map performance

### ISSUE THREAD

**Issue by niehorst** [dcs-liberation/dcs_liberation#1392]
Since 3.0 I have really poor map performance when scrolling, zooming or moving waypoints. It feels like taking hours when I want to move the map or anything. It seems that the menu itself is very slow for some reason.

Can't be hardware related. Quiet a good machine at my end with a 9900K + 3090

I really hope I can get some help to fix this. Mission planing is almost impossible right now!

**Comment by DanAlbert** [comment]
Disable some map options maybe? It's perfectly smooth on my end so there's nothing for me to investigate.
