### ISSUE TITLE
Incorrect composition of Silkworm ASM Battery in Syria-Lebanon 2005 (Allied Sword) Faction

### ISSUE THREAD

**Issue by Floydii** [dcs-liberation/dcs_liberation#1393]
**Describe the bug**

The Silkworm Anti-Shipping Missile Battery for the Syria-Lebanon 2005 (Allied Sword) Faction has 6x Silkworm search Radars (AShM Silkworm SR) and no launchers (AShM SS-N-2 Silkworm). This makes the site harmless to ships. 
![image](https://user-images.githubusercontent.com/40154322/124128570-4324e700-dac0-11eb-8c78-168a163836bc.png)

**To Reproduce**

1. create a campaign that utilises the Syria-Lebanon 2005 (Allied Sword) Faction and includes locations for anti-shipping missile sites.
2. 'Take off'
3. View Silkworm Site in editor, note that it has no missiles launchers.

**Expected behaviour**

The Silkworm site should consist of 5-6 Silkworm launchers (AShM SS-N-2 Silkworm) and only 1-2 Radar vans (AShM Silkworm SR). This will allow it to target ships. The site should also retain its ancillary vehicles (SA9/ZSU23-4 and KAMAZ truck).

**Comment by Kea21** [comment]
This isn't just an issue for the Allied Sword faction as I've also noticed this in a 2020s Iran faction I've created. All Silkworm sites end up with SRs instead of launchers.
