### ISSUE TITLE
No COLD Start on Carriers

### ISSUE THREAD

**Issue by Quax456** [dcs-liberation/dcs_liberation#14]
Even if selectet you will not start cold and dark on the Carriers.
Always hot.

**Comment by MedievalBunny** [comment]
Takeoff from runway doesn't work either. At least with Super Carrier (I've not tried without) it seems that any spawn selection always results in a hot start from parking.

**Comment by Khopa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Carrier cold start not working](https://trello.com/c/KikCc5v1/102-carrier-cold-start-not-working)

**Comment by Khopa** [comment]
This should be fixed in 2.0.10

Please re-open if you encounter the issue again.
