### ISSUE TITLE
MLRS in forests

### ISSUE THREAD

**Issue by DillieKoe** [dcs-liberation/dcs_liberation#1404]
**Is your feature request related to a problem? Please describe.**
When MLRS units are spawned in forest there is a chance for them to blow themselves up.

**Describe the solution you'd like**
Lower or even remove the possibility for MLRS units to spawn in forests/next to trees.

**Comment by DanAlbert** [comment]
We can't automatically predict where forests are. We build exclusion areas for each map to define areas where ground units shouldn't spawn.

I'm other words, this "feature" already exists but has a bug. Without the details the bug template asks for we don't know which zone is broken.
