### ISSUE TITLE
exclude Cyprus from sea zone mapping

### ISSUE THREAD

**Issue by zelosos** [dcs-liberation/dcs_liberation#1408]
The title should explain it well.

**Comment by DanAlbert** [comment]
It doesn't. What's the problem?

**Comment by zelosos** [comment]
As I understand it:
The sea zone marks the area of ship spawns. Therefore ships can spawn on the land of Cyprus.
The exclusion from Cyprus of this zone will prevent this from happening.

**Comment by DanAlbert** [comment]
There is no random spawning any more. If a ship is spawning in land it means the campaign designer put it there?

If you could upload the data the template asked for it would remove the guesswork. It saves everyone, including you, time if you fill out the template.

**Comment by zelosos** [comment]
OK then it is not needed indeed.

**Comment by DanAlbert** [comment]
I'm confused, what's the problem you were seeing?

**Comment by zelosos** [comment]
The carier wants to move across Cyphrus.

**Comment by zelosos** [comment]
I think the carrier is intended to move to the target point the players sets in liberation.
Ingame it moves in a random other direction. One of them can be across Cyphrus.

**Comment by DanAlbert** [comment]
Fill out the template and we can reopen.
