### ISSUE TITLE
Helicopter and A-10 CAS mission profiles

### ISSUE THREAD

**Issue by broecker** [dcs-liberation/dcs_liberation#1413]
When creating CAS missions for Helicopters and A-10s the AI places the ingress, egress and NAV waypoints at at 20,000 feet. These should be much lower, especially for helos.

To reproduce:
Create a CAS mission with either an A-10 or AH-64
Check waypoint altitude on map

Select 'edit' on the mission -- waypoints cannot be changed
Edit > Recreate as CAS still inserts WPs at too high altitudes.

Tested on  Liberation 4.0.0, Syria map

**Comment by DanAlbert** [comment]
Duplicate of #270
