### ISSUE TITLE
Better way to included mod aircraft without needing to become a coder

### ISSUE THREAD

**Issue by KeithGadgetUK** [dcs-liberation/dcs_liberation#1414]
**Is your feature request related to a problem? Please describe.**
As the means to add mod aircraft to Liberation appears to be the same process, every time, can you create a stand-alone tool to do this?

**Describe the solution you'd like**
I want to add the aircraft Mods (such as VSN etc) to Liberation, but I do not want to install the tools to be a programmer or learn how to code to be able to do this.  As the process appears to be the same steps for each aircraft, can you create a stand-alone tool where all we have to do it point to the Mod folder and it will add that mod to the Liberation database.

I'm not a technophobe, but it seems a very convoluted process to add aircraft to the game.  I do not feel it is too much to want the F-35 or another mod I have for the Euro Fighter Typhoon.

The other user level tweaks where it is just a matter of amending files seems straightforward, but adding aircraft is not simple.

**Additional context**
Nope, just with to thank you in advance.

**Comment by DanAlbert** [comment]
This isn't feasible. The reality is that it's not trivial to add a mod.

**Comment by KeithGadgetUK** [comment]
I didn't suggest it was trivial, I suggested the process appears to be the same steps for adding the mods.  If it is the same, it can feasibly be automated.
