### ISSUE TITLE
Liberation Ignores "Disabled" Automatic Package Planning Behavior Setting

### ISSUE THREAD

**Issue by jeetsukumaran** [dcs-liberation/dcs_liberation#1416]
Before filing, please search the issue tracker to see if the issue has already been reported.

If reporting a DCS AI bug, check https://github.com/dcs-liberation/dcs_liberation#dcs-bugs.

**Describe the bug**

Even if "Disabled" is selected under Settings > Campaign Management > Automatic package planning behavior, packages are auto generated.

**To Reproduce**
1. Create New Campaign
2. Go to "Settings > Campaign Management > Automatic package planning", and select "Disabled".
3. Purchase some aircraft.
4. Click on "Begin Campaign"
5. See auto generated packages/missions.

**Expected behavior**

No packages should be generated for player side by AI.

**Additional information**

We will usually need more information for debugging. Include as much of the following as you are able:

- DCS Liberation save file (the `.liberation` file you save from the DCS Liberation window). By default these are located in your DCS saved games directory (`%USERPROFILE%/Saved Games/DCS`).
- The generated mission file (the `.miz` file that you load in DCS to play the turn). By default these are located in your missions directory (`%USERPROFILE%/Saved Games/DCS/Missions`).
- A tacview track file, especially when demonstrating an issue with AI behavior. By default these are located in your Tacview tracks directory (`%USERPROFILE%/Documents/Tacview`).
- The state.json file from the finished mission when the problem is related to results processing. By default these are located in your Liberation install directory.

**Version information (please complete the following information):**

- This behavior is seen in Build #2424

**Comment by RndName** [comment]
This problem was an issue in https://github.com/dcs-liberation/dcs_liberation/commit/6ca03a2b9aae74b765fc42df16d009dd7d44f646

Which was solved already with a change how the initialization works. There was an issue within a For Loop which basicly was always true and so ignored the AutoAtoBehavior.Disabled

Should be working with later builds again. Like 2425
