### ISSUE TITLE
Heading option for SAM-sites (specifically Patriot)

### ISSUE THREAD

**Issue by CptBean** [dcs-liberation/dcs_liberation#1423]
**Problem:**
When a faction has the Patriot SAM-site in it's inventory, the mission generator will place it in a random heading. Since the Patriot STR can only track in one direction, this sometimes renders a Patriot site useless.

**Solution:**
An option available to campaign-makers to choose the heading for large SAM sites (I think only the Patriot would have this issue). For instance by placing a waypoint a couple of feet in the required heading or changing the heading of the unit itself. Also of EWR sites running the Patriot STR it would be nice if this was an option.

**Comment by Floydii** [comment]
I would greatly prefer a 'heading' input per CptBean's post. If not possible, three other possibilities:

1. Give the option to buy Patriot templates that are orientated a given direction (Patriot N, Patriot E, Patriot S, Patriot W). At least then the player can specify the general direction the thing points. This assumes that Liberation does not arbitrarily alter headings on placement.

2. Back three Patriot Radars up against each other facing out in the template to give maximum coverage, but so close together that a single missile will kill them all.

3. Some sort of logic that points the Patriot Battery towards the greatest density of enemy airbases so the radar is roughly pointed along the most likely avenue of approach.

![image](https://user-images.githubusercontent.com/40154322/126138138-f4e65395-79f7-4c8d-a008-e39d6c242305.png)

**Comment by Floydii** [comment]
Also worth noting is that the Liberation SA10 site has 28 ready use missiles by default, but the Patriot only has 12?
