### ISSUE TITLE
Limits on certain airframes by faction

### ISSUE THREAD

**Issue by sgtfuzzle17** [dcs-liberation/dcs_liberation#1424]
**Is your feature request related to a problem? Please describe.**
A particular problem my group and I have run into a few times is the autopurchaser deciding that the best plane is the way to go, regardless of price. This can lead to some inconsistencies with how you engage the airforce you're facing. I understand that squadron replenishment limits are a feature that's in the works, but specifically I'd like to see the option to limit particular air forces' ability to field large numbers of particular airframes. A great example is the IRIAF - in real life they can only field about an absolute maximum of two dozen F-14As, but ingame they're able to throw as many as they want at you. A way to specifically limit this faction (but not necessarily say US Navy 1985 or similar) would be handy.

**Describe the solution you'd like**
Ideally, an optional system implemented in the faction files would seem to be the best way to do this in my (admittedly not-coder) opinion. Something along the lines of:

`"aircrafts": [
    "AH-1J SeaCobra",

    "F-14A Tomcat (Block 135-GR Late)" {x},

    "F-4E Phantom II",

    "F-5E Tiger II",

    "MiG-21bis Fishbed-N"
  ],`

where {x} represents the max number of that airframe this faction can have deployed across a theatre at a time. 

**Additional context**
Note that the above implementation is almost certainly an example of bad syntax on my part. This is just an idea I had for a potential way it could be implemented. You could also look at implementing a way where if that particular value in the array isn't present, it's assumed that airframe is unlimited for that faction (as is currently the case). So in the above example, all airframes except the F-14A would be unlimited.

**Comment by DanAlbert** [comment]
Squadron limit features will do exactly this. Rather than being part of the faction file it'd be part of the campaign, customizable as part of the new game wizard.
