### ISSUE TITLE
Easy Communications Switch

### ISSUE THREAD

**Issue by pablodma** [dcs-liberation/dcs_liberation#1425]
**Describe the solution you'd like**
As user, I would like to force disable Easy Comms on Liberation DCS as part of Mission Settings.

**Comment by Thumper71** [comment]
Right now easy comms seems to be forced on in the liberation_nextturn/options file on line 24
```
["easyCommunication"]=true,
```

**Comment by RndName** [comment]
implemented with 2c21644a2c1b073b8eb46302b410766a04ad193e
