### ISSUE TITLE
Add 'Strike' and 'DEAD' Missions to KA-50

### ISSUE THREAD

**Issue by NeelKulkarni6** [dcs-liberation/dcs_liberation#1434]
**Add 'Strike' and 'DEAD' Missions to KA-50**

The KA-50 should be capable of strike/bombing missions as it has the **FAB - 250 and FAB - 500 kg bombs** in its arsenal. Rockets and Vihkir missiles could potentially be used too. Currently, it is only capable of CAS and BAI missions (afaik), which limits the potential for people who only have/primarily use the Black Shark. 

IRL the KA-50 and Ka-52 are capable and have done Strike missions. 
For example in the Chechen war, Ka-50s bombed warehouses and ammo depots, and in Syria, KA-52s bombed ISIS-held territory.
https://en.wikipedia.org/wiki/Kamov_Ka-50
https://tass.com/defense/933891

As for DEAD missions, the potential is completely hypothetical as it has never been used in real life (unclassified at least). However, the KA-50 is a capable standoff attacker since it has a very accurate targeting camera and Vihkir missiles, and would be great to target sam or AAA sites. Running in more aggressively with bombs or rockets would also be a (more risky) possibility. 

If requested, I can give my idea for suggested loadouts for these missions.

_Sidenote: I do not own the MI24 HIND, but if it has not been added already, I think it should be able to do these missions too, as it can carry bombs and guided rockets as well._

**Comment by Floydii** [comment]
I'm guessing you're seeking to leverage the behaviour in 'strike' where the aircraft targets multiple points on the ground (generally right under buildings). If so, we'll also need loadouts created that have either heavy rockets or bombs when 'strike' is selected.

Regarding DEAD, does BAI have the same endstate (helo attacking the SAM target group)?

**Comment by NeelKulkarni6** [comment]
For STRIKE loadouts, here's what I recommend:
4 x FAB - 500 kg bombs
![image](https://user-images.githubusercontent.com/77650484/126056000-065af5ef-4c40-445b-81a1-06fff936ff45.png)

Alternative; with rockets
2 x S-13-OF Rkts, 2 x FAB - 500 kg bombs
![image](https://user-images.githubusercontent.com/77650484/126056014-082dfa0d-ac0b-46c2-b928-2ac833d02d2b.png)

I think the first loadout should be fine, but you may want to consider the alternative one since it has more firepower for more lighter targets like oil tanks.

**Comment by NeelKulkarni6** [comment]
As for BAI, it is hard to test whether the ai helicopters will attack the sam in Liberation. Mainly because the BAI waypoint altitude is at **20,000 ft** which is obviously way too high for a helicopter. This often breaks the flight. I tested this in the mission editor with the sams set to passive and the Ka-50s set to do CAS and they did attack the site.

**Comment by Tinchus2009** [comment]
I fly the K-50 is I can say it is very good capable. Helicopters are vulnerable to IR missiles from manpads, and AR defenses with IR missiles. But they are pretty much protected against  radar guided missiles because its ability to fly very low and very slow eor even hover if it is nessary, in those situations the radar just can see them o get a lock or mantein a lock. So the KA-50 can verydo strike bombing missions, runaway bombing missions and DEAD mission. The vikrs if used well at 8 kms away poses a deadly threat to any sam because at 8 kms away, they usual protection they have are manpads, shilkas o similar, so....

**Comment by magwo** [comment]
@ThatOneguyC6 FYI the helicopter altitudes have been fixed. However, they still follow a join/hold/split flight plan which is not feasible for the speeds helicopters fly. I'm currently looking at ways to avoid this behaviour in the flight planning code.
