### ISSUE TITLE
'Ferry' as a mission type.

### ISSUE THREAD

**Issue by Floydii** [dcs-liberation/dcs_liberation#1439]
**Is your feature request related to a problem? Please describe.**
Currently aircraft cannot be simply told to fly from one base to another during a turn because there must be a task in between ( which task dependent on aircraft type). This requires the user to 'break' the mission to ensure the AI flight does not, for example, try to conduct a strike when it would be inappropriate to do so and the priority is relocation.

**Describe the solution you'd like**
A package mission type called 'Ferry' is created (click on a friendly airfield to activate) with a 'Ferry' task available to any flight assigned to it. To simplify implementation, the desired ferry destination should be chosen via the existing option to have aircraft land at a different one they took off from.

Waypoints:
The initial placement should put the final waypoint (before the landing one) in vicinity of the airfield targeted when the package was created (changing the flight's landing airfield will establish the landing waypoint). There should be enough waypoints to allow the automated mission planning to dog-leg flights around any threats.

Payload/ROE: 
Standard A2A loadout (or empty if none available) should be the default. The flight should react to being attacked, but otherwise ignore enemy and follow it's waypoints.

**Additional context**
The main usage case for this arose through seeking to transit hinds and KA50s to new bases or carriers at night where it was impractical to have them fly all the way to the frontline, which they couldn't see in the dark anyway.

**Comment by HILOK** [comment]
good idea. and it would also allow playing another turn, when the player has only a short time slot available...or is fatigued ; )
