### ISSUE TITLE
New start type: "ACCELERATED"

### ISSUE THREAD

**Issue by jeetsukumaran** [dcs-liberation/dcs_liberation#1440]
**Is your feature request related to a problem? Please describe.**

Many missions should typically be operating on a 24/7 cycle, e.g. BARCAPs, AWACS, refueling etc.. This means that they should already be in place when the player mission begins. Liberation can easily replicate this by having aircraft fragged to this mission take an "ACCELERATED" start type, which essentially spawns them in their stations. This also prevents players accidentally arriving at the their targets before the "party" starts (say, by taking off immediately and flying directly to the target), and the OPFOR BARCAP is still waking up. 

In addition, many times the player finishes their mission early and exits, never giving a chance for enemy strikes etc. to complete. Players on BARCAP also may find themselves doing nothing for most of the mission, 20-40 minutes of just flying above the airfield waiting for an enemy strike to take off etc. An "ACCELERATED" start type (for the OPFOR) will speed up the action.

**Describe the solution you'd like**

An ACCELERATED start type will spawn:

- BARCAP missions at their "RACE TRACK START" waypoint
- Refueling, AEW&C missions on their orbit waypoints
- All other missions (strike, escort, SEAD, SEAD escort, DEAD, TARCAP, OCA, etc.) at what is effectively their current JOIN waypoint (or would be a JOIN waypoint in a typical mission plan). We can even think about an "ACCELERATED 1" (spawn at HOLD waypoint, with 5 min orbit before push) and "ACCELERATED 2" (spawn at JOIN, no orbit, already pushed). etc.

Of course, this all can be set on a per flight basis, either by the AI or the player, with the default available in the settings. (Optionally, It would actually be nice for players to set different defaults for BARCAP and support missions vs all other types. This for the player side as much as for the OPFOR/AI. That is, the player may want to have both sides to at least have their BARCAPs and AWACS up at the mission start, even if strikes etc. all default to cold, warm, etc. Alternatively, a sensible default for the defaults would be "ACCELERATED" only for the *first* round of BARCAPs)

**Comment by DanAlbert** [comment]
Obsolete with https://github.com/dcs-liberation/dcs_liberation/issues/1681
