### ISSUE TITLE
current versioning philosophy

### ISSUE THREAD

**Issue by HILOK** [dcs-liberation/dcs_liberation#1442]
**big thanks everybody for devoting your precious time to this awesome game-changing software !!**

**as a regular user without too much IT knowledge, i am trying to understand the current versioning system. would some dev be so kind and shed some light please?**

1) currently there is a version 4.0.0 available as official release. time stamp says several days old. are there any plans to release updates more frequently as before (pre 3.x) ? (if not, just out of interest, what are the reasons?)

2) meanwhile development goes on continuously. if i wanted to test the latest development (on my own risk), after following the link https://github.com/dcs-liberation/dcs_liberation/wiki/Preview-builds
what do i need to do next ?

3) there is also a v5.x.x in development. is this version at all usable ?

**thanks**

**Comment by HILOK** [comment]
would some dev be kind enough to share his/her thoughts on the topic?
i am sure this would be of interest to other users as well...thanks : )

**Comment by Mustang-25** [comment]
1. At the very least the devs will try to keep Liberation running when DCS updates but given the open nature of this development and the fact that all the devs contribute to this project in their free time, we can't and shouldn't expect a regular release schedule. 
2. Follow the link to the action page and click on the build you want. From there you can download the build under the artifacts section if you are logged into github.
3. any dev build should be played at your own risk, there is no guarantee of stability or usability.

**Comment by HILOK** [comment]
@Mustang-25 thanks, very appreciated!!

_>At the very least the devs will try to keep Liberation running when DCS updates but given the open nature of this development and the fact that all the devs contribute to this project in their free time, we can't and shouldn't expect a regular release schedule._

that's understood. and i can see there has been a tremendous amount of work done since 4.0.0. hence i was wondering, if there was any particular reason that no intermediate update has been released ever since?
thanks
