### ISSUE TITLE
RuntimeError: Duplicate convoy unit: Convoy 001 Unit #1

### ISSUE THREAD

**Issue by Nova-111** [dcs-liberation/dcs_liberation#1446]
Before filing, please search the issue tracker to see if the issue has already been reported.

If reporting a DCS AI bug, check https://github.com/dcs-liberation/dcs_liberation#dcs-bugs.

**Describe the bug**
When I click "Take Off", nothing happens. I checked the other log window which shows the message "RuntimeError: Duplicate convoy unit: Convoy 001 Unit #1". No .miz file is created. A link for my .liberation file is https://drive.google.com/file/d/1To2uNxGEy5Xe0VPU4BU7idkIow7jfi6L/view?usp=sharing

**To Reproduce**
See above

**Expected behavior**
Mission created successfully

**Additional information**

We will usually need more information for debugging. Include as much of the following as you are able:

- DCS Liberation save file (the `.liberation` file you save from the DCS Liberation window). By default these are located in your DCS saved games directory (`%USERPROFILE%/Saved Games/DCS`).
- The generated mission file (the `.miz` file that you load in DCS to play the turn). By default these are located in your missions directory (`%USERPROFILE%/Saved Games/DCS/Missions`).
- A tacview track file, especially when demonstrating an issue with AI behavior. By default these are located in your Tacview tracks directory (`%USERPROFILE%/Documents/Tacview`).
- The state.json file from the finished mission when the problem is related to results processing. By default these are located in your Liberation install directory.

**Version information (please complete the following information):**
 - DCS Liberation 4.0.0:

**Additional context**
https://drive.google.com/file/d/1To2uNxGEy5Xe0VPU4BU7idkIow7jfi6L/view?usp=sharing

**Comment by DanAlbert** [comment]
The save already has the broken data. Without a way to determine how it got there we can't fix it. If you can figure out how to create the save with this problem let us know, but unfortunately there's nothing we can do with the info we have.

**Comment by DanAlbert** [comment]
Note that https://github.com/dcs-liberation/dcs_liberation/issues/1247 was the same symptom, but that was fixed before 4.0.0 was released. Unless you're actually running an old preview of 4.0, that wouldn't explain it.
