### ISSUE TITLE
Popup on top causes black screen

### ISSUE THREAD

**Issue by ace747** [dcs-liberation/dcs_liberation#145]
Please change this:

Line 18 in QMissionPlanning
self.setWindowFlags(Qt.WindowStaysOnTopHint)

This forces the popup to always be on top and screws with screen capture and screen sharing.  Your other popups such as for settings will work since this line does not exist in those classes.  However, whenever I click the mission planning button when sharing my screen (specifically sharing the liberation app), the screen share goes black because the popup is forced to the top, and focus is lost.

There must be a better way of doing this if you do in fact need the popup to be topmost.

**Comment by DanAlbert** [comment]
That window doesn't exist any more in 2.2.
