### ISSUE TITLE
SA-8/SA-13 unit files duplicate

### ISSUE THREAD

**Issue by sith1144** [dcs-liberation/dcs_liberation#1450]
There are three unit files related to the sa-8 and sa-13
SA-8 Osa LD 9T217.yaml
Osa 9a33 ln.yaml
Strela-10M3.yaml
There is some mix up in these. The first file has information regarding the SA-8, but lists the SA-13 as its only variant. The second file only contains a price and variant (so no description, role, class etc). The Strela-10M3 file appears to be correct.

Remove the Sa-8 Osa LD 9T217 file and verify the other files are correct

**Comment by DanAlbert** [comment]
> Remove the Sa-8 Osa LD 9T217 file

Note for whoever picks this up: don't do this, fix it.

**Comment by RndName** [comment]
I am just leaving some things from the discussion on discord here:

- SA-8 Osa LD 9T217 -was- an unarmed rearming unit which was implemented in DCS some time. Many confirmed that this was already existing! Therefore there as a pydcs unit in the vehicle.py!
- This unit is currently not in the game anymore (only tested latest open beta)
- in this https://forums.eagle.ru/topic/273770-encyclopedia-bug-maybe/?tab=comments#comment-4691212 ED said it is fixed internally, whatever this means. Is it removed completly or temporarly?

The current SA-8 generator in the code still created this LD vehicle as part of an SA-8 Group. Unfortunately this will not have any type in the MissionEditor and therefore will not be created as real group in the final mission.

![grafik](https://user-images.githubusercontent.com/6678803/126763710-dd49a3c7-e983-4a2d-836e-d0464cb14d4c.png)

**Comment by DanAlbert** [comment]
ED acknowledged that the missing SA-8 loader is a bug and it's been fixed internally. I'm tempted to just ignore this. It's not breaking the generated missions, so whenever DCS updates with the fix it'll fix any games using it.

**Comment by DanAlbert** [comment]
The other files look right to me. Descriptions are missing for the Osa but that isn't a bug. Someone can send a PR adding data if they want but it's unlikely we'll ever have complete data.
