### ISSUE TITLE
Seperate Flight and AWACs comm channels

### ISSUE THREAD

**Issue by spectre7512** [dcs-liberation/dcs_liberation#146]
In earlier versions of Liberation AWACS was on 133mhz by default. Currently AWACS default to 233mhz. With friendly flights on 251mhz in some aircraft this requires changing radios during intense situations where previously both channels could be listened to at the same time. Is it possible to set AWACs back to 133mhz?

**Comment by DanAlbert** [comment]
What aircraft is this a problem for?

**Comment by spectre7512** [comment]
I fly the f-16 mostly. With my flight and AWACS on the same radio I have to take my hand off the hotas to switch between freqs. If my flight is on say 251mhz on UHF radio and AWACS is on 133mhz on VHF radio I can listen to both without having to touch my radio. This was the default just a few versions ago. I am just wondering if it could be that way again.

**Comment by DanAlbert** [comment]
Your flight and AWACS shouldn't be on the same radio as of the current release. AWACS should be on UHF and your flight should be on VHF.

**Comment by spectre7512** [comment]
Great, just downloaded 2.1.1. Not finding the flight or AWACS freqs in the briefing. Am I just missing them?

**Comment by DanAlbert** [comment]
Comm info all moved to the kneeboard because channel assignments vary per-flight. The AWACS/tanker/JTAC frequencies could be put back in the briefing if that helps, but the kneeboard seems strictly more useful?

**Comment by spectre7512** [comment]
Awesome, I missed the comm stuff in the release info. No, the kneeboards are a great idea. I can talk with ATC and AWACS fine on UHF but I can't transmit to my flight on VHF in the F-16 for some reason. Have to track down why. Thanks so much for your help. Liberation is an incredible project.

**Comment by DanAlbert** [comment]
No problem, glad to hear it's (mostly) working :)

> Have to track down why

What frequency did your flight get allocated? I pulled the valid range from the Chuck's guide, so it should be somewhere between 108.000 MHz and 173.975 MHz, although I see the BMS manual says it should only go to ~152 MHz (the DCS manual says nothing on the subject).

**Comment by spectre7512** [comment]
Not sure what the issue is. Kneeboard says flight freq was 116 mhz. I could hear my flight making calls but couldn't transmit orders. Just tested and VHF transmit works fine in single and multiplayer.
