### ISSUE TITLE
Incorrect campaign submission

### ISSUE THREAD

**Issue by pilnick** [dcs-liberation/dcs_liberation#1460]
![image](https://user-images.githubusercontent.com/40298625/126903815-5d6af7a9-2758-4cb9-8db1-683dc143374f.png)
This error occurred when submitting battle settlement after the last enemy base was shot down. The result could not be submitted.
I wonder if there is a picture of the success or failure of the battle and the damage of the battle until the whole battle is finished.

**Comment by RndName** [comment]
@pilnick thanks for your bug report. Please use the template to fill bug reports. Without any more information like the **save file**, the **state.json**, **version number** and so on we can not really look into such problems.

Please attach the things above
