### ISSUE TITLE
JAS 39 Gripen - Loadouts not appearing correctly in missions

### ISSUE THREAD

**Issue by NeelKulkarni6** [dcs-liberation/dcs_liberation#1463]
**Describe the bug**
In both the A-A and A-G versions of the Gripen, the loadouts in liberation do not match what is there in-game. For example in liberation, ill try to set a default cap loadout with 4 asraams, but in-game it bugs out and the only thing there is an ecm pod. The same thing happens in the A-G version. For players, this can easily be fixed in-game by requesting the ground crew to rearm, but the ai aircraft can't do this. 

**To Reproduce**
1. Set up a flight with either a-a or a-g loadout
2. observe the error in the mission

**Expected behavior**
For the correct loadout to be there

SAVEFILE: 
https://www.filemail.com/d/uqpoqnmvzjwnqlo
file link only lasts for 1 week, if requested I can send it again

**Version information (please complete the following information):**
 - DCS Liberation  4.0.0

**Comment by kevstosmart** [comment]
the mod updated, prob new stuff or things changed. lib cant figure whats what with the mod not a bug. the mod just needs to be updated on liberations lib
