### ISSUE TITLE
Update for campaigns (Fuzzle)

### ISSUE THREAD

**Issue by sgtfuzzle17** [dcs-liberation/dcs_liberation#1464]
In preparation for the coming update, submitting this so that my campaigns (listed below) can be bumped to the new version. None of them have scenery targets and just need a .json bump.

- Operation Allied Sword
- Operation Blackball
- Scenic Route

**Comment by DanAlbert** [comment]
https://github.com/dcs-liberation/dcs_liberation/pull/1467
