### ISSUE TITLE
[Build 2511] AI Planner Purchasing a Confusingly Large Amount of Tankers

### ISSUE THREAD

**Issue by Mustang-25** [dcs-liberation/dcs_liberation#1470]
In the campaign my group is running, we noticed that the Red side had purchased 18 tankers as illustrated below.

![](https://cdn.discordapp.com/attachments/844372015989129216/870175091139420200/unknown.png)

The intended behavior I suppose is that it shouldn't buy that many. Maybe Just 1 planned for each frontline and 1 or 2 each in reserve?

Saves and miz attached below.

**Comment by DanAlbert** [comment]
Only in dev, right?

**Comment by Mustang-25** [comment]
Correct, only on dev that I've seen and I haven't seen anyone else on Discord mention this problem in release.

Also, I noticed that it purchased all of them in a single turn:

![image](https://user-images.githubusercontent.com/72566076/127529334-55787c0f-1008-445a-bc04-37358b90ae3b.png)

**Comment by DanAlbert** [comment]
I think you forgot to actually attach them. Don't suppose you still have them? It's not too hard to repro but your case was pathologically bad enough that I wanted to make sure it was really fixed.

**Comment by Mustang-25** [comment]
> I think you forgot to actually attach them. Don't suppose you still have them? It's not too hard to repro but your case was pathologically bad enough that I wanted to make sure it was really fixed.

Whoops! I did indeed forget. Here's the files:

[Saves.zip](https://github.com/dcs-liberation/dcs_liberation/files/6913426/Saves.zip)

**Comment by DanAlbert** [comment]
Submitted a change to dedup purchase orders. It's not an ideal fix but I need to put more thought into how we might fix this better, but if we end up deciding to make pilots the resource rather than aircraft we won't actually _need_ any purchase logic, so maybe not needed.
