### ISSUE TITLE
HAVE an option to have OR NOT observator slot AND tactical user slot

### ISSUE THREAD

**Issue by Kervinou** [dcs-liberation/dcs_liberation#1481]
Before filing, please search the issue tracker to see if this feature has already been requested.

If requesting a DCS AI feature, check If reporting a DCS AI bug, check https://github.com/dcs-liberation/dcs_liberation#dcs-bugs.

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Hi, another thing that would be great to have : an option to have OR NOT observator slot and tactical user slot. Disabling the observer slot would be good to prevent a pilot from seeing enemy units. Thanks

**Additional context**
no

thanks

**Comment by Mustang-25** [comment]
Closed #905 and consolidating the FR here under the general umbrella of being able to select the number of observer and commander slots.

**Comment by DanAlbert** [comment]
Duplicate of #2235 (kind of, but either ready fixed)
