### ISSUE TITLE
HAVE MPRS refuel tanker at M0.7 and not M0.85 :)

### ISSUE THREAD

**Issue by Kervinou** [dcs-liberation/dcs_liberation#1482]
Before filing, please search the issue tracker to see if this feature has already been requested.

If requesting a DCS AI feature, check If reporting a DCS AI bug, check https://github.com/dcs-liberation/dcs_liberation#dcs-bugs.

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Doing more slowly C135 MPRS (this evening i refueled at approximatively M0.86) !! make it at M0.7 will be good  :slight_smile:
Max 350 kts to expand fuel probe on FA18 
Thanks

**Additional context**
No

Thanks

**Comment by Mustang-25** [comment]
Reclassifying this as a bug. MPRS should be moving at a slower speed.

**Comment by Mustang-25** [comment]
Able to reproduce it in-game on build 2631. Both MPRS and boom 135 reach their fragged altitude but speed up to 500kts GS which brings them to around 340 indicated. Looking in the ME, the speed of the racetrack has been set to 545kts for the MPRS and 530kts for the Boom 135 so I guess something else is overriding the speeds listed in the aircraft yaml.
