### ISSUE TITLE
Liberation (#2653) crashes if log window is open when entering mission

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#1493]
**Describe the bug**
The new log window implementation causes Liberation to crash to desktop if the log is open when mission starts up. The log window also cannot be scrolled through (and also appears to no longer update) once "Take Off" is hit, which significantly reduces its utility.

**To Reproduce**
1. Open log window
2. Hit Take Off
3. Start mission in DCS
4. Liberation crashes

**Comment by magwo** [comment]
@pbzweihander 

>

**Comment by pbzweihander** [comment]
@Starfire13 I can't reproduce.. Could you provide the log from `logs` folder?

**Comment by Starfire13** [comment]
@pbzweihander Here's the liberation.log file. The crash to desktop (It's Liberation crashing, not DCS) is still occuring consistently on #2904. Once I load into the mission, Liberation simply CTDs. I don't see any errors in the log file though.

[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/7343701/liberation.log)

By the way, apart from the log window causing this crashing, the fact that the log window cannot be manipulated once take off button is clicked is not ideal, because being able to scroll through and copy text from it it is really handy for troubleshooting.

**Comment by DanAlbert** [comment]
Unless we get a fix for this for 5.0.0 we'll revert the new log window before release.
