### ISSUE TITLE
Flight Plan display bug hides all flights plans when any other option is selected after clicking Show All

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#1496]
**Describe the bug**
After Clicking "Show All" under Flight Plans, clicking Show Selected Blue, Show All Blue, or Show All Red will Hide all Flight Plans instead of showing the correct selection.

**To Reproduce**
1. Click Show All
2. Click any of the 3 options above it
3. All Flight plans get hidden

#2676 Preview

**Comment by DanAlbert** [comment]
Should be obsolete now that the map has been replaced.
