### ISSUE TITLE
Err on stratup

### ISSUE THREAD

**Issue by Shrikee** [dcs-liberation/dcs_liberation#15]
1. launched liberation_main.exe
2. saved paths
AR: https://imgur.com/a/Gf1XDD1
Version : RC9

**Comment by Khopa** [comment]
Do you have an old save game from a previous version of DCS Liberation in your DCS saved game folder ? (The file name is liberation_save)
If so, delete it, and relaunch DCS liberation RC9.

**Comment by Shrikee** [comment]
> Do you have an old save game from a previous version of DCS Liberation in your DCS saved game folder ? (The file name is liberation_save)
> If so, delete it, and relaunch DCS liberation RC9.

It worked, thanks 👍
