### ISSUE TITLE
Weather presets not working on Syria map

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#1500]
**Describe the bug**
At least on the Syria map, weather presets do not appear to be working. I am using Spring 95 and SchmokedPancake is using Summer 2021, and we are both only getting clear skies on every turn. Not certain if this is specific to Syria map, but it is definitely occuring on that map.

#2676 Preview

**Comment by Starfire13** [comment]
Looks like the same issue occurs on the PG and NTTR maps. Normandy, Channel, and Caucasus are fine. While Syria, PG, and NTTR both have more arid climates, having clear skies 90% of the time is a tad boring. A higher frequency of scattered clouds would be nice.

**Comment by magwo** [comment]
#1501

**Comment by magwo** [comment]
Just to confirm @Starfire13, if you skip like 20 rounds, you don't always get clear sky, right?
