### ISSUE TITLE
Battle Damage Assesment

### ISSUE THREAD

**Issue by DevastatorCM** [dcs-liberation/dcs_liberation#1508]
**Is your feature request related to a problem? Please describe.**
At the moment with default mission setup of Liberation, each hit can be seen by the player with damage report which is making the game a bit unrealistic unless it is manually turned off in mission editor after liberation generates the mission.

**Describe the solution you'd like**
Would be nice to have an option in liberation to turn off battle damage assesment to prevent the manual effort by each mission generated

**Additional context**

**Comment by Mustang-25** [comment]
You can disable the BDA window in DCS through options > misc. > overlays

**Comment by DevastatorCM** [comment]
I know that. My point is to disable it via Liberation setting instead of doing it in mission editor (to disable for all players) or at my end.
Goal is to disable it for all mission players but over liberation

**Comment by Mustang-25** [comment]
Feature added to dev branch, will be included in a future release. Marking this request as closed.
