### ISSUE TITLE
Enemy faction  purchase priorities

### ISSUE THREAD

**Issue by Furia139** [dcs-liberation/dcs_liberation#1509]
One issue I am encountering is that no matter what enemy faction I am selecting for a campaing, if they always priorize the purchase of aircraft over ground units. It happens with faction with inventories of 10 different aircraft or inventories of just 2 different types of aircraft. Priorities always go for aircraft and if the faction is given few money resources, they it buys the expensive aircraft and very few ground vehicles.
I would like to have the option while configuring the campaing to define the enemy "ORBAT" a bit by prioritizing the weapons system adquisitions policy. So for instance  as a fictional example, I could create an enemy that dedicates 30% of its resources to purchase aircrafts and dedicates the other 70% in (25% Air defense Systems like SAM AAA and EWR and 45% in ground forces)
This way the one enemy faction would also provide different possibilities in the campaing by being ground reinforced or air reinforced or even combinations of weak air and weak ground but very strong SAM defences.
We just need to be able to define the priorities where the enemy would place its money to better define the faction.
It helps us to better customize the campaing and make most use of a faction that could be used in multiple strategic postures.
Thanks

**Comment by RndName** [comment]
@Furia139 the current version already has an automated way to split the budget for ground and air units based on the ratio between existing ground units / aircraft. The AI "aims" to have a 50/50 ratio if iirc.

I am not quite sure if setting the ratio for ai spending money directly in the campaign generation will lead to a better result.

Which version are you currently running? Maybe we have to investigate why the ratio is broken on your side

**Comment by DanAlbert** [comment]
Duplicate of #505

**Comment by Furia139** [comment]
> @Furia139 the current version already has an automated way to split the budget for ground and air units based on the ratio between existing ground units / aircraft. The AI "aims" to have a 50/50 ratio if iirc.
> 
> I am not quite sure if setting the ratio for ai spending money directly in the campaign generation will lead to a better result.
> 
> Which version are you currently running? Maybe we have to investigate why the ratio is broken on your side

Could you please let me know where is this ratio defined? That could be a solution for what I need.
Thanks

**Comment by Furia139** [comment]
> @Furia139 the current version already has an automated way to split the budget for ground and air units based on the ratio between existing ground units / aircraft. The AI "aims" to have a 50/50 ratio if iirc.
> 
> I am not quite sure if setting the ratio for ai spending money directly in the campaign generation will lead to a better result.
> 
> Which version are you currently running? Maybe we have to investigate why the ratio is broken on your side

Could you please let me know where is this ratio defined? That could be a solution for what I need.
Thanks
