### ISSUE TITLE
Increase Tanker On-Station Time

### ISSUE THREAD

**Issue by Mustang-25** [dcs-liberation/dcs_liberation#1511]
**Is your feature request related to a problem? Please describe.**

The current on-station duration for tankers is set at 1 hour. This can lead to situations where aircraft need fuel but do not fall within the refueling window. In the default mission duration of 1 hour, you'd have to choose a window of either refueling at the start of your flight plan or at the end but, depending on how long your mission takes, you might not necessarily have the window to do both.

**Describe the solution you'd like**

Increase the on-station time to 1.5 or 2 hours. Or maybe a function of the set mission duration like x+30 minutes?

Doing it this way would allow for a larger refueling window without having to purchase more refueling aircraft. Especially helpful for campaigns with lower budgets or airfields with limited parking spaces.

**Comment by DanAlbert** [comment]
The better fix (we could be in _addition_ to this) is specific tanker tasking for packages so that the start and end times line up with the mission timing. The timing is better and it'll automatically be in a more useful location.

**Comment by DevastatorCM** [comment]
I usually use two tankers taking off in different times to cover the full mission time. One question, is there a way to see the onstation time of the tanker? If yes, could be nice to have this info for Awacs and Tankers on the kneepad as well

**Comment by HILOK** [comment]
don't know, if related. i had this happen regularly in the scenic route campaign, when trying to refuel during return from target:

after getting positive acknowledgement to my "approaching for refuel call, some 25nm away, an AI plane squeezes in before i get close enough for "ready pre-contact". when the AI plane has finished refueling, the tanker terminates responding.

v5.0 (never happened on v2.5)
option mission time set to 60min

**Comment by zhexu14** [comment]
Closing as the suggested implementation of desired mission duration + 30 minutes was implemented and merged into the develop branch.
