### ISSUE TITLE
"Allowed Mission Types"~ Squadrons don't follow their Roles

### ISSUE THREAD

**Issue by KeeseAF** [dcs-liberation/dcs_liberation#1515]
Before filing, please search the issue tracker to see if the issue has already been reported.

If reporting a DCS AI bug, check https://github.com/dcs-liberation/dcs_liberation#dcs-bugs.

**Describe the bug**
Squadrons that have specific mission types don't follow them. The UI always seem to prioritize 1 squadron for flight scheduling before moving to the next squadron.

**To Reproduce**
Any Dev build since implementation. Current build #2716

**Expected behavior**
-A squadron set for only ground war should not be scheduled for Air war, and vice versa

**Additional information**

We will usually need more information for debugging. Include as much of the following as you are able:

- DCS Liberation save file (the `.liberation` file you save from the DCS Liberation window). By default these are located in your DCS saved games directory (`%USERPROFILE%/Saved Games/DCS`).
- The generated mission file (the `.miz` file that you load in DCS to play the turn). By default these are located in your missions directory (`%USERPROFILE%/Saved Games/DCS/Missions`).
- A tacview track file, especially when demonstrating an issue with AI behavior. By default these are located in your Tacview tracks directory (`%USERPROFILE%/Documents/Tacview`).
- The state.json file from the finished mission when the problem is related to results processing. By default these are located in your Liberation install directory.

**Version information (please complete the following information):**
 - DCS Liberation [e.g. 2.3.1]:

**Additional context**

**Comment by DanAlbert** [comment]
Not enough information. What's the problem? Your repro instructions are not sufficient for me to know what you're talking about.

It sounds like you're saying the auto planner isn't obeying the squadron settings, in which case we need a save game, but then you mention the UI, so I'm not sure what you mean.

**Comment by KeeseAF** [comment]
Im sorry, i tend to always mess these up. 

The problem is, is that the squadrons that are set for specific tasks, aren't getting assigned those specific tasks. For Example. I have 1 F-16 Squadron set for "ground ops" SEAD, DEAD, CAS etc, and i have another F-16 set for specifcally air superiority IE. TARCAP BARCAP . 

The issue seems to be that no matter what the squadron is assigned to, the "auto planner" will just use 1 squadron up fully and then move on to the next available squadron.  Attached is my saved game.

**Comment by DanAlbert** [comment]
> is that the squadrons that are set for specific tasks

Set how? There's more than one way to do this, and they have different behaviors.

> Attached is my saved game.

I think you missed, because it isn't :)

**Comment by KeeseAF** [comment]
Whenever you create a new game, in the beta ( I am currently in Build #2716), as soon as you click finish, there is a option to turn  on and off certain squadrons that you would like. For example, I only fly American airplanes so I click the green box alongside any and all aircraft that is not American to turn OFF those squadrons. Now, along the right hand side are a bunch of boxes. In those boxes are a bunch of different missions that ( I'm assuming ) allows you to decide what you want a specific squadron to do. For example. 

For the 2 F-18 squadrons that are available I want:

Squadron 1: I want to have this squadron do ONLY

-TARCAP
-BARCAP
-ESCORT
-INTERCEPT

Squadron 2: I want this squadron to do ONLY:

-CAS
-SEAD
-DEAD
-SEAD ESCORT
-BAI

~ I set all of this up when Before I "Begin Campaign" 
~Then I verify if the squadrons are set correctly after I click "Begin Campaign" and are all concurrent

However,
Once I Click next turn, I no longer see the "auto planner" use the squadrons how they are supposed to be used. For example, I will see all of Squadron 1 Being used according to their " Contract " which is to be used as Pure Air to Air.

**_The problem that I'm having trouble with is, The auto planner doesn't care about who does what, It will use the squadrons from top to bottom. And in terms of priority it will auto-plan BARCAP first._**

The Auto-planner doesn't take into account the mission sets for a set squadron.

To Replicate: Make a new campaign and set up 2 squadrons. 

Make 1 squadron set only to do CAS

Make the other do BARCAP .

Once you started the campaign and start turn 1, you can see how the auto planner uses both squadrons by clicking on a package and seeing the squadron who is doing the BARCAP and the CAS. 

Note: I usually "deal" with this situation by having the 1st Squadron be the BARCAP Squadron, however the autoplanner frequents having the CAS squadrons pilots.

I Usually play on 150 minute mission times, however with testing this happens on any time below 150 minutes. 

Hopefully this does a better job at explaining the "bug" with the auto planner enough as for some reason im having difficulty transferring my saved game file. I think there is a file sharing setting that I have enabled and forgot about :/ I will do my best to update this with a file as soon as I can.

**Comment by KeeseAF** [comment]
[autosave (2).zip](https://github.com/dcs-liberation/dcs_liberation/files/6949259/autosave.2.zip)

**Comment by DanAlbert** [comment]
Got it, thanks. To explain my confusion, you can set the mission types in that menu, in the air wing menu, and in the custom squadron files.

This does indeed sound like a bug, and I think I have enough to investigate now 👍

**Comment by DanAlbert** [comment]
Your save game won't load:

```
2021-08-07 13:51:33,283 :: ERROR :: Invalid Save game
Traceback (most recent call last):
  File "C:\Users\dan\src\dcs_liberation\game\persistency.py", line 48, in load_game
    save = pickle.load(f)
MemoryError
```

Did you by any chance modify it before uploading? Some people do that. It breaks them.

**Comment by DanAlbert** [comment]
Was able to recreate the problem though, so not needed.

**Comment by DanAlbert** [comment]
It's fixed, but the problem was happening during campaign startup so existing campaigns will remain broken.

**Comment by KeeseAF** [comment]
Thank you so much, sorry i was away all this time.
