### ISSUE TITLE
PATRIOT STR with the "auto pointing on center of conflict" feature

### ISSUE THREAD

**Issue by Wawar9** [dcs-liberation/dcs_liberation#1526]
Hey guys, just a little feedback about the new "SAM pointing on center of conclict" feature, comes with the 4.1.0. 

We still have an issue with the Patriot STR, even with the new "auto center to central point of conflict" feature. The Patriot STR is not gimballed and have to be pointed on the good heading to be able to perform. 

The issue comes from the positioning of the STR in the "template" of the Patriot Site itself in the mission generation. It could be fixed by changing the heading of the STR itself in the template, or by adding more STR to cover more azimuths.

![lib1](https://user-images.githubusercontent.com/82789122/128780767-a48623c6-fc1a-4f1d-9003-6f27a3e23a46.jpg)
![lib 2](https://user-images.githubusercontent.com/82789122/128780772-2e6f8c0b-1186-41cc-8939-5230d9d78d33.jpg)

**Comment by magwo** [comment]
Fixed in 4.1.1
