### ISSUE TITLE
Su-34 should not be listed as CAP capable aircaft

### ISSUE THREAD

**Issue by foxwxl** [dcs-liberation/dcs_liberation#1528]
**Describe the bug**
Though Su34 is capable of using R77, it is NOT a Fighter, it's a tactical bomber to replace Su24, not a Su30/F15E kind multi-role fighter. The R-77 or R-27 is for self defence only. 
And since Su-34 is R77 capable, it seems that the ATO will even pick Su-34 rather than Su-27(Only R-27 capable) for CAP mission in some case, which cause a total mess in auto mission planning. 

**To Reproduce**
Choose any faction with Su34.

**Expected behavior**
Remove Su-34 from CAP capable list.

**Additional information**
And We don't call this as CAP capable, right?
![Su-39_02](https://user-images.githubusercontent.com/74572837/128841439-d2527e82-ef41-4a9b-ae95-6cad4f6666ec.jpg)

**Comment by magwo** [comment]
Fixed in 4.1.1
