### ISSUE TITLE
Avoid TACAN channels disturbing Link-16 datalink for F-16C and F/A-18C

### ISSUE THREAD

**Issue by jchcommun** [dcs-liberation/dcs_liberation#1529]
Some TACAN channels (especially A/A TACAN) disturb Link-16 datalink (up to the point the datalink doesn't work anymore at all for the F-16C and the F/A-18C), as described in https://forums.eagle.ru/topic/276390-datalink-issue/.

Each time I generate a mission with DCS liberation, I have to change the TACAN channels in DCS mission editor to avoid this problem, because the channels used for tankers and ships include degraded ones. For example, tankers are generated with TACAN channels 1Y, 2Y, etc. I have to change them to 41Y, 42Y, etc. so datalink can work for F-16Cs and F/A-18Cs. Same for ships, generated with 1X, 2X, etc. (1X is OK but not 2X, for example, so I change them to 31X, 32X).

Would it be possible to automatically generate tankers and ships with non-degraded TACAN channels, please? The chart of degraded / non-degraded TACAN channels is attached here: ![Degraded TACAN Channels](https://user-images.githubusercontent.com/83498966/128848939-529b6539-ee83-4d00-af7c-a75a3a00291c.png)

Thanks!

**Comment by DanAlbert** [comment]
Is this correct behavior from DCS, or is it a DCS bug? It seems like the former but some people in that thread aren't sure.

Is the list of degraded channels the same for all aircraft?

**Comment by jchcommun** [comment]
Correct behavior or not, I don't know, I haven't found any official information confirming it one way or the other at the moment.

Regarding the aircrafts, as far as I know, the issue touches the F-16C (I'm sure of this, as I fly this one and I can reproduce the problem and the solution) and the F/A-18C, for the same channels it seems, though I don't fly the F/A-18C, but the diagram provided by ED is labeled with this one.

**Comment by magwo** [comment]
This is pretty crazy, I will take a look.

**Comment by magwo** [comment]
@jchcommun Do you know if 47-63 X is in fact available for A/A?

**Comment by jchcommun** [comment]
Well, the values I have actually used for aerial refueling in my missions (not DCS liberation ones) on the X channels were 41X to 43X. I haven't tested 47-63X, but according to the channels diagram I posted, I guessed they can be used as well (?)

**Comment by magwo** [comment]
Fixed in develop branch now. Expect it in 5.0.

**Comment by jchcommun** [comment]
Hello Magnus,

Thanks a lot!

Have a nice day.

Regards,
JC.


Le mar. 17 août 2021 à 23:15, Magnus Wolffelt ***@***.***> a
écrit :
