### ISSUE TITLE
Click the TAKE OFF button to report an error

### ISSUE THREAD

**Issue by spark135246** [dcs-liberation/dcs_liberation#153]
2.1.0 can still be played, 2.1.1 reported an error

![image](https://user-images.githubusercontent.com/26293439/94260581-04776480-ff63-11ea-9323-4de5b634c2ec.png)

![image](https://user-images.githubusercontent.com/26293439/94261308-3937eb80-ff64-11ea-8af3-a15197d64fd6.png)

**Comment by Khopa** [comment]
Hello, 

Can you temporarily remove the file mentionned in the second screenshoot, and try again ?

Thanks,

----------

(It is probably the same error as mentionned here : https://github.com/rkern/line_profiler/issues/37)

**Comment by spark135246** [comment]
![image](https://user-images.githubusercontent.com/26293439/94382656-23971180-0170-11eb-8e67-f53bf0b75510.png)

![image](https://user-images.githubusercontent.com/26293439/94382773-88526c00-0170-11eb-88ee-6952354a12fc.png)

![image](https://user-images.githubusercontent.com/26293439/94382797-999b7880-0170-11eb-9fac-145a379869ea.png)

**Comment by spark135246** [comment]
works!

![image](https://user-images.githubusercontent.com/26293439/94442133-2fb5ba00-01d6-11eb-89df-90acf7339095.png)

![image](https://user-images.githubusercontent.com/26293439/94442184-3e9c6c80-01d6-11eb-90be-7be466370b5b.png)

![image](https://user-images.githubusercontent.com/26293439/94442241-4fe57900-01d6-11eb-9b8f-599ceb526d24.png)

**Comment by Khopa** [comment]
Hello spark135246,

Sorry i had not the time to perform or try the change myself; but i'm glad to see that you found a solution.

You could submit a pull request to the pydcs library there : https://github.com/pydcs/dcs 
I have seen that there is actually an open issue there with the same error. (See https://github.com/pydcs/dcs/issues/77)

Thanks for your help !
