### ISSUE TITLE
More Patriot STR in Patriot sites.

### ISSUE THREAD

**Issue by Wawar9** [dcs-liberation/dcs_liberation#1531]
As suggested per Mags on Discord, I forward the idea on Github : 

Currently, in the Lib Patriot sites, there is only one STR, wich is watching at a fixed heading. 

Add other STRs that look at different heading would allow to cover more azimuths for the hi-end NATO SAM system.

Moreover, In Lib S300 sites have 2 TR. It's always interesting to have some sort of redundancy, especially for a 300M$ sam site.

**Comment by magwo** [comment]
I think it would be nice to first research if this is realistic - does a Patriot site ever use more than one radar unit IRL? Maybe it doesn't even technically support multiple radars?

But from a gameplay perspective it would be nice if Patriot's default config was more comparable to the SA-10.

**Comment by Mustang-25** [comment]
> I think it would be nice to first research if this is realistic - does a Patriot site ever use more than one radar unit IRL? Maybe it doesn't even technically support multiple radars?

IRL patriot batteries operate in multiple sections and has a much more complex network than DCS really simulates. The generator we have in Liberation is just a single section so to simulate reality you'd want multiples of them would work in concert to cover a broader front. That also gets into different strategies of converging or diverging coverage. FM 3-01.85 has more info if you want to read up on it.

**Comment by Wawar9** [comment]
@magwo I don't really have any doubt about the fact that in a modern IADS system, BLU or OPFOR, have the capability to fuse the data from multiple sensors, to increase the lethality and the survivability (redundancy) of the system. 

@Edit : Thanks for the ref Mustang-25

In the same way, without knowing if the current setup was based on evidences : Is the S300P Firstgen that we have in DCS was compatible and commonly deployed with two 30N6E Flap Lid ?
