### ISSUE TITLE
Harriers won't take off

### ISSUE THREAD

**Issue by Navidator** [dcs-liberation/dcs_liberation#1544]
In Build #2758 there is bug. Harriers won't take off when you have cold start selected. one harrier stands on deck with wheel chocks on.

**Comment by DanAlbert** [comment]
We can't investigate if you don't fill out the bug template.

Do your harriers have waypoints? If they have waypoints and aren't taking off when their takeoff time arrives, this is a DCS bug and there's nothing we can do about it.
