### ISSUE TITLE
Invalid entries in killed_ground_units

### ISSUE THREAD

**Issue by michael-davenport** [dcs-liberation/dcs_liberation#1545]
Version v5.0.0-2511-preview

During a campaign mission, some entries appeared in the state.json file under killed_ground_units that appeared to be invalid. Rather than a string representing a group name, these were just numbers - maybe a static map object? Liberation was unable to submit this state.json file.

Reloading the backup save, removing these entries from the json and submitting it allowed Liberation to proceed.

Full liberation log from this session is [here](https://pastebin.com/JkeC9fFt)
Tacview is [here](https://drive.google.com/file/d/1-BFP1mtPLwgs-HqgdyJWJgU4hO_WleMc/view?usp=sharing)
Original state.json is [here](https://pastebin.com/QGu3AHQJ)
Corrected state.json is [here](https://pastebin.com/00jZX8yD)
![liberation_main_bln9IOPQQ4](https://user-images.githubusercontent.com/52147153/129460280-93af377c-3660-41fe-af3b-9372f0e93c2e.png)

**Comment by RndName** [comment]
@michael-davenport thanks for your bug report. Please use the The template which github requires you to fill out a bug report. This also asks for the needed files like the savegame.

Also you are running a quite old preview of the Develop Branch (1 month).
To reproduce we definetly need the savegame file which is not part of this bug report
