### ISSUE TITLE
Warp Drive to spawn unable to pilot the aircraft

### ISSUE THREAD

**Issue by SynchroHD** [dcs-liberation/dcs_liberation#1546]
Before filing, please search the issue tracker to see if the issue has already been reported.

If reporting a DCS AI bug, check https://github.com/dcs-liberation/dcs_liberation#dcs-bugs.

**Describe the bug**
As i spawn, i see a sort of transportation to the airport while in my cockpit, after i arrive, im unable to control my aircraft and only able to see in external views and map.

**To Reproduce**
1. Start a mission and select pilot slot
2.
**Expected behavior**
1. I expect to spawn as normal and be able to utilize my aircraft

**Additional information**

We will usually need more information for debugging. Include as much of the following as you are able:

- DCS Liberation save file (the `.liberation` file you save from the DCS Liberation window). By default these are located in your DCS saved games directory (`%USERPROFILE%/Saved Games/DCS`).
- The generated mission file (the `.miz` file that you load in DCS to play the turn). By default these are located in your missions directory (`%USERPROFILE%/Saved Games/DCS/Missions`).
- A tacview track file, especially when demonstrating an issue with AI behavior. By default these are located in your Tacview tracks directory (`%USERPROFILE%/Documents/Tacview`).
- The state.json file from the finished mission when the problem is related to results processing. By default these are located in your Liberation install directory.

**Version information (please complete the following information):**
 - DCS Liberation [e.g. 2.3.1]: 4.1.1

**Additional context**
Sometimes it is fixed by passing a turn and doing the exact same mission
[TurnBugSynchro.zip](https://github.com/dcs-liberation/dcs_liberation/files/6987375/TurnBugSynchro.zip)
https://im4.ezgif.com/tmp/ezgif-4-ce94df93118e.gif

**Comment by Mustang-25** [comment]
Is your client slot on delayed start? A couple people have had a similar problem before and they were delayed starts.

**Comment by SynchroHD** [comment]
> Is your client slot on delayed start? A couple people have had a similar problem before and they were delayed starts.

After ASAP checkbox is checked it seems to have fixed it.
