### ISSUE TITLE
9.0 campaign squadron issue

### ISSUE THREAD

**Issue by kevstosmart** [dcs-liberation/dcs_liberation#1564]
Before filing, please search the issue tracker to see if the issue has already been reported.

If reporting a DCS AI bug, check https://github.com/dcs-liberation/dcs_liberation#dcs-bugs.

**Describe the bug**

**To Reproduce**
1. create a squadron for beirut 
2. set up lib 1st turn normally 
3.hit take off after setting up packages and it does nothing log stops when the flight planner for beirut starts
4. no mission generated

**Expected behavior**
dev build, squadron yaml file. beirut must be bugged lib breaks if any squad is set to start from there. 

**Additional information**

We will usually need more information for debugging. Include as much of the following as you are able:

**Version information (please complete the following information):**
 - DCS Liberation [e.g. 2.3.1]: latest dev build

**Additional context**

choose every other airport besides beirut

**Comment by DanAlbert** [comment]
> create a squadron for beirut

Upload that and the campaign.
