### ISSUE TITLE
enemy ai aircraft not spawning at airfield

### ISSUE THREAD

**Issue by TheLurk** [dcs-liberation/dcs_liberation#1566]
Hello,

In my current Black Sea campaign I have ran into an issue where at Tiblisi no Enemy AI Aircraft are spawning.

Tiblisi is currently held by Redfor, the Runway is damaged, 4 turns to repair remaining, there are plenty of aircraft there according to intel, but none of them are being spawned in the mission.
see images:

![image](https://user-images.githubusercontent.com/89359563/130369615-f5643dbb-3dec-4281-967c-e9d5744b32fd.png)

![image](https://user-images.githubusercontent.com/89359563/130369627-02602831-0dfb-4228-93fd-d8a188d23483.png)

there are no static defenses left and the frontline is fairly close to the airfield. 

save game and .miz file attached in the zip file. played on my own dedicated server with 2 human players, current lib release, current dcs open beta. cold starts are used. 

thanks!

[Savegame and miz.zip](https://github.com/dcs-liberation/dcs_liberation/files/7028128/Savegame.and.miz.zip)

**Comment by CMGolden** [comment]
I'm having the same issue at Maykop. We bombed the runway to destruction, leaving 50+ aircraft on the ramp to destroy (per Liberation), but.... they weren't there when the mission was run.
![image](https://user-images.githubusercontent.com/89716523/131236697-72d5c88d-c620-4aa1-8f58-10b1e38453c0.png)
![image](https://user-images.githubusercontent.com/89716523/131236829-4dbd6bed-14be-49a9-8ac8-667c88c7fa9b.png)
Edit: this happened on the Black Sea campaign.

**Comment by DanAlbert** [comment]
No save game attached. Provide that and we'll reopen.
