### ISSUE TITLE
AI attacking only single units with multiple munitions (overkill)+ ghost targets

### ISSUE THREAD

**Issue by NightstalkerNOR** [dcs-liberation/dcs_liberation#1568]
Possible two part bug:
1 - AI-assets attacking the same target with multiple individual weapons even though the target is very likely to be killed (ovekill). AI may spend a full load on a single unit, ie. BTR killed with 4 mavericks, 4 JDAMs/GBUs, leaving other units in the target location unharmed.
2 - AI attacking targets not visible, or missing its target but would have hit if the targets didn't move.  Are targets for the AI generated by coordinates, rather than the actual unit?

**Describe the bug**
The bug seems to be in two parts

1: (Waste of munitions) 
Loading up an AI-aircraft with AG-weapons tasked with SEAD/DEAD or Strike mission, the AI engages the same target with multiple individual weapons of the same type, wasting the loadout and will only be able to kill a single target. 

In the attached tacview file, a group of 4 Harriers are tasked with engaging a group of 8 T80Us (Target location Fennec). Each Harrier engages one single tank with all of its munitions (4 mavericks). The rest of the tanks are unengaged, meaning the attack is very uneffective.

2: (Coordinates, rather than units?) 
In the attached tacview file the same group of 8 T80Us are attacked by a total of 16 AGM65Fs launched from Harriers (Target location Fennec). The first maverick hit and kills its target. The other tanks are spooked and starts to move immediately for a couple of meters. The rest of the mavericks impact the ground where the rest of the targets initially stood. Are targets generated on the basis of coordinates, rather than actual units?

**To Reproduce**
Make the AI engage a location with multiple targets. Load the aircraft with several weapons of the same kind, ie. several AGM65Fs, or several GBU38 JDAM

**Expected behavior**
1: I would expect the AI to engage a single target with the necessary amount of munitions, or do several passes to kill the target, not use all its munitions in one run on the same, single unit.

2: I would expect Fire-and-forget weapons, or weapons that needs to be directed to the target (ie. weapons directed by laser-targeting) to hit its target. Instead the weapons seems to be locked at a location, rather than a individual unit.

**Version information (please complete the following information):**
 - DCS Liberation 4.1.1

[Files collection.zip](https://github.com/dcs-liberation/dcs_liberation/files/7034547/Files.collection.zip)

**Comment by RndName** [comment]
This issue (1) is now tracked in another issue #2152 
For issue 2: It is better to use BAI task for this. (https://github.com/dcs-liberation/dcs_liberation/wiki/Mission-planning) Strike mission uses the Bomb tasking which tells the AI to strike a specific location rather than units / groups. BAI on the other side uses the AttackGroup command which forces the AI to attack a specific group.
