### ISSUE TITLE
Invalid frequency - mission cannot be saved

### ISSUE THREAD

**Issue by Prof-hilactic** [dcs-liberation/dcs_liberation#158]
After generating and loading the mission in DCS editor, I cannot start the mission as the radio frequency is invalid (error message : unit/2/19/24/A-10C/:invalid frequency 117 MHz). I tried to change the frequency manually but it does not work.

I tried with different maps and the issue is the same. Did not had the issue with previous version only with the latest (2.1.1)

**Comment by DanAlbert** [comment]
https://github.com/Khopa/dcs_liberation/pull/151

**Comment by Khopa** [comment]
Hello,

This should be fixed in version 2.1.2.  (See https://github.com/Khopa/dcs_liberation/releases/tag/2.1.2)

Thanks,

Khopa
