### ISSUE TITLE
Add option to disable spawning of unused aircraft

### ISSUE THREAD

**Issue by ziher123** [dcs-liberation/dcs_liberation#1581]
Please add option to disable spawning of uncontrolled ambience aircraft. It can completely tank otherwise good performance around affected airfields. 
Right now in my campaign i have to manually delete over 100 of them one by one to have playable mission around this last enemy airfield.

![DCS](https://user-images.githubusercontent.com/89880695/131590635-035afad5-6c14-44ce-9d0c-d9e1f05d7575.jpg)

**Comment by DanAlbert** [comment]
100 unused aircraft is a bug. The AI isn't supposed to buy aircraft they don't use. You need to refile using the bug template so we have the information we need to diagnose this.
