### ISSUE TITLE
Excessive number of unused aircraft spawning

### ISSUE THREAD

**Issue by ziher123** [dcs-liberation/dcs_liberation#1582]
**Describe the bug**
Excessive number of unused aircraft are spawning in my campaign tanking performance around airfields.

**To Reproduce**

**Expected behavior**
I expected that only aircraft with assigned package would spawn in game.

**Additional information**
[CampaignFiles.zip](https://github.com/dcs-liberation/dcs_liberation/files/7087784/CampaignFiles.zip)

**Version information (please complete the following information):**
 - DCS Liberation 4.1.1.

**Additional context**
A large number of unused aircraft is spawning on last enemy airfield. I have to manually remove them one by one to make flying close to that airfield playable again.
![DCS](https://user-images.githubusercontent.com/89880695/131601972-f884cbbe-b451-4e5c-a66d-c86097c96fad.jpg)
If i skip few turns from here AI will buy even more aircraft and numbers will continue to stack up. There's around 100 of them here.
![DCS3](https://user-images.githubusercontent.com/89880695/131603425-1b526ebe-d032-4c5d-a947-0b8f1926560c.jpg)
I also noticed 2 A-10s without assigned package spawning at a friendly airbase so i'm unsure if that's a bug or a feature.
![DCS2](https://user-images.githubusercontent.com/89880695/131602555-59e471a2-579c-4ce7-81f0-d97aa03c6423.jpg)

**Comment by Starfire13** [comment]
This is not a bug. This is as intended. All aircraft, tasked or untasked, spawn in so that oca/aircraft flights have targets.

**Comment by DanAlbert** [comment]
Having this many untasked aircraft is almost certainly a bug. The AI only buys what it can use.

**Comment by ziher123** [comment]
Can option be added to only spawn tasked aircraft or prevent AI from accumulating large number of aircraft it doesn't use in the first place? It makes a huge difference in performance in this particular scenario.

After passing dozen of turns AI finally stopped buying more aircraft at a total of 175.
Mission then spawned all the unused aircraft resulting in this:
![DCS4](https://user-images.githubusercontent.com/89880695/131747817-edf4feb0-c544-4038-b369-ba91d2577c92.jpg)

**Comment by DanAlbert** [comment]
As I said, that's a bug. The option would do very little once the bug is fixed.

> prevent AI from accumulating large number of aircraft it doesn't use in the first place

This is the intended behavior. That's the bug. The AI isn't supposed to buy things it can't use.

**Comment by DanAlbert** [comment]
You left out the most important part: repro instructions. There's nothing I can do with the information given. I can't fix a problem if I can't observe it.

**Comment by DanAlbert** [comment]
I don't see this behavior in 4.x, but I do see it in 5.x. The two systems are entirely different so I can't explain the 4.x behavior, but I guess it doesn't matter since we're not doing more releases of 4.x. Will investigate what I have in 5.x.

**Comment by ziher123** [comment]
Sorry, didn't know what to write on repro. I just noticed big performance drop when enemy was pushed to the last base. Everything else worked great and as expected. This was on Nevada - Exercise Vegas Nerve campaign, if that helps.

**Comment by DanAlbert** [comment]
I fixed _something_ in 5 today but I'm not sure what, and I have no idea if it was related or not.
