### ISSUE TITLE
Multiple errors in QFlightCreator.py when attempting to alter Task and Aircraft type (#2838)

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#1587]
**Describe the bug**
When creating a package, attempting to change the task or aircraft type causes multiple error popups. If you click through all of them, you can still create the package (but you'll get error popup(s) again if you try to change either of those 2 settings). However, if you try to plan a package to an airfield (e.g. oca/runway), this will turn Liberation unresponsive since the error popup is in the back and doesn't have focus. So, you can't close it.

![Capture](https://user-images.githubusercontent.com/72491792/131756985-7f0a5e74-e4a1-4357-b599-896f23098c26.JPG)

**To Reproduce**
1. Attempt to create a package
2. Change either Task or Aircraft type

**Version information (please complete the following information):**
#2838

**Additional context**
Changing squadron, divert, size, assigned pilots, and start type does not generate errors.

**Comment by Starfire13** [comment]
Workaround for closing hidden error window is to hit alt+F4. That will close the hidden window.

**Comment by DanAlbert** [comment]
Oops. I tested a bunch of the other things but I guess I missed those two. Fixed.
