### ISSUE TITLE
Possible Bug: Germany 1990's tornados do not get spawned in generated mission

### ISSUE THREAD

**Issue by fedepiz** [dcs-liberation/dcs_liberation#159]
I am playing a campaign as Bluefor Modern vs Germany 1990 in Caucasus.
In DCS liberation, I can see the German side has Tornado IDS, set on CAS  (I get the info by clicking on enemy airfields).

However, in the generated missions, there do not seem to be any Tornado IDS automatically spawned.
[autosave.zip](https://github.com/Khopa/dcs_liberation/files/5288810/autosave.zip)

**Comment by Khopa** [comment]
Hello fedepiz, 

Thanks,

This should now be fixed in 2.1.2. [https://github.com/Khopa/dcs_liberation/releases/tag/2.1.2]

Could you confirm ?

**Comment by fedepiz** [comment]
I can confirm Tornados are spawned in a new campaign using version 2.1.2
