### ISSUE TITLE
Unit purchase buttons not visible when squadron names are too long.

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#1592]
**Describe the bug**
When the squadron name is too long (like in the tanker squadron example below), it cuts off the buttons to the right, making it impossible to purchase aircraft.

![Capture](https://user-images.githubusercontent.com/72491792/131943270-3d68b241-9097-4d43-95fd-d45e4b6489f8.JPG)

**Version information (please complete the following information):**
#2843

**Comment by Furia139** [comment]
I have experienced the same but I found a temporary solution by clicking on the area of the squadron name and using the right arrow in the keyboard the view moves right allowing you to purchase the units. However this should not be a permanent solution if this is possible to fix

**Comment by Starfire13** [comment]
For now, I'm getting around the issue by simply removing the word "expeditionary" from the refueling squadron's name. It appears that is the only squadron with a name long enough to cause the problem.
