### ISSUE TITLE
AEW&C package defaulting to 0 aircraft instead of 1 when manually planned

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#1593]
**Describe the bug**
When a player manually plans an AEW&C package, aircraft in the flight defaults to 0.

**Expected behavior**
Should select 1 aircraft by default.

**Version information (please complete the following information):**
#2843

**Comment by Starfire13** [comment]
Tankers may possibly have the same problem, because both are aircraft that fly singly.

Edit: Tested tankers and can confirm they exhibit the same problem.

**Comment by Furia139** [comment]
I can confirm this issue as well in version 2850
