### ISSUE TITLE
Players' flight intra flight frequencies (on COMM1 channel1) are not correct

### ISSUE THREAD

**Issue by pcoud** [dcs-liberation/dcs_liberation#1596]
**Describe the bug**

Most players' intra flight frequencies, on COMM1 channel1, are not correct: they don't match the frequencies that can be seen in liberation_nextturn.miz under the mission editor.

Please note that the kneeboards show the correct intra flight frequencies, so another way to reformulate the bug is: most players' COMM1 channel1 frequencies are not correct: they don't match the frequencies found in the kneeboards.

(Please also note that all COMM2 frequencies, ie COMM2 channel 1/2/3/4 are all correct, as per the mission editor and the kneeboards)

Example: I am starting this campaign:

![Capture d’écran (12)](https://user-images.githubusercontent.com/90111363/132106057-c548161c-61d0-467a-9a85-477a0a87cba7.png)

There are 4 players flights:
- SEAD RAVEN
- strike MONKEY
- strike WOMBAT
- BARCAP Truman

I press the START button and then load the generated liberation_nextturn.miz in the mission editor. In the mission editor I check the various intra flight frequencies. It says:

- SEAD RAVEN: 118 Mhz
- strike MONKEY: 123 Mhz
- strike WOMBAT: 119 Mhz
- BARCAP Truman: 120 Mhz

I close the mission editor, launch a hosted server in the DCS multiplayer panel, load liberation_nextturn.miz, choose one of the players' slots and press FLY. Once in the plane (they are all F18s), I start the right engine so that I can check the COMM1 channel1 frequency. I do this for all 4 players flights, here are the results:

- SEAD RAVEN: 123 Mhz
- strike MONKEY: 123 Mhz
- strike WOMBAT: 123 Mhz
- BARCAP Truman: 123 Mhz

**Additional information**

I have the liberation save, and the liberation_nextturn.miz available, but this is my first time posting here and I have not been able to figure out how to join files (?)

**Version information (please complete the following information):**
 - DCS Liberation 4.1.1

[Golan bot1.zip](https://github.com/dcs-liberation/dcs_liberation/files/7111056/Golan.bot1.zip)
[liberation_nextturn.zip](https://github.com/dcs-liberation/dcs_liberation/files/7111057/liberation_nextturn.zip)

**Comment by DanAlbert** [comment]
Attach the save game please. You can rename it .txt to get last github's filter, or put in on a zip file.

**Comment by pcoud** [comment]
Hi DanHere are liberation save game and the generated miz.Was it possible to attach those files directly within the report in GitHub ? I couldn't figure out how ?envoyé : 4 septembre 2021 à 22:50de : Dan Albert ***@***.***>à : dcs-liberation/dcs_liberation ***@***.***>cc : pcoud ***@***.***>, Author ***@***.***>objet : Re: [dcs-liberation/dcs_liberation] Players' flight intra flight frequencies (on COMM1 channel1) are not correct (#1596) Attach the save game please.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Starfire13** [comment]
@pcoud, you can zip the files up and drag and drop em into the comment window to attach them.

**Comment by pcoud** [comment]
I edited the initial comment and dropped the zip files, looks like it worked

**Comment by pcoud** [comment]
Hi guys,

I have done some additionnal testing.

1. I have loaded the liberation_nextturn.miz that had previously been generated by Liberation (the one I attached here above) into the mission editor (I have NOT launched Liberation itself). I have checked again the radio frequencies of each clients' flights. I then clicked on FLY from within the ME, and chose the SEAD client flight. Once in the plane its COMM1 chnl1 frequency was 123Mhz while it should have been 118Mz. Same error as what I described in my initial report. I just can't understand this, there is a discrepancy between what is in the ME and in the actual plane. As I have understood that liberation does nothing else than generating a miz file, after that it's all DCS related, I seriously wonder if "the bug" I reported is really liberation related. And even if it's a bug (see below)
2. I found a workaround: If I uncheck the "RADIO" box in the ME for each of the clients' flights, it all works like a charm whether I launch the mission from within the ME or from a hosted multiplayer server.

<img width="1920" alt="Screen_210905_120017" src="https://user-images.githubusercontent.com/90111363/132123432-488957be-36f1-4a5b-ac58-c8f0ac0989bb.png">

3. Bottom line: I don't know what to think. I don't even understand what this "RADIO" box is meant for in the ME (I checked in the documentation, but did not understand) and why it should be checked or unchecked. I suspect the explanation may actually lie there.

So, not sure at all if this is directly liberation related. Not sure also if liberation, when creating the miz file, could uncheck the RADIO boxes ? This would apparently solve my little problem even though I cannot really explain why (which I don't like)

**Comment by pcoud** [comment]
I have further investigated with ED, please see the following thread:
https://forums.eagle.ru/topic/281620-comm1-channel1-radio-frequency-at-mission-start-does-not-match-what-was-set-in-the-me/?tab=comments#comment-4771950
The generated miz has inconsistencies regarding comm1 channel1 frequencies vs what is set in the ME. Seems to be liberation related.

**Comment by DanAlbert** [comment]
I don't think we had any doubts this was our bug, we just don't have any releases coming up soon. We'll have a look when it's time for a release, but we have our minds on other things right now.

**Comment by pcoud** [comment]
No problem Dan, that was not to put pressure, just to provide you with all the information I had gathered :-)
Many thanks for what you're doing

**Comment by DanAlbert** [comment]
Setting the plane to hot start also fixes it.

Grimes is right (as always): there's a discrepancy in the default channel (mainly used for AI flights) and the preset channel list, so we're generating the mission wrong, and for whatever reason changing from cold to hot start also fixes it (maybe tweaking the group options is causing the ME to fix up the inconsistencies?)

But yeah, our bug for generating the wrong radio data in the first place. Not sure if that's a problem for all radio presets or just channel 1.

**Comment by DanAlbert** [comment]
Was actually a pydcs bug: https://github.com/pydcs/dcs/pull/187. Only symptomatic in Liberation when there was more than one flight of players using the same aircraft.

**Comment by DanAlbert** [comment]
pydcs change is merged, so we just need to take the update. We'll need an update for the upcoming DCS update anyway, but leaving this open until that happens.
