### ISSUE TITLE
JAS-39 it's generated with empty payload 

### ISSUE THREAD

**Issue by ObsceneNickname** [dcs-liberation/dcs_liberation#1598]
* Mod name: Community-JAS-39-C
* Mod URL: https://github.com/whisky-actual/Community-JAS-39-C/
It seems that JAS-39 it's generated without payload at least with the new version of the mod: v1.6.0-Beta

I take the opportunity to express my deep recognition and appreciation for the work on Liberation. Thanks to all of the staff.

**Comment by DanAlbert** [comment]
This isn't a request for a new mod or a mod update. Use the big report template. We can't do anything with the info given.
