### ISSUE TITLE
Wizard ignores if "use Super-Carrier Module" is ticked or not

### ISSUE THREAD

**Issue by Surfingnet** [dcs-liberation/dcs_liberation#1599]
Before filing, please search the issue tracker to see if the issue has already been reported.
_Probably related to, but works the opposite way: [ Super Carrier Selected Still Places Stennis #1214 ](https://github.com/dcs-liberation/dcs_liberation/issues/1214)_

If reporting a DCS AI bug, check https://github.com/dcs-liberation/dcs_liberation#dcs-bugs.
_Not a DCS AI bug._

**Describe the bug**
_If there are both super-carrier and non-super-carrier carriers in the faction's file unit list, there is chances that, when I do not tick the "use super-carrier module" box in the wizard, the carrier will still be from the super-carrier module when starting the campaign. Tried on several campaign on caucasus and syria and it's always the same thing, I have to restart the wizard over and over until it's a Stennis that pops up eventually._

**To Reproduce**
1. _New Campaign (any)_
2. _In the Wizard do **NOT** tick "Use Super-Carrier Module"._
3. _Select a faction with **BOTH** Super-Carrier carriers and the vanilla CVN 74 John C. Stennis._
4. _When ready to go, finish and close the Wizard._
5. _Check which carrier has spawned._

**Expected behavior**
_A CVN 74 John C. Stennis has spawned._

**Additional information**
_Sometimes it's not a CVN 74 John C. Stennis that spawns but a carrier from the Super-Carrier Module._

We will usually need more information for debugging. Include as much of the following as you are able:

- DCS Liberation save file (the `.liberation` file you save from the DCS Liberation window). By default these are located in your DCS saved games directory (`%USERPROFILE%/Saved Games/DCS`).
_[CVN_bug.zip](https://github.com/dcs-liberation/dcs_liberation/files/7116130/CVN_bug.zip)_
- The generated mission file (the `.miz` file that you load in DCS to play the turn). By default these are located in your missions directory (`%USERPROFILE%/Saved Games/DCS/Missions`).
_[liberation_nextturn.zip](https://github.com/dcs-liberation/dcs_liberation/files/7116151/liberation_nextturn.zip)_
- A tacview track file, especially when demonstrating an issue with AI behavior. By default these are located in your Tacview tracks directory (`%USERPROFILE%/Documents/Tacview`).
_I didn't fly the mission._
- The state.json file from the finished mission when the problem is related to results processing. By default these are located in your Liberation install directory.
_I didn't fly the mission._

**Version information (please complete the following information):**
 - _DCS Liberation 4.1.1_

**Additional context**
_[Pictures](https://imgur.com/a/RIC8n2U)_

**Comment by Starfire13** [comment]
Not a bug. Merely a case of mistaken identity due to not realising the Stennis carrier can have diferent names.

**Comment by DanAlbert** [comment]
Yeah, you can toggle super carrier on and off whenever but the name needs to be stable, so the name is irrelevant.

**Comment by Surfingnet** [comment]
> 
> 
> Yeah, you can toggle super carrier on and off whenever but the name needs to be stable, so the name is irrelevant.

Yeah it's a non-sense, a BIG "74" on the carrier but named 73 or 71 or whatever...

**Comment by DanAlbert** [comment]
If you have an idea of how to fix the problem without limiting player choice we're all ears.
