### ISSUE TITLE
[Build 2849] Squadron Mission Preference Bug

### ISSUE THREAD

**Issue by Mustang-25** [dcs-liberation/dcs_liberation#1608]
When creating the squadron list in a campaign YAML, there are certain taskings or groups of taskings that are not compatible in either the primary task list or secondary task list.

As discussed on Discord, It seems like A2A, A2G, and Any are the only ones that work for secondary tasks and you can't use specific task names. Conversely, primary tasks have to use specific task names and can't be A2A or A2G. Attempting to add a specific task name will generate an error pictured below:

![image](https://user-images.githubusercontent.com/72566076/132732210-cf4aa00e-9913-4b73-985d-94cfbc14ced9.png)

**Version information (please complete the following information):**
 - Build 2849

**Comment by DanAlbert** [comment]
Ah, this is actually the expected behavior. If you want to name specific mission types you need to make the entry a list. e.g.

```
secondary: air-to-ground
```

vs

```
secondary:
  - BAI
```

The docs say this, but only if you're reading the very fine print "This can be either the literal strings any, air-to-air, or air-to-ground, or a **list** of specific task types." (emphasis mine)

**Comment by Starfire13** [comment]
Ah. So in the case of, for example, the Mi-8 that I want to be used primarily for BAI, with secondary tasks as CAS or transport, I could set it as:

- primary: BAI
      secondary: 
        - CAS
        - Transport       
      aircraft:
        - Mi-8MTV2 Hip

Does this work for primary roles too?

**Comment by DanAlbert** [comment]
Correct.

There can only be one primary role. Primary is "if we can't fulfill any other constraints at least make sure it can do this". Any squadron is better than no squadron, so it's as loosely constrained as possible to maximize the chances of the fallback working.
