### ISSUE TITLE
[Linux] Kneeboard generation fails due to fonts not being found

### ISSUE THREAD

**Issue by SirRolls** [dcs-liberation/dcs_liberation#1613]
By default core.getfont (used in PIL) only searches windows font directories. These obviously are not there in linux. To fix, install corefonts or any truetype font that you like then edit kneeboard.py lines 76,79, and 82, replacing "arial.ttf" with a full path (/usr/share/fonts/someFont/SomeFontFace.ttf) missions will generate just fine. Editing these lines on windows also allows for changing fonts on the generated Kneeboard. 

Below is a quick preview of the Kneeboard being generated with liberation fonts on gentoo Linux. 

Maybe a option in campaign settings to change the font directly would add some customization to Kneeboards and allow for quick fixes to font issues when running under Linux

![kneetest](https://user-images.githubusercontent.com/30061518/132999913-19354692-2985-43b7-88dc-cd470f6f8182.png)

**Comment by DanAlbert** [comment]
We're not going to get into re-implementing font finding for each OS. If PIL can't find fonts on Linux someone should teach PIL to do that.
