### ISSUE TITLE
Custom Radio Frequencies

### ISSUE THREAD

**Issue by DevastatorCM** [dcs-liberation/dcs_liberation#1614]
**Is your feature request related to a problem? Please describe.**
Kind of related to a problem of VAICOM. It has by some players issue that only one comm channel is working

**Describe the solution you'd like**
Able to set custom frequencies for each planned flight. i.e. Tanker uses 200.00, awacs uses 180.00 etc. It is doable over mission editor but better to bring this setup also into the Liberation UI

**Additional context**
N/A

**Comment by Starfire13** [comment]
This is a repeat of (or at least closely related to) https://github.com/dcs-liberation/dcs_liberation/issues/835

**Comment by DevastatorCM** [comment]
yes you are right. Sorry for the dupp
