### ISSUE TITLE
None-FARP-usable aircraft being purchased/tasked at FOB after squadron falllback post-capture

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#1615]
**Describe the bug**
After an airbase capture, squadrons for aircraft that are not FARP-capable (e.g. Su-25) are falling back to the next FOB control point instead of to the nearest air base. At the FOB, the squadrons can purchase aircraft that cannot be placed on FARPs, leading to them spawning in mid air.

**Expected behavior**
Squadrons from airfields (with the possible exception of chopper/harrier squadrons) should fall back to the nearest airfield when their airfield is captured instead of to a FOB.

**Version information (please complete the following information):**
 - DCS Liberation #2870

**Comment by DanAlbert** [comment]
Do you have a save game? I have a probable fix but no simple way to test.

**Comment by Starfire13** [comment]
I created a save file for you to test this, using Operation Vectron's Claw.

[Squadron Fallback Behaviour Test #2906.zip](https://github.com/dcs-liberation/dcs_liberation/files/7358900/Squadron.Fallback.Behaviour.Test.2906.zip)

Capture the next airfield (Sochi-Adler). The next control point after that is a FOB, Dzhugba, which has a helicopter squadron (though the AI hasn't bought any yet due to distance from frontline). In my previous tests, squadrons at Sochi-Adler would end up at Dzhugba instead of falling back to Anapa-Vityazevo.

**Comment by DanAlbert** [comment]
Thanks, will check my fix later.

**Comment by DanAlbert** [comment]
Can't repro. With your save I tried:

1. Capturing
2. Skipping then capturing
3. Capturing then skipping

In all three cases FOB Dzhugba did not receive any aircraft. Stepping through with the debugger makes this look impossible.

**Comment by DanAlbert** [comment]
(assuming not-reproducible rather than just missing instructions, will reopen if someone can figure out _how_ this happens)

**Comment by Starfire13** [comment]
This is the result I got previously after capturing Sochi Adler. If you pass turn, you'll see the AI buy 8 SU-25s at Dzhugba. The Su-25 squadron was previously at Sochi Adler. There doesn't appear to be any way to view OPFOR squadron locations so I don't know if all the Sochi Adler squadrons ended up at Dzhugba or just the Su-25 squadron.

[Vectron's Claw FARP Test After Fix.zip](https://github.com/dcs-liberation/dcs_liberation/files/7360923/Vectron.s.Claw.FARP.Test.After.Fix.zip)

**Comment by Starfire13** [comment]
I'm gonna start a new campaign in the next couple of days to test this out once more.

**Comment by DanAlbert** [comment]
Yeah, that save unfortunately only shows that something _has_ gone wrong. Since the thing has already gone wrong it doesn't tell me anything :\

**Comment by Starfire13** [comment]
What I think I'll do is try to save each turn as a separate file in my new campaign, and hopefully that can help make things clearer. Having some way to determine enemy squadron locations would be handy though. Is there any way to tell from the log file? Do squadron relocations show up there?

**Comment by DanAlbert** [comment]
> What I think I'll do is try to save each turn as a separate file in my new campaign, and hopefully that can help make things clearer.

As long as I have the save from the turn before that capture and the state.json, that's plenty.

> Do squadron relocations show up there?

Yeah.

**Comment by Starfire13** [comment]
Ok, here's a bunch of files showing the squadron fallback problem.

[Squadron Fallback Behaviour Test.zip](https://github.com/dcs-liberation/dcs_liberation/files/7401803/Squadron.Fallback.Behaviour.Test.zip)

**Squadron Fallback Behaviour Test #2942 - Turn 5.liberation**
This file was saved just before a turn where Sochi-Adler was captured. Sochi-Adler has a bunch of different squadrons, and two Mig29s. The next OPFOR control point is Dzhugba, which is a FOB/FARP with a Mi-24 Hind squadron (with no Hinds purchased).

**state.json**
This is the state.json file from the end of Turn 5.

**liberation_nextturn.miz**
The .miz file generated for Turn 5.

**Squadron Fallback Behaviour Test #2942 - Turn 6.liberation**
This is the .liberation file for Turn 6. You'll see that I've now captured Sochi-Adler, and Dzhugba now has two Mig-29s that were at Sochi-Adler. So at the very least, this is proof that the aircraft are being retreated to the FOB. How about the squadrons then? Let's look at the next file.

**Squadron Fallback Behaviour Test #2942 - Turn 7.liberation**
This is the Liberation save after I hit Pass Turn, and you can see that the autoplanner has purchased 4 Su-25s. The Su-25 squdron was previously at Sochi-Adler, which suggests that it has indeed been moved over to Dzhugba.
