### ISSUE TITLE
Can not adjust size of window

### ISSUE THREAD

**Issue by HoovieDoovie** [dcs-liberation/dcs_liberation#1618]
**Describe the bug**
I can't resize the window by grabbing the corner and adjusting, it will either disappear or not work at all. The windowed screen is too large and i have to drag across my screen to be able to see the begin campaign/skip turn/take off button. also when I full screen it, the UI doesn't fit to the fullscreen, it is too small, but the click boxes are where the UI would be on the screen if it did fit.

**To Reproduce**
1. Have a 16:10 screen (2560x1600)
2. launch liberation_main.exe
3. window is way too big
4. click full screen
5. UI image is too small, but buttons to click are where they should be if it did fit to screen

**Expected behavior**
UI fits to my screen or can be adjusted to do so

**Version information (please complete the following information):**
 - DCS Liberation [e.g. 5.0.0-2875]:
 - happens on any version i've had

**Comment by DanAlbert** [comment]
This has been tweaked in the past, so probably not still present.
