### ISSUE TITLE
end of campaign blocked

### ISSUE THREAD

**Issue by Kervinou** [dcs-liberation/dcs_liberation#1620]
**Describe the bug**
after clic on "accept results" button, nothing happens
it's the last mission of the campaign, we have taken the last control point

**To Reproduce**
load 3rd_Insurgents_Syria_16-3.liberation
take-off
manual submit of results
the result screen appears
clic on "accept results" button, nothing happens
several lines appears on console window with error : error_log.jpg

**Additional information**
[](https://kerv.fr/.images_forums/.v30/2109161007236142fb3b6aef8bug_report_kervinou.7z)
[bug_report_kervinou.zip](https://github.com/dcs-liberation/dcs_liberation/files/7176025/bug_report_kervinou.zip)

DCS Liberation save file => 3rd_Insurgents_Syria_16-3.liberation
The generated mission file => liberation_nextturn.miz
The state.json file from the finished mission =>state.json
screenshot of console error that you can reproduce => error_log.jpg

**Version information (please complete the following information):**
 - DCS Liberation 4.1.1

**Additional context**
n/a

**Comment by ColKernel0x8E** [comment]
I experienced this bug as well after capturing the last control point in the Golan Heights campaign in Liberation 5.0 (5.0.0_2929).

Same steps to reproduce as outlined by Kervinou above, but using the files in the attached .zip. Judging from the log it seems to be related to the update of ground losses from the last enemy control point:

2021-10-21 21:51:32,990 :: ERROR :: Found killed BMP-1 from Damascus but that airbase has none available.
2021-10-21 21:51:32,990 :: ERROR :: Uncaught exception
Traceback (most recent call last):
  File "windows\QWaitingForMissionResultWindow.py", line 217, in process_debriefing
  File "game\game.py", line 233, in finish_event
  File "game\event\event.py", line 215, in commit
  File "game\event\event.py", line 169, in commit_ground_object_losses
ValueError: list.remove(x): x not in list


[bug_report_colkernel_campaign_end.zip](https://github.com/dcs-liberation/dcs_liberation/files/7392545/bug_report_colkernel_campaign_end.zip)

**Comment by Starfire13** [comment]
For the moment, there isn't really a proper end of campaign. You get a small message in the text box under the map in Liberation that you won, and the game pretty much just generates errors as it tries to plan the next turn (but can't). As for the "Found killed BMP-1 from Damascus but that airbase has none available" error, that most likely occurs due to clicking the accept results button more than once. If it doesn't work the first time, clicking again isn't going to make it work, you just get different errors.

**Comment by Kervinou** [comment]
OK thanks a lot for your time :-)
