### ISSUE TITLE
error when attempting to edit flight of JF-17ss

### ISSUE THREAD

**Issue by Moguy164** [dcs-liberation/dcs_liberation#1623]
Before filing, please search the issue tracker to see if the issue has already been reported.

If reporting a DCS AI bug, check https://github.com/dcs-liberation/dcs_liberation#dcs-bugs.

**Describe the bug**
when trying to edit a flight of JF-17s I get an error window with the contents 'DIS_GBU_12_DUAL'

`'DIS_GBU_12_DUAL'

Traceback (most recent call last):
  File "widgets\ato.py", line 119, in on_double_click
  File "widgets\ato.py", line 124, in edit_flight
  File "dialogs.py", line 57, in open_edit_flight_dialog
  File "windows\mission\QEditFlightDialog.py", line 33, in __init__
  File "windows\mission\flight\QFlightPlanner.py", line 20, in __init__
  File "windows\mission\flight\payload\QFlightPayloadTab.py", line 39, in __init__
  File "windows\mission\flight\payload\QFlightPayloadTab.py", line 13, in __init__
  File "gen\flights\loadouts.py", line 120, in iter_for
  File "gen\flights\loadouts.py", line 120, in <dictcomp>
  File "game\data\weapons.py", line 73, in with_clsid
KeyError: 'DIS_GBU_12_DUAL'`
**To Reproduce**
1. make a flight of JF-17s (any tasking)
2. double click on the flight to edit
3. See error

**Expected behavior**
allows you to edit the flight like other aircraft
**Additional information**

We will usually need more information for debugging. Include as much of the following as you are able:

- DCS Liberation save file (the `.liberation` file you save from the DCS Liberation window). By default these are located in your DCS saved games directory (`%USERPROFILE%/Saved Games/DCS`).
- The generated mission file (the `.miz` file that you load in DCS to play the turn). By default these are located in your missions directory (`%USERPROFILE%/Saved Games/DCS/Missions`).
- A tacview track file, especially when demonstrating an issue with AI behavior. By default these are located in your Tacview tracks directory (`%USERPROFILE%/Documents/Tacview`).
- The state.json file from the finished mission when the problem is related to results processing. By default these are located in your Liberation install directory.

**Version information (please complete the following information):**
 - DCS Liberation : V5.0.0 -2880

**Additional context**

**Comment by Mustang-25** [comment]
Looking GBU-12-2X.yaml, it looks like the clsid is correct. Is missing the brackets what's throwing up the error?

![image](https://user-images.githubusercontent.com/72566076/133910746-de7b30c7-d9c9-4525-92fe-424ddbf3cd71.png)

**Comment by Moguy164** [comment]
> Looking GBU-12-2X.yaml, it looks like the clsid is correct. Is missing the brackets what's throwing up the error?
> 
> ![image](https://user-images.githubusercontent.com/72566076/133910746-de7b30c7-d9c9-4525-92fe-424ddbf3cd71.png)

are you using the new pylons that got added to the Jeff?  clsid": "DIS_GBU_12_DUAL_GDJ_II19_L

**Comment by DanAlbert** [comment]
Doesn't repro. Assuming fixed by a pydcs update.
