### ISSUE TITLE
F-86 Unable to be controlled in DCS 2.7.6.12852

### ISSUE THREAD

**Issue by 2alpha-down0** [dcs-liberation/dcs_liberation#1624]
Before filing, please search the issue tracker to see if the issue has already been reported.

If reporting a DCS AI bug, check https://github.com/dcs-liberation/dcs_liberation#dcs-bugs.

**Describe the bug**
F-86 player slots are unplayable in Liberation 4.1.1 missions in DCS 2.7.6.12852.  From a cold start aircraft, the view slews uncontrollably in-cockpit and the aircraft itself rubber-bands all over the place.  Initial testing showed the P-51 working fine, but now the P-51 is affected as well.

**To Reproduce**
1. Create a multiplayer Liberation mission with F-86 client slots using DCS 2.7.6.
2. Select an F-86 client slot and spawn in.
3. Issue manifests immediately.

**Expected behavior**
Player should spawn into the aircraft with full control as normal.

**Additional information**

We will usually need more information for debugging. Include as much of the following as you are able:

- DCS Liberation save file (the `.liberation` file you save from the DCS Liberation window). By default these are located in your DCS saved games directory (`%USERPROFILE%/Saved Games/DCS`).
- The generated mission file (the `.miz` file that you load in DCS to play the turn). By default these are located in your missions directory (`%USERPROFILE%/Saved Games/DCS/Missions`).
- A tacview track file, especially when demonstrating an issue with AI behavior. By default these are located in your Tacview tracks directory (`%USERPROFILE%/Documents/Tacview`).
- The state.json file from the finished mission when the problem is related to results processing. By default these are located in your Liberation install directory.

**Version information (please complete the following information):**
 - DCS Liberation [e.g. 2.3.1]: 4.1.1

**Additional context**
Add any other context about the problem here

[Korea DC 2.zip](https://github.com/dcs-liberation/dcs_liberation/files/7
[liberation_nextturn.zip](https://github.com/dcs-liberation/dcs_liberation/
[server-20210918-181028.zip](https://github.com/dcs-liberation/dcs_liberation/files/7190717/server-20210918-181028.zip)
files/7190714/liberation_nextturn.zip)
190713/Korea.DC.2.zip)

**Comment by Mustang-25** [comment]
Hi, I reviewed your save and you have start times for both aircraft at 18 minutes and 15 minutes. Without checking the Player Ignores ToT option, you will not be able to spawn into the aircraft until those times. So this isn't a bug, it is functioning as intended.

**Comment by 2alpha-down0** [comment]
Just checked this and confirmed it was my error and not a bug.  Thanks!
