### ISSUE TITLE
Su-27 causing issues when beginning a campaign.  5.0.0-2890 preview

### ISSUE THREAD

**Issue by sncollie** [dcs-liberation/dcs_liberation#1630]
Started a Black Sea Campaign...inverted map, playing as Russia 1990 against USA 1990.  Set everything to Auto "purchases/front-line, etc".  Set up a player in a Su-27 Squadron at Sochi.  Changed the roles to include intercept, CAS, and BAI.  

When the map appeared I went into the Air Wing page, and make sure all the Mission types were checked (only BARCAP was, I believe this is a known bug).    I then adjusted a few parameters in the setting like Spawn immediately for Player aircraft...adjust some AI levels.

When I click "Begin Campaign"  I get this "An unexpected error occurred" warning:

AircraftType(dcs_unit_type=<class 'dcs.planes.Su_27'>, name='Su-27 Flanker-B', description='The Su-27, NATO codename Flanker, is one of the pillars of modern-day Russian combat aviation. Built to counter the American F-15 Eagle, the Flanker is a twin-engine, supersonic, highly manoeuvrable air superiority fighter. The Flanker is equally capable of engaging targets well beyond visual range as it is in a dogfight given its amazing slow speed and high angle attack manoeuvrability. Using its radar and stealthy infrared search and track system, the Flanker can employ a wide array of radar and infrared guided missiles. The Flanker also includes a helmet-mounted sight that allows you to simply look at a target to lock it up! In addition to its powerful air-to-air capabilities, the Flanker can also be armed with bombs and unguided rockets to fulfil a secondary ground attack role.', year_introduced=1985, country_of_origin='USSR/Russia', manufacturer='Sukhoi', role='Air-Superiority Fighter', price=18, carrier_capable=False, lha_capable=False, always_keeps_gun=False, gunfighter=False, max_group_size=4, patrol_altitude=None, patrol_speed=None, max_mission_range=Distance(distance_in_meters=555600), fuel_consumption=None, intra_flight_radio=None, channel_allocator=None, channel_namer=<class 'game.radio.channels.ChannelNamer'>) is not in list

Traceback (most recent call last):
  File "widgets\QTopPanel.py", line 148, in passTurn
  File "game\game.py", line 323, in pass_turn
  File "game\game.py", line 402, in initialize_turn
  File "game\coalition.py", line 182, in initialize_turn
  File "game\coalition.py", line 203, in plan_missions
  File "game\commander\theatercommander.py", line 82, in plan_missions
  File "game\htn.py", line 82, in plan
  File "game\commander\tasks\primitive\cas.py", line 16, in preconditions_met
  File "game\commander\tasks\packageplanningtask.py", line 51, in preconditions_met
  File "game\commander\tasks\packageplanningtask.py", line 102, in fulfill_mission
  File "game\commander\packagefulfiller.py", line 158, in plan_mission
  File "game\commander\packagefulfiller.py", line 77, in plan_flight
  File "game\commander\packagebuilder.py", line 46, in plan_flight
  File "game\squadrons\airwing.py", line 60, in best_squadron_for
  File "game\squadrons\airwing.py", line 50, in best_squadrons_for
  File "game\squadrons\airwing.py", line 52, in <lambda>
ValueError: AircraftType(dcs_unit_type=<class 'dcs.planes.Su_27'>, name='Su-27 Flanker-B', description='The Su-27, NATO codename Flanker, is one of the pillars of modern-day Russian combat aviation. Built to counter the American F-15 Eagle, the Flanker is a twin-engine, supersonic, highly manoeuvrable air superiority fighter. The Flanker is equally capable of engaging targets well beyond visual range as it is in a dogfight given its amazing slow speed and high angle attack manoeuvrability. Using its radar and stealthy infrared search and track system, the Flanker can employ a wide array of radar and infrared guided missiles. The Flanker also includes a helmet-mounted sight that allows you to simply look at a target to lock it up! In addition to its powerful air-to-air capabilities, the Flanker can also be armed with bombs and unguided rockets to fulfil a secondary ground attack role.', year_introduced=1985, country_of_origin='USSR/Russia', manufacturer='Sukhoi', role='Air-Superiority Fighter', price=18, carrier_capable=False, lha_capable=False, always_keeps_gun=False, gunfighter=False, max_group_size=4, patrol_altitude=None, patrol_speed=None, max_mission_range=Distance(distance_in_meters=555600), fuel_consumption=None, intra_flight_radio=None, channel_allocator=None, channel_namer=<class 'game.radio.channels.ChannelNamer'>) is not in list

[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/7207865/liberation.log)

**Comment by Starfire13** [comment]
Please use the proper bug report template, and attach your .liberation file. Thanks!

**Comment by sncollie** [comment]
New ticket created per instructions.  Closing.
