### ISSUE TITLE
Unable to sell units

### ISSUE THREAD

**Issue by DougStep** [dcs-liberation/dcs_liberation#1633]
**Describe the bug**
Able to sell units and gain cash but unit count will not go down - Can sell up to owned number and gain cash from it, number will not lower

**To Reproduce**
1. Go to mozdok
2. Click on sell button for any unit that you own
3. See error

**Expected behavior**
Unit should sell, money should go up and unit count should be lowered by 1

**Additional information**
https://youtu.be/VUD6O6OJ7QE

**Version information (please complete the following information):**
 - DCS Liberation 4.1.1

**Additional context**
[Lib Troubleshoot.zip](https://github.com/dcs-liberation/dcs_liberation/files/7237077/Lib.Troubleshoot.zip)

**Comment by Starfire13** [comment]
Appears to be same issue as https://github.com/dcs-liberation/dcs_liberation/issues/1535

**Comment by DougStep** [comment]
> Appears to be same issue as #1535

If so then they left quite a bit out
https://youtu.be/8MYlcgYL7Hw
Sold units can be sold multiple times and will still exist for the AI to plan around, it's not just the UI
The total aircraft also does not lower meaning you cannot buy more

**Comment by Starfire13** [comment]
Be that as it may, all those issues have already been ironed out.
