### ISSUE TITLE
Su-27 causing issues when beginning a campaign.

### ISSUE THREAD

**Issue by sncollie** [dcs-liberation/dcs_liberation#1636]
**Describe the bug**
When I click "Begin Campaign" I get an "unexpected error occurred" warning (see below)

**To Reproduce**
Start a Black Sea Campaign, invert map, Player side Russia 1990, Enemy side USA 1990.
Choose automate aircraft purchases, and assign a player to a Su-27 squad based at Sochi.
under "Air-Wing" choose all roles except BARCAP for the player squadron
Purchase Su-27 at Sochi.
Choose "Prefer Player Pilots" under automation.
Click Begin Mission.  If no player missions are created, click pass turn.  the below error pops up:
![image](https://user-images.githubusercontent.com/9039236/135350384-4895f18e-90fa-42fc-a421-0b243f4fd202.png)

**Expected behavior**
Campaign should progress normally. 

**Version information (please complete the following information):**

5.0.0-2890 [preview]

.liberation file attached.
[red90.zip](https://github.com/dcs-liberation/dcs_liberation/files/7255135/red90.zip)

**Comment by Starfire13** [comment]
I am on #2890 as well and am unable to reproduce this error. It does not occur on my end even when I follow the steps above exactly.

Edit: I would suggest you re-install Liberation. It's possible you might have accidentally messed up a file while editing stuff. TO me, it looks like somehow the entire text string for SU-27 including the description and other stuff, is all getting lumped in together with the name, so it is likely a syntax error.
