### ISSUE TITLE
SA-5 Support

### ISSUE THREAD

**Issue by Khopa** [dcs-liberation/dcs_liberation#1637]
- [x] Pydcs Support
- [x] Implement SA-5 Site Generator
- [x] Add SA-5 to various factions

**Comment by Furia139** [comment]
SA-5 is an awesome addition to DCS, It is powerful and has an incredible range while but can be defeated with a HARM if you mange to get in range alive.
I would love to have it in Liberation. Pls Pls

**Comment by DanAlbert** [comment]
@Khopa all the boxes are checked. Can this be closed, or is there other work to do?

**Comment by Khopa** [comment]
Yeah, sorry, all is done.
I'm closing this one.
