### ISSUE TITLE
Liberation won't start

### ISSUE THREAD

**Issue by KillerHorsefly** [dcs-liberation/dcs_liberation#1639]
I've used it many times previously, I updated DCS, now when I try to start liberation, the DOS window pops up for a few seconds, disappears, and Liberation does not start.

**Comment by Starfire13** [comment]
Please use the template. We can't help if you don't attach your Liberation log file or even tell us what version of Liberation you are on.

**Comment by KillerHorsefly** [comment]
[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/7289485/liberation.log) Version 4.1.1

**Comment by DanAlbert** [comment]
Nothing useful in the log. No idea what's wrong but there's also nothing we can do here.

**Comment by KillerHorsefly** [comment]
I am able to use 2.5 but nothing else after that???

**Comment by Starfire13** [comment]
2.5 is ancient and isn't even usable with the current version of DCS.

**Comment by Starfire13** [comment]
By the way, check that Windows Defender is not blocking Liberation from running.

**Comment by KillerHorsefly** [comment]
Is liberation listed under defender?

**Comment by Starfire13** [comment]
You have to check it yourself. On my end, Defender will always block Liberation from running and I have to let it through. On your end, it might be getting block automatically.

**Comment by atercygnus** [comment]
As of me, moving **dcs_liberation** forder from desktop to **C:\Users\my_user_name\\** solved the issue

**Comment by JohnnyNP** [comment]
> As of me, moving **dcs_liberation** forder from desktop to **C:\Users\my_user_name\** solved the issue

Worked for me :)
