### ISSUE TITLE
Blocking Bug: Can't "take off"

### ISSUE THREAD

**Issue by Nomadzy** [dcs-liberation/dcs_liberation#164]
After planning the mission, pressing the take off button does noting (Console Error). I had this issue first in the 2.1.1, but the update to the 2.1.2 solved the problem. Now I got it again and can't do anything.
Also, can't take the Al Ain AB no matter what I do. Where can I find the Airbase Id to edit the JSON manually ?

Thanks.

> 2020-09-30 23:29:04,625 :: INFO :: armorgen: <class 'dcs.vehicles.Armor.ATGM_M1134_Stryker'> for 2
[Errno 2] No such file or directory: './resources/scripts/plugins/__plugins.lst'
Traceback (most recent call last):
  File "qt_ui\windows\mission\QMissionPlanning.py", line 156, in on_start
  File "game\game.py", line 178, in initiate_event
  File "game\event\event.py", line 111, in generate
  File "game\operation\frontlineattack.py", line 39, in generate
  File "game\operation\operation.py", line 289, in generate
  File "game\operation\operation.py", line 321, in assign_channels_to_flights
  File "game\operation\operation.py", line 333, in assign_channels_to_flight
  File "gen\aircraft.py", line 282, in assign_channels_for_flight
  File "gen\aircraft.py", line 228, in assign_channel
AttributeError: 'NoneType' object has no attribute 'mhz'

**Comment by DanAlbert** [comment]
The second error is similar to the one in 2.1.1, but it's a different issue. I don't know about the first error.

**Comment by Nomadzy** [comment]
> The second error is similar to the one in 2.1.1, but it's a different issue. I don't know about the first error.

Thank you @DanAlbert for the quick reply. For the first/main issue, is there something I can do or send you to help you find the bug ? the 'Take Off' button blinks when I click it but there's no action, only a lot of console output that ends with the error message above ...

**Comment by DanAlbert** [comment]
@davidp57 added the feature the other error refers to.

**Comment by davidp57** [comment]
Dan, you’re talking about this ?
 ˋ[Errno 2] No such file or directory: './resources/scripts/plugins/__plugins.lstˋ 
That’s simply a warning message because the file does not exist.
I probably should not write that at all

**Comment by DanAlbert** [comment]
Pushed https://github.com/Khopa/dcs_liberation/commit/a44cbe59724ff89980e72654f7c40c85a72065b5 to make it look less like an error.

**Comment by davidp57** [comment]
Excellent, thanks !

**Comment by Nomadzy** [comment]
@DanAlbert @davidp57  Thank you for the new release, but I still can't take off on two ongoing campaigns.

Full log from start if it can help + the 2 .liberation files:
[Liberation213-No_take_off_Bug.txt](https://github.com/Khopa/dcs_liberation/files/5319870/Liberation213-No_take_off_Bug.txt)
[DCS.OB.zip](https://github.com/Khopa/dcs_liberation/files/5319889/DCS.OB.zip)
