### ISSUE TITLE
AI aircrafts don't carry out CAS mission after several turns

### ISSUE THREAD

**Issue by JeffreyBai** [dcs-liberation/dcs_liberation#1640]
**Describe the bug**
After several turns in the campaign, suddenly all AI aircrafts don't carry out CAS missions anymore. They still fly through the waypoints, but they go directly Ingress-CAS-Egress and leave immediately instead of staying in the mission zone and carrying out the mission.

**To Reproduce**
1. Load the problematic campaign save file
2. Click "Take off" and run the mission
3. Observe the AI behavior of CAS packages and see the problematic behavior

**Expected behavior**
AI aircrafts should stay in the mission zone and carry out CAS mission

**Additional information**
[CAS bug.zip](https://github.com/dcs-liberation/dcs_liberation/files/7285736/CAS.bug.zip)

**Version information (please complete the following information):**
 - DCS Liberation 4.1.1

**Additional context**
The CAS behavior was normal in the first few turns. Then it stopped working all in a sudden. Removing the flight packages and creating new CAS packages doesn't solve this issue. Dragging Ingress-CAS-Egress waypoints apart from each other also doesn't solve this issue. It seems that the Egress waypoint disappears automatically with the CAS waypoint even if the aircrafts haven't reached the Egress waypoint yet.

**Comment by Starfire13** [comment]
There are two different issues here. For one thing, starting your AWACs off on the carrier is preventing your other flights from taking off. I suggest air-starting your AWACs, or have your other flights delayed till the AWACs has already launched. As for your CAS aircraft, setting them to a lower altitude resulted in them engaging in CAS as expected. I did indeed see that they just overflew the frontline and RTB'd when set to 20k feet.

**Comment by JeffreyBai** [comment]
Yes I noticed the AWACS problem too, but it's totally irrelevant to this issue. As for the CAS flight, the altitude is automatically generated by Liberation, so I think it might also worth to take a look why the program generates invalid altitude automatically. I'll try to modify the altitudes manually to see if it solved the problem temporarily. Thanks for your reply.

**Comment by Starfire13** [comment]
Altitude profiles are a planned feature. For now, all flights are set to 20k feet and you have to edit manually in the mission editor as required. The altitudes are not invalid, simply not ideal for all flights. That said, my Harriers have not had issues performing CAS from 20k feet, but I don't use Mavericks on them but GBU-54s.

**Comment by Skunimatrix** [comment]
Something that we noticed in our last campaign, set 1980's so not a lot of smart weapons, was that weather had a major impact on AI CAS behavior.  If it was clear or broken clouds they had few problems with CAS/DEAD/SEAD missions.  However if it was low level clouds/raining/etc. they rarely would engage even if given commands to in the F10 map.  Understandable for TV & IR mavs, LGB's, and even iron bombs or rocket pods, but it also impacted flights tasks with SEAD/SEAD Escort & outfitted with Shrikes or HARMS which shouldn't be weather dependent.
