### ISSUE TITLE
Add campaign start map snapshot images to the campaign selection screen

### ISSUE THREAD

**Issue by sgtfuzzle17** [dcs-liberation/dcs_liberation#1641]
**Is your feature request related to a problem? Please describe.**
In its current form, the campaign creation screen provides a good amount of context and info on what the player will be doing in a campaign and the general region of a given terrain they'll be flying in, but not a great deal of info on how a campaign may progress. At the moment, the only way to get this context is to go through all of the campaigns and generate their starting states which can be time consuming, especially if you're not familiar with them to start with.

**Describe the solution you'd like**
Adding a small snapshot image of the zoomed out Liberation map at the start of the campaign in the campaign creation screen (somewhere off to the side so it's not fighting the rest of the UI for space) would be a great way to give a player some more context before they start up a campaign. You could either have the devs take them to spec, or add it as a requirement for campaign authors to provide alongside their other standard files with given specifications (aspect ratio, ideal resolution, desired UI layers turned on etc.) to ease implementation.

**Additional context**
Here's an example image of my Scenic Route campaign:
![GnbM6WH](https://user-images.githubusercontent.com/49757384/136060709-ff906bd9-5fc6-4584-a517-e46ddde9df51.jpeg)
.

**Comment by Starfire13** [comment]
Yes, this would be so very handy!

**Comment by DanAlbert** [comment]
Duplicate of #446
