### ISSUE TITLE
Autoplanner is planning 2-ship Tu-160 Blackjack flights although DCS only allows a single Tu-160 per flight

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#1649]
**Describe the bug**
This bug was first reported by Paarthurnax on Discord, and I have verified that it occurs in both 4.1.1 and #2890.

While the autoplanner is able to plan 2-ship Tu-160 flights, player-created Tu-160 flights can only ever have a single aircraft. This is not related to pilot availability.

**To Reproduce**
1. Purchase more than 1 Tu-160
2. Set up a Tu-160 flight
3. It will default to a single aircraft
4. You cannot add additional aircraft even though they are available.

**Version information (please complete the following information):**
Bug exists in both 4.1.1 and #2890

**Comment by DanAlbert** [comment]
The auto planner is wrong. Flight size is limited per aircraft by DCS.

**Comment by Starfire13** [comment]
Ah, so it is DCS that limits Tu-160s to one aircraft per flight?

**Comment by DanAlbert** [comment]
The blackjack and a few others, yeah. Almost everything has a max size of 4 but some cargo planes and bombers have lower limits. I have no idea why, but you can see the same behavior in the ME.

**Comment by Starfire13** [comment]
I see. How odd that that they allow 4-ship B-1s but not Tu-160s. So the thing that needs fixing is just the autoplanner display then.

**Comment by DanAlbert** [comment]
It's not a display issue, the auto planner is planning broken missions.

**Comment by Starfire13** [comment]
Oh I see. Do you want me to close this BR and open a new one about that then?

**Comment by DanAlbert** [comment]
No, we have the data we need here.

**Comment by DillieKoe** [comment]
ED seems to have fixed this now
