### ISSUE TITLE
AI wont fire at ships

### ISSUE THREAD

**Issue by mikef-phy** [dcs-liberation/dcs_liberation#1656]
The AI wont fire in anti ship missions.  I did find this setting you need to apply to those missions to make the AI shoot.

Currently, AI won't attack ships unless you set their Reaction To Threat parameter to anything but "allow abort mission".

**Comment by mikef-phy** [comment]
I just noticed in the mission editor that there are no attack actions set for any waypoints in anti ship missions.  So that may be the issue.

**Comment by DanAlbert** [comment]
How were you able to bypass the bug template?

**Comment by mikef-phy** [comment]
i just looked at the generated mission file

**Comment by mikef-phy** [comment]
i would have to fix the mission every time

**Comment by DanAlbert** [comment]
No, I mean how were you able to file a bug without going through the bug template?

**Comment by mikef-phy** [comment]
i just clicked the new issue button.

**Comment by DanAlbert** [comment]
That should have taken you to 
![image](https://user-images.githubusercontent.com/315852/137650798-e412d947-e64b-4cdd-afad-1ff714308ff6.png)
and the "Bug report" option should have given you a big template to fill out, which asks for the information that we would need to investigate anything: 
![image](https://user-images.githubusercontent.com/315852/137650840-dcb8595d-1964-4acd-a997-35740e9d8e51.png)

Did that not happen?

**Comment by DanAlbert** [comment]
Someone else pointed out that GitHub inexplicably adds a "file a blank issue" link to the bottom of that as fine print. I've disabled that now. Please fill out the template so we can investigate. Closing until we have the info we need.
