### ISSUE TITLE
SEAD target WP at 20k ft

### ISSUE THREAD

**Issue by FalcoGer** [dcs-liberation/dcs_liberation#1660]
**Describe the bug**
I joined a SEAD flight in an F16 and set up a AGM-88 in position pre-briefed mode. It failed because the waypoint was set at 20 000ft instead of ground level. I could also not use the targeting pod effectively without first setting the altitude to ground level. Ground target waypoints should be on the ground.

**To Reproduce**
1. Generate SEAD mission
2. Check target waypoint altitude

**Expected behavior**
The target point should be right on the ground.

**Version information (please complete the following information):**
 - DCS Liberation 4.1.1

**Comment by Starfire13** [comment]
Was it set up as a player flight or did you use Combined Arms to take over an AI aircraft? Player flight waypoints are set up differently and have their target waypoint at ground level. I fly SEAD a lot and have never seen the target waypoint placed at 20k feet for player flights.

**Comment by DanAlbert** [comment]
Closing because no save game or miz attached. We need both.
