### ISSUE TITLE
Add the new H-6J to appropriate factions

### ISSUE THREAD

**Issue by sgtfuzzle17** [dcs-liberation/dcs_liberation#1661]
**Is your feature request related to a problem? Please describe.**
The new H-6J AI aircraft would fill the strategic bomber/long range anti-shipping mission for several factions, listed below. It adds another high-fidelity aircraft which is a high priority to intercept.

**Describe the solution you'd like**
The following factions should have the plane added to them once the preceding pydcs work is done:

- China 2010
- Redfor (China) 2010
- Iraq 1991

If possible, please ping me (Fuzzle) in the Liberation Discord should these be added and set up for the 5.x release so that I can adjust some squadron designations in a campaign I'm contributing.

**Comment by MetalStormGhost** [comment]
H-6J could be relatively easily added, since it's already supported by pydcs. @sgtfuzzle17, would you be willing to create the loadouts for the aircraft? Anti-ship, CAS and Strike at least.

**Comment by Starfire13** [comment]
I can save some time for you cos I already have one created. Gimme a min and I'll attach it.

**Comment by Starfire13** [comment]
Here you go. I updated it to include a loadout for OCA/Runway as well.

This loadout file includes loadouts for:
Strike
BAI
CAS
Anti-Ship
OCA/Runway

[H-6J.zip](https://github.com/dcs-liberation/dcs_liberation/files/7403554/H-6J.zip)

**Comment by Starfire13** [comment]
Should the H-6J be added to Redfor (China) 2010 as well?

**Comment by MetalStormGhost** [comment]
These are the factions I added it to:
![image](https://user-images.githubusercontent.com/89945461/138586148-6b26302a-dd8d-4d37-9369-9bdc6a55d7f2.png)

**Comment by Starfire13** [comment]
Perfect. Thank you!

**Comment by sgtfuzzle17** [comment]
Looking great guys, thanks for this. I’ll get the newest dev build downloaded and integrate them into the squadrons for the Marianas campaign I’ve put together then submit it later tonight.
