### ISSUE TITLE
Linked FOBs

### ISSUE THREAD

**Issue by Nosajthedevil** [dcs-liberation/dcs_liberation#1665]
Would it be possible to add the ability to link FOBs so that if one is captured, the other linked FOB also flips sides. This would allow more use out of the mariana map. 

Allow campaign designers to link FOBs somehow ( maybe using a naming convention) so that if a user captures one FOB the linked FOB is also considered captured. This would allow a campaign designer to create a campaign where, for example, when the last FOB or base on one island is captured, a small fob ( no warehouses or factories) on the next island also flips essentially simulating a small beachhead. Fighting would then resume on that next island as blufor pushes from the beachhead and gains more resources till they drive the enemy off that island and on to the next.

**Comment by Starfire13** [comment]
The amphibious landings/assault feature that is planned (no ETA) would achieve the same thing.

**Comment by Nosajthedevil** [comment]
Understood, and amphibious landings/assault feature would be awesome, but I wonder if this would be easier to implement as a stopgap. Figured I'd throw it out there.

**Comment by Nosajthedevil** [comment]
I was trying to think of other use cases for this, and one I thought of is opening up bases & FOBs that are off the capturable path. Using the Scenic Route as an example, we could assume that Oman or UAE refuses to allow US forces to use their airbases out of fear of Iranian retaliation, forcing the player to use only naval air assets at the start of the campaign . Once the U.S captures a couple fobs, Oman, sensing that the US will likely be successful, will then allow the US to use Kaman allowing the player to also start using some limited ground based air assets (assuming a faction with those assets was originally chosen of course). The mechanism in the game to make this happen would be linking Kaman to FOB Kohnehshahr.

I don't know if anyone would actually use any of this, but just thought I'd throw it all out there in case someone wants to consider it.

**Comment by Nosajthedevil** [comment]
Air assault is a better solution.
