### ISSUE TITLE
Air wing configuration does not contain all faction aircraft

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#1668]
**Describe the bug**
The squadrons available for configuration do not contain all of the faction's available aircraft.

**To Reproduce**
1. Create Mozdok to Maykop Campaign.  (USA 2005, Russia 2010, June 30, 2010)
2. No Carriers, No LHA
3. Auto Buy Ground Units
2. At air wing configuration screen, see:

![image](https://user-images.githubusercontent.com/74509817/138540244-41a8e17a-b98b-4698-a8ff-c9a3bc5f4018.png)

**Expected behavior**
Squadrons available for every faction aircraft.

**Saved Game**
[Mozdok_Maykop_2945.zip](https://github.com/dcs-liberation/dcs_liberation/files/7402176/Mozdok_Maykop_2945.zip)

**Version information (please complete the following information):**
 - DCS Liberation Build 2945

**Comment by Starfire13** [comment]
1. The Mozdok to Maykop campaign has no carriers. This is intentional.

2. That isn't how persistent squadrons work. You don't get squadrons for every single aircraft type.
