### ISSUE TITLE
Default window size of aircraft purchase screen makes render issues for entries

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#1669]
**Describe the bug**
The default window size is too short to display aircraft names and squadrons in the text box.

**To Reproduce**
1. Generate any campaign.
2. Open airfield menu on `Airfield Command` tab.

**Expected behavior**
The squadron name and the aircraft name to be visible.

**Version information (please complete the following information):**
 - DCS Liberation build 2945

**Additional context**

Screen resolution is 2560x1440.

![image](https://user-images.githubusercontent.com/74509817/138541724-19ae5fc6-717c-48f2-bf07-4c96de0a87e6.png)

**Comment by DanAlbert** [comment]
How is this different from #1670?

**Comment by SnappyComebacks** [comment]
I thought I closed the window and didn't submit #1670 .  It's a duplicate.

**Comment by DanAlbert** [comment]
Duplicate of #1670
