### ISSUE TITLE
Default airfield window size does not fit squadrons names.

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#1670]
**Describe the bug**
The default window size for aircraft purchasing does not show the squadron name clearly when on a 2560x1440 monitor.

**To Reproduce**
1. Generate any campaign:
2. Open the airfield's management window (left click on airfield) `Airfield Command` tab.
3. See:

![image](https://user-images.githubusercontent.com/74509817/138542106-765b6ee7-05d7-41fb-8059-d911f138f5b4.png)

**Expected behavior**
Aircraft names and squadron names to be clearly readable.

**Additional Information**
[Mozdok_To_Maykop_2945_SquadronPurchaseRenderingIssue.zip](https://github.com/dcs-liberation/dcs_liberation/files/7402300/Mozdok_To_Maykop_2945_SquadronPurchaseRenderingIssue.zip)

**Version information (please complete the following information):**
 - DCS Liberation build 2945

**Comment by DanAlbert** [comment]
> Generate any campaign:

Works for me. Include a save.

**Comment by Starfire13** [comment]
This same issue also happens on my end. I have to drag the window down to expand it every time. I figured it was just cos I run Liberation on my crappy secondary monitor, which is only 1920x1080, but looks like it's happening on Snappy's larger monitor too.

**Comment by DanAlbert** [comment]
Attach a save please. I don't have this problem on Black Sea.

**Comment by SnappyComebacks** [comment]
Here is a campaign that creates the issue for me.  Mozdok aircraft management window.  [Mozdok_To_Maykop_2945_SquadronPurchaseRenderingIssue.zip](https://github.com/dcs-liberation/dcs_liberation/files/7402300/Mozdok_To_Maykop_2945_SquadronPurchaseRenderingIssue.zip)

**Comment by Starfire13** [comment]
It doesn't just happen on Black Sea. It happens on every single campaign on my end.

**Comment by sgtfuzzle17** [comment]
I've managed to establish that this is far more common in campaigns where you've got a large amount of squadrons stationed at a given control point (the list scales entry size vertically, rather than introducing a scroll bar or enlarging the window to suit).
