### ISSUE TITLE
Clicking Add Flight on Front Line causes exception

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#1672]
**Describe the bug**
Clicking on the front line and then `Add Flight` causes an exception.

![image](https://user-images.githubusercontent.com/74509817/138542677-b84e39a6-41b3-44b9-b28d-68606f49d6ef.png)

**To Reproduce**
1. Create Mozdok To Maykop campaign (USA 2005, Russia 2010, June 30 2010)
2. Check No carriers and No LHAs
3. Default squadrons
4. Purchase aircraft
5. Pass Turn
6. Attempt to create a package on the front line

**Expected behavior**
Exception not to be thrown.
To be able to create a package.

**Additional information**
[Mozdok_Maykob_2945_ExceptionPackageCreationFrontLine.zip](https://github.com/dcs-liberation/dcs_liberation/files/7402276/Mozdok_Maykob_2945_ExceptionPackageCreationFrontLine.zip)

**Version information (please complete the following information):**
 - DCS Liberation build 2945

**Comment by Nosajthedevil** [comment]
I'll try to recreate this tomorrow, but I saw this exact error on build 2944, 2945, & 2946  for the marianas landing at agat campain. Reverting to 2943 fixed it.

**Comment by MetalStormGhost** [comment]
Could you try it with build #2948 and report if it also happens with that one? If so, I could take a look.

**Comment by DanAlbert** [comment]
@MetalStormGhost I'll probably beat you to it. I suspect this is trivial, the UI just can't be type checked so we miss little things easily :(

**Comment by MetalStormGhost** [comment]
Yeah. I figured that I might have fixed this already since I made some changes to QFlightCreator on PR #1674

**Comment by DanAlbert** [comment]
Ah, gotcha. Will get on that review :)

**Comment by DanAlbert** [comment]
Your PR does have the fixes in it but it also has other stuff and the PR isn't quite ready to merge, so I merged a fix.
