### ISSUE TITLE
Squadron generation should consider aircraft types for tanker choice

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#1673]
**Is your feature request related to a problem? Please describe.**
If squadrons are generated through the current fallback system, the tanker squadron selected may or may not match the aircraft of the other squadrons.

**Describe the solution you'd like**
Tanker availability should be based off the aircraft available in the campaign.

**Additional context**
The `F-15C` here cannot use the `KC-130`.

![image](https://user-images.githubusercontent.com/74509817/138540244-41a8e17a-b98b-4698-a8ff-c9a3bc5f4018.png)

**Comment by DanAlbert** [comment]
It's up to the campaign designer.

**Comment by SnappyComebacks** [comment]
> It's up to the campaign designer.

That's why I mentioned that this occurs when using squadrons chosen by the fallback method (When you choose factions that don't match the recommended ones).  They cannot have been chosen by the campaign designer.

**Comment by DanAlbert** [comment]
The campaign designer should include both types though.

**Comment by SnappyComebacks** [comment]
> 
> 
> The campaign designer should include both types though.

The campaign designer cannot include both types if the recommended faction is not capable of both types.  Russian factions cannot do boom refueling, but US factions can.

**Comment by DanAlbert** [comment]
Yes they can. They can make a boom squadron and a basket squadron and it'll fall back to whatever the faction is capable of they don't have those. If the player chooses a faction capable of them they'll get them, if they don't they'll get whatever the faction is capable of.

**Comment by Starfire13** [comment]
You can add two refueling aircraft to the same squadron. If the first on the list isn't available, the second will be chosen (provided it is available, of course). I just pick the MPRS for my campaigns since it can refuel anything.

**Comment by SnappyComebacks** [comment]
> They can make a boom squadron and a basket squadron and it'll fall back to whatever the faction is capable of they don't have those.

I'm having trouble understanding what you are saying here.  My understanding is that the default squadrons are set in `/resources/campaigns/{campaign_name}.yaml`.

Are you saying that the refueling entry in this file: https://github.com/dcs-liberation/dcs_liberation/blob/develop/resources/campaigns/mozdok_to_maykop.yaml should be:

```
squadrons:
  # Mozdok
  28:
    - primary: Refueling
      aircraft:
        - IL-78M
        - KC_135MPRS
```

If the campaign designer wants to support `boom` and `probe and drogue`?   Or do what @Starfire13 is saying?

**Comment by DanAlbert** [comment]
If you want to make a campaign that has tankers support that works for most factions you need two tanker squadrons. One designed like that, plus another that falls back to a regular KC-135 for a boom.

> I just pick the MPRS for my campaigns since it can refuel anything.

That's not actually true in DCS though, right? Did that get fixed?

**Comment by SnappyComebacks** [comment]
> That's not actually true in DCS though, right? Did that get fixed?

It is still not true.  The boom on a `KC_135MPRS` does not function.

**Comment by DanAlbert** [comment]
Thought so. Need two squadrons then.

**Comment by Starfire13** [comment]
> > That's not actually true in DCS though, right? Did that get fixed?
> 
> It is still not true. The boom on a `KC_135MPRS` does not function.

Ah, interesting. I did not know that. I've never tried refueling from one of those. I should alter the refueling squadrons then when I update my campaigns for 9.1.
