### ISSUE TITLE
Add option to generate the mission part way through

### ISSUE THREAD

**Issue by DanAlbert** [dcs-liberation/dcs_liberation#1681]
Add simulation of the mission from the start of the turn up to the first engagement. Generate the mission from that point.

Subtask of https://github.com/dcs-liberation/dcs_liberation/issues/1680

- [x] Add option to fast forward the mission until the first contact:
    - [x] Contact at IP
    - [x] Contact at SAM threat
    - [x] Contact at A2A threat
- [x] Reduce mid-mission fuel based on estimated fuel spent in travel

**Comment by Starfire13** [comment]
This seems related to https://github.com/dcs-liberation/dcs_liberation/issues/1440 and is definitely a very welcome new feature, especially for those who prefer to play roles that tend to have later starts.

**Comment by sgtfuzzle17** [comment]
Really liking this feature in the dev build currently, but I think the "start at startup time" option could maybe use some tuning. Currently it seems to allow 20 minutes for startup which is quite large for most aircraft (which can get in the air in 5-10).

**Comment by DanAlbert** [comment]
Unrelated. File a new FR.
