### ISSUE TITLE
E-2D is wrongly labeled E-2C

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#1696]
**Describe the bug**
Liberation defines the E-2D from DCS as the E-2C.

Liberation:
![image](https://user-images.githubusercontent.com/74509817/139180548-88a6692b-a910-4cf0-b33f-6c900cf5d6d6.png)

DCS:
![image](https://user-images.githubusercontent.com/74509817/139180821-2aab9c30-fcb1-488c-b890-5ae418d71877.png)

**Expected behavior**
E-2C to be renamed E-2D.

**Additional information**
[VectronsClaw_4.1.1.zip](https://github.com/dcs-liberation/dcs_liberation/files/7430823/VectronsClaw_4.1.1.zip)

**Version information (please complete the following information):**
 - DCS Liberation 4.1.1

Edit:  Actually, it's inconssistent on ED's side as well.
![image](https://user-images.githubusercontent.com/74509817/139184305-a59db14b-bda3-4fc0-ac5a-b1919b928e32.png)
It is supposed to be E-2D though.  8 bladed prop.

**Comment by DanAlbert** [comment]
Added a new variant and moved blufor modern to it, but the rest of the factions are older than the E-2D so left them where they are.

**Comment by SnappyComebacks** [comment]
That is way simpler of a fix than I was thinking it was going to be.  Nice!
