### ISSUE TITLE
Persian Gulf – Road to Dubai - BLUE side: only one aircraft takes off

### ISSUE THREAD

**Issue by taipan303** [dcs-liberation/dcs_liberation#1697]
Liberation Version: 4.1.1
DCS version: Open Beta current (28th October 2.7.7.14727)

**To Reproduce**
Start a new game with Theatre = Persian Gulf – Road to Dubai, late cold war Winter 1985, invert map OFF
Player faction = USA 1975
Enemy faction = Iran 1974 (same as Iran 1988 with removal of F5, F14 removed, Patton, Hawk, Rapier - file attached)
Set campaign and mission generator settings as per save file attached (or load save file)
Set automation for all purchases
Next turn

Any mission flown in the first four missions I found only my wingman, and one or two other planes would actually take off.
The attached track and save is for an AI only mission to demonstrate this, only the first plane takes off and the rest are stuck in place with engines running even if time accelerate to the missions end.

All red planes takeoff as normal, its only blue side that is affected.

**Expected behavior**
Blue side to perform missions similar to how red does

**Additional information**
[Liberation no takeoffs.docx](https://github.com/dcs-liberation/dcs_liberation/files/7433231/Liberation.no.takeoffs.docx)
[Liberation files.zip](https://github.com/dcs-liberation/dcs_liberation/files/7433234/Liberation.files.zip)
[dcs files.zip](https://github.com/dcs-liberation/dcs_liberation/files/7433237/dcs.files.zip)
[Saves_before_mission.zip](https://github.com/dcs-liberation/dcs_liberation/files/7433239/Saves_before_mission.zip)
[Saves_after_mission.zip](https://github.com/dcs-liberation/dcs_liberation/files/7433241/Saves_after_mission.zip)

**Comment by Starfire13** [comment]
Don't use F-14As on airfields in Syria. They don't know how to keep their wings closed inside the hangars and get stuck. Have to wait till Ugra Media fixes their map.

https://steamuserimages-a.akamaihd.net/ugc/1804248189042640922/16EDD117875901C32E497B67DE95BD1100D9D69F/

**Comment by taipan303** [comment]
Thanks for the fast response! That explains why Iran worked - only because I had customised it.. 
I'll edit the blue faction to remove them thanks

**Comment by taipan303** [comment]
Actually this was Persian Gulf map not Syria. Should we remove F-14 for both maps?

Not sure if ED will ever fix Persian Gulf

**Comment by Starfire13** [comment]
No, because folks can use F-14s from carriers (which is where they would be stationed anyway).

**Comment by taipan303** [comment]
> 
> 
> No, because folks can use F-14s from carriers (which is where they would be stationed anyway).

Yes but Liberation doesn't assign them to a carrier, it puts them in the hangars because there is no carrier in this case.

Using the HQ Automation for all purchases it still purchases F-14s even if there is no carrier, then adds them to shore based packages at the airbase.

If F-14s are never shore based, could the automation be changed to only purchase F-14s if there is a carrier? 
Or to not assign any F-14s to shore based packages?
Otherwise it auto-creates packages starting from hangar tents and the only way around it with automation is to totally remove the F-14 from the faction file.

I've raised with ED in case they want to fix the map or the AI: https://forums.eagle.ru/topic/285579-persian-gulf-f-14a-ai-open-wings-on-startup-getting-stuck-inside-the-hangar-tents/?tab=comments#comment-4810754

**Comment by Starfire13** [comment]
In 5.0, squadron locations are preset by the campaign designer, so the F-14s would be stationed on the carrier.

**Comment by taipan303** [comment]
> 
> 
> In 5.0, squadron locations are preset by the campaign designer, so the F-14s would be stationed on the carrier.

Awesome, that will be cool. Love this tool, looking forward to trying v5

**Comment by DanAlbert** [comment]
Watching the track, this is just the usual DCS AI taxi misbehavior. All the planes are turning on which means the triggers are working, the airport is just jammed. The E-2 gets stuck mid-taxi and that blocked everything else. Removing the E-2 allows the  tanker to take off but everything else is still jammed it seems.

Nothing we can do.
