### ISSUE TITLE
Viper Targeting Pod

### ISSUE THREAD

**Issue by wraith70** [dcs-liberation/dcs_liberation#17]
Custom loadout  for the Viper is missing the AN/AAQ-28 Litening pod for 5R (payload position 6).

**Comment by Khopa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [F-16C Pylons](https://trello.com/c/m73w9dbd/115-f-16c-pylons)

**Comment by Khopa** [comment]
In Liberation,
- Pylon 5L is Pylon "10" which is not implemented by DCS, so not shown.
- Pylon 5R is Pylon "11"

These are the internal ID used by DCS for these pylon. I believe only the F-16C has this weirdness.
The Pylon name being different from the real Pylon Id, this currently cause a bug in DCS Liberation, and the litening pod is never correctly added to the payload. I'm fixing this in version 2.1.1.

In the UI, Pylon 5R will remain "11" for now though. (This is autogenerated based on DCS data, and i don't really want to start adding exceptions for now)

![image](https://user-images.githubusercontent.com/2546901/90946505-a4eedc00-e42d-11ea-8bc3-a32b7e4e75dc.png)

**Comment by Khopa** [comment]
This should be fixed in 2.1.1 and 2.1.2

Closing
