### ISSUE TITLE
New Marianas campaign: Pacific Repartee

### ISSUE THREAD

**Issue by sgtfuzzle17** [dcs-liberation/dcs_liberation#1701]
* Campaign name: Pacific Repartee
* Files:
[pacific_repartee.zip](https://github.com/dcs-liberation/dcs_liberation/files/7441759/pacific_repartee.zip)
 
* Update summary (optional): A modern naval campaign for Marianas utilizing the new island chains north of Guam as well as Saipan and Guam. Using default factions will see the US Navy carrier group fighting their way south through the islands to eventually retake Andersen AFB and the rest of the island chain.
* Note that this is an offensive air campaign without a traditional frontline, which is stated in the campaign description quite clearly. Players will be flying CAPs, intercepting bombers (including the new Deka H-6J), hunting ships and attacking strike targets. Unfortunately until we get amphibious landings, it's basically impossible to make a traditional Liberation campaign on Marianas that isn't built around helicopters or WW2 gameplay. This can fill the modern/cold war era gameplay gap in the meantime.

**Comment by DanAlbert** [comment]
I fixed this before checking it in, but note that:

```yaml
aircraft:
  THING
```

and

```yaml
arcraft:
  - THING
```

Are not the same. The second one is correct. (most of them were right but a few were wrong and would have gotten some arbitrary aircraft rather than what you picked).

**Comment by DanAlbert** [comment]
Also the version field should be quoted. `"9.1"`, not `9.1`.
