### ISSUE TITLE
No attack orders given to anti-ship flights when enemy carrier is the target

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#1702]
**Describe the bug**
Mikef brought this to our attention on Discord and I did some testing to verify. There don't appear to be any orders on the ingress waypoint (or any other waypoint for that matter) directing an anti-ship flight to attack their intended target (edit: only applies when target is a carrier). They fly to the ingress waypoint and then RTB. This applies to both Hornets and Vikings, and the bug exists in both the latest dev build #2976 and 4.1.1. I wonder if some DCS update has broken this because I know it was working a while back.

![Capture](https://user-images.githubusercontent.com/72491792/139528451-dcec15f6-dbf4-454a-9e9d-aa0f49522d9e.JPG)

**To Reproduce**
1. Buy Hornets or Vikings.
2. Give them an anti-ship mission (edit: with a carrier as the target).
3. Look at ingress waypoint in mission editor.
4. There are no orders.

**Expected behavior**
Anti-ship flights should fire their missiles.

**Version information (please complete the following information):**
 - This issue currently exists on both #2976 and the 4.1.1 release build.

**Comment by MetalStormGhost** [comment]
I did some testing on this and found out the problem seems to be specific to anti-ship missions against carriers. When attacking destroyer groups or cargo ships, the attack orders are generated correctly. Liberation develop Revision: 74291271e398f971fe39635c77586777c94ba7ce - DCS World 2.7.7.15038 open beta.

**Comment by MetalStormGhost** [comment]
The log shows an error about an unexpected BAI mission target:
`2021-10-30 13:14:47,161 :: INFO :: Generating flight: F/A-18C Hornet (Lot 20)`
`2021-10-30 13:14:47,165 :: ERROR :: Unexpected target type for BAI mission: Carrier`
