### ISSUE TITLE
UI for fast forward

### ISSUE THREAD

**Issue by DanAlbert** [dcs-liberation/dcs_liberation#1704]
Show the status of fast-forwarded flights in the UI.

Subtask of https://github.com/dcs-liberation/dcs_liberation/issues/1680

- [x] Play/pause/speed buttons
- [x] Show in-progress flights on the map
- [x] Update ATO panel with flight status (waiting, startup, taxi, takeoff, in air)

**Comment by Starfire13** [comment]
Will this have a rewind function as well in case we fast forward too much?

**Comment by DanAlbert** [comment]
No.
