### ISSUE TITLE
custom squadron .yaml for the hornet are ignored

### ISSUE THREAD

**Issue by dasrehzockt** [dcs-liberation/dcs_liberation#1710]
custom squadron.yaml for the hornet seem to be ignored on 5.0.0-2994-preview at Air Wing Configuration when starting a new Campaign.

**Comment by DanAlbert** [comment]
Follow the template.

**Comment by dasrehzockt** [comment]
it ignores the 4 non altered templates that are included with the download as well. it does not read any of them and always generates random squadrons like "squadron 001".
the other airframes work fine.

EDIT: This seems to be due to the squadron not being able to spawn ashore. so in a scenario without any carrier, it will not consider these squadrons without adding other bases to spawn at.
```
bases:
  shore: true
```

while this is obviously intended behaviour it would be better to include those new lines considering 'base' in the standard templates. also i think the hornet should not be bound to carrier only by default but only when set to in a template. without any lines defining the bases, it seems do have shore set to false and only carrier to true.

**Comment by Starfire13** [comment]
This is already fixed. https://github.com/dcs-liberation/dcs_liberation/issues/1621
