### ISSUE TITLE
fix missing label for income multiplier in campaign wizard

### ISSUE THREAD

**Issue by rabauke80** [dcs-liberation/dcs_liberation#1712]
To new players, it's often unclear what the top two sliders are, especially since there is no labeling.

5.0.0-3000-preview build
![image](https://user-images.githubusercontent.com/67376231/140546897-0def7468-6c1a-4b1f-96fc-9b08b8c5d96b.png)

I worked my mspaint magic and tried to come up with something simple but self explanatory.

mockup:
![image](https://user-images.githubusercontent.com/67376231/140548586-e268b7bf-4c13-469d-9274-a2c39925fa58.png)

**Comment by DanAlbert** [comment]
There's _supposed_ to be a label. This is a bug.

**Comment by rabauke80** [comment]
> There's _supposed_ to be a label. This is a bug.

understood - well I think even with a label, the suggested UI flow would be more clear. I would even add a few other preferences on that screen, as part of the campaign setup, based on the selected plugins.

e.g. if you've selected Skynet IADS - force the player to set up the plugin options as part of the campaign setup. Unless there is a good reason why they are in a separate menu, after the campaign is created? It happened to me, during heavy testing, that I sometimes forgot about the plugin options before launching a mission.

**Comment by DanAlbert** [comment]
One bug per bug please. We can't track half a bug.
