### ISSUE TITLE
Mission Won't Start, Unit Data 'Missing'

### ISSUE THREAD

**Issue by Lloydski246** [dcs-liberation/dcs_liberation#1714]
Before filing, please search the issue tracker to see if the issue has already been reported.

If reporting a DCS AI bug, check https://github.com/dcs-liberation/dcs_liberation#dcs-bugs.

**Describe the bug**
We've been running a Cyprus liberation for a while, we're on turn 6ish. It's been fine for the past month or so, but when I loaded it up today I am unable to take-off. Two key things I've noticed:

1. Pressing 'take-off' either does nothing or crashes the lib client.
2. The cmd window has a long list of 'no data' errors (screenshot attached)

I've checked my DCS folder location and everything is pointed to the right place. Apart from updating DCS itself, nothing has changed.

**To Reproduce**
1. Load up the attached campaign.
2. Check cmd window for missing unit warnings.
3. Click 'take-off'.

**Expected behavior**

**Additional information**

The following items are attached in the zip file: [sabrecyprus.zip](https://github.com/dcs-liberation/dcs_liberation/files/7488056/sabrecyprus.zip)
- sabrecyprus.liberation (the campaign file)
- liberation.log (the full logfile in the lib folder)
- liberation_nextturn.miz (the last mission we ran)
- current_state.json (the state.json from my lib folder)
- previous_state.json (the state.json from the ser
ver we ran the last mission on)

**Version information (please complete the following information):**
 - DCS Liberation [e.g. 2.3.1]: 4.1.1
 - DCS Version: 2.7.7.15038

**Additional context**
None.

**Comment by Hornet2041** [comment]
i loaded up the save in 4.1.1 and generated this error:

Traceback (most recent call last):
  File "widgets\QTopPanel.py", line 289, in launch_mission
  File "game\game.py", line 270, in initiate_event
  File "game\event\event.py", line 64, in generate
  File "game\operation\operation.py", line 288, in generate
  File "game\operation\operation.py", line 408, in _generate_transports
  File "gen\convoygen.py", line 31, in generate
  File "gen\convoygen.py", line 34, in generate_convoy
  File "gen\convoygen.py", line 61, in _create_mixed_unit_group
IndexError: list index out of range

**Comment by Hornet2041** [comment]
https://github.com/dcs-liberation/dcs_liberation/issues/1409
https://github.com/dcs-liberation/dcs_liberation/pull/1411

**Comment by RndName** [comment]
This sounds familiar. Did you submit the previous results with Version 4.0.0?
Do you have the liberation save file for the previous round?

**Comment by RndName** [comment]
A quick workaround which you could try is to press "Pass Turn" once and then it should hopefully work again :)

**Comment by Hornet2041** [comment]
i'm pretty sure this is the empty enemy convoy bug that keeps popping up in 4.0/4.1

**Comment by RndName** [comment]
...which was fixed with 4.1. 
**BUT** the fix only works if a result (state.json) is submitted using the V4.1. If the save is already broken because it was submitted with V4.0 the fix will not help. Then the only solution i am aware of is  to try the "Pass Turn" workaround once.

Nevertheless it would be extremly helpful to debug what exactly happend in this issue here. To do so i need the liberation campaign save of the previous round and the corresponding state.json.

With the save attached here i can see that there is an convoy with 0 units. Thats why the Take Off is not working and throwing the error already mentioned here.

**Comment by Lloydski246** [comment]
Hi, 

Unless Liberation has an auto-update feature that I've missed, the campaign was created on 4.1.1 as I avoid updating whilst a campaign is running.

We use a single save file for the campaign, so I cannot provide a previous one unless it is backed up by the lib client somewhere.

I encountered this issue again during the campaign a week ago (we run a turn, maybe 2 turns every Saturday), which I negated by passing a turn as suggested by Lion. It is not consistent, seemingly happening randomly.

In the upcoming turn, I will create a second save to act as a backup and see if I can catch it happening.

**Comment by RndName** [comment]
thanks for the clarification! i will try my best to reproduce this somehow. 

The best thing would be to have a save from the previous round together with the state.json which was used to finish the round. As soon as you catch this thing again it would be super if you could upload these here as well.

**Comment by RndName** [comment]
Should be fixed with c643adf
