### ISSUE TITLE
Faction "Iran 1988" should not have SA5Generator

### ISSUE THREAD

**Issue by rabauke80** [dcs-liberation/dcs_liberation#1717]
Version: 5.0.0-3000 preview

According to this source: https://en.wikipedia.org/wiki/Islamic_Republic_of_Iran_Air_Defense_Force

Iran did not have SA-5 operational before 1997

" In 1997, the Iranian Air Defense forces declared the Almaz S-200 Angara (SA-5 'Gammon') low-to high-altitude surface-to-air missile (SAM) operational."

**Comment by Khopa** [comment]
Fixed in commit https://github.com/dcs-liberation/dcs_liberation/commit/5b4d65db239820a741d1c64452038260401f9c37
