### ISSUE TITLE
Faction "Israel 1982" shouldn't have Merkava Mk IV

### ISSUE THREAD

**Issue by rabauke80** [dcs-liberation/dcs_liberation#1718]
Version:
5.0.0-3000 preview

According to this source (https://en.wikipedia.org/wiki/Merkava#Merkava_Mark_IV) the Mk4 of the Merkava was not in service of the IDF before 2004.

The only model fitting to that time frame would be the Mk1 which is not modeled in DCS yet.

**Comment by Khopa** [comment]
Fixed in commit https://github.com/dcs-liberation/dcs_liberation/commit/c21476b262d91a0139437238666ff887fc5dc6d7
