### ISSUE TITLE
Syria MAP: Ground Units spawn on roftops

### ISSUE THREAD

**Issue by Quax456** [dcs-liberation/dcs_liberation#172]
As the title says ... many Units are spawning very close to Buildings and sometimes on their roftops.....
This makes it very hard to spot especialy if they spawn between the half round hothouses.

**Comment by Mustang-25** [comment]
Many of the campaigns have been reworked and this shouldn't be a problem going forward. If you see this again go ahead and file a new bug report with the specific campaign and unit location so the campaign designer can make the fix. Thanks!
