### ISSUE TITLE
UI map does not update on first package deletion

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#1720]
**Describe the bug**
Map UI does not update immediately on deletion of some packages.

**To Reproduce**
1. Generate `Operation Peace Spring` campaign with `default` factions/settings and `auto purchase ground units` enabled.
2. Purchase lots of aircraft at `Ramat David`, specifically lots of multirole, some awacs and tankers
3. Generate campaign
4. Delete an auto generated strike package (suggest `COCKATOO` if available)
5. View that the deleted strike package still exists on the map, and can no longer be selected
6. Try to recreate the package you just deleted, and receive:
![image](https://user-images.githubusercontent.com/74509817/140663615-d8c9e94f-0dc0-4072-b41e-f85d1266acec.png)

**Expected behavior**
Package `Strike COCKATOO` to be removed from the map after clicking `Delete`.

**Additional information**
[3025_ui_update.zip](https://github.com/dcs-liberation/dcs_liberation/files/7493197/3025_ui_update.zip)
Here is the same campaign at two different save points.  Immediately before pressing `begin campaign` and immediately after.

If you use the save file from after campaign start, and try to delete strike package `COCKATOO`, the UI will not update.
Then try to recreate strike package `COCKATOO` and you will receive the error in the image.

**Version information (please complete the following information):**
 - DCS Liberation `build 3025`

**Comment by DanAlbert** [comment]
https://discord.com/channels/595702951800995872/595706037449785364/907126320520114176 is what I'd found so far. Linking here so it doesn't get lost by the time I have a chance to look more closely.
