### ISSUE TITLE
More realistic ship damage

### ISSUE THREAD

**Issue by Kervinou** [dcs-liberation/dcs_liberation#1725]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**

Ships are very difficult to disable in DCS, having a trigger that allows them to be disarmed for example without the need to sink them would be more realistic.
This is what I do in my missions in general,
- a trigger to stop them from firing if they get hit once or twice (a few times only for a set time of about 30 minutes)
- another trigger that allows you to destroy them with a certain % of damage

**Additional context**
No

**Comment by Hornet2041** [comment]
The Harpoon was buffed recently to deal twice as much damage as it used to. Ships I find have no problem dying now after a reasonable amount of hits.

**Comment by Kervinou** [comment]
Indeed, this seems to have changed, I had missed this improvement of the Harpoon.
And indeed, during a recent mission, another pilot managed to sink two ships without much difficulty and to my great surprise!

Sorry for the inconvenience ;-)
Thanks
