### ISSUE TITLE
campaign blocked : create next mission is impossible

### ISSUE THREAD

**Issue by Kervinou** [dcs-liberation/dcs_liberation#1726]
**Describe the bug**
create next mission is impossible

**To Reproduce**
Click on "Take-Off" button

**Expected behavior**
have a mission generated as normaly !
but nothing happens

have you a work arround for me please, campaign is blocked
thanks

**Additional information**

- DCS Liberation save file enclosed
[georgian_turn_08_A.zip](https://github.com/dcs-liberation/dcs_liberation/files/7510820/georgian_turn_08_A.zip)

**Version information (please complete the following information):**
 - 4.1.1

**Additional context**
n/a

**Comment by Kervinou** [comment]
i have noticed this in the log : 2021-11-10 08:49:54,332 :: WARNING :: Found empty group in Ship
![Capture d’écran 2021-11-10 090009](https://user-images.githubusercontent.com/6077455/141073256-900d95f1-f6d6-4b35-9938-7db12d7f3f19.png)

**Comment by Kervinou** [comment]
Previous mission is OK
enclosed liberation file and json

to test, you can takeoff and next manually import json, all seems correct
but after that, impossible to create the next mission
[previous_mission_is_ok.zip](https://github.com/dcs-liberation/dcs_liberation/files/7510879/previous_mission_is_ok.zip)

**Comment by DanAlbert** [comment]
The JSON file in the zip is the state.json, right? Sounds like it but I can't view it on my phone and wanted to ask ASAP before it gets overwritten because that part is also usually critical in debugging these types of issues.

**Comment by Kervinou** [comment]
Thanks
liberation file of the previous mission and json of results of the mission are in the zip ;)

**Comment by Kervinou** [comment]
Yes, there are in the zip ;-) 

---

Serveur Minecraft +21ans depuis avril 2013
http://madincraft.fr 

Le 10/11/2021 10:08, Dan Albert a écrit :

> Any chance you also have the state.json file to go from the previous mission to the broken one? Maybe that's already in the zip, but k can't view it on my phone. Wanted to ask ASAP before it gets overwritten because that part is also usually critical in debugging these types of issues. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
> Triage notifications on the go with GitHub Mobile for iOS [3] or Android [4].
 _L'absence de virus dans ce courrier électronique a été vérifiée par la
mission Apollo (ClamAV+SpamAssassin)_

**Comment by Kervinou** [comment]
I have tried more things without success

- removal of the destruction of boats in the json
- removed vaziani capture (but it's wrong, I don't understand why it's in the json)
- removed all automatically created packages

but i have always this message in the log : 2021-11-10 12:35:48,376 :: WARNING :: Found empty group in Ship

**Comment by Kervinou** [comment]
2021-11-10 12:45:12,201 :: WARNING :: Found empty group in Ship
Traceback (most recent call last):
  File "widgets\QTopPanel.py", line 289, in launch_mission
  File "game\game.py", line 270, in initiate_event
  File "game\event\event.py", line 64, in generate
  File "game\operation\operation.py", line 288, in generate
  File "game\operation\operation.py", line 408, in _generate_transports
  File "gen\convoygen.py", line 31, in generate
  File "gen\convoygen.py", line 34, in generate_convoy
  File "gen\convoygen.py", line 63, in _create_mixed_unit_group
  File "dcs\mission.py", line 687, in vehicle_group
IndexError: list index out of range

**Comment by Starfire13** [comment]
It's that empty convoy error again. It's already fixed in dev build. Just delete your convoys in Liberation. If it's an enemy convoy causing the problem, just hit pass turn.

**Comment by Kervinou** [comment]
Big Thanks you saved me and others ;-)
Tried and it's seems to be OK, thanks again !

**Comment by DanAlbert** [comment]
Alright, that means we've already fixed this so can close.

Thanks for getting all the right artifacts for us to debug this though. That almost never happens :)
