### ISSUE TITLE
Liberation 2.1.3 Take off button not working.

### ISSUE THREAD

**Issue by jasonmayr** [dcs-liberation/dcs_liberation#173]
[DCS Liberation Log.txt](https://github.com/Khopa/dcs_liberation/files/5321068/DCS.Liberation.Log.txt)
[liberation 2-1-2.log](https://github.com/Khopa/dcs_liberation/files/5321079/liberation.2-1-2.log)

Ok So In 2.1.2 which works prefectly, except in 2.1.1 where the carrier had 127.5 and Tcan of 47 and ICLS 2, with tanker info in the briefing. to in 2.1.2 where carrier went to Tacan of 1X and ICLS Channel 1 with no tanker info in the briefing. and In 2.1.3 it doesn't create the liberation_nextturn.miz file for the missions. I tried everything so I attached to the log file the game generates in the back ground. Both versions of the log file is in this post. I reinstalled 2.1.2 and it works flawlessly, 2.1.3 doesn't

JM

**Comment by Meyomyx** [comment]
Agreed - my 2.1.2 mission won't start in 2.1.3. The "Take Off" button does nothing.

**Comment by Meyomyx** [comment]
![err](https://user-images.githubusercontent.com/70166005/94984094-68d88c00-0540-11eb-8ca4-32fa55bf355e.jpg)

**Comment by Nomadzy** [comment]
Same problem in the 2.1.2 and 2.1.3
 More details: https://github.com/Khopa/dcs_liberation/issues/164

**Comment by davidp57** [comment]
```
2020-10-03 00:05:15,935 :: INFO :: armorgen: <class 'dcs.vehicles.Armor.APC_MTLB'> for 17
Traceback (most recent call last):
  File "qt_ui\windows\mission\QMissionPlanning.py", line 156, in on_start
  File "game\game.py", line 178, in initiate_event
  File "game\event\event.py", line 111, in generate
  File "game\operation\frontlineattack.py", line 39, in generate
  File "game\operation\operation.py", line 224, in generate
  File "game\game.py", line 195, in is_player_attack
AttributeError: 'NoneType' object has no attribute 'name'
```

This particular error has been corrected in https://github.com/Khopa/dcs_liberation/commit/aca415db235da646ae868c2fa2f047b9a873e4fa

**Comment by Khopa** [comment]
Release for this fix : 

https://github.com/Khopa/dcs_liberation/releases/tag/2.1.4b
