### ISSUE TITLE
[Reminder] Document usage with MP server

### ISSUE THREAD

**Issue by davidp57** [dcs-liberation/dcs_liberation#174]
This is for me (@davidp57), just as a reminder
--------------------------------------------------

- try to understand if (and why) the open/save in the ME step is needed
- write a page in the wiki explaining (with pictures and clear usecases) how to use Liberation with a dedicated MP server
- be clear about the file locations, explain how to set up environment variables

**Comment by Khopa** [comment]
@davidp57 

I had started a page here for dedicated server : https://github.com/Khopa/dcs_liberation/wiki/Dedicated-Server-Guide
It's far from complete or up-to date, but it's a start 😁 

I sent you an invite, so you will be able to modify wiki pages.

**Comment by davidp57** [comment]
Great, thanks !
I'll do that.

PS : I confirm, I do have access.

**Comment by davidp57** [comment]
done !
