### ISSUE TITLE
Autogenerated frequencies for Viper

### ISSUE THREAD

**Issue by laserjarle** [dcs-liberation/dcs_liberation#1740]
Before filing, please search the issue tracker to see if the issue has already been reported.

If reporting a DCS AI bug, check https://github.com/dcs-liberation/dcs_liberation#dcs-bugs.

**Describe the bug**

**To Reproduce**
1. Start new campaign
2. Enable supercarrier, 3x income multiplier and 5000 cred on blue.
3. Automate runway repairs, fron-line purchases, and aircraft purchases.
4. Finish the setup and begin campaign.
5. Insert player in the upper right dead/sead mission

**Expected behavior**
Some of the times this will create autogenerated frequencies outside the range of the Vipers COM 2 (108.000 to 115.975 MHz).

**Additional information**
This happened 4 out of 5 times for me. I suspect it's because I am cheating with the income and the generator creates too many flights to separate the frequencies.

We will usually need more information for debugging. Include as much of the following as you are able:

- DCS Liberation save file (the `.liberation` file you save from the DCS Liberation window). By default these are located in your DCS saved games directory (`%USERPROFILE%/Saved Games/DCS`).
- The generated mission file (the `.miz` file that you load in DCS to play the turn). By default these are located in your missions directory (`%USERPROFILE%/Saved Games/DCS/Missions`).
- A tacview track file, especially when demonstrating an issue with AI behavior. By default these are located in your Tacview tracks directory (`%USERPROFILE%/Documents/Tacview`).
- The state.json file from the finished mission when the problem is related to results processing. By default these are located in your Liberation install directory.

**Version information (please complete the following information):**
 - DCS Liberation [e.g. 2.3.1]: v5.0.0

**Additional context**
Add any other context about the problem here

[baltic.zip](https://github.com/dcs-liberation/dcs_liberation/files/7534578/baltic.zip)
.
[liberation_nextturn.zip](https://github.com/dcs-liberation/dcs_liberation/files/7534605/liberation_nextturn.zip)
![error message](https://user-images.githubusercontent.com/94320027/141697612-4f6fd33b-f4b1-48f9-b242-58c261c14f64.jpg)

**Comment by DanAlbert** [comment]
Your game doesn't load in 5.0.0:

```
2021-11-14 12:37:46,885 :: ERROR :: Invalid Save game
Traceback (most recent call last):
  File "C:\Users\dan\src\dcs_liberation\game\persistency.py", line 48, in load_game
    save = pickle.load(f)
  File "C:\Users\dan\src\dcs_liberation\venv\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'game.event.frontlineattack'
```

The AN/ARC-222 data is clearly wrong. I'll fix it, but I can't verify the fix.
