### ISSUE TITLE
DCS Server SCRIPT ERROR 

### ISSUE THREAD

**Issue by Wawar9** [dcs-liberation/dcs_liberation#1748]
**Describe the bug**
DCS Server SCRIPT ERROR when loading a mission with the web GUI, but issue resolved If I load and save the mission in the DCS mission editor before playing it.

**To Reproduce**
Load "liberationnextturn.miz" with DCS Server.

**Additional information**
Script Error happens when I try to load "liberationnextturn.miz" with a dedicated server. I have the issue with "DCS Server" running on the same machine where DCS Main is installed AND I have the same issue with DCS Server on a dedicated machine. (true dedicated server) 

Paths are good, it replaces correctly the "missionscripting.lua", the file is correctly edited. 

There is the error : 
![script error](https://user-images.githubusercontent.com/82789122/141720826-9148702a-e42d-444d-aaa4-fee1e73278ec.png)

.liberation and .miz before and after saving attached.

**Version information (please complete the following information):**
 - DCS Liberation 5.0.0

[Files.zip](https://github.com/dcs-liberation/dcs_liberation/files/7535787/Files.zip)

**Comment by Darren801** [comment]
Having the same problem but doesn't notice the impact on the gameplay.

**Comment by 2FJgSnazzyDuckling** [comment]
I've observed the same behaviour running several different campaigns. Seems consistent and easily reproducible.

**Comment by RedMeKool** [comment]
I have the same issue with my dedicated server

**Comment by RndName** [comment]
fixed with 676a256 / bb1e314
