### ISSUE TITLE
TARCAP generating extraneous NAV point after Refuel waypoint

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#1749]
**Describe the bug**

After refuel waypoint, and extra NAV waypoint (4 NAV in the screenshot) is being generated for TARCAP flights, leading the flight back out to its CAP area.

To replicate for testing, use Exercise Vegas Nerve, with frontline TARCAP taking off from Tonopah Airport. This appears to occur consistently (I planned 6 separate TARCAP flights and it occured on every one of them)

![Capture](https://user-images.githubusercontent.com/72491792/141722830-0a0a47f7-1a33-401a-a03a-9574ef9ff93a.jpg)

**Expected behavior**
Flight should proceed to land after refuel waypoint.

**Version information (please complete the following information):**
 - DCS Liberation [e.g. 2.3.1]: #3055

**Comment by DanAlbert** [comment]
Save game.

**Comment by Starfire13** [comment]
[TARCAP Flight Path Problem.zip](https://github.com/dcs-liberation/dcs_liberation/files/7536081/TARCAP.Flight.Path.Problem.zip)

**Comment by Starfire13** [comment]
After some further testing, I think there might be a (hopefully) easy way around this issue. Instead of placing the refuel waypoint immediately after the racetrack end waypoint, place it just prior to the landing waypoint.

**Comment by Hornet2041** [comment]
That looks like its the normal egress path for a TARCAP but it still trying to refuel in friendly airspace.

**Comment by SnappyComebacks** [comment]
I can't try this for myself at the moment, but would a viable solution to this be to replace the first nav waypoint on the way back from target to home with a refuel waypoint?  I don't remember if the nav waypoints are common to the package or not.

**Comment by Starfire13** [comment]
That is kinda what is causing the problem in the first place. The refuel waypoint is placed right after the target waypoint, but has to be in friendly airspace. So it's quite a ways back. But the nav points that are then generated do not take into account the presence of the refuel waypoint, leading them to plan a route from the target, as if the refuel waypoint didn't exist. Perhaps a better solution is to place the refuel waypoint after any post-target nav waypoints, or better yet, place it just after the split waypoint.

**Comment by DanAlbert** [comment]
> I can't try this for myself at the moment, but would a viable solution to this be to replace the first nav waypoint on the way back from target to home with a refuel waypoint? I don't remember if the nav waypoints are common to the package or not.

That's part of the fix. I suspect https://github.com/dcs-liberation/dcs_liberation/blob/73b7be0606682b7d18fc01f70faae68ea671b167/game/flightplan/refuelzonegeometry.py#L24 needs to be fixed too though.

**Comment by DanAlbert** [comment]
@SnappyComebacks were you planning to look at this? Placing refuel waypoints over threatened areas is a regression in AI flight plans that could be fairly game breaking. I can take a look this weekend, but that TODO might actually be quite hard to fix. If you don't have time to fix it and I don't see an easy fix, we probably need to look for alternate implementations that exclude the AI.

**Comment by SnappyComebacks** [comment]
I won't be able to do anything about it for a bit. Do what you feel needs to be done about it.

I did look into fixing it and was thinking about swapping the first or second navigation point with a refuel point at the time (as refuel points might not need to exist all the time),  but didn't get around to trying it.

**Comment by DanAlbert** [comment]
> If you don't have time to fix it and I don't see an easy fix, we probably need to look for alternate implementations that exclude the AI.

I investigated this a bit and came to the conclusion that what we currently have is probably the best this gets until someone can put the time into building proper placement logic: https://github.com/dcs-liberation/dcs_liberation/issues/2544

The worst part of this (the bad ordering reported in this bug) is fixed though.
