### ISSUE TITLE
Liberation 2.1.3 "Buy planes button not working"

### ISSUE THREAD

**Issue by Pixinger** [dcs-liberation/dcs_liberation#175]
In Liberation 2.1.3 the buttons to buy planes ("plus sign" buttons) are not working. 
The problem happens after a project from "Liberation 2.1.2" is loaded. When creating a new project in "Liberation 2.1.3", the button works as expected. When using the 2.1.2 project with "Liberation 2.1.2" exe, the button also works as expected.

Maybe in some way related to #173 ?

If required, I can upload the problematic project file - just let me know.

**Comment by Khopa** [comment]
Hello Pixinger, 

In Liberation 2.1.3, there is a limit on the number of aircraft that can be bought on a specific airfield. 
Maybe you are over the limit ?

Otherwise, please send your liberation save file.

Thanks, 

Khopa

**Comment by Pixinger** [comment]
I'm not sure if it is the aircraft limit. This might be the case, if there was no limit in 2.1.2., as I am able to increase the number there. To make it easier, I attached the project file. 

BTW, great work Khopa! We really appreciate it!

[Bones_Test1_10Defekt.zip](https://github.com/Khopa/dcs_liberation/files/5321764/Bones_Test1_10Defekt.zip)

Oh, one more thing. The TAKE OFF button also does not work in this file, when using 2.1.3. Don't know if this matters.

**Comment by Khopa** [comment]
![image](https://user-images.githubusercontent.com/2546901/94993908-7ae41a00-0594-11eb-84da-3e076d8784d2.png)

Yes, that's your issue, Fujairah has only 4 parking slots and you already have 6 aircrafts... :/
So it's not possible to host more there, and you already had bought than now possible more in version 2.1.2.

Yes, i have the takeoff issue with your save file as well, we have a fix coming soon for this one.

**Comment by Khopa** [comment]
Issue 2 should be fixed in Release 2.1.4

https://github.com/Khopa/dcs_liberation/releases/tag/2.1.4b

**Comment by Pixinger** [comment]
Thank you for making this clear and sorry for reporting something that is in the end an "user issue". 
Having the screenshot, I feel a little stupid for not seeing the 6/4 earlier.

=> Issue close

**Comment by Khopa** [comment]
Thanks, no problem.
There should be a message saying that you do not have enough slots left on the airport. :)
