### ISSUE TITLE
Flights spawning on top of each other with fast forward.

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#1754]
**Describe the bug**
I have a package with 2 SEAD flights and a DEAD flight (attacking an SA-10 site). My own flight is set to start up at 14 minutes, and since player missions interrupt fast forward is turned on, Liberation automatically fast forwards the mission to that point in time. So, my SEAD and DEAD flights are already airborne when I enter the mission.

However, my 2 SEAD flights pretty much explode instantly in mid air as there are multiple aircaft stacked up on each other. See picture: https://steamuserimages-a.akamaihd.net/ugc/1804249609470138713/69FB6752C2AAE12927C935EB68703E816000CC05/

Here's a screenshot showing the two flights directly on top of each other in the mission editor. I have moved one flight very slightly so you can see that there are in fact 2 flights, not 1.

![Capture](https://user-images.githubusercontent.com/72491792/141775883-eaa0a123-928f-4633-873e-23b5e58eb651.JPG)

Here is my Liberation save file and the .miz.
[Files.zip](https://github.com/dcs-liberation/dcs_liberation/files/7538369/Files.zip)

**Expected behavior**
Aircraft should respect social distancing guidelines.

**Version information (please complete the following information):**
 - DCS Liberation [e.g. 2.3.1]: #3055

**Comment by holyorangejuice** [comment]
Still an issue in 3056

**Comment by DanAlbert** [comment]
That's why it's still open.
