### ISSUE TITLE
Desired Mission Duration Slider - BUG

### ISSUE THREAD

**Issue by holyorangejuice** [dcs-liberation/dcs_liberation#1759]
**Describe the bug**
I was confused about how the Desired Mission Duration Slider worked. I was told on the discord it sets the latest a flight could take off. Setting this to the lowest setting should, in theory, get more red flights in the air, in a shorter period of time. Based on the blue auto tasking it seems setting this to 30, makes the latest TOT around 1 hour long. 

The bug I'm experiencing is changing this slider mid campaign. It seems to break the tasking. My blue flights are auto tasked but I don't have any red air doing tasks.

**To Reproduce**
-I set my current campaign from 60 minutes to 30 minutes
-Launch game and fast forward at 3x for almost 1 hour in game time.
-No enemy air as confirmed by two tacview files

**Expected behavior**
I loaded a brand new campaign and set the slider before hitting begin campaign. It worked fine. A lot more red air tasking was within the 1 hour testing window.

**Additional information**
https://www.dropbox.com/sh/h3b3oa6lcd4588g/AAAdfWdIcFMQvLnie3u9O7zDa?dl=0

Two tacview files of Nevada and the 5.0.0 save file. One tacview file of a fresh campaign showing it working properly.

**Version information (please complete the following information):**
 - DCS Liberation 5.0.0.

**Additional context**
NONE

**Comment by DanAlbert** [comment]
Artifact was deleted. Not possible to investigate. One thing to note is that the slider will not affect the current turn, only future turns.

Not that it really matters for much longer. That slider will be gone when turns are gone.
