### ISSUE TITLE
JF-17 Flights cannot be altered. ERROR: 'DIS_GBU_12_DUAL'

### ISSUE THREAD

**Issue by dasrehzockt** [dcs-liberation/dcs_liberation#1760]
Describe the bug
The dialogue to alter generated JF-17 flights does not open. The following Error appears instead:

```
'DIS_GBU_12_DUAL'

Traceback (most recent call last):
  File "widgets\ato.py", line 119, in on_double_click
  File "widgets\ato.py", line 124, in edit_flight
  File "dialogs.py", line 57, in open_edit_flight_dialog
  File "windows\mission\QEditFlightDialog.py", line 33, in __init__
  File "windows\mission\flight\QFlightPlanner.py", line 20, in __init__
  File "windows\mission\flight\payload\QFlightPayloadTab.py", line 39, in __init__
  File "windows\mission\flight\payload\QFlightPayloadTab.py", line 13, in __init__
  File "gen\flights\loadouts.py", line 120, in iter_for
  File "gen\flights\loadouts.py", line 120, in <dictcomp>
  File "game\data\weapons.py", line 73, in with_clsid
KeyError: 'DIS_GBU_12_DUAL'
```

To Reproduce

    Double click auto generated JF-17 flight.

Expected behavior
the window opens.

Additional information
i don't know how to attach my save since only images are accepted. but this does not seem to be affected by a savegame, it is consistent with any campaign i am starting, independet of what faction or map i am using.
This bug prevents me from making certain flights player/AI controlled or from changing loadouts.

Version information (please complete the following information):
v5.0.0-3022 & 5.0.1-3051

**Comment by DanAlbert** [comment]
> i don't know how to attach my save since only images are accepted.

rename it .txt and drag and drop.

**Comment by dasrehzockt** [comment]
[autosave.liberation.txt](https://github.com/dcs-liberation/dcs_liberation/files/7559109/autosave.liberation.txt)

**Comment by Mustang-25** [comment]
Checking with PyDCS, it looks like that clsid was changed to `DIS_GBU_12_DUAL_GDJ_II19_L` and `DIS_GBU_12_DUAL_GDJ_II19_R`

**Comment by Mustang-25** [comment]
Actually, I just looked at GBU-12-2X.yaml and it looks like the "{" and "}" are missing from the DIS_GBU entries. Could that be the problem? 

Also, I noticed that that BRU-42 entries don't seem to exist in PyDCS either. I'm guessing it was changed since that file was last updated in July.

**Comment by DanAlbert** [comment]
Any of the above would make sense. DCS does sometimes remove weapon IDs, and adds new ones often.

**Comment by DanAlbert** [comment]
Liberation doesn't include a loadout that uses `DIS_GBU_12_DUAL`. I think this is an old loadout of yours that was broken by a DCS update. Unless that becomes common, I don't think it's a good idea to skip old incompatible loadouts since that will lead to confusion when users can't figure out why their loadouts won't show up in Liberation.
