### ISSUE TITLE
Preview 3056 - AWACs set to land

### ISSUE THREAD

**Issue by holyorangejuice** [dcs-liberation/dcs_liberation#1765]
**Describe the bug**
I start the mission at first contact. AI AWACs is set to land with no orbit waypoint in the mission editor. I believe this is a bug. The AWACs just lands instead of loitering.

**Version information (please complete the following information):**
 - DCS Liberation [e.g. 2.3.1]: 3056 build

**Comment by Starfire13** [comment]
There is no build 3065. The latest build is 3056.

My AWACs is orbiting fine on #3055. See screenshot.

![Capture](https://user-images.githubusercontent.com/72491792/142497056-498172e6-61ec-41e9-ac36-eac9fe4c5ca7.JPG)

Please include your save file (.liberation and .miz).
