### ISSUE TITLE
Plane F-16C_50 has no pylon 10.

### ISSUE THREAD

**Issue by JEEPnHoop** [dcs-liberation/dcs_liberation#1768]
**Describe the bug**
When going to launch mission with a F-16 as any part of the mission, get an error about pylon 10... assuming this has to do with the recent DCS Viper update adding the HAS in.

**To Reproduce**
So far, have had this error pop up with an F 16 as either player or AI

**Version information (please complete the following information):**
 - DCS Liberation [5.0A]:

**Additional context**
![image](https://user-images.githubusercontent.com/94661671/142555953-cbe33dcf-4996-45a6-9c25-b062fcfd8014.png)

**Comment by Starfire13** [comment]
Yes, pylon 10 is for the HTS pod, and is not available in Liberation yet. You will have to wait for an update to use it.
