### ISSUE TITLE
log an error when starting with non-ASCII characters in the path

### ISSUE THREAD

**Issue by lukaszgemborowski** [dcs-liberation/dcs_liberation#1774]
**Describe the bug**
After extracting dcs liberation directly to my desktop, executable won't start. It closes right after the splash screen without any message. There's nothing in the log, the last print is just a path to saved games and dcs installation directory, log ends. After moving the dcs_liberation folder to a different location it is able to start. My username, therefore path to desktop, contains letter ["Ł"](https://en.wikipedia.org/wiki/%C5%81).

**To Reproduce**
1. rename dcs_liberation directory to contain letter Ł (upper or lower case, does not matter)
2. start dcs_liberation.exe

**Expected behavior**
Executable will start.

**Additional information**
N/A

**Version information (please complete the following information):**
 - DCS Liberation 5.0.0

**Additional context**
N/A

**Comment by Hornet2041** [comment]
https://github.com/dcs-liberation/dcs_liberation/issues/1265

thought I'd seen this bug earlier somewhere

**Comment by lukaszgemborowski** [comment]
I haven't seen the "Could not find QTWebEngineProcess.exe" neither in the log nor in the stdout/stderr in my case. But the symptoms looks the same.

I was trying to search for similar open issues but I couldn't find anything, if it's duplicate go ahead and close the issue.

**Comment by RndName** [comment]
Maybe we have to handle more strings with utf8 (like https://github.com/dcs-liberation/dcs_liberation/pull/1538 ) or it’s a simple escape of special characters in some variables.

**Comment by DanAlbert** [comment]
Windows file names are actually UTF-16 rather than UTF-8. I have no idea if that's related to this problem, but it would not be the first time I saw software that was written for Linux (in this case, not liberation, but definitely all of our dependencies) fail with non-ascii characters in paths because they expect any non-ASCII paths to be UTF-8.

**Comment by lukaszgemborowski** [comment]
>  I saw software that was written for Linux (in this case, not liberation, but definitely all of our dependencies) fail with non-ascii characters 

I saw software written for windows not handling non-ascii characters properly (first releases of **Microsoft** Flight Simulator 2020 for example :D). Unfortunately I don't have much knowledge about Windows/NTFS to help here. But if the bug is complex to address, maybe you can detect that there're non-ascii characters in the path and at least display some kind of warning message box to the user?

**Comment by DanAlbert** [comment]
We should probably do that and display a warning even if we do fix this particular issue. IME problems like this are often whack-a-mole. Fixing one just means you can find the next ten. "Hey, we think this works, but i18n is hard, so install somewhere else and file a bug if it doesn't" would save folks some time if there are more problems.

**Comment by lukaszgemborowski** [comment]
Agree. I personally spent like an hour figuring out why this app won't start. A simple popup would save me this time and maybe it would save a "new user" from completely abandoning the liberation altogether (or spamming the issue tracker).

**Comment by DanAlbert** [comment]
@Raskil did some investigation and this seems that Qt is the thing that doesn't handle this well, which isn't something we can fix. [We are working on moving off Qt though](https://github.com/dcs-liberation/dcs_liberation/issues/2067), so this won't be around forever. It doesn't mean that this is going to take a while though, but @Raskil is going to add a log message that'll at least tell you what went wrong.
