### ISSUE TITLE
Builds #3069 to #3080 will not run

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#1783]
**Describe the bug**
This error ocurs when starting up builds #3069 to #3080. #3066 is fine.

![Capture](https://user-images.githubusercontent.com/72491792/142785968-0d4ee7cd-c844-4dda-b279-bb775f9864a7.JPG)

**Comment by DanAlbert** [comment]
Fixed by https://github.com/dcs-liberation/dcs_liberation/commit/9e92c8735123d362e90b6034901f38052af70b37
