### ISSUE TITLE
Flight start time mismatch

### ISSUE THREAD

**Issue by Meyomyx** [dcs-liberation/dcs_liberation#1788]
The scenario starts at 1400 with my flight departing in about 26 minutes. I wait a while until my flight is spawned on the carrier. However, looking at the panel clock, the time remains at 14:00.

Keep up the great work - would welcome some easier scenarios. I seem to get overwhelmed/shot down very early on in most campaigns!

![1a](https://user-images.githubusercontent.com/70166005/143002369-4d2b0c5b-cccc-40b3-9c47-0a94f832ecaa.jpg)

![2](https://user-images.githubusercontent.com/70166005/143002402-093b3656-e0a8-4457-a4f2-2e7ee58a30d7.jpg)

![3](https://user-images.githubusercontent.com/70166005/143002423-a251cc27-82d3-48c4-9ecd-aedf6cd48300.jpg)

**Comment by Hornet2041** [comment]
i'm confused what the issue is here. does the in-game clock spawn you at 1400? or it waits correctly until 1426? 

The Liberation clock won't change until you pass turns in 5.0.

**Comment by Meyomyx** [comment]
I start the turn. The clock (in F2 views) starts at 1400. I wait for some 15-20 mins until my aircraft spawns. F2 views show the correct elapsed time but the clock in the newly spawned aircraft shows 1400 - and I have 38 minutes to wait for my departure time.

**Comment by Meyomyx** [comment]
As you say … the clock should read 1626 when it spawns in

**Comment by DanAlbert** [comment]
If the clock in DCS UI and the clock in the aircraft don't match that's on DCS. We don't (and can't) set the clock.
