### ISSUE TITLE
Names with apostrophes cause scripting errors

### ISSUE THREAD

**Issue by Ren0k** [dcs-liberation/dcs_liberation#1797]
## Description
This bug refers specifically to names of airbases, but will due to the nature of the issue likely translate to other names that are used as a string in the scripting environment.
If the name of the airbase/object used as a string contains an apostrophe, it will produce a mission scripting error.
For example, see **Tha'lah** airbase in the Syria map.

## To Reproduce
1. Create a liberation campaign in the Syrian theatre
2. Create a AEW&C package originating from **Tha'lah** airbase and export the mission to DCS
3. In the mission editor, in the trigger section, go to the trigger called 'Set DCS Liberation data'
4. Note here how the section **-- list the AWACs generated by Liberation** contains the created AEW&C package called something similar to ```{dcsGroupName='Tha'lah AEW&C|81|42|7|A-50|', callsign='Overlord', radio='253.0' }```
5. Launch the mission

## Expected Behaviour
Upon launching the mission, expect to receive the error ```SCRIPTING: Mission script error: [string "..."]:24: '}' expected near 'lah'```. Several modules and LUA plugin will not work if you continue the mission.
This error makes sense as the line in point 4 of the section above, contains an unclosed string.
If I manually correct the error by changing ```'Tha'lah``` into ```'Thalah``` the error message will not appear.

## Additional Information
As the mechanics of the issue are more obvious than other more complex bugs, I skip providing any saves files for now. But if this seems helpful to resolve the issue I will add them later.
- **DCS Liberation [5.0.0]**

**Comment by RndName** [comment]
I am currently refactoring the lua generation with #324 
I think the best way to prevent future issues is not to handle the special characters. Instead escape them directly during generation of the dcs unit for the miz during mission generation routine. Then use the escaped value for the Lua and we don’t have to take care for everything afterwards.

**Comment by DanAlbert** [comment]
> Instead escape them directly during generation of the dcs unit for the miz during mission generation routine. 

Do you mean escape the name before we pass it to pydcs? Unless pydcs has its own bugs with escaping, that'll double escape, so the names wouldn't show right in DCS, I think.

**Comment by RndName** [comment]
I will try to first escape the single quote with `\' ` which is used as the string delimiter in all our lua strings and therefore causes this bug.
If this doesn’t work we can discuss if changing the unit name is a bad thing. I think it’s easier to prevent using these special characters in the first place but maybe it is just this quote which messes things up. Lua itself supports utf8 so this does not brake it.

**Comment by RndName** [comment]
> As the mechanics of the issue are more obvious than other more complex bugs, I skip providing any saves files for now. But if this seems helpful to resolve the issue I will add them later.

@Ren0k I was not able to find a supported campaign with `Tha'lah` airbase. As it's the only airbase in dcs which has the `'` in the name i now understand why this problem never showed off before.
Could you share your safe to reproduce it without spending more time building a campaign for it?

**Comment by RndName** [comment]
nvm, was able to reproduce it. this will be resolved with the new lua generation in #1839
Single quotes will be replaced with double quotes to allow the usage of the single quote in the dcsGroupName

**Comment by Ren0k** [comment]
> nvm, was able to reproduce it. this will be resolved with the new lua generation in #1839 Single quotes will be replaced with double quotes to allow the usage of the single quote in the dcsGroupName

 My apology for not responding to your request sooner. I'm glad to hear that you were able to reproduce it without an included save file, much appreciated.

**Comment by RndName** [comment]
solved with 138e48dc2d0d5b52c591e4dbd711dbc6b01d3f56 in develop branch
