### ISSUE TITLE
[Bug?] Last waypoint is not of type LANDING

### ISSUE THREAD

**Issue by davidp57** [dcs-liberation/dcs_liberation#180]
The name of the waypoint is LANDING but it is still a turning point...

![2020-10-03 20_07_10-Window](https://user-images.githubusercontent.com/172286/94998694-20f34c80-05b4-11eb-85b0-15a2a35e6af2.jpg)

**Comment by Khopa** [comment]
Oh good catch.  
That might explain some AI issues we had.. 😁 

Fixed here : https://github.com/Khopa/dcs_liberation/commit/1f240b02f4d62f427d06d210f009f89da0801f0e

**Comment by Khopa** [comment]
Fixed in 2.1.5 Release

https://github.com/Khopa/dcs_liberation/releases/tag/2.1.5
