### ISSUE TITLE
[Bug?] Callsigns are always redfor-style

### ISSUE THREAD

**Issue by davidp57** [dcs-liberation/dcs_liberation#181]
The callsigns generated for the blufor units are always redfor-style.
E.g., the tanker is named "100" instead of "Texaco11".

I suspect that it is due to the change from USA to CombinedJointTaskForcesBlue.

I traced this error up to the Mission._assign_callsign method, where this code : 
```python
        if category in _country.callsign:
            callsign_name = _country.next_callsign_category(category)
```
tests for existing callsigns in the country.
I think that this new "country" (CombinedJointTaskForcesBlue) has no defined callsigns, but I'm not able to find out more.
@Khopa, any idea ?

**Comment by davidp57** [comment]
@DanAlbert , @Khopa , did you see this ?
I could spend more time hunting, although I think you'd do the same in a millionth of the time ;)

**Comment by DanAlbert** [comment]
> I think that this new "country" (CombinedJointTaskForcesBlue) has no defined callsigns, but I'm not able to find out more.
@Khopa, any idea ?

Had missed this part before. That'll be it. See the comments in https://github.com/pydcs/dcs/blob/c203e5a1b8d5eb42d559dab074e668bf37fa5158/dcs/flyingunit.py#L152-L180

Basically, pydcs is just dumping the _tables_ in db_callnames.lua, but allowed callnames are partially implemented by a function, so dumping the tables gives incomplete information. It looks like only a very small number of nations have working aircraft callsigns in pydcs (basically just US and Russia, although the UK and France at least have AWACS names).

DCS is actually smart enough to fix them when the mission loads, but our kneeboards are indeed broken.

https://github.com/pydcs/dcs/pull/80 fixes it, and https://github.com/Khopa/dcs/pull/3 fixes @Khopa's fork, which I think is what we're currently using.

**Comment by davidp57** [comment]
Thanks, I'll test and report.

**Comment by DanAlbert** [comment]
Fix was merged into pydcs and we've pulled it into develop.
