### ISSUE TITLE
Selecting edit of Harrier unit, I get the following error :  '{BRU-42_3*MK-20}'

### ISSUE THREAD

**Issue by Oesau** [dcs-liberation/dcs_liberation#1810]
Before filing, please search the issue tracker to see if the issue has already been reported.

If reporting a DCS AI bug, check https://github.com/dcs-liberation/dcs_liberation#dcs-bugs.

**Describe the bug**
Whenever edit Harrier unit, I get the following error :

***'{BRU-42_3*MK-20}'

Traceback (most recent call last):
File "widgets\ato.py", line 140, in
File "widgets\ato.py", line 124, in edit_flight
File "dialogs.py", line 57, in open_edit_flight_dialog
File "windows\mission\QEditFlightDialog.py", line 33, in init
File "windows\mission\flight\QFlightPlanner.py", line 20, in init
File "windows\mission\flight\payload\QFlightPayloadTab.py", line 39, in init
File "windows\mission\flight\payload\QFlightPayloadTab.py", line 13, in init
File "gen\flights\loadouts.py", line 120, in iter_for
File "gen\flights\loadouts.py", line 120, in
File "game\data\weapons.py", line 73, in with_clsid
KeyError: '{BRU-42_3*MK-20}'****

**To Reproduce**
1. Go to zip file, load mission "Marianas Island Attack"
2. Scroll down to and click on the 'DEAD Herring Package'
3. from the Flights window, right click and select edit

**Expected behavior**
Expect to see the edit flight window appear

**Additional information**

We will usually need more information for debugging. Include as much of the following as you are able:

- DCS Liberation save file (the `.liberation` file you save from the DCS Liberation window). By default these are located in your DCS saved games directory (`%USERPROFILE%/Saved Games/DCS`).
- The generated mission file (the `.miz` file that you load in DCS to play the turn). By default these are located in your missions directory (`%USERPROFILE%/Saved Games/DCS/Missions`).
- A tacview track file, especially when demonstrating an issue with AI behavior. By default these are located in your Tacview tracks directory (`%USERPROFILE%/Documents/Tacview`).
- The state.json file from the finished mission when the problem is related to results processing. By default these are located in your Liberation install directory.

**Version information (please complete the following information):**
 - DCS Liberation 5.5.0

**Additional context**
Add any other context about the problem here
[Marianas Island Attack.zip](https://github.com/dcs-liberation/dcs_liberation/files/7610855/Marianas.Island.Attack.zip)
.

**Comment by Mustang-25** [comment]
Looking in PyDCS (and also in DCS itself), the 3x rockeye loadout has been entirely removed from the Harrier. I'm not sure where I'd need to edit to remove that clsid from Liberation though.

**Comment by Oesau** [comment]
> Looking in PyDCS (and also in DCS itself), the 3x rockeye loadout has been entirely removed from the Harrier. I'm not sure where I'd need to edit to remove that clsid from Liberation though.

Good call out @Mustang-25 - this is probably the root cause of the issue

**Comment by Hornet2041** [comment]
check your loadout files for the Harrier in the dcs mission editor to make sure a triple rockeye isn't actually part of any of them. Custom/modded payloads will still mess with Liberation - the Harrier can't normally triple-rack Rockeyes.

**Comment by Oesau** [comment]
> check your loadout files for the Harrier in the dcs mission editor to make sure a triple rockeye isn't actually part of any of them. Custom/modded payloads will still mess with Liberation - the Harrier can't normally triple-rack Rockeyes.

Thanks for the lead on that - I've checked  but I don't have that as a custom loadout option

**Comment by DanAlbert** [comment]
Working fine for me in 5.1.0:
![image](https://user-images.githubusercontent.com/315852/150896032-b4e8a0c2-2628-4651-800e-851737c236b6.png)
