### ISSUE TITLE
Mi-8, Mig19 and Mig15 does not produce squadrons

### ISSUE THREAD

**Issue by Eagle01ph** [dcs-liberation/dcs_liberation#1814]
Before filing, please search the issue tracker to see if the issue has already been reported.

If reporting a DCS AI bug, check https://github.com/dcs-liberation/dcs_liberation#dcs-bugs.

**Describe the bug**
The Mi-8, Mig 19 and Mig 15 doesn't produce squadrons

**To Reproduce**
1.Create a new campaign 
2.Select Syria - "Battle for Golan Heights"
3.Invert the map
4.Select Syria 1973 faction for blue, and any faction for red
5.The sqaudron setup for blue would only have the Mig21 and Fitter.  The Mi8, Mig19 and Mig15 have no squadrons and couldn't be bought.

**Version information (please complete the following information):**
 - DCS Liberation 5.0.0:

**Comment by Starfire13** [comment]
https://github.com/dcs-liberation/dcs_liberation/issues/1744

Also, if you invert a map, your squadrons are going to get all randomised and you might get non-optimal aircraft.
