### ISSUE TITLE
AI don't take off from airfield, Syria.

### ISSUE THREAD

**Issue by TheIrishAce** [dcs-liberation/dcs_liberation#182]
Currently have a problem with AI flights not taking off from the beginning airfield on Syria(Full Map). They sit ready to taxi but never take off.
![20201004024216_1](https://user-images.githubusercontent.com/35999336/95005103-b6f69980-05eb-11eb-98f1-ff8d40e549c6.jpg)

**Comment by DanAlbert** [comment]
Is this still a problem? What airfield? Please upload the mission file if it's still a problem, because I don't think anyone else has seen this.

**Comment by Khopa** [comment]
I believe this was resolved in the latest DCS open beta version.
It was an issue with the map.

See the changelog : 

![image](https://user-images.githubusercontent.com/2546901/98442944-70bfb900-2108-11eb-8fbb-79398f8fd609.png)
