### ISSUE TITLE
Campaign version non-string fix

### ISSUE THREAD

**Issue by sgtfuzzle17** [dcs-liberation/dcs_liberation#1821]
Small update for all of my campaigns to fix a small formatting error in the campaign.yaml files where campaign version was in place without quotations, leading to an error in logs
[campaigns.zip](https://github.com/dcs-liberation/dcs_liberation/files/7629531/campaigns.zip)

**Comment by RndName** [comment]
@sgtfuzzle17

was this change in the screenshot intended (pacific_repartee)

![grafik](https://user-images.githubusercontent.com/6678803/145449791-65a6c5b1-d88f-40b0-a94b-98d57e2e80d5.png)

**Comment by sgtfuzzle17** [comment]
No it was not, I can’t recall making this edit but apparently I have. Would it be possible for you/one of the devs to fix that up so we don’t need to bother with me submitting fix files/you guys implementing them?
