### ISSUE TITLE
[Feature request] Base qty./affiliation customization

### ISSUE THREAD

**Issue by BigBoss329** [dcs-liberation/dcs_liberation#183]
It would be nice if you could implement the option to allow the player to preselect the amount of bases per faction, and set which belongs to whom. 
At the moment, if I generate a campaign on the west side of the Caucasus, Russia only has 2 airbases, while NATO has 4, giving them unfair advantage, making the campaign way too easy for bluefor. If I generate a full map campaign, Russia has a lot more bases on the western side of the map, but the performance tanks, due to the large amount of units present on the two front lines.

**Comment by DanAlbert** [comment]
In 2.2 you can modify the campaign setup.
