### ISSUE TITLE
Editing flight error in 5.0.0

### ISSUE THREAD

**Issue by zbenesch** [dcs-liberation/dcs_liberation#1831]
![image](https://user-images.githubusercontent.com/31964331/145399357-29cdb6ee-0ebc-4305-9e44-c47dd8bf8929.png)

**Describe the bug**
Trying to edit any unit brings up error.

**To Reproduce**
1. Go to new campaign
2. Click on start
3. double click on any unit to edit loadout, etc and this error appears

**Expected behavior**
Loadout window appears

**Additional information**
Creating new packages and trying to edit the flights/units in them results in the same error.

**Comment by Starfire13** [comment]
Please provide save file (zip it and attach) and state what version of Liberation you are on.

**Comment by zbenesch** [comment]
Hi, version is 5.0.0 as stated in the title.
Please find the zip attached.
[marianas.zip](https://github.com/dcs-liberation/dcs_liberation/files/7685286/marianas.zip)

**Comment by Starfire13** [comment]
Your save file is working fine on my end. I suggest you reinstall Liberation because you have quite possibly corrupted some file somewhere while editing stuff.

![Capture](https://user-images.githubusercontent.com/72491792/145407972-6c42f02e-2117-44a9-b6db-69524b8ce529.JPG)

**Comment by zbenesch** [comment]
I deleted and redownloaded it. First it produced the same error.
Did it again.
Now it works.
 ¯\_(ツ)_/¯
 
 
 Thanks for the help, please close this issue.

**Comment by Starfire13** [comment]
Glad you got it working! :)
