### ISSUE TITLE
Autopurchaser should not buy aircraft when there aren't enough pilots to fly them

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#1832]
**Is your feature request related to a problem? Please describe.**
At the moment, the autoplanner will purchase aircraft that it can task, without checking if there are enough pilots to fly them.

**Describe the solution you'd like**
Autoplanner should take pilot count into account when purchasing aircraft.

**Comment by MetalStormGhost** [comment]
I tried to reproduce this, but have been unsuccessful so far. Steps taken:

1. Start Liberation, latest dev build
2. Start new campaign (I used Allied Sword)
3. Configure low starting funds so turn 0 purchases don't happen before pilot limits take effect
4. Set pilot limits to 12
5. Pass turn several times, notice that none of the squadrons have bought more than 12 aircraft

There exists the following evaluation in the code:
```
    def best_squadrons_for(
        self, request: AircraftProcurementRequest
    ) -> Iterator[Squadron]:
        threatened = []
        for squadron in self.air_wing.best_squadrons_for(
            request.near, request.task_capability, request.number, this_turn=False
        ):
            if not squadron.can_provide_pilots(request.number):
                continue
```

**Comment by MetalStormGhost** [comment]
I was able to reproduce the problem with the Scenic Route campaign. This leads me to believe this is somehow task dependent.

**Comment by DanAlbert** [comment]
This is the biggest reason that feature still has a "WIP" label on it, btw :)
