### ISSUE TITLE
F-16 ECM pod support for next release

### ISSUE THREAD

**Issue by MetalStormGhost** [dcs-liberation/dcs_liberation#1836]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
The F-16 ECM pod will be released in the next Open Beta. In case an interim release is made before 6.0.0, the F-16 ECM pod should be included.

**Additional context**
![image](https://user-images.githubusercontent.com/89945461/145634312-2ee95d4e-35cd-45a1-bca4-416500ab21d8.png)
https://www.digitalcombatsimulator.com/en/news/newsletters/345a4089f1222f5f84a152683a2c1544/

**Comment by DanAlbert** [comment]
Was done ages ago.
