### ISSUE TITLE
Ability to adjust AI & Non-AI Waypoint altitudes

### ISSUE THREAD

**Issue by DevastatorCM** [dcs-liberation/dcs_liberation#1840]
**Is your feature request related to a problem? Please describe.**
It can create potential problems in high mountain regions or where other flights are using same alt.  It would be good to adjust any WP's alt.

**Describe the solution you'd like**
being able to adjust the alt. over the "waypoints" tab of the flight

**Additional context**

**Comment by RndName** [comment]
#1307
