### ISSUE TITLE
6.0 3105 - Cull Zone Bug

### ISSUE THREAD

**Issue by holyorangejuice** [dcs-liberation/dcs_liberation#1842]
Before filing, please search the issue tracker to see if the issue has already been reported.

If reporting a DCS AI bug, check https://github.com/dcs-liberation/dcs_liberation#dcs-bugs.

**Describe the bug**
SA-6 site was outside of a cull zone so it should not spawn in. I created a target for it, which should make it spawn in, even outside of a cull zone. The SA-6 site did spawn in and we destroyed it. Submitting the JSON file manually and the SA-6 site did not register any hits in liberation. All other targets inside cull zones registered hits such as a SA-3 site that was in a cull zone. 

**To Reproduce**
Build 6.0 3105 - Make sure a target is outside a cull zone
-Make that a target so it spawns in anyway
-Destroy target
-Manually submit your JSON file (in our case we use a dedicated server for missions and manually submit json files on our game machines)
-Target not destroyed or registering damage

**Expected behavior**
SA-6 site should have been destroyed.

**Additional information**

We will usually need more information for debugging. Include as much of the following as you are able:
https://www.dropbox.com/sh/i86ifie8o573x52/AAC-WoNGsU7OD4LnhvDkkSsCa?dl=0
-json file and game save after json file submitted

**Version information (please complete the following information):**
Build 6.0 3105

**Comment by DanAlbert** [comment]
Artifact was deleted. Not possible to investigate.
