### ISSUE TITLE
Start up times in Flight pane stop updating after Control Point window is opened

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#1844]
**Describe the bug**
After planning a flight, it shows up in the Flight pane like this:
![Capture1](https://user-images.githubusercontent.com/72491792/145939580-0402cdff-e639-4909-b8c7-349d67c303c4.JPG)

Once any control point is clicked on, the times update to show the actual hour, like this:
![Capture2](https://user-images.githubusercontent.com/72491792/145939617-b5487437-a9e2-4806-9dfb-2c42d3c22ac6.JPG)

That change isn't the issue, though. The issue is that once the time format switches, it will no longer update the start time if you then change the TOT, until you save and reload.

**Expected behavior**
Start times should always update when you change TOT.

**Additional information**

**Version information (please complete the following information):**
 - #3107

**Comment by DanAlbert** [comment]
> it will no longer update the start time if you then change the TOT

There's no expectation that this works. Any modification whatsoever after pushing play is not supported yet.

**Comment by Starfire13** [comment]
What does "pushing play" even mean. You're saying that we shouldn't be opening up any Control Point windows while setting up our flights? That makes zero sense...

**Comment by DanAlbert** [comment]
> What does "pushing play" even mean.

The first time each turn that you unpause.

> You're saying that we shouldn't be opening up any Control Point windows while setting up our flights? That makes zero sense...

The feature isn't done yet. Any modifications made after unpausing are not expected to work until the feature is done.

**Comment by Starfire13** [comment]
But no unpausing has happened. All I've done is click on a control point. Right now, every time I open up a control point window, I have to save and reload.

**Comment by DanAlbert** [comment]
Oh wait, wat. Sorry, the change in time format is something that is expected to happen once the game unpauses, so I thought that happened here. Seems something is initializing all that state ahead of schedule?

**Comment by Starfire13** [comment]
Yes, it's happening any time I click on any of the carriers/airfields/FOBs. Basically, any time a control point's window is opened, the time stops updating.
