### ISSUE TITLE
Ability to remove vehicle types

### ISSUE THREAD

**Issue by DevastatorCM** [dcs-liberation/dcs_liberation#1849]
**Is your feature request related to a problem? Please describe.**
Some of the vehicles which a faction has, causes the AI to spend money on less effective vehicles and lowers the difficulty through campaign

**Describe the solution you'd like**
Ability to adjust the faction via simple clicks at campaign generation screen where each possible units are shown for air and land forces.
I.e. If a player does not want MIG-29s to be used by AI, although it is defined in faction of Russia checkboxes next to each vehicle can be used to turn them off.

**Additional context**
N/A

**Comment by DanAlbert** [comment]
Duplicate of #789
