### ISSUE TITLE
Suspicious AI purchase decisions 

### ISSUE THREAD

**Issue by DevastatorCM** [dcs-liberation/dcs_liberation#1850]
Before filing, please search the issue tracker to see if the issue has already been reported.

If reporting a DCS AI bug, check https://github.com/dcs-liberation/dcs_liberation#dcs-bugs.

**Describe the bug**
AI is spending money on unnecessary aircrafts which does not help the AI at all.  At the moment by a Caucasus campaign Russia (AI) decided to spend all his money by L-39 Albatros which does simply nothing compared to all other possible aircrafts in its inventory.
I.e. in Mozdok, they have 27 L-39, 2 Su-25 and 2 Su-33 which made the A/A missions a slaughter house...

**To Reproduce**
Hard to say how to reproduce as it is not simply click click issue but more a campaign time frame issue

**Expected behavior**
AI might be enhanced so that it can recognize what causes the most of the trouble for him. i.e. if the player airforces is dominating, AI should invest on reparing SAMs, buying air superioty aircrafts. If player landforces is the trouble, then land vehicles and CAS capable aircrafts. On top of this it should be able to understand which aircraft has the worst kill death ratio during the campaign and stop prefering that aircraft over others maybe.

**Additional information**

We will usually need more information for debugging. Include as much of the following as you are able:

**Version information (please complete the following information):**
 - DCS Liberation [e.g. 5.0.0]:

**Additional context**
N/A

**Comment by DanAlbert** [comment]
Nothing to investigate without a save game. AI purchase behavior is heavily dependent on campaign and faction selection, and that info isn't here.

_Always_ upload a save game with bug reports. We usually can't do anything without them.

**Comment by DevastatorCM** [comment]
[save game.zip](https://github.com/dcs-liberation/dcs_liberation/files/7730034/save.game.zip)

**Comment by DanAlbert** [comment]
> DCS Liberation [e.g. 5.0.0]:

We need this too. _Please_ fill out bug templates. If we have to guess it takes a lot longer.
