### ISSUE TITLE
Only count aircraft flagged as "kill" in casualty report

### ISSUE THREAD

**Issue by Roosterfeet** [dcs-liberation/dcs_liberation#1851]
AI frequently run out of fuel due to poor DCS AI. This is a particularly bad problem for carrier based aircraft. 

Losses due to poor ai fuel management and refueling might be addressed by adding an option to only count destroyed aircraft that are flagged as being "killed" in the Liberation casualty report. Aircraft destroyed by other means would be available for the next mission.

**Comment by Starfire13** [comment]
Liberation tracks kills. The data Liberation reads doesn't provide the source of the kills, so there is no way to tell the difference.
