### ISSUE TITLE
JTAC doesn´t respond to radio calls at all

### ISSUE THREAD

**Issue by Goliathus-21** [dcs-liberation/dcs_liberation#1853]
**Describe the bug**
I can´t get in contact with JTAC via RADIO at all, JTAC never responds to my calls. I tripple checked everything and I can´t find out why. In my  kneeboard I can see that the preset frequency is for example on my COMM2, CH4, 227.000 AM, but the JTAC ignores me on this frequency. I checked the mission editor and I found out, that the true frequency of the JTAC is different (for example 251.000 AM), but JTAC still doesn´t respond to my calls even if I change the frequency to the one I saw in the mission editor.

**To Reproduce**
This supposed bug is very easy to reproduce - this issue happens everytime I try to contact JTAC (I fly the F/A18C only). At the moment the (9-line) JTAC seems not to work at all and I can only use the autolase JTAC function and MGRS coordinates I see in the JTAC pop-up window.

**Expected behavior**
I´d appreciate if the JTAC could respond to my radio calls and give me targets and coordinations via radio, just for the better immersion.

Thx.

**Comment by DanAlbert** [comment]
No save, no miz. Will reopen if we get those (at least the save, both preferred)

**Comment by Goliathus-21** [comment]
Sorry DanAlbert for opening uncomplete report.

I attach the .miz file with some screenshots of kneeboard with JTAC freq, as well as from the ME, where you can see differences.

I wasn´t able to make a video from the gameplay, I can attach only track made by the DCS itself. As you can see, I only started right engine, just make the radio powered, but the very same results come even if I get airborne the proper way.

I can be of any help with this solving this issue, just please let me know.

The .miz and track files are in the ZIP folder, cause it seems like there is no other way to attach them.

![JTAC Enfield Freq 251 000 AM](https://user-images.githubusercontent.com/84329357/146655341-ba12f3e4-2b31-4b7f-97bf-d5c984468453.jpg)
![JTAC Enfield Freq in ME](https://user-images.github
[JTAC.zip](https://github.com/dcs-liberation/dcs_liberation/files/7739950/JTAC.zip)
usercontent.com/84329357/146655342-4c39251c-8d66-46ff-8f8f-e6c19dbf92e6.jpg)
![JTAC Springfield freq in ME](https://user-images.githubusercontent.com/84329357/146655343-36063912-d5d6-42b6-be00-1a9b9b32170e.jpg)
![JTAC Freq in Kneeboard](https://user-images.githubusercontent.com/84329357/146655344-930c0c23-f121-4a47-8c5b-d319997a6b45.jpg)
![JTAC Enfield CH4](https://user-images.githubusercontent.com/84329357/146655345-ac76cadf-cdac-4ee4-8f15-484884ba6b46.jpg)
.

**Comment by DanAlbert** [comment]
Still no save game. We need a save game.

**Comment by Goliathus-21** [comment]
[Syria.zip](https://github.com/dcs-liberation/dcs_liberation/files/7740044/Syria.zip)

Oh, so this is what you need? /facepalm/

**Comment by Hornet2041** [comment]
The JTAC radios are on FM, not AM. Just press the UFC button next to AM to switch to FM and it will work.

![jtac1](https://user-images.githubusercontent.com/55866858/146841556-40ad3d4d-9298-403e-b2c1-6ba4d829609b.jpg)

![jtac2](https://user-images.githubusercontent.com/55866858/146841617-b7edb308-b607-4795-9b8c-c6bbc9914d2b.jpg)

**Comment by Hornet2041** [comment]
there *could* be a small enhancement to the kneeboard to specify which modulation the frequencies are on, but other than that this is user error

for the record, the kneeboard frequences are correct, ignore what the box says in the mission editor - the real JTAC action happens in the advanced waypoint options

**Comment by DanAlbert** [comment]
Would AM by default be a better choice? Is that even a choice? idr what the task allows, but if it allows us to put the JTAC on AM by default, that is the default for most if not all of the UHF radios in DCS (I think), and because of how our radio alloc works we do know that it'll always be UHF.

**Comment by Hornet2041** [comment]
probably, yeah. that would fix this --> https://github.com/dcs-liberation/dcs_liberation/issues/1847
I just tested it and the JTAC will transmit on AM

**Comment by Goliathus-21** [comment]
Thank you guys, I had no idea I should switch to FM while talking to JTAC.

I really appreciate your work. DCS without Liberation wouldn't make any sense to me anymore.
