### ISSUE TITLE
[Feature Request] FARPs for Helicopters

### ISSUE THREAD

**Issue by Lennsson** [dcs-liberation/dcs_liberation#186]
Hi! First of all: This campaign makes up all of my singleplayer experience and want to thank everyone contributing to this campaign, you´re awesome!

My Request would be, if it is possible to have **FARPs for Helicopters** in missions. I saw that video from casmo with helicopter praxis and the usage of farps and since i bought the ka50 some days ago i see lots of potential in dcs in regards to helicopter operations.
My thought is to have different preplaced farps on different locations per map. For example: Lane xy is pushed 60% to xy. Between base and frontline are two preplaced FARPs from wich one is then used by the campaign.

Thanks for listening! Once again, you´re awesome!
Best Regards Lennsson

**Comment by TinuzzWasTaken** [comment]
I would love to see this implemented as well!

**Comment by ssg-dev** [comment]
This feature should also include Harrier.

**Comment by Furia139** [comment]
This would have an awesome impact in the campaign. Would add a highly valuable objetive to capture or hold and will allow helicopter operations closer to the front lines. I am really looking forward for this possibility !!
Thanks

**Comment by DanAlbert** [comment]
Was done several releases ago.
