### ISSUE TITLE
Support for DCS 2.7.9.17830

### ISSUE THREAD

**Issue by DanAlbert** [dcs-liberation/dcs_liberation#1868]
- [x] https://github.com/pydcs/dcs/pull/194
- [x] Terrain export https://github.com/pydcs/dcs/pull/196
- [x] https://github.com/dcs-liberation/dcs_liberation/pull/1869
- [X] Weapon data for AN/ALQ-184
- [x] Bump campaign version for map updates

I'll take care of the data export and viper loadouts. Would appreciate a volunteer to do to the terrain export since I've never figured those out :)

**Comment by DanAlbert** [comment]
Main work is done. We've shipped without terrain exports before, so probably okay to continue doing so if no one figures out how to do them before release.

**Comment by RndName** [comment]
i'll try to figure out how that terrain export thing works today and will write some info about it..

**Comment by RndName** [comment]
#1917

**Comment by RndName** [comment]
all done and merged :)
