### ISSUE TITLE
No comms when using latest DCS openbeta with Liberation missions

### ISSUE THREAD

**Issue by franukis** [dcs-liberation/dcs_liberation#1874]
### Affected versions

5.0.0

### Description

When using a Liberation mission with DCS 2.7.9.17830 Open Beta, the AWACS, Tanker... are not responding, and neither do the comms menu pop-up. Happens both in MP and SP, and just with liberation missions. When using a non-liberation mission, everything's fine. Eventually, this has ended with server crashes, and again, only wirth liberation missions.

### Save game and other files

[BugReport.zip](https://github.com/dcs-liberation/dcs_liberation/files/7776884/BugReport.zip)

**Comment by Starfire13** [comment]
Tested with included .miz and ATC and AWACs are functioning just fine. Problem is on user's end.
