### ISSUE TITLE
Feature request - On the new game menu: Limit spawns to XX number of minutes

### ISSUE THREAD

**Issue by qwertymanisalive** [dcs-liberation/dcs_liberation#188]
Add a menu item on the new games menu - Limit spawns to XX number of minutes

My games tend to be in the 45-60 minute time frame. Right now I delete flights delayed longer than 60 minutes and reuse the airplanes on shorter flights but it would be nice to limit the spawns to a certain number of minutes on the new game menu.

Cheers

![dcs lib menu](https://user-images.githubusercontent.com/39744809/95258480-b3753500-07da-11eb-875f-fa5b8e85df91.PNG)

**Comment by DanAlbert** [comment]
This is in 3.0
