### ISSUE TITLE
Problem of balance of Power with Mariana's campaign PACIFIC REPARTREE

### ISSUE THREAD

**Issue by JF-JEFX** [dcs-liberation/dcs_liberation#1886]
I am writing this here on this part of the forum because there is not entry for this campaign in the _campaign maintenance_ area of this website (actually for any of the Mariana's campaigns).  

At first, I thought it would be a really great naval only campaign, like we are really missing with our Hornets and Supercarrier...   
BUT...
It is unplayable (for me at least)...  At a certain point in any mission (around 00:45') the enemy carriers (there really are many) and main destroyers start shooting (huge) swarms of anti-ship missiles (P-700 Granit , etc.) that are MUCH more effective than our Harpoons... they manage to severely damage or destroy our ONLY carrier (which is our ONLY base of operation here!)... 

I even tried launching at the start of mission 1 a very strong 30+ F-18 ANTI-SHIP offensive against the closest 2 aircraft carriers (Liaoning-Kuznetzov...) but our Harpoons get exterminated as well...  I tried many strategies, even tried to give the enemy half of our initial budget... but to no avail, it seems unplayable...

I really think there is a problem of balance of power in this (very promising) campaign and it is unplayable.  Is it possible to balance it please?  thanks.

JEFX

**Comment by Starfire13** [comment]
If you have issues with that specific campaign, contact Fuzzle directly on the Liberation Discord as he is the author.
