### ISSUE TITLE
"not enough helipads available at Haifa"

### ISSUE THREAD

**Issue by Hornet2041** [dcs-liberation/dcs_liberation#1890]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/1641142960

### Description

pressed takeoff, this error pops up and prevents play:
![image](https://user-images.githubusercontent.com/55866858/147840116-b9adc53a-1d78-4ca8-a873-67b07e00b9e8.png)

I had to skip the first 3 turns because the mission planner did not buy the aircraft I assigned my player pilot to, so it did its automatic-everything thing. finally get a mission I can fly and this error generated.

All default options for Operation Allied Sword, except i renamed the existing F-14 squadron and moved it to Ramat David.

### Save game and other files

[haifa heliports bug.zip](https://github.com/dcs-liberation/dcs_liberation/files/7797153/haifa.heliports.bug.zip)
[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/7797157/liberation.log)

**Comment by Hornet2041** [comment]
got a workaround by selling the Apaches at Haifa.

**Comment by Hornet2041** [comment]
new save of this bug, caused by AI Mi-8s at Tiyas
[helipads at airfield bug.zip](https://github.com/dcs-liberation/dcs_liberation/files/7921756/helipads.at.airfield.bug.zip)

**Comment by DanAlbert** [comment]
5.1 isn't affected. I merged a probable fix into develop but since the save games here are too old to load in HEAD I can't be sure. lmk if this is broken in https://github.com/dcs-liberation/dcs_liberation/actions/runs/1743077315 or newer.
