### ISSUE TITLE
Hotfix for Allied Sword

### ISSUE THREAD

**Issue by sgtfuzzle17** [dcs-liberation/dcs_liberation#1891]
BLUFOR Apaches are unable to take off from Haifa for some reason; seems to be a parking slot issue. Have resolved this by moving the 113th Squadron Israeli Apaches to Ramat David. Note that Haifa remains a BLUFOR airfield to force blue reinforcements to move through an extra point of delay before contributing to the frontline fight, and to provide a point for naval convoys to move from when further through the campaign.

**Comment by sgtfuzzle17** [comment]
Forgot my file, whoops.
[operation_allied_sword.zip](https://github.com/dcs-liberation/dcs_liberation/files/7797529/operation_allied_sword.zip)

**Comment by DanAlbert** [comment]
Only needed if https://github.com/dcs-liberation/dcs_liberation/issues/1890 doesn't get fixed.
