### ISSUE TITLE
AI flights won’t spawn

### ISSUE THREAD

**Issue by ugh428** [dcs-liberation/dcs_liberation#19]
Hello and thanks for your hard work in making this.  Recently downloaded RC9 and got the first mission working mostly fine, the subsequent missions however, AI flights may or may not spawn, and in all cases (even the first mission) none of the AI flights spawn off the carrier.  The planes are available and are tasked before the mission launches.  I’ve tried changing their flights time, I’ve tried changing my flight time, I’ve tried leaving everything alone but it’s still hit or (mostly) miss if the flights spawn.

**Comment by 8karos** [comment]
@ugh428 My solution: (1) click the “take off” button, but don't start DCS. (2) check if the terminal says “INFO :: Flight not generated : culled”. (3) if so, disable the culling of distant units or increase the culling distance.

**Comment by ugh428** [comment]
@8karos thanks for the info, I’ll look at that next time.

**Comment by spark135246** [comment]
> @ugh428 My solution: (1) click the “take off” button, but don't start DCS. (2) check if the terminal says “INFO :: Flight not generated : culled”. (3) if so, disable the culling of distant units or increase the culling distance.

thanks! nice solution

**Comment by Khopa** [comment]
This should be fixed in 2.0.10. AI flights will be generated from frontline bases regardless of the culling setting, so it shouldn't be possible to run into such situation again. 

Please re-open if you encounter the issue again.

**Comment by IsaNoot** [comment]
I believe I have run into a slight issue regarding this and I hope I can explain well enough:

In the current release if I capture a new base 80km away from my previous base, it becomes the new "frontline base" as you put it, but I obviously cannot populate this new base with new aircraft until the next turn. So if my culling distance is 79km or less for example, the flights from the previous base are culled and no friendly flights will spawn but my own.

I figure the center point for the culling is on this frontline base? If so, would it perhaps be better to set it only if there are friendly flights available?
