### ISSUE TITLE
default Ju-88 anti-ship uses unavailable LTF-5B

### ISSUE THREAD

**Issue by ali4000** [dcs-liberation/dcs_liberation#1901]
### Affected versions

Development build

### Development build

develop-5.1 branch

### Description

After switching to develop-5.1 branch and updating dependencies (i.e. pydcs), it's no longer possible to edit the loadout of Ju88 flights, because the anti-ship loadout references the LTF_5B torpedo, which now causes a KeyError:

![error](https://user-images.githubusercontent.com/48153528/147980929-6a79e2a7-c3a0-4958-9fdb-57374605f750.png)

Apparently they are right now missing in pydcs; inspecting the Ju88 entry in pydcs/dcs/planes.py, they are mentioned in error comments on lines 40294 and 40306 with

#ERRR {LTF_5B}

Changing Liberation's Anti-Ship loadout to e.g. {SC_500_L2} works as a temporary workaround. I realize this is really a pydcs issue, but filing here after discussion on Discord.

### Save game and other files

No save game or anything needed, just start a new Normandy campaign with e.g. Germany 44 as player faction, make a Ju88 flight, and double-click the flight to open the edit flight window, and it will generate the traceback:

2022-01-03 21:07:09,642 :: ERROR :: Uncaught exception
Traceback (most recent call last):
  File "D:\devel\dcs_liberation\qt_ui\widgets\ato.py", line 119, in on_double_click
    self.edit_flight(index)
  File "D:\devel\dcs_liberation\qt_ui\widgets\ato.py", line 124, in edit_flight
    Dialog.open_edit_flight_dialog(
  File "D:\devel\dcs_liberation\qt_ui\dialogs.py", line 57, in open_edit_flight_dialog
    cls.edit_flight_dialog = QEditFlightDialog(
  File "D:\devel\dcs_liberation\qt_ui\windows\mission\QEditFlightDialog.py", line 33, in __init__
    self.flight_planner = QFlightPlanner(package_model, flight, game_model.game)
  File "D:\devel\dcs_liberation\qt_ui\windows\mission\flight\QFlightPlanner.py", line 20, in __init__
    self.payload_tab = QFlightPayloadTab(flight, game)
  File "D:\devel\dcs_liberation\qt_ui\windows\mission\flight\payload\QFlightPayloadTab.py", line 39, in __init__
    self.loadout_selector = DcsLoadoutSelector(flight)
  File "D:\devel\dcs_liberation\qt_ui\windows\mission\flight\payload\QFlightPayloadTab.py", line 13, in __init__
    for loadout in Loadout.iter_for(flight):
  File "D:\devel\dcs_liberation\gen\flights\loadouts.py", line 120, in iter_for
    {p["num"]: Weapon.with_clsid(p["CLSID"]) for p in pylons.values()},
  File "D:\devel\dcs_liberation\gen\flights\loadouts.py", line 120, in <dictcomp>
    {p["num"]: Weapon.with_clsid(p["CLSID"]) for p in pylons.values()},
  File "D:\devel\dcs_liberation\game\data\weapons.py", line 73, in with_clsid
    return cls._by_clsid[clsid]
KeyError: '{LTF_5B}'

**Comment by ali4000** [comment]
Actually, the FW190-A8 is also broken, but in a weirder way -- the edit flight window won't open with the same assert, but the KeyError is because '{SC_250}' is unknown -- however, the SC250 is not used(!) in the Liberation loadouts for the the Anton, so the same workaround won't work. The SC250 class names appear to have changed in pydcs to become more elaborate, but I'm not sure where the reference to the old "{SC_250}" comes from as neither Liberation nor pydcs appear to use that string anywhere.

Did not (yet) see problems with the K4 or D9, but need to investigate more.

**Comment by Oesau** [comment]
similar to https://github.com/dcs-liberation/dcs_liberation/issues/1810

Appears that when loadout options are changed in DCS they need to be updated in Liberation (there must be a reference list within Liberation - can this be changed to a lookup directly in DCS to decouple the two?)

**Comment by DanAlbert** [comment]
Key point from the main post:

> Apparently they are right now missing in pydcs; inspecting the Ju88 entry in pydcs/dcs/planes.py, they are mentioned in error comments on lines 40294 and 40306 with
>
> ```
> #ERRR {LTF_5B}
> ```

Short term fix would be to update the loadout to use a different weapon. Recreating that loadout with the same torpedo yields the same clsid, so the problem is definitely pydcs.

**Comment by DanAlbert** [comment]
Reported upstream as https://github.com/pydcs/dcs/issues/227
