### ISSUE TITLE
Validate the factions when they are loaded and check if the country has access to the units

### ISSUE THREAD

**Issue by RndName** [dcs-liberation/dcs_liberation#1903]
Currently the generators just generate the group and do not check if the faction even has the unit. This creates GroundObjects which are never used in the campaign. In the mission editor they are generated but have an empty type which lets dcs ignore them. Nevertheless they appear on the map and lead to some confusion as they can be set as strike targets and so on.

**Describe the solution you'd like**
1) Factions files should be validated during campaign generation. It should validate if the country has access to the units and if not an error log should be produced to help find issues with the factions and also the unit should be removed from the faction.
2) Also all shipped factions should be validated with pytest and during the build workflow to ensure only valid factions are shipped. This is useful whenever pydcs receives an update or a new factions submission happens.
3) There should also be a logic to improve the current generators to allow faction specific handling. (If faction a use unit type 1 else unit type 2). 

The validation against pydcs needs an PR to pydcs to exent the countries with a list of all supported vehicles per country (like this already exists for planes and helicopters). Thats an easy fix but requires a new data export.

**Comment by DanAlbert** [comment]
Probably better to validate _everything_ in the file when we load it? Should be doable.

**Comment by RndName** [comment]
As Ghosti showed me i was wrong with my assumption that units which are not supported by the country will result in not spawning at all and it was me more like having a culling issue i will close this issue. not a problem anymore when the faction has some units from other countries.
