### ISSUE TITLE
SA5Generator uses RLS_19J6 SR which can not be used by any country which has access to the SA-5

### ISSUE THREAD

**Issue by RndName** [dcs-liberation/dcs_liberation#1906]
### Affected versions

5.0.0

### Description

As the title says the current SA-5 Generator always build a group with the `"SAM SA-5 S-200 ST-68U \"Tin Shield\" SR"` which can not be used by any country in the game which actually has access to the S-200 LN and RPC_5N62V TR. Example: Iran, Poland, Lybia...

Therefore the SA-5 Group will not have any SR as there will be a unit with not type which will not generate the SR.

Expectation: Add a fallback for factions which have different SR available. I am not sure which system exactly would be a good replace for the Tin Shield...

Connected with #1903

### Save game and other files

-

**Comment by RndName** [comment]
There is also a discussion at the ED Forum about the TinShield as SA-5 SR
https://forums.eagle.ru/topic/278213-tin-shield-radar-incorrectly-named-as-sa-5-search-radar/

Maybe a good idea would be to create different types of SA5 Generators. For example a "Late"SA-5 Version with the BigBird `"SAM SA-10 S-300 \"Grumble\" Big Bird SR "` Radar or maybe an early version with a not so efficient radar like the `"SAM SA-10 S-300 \"Grumble\" Clam Shell SR"` or similar

**Comment by DanAlbert** [comment]
I think everyone with the SA-5 has the P-19, for a fallback.

**Comment by RndName** [comment]
> I think everyone with the SA-5 has the P-19, for a fallback.

is the P-19 range enough to fit the SA-5? thought the same but was not really sure as i am really complety unexperienced with these facts :D

**Comment by DanAlbert** [comment]
Probably not but for any factions without the SA-10 I think it's the only option.

**Comment by RndName** [comment]
oh wow the vehicles.py says: `detection_range = 160000` for the P-19 and `detection_range = 150000` for the TinShield

**Comment by RndName** [comment]
so maybe an EarlySA-5 with the P19 and an LateSA-5 with the SA-10 SR?

**Comment by RndName** [comment]
Gone trough all factions using the SA-5 and i think the P-19 (FlatFace) is the best option for a legacy SA-5

Faction | FlatFace | TinShield | BigBird
-- | -- | -- | --
Iran 2015 | Yes | No | No
Libya 2011 | Yes | No | No
North Korea 2000 | Yes | Yes | No
Poland 2000 | Yes | No | No
Russia 1975 | Yes | Yes | No
Syria 2011 | Yes | Yes | No
Syria 2012 | Yes | Yes | No
Ukraine 2010 | Yes | Yes | Yes
