### ISSUE TITLE
Airports with heli parkings doesn't accept helicopters

### ISSUE THREAD

**Issue by ataribaby42** [dcs-liberation/dcs_liberation#1908]
### Affected versions

5.0.0

### Description

When I tried create simple helicopter only campaign at Syria I didn't find airport that will accept my helicopter sqadron. with 5.0 release player always starts at air and with 6.0 preview build I got error dialog about no available heliports has been found.

I tried use nice helicopter base Taftanaz and tried other airports that accept helis in Misson Editor without luck.

I solved it to make FOB FARP nearby but it is not nice as there is special helicopter bases at Syria map.

### Save game and other files

**Comment by DanAlbert** [comment]
Duplicate of https://github.com/dcs-liberation/dcs_liberation/issues/1890
