### ISSUE TITLE
[Documentation] Frontline strategies & Capture base conditions

### ISSUE THREAD

**Issue by Nomadzy** [dcs-liberation/dcs_liberation#191]
First, thank you guys for solving the 2.1.2/3 bugs, I appreciate your reactivity.

Can you add an explanation to the doc about the meaning of the frontline strategies other than aggressive/defensive ?
And also can you explain the base capture event conditions ? In many times you level a full base with it surrounding troops, and in the end, no capture base event. And worst than that, sometimes this event goes from 1 to 0 for no apparent reason !!!

**Comment by DanAlbert** [comment]
https://github.com/Khopa/dcs_liberation/wiki/Frontline-Strategies-Stances

Base capture logic is implemented by DCS. If there are friendly ground units in the base and no enemy units, you capture the base. That will change at some point in the future.

**Comment by Nomadzy** [comment]
Well I'm not sure about that, sometimes I have to take bases three times (turns) to advance. Some ss from the last times it happened : 
![Screen_201008_133656](https://user-images.githubusercontent.com/23081223/98453939-0d14aa80-215f-11eb-9886-dd0d2ec24905.png)
![Screen_201011_000919](https://user-images.githubusercontent.com/23081223/98453940-10a83180-215f-11eb-8301-7ddabe64eaca.png)
![Screen_201011_000926](https://user-images.githubusercontent.com/23081223/98453950-1a319980-215f-11eb-9c6b-9ddf8c22cc31.png)

**Comment by DanAlbert** [comment]
Click on the base in the map view. It will tell you what coalition owns it. Unless it says blue DCS didn't register the capture.
