### ISSUE TITLE
AI helicopters stuck after takeoff from FOB

### ISSUE THREAD

**Issue by ataribaby42** [dcs-liberation/dcs_liberation#1910]
### Affected versions

5.0.0, Development build

### Description

AI Helicopters got stuck after takeoff and hover forever. It happens in 5.0 release, 5.1 dev and 6.0 dev. Savegame is from 5.1 dev.

![liberation](https://user-images.githubusercontent.com/54838824/148136382-3afcf214-6763-4eab-95d1-e2363ea38594.jpg)

### Save game and other files

Savegame, generated mission and campaign definitions attached.

[Liberation2.zip](https://github.com/dcs-liberation/dcs_liberation/files/7810960/Liberation2.zip)

**Comment by bbirchnz** [comment]
I've seen similar. Looking into it.

**Comment by ataribaby42** [comment]
In-flight as start works always ok, Cold/Warm got stuck sometimes.

**Comment by Starfire13** [comment]
Cold starts from FIB in 6.0 appear to be working just fine for me.

**Comment by Hornet2041** [comment]
I've seen them get stuck in hover after cold start too. The waypoint sequence displayed when they do it seem to indicate they're still on waypoint 0. Might be a DCS bug?
