### ISSUE TITLE
Hint for squadron transfer in aircraft purchase window

### ISSUE THREAD

**Issue by pwmohr** [dcs-liberation/dcs_liberation#1911]
### Affected versions

5.0.0

### Description

In the course of playing through the "Caucasus - Northern Russia", we captured Tbilisi-Lochini. The airport turned blue on the Liberation map as expected, but when I click on the airport to buy airplanes there, the window where the purchase controls normally appear ... the "Airfield Command" tab is blank.

### Save game and other files

[Caucasus3.zip](https://github.com/dcs-liberation/dcs_liberation/files/7811322/Caucasus3.zip)

**Comment by DanAlbert** [comment]
Did you transfer any squadrons there?

**Comment by pwmohr** [comment]
Ah that was the problem. I hadn't realized that was necessary, but tried it and that fixed the issue. Looks like we can close this one. Thanks for your quick response! (It might be worth considering adding some simple guidance text in the case that the window is empty like that. "Transfer squadron(s) here to allow aircraft purchases." or something like that.)

**Comment by DanAlbert** [comment]
Yeah, that's a good idea. We often do things like that but I wasn't sure where to put it. Under the aircraft purchase box seems like a good spot though. Reopening this to track that even if it wasn't the original goal :)

**Comment by DanAlbert** [comment]
@RndName probably simple if you want to pick this up for 5.1.0

**Comment by RndName** [comment]
> @RndName probably simple if you want to pick this up for 5.1.0

Agree that it is useful but i think it will not make it any more in 5.1.0. But it is definitely worth shipping with a 5.1.X whenever it would make sense to ship one.

**Comment by pwmohr** [comment]
Another bit of confusion that might add an idea for a future feature: Being ignorant of the fact that I needed to reassign the bases for the squadron(s), I had edited a few flight plans for some AI and player flights to land at Tbilisi-Lochini. After the turn, although I'd seen the AI land there, none of the AI ended up there when I looked in Liberation. I now understand why that was the case, but you may want to consider this: If the player changes the "Arrival" airport on the "Edit flight" page, you could ask if they wanted to change the squadron base for that particular aircraft to that new "arrival" airport. Because without that, changing the "arrival" airport won't really work if I am understanding things correctly now.

Something like that, anyway.

Thanks, by the way. You're doing really amazing work.

**Comment by pwmohr** [comment]
Actually thinking about it a bit more, it seems that if all a squadron's aircraft must fly out of the same airport / carrier, that the "arrival" airport option on the "edit flight" screen should maybe be eliminated.  And possibly replaced with a "relocate squadron" option. Haven't thought about it enough to be sure it would make sense on that particular page but maybe.

**Comment by DanAlbert** [comment]
Tbh I thought I had removed that already. Divert should be controllable, but arrival shouldn't be.

**Comment by DanAlbert** [comment]
Looks like I removed it from the _new_ flight dialog, but not the edit. Probably worth doing.
