### ISSUE TITLE
"Could Not Find Front Line Point" Error

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#1912]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/1647276730

### Description

Encountered this error at the end of Turn 2 of my updated Exercise Vegas Nerve campaign.
![Capture](https://user-images.githubusercontent.com/72491792/148208422-9456e66e-79d4-497d-8ca2-33a8f9f02867.JPG)

It may possibly be related to this: https://github.com/dcs-liberation/dcs_liberation/pull/1838

Note that while the Vegas Nerve campaign is an updated one (I have included the .miz and .yaml in the zip), those changes are on the southern end of the map (the addition of a FOB and an additional airfield). The section of frontline pathing (Tonopah to Groomlake) where this error occured has not changed since the version of Vegas Nerve in the release build.

### Save game and other files

[Files.zip](https://github.com/dcs-liberation/dcs_liberation/files/7814476/Files.zip)

**Comment by DanAlbert** [comment]
@RndName I see this was marked as todo in 5.1.1, but I think you reverted the problem commit before it went out in 5.1.0. Was that mistriaged, or did I misunderstand? I want to be sure I'm not prematurely marking this complete.

**Comment by RndName** [comment]
> @RndName I see this was marked as todo in 5.1.1, but I think you reverted the problem commit before it went out in 5.1.0. Was that mistriaged, or did I misunderstand? I want to be sure I'm not prematurely marking this complete.

Yes, i marked it as todo to remind me that i reverted the original commit so that i will squash the commit and the fix later. Just a reminder that the new fix has a dependency
