### ISSUE TITLE
Option to adjust fuel level of player aircraft dynamically linked to weapon selection

### ISSUE THREAD

**Issue by LMXd2** [dcs-liberation/dcs_liberation#1913]
I noticed (version 5.0) after manually changing the weapons selection that the fuel level did not appear to automatically adjust based on the new weight of the aircraft. In my case this was for the A10C on Caucasus and Nevada campaigns. 

In addition, as far as I can see, there is no option in DCS liberation to control the fuel level for player aircraft (or AI aircraft).

Some suggestions for new options:

- automatically load the aircraft with max fuel after switching to another preprogrammed weapon loads or a manually defined weapon configuration.
- add a fuel control panel similar to what is available in the DCS mission editor where changes in weapons immediately show how much weight is still available and fuel level can be adjusted easily.

**Comment by DanAlbert** [comment]
> automatically load the aircraft with max fuel after switching to another preprogrammed weapon loads or a manually defined weapon configuration.

All aircraft have max fuel except a few special cases where it's know that aircraft won't be able to take off with full fuel (I think the Su-33 and the C-101 are the only aircraft with this special case). If you're seeing otherwise you'll need to file a bug.

**Comment by LMXd2** [comment]
![1a Starting automatic loadout](https://user-images.githubusercontent.com/63405293/148385168-5fe5cbc2-a4fd-441d-aa76-6372e962541e.jpg)
![1b Fuel level directly after autostart with automatic weapon loadout](https://user-images.githubusercontent.com/63405293/148385196-5f5bf4f2-0201-4b72-bc93-627e06615486.jpg)
![2a Manual weapon loadout](https://user-images.githubusercontent.com/63405293/148385205-0735db25-a8f7-48cd-913c-5e5abc820e25.jpg)
![2b Fuel level directly after autostart with manual near zero weapon loadout](https://user-images.githubusercontent.com/63405293/148385212-c7809012-4f93-4c25-8fca-98da94d1f8dc.jpg)

![4a Reference mission editor Nevada](https://user-images.githubusercontent.com/63405293/148385226-01629c
![3a Reference mission editor weapon loadout Caucasus](https://user-images.githubusercontent.com/63405293/148386367-bf41f35d-edf2-43a8-a9b1-9073c1e5d40a.jpg)
![3b Reference fuel level after start up low weapon loadout Caucasus](https://user-images.githubusercontent.com/63405293/148387340-351453ad-3c1e-4498-855d-03188073e904.jpg)
![4b Reference fuel level after start low weapon load](https://user-images.githubusercontent.com/63405293/148385232-7d720873-d3ed-4376-bfc1-3738175030fd.jpg)
![4c Reference fuel level after refuelling](https://user-images.githubusercontent.com/63405293/148385237-fae9a26e-a5d2-4f12-a5ef-646846d2d12b.jpg)

Thank you for your feedback. I investigated it a bit further and it looks like a bug in DCS. Pictures 1a and b show an automatic weapon load and fuel level in the DCS liberation campaign Mozdok to Maykop. Pictures 2a and b show that the fuel level does not increase in case I reduce the weapon load. However, pictures starting with 3 (Caucasus) and 4 (Nevada) show that I get the same (too low) fuel level when I start from the mission editor and load the same low weapon configuration. 4c shows that the fuel level also does not increase after a request for refuelling.

I used the A10C II model in the mission editor. DCS liberation version 5.0 and DCS world beta version 2.7.9.18080

**Comment by LMXd2** [comment]
Hi, this issue is not related to Liberation. The fuel gauge dial (below the fuel gauge) was set to wing. After switching it to MAIN or INT it shows that there is more fuel available. The standard setting of this dial may have changed with the change from A10C to A10C II, I am not sure. At any rate this issue can be closed.
