### ISSUE TITLE
None of A2A Blue aircrafts engage the enemy aircrafts, Solution: raise the engagement distance by at least x3

### ISSUE THREAD

**Issue by Adixy** [dcs-liberation/dcs_liberation#1916]
### Affected versions

5.0.0

### Description

I tried several different campaigns and noticed that 90% of blue CAP aircrafts fly straight to their death, without fighting against the enemy aircraft nor attacking any enemy bombers.
Then I went to the Mission Editor in DCS and noticed that you've set the **distance** for Enroute Task to **SearchThenEngage** to extremely low numbers, like 50km or so away from waypoint "2" which is named "JOIN". That waypoint is 100+ km away from waypoint 4 or in other words, away from Area of Operation, what explains why most of the aircrafts fly blindly to their death. I changed that distance to 3 times bigger and redid the mission, suddenly all the blue fighters actually attacked the enemy. It really looks cool on the TacView.
I really like what you did with Liberation, it's awesome and I will gladly support you guys, but can you please set this as a priority bug and fix it since all you must do is to multiply the 'max_engage_distance' by 3 and problem solved (but another introduced).
I would suggest (you don't have to listen to me ofc, it's all up to you) to make a check how far is the closest SAM area from the waypoint where you created this "Start Enroute Task" and maybe use that as a condition for max distance. It would be the best to give us, the players|users, the capability to change this distance via the UI (while also multiplying your momentarily default distance by 3 to create a new default).
Please. This Liberation is really cool and brings a joy to my heart. Thanks for all the hard work! :)

### Save game and other files

-

**Comment by DanAlbert** [comment]
> you've set the distance for Enroute Task to SearchThenEngage to extremely low numbers, like 50km or so away from waypoint "2" which is named "JOIN". That waypoint is 100+ km away from waypoint 4 or in other words, away from Area of Operation, what explains why most of the aircrafts fly blindly to their death.

It's an enroute task. It's 50km from the aircraft's location, not from the waypoint.

> CAP aircrafts fly straight to their death, without fighting against the enemy aircraft nor attacking any enemy bombers.

If it has a join point it's an escort. It's not supposed to wander off and find targets of opportunity. It's supposed to stay close to the rest of the package and engage anything that's moving to attack the package. If it's engaging anything within 150nm of the package it will not do that.

> Save game and other files

This is required.

**Comment by Adixy** [comment]
Hey man, thanks for the answer :) Escort isn't meant to attack when somebody gets too close, it's meant to make sure the package does their job without dying. They attack targets that jeopardize the mission. If they react only when enemy is 50km away from them, which can be different distance from the CAS/Strike, then probably the CAS is already dead or will die soon.
I will send you TacView today when I get on my PC. Don't get me wrong, I really like this Liberation thing and as a programmer myself, I can see how much work and effort has been put into this. And I know this is an easy fix cause I found the lines you have to edit xD
But from a perspective of a strategist/tactician, putting trigger to start fight to 50km on an F-14 with Phoenx missiles that have range of 190km isn't a smart decision. It's quite the opposite, waste of resources, failure of escort mission and ultimately lost lives of those pilots as they always lose... Unless I edit the mission in Mission Editor, which shouldn't be the case as this can be fixed with automatic scripts. It's a small fix, easy one... 
Also, the waypoints for CAP guys doing the racetrack are put 250km away from the AO, with distance set to 90km, which renders them useless. But this isn't such an issue as you can easily move the waypoints and fix it like that :) But it too can be fixed with just a small line edit where you calculate the distance for the task... Please :)
I'll be putting the tacview soon

**Comment by Adixy** [comment]
I don't have the .miz since I created 10 different campaigns in last several days, but I do have the TacViews which are not supported for uploading. I'll just give you screenshots

This is from Syria Campaign, first mission, AI flight. They ignore enemies and die later (2nd picture)
![image](https://user-images.githubusercontent.com/16743558/148373481-72c13acb-15ae-4599-9992-d31d884b1170.png)

Not even a single missile fired, I had to kill enemy aircraft, and I was on a A2G mission xD
![image](https://user-images.githubusercontent.com/16743558/148373614-aeb7c1af-7df6-4fe5-8cda-8c86ed2fc77c.png)

F-15C attacked the first enemy A2G aircraft when they got close to them, but ignored the other one which killed lots of our ground units. Treason I'd say.
![image](https://user-images.githubusercontent.com/16743558/148373829-022a4a66-ee07-4c92-9ba0-67201c8728a6.png)
They ignore this guy...
![image](https://user-images.githubusercontent.com/16743558/148373880-77d59ce6-bbc0-4b5f-9de3-a99d7c8b0ce2.png)

He is killing ground units, F-15s are doing nothing untill I told them (thanks to CA module) to engage this guy)
![image](https://user-images.githubusercontent.com/16743558/148373999-cd0acfbd-4b67-42dc-aa24-71d76c34078c.png)

Another proof
![image](https://user-images.githubusercontent.com/16743558/148374069-3094f6ab-f9d2-4f58-954c-3ea5374f99be.png)

F-14s using Aim-7 cause the distance is too short for Aim-54 (they all died btw) [This is a different Syria campaign]
![image](https://user-images.githubusercontent.com/16743558/148374352-1d9e3c50-c246-4f30-8a0a-b8479486d094.png)
And again
![image](https://user-images.githubusercontent.com/16743558/148374510-5a8f0806-7588-479f-814d-e6291b9dbb64.png)

All this time, there were several CAP aircrafts just ignoring the enemy that is killing their friendlies and losing us a war
![image](https://user-images.githubusercontent.com/16743558/148374674-4086c9d8-157e-4c40-9e63-07f9e4d95c4b.png)

This should be enough of proofs. If you want more, just create a campaign, let the mission play out and check the TacView... I noticed that DCS community wants to simulate reality, but they always tend to go opposite direction when it comes to strategy. The thing is, in a war, you want to have air supperiority and if you can, you want to outnumber your enemy. To have A2A friendly aircrafts flying around doing literally nothing while there is an air fight going on and friendlies are dying, makes no sense. All friendly air fighters should try to destroy most of the enemy air fighters cause in the end, they will bomb their runways, or kill them with SAMs or in a certain a2a battle. The soon as you make air safe in the safest possible way, the better it is. 
Putting extra small engage distance, distances that are smaller than the range of the missiles, makes 0 sense and just makes you lose most of the air battles. Not because you were weaker, but because limitations didn't allow you to react and attack on time, or react at all. If you could at least change this to x2.5 the size, it would make a huge difference. 
Ofc you don't have to, I can just edit it manually every time, or I'll just pull the whole project and edit and build it by myself xD
Pretty please :) This Liberation has a huge potential and it's really a work of Gods, the programmers now their stuff. But, when it comes to strategizing, sometimes it kinda goes off and ruins the immersiveness and fun. 
Anyway, thank you for your hard work

**Comment by DanAlbert** [comment]
Typo. 50nm, not 50km. 50nm should be plenty. Anything more than that and they wander off and don't protect the package.

**Comment by Adixy** [comment]
50nm would be much better, but for me it's 50km. 
Maybe if I change default units to nm instead of meters it'll fix by itself... I'll try and see if it changes, thanks :)

**Comment by DanAlbert** [comment]
Apparently escorts (and only escorts) have a hard coded lower commit range: https://github.com/dcs-liberation/dcs_liberation/blob/82dfeb8afa69803ad040c8dee57cb1aa373b5be4/game/missiongenerator/aircraft/waypoints/joinpoint.py#L74

30nm is possibly a bit too low. We can't actually _usefully_ control escorts because the DCS AI has no "ignore things that aren't attacking friendlies" option, nor is there a "defend friendlies that are being attacked" option. If we set it too high the escorts are quite likely to spend all their ammo on flights that weren't going to cause any trouble for the package, and then they won't be able to help when there actually is a problem.

**Comment by Adixy** [comment]
Ohhh I see, now everything makes sense. And since DCS doesn't really support dynamically changing the wapoints and tasks of AI flight (as, with this, we could in real time change to SearchThenEngageInZone when the escorted flight starts doing it's attack, and then go back to Escort), we are stuck with this. I guess having someone in Tactical Commander slot is really needed for AIs...

**Comment by Hornet2041** [comment]
instead of escort you could instead task flights to sweep the route ahead of fighters / suppress SAMs
