### ISSUE TITLE
P-47 causing an "unexpected error" on mission generation

### ISSUE THREAD

**Issue by Venree** [dcs-liberation/dcs_liberation#1925]
### Affected versions

5.0.0, Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/1670015105

### Description

Almost every time I try to run a campaign and use the P-47 it causes the error seen in the attached screenshot. this is happens whenever I try to assign P47's (any model) to a flight (player or AI) no matter what turn of the campaign.

all other aircraft I have tested work fine (all other prop planes work fine too).
Removing the flight of P47's from the active flights list and generating the mission (Take off button) removes the error and everything seems to work, but no P47 of course.

![P47 error](https://user-images.githubusercontent.com/25193373/148643428-d7552e9a-aee8-43af-8942-184af69d06f9.png)

### Save game and other files

[Liberation bug report.zip](https://github.com/dcs-liberation/dcs_liberation/files/7833177/Liberation.bug.report.zip)

**Comment by RndName** [comment]
@Venree this is the wrong save file, could you attach the one with P-47s?

**Comment by RndName** [comment]
possible root cause: StopIteration during the channel_allocation means that maybe there are no more radio channels available. Not sure how many preset channel the P-47 has but this should nevertheless not result in an unexpected error. More a warning as this is not a behaviour we can remove. The only workaround is first assign "priority" radio channels as we already to (inter flight, awacs, jtac, departure and so on.)

We could make a special handling like we do with the viggen or just make a usefull exception handling around it.

**Comment by RndName** [comment]
okay found out how to use your savegame. Was not expecting to see FA-18, F-16 next to P-47s :D 

Found the issue and is under investigation :) Its exactly as i said above. P-47 has 4 channels and the mission wants to assign 5 Preset channels (Intra, Departure, Awacs and 2 JTACs)

**Comment by Venree** [comment]
Yeah, the 47's were added as a joke to be fair (ww2 planes are surprisingly fun to fly vs modern sam sites lol)

with that said, if it is a radio channel thing is it something that can be fixed on the fly? or would it require some internal rework?

**Comment by RndName** [comment]
can be changed on the fly:

- go to the folder `ressources/units/aircrafts` in the dcs_liberation folder
- open the file P-47D-40.yaml (or the other P-47D and P-51D Variants you want to use)
- change the following:
![grafik](https://user-images.githubusercontent.com/6678803/148645340-ed8f9a4a-659a-48f1-bfb0-e037ffc68a5b.png)

(corrected one is to the right)
I will push it to the next hot fix branch as well

**Comment by Venree** [comment]
Confirming fix works perfectly and .... you guys rock btw lol 6.0 branch is turning out to be Very fun :D
