### ISSUE TITLE
Make the original ED F-14A AI available to factions

### ISSUE THREAD

**Issue by Hornet2041** [dcs-liberation/dcs_liberation#1927]
**Is your feature request related to a problem? Please describe.**
There is currently a bug in DCS 2.7.9 where the Heatblur F-14s won't fire their AIM-54s beyond dogfighting range at all, which makes buying them almost entirely pointless in most campaigns. Considering how long DCS bugs can exist, we don't know when its going to get fixed.

**Describe the solution you'd like**
The original AI asset by ED is not affected by this bug and will happily fire their warp 5 AIM-54s willy-nilly. The only downside to using this is that they have an exterior model only its artist can love.

**Additional notes**
when adding this airplane, it should be noted that for some reason to able to carry two AIM-7s in the tunnel even if four AIM-54s are loaded, so it would look normal if the Liberation loadout screen has two extra slots.

also, the ED AIM-54 is a different weapon than Heatblur's.

**Comment by MetalStormGhost** [comment]
@Hornet2041 Please confirm that the F-14A AI version is not able to ramp start from carriers?

**Comment by Hornet2041** [comment]
they ramp start on all carriers that Liberation supports

**Comment by Hornet2041** [comment]
![image](https://user-images.githubusercontent.com/55866858/148694489-42a58583-f451-4295-a679-64a7f388984d.png)
 from your commit :D

**Comment by Hornet2041** [comment]
uh.... the F-14 AI is *extra* dumb though

![image](https://user-images.githubusercontent.com/55866858/148694545-5f35510a-50a4-4796-a3d3-22363b00fc1b.png)

**Comment by Mongyman** [comment]
I think is no longer needed. AI was updated.
