### ISSUE TITLE
Iran 2015 and Iran 1988 factions not visible as factions

### ISSUE THREAD

**Issue by Meyomyx** [dcs-liberation/dcs_liberation#1930]
### Affected versions

5.1.0

### Description

Despite being in the factions list, both Iran factions don't appear in the factions drop down list. Can't quite see why. All others appear as they should

### Save game and other files

[no_iran.zip](https://github.com/dcs-liberation/dcs_liberation/files/7835647/no_iran.zip)

**Comment by DanAlbert** [comment]
> Affected versions
> 5.0.0, Development build
>
> Development build
> v5.1.0

This was filled out wrong and idk what it means. Are you trying to tell us that it's broken on 5.0.0, 5.1.0, and development builds (if so, which development build?), or are you trying to say it's broken on 5.0.0 and 5.1.0?

**Comment by DanAlbert** [comment]
Oh, I see that the templates weren't updated when 5.1.0 released, so probably the latter.

**Comment by Meyomyx** [comment]
The form didn't give me a drop down option for 5.1.0! Anyhow, it looks like you've spotted the issue. Thank you

**Comment by DanAlbert** [comment]
I fixed the template but we haven't looked at the bug. Reopening.

**Comment by DanAlbert** [comment]
I edited the OP. Please confirm that my understanding is correct.

**Comment by Meyomyx** [comment]
I wasn't aware of it being a problem in previous versions. The .zip file is somewhat redundant here. When I try to create any new campaign in Liberation, the two Iranian factions are not available in the drop down - despite being in the resources\factions directory. Any campaign that uses either of the the Iranian factions as the suggested default (Scenic Route for example) proposes "Allies 1940" as the faction (first in the directory).

Hope this helps

**Comment by RndName** [comment]
I have updated the faction file recently. Will look into it closer.

Just to confirm, you are on the official release version 5.1.0? And not on a dev build?

**Comment by DanAlbert** [comment]
> The .zip file is somewhat redundant here. When I try to create any new campaign in Liberation, the two Iranian factions are not available in the drop down

Problems with the New Game wizard should use the "new game wizard failed" template, which doesn't ask for a save game for obvious reasons. Perhaps I worded the description of that template a bit too strongly though.

**Comment by Meyomyx** [comment]
I just re-downloaded and installed 5.1.0 and now the factions are available (along with an additional campaign Scenic Route 2). If I re-install the version of 5.1.0 I just deleted, the problem returns .... so the summary is - fixed in the version of 5.1.0 that is currently available to download!
