### ISSUE TITLE
liberation_main.exe won't start.

### ISSUE THREAD

**Issue by Froggy94** [dcs-liberation/dcs_liberation#1931]
### Affected versions

5.0.0

### Development build

beration_main.exe won't start. 

### Description

Hallo,

since Version 5.0 (including Version 5.1) my liberation_main.exe won't start. Nothing happend. No Command line showd up and no log files are created. when i look at the Task Manger the liberation_main.exe is shown for one second and then disappers. I tried several times do reinstall liberation and deactivate windows defender but nothing helps. Windows and dcs is up to Date. With version 4.1 it works without any Problem ther are only Problem with version 5.0 an above. 

Thanks for Help 

### Save game and other files

No File

**Comment by Starfire13** [comment]
It is most likely an issue with Windows Defender or whatever antivirus you are using. Create an exception so they don't block liberation.

**Comment by Froggy94** [comment]
Thanks for the answer.  I added a exception for the liberation_main.exe in windows defender and also tried it with deactivated defender. Still no Change.  windows defender i the only Antivirus i use.

**Comment by DanAlbert** [comment]
If there's not any error message there's sadly nothing we can do to help.

**Comment by Froggy94** [comment]
Hallo, i found the Issue after i checkt the Windows Error Reporting (WER)  File under C:\ProgramData\Microsoft\Windows\WER\ReportArchive. Liberation tryed do load a DLL form my local python installation which faild.  I delete the pyhon Installation and all system variables which pointed to it and installed the latest python version. Now it seems to Work

**Comment by DanAlbert** [comment]
If you had `PYTHONPATH` set globally that would probably do it.
