### ISSUE TITLE
[Feature Request] Ability to Adjust SAM Threat

### ISSUE THREAD

**Issue by Mustang-25** [dcs-liberation/dcs_liberation#194]
I think it would be a nice idea to have the ability to increase/decrease both the number of SAMs and the difficulty levels for SAM sites. An additional nice to have would be crafting the SAM threat to be similar to the real life threats that existed in which ever map is selected.

In addition to introducing IADS scripts like Skynet, this would add more (or less) challenge to the campaigns and also provide more variety so that the end user can create the scenario that is perfect for them.

**Comment by DanAlbert** [comment]
That's a good idea. Should probably do it for ground forces and air forces as well.

> An additional nice to have would be crafting the SAM threat to be similar to the real life threats that existed in which ever map is selected.

I think we do try to do this based on the enemy coalition, to an extent. Does it need tuning? I haven't looked all that closely.

> In addition to introducing IADS scripts like Skynet

https://github.com/Khopa/dcs_liberation/issues/66 in case you hadn't seen it :)

**Comment by Starfire13** [comment]
One issue with SAMS is that as far as I can tell, they don't ever get replenished. Once I take down all the enemy's radars, I no longer have to worry about SAMs for the duration of the campaign. I can rebuild my SAM sites when they get destroyed, but it doesn't appear that the AI does. That doesn't mean I want all the radars I took down to pop back up on the next turn, but perhaps seeing the occasional one pop back up after a number of turns might provide some additional variety.

**Comment by Mustang-25** [comment]
I like that idea! Maybe a replenishment mechanic similar to what exists for other ground and air units but it takes a few turns? Or maybe it only pulls from a finite stock so there is still a point where you destroy all SAMs.

**Comment by alcmann** [comment]
Excellent Idea Mustang.

**Comment by DanAlbert** [comment]
Obsolete with random objectives going away
