### ISSUE TITLE
Mirage 2000 damage not taken by mission/campaign

### ISSUE THREAD

**Issue by Chichowalker** [dcs-liberation/dcs_liberation#1940]
### Affected versions

5.1.0

### Description

When using Mirage 2000 for runway attack, for instance with BAP-100, after completing the mission, runway appears intact. Also dropping some gnu-12 with autolasing by JTAC and watching impacts and vehicles destroyed, mission does not collect kills. From my tests only happens in this aircraft. I dont know if it is DCS bug or Libertion Bug.

### Save game and other files

[5JOTTERS_OP_CROSSFIELD_M002.zip](https://github.com/dcs-liberation/dcs_liberation/files/7838415/5JOTTERS_OP_CROSSFIELD_M002.zip)

**Comment by Starfire13** [comment]
Attach the state..json generated at the end of the mission.

**Comment by DanAlbert** [comment]
Please follow the bug template:

> The state.json file for the most recently completed turn, located at <Liberation install directory>/state.json. This file is essential for investigating any issues with end-of-turn results processing.

**Comment by Chichowalker** [comment]
Morning.
We continued flying that campign and we overwrote json.
Anyway Im planning to flying the misión again this evening and I Will send you state.json file for you to check.
Thanks in advance.
Chicho.

**Comment by DanAlbert** [comment]
Without the state.json from the turn that had this problem there's nothing we can do.

**Comment by Chichowalker** [comment]
My plan was repeat the mission sending you again turn and .json but you closed without letting me send proper data...

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by DanAlbert** [comment]
It's trivial to reopen a bug. If you encounter the problem again and upload the data that's what we'll do, but we close bugs that we can't investigate because it helps us track what we can and can't work on.
