### ISSUE TITLE
in flight" mission start spawns aircraft too close to ground level

### ISSUE THREAD

**Issue by Hornet2041** [dcs-liberation/dcs_liberation#1941]
### Affected versions

Development build

### Development build

6.0.0-34-preview

### Description

flights set to "in flight" start spawn *way* too close to the ground and have a very high risk of colliding with terrain or buildings and dying instantly:

![image](https://user-images.githubusercontent.com/55866858/148893956-17057e84-089c-49ab-95d7-479a684cd106.png)

### Save game and other files

[battle for golan heights inflight bug.zip](https://github.com/dcs-liberation/dcs_liberation/files/7844280/battle.for.golan.heights.inflight.bug.zip)

**Comment by DanAlbert** [comment]
This is a bit tricky because we don't know where the ground is, but I guess we could just always spawn at a minimum of 10k ft MSL? I'm not sure what the highest elevation airfield in the game is, but it's definitely lower than that.

**Comment by MetalStormGhost** [comment]
Would spawning at the maximum AGL altitude work?

**Comment by DanAlbert** [comment]
Using AGL altitudes also Alters aircraft behavior. I'm not sure if using an AGL WP0 would cause them to terrain follow to WP1, or if the MSL/AGL setting is dependent on the waypoint being traveled to.

We also don't necessarily want a low altitude, we just want to enforce a minimum altitude. If we could compare MSL and AGL we wouldn't have this problem at all.

**Comment by Hornet2041** [comment]
i mean, they just need to start high enough that they dont plow into a building on start. with some spawns being over flat plains the flights *mostly* survived their spawn and climbed to their hold points

**Comment by SnappyComebacks** [comment]
> I'm not sure what the highest elevation airfield in the game is, but it's definitely lower than that.

The highest airfield in DCS is Kerman at 5700ft on the Persian Gulf map I believe.  Nevada has lots of high altitude airfields but they are at 4500 - 5500 feet.

**Comment by DanAlbert** [comment]
6000 ft it is. Thanks. I'd remembered that ~5k was pretty typical for Nevada but hadn't done the research to confirm it.

**Comment by DanAlbert** [comment]
The saves are too old for me to verify them, but I added a 6000ft minimum spawn altitude. lmk if this continues to happen.

**Comment by Hornet2041** [comment]
build 3344
the E-3 and KC-135 tankers spawned mid-air as fixed and then proceeded to immediately land at Ramat David :(
[china vs blufor peace spring.zip](https://github.com/dcs-liberation/dcs_liberation/files/7935957/china.vs.blufor.peace.spring.zip)

**Comment by Hornet2041** [comment]
after some testing, it appears something specifically in the scripts Liberation loads at mission start is causing this, because I deleted them in the mission editor and the planes continued on to their racetrack start points. will update if i can figure out which trigger specifically causes it...

**Comment by Hornet2041** [comment]
update:
ok, after some testing, for whatever reason, the AWACS and Tanker will fly normally if you open the mission up in the editor first, and then directly click on the AWACS and tanker icons in the editor, and then press fly (no need to save).

No idea why.....

**Comment by DanAlbert** [comment]
Idk why this was reopened. The thing you retitled it as is a different bug. File new bugs for new bugs.
