### ISSUE TITLE
Unit wont appear in game

### ISSUE THREAD

**Issue by Deantjee** [dcs-liberation/dcs_liberation#1946]
### Affected versions

5.1.0

### Description

When I planning a mission in Liberation, I can see that the enemy have some SA-13. When I planning through  'Packages' I plan a SEAD attack on this SA-13 unit. For this planning I am using a fly that I control. When I am starting the mission and flying to the obbjective I cannot see the SA-13 anyone, it looks like its bugged in the ground somehow. 

So what I did, I plannend on a next turn a AI to attack this SA-13. When my mission is over and I comming back to Liberation, I am still seeing this SA-13 alive. I have turned off culling so that is not the problem.

So can anyone please help me with this problem?

### Save game and other files

[Liberation mission.zip](https://github.com/dcs-liberation/dcs_liberation/files/7865689/Liberation.mission.zip)

**Comment by Hornet2041** [comment]
loaded up the save files....

![image](https://user-images.githubusercontent.com/55866858/149403423-cca6d3d7-3537-437d-80f4-5a4d38af75c4.png)
![image](https://user-images.githubusercontent.com/55866858/149403441-2e51c146-3457-4693-8e29-25a561dddd59.png)

I don't see anything in the Liberation or DCS log about an SA-13 error, either. 

The faction file, Poland 2010 doesn't list SA13Generator, only SA8Generator.

**Comment by Hornet2041** [comment]
https://github.com/dcs-liberation/dcs_liberation/issues/1666 old bug?

**Comment by RndName** [comment]
#2033 solved in 6.0
