### ISSUE TITLE
If automatic frontline stance is turned on, disable "no moving ground units" when stance is set to breakthrough

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#1947]
**Is your feature request related to a problem? Please describe.**
At the moment, those with "no moving ground units" turned on in performance settings cannot capture airfields/fobs.

**Describe the solution you'd like**
 I suggest disabling "no moving ground units" for any turn where automatic frontline stance is set to breakthrough (which would be when the frontline is close enough for ground units to capture the enemy control point). This would allow those who use "no moving ground units" to still capture bases as long as they keep automatic frontline stance on.

**Comment by DanAlbert** [comment]
This is unnecessary given https://github.com/dcs-liberation/dcs_liberation/issues/1680. I'm not keen on disobeying the user's performance preferences anyway. If they want ground units to move they shouldn't check that box. I assume anyone that does will cheat to capture bases.
