### ISSUE TITLE
iran 2015 faction description incorrectly displays "Iranian 2010s faction"

### ISSUE THREAD

**Issue by Lspd-officer** [dcs-liberation/dcs_liberation#1949]
### Affected versions

5.1.0

### Description

iran 2015 faction description incorectly displays "Iranian 2010s faction" iran 
![image](https://user-images.githubusercontent.com/76147975/149646894-8f740142-530e-4a30-a125-b88caf38796c.png)

### Save game and other files

![image](https://user-images.githubusercontent.com/76147975/149645088-65d89220-0603-47b5-bbe8-fc2337097073.png)

**Comment by DanAlbert** [comment]
2015 is in the 2010s decade.
