### ISSUE TITLE
Squadron transfers require one more slot than total aircraft being transferred

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#1952]
### Affected versions

5.1.0 and Dev Build

### Description

Let's say an airfield has 10 parking spots free. You can't transfer a squadron with 10 aircraft to it. You will get this error.

![Capture](https://user-images.githubusercontent.com/72491792/149679930-c846d7a8-aebf-4419-a062-ab47fb9abab2.JPG)

However, if you sell one aircraft, the transfer will go through just fine with 9 aircraft.

To get around this issue, you can:

1. Setup the transfer with 9 aircraft, then buy 1 additional aircraft for the squadron afterwards. All 10 will be transferred.

2. Alternatively, buy another aircraft for a squadron already at the destination airfield.

Essentially, that parking spot is only unavailable when setting up the transfer.

### Save game and other files

Here's a save file created using Operation Vectron's Claw on 5.1 release. I have 13 aircraft at Sukhumi-Babushara, with 10 parking spots available. There are no pending transfers and no pending aircraft purchases.

At the "From Incirlik" mid-air spawn point, I have a squadron of F-16s with 10 aircraft, and a squadron of F-15Es with 9 aircraft. You can't transfer the F-16s (unless you delete one aircraft) but you can transfer the F-15Es.

[Transfer Test.zip](https://github.com/dcs-liberation/dcs_liberation/files/7878041/Transfer.Test.zip)

**Comment by DanAlbert** [comment]
To be 100% clear: were there pending aircraft deliveries for any of the squadrons at the destination? It's counting the expected aircraft at the airfield next turn. The current turn is irrelevant.

**Comment by Starfire13** [comment]
At least when I encountered it, there weren't. But I plan to test it out later when I get home and will upload a save file if I can replicate.

**Comment by Starfire13** [comment]
Ok. Save file uploaded.
