### ISSUE TITLE
Waypoints not tansfering to aircraft (Player) F-15C Eagle

### ISSUE THREAD

**Issue by GamerKing122** [dcs-liberation/dcs_liberation#1954]
### Affected versions

Development build

### Development build 6.0

https://github.com/dcs-liberation/dcs_liberation/pull/1953

### Description

[autosave.zip](https://github.com/dcs-liberation/dcs_liberation/files/7880539/autosave.zip)
[liberation_nextturn.zip](https://github.com/dcs-liberation/dcs_liberation/files/7880541/liberation_nextturn.zip)

### Save game and other files

Won't import nav points

**Comment by Hornet2041** [comment]
the build you linked is an open, un-merged pull request that has nothing to do with nav points 🧐

**Comment by Hornet2041** [comment]
I opened your file in mission editor and loaded it. Navpoints are working fine for me:
![Screen_220117_154748](https://user-images.githubusercontent.com/55866858/149835413-fe53217e-7f5f-44a8-8c10-87724174aa3a.png)
![Screen_220117_154818](https://user-images.githubusercontent.com/55866858/149835422-0951eca7-fe07-450b-a8e2-f5b88e55b334.png)


what are you showing that yours aren't lining up?

**Comment by Starfire13** [comment]
As Lion (Hornet2041) said, don't use unmerged pull requests unless there is a specific reason you need to.

I had a look at your .liberation and .miz files anyway and all your F-15C flights have nav points that show up (both in Liberation 6.0 and in the mission editor). I am closing this for now. If you can provide specific info on which set of nav points aren't getting imported (a screnshot showing this would also be helpful), and this can be verified, we can always re-open the bug report.
