### ISSUE TITLE
runway start-set flights revert to cold starts AND prevent untasked aircraft from spawning in airfields

### ISSUE THREAD

**Issue by Hornet2041** [dcs-liberation/dcs_liberation#1956]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/1684997687

### Description

Default start is set to cold, but I set the first flight generated (manually) to runway start. On DCS mission start, only the aircraft that are tasked for missions that round show up in-game, the untasked ones are missing. 

Also the flight that is set for runway start reverted back to cold start.

### Save game and other files

[peace spring inverted jan22.zip](https://github.com/dcs-liberation/dcs_liberation/files/7885096/peace.spring.inverted.jan22.zip)

**Comment by Hornet2041** [comment]
observation: this bug does not happen if an E-3 is set to runway start.

**Comment by DanAlbert** [comment]
Can't repro. Loaded the save provided and regenerated the mission. The A-10 is runway start as expected. I then cleared all the other missions and regenerated to check for spawning of unassigned aircraft. Incirlik still has a lot of aircraft on the ground.
