### ISSUE TITLE
Add additional JTAC/TAC CMDR slots in settings UI

### ISSUE THREAD

**Issue by Skunimatrix** [dcs-liberation/dcs_liberation#1958]
Having to load the mission into the ME and manually add slots before each COOP/MP campaign sortie is cumbersome.  Especially since some nights we'll have 2 - 3 people who are dedicated to the ground game for whatever reason.  

It would be nice if in the settings panel for Mission Generation there were a text box where the number of Tac Commander & JTAC slots to be generated for each mission.

**Comment by Starfire13** [comment]
Closing and consolidating under this FR. https://github.com/dcs-liberation/dcs_liberation/issues/1481
