### ISSUE TITLE
RAF No12 (Tornado GR4) Squadron should not include SEAD

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#1960]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/1709226846

### Description

RAF No12 Squadron is a squadron for `Tornado GR4`.  The only air to ground weapons Liberation can set for it is GBU-12s, GBU-16s, and Anti Ship missiles.  It is (arguably) not suitable for a SEAD role.  `SEAD` loadout could probably be removed, as it is identical to the `CAS` loadout.

The `Tornado IDS` is the one capable of SEAD missions.  It carries Mk-82s, air-to-ship missiles, and HARMs.

### Save game and other files

[battle_for_dubai_2_no_ewr_culling.zip](https://github.com/dcs-liberation/dcs_liberation/files/7894165/battle_for_dubai_2_no_ewr_culling.zip)

**Comment by Hornet2041** [comment]
Tornado GR4 carries the ALARM missile
https://en.wikipedia.org/wiki/ALARM

![image](https://user-images.githubusercontent.com/55866858/150172345-1e95f393-534e-4307-8268-88063c29bddb.png)

maybe it is actually Liberation that is missing the ALARM weapon instead?

**Comment by SnappyComebacks** [comment]
> maybe it is actually Liberation that is missing the ALARM weapon instead?

This is probably the way to go.

**Comment by RndName** [comment]
@SnappyComebacks can this be closed with the merge of #1961 ?

**Comment by SnappyComebacks** [comment]
> @SnappyComebacks can this be closed with the merge of #1961 ?

Yes.
