### ISSUE TITLE
SC not recognizing player aircraft and spawning AI flights in weird positions

### ISSUE THREAD

**Issue by GrassyKn0ll** [dcs-liberation/dcs_liberation#1965]
### Affected versions

5.1.0

### Description

Mission upon loading on a server will spawn tomcats Approx. half a mile behind the SC and they will float. The hornets will spawn fine but after starting up 2 will not roll with 1. Carrier crew will not recognize the player aircraft and will not guide to cat. Other missions work fine, seems to be a liberation issue. Please ping on discord (Grassy_Knoll #7705) with any questions.

Thanks, 
Grassy

### Save game and other files

[Liberation files.zip](https://github.com/dcs-liberation/dcs_liberation/files/7901873/Liberation.files.zip)

EDIT: Zip was missing files, corrected and readded.

**Comment by DanAlbert** [comment]
>  The hornets will spawn fine but after starting up 2 will not roll with 1. Carrier crew will not recognize the player aircraft and will not guide to cat.

These are both familiar problems in non-Liberation missions for me, so not considering those for this report. We have no control over this behavior.

**Comment by DanAlbert** [comment]
> Mission upon loading on a server will spawn tomcats Approx. half a mile behind the SC and they will float.

Does not reproduce in current DCS. Was likely a DCS bug.
