### ISSUE TITLE
WW2 pilots are female aswell

### ISSUE THREAD

**Issue by NeelKulkarni6** [dcs-liberation/dcs_liberation#1966]
### Affected versions

5.1.0

### Description

This might not constitute a "bug" so apologies if it doesn't, but in WW2 Pilots and military personal were strictly male. It's not game-breaking but I think it should be added that if the year is like 1940s or 50s, the pilots only have male names 

![image](https://user-images.githubusercontent.com/77650484/150280310-3cd8e534-f665-4564-ac7f-d7ac7f7c5879.png)
Andrea, Ashley, Jessia, & Sandra in the bomber crew

Also consider adding 2 'pilots' per plane if its like a bomber or an F14 

### Save game and other files

[WW2 - Copy.txt](https://github.com/dcs-liberation/dcs_liberation/files/7902613/WW2.-.Copy.txt)
 i made it .txt, just edit it to .liberation

**Comment by tehnerd** [comment]
are you sure about strict male? https://en.wikipedia.org/wiki/Night_Witches

**Comment by NeelKulkarni6** [comment]
> are you sure about strict male? https://en.wikipedia.org/wiki/Night_Witches

Yes but the night witches only flew the Po-2, a plane which we don’t have and probably never will have in dcs.

other than that, there were pretty much no female pilots

**Comment by Khopa** [comment]
We could introduce a *female_pilot_ratio* parameter on squadrons, so we'd be able to treat any case : 
* Put it at 100% if you want to get a female only squadron such as the night witches
* Put it at ~0% for most ww2 & cold war scenarios (most air force did not accept female pilots before the 90s)
* It would default to something like ~6% for modern days scenarios (which is USAF current situation)
