### ISSUE TITLE
Could not find front line point {number} from {control point}

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#1969]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/1709226846

### Description

Second mission in `Persian Gulf - Scenic Route 2 - Dust To Dust` campaign with default factions and start date.  Error `Could not find front line point 70426.30385201362 from FOB Anguran` presents itself after pressing `Accept Results`.

I did steal Starfire's Tornado GR4 loadouts for this mission, but I doubt that is related.

And the campaign file was loaded when I was running https://github.com/dcs-liberation/dcs_liberation/pull/1961, but I never saved it.

### Save game and other files

[battle_for_dubai_2_no_ewr_culling.zip](https://github.com/dcs-liberation/dcs_liberation/files/7917415/battle_for_dubai_2_no_ewr_culling.zip)

**Comment by Starfire13** [comment]
Repeat of https://github.com/dcs-liberation/dcs_liberation/issues/1912

There is a fix in progress by Ghosti: https://github.com/dcs-liberation/dcs_liberation/pull/1914

**Comment by SnappyComebacks** [comment]
Ah I misread the events there as "this was fixed already".  Thanks.
