### ISSUE TITLE
Aircraft are removed from inventory with mission unplanned if Mission Package window is closed before Create Flight is clicked

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#1971]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/1701873298

### Description

If the Mission Package window is closed (1 in the screenshot) before clicking Create (2 in the screenshot) in the Create Flight window, the flight is not created. However, the aircraft for that flight are still removed from the inventory for that turn.

![Capture](https://user-images.githubusercontent.com/72491792/150664808-8213e424-60f9-42ae-8679-28938a0d8481.JPG)

Perhaps set Mission Package window as noninteractive when Create Flight window is open? Or also close the Create Flight window when Mission Package window is closed.

### Save game and other files

[Peace Spring A-10C #3306.zip](https://github.com/dcs-liberation/dcs_liberation/files/7919781/Peace.Spring.A-10C.3306.zip)

**Comment by Hornet2041** [comment]
sounds very similar to an old closed bug report here:
https://github.com/dcs-liberation/dcs_liberation/issues/1027

**Comment by Starfire13** [comment]
Good catch. Looks like it was previously fixed by making the second window subordinate to the first, but that no longer appears to be the case now.

**Comment by Raskil** [comment]
Issue #1027 was about the package creation dialog, which has been made modal in the patch mentioned. This issue is about the flight creation/edition dialog, which is not modal as of now. I'll provide a patch which makes the flight dialog modal as well.
