### ISSUE TITLE
Abu-al-Duhur has no ATC frequency on kneeboard

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#1972]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/1701873298

### Description

Abu al-Duhur on the Syria map has no ATC frequency generated on the kneeboard.

![Capture](https://user-images.githubusercontent.com/72491792/150701790-95a32ffd-abd8-4e26-b98b-620a92507836.JPG)

### Save game and other files

[Peace Spring A-10C #3306.zip](https://github.com/dcs-liberation/dcs_liberation/files/7921653/Peace.Spring.A-10C.3306.zip)

**Comment by Raskil** [comment]
It seems like https://github.com/dcs-liberation/dcs_liberation/commit/011d8a4e122cf9cc107fd7ba91104f4621338747 fixed the issue mentioned here. Test on develop always came up with proper atc frequencies on the kneeboard for the A-10C II in the Peace Spring Campaign. We will close the issue for now, @Starfire13 will reopen an issue if he encounts it again.
![page00](https://user-images.githubusercontent.com/6024867/158037527-e6c5eb82-9d8c-49ee-a9de-519710b72ffd.png)
