### ISSUE TITLE
A-10C II using UHF radio instead of VHF for flight comms

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#1973]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/1701873298

### Description

At the moment, both the intraflight frequency and ATC frequency are set on UHF. Intraflight channel should be set to VHF.

### Save game and other files

[Peace Spring A-10C #3306.zip](https://github.com/dcs-liberation/dcs_liberation/files/7921655/Peace.Spring.A-10C.3306.zip)

**Comment by MetalStormGhost** [comment]
I found a comment in 5e35efcaef5a1e526a142768b65712773f2c9090 related to this:
**UHF Intraflight Frequency for Player and Clients A-10C**

In the mission editor, using a VHF frequency for a Player or
Client A-10C results in an error. Changed the radio definitions
to use AN/ARC-164 for intraflight comms.

There is also a link to an issue on the Eagle Dynamics forums in the aircraft yaml, but that link isn't working (at least for me). I wonder if this DCS issue still exists?

**Comment by DanAlbert** [comment]
That rings a bell. If that's no longer an issue we should change it back.

**Comment by DanAlbert** [comment]
DCS still does not allow this.
