### ISSUE TITLE
Second last created package flightpath lines not refreshing properly after being dragged

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#1974]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/1701873298

### Description

If you create a number of packages (n>1), the package that you created just prior to the newest one will show this problem. Packages created prior to the second last will not, nor will the most recently created package. If you drag the flight paths of any flight in that second last package, the flight paths do not refresh properly. See example here:
![Capture3](https://user-images.githubusercontent.com/72491792/150712163-4d934843-b92c-40d9-8ff2-15b321c6e4b9.JPG)

Note that this issue will not show up in a downloaded save file. You have to actually create 2 packages for it to show up.

### Save game and other files

Here is a save file with 2 packages created. Delete them and recreate them (or just make another 2 packages, you just have to make two new ones) to experience the bug

[Peace Spring A-10C Part 2 #3306.zip](https://github.com/dcs-liberation/dcs_liberation/files/7922217/Peace.Spring.A-10C.Part.2.3306.zip)
.

**Comment by DanAlbert** [comment]
Map was redone. Should be obsolete.
