### ISSUE TITLE
Set bomber Altitude in Liberation mission planner

### ISSUE THREAD

**Issue by NeelKulkarni6** [dcs-liberation/dcs_liberation#1975]
**Is your feature request related to a problem? Please describe.**
All too often in liberation when I set my bombers to go on a strike mission, be it B-52s or b-17s, I find that they are at an unsatisfactory altitude. It makes no sense that the high altitude bombers are forced to fly low, in range of AAA and manpads. Sure you can change it manually in the dcs mission editor, but that is tedious, especially with a lot of bombing missions planned. 

**Describe the solution you'd like**
Have an adjustable, altitude that the bombers fly at by default. Thi scan maybe be adjusted in liberation settings or in the mission settings. This will allow us to decide if they fly low or high easier.

**Comment by Starfire13** [comment]
Covered under https://github.com/dcs-liberation/dcs_liberation/issues/270

**Comment by DanAlbert** [comment]
Help me avoid duplicate bugs. How do I make this more obvious than pinning it to the top of the bug tracker?

**Comment by DanAlbert** [comment]
This is actually your second dup of that bug: https://github.com/dcs-liberation/dcs_liberation/issues/891. All things about flight plan customization are that bug.
