### ISSUE TITLE
Static object ships defined as custom strike targets not staying dead

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#1976]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/1701873298

### Description

Ships parked along the coast on the Syria map that have been defined as custom strike targets are getting destroyed, but re-appear on the next turn.

![Capture1](https://user-images.githubusercontent.com/72491792/150790008-c28ce922-4f75-4ad8-96c3-8f78e4bab369.JPG)

I have attached a save where all four ships in the picture above have been bombed and observed to have sunk (and I got the red "destroyed" BDA message on screen). However, they are alive again on the next turn. I have tested this twice on two separate groups of ships, and am getting the same result.

### Save game and other files

[Files.zip](https://github.com/dcs-liberation/dcs_liberation/files/7925838/Files.zip)

ASlong with the .miz and the state.json, there are two .liberation saves in the zip file. The on labelled "part 3" was saved just prior to playing that turn. "Part 4" was saved right after results were accepted.

**Comment by RndName** [comment]
Interesting. Some observation: The recent change with the "map object is dead" trigger seems not to be triggered. Only the kill event hook will write the map object id to the state.json "79101952" is the Karaboudjan. As we do not track this ID anymore the kill does not get recognized.

The question is: Does the trigger not work on ships or is the trigger not positioned correctly to recognize the kill.

Workaround could be to track both Name and ObjectID but this will also result in the original problem again with map objects after ED updates the map.

**Comment by RndName** [comment]
Ok it is definetly because DCS does not fire the trigger. even when i manually create the trigger zone and rule
![grafik](https://user-images.githubusercontent.com/6678803/151243311-4924fb95-2ed2-40cb-9ae2-944e17327437.png)

![grafik](https://user-images.githubusercontent.com/6678803/151243458-b96d6a61-64cc-460c-b63b-d3b06d939bb8.png)

Could be reported to ED.
Unitl then i will think about a way to solve this one

**Comment by RndName** [comment]
https://github.com/dcs-liberation/dcs_liberation/issues/1894

**Comment by RndName** [comment]
Would be good to have some testing to identitfy which scenery objects can be tracked at all and write this one down to https://github.com/dcs-liberation/dcs_liberation/wiki/Custom-Campaigns#map-objects

Currently this is mostly used for structures which generate income and have some strategic matter. these statics ships wont. so not a really important issue to fix in short term

**Comment by Starfire13** [comment]
I'll just remove ships from my custom strike targets for now.
