### ISSUE TITLE
NASAMs still project an 'air defense' threat zone with the search radar destroyed

### ISSUE THREAD

**Issue by Hornet2041** [dcs-liberation/dcs_liberation#1978]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/1743270423

### Description

In DCS the NASAM cannot fire without its search radar. I tested this by deploying 2 NASAM sites in a clean mission with an E-3 AWACS for any possible datalink function and a drone MiG-29 flying over the sites repeatedly. It was never fired on.

Campaign save and nasam demo test mission attached plus a screenshot of the NASAMs projecting threat zone with SR dead:
![image](https://user-images.githubusercontent.com/55866858/151186701-4e1ff2aa-d8e6-4390-a72c-ab50f56965c7.png)
![image](https://user-images.githubusercontent.com/55866858/151186849-3252b438-6989-4157-a74c-baad8e99d15c.png)

### Save game and other files

[china vs blufor peace spring.zip](https://github.com/dcs-liberation/dcs_liberation/files/7942693/china.vs.blufor.peace.spring.zip)

**Comment by RndName** [comment]
![grafik](https://user-images.githubusercontent.com/6678803/151515415-14def35f-bf78-4c0b-921b-2ed66dfce1b3.png)

Will now be calculated correctly and marked as "damaged"
