### ISSUE TITLE
Problems with Wingman Comms on F16 Viper

### ISSUE THREAD

**Issue by clarasdk** [dcs-liberation/dcs_liberation#198]
First of I love the work that is being put into this.

I have started playing around with Liberation 2.0 (latest version) and I am using it with the F16 Viper. I have problems with the Comms though. I can hear the calls from my wingman (mudspike etc) But he does not follow my orders. I have tried with and without easy comms. If I go into the mission with the mission editor and change the flight comms to 305 it seems to work. It might be me doing something wrong, but I have a feeling that something is not generated correct?

**Comment by DanAlbert** [comment]
Works for me. Started the mission, set COM2 to channel 1, keyed COM2, Flight, Radar Off. Wingman responded.

**Comment by Starfire13** [comment]
Don't know if it's related but on the Hornet, I have to leave both radios on channel 1, and communicate with my wingman on radio 1, and with ATC on radio 2. Wingman won't talk to me on radio 2 and ATC won't talk to me on radio 1, even though channels are the same.

**Comment by clarasdk** [comment]
Thanks for inputs will try some more....

**Comment by clarasdk** [comment]
Tested it and the only way I can make the radio work is by editing the missions before I start. When I go into the editor the radio freq is 123 am, when I change it to 305 am and go into the airplane the comms to my wingman is white and everything works. I have not clue if this is a bug or it is just me being a noob.

**Comment by clarasdk** [comment]
Ok, did some more testing. The problem seems to be related to using the easy comms setting as it is only sending in uhf and not vhf. I tried to turn it off and made it work with rctrl+/. I have been using easy comms in other missions without problems. So I dont know what causes the problem here. But it is not a game breaker bug. Thanks for the patience with me :)

**Comment by DanAlbert** [comment]
> Don't know if it's related but on the Hornet, I have to leave both radios on channel 1, and communicate with my wingman on radio 1, and with ATC on radio 2. Wingman won't talk to me on radio 2 and ATC won't talk to me on radio 1, even though channels are the same.

The channel _numbers_ are the same. The frequencies assigned are not.

**Comment by Starfire13** [comment]
> The channel _numbers_ are the same. The frequencies assigned are not.

Huh. I learned something new today. I always assumed they used the same frequency set. Good to know. Thanks!

**Comment by DanAlbert** [comment]
It varies from aircraft to aircraft. The F/A-18 has two identical radios with distinct sets of preset channels, others like the F-16 have a UHF radio and a VHF radio, and the JF-17 has two identical radios with shared presets.
