### ISSUE TITLE
Unexpected error on mission generation: "Duplicate convoy unit"

### ISSUE THREAD

**Issue by ColKernel0x8E** [dcs-liberation/dcs_liberation#1982]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/suites/4965852300/artifacts/144595938

### Description

The mission failed to generate with an unexpected error of a duplicate convoy unit:
![duplicate convoy](https://user-images.githubusercontent.com/84617346/151655550-06d09beb-7573-4ebb-b422-d4ad238642d2.PNG)

During mission planning I wanted to move ground units toward the frontline, so I manually ordered a number of ground unit transfers from control points behind the frontline. Hence there are 5 active convoys on my side. I think I may have closed Liberation and reopened it before ordering the transfers, as mentioned in #1247.
 
Cancelling the transfer of 8 units from Abu al-Duhur to Tabqa seems to resolve the error and allows the mission to be generated. I believe this transfer was generated by the AI mission planner itself (but can't remember for sure):
![transfers](https://user-images.githubusercontent.com/84617346/151656045-b41c1bbc-ac88-41a8-a84d-fef0ce71a45c.png)

### Save game and other files

The zip contains the save file, log file and state.json. No new .miz was generated, so I haven't included the nextturn.miz.
[duplicate_convoy.zip](https://github.com/dcs-liberation/dcs_liberation/files/7963395/duplicate_convoy.zip)

**Comment by DanAlbert** [comment]
What build number is that? The download link isn't useful, we just need to know what revision it is.

**Comment by ColKernel0x8E** [comment]
Ah sorry. It's 6.0.0-3315

**Comment by DanAlbert** [comment]
https://github.com/dcs-liberation/dcs_liberation/actions/runs/1709624713

3315 isn't a merged build, it's a PR that isn't ready yet, but the changes almost certainly didn't cause this.

**Comment by DanAlbert** [comment]
Has this problem recurred? We had a number of problems in this area that have been fixed, and looking at the code we currently have I don't see how this could be possible. This is one of those bugs where we need the _previous turn's_ save game to debug (the save game of the current turn has already had the damage done).

Dropping from 6.0.0 and closing since I believe this has since been fixed, but it's easy to reopen if that's not the case.

**Comment by ColKernel0x8E** [comment]
Thanks for checking up on this. The problem hasn't recurred, so I'm convinced it's been fixed in the more recent versions.
