### ISSUE TITLE
Budget is not rounded

### ISSUE THREAD

**Issue by Brausepaul** [dcs-liberation/dcs_liberation#1983]
### Affected versions

5.1.0

### Description

Budget (income and balance) is not rounded in Intelligence and Finances screen.

### Save game and other files

Any save game will do, I guess. I would expect to see the same value as shown right beneath Budget info in main screen.
![Screenshot](https://user-images.githubusercontent.com/13948653/151658897-551b6b22-f044-4613-98b4-37e44bcfc97d.png)
.

**Comment by Raskil** [comment]
Wasn't able to replicate this on 6.0. Fo me it looks fine:
<img width="618" alt="budget" src="https://user-images.githubusercontent.com/6024867/158016404-1ab61544-89f5-4f5b-9bbc-07680deaa6b7.png">
The code has rounding implemented as well:
```
self.finances.setText(
   str(round(budget, 2)) + "M (+" + str(round(reward, 2)) + "M)"
)
```
@DanAlbert Should I remove the 6.0 label or how would you like to proceed with that?

**Comment by Hornet2041** [comment]
They still exist on 6.0 builds:

![image](https://user-images.githubusercontent.com/55866858/158017026-76d1764f-45e0-4ba9-ba57-1b0bb6951db7.png)

![image](https://user-images.githubusercontent.com/55866858/158017063-aa927fb7-738b-469c-9575-5b27ef5baa4b.png)


This was generated by setting income multiplier to 0.4x

**Comment by Starfire13** [comment]
Looks like it only happens if the multiplier is changed. I always have my multiplier on the default 1.0 so it's not an issue I've come across thus far, but it starts to occur once I change the multiplier.

**Comment by Brausepaul** [comment]
I can confirm that my multiplier was changed and was different from 1.0

**Comment by DanAlbert** [comment]
This is why we ask for save games. It removes the guesswork.

**Comment by Raskil** [comment]
Sorry guys, I've missed the multiplier. Will give it another shot.

**Comment by Raskil** [comment]
Question; What is the expected number of decimal places we would like to show on the dialog? 1 as in the budget top panel?

**Comment by DanAlbert** [comment]
1 decimal place sounds like plenty of precision to me.
