### ISSUE TITLE
CTD after repeating errors when going to Air Wings Tab

### ISSUE THREAD

**Issue by subsonic-pilot** [dcs-liberation/dcs_liberation#1986]
### Affected versions

5.1.0

### Description

When trying to transfer helo units to a newly captured FOB, when I click on the "Air Wing" tab I get an error message reading: 

An unexpected error occurred
'NoneType' object has no attribute 'name'
Traceback (most recent call last):
File "delegates.py", line 113, in sizeHint
File " windows)AirWingDialog.py", line 48, in text for
AttributeError: "'NoneType' object has no attribute "name'

This error will immediately reappear about a dozen times after clicking the X or OK options then take me to the Air Wings page. However, if I scroll on this page the same error as listed above as well as a second error code will alternate, and I will need to exit each of those messages a dozen times each, and then the Liberation program will crash to desktop on the final error being exited. The secondary error reads:

An unexpected error occurred
'NoneType' object has no attribute 'name'
Traceback (most recent call last):
File "delegates.py", line 68, in paint
File "windows\AirWingDialog py", line 48, in text for
AttributeError: "NoneType' object has no attribute "name'

### Save game and other files

[WPUSLiberationPG - Copy.zip](https://github.com/dcs-liberation/dcs_liberation/files/7968396/WPUSLiberationPG.-.Copy.zip)

[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/7968401/liberation.log)

[state - Copy.zip](https://github.com/dcs-liberation/dcs_liberation/files/7968404/state.-.Copy.zip)

**Comment by DanAlbert** [comment]
This seems to just be a corrupt save. There doesn't appear to be any way for a `None` squadron location to occur. It'd not debuggable because whatever circumstances caused the location to become `None` have already happened, so we can't determine what the cause is.
