### ISSUE TITLE
UI oversized

### ISSUE THREAD

**Issue by JeffreyCor** [dcs-liberation/dcs_liberation#1987]
### Affected versions

Development build

### Development build

6.0.0-3348-preview

### Description

Liberation UI is oversized under recommended settings even on 4K display causing right side to be cut off or time control buttons to be unusable. 

Issue persists with 1080P displays as well as 4K under recommended scaling. Removing scaling makes text very small on 4K display overall and in Liberation.

### Save game and other files

![CreatedCampaign](https://user-images.githubusercontent.com/7409930/151744397-e289e8ca-64ac-4b53-9104-2a60e6fc614b.jpg)
![ResetFullScreen](https://user-images.githubusercontent.com/7409930/151744403-d7894ffe-9487-44d2-a264-773786b75e4f.jpg)
![smalltext](https://user-images.githubusercontent.com/7409930/151744406-4e756f92-eb42-4a45-b0de-aef9b3cc7366.jpg)
![recomendedscaling4K](https://user-images.githubusercontent.com/7409930/151744409-4384ae1a-3eed-4145-9a47-f75fe418ce55.jpg)

**Comment by JeffreyCor** [comment]
Forgot to mention, this only shows after the campaign has been created. When first starting with no campaign loaded everything fits on the screen fine in all cases. Once the campaign has been created the UI sizing issue shows.

**Comment by ataribaby42** [comment]
Have same problem on 1680x1050

**Comment by Raskil** [comment]
It seems somebody set os.environ["QT_AUTO_SCREEN_SCALE_FACTOR"] = "1"  # Potential fix for 4K screens for the ui windows but forgot about the dpi scaling attributes. When I set 
    app.setAttribute(Qt.AA_EnableHighDpiScaling, True)  # enable highdpi scaling
    app.setAttribute(Qt.AA_UseHighDpiPixmaps, True)  # use highdpi icons
for the window as well, it works fine on my 4k screen as well as on my 1080p screen. 

#2049 might be fixed as well.
