### ISSUE TITLE
F/A-18C have inverted radio usage (possibly)

### ISSUE THREAD

**Issue by Robune** [dcs-liberation/dcs_liberation#1992]
### Affected versions

5.1.0

### Description

DCS Liberation assigns ATC & primary tactical frequencies (AWACS, etc...) on F/A-18C's Radio 2 (COMM 2), and intra-flight frequencies on Radio 1 (COMM 1). From my understanding, this would typically be the opposite in the real aircraft (taking MIDS into account).

This mudspike post has an (alleged) Hornet driver mentioning typical use of the radios. https://forums.mudspike.com/t/how-are-you-guys-using-the-radios-in-dcs/10433/67

In the attached files you can see how the carrier and the AWACS are on COMM 2 (channels 1 & 2), while the flight is on COMM 1 (channel 1). There's a tanker on COMM 2 also.

I think  this should be reversed, although the tanker can probably stay on COMM 2 (the above-mentionned post does mention having a tanker on COMM 2, although it also mentions using MIDS for intra-flight communication then).

### Save game and other files

[Uploading FA-18_radios.zip…]()

**Comment by DanAlbert** [comment]
That's how DCS works for the hornet. The AI uses radio 1 channel 1 for flight comms.
