### ISSUE TITLE
[RC6] Supercarrier tacan not working F/A-18C

### ISSUE THREAD

**Issue by MysticDaedra** [dcs-liberation/dcs_liberation#2]
Glad you got this set up, feels much more organized for submitting bug reports!

Anyways, the tacan doesn't seem to be working on the supercarrier. I'll punch in the correct channel (45X), cage TCN on the HSI (I'm using the F/A-18C), but the arrow keeps spinning and the bug on the HUD never shows up. Consequently, I cannot set the BRC or do CASE III landings. I checked on the forums to see if it was a bug with the Hornet, but I didn't see anything. It seems to work on my squadron's private server, running Into the Inferno.

**Comment by Khopa** [comment]
Thank you for your report. 

In DCS Liberation 2.0RC6, the Tacan could be set to channel Y for the carrier (The tacan channel is assigned randomly at campaign start) 

But I then figured out that it was not possible to set up the carrier tacan channel to mode Y. And I encountered the same issue, even when dialing the correct Tacan channel it would not work. 

From next version, the carrier Tacan channel will always be in X mode.

Are you sure your carrier channel was not set to 45Y and not 45X ?  I'll re-run additional tests later btw.
If you still have the .miz file, i'd be interested to have a look.

**Comment by MysticDaedra** [comment]
I was going by the TACAN listed in the briefing, and it _said_ that it was 45X. I honestly didn't think to check if it was actually set to Y. The weird thing is that whatever the briefing said, wasn't correct.

**Comment by TezzaCourtney** [comment]
Hi Khopa,

I checked in RC8 last night with a new campaign (Emirates) and the TACAN was being set to 45Y for the carrier still (SC enabled)

If I switch to 45Y the TACAN is recognized correctly as CVH, but no range or bearing information is returned.

This is with the Hornet and I ensured that only T/R mode was engaged.

**Comment by Khopa** [comment]
I have done some tests. The TACAN seems to be always set up as X in RC8 in the generated mission, not sure what is done wrong : 

![image](https://user-images.githubusercontent.com/2546901/85623665-0d595100-b669-11ea-88db-65acc2fef327.png)

So i have this in the briefing : 

![image](https://user-images.githubusercontent.com/2546901/85622896-d6367000-b667-11ea-897e-e82a2d369de7.png)

I'm not sure whether it's a DCS bug or not, but, with TACAN in set up as 48X T/R only i get this : 

![image](https://user-images.githubusercontent.com/2546901/85623006-00882d80-b668-11ea-8533-66863175cbe2.png)

With TACAN set up to 48Y, i get this : 

![image](https://user-images.githubusercontent.com/2546901/85623078-1b5aa200-b668-11ea-9a65-6545ced1bb8f.png)

So it's weird, i get better information (there is the "ACC" code) which is what you got as well. (And i'm not sure if it is a DCS bug or not)

However, i have noticed that with TACAN set up to 48X, T/R + A/A :

![image](https://user-images.githubusercontent.com/2546901/85623161-45ac5f80-b668-11ea-878f-8f3f984b9dcb.png)

Now it looks OK, i have bearing information and the icon on the HSI. 

Maybe i'm missing something though, i'm not a TACAN specialist. So i have a big doubt, for me A/A was for Air to Air TACAN, to find another plane, such as the Tanker. 

I'll do test in other mission later.

**Comment by Khopa** [comment]
Ok i found the issue, i forgot a parameter in the TACAN object injected in the mission file. It is an AA Tacan beacon that was being set up by DCS liberation (this is a parameter that does not appear in the editor (since it would not make sense to put the carrier as an A/A Tacan), but only exists in the mission file structure.)

Now it is Ok, with 48X T/R only !

![image](https://user-images.githubusercontent.com/2546901/85628787-ffa7c980-b670-11ea-8749-8037ce37eb13.png)

So it will finally be correctly fixed in next version !

Thanks for noticing and reporting the issue @TezzaCourtney

**Comment by Khopa** [comment]
Should be fixed in https://github.com/Khopa/dcs_liberation/releases/tag/2.0RC9
