### ISSUE TITLE
RC9 Problem with Cold War map units.

### ISSUE THREAD

**Issue by Krag6** [dcs-liberation/dcs_liberation#20]
While most units are correctly replaced in the cold war scenarios, Having a Oliver Hazard Perry class boat right near the coast is absolutely devastating to any AI flights. Trying to play 1965 scenario with realistically unsinkable murdersams on my doorstep is rough. This ship is not even gonna be commissioned for 10 years.

**Comment by Khopa** [comment]
Oh yes, that's a mistake. 
I'm removing Perry from bluefor coldwar faction.

**Comment by Khopa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Oliver Hazard Perry class for Cold War factions is unrealistic](https://trello.com/c/w2aFoSMW/116-oliver-hazard-perry-class-for-cold-war-factions-is-unrealistic)

**Comment by Khopa** [comment]
Perry should have been removed from bluefor coldwar factions in latest versions. Closing.
