### ISSUE TITLE
Mission frequencies in briefing

### ISSUE THREAD

**Issue by linmar22** [dcs-liberation/dcs_liberation#200]
It would be nice to see the channel presets in the mission briefing.

**Comment by DanAlbert** [comment]
For every aircraft? That'll get cluttered really fast.

They're in the kneeboard. Is there something specific you want in the briefing as well?

**Comment by DanAlbert** [comment]
The briefing will now point you to the kneeboard. Had a handful of other people ask the same question and they just didn't know to check the kneeboard, so that should clear up the confusion.
