### ISSUE TITLE
Error Pop-up

### ISSUE THREAD

**Issue by Eagle01ph** [dcs-liberation/dcs_liberation#2000]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/1797094266

### Description

Hi,

On the v6.0.0-3368 preview build.  

After creating a new WW2 campaing with a faction that has the Mosquito included as a flyable aircraft.  Buy the Mossie and begin campaign.  After assigning a mission to the Mossie, double click the flight to edit it's loadout.  The error below pops up.  And you will not be able to edit the loadout.

![image](https://user-images.githubusercontent.com/84751885/152681146-01e40b35-d02d-4e55-91a1-52007c796c89.png)

And similar error happens to the JF-17.  Start any campaing that has the JF-17 as a flyable aircraft.  But the Jf-17 and beging the campaign.  After assigning a mission to a flight of JF-17s.  double click the flight to edit it's loadout.  The error below pops up and prevents you from editing the loadout.

![image](https://user-images.githubusercontent.com/84751885/152681407-95a0f203-227a-4165-aec8-ecef5ba1fbe9.png)

### Save game and other files

[Flight editing errors.zip](https://github.com/dcs-liberation/dcs_liberation/files/8010217/Flight.editing.errors.zip)
[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/8010218/liberation.log)

**Comment by Starfire13** [comment]
The issue with the Mossie is currently being fixed: https://github.com/dcs-liberation/dcs_liberation/pull/1926

As for the JF-17, check that you don't have any invalid custom loadouts for it in the DCS mission editor.

**Comment by Eagle01ph** [comment]
Thanks.  The JF-17 is now fixed.

**Comment by Starfire13** [comment]
Great. By the way, a temporary workaround for the Mossie issue is to remove rockets from your loadouts for now. They're the ones causing the problem.
