### ISSUE TITLE
Campaign engine

### ISSUE THREAD

**Issue by Danguard63** [dcs-liberation/dcs_liberation#2004]
### Affected versions

5.1.0

### Description

I think something it's seriously different in the campaign engine from the older version. I remember perfectly that in the older versions after 2 or 3 turns with the massive destruction of enemy ground units i had the control of an enemy base. Actually in the campaign Multipart Russia i completely destroyed all units in Sochi-Adler airbase but the frontline it's in the same position. I remember that in the same situation in the older version (3-4 versions before) i had the complete control of the airbase.

### Save game and other files

[liberation_nextturn.zip](https://github.com/dcs-liberation/dcs_liberation/files/8028206/liberation_nextturn.zip)
[caucas3.zip](https://github.com/dcs-liberation/dcs_liberation/files/8028207/caucas3.zip)

**Comment by Starfire13** [comment]
User had unit movement turned off. Resolved on Discord.
