### ISSUE TITLE
'Squadron' object has no attribute 'female_pilot_percentage' - blocks accepting turn results

### ISSUE THREAD

**Issue by Hornet2041** [dcs-liberation/dcs_liberation#2005]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/1814652106

### Description

![image](https://user-images.githubusercontent.com/55866858/153113399-2946b8cf-a60d-4d6b-a0f5-1f5ff4f0ab19.png)

Started a new game with the build, custom faction vs custom faction in the black sea coastal campaign. Played a turn, submitted results, and that error pops up. Unable to accept results / progress campaign.

### Save game and other files

[female pilots reeeeee.zip](https://github.com/dcs-liberation/dcs_liberation/files/8029044/female.pilots.reeeeee.zip)
campaign save, .miz, and state file attached

**Comment by DanAlbert** [comment]
I guess that property isn't optional. It probably should be.

**Comment by DanAlbert** [comment]
Except yes it is. There's something wrong with the squadrons in your save. You sure you created the game with the same build you're running?

**Comment by Hornet2041** [comment]
..... yes?

**Comment by Hornet2041** [comment]
![image](https://user-images.githubusercontent.com/55866858/153141934-739da641-8e4d-4812-816b-87db55fd291b.png)
![image](https://user-images.githubusercontent.com/55866858/153142021-9d737057-4901-4990-9bb8-7e20623f282a.png)
there's no clear option in the present-squadron window or the add-squadron window to set a female pilot ratio

**Comment by DanAlbert** [comment]
It doesn't matter that the UI doesn't have an option; the squadron already exists. There's only one way they get created anywhere in the code afaict and it's not possible for this to not be set when it gets created. I cannot reproduce the same results by creating a fresh mission. I haven't tried your save, but the error message already tells me that the save is corrupt. It won't tell me how it was corrupted, and that's the problem.

The issue persists if you create a new game and try again?

**Comment by Hornet2041** [comment]
unable to reproduce on a new game.... i strongly suspect it was the identical squadrons i had in my saved games folder that did not have the female pilot percentage value that was causing the error though on some investigating - i removed those and played a new campaign and it accepted fine.
