### ISSUE TITLE
Add a new loadout option for f16 ALQ-184 long jammer

### ISSUE THREAD

**Issue by mikef-phy** [dcs-liberation/dcs_liberation#2008]
Before filing, please search the issue tracker to see if this feature has already been requested.

If requesting a DCS AI feature, check If reporting a DCS AI bug, check https://github.com/dcs-liberation/dcs_liberation#dcs-bugs.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by DanAlbert** [comment]
Please fill out the thing. Idk what you're asking for.

If you're just asking for the default loadouts to change, we decided not to because there's no benefit that we know of. You can trivially customize your own default loadouts though.

If you're asking for something else, idk what it is.
