### ISSUE TITLE
All squadrons of the same aircraft type are using the same preset squadron

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#2011]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/1835083770

### Description

In this dev build, all the squadrons for the same aircraft type are using the exact same preset squadron. For example, in the picture below, there are multiple VMA-214 Black Sheep squadrons. This wasn't the case in previous dev builds a while back (e.g. #3349) nor in 5.1 release.

![Capture3](https://user-images.githubusercontent.com/72491792/153734182-2bcd8e37-8ed5-408f-9f2a-fb082de1089d.JPG)

### Save game and other files

This zip file contains two saves, one created with 5.1 release and one with #3432. Campaign and faction settings are identical. You'll see that in the 5.1 version, each squadron is unique. In the 6.0 version, all the squadrons for the same aircraft type are identical.

[Saves.zip](https://github.com/dcs-liberation/dcs_liberation/files/8054790/Saves.zip)

**Comment by Raffson** [comment]
Can you confirm this is only the case for blue? On my end red does actually generate different names/nicknames.

**Comment by Raffson** [comment]
I think I've got it already, by the looks of it squadrons aren't being "claimed" properly, expect a fix in the next couple of hours 👍

**Comment by Raffson** [comment]
https://github.com/dcs-liberation/dcs_liberation/blob/1bee29de83f0a05212acff9ed4aa71fd811837b8/game/campaignloader/defaultsquadronassigner.py#L169

Tracked it down to this line, `dataclass.replace` constructs a new object and afaict the original object is the one being used to check the "claim". Therefore "claiming" the squadron in `Squadron.create_from` doesn't have any effect.
