### ISSUE TITLE
Front Line stucked

### ISSUE THREAD

**Issue by DevastatorCM** [dcs-liberation/dcs_liberation#2019]
### Affected versions

5.1.0

### Description

It looks like front line is bugged and not moving although all frontline units are getting killed every single turn by blufor forces. I suspect the issue is due to a wrong unit in redfor side. One SA-13 has no type visible in ME. Screenshots and the mission are all attached

### Save game and other files

[bug files.zip](https://github.com/dcs-liberation/dcs_liberation/files/8112428/bug.files.zip)

**Comment by Hornet2041** [comment]
This needs the .liberation save game too. Can't do much with the files provided otherwise.

**Comment by DevastatorCM** [comment]
[campaign.zip](https://github.com/dcs-liberation/dcs_liberation/files/8114781/campaign.zip)
sorry I forgot that one :)

**Comment by Hornet2041** [comment]
![image](https://user-images.githubusercontent.com/55866858/155203491-b3c8a584-9c57-408f-89de-67fe459eac20.png)
The frontline is where all those units actually spawn.

The FOB is that cluster of circles to the southwest. 

In between is a massive forest. DCS units go _very slowly_ through forests. Unless you want to wait 8 hours for them to reach it, I recommend just enabling cheats and capturing the FOB manually.

edit: if you do that, remember you have to manually transfer the frontline units from Tblisi to the FOB.
