### ISSUE TITLE
Option to remove map/WP kneeboard pages

### ISSUE THREAD

**Issue by ghost** [dcs-liberation/dcs_liberation#2028]
For a few reasons, the initial individual waypoint pages of the generated kneeboard, where the waypoints are superimposed over the map, are generally useless.  A lot of the time, the waypoints are too close to be legible, for instance, on the overall flight plan page (last 'map page').  Personally, I find these pages redundant since the HSI holds the sequence of the waypoints.  

There should be an app option to simply omit generating them, or move them to the end of the generated pack?

**Comment by DanAlbert** [comment]
We don't generate those. Those are automatically added by DCS. They are present in every mission.
