### ISSUE TITLE
Game-breaking error on WWII campaign Normandy

### ISSUE THREAD

**Issue by ObsceneNickname** [dcs-liberation/dcs_liberation#2029]
### Affected versions

5.1.0

### Description

As title, there's a game-breaking error when you press "Begin Campaign" after the generation of a WWII Normandy Campaign.

![immagine](https://user-images.githubusercontent.com/65090780/155602951-b5e48814-1f70-48aa-8147-2bd4ecfb9bf4.png)

Even if you can kind of continue despite this error message, the generation of missions seems broken and there's no enemy planes and no units on the front-line. Tried multiple times and it happens always.

### Save game and other files

[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/8135593/liberation.log
[WWII seria.zip](https://github.com/dcs-liberation/dcs_liberation/files/8135602/WWII.seria.zip)

**Comment by Starfire13** [comment]
https://github.com/dcs-liberation/dcs_liberation/issues/2000

**Comment by DanAlbert** [comment]
(@Starfire13 you should be able to close dups, btw. Feel free to do so)

**Comment by Starfire13** [comment]
I couldn't figure out how to to close stuff on the Github mobile app but I think I've just figured it out. It's in the drop down list in the top right corner.
