### ISSUE TITLE
A-10C II: can't load APKWS on TER

### ISSUE THREAD

**Issue by unixwitch** [dcs-liberation/dcs_liberation#203]
in-game, stations 3, 4, 8, 9 can be loaded with 3x LAU-131 carrying APKWS (M151 or M282) for a total of 21 rockets per station.

however this can't be selected from the custom loadout tab in the DCS Liberation mission selector - only the standard LAU-131 with 7 rockets per station is available.

**Comment by walterroach** [comment]
@DanAlbert   - this one is fixed for the 2.2 release.
