### ISSUE TITLE
SA-13 site showing as degraded in Liberation UI even though none of its units have been destroyed

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#2033]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/1897885878

### Description

SA-13 sites in dev builds after the ground object rework are showing as degraded upon campaign generation, with all units still intact.

![Capture](https://user-images.githubusercontent.com/72491792/155806681-627a197a-d40b-4aa7-8ccc-127f24cb208b.JPG)

Contrast this with an SA-13 site in 5.1 release build.

![Capture2](https://user-images.githubusercontent.com/72491792/155806741-285da3c1-d8ae-40c8-9d8a-cd06bbc49cac.JPG)

### Save game and other files

[Vegas Nerve #3506.zip](https://github.com/dcs-liberation/dcs_liberation/files/8144995/Vegas.Nerve.3506.zip)

**Comment by RndName** [comment]
solved with https://github.com/dcs-liberation/dcs_liberation/commit/762bc328e12e74824c1b4984ba6b6ebfd96aa2c0
