### ISSUE TITLE
Can't damage ground targets

### ISSUE THREAD

**Issue by TinmanViper** [dcs-liberation/dcs_liberation#2034]
### Affected versions

5.1.0

### Description

When shooting a ground target which is also visible. Nothing happens. Also when switching to guns the bullets just pass through and no damage is done. I had this happen on multiple occasions.

### Save game and other files

[First_Campaign.zip](https://github.com/dcs-liberation/dcs_liberation/files/8146813/First_Campaign.zip)
[state.zip](https://github.com/dcs-liberation/dcs_liberation/files/8146814/state.zip)

**Comment by Starfire13** [comment]
Can you provide more information? Which ground target? What were you shooting it with (apart from guns)?

**Comment by TinmanViper** [comment]
Hi,

Thanks for the reply I’m glad you’re looking into it. I am not at home now
so more in depth information is possible later. However if it is of any
help (from memory) if you open the .liberation file. You see there is one
player f-18. That was me. I made several waypoints and i flew towards my
first target which was at waypoint 2. I don’t exactly remember what the
target was called but it was some vehicle with missiles? Two of them. I was
planning to destroy the remaining operational (or at least I think) units
at the sights. That was my intention at least.

But after using jsows with good alignment and very close proximity
detonation, they don’t get damaged at all...so I dived towards them and
went for guns but nothing happened even while I got rounds on target...it
just passes through it and out of frustration I kamikazed onto them and I
think even that didn’t destroy them.

I remember this happening some other time where the remaining units were
acting like ghosts.

It’s at those scenes where most units have [dead] behind their unit name
(which I then assume are destroyed in previous sortie?) with a couple
remaining intact ...these were my targets to destroy the last units
remaining at the forward operation point of the enemy side so my own units
can advance

But now I get frustrated because I feel like they are there but I can’t hit
them..

If this is not enough please let me know exactly what you need I will try
to provide the needed information when I get home and can open the file


Op za 26 feb. 2022 om 20:57 schreef Starfire13 ***@***.***>

**Comment by DanAlbert** [comment]
DCS is responsible for damaging units, not Liberation. We can't fix DCS.

**Comment by TinmanViper** [comment]
Ok weird because I only experience this when using liberation.

Op za 26 feb. 2022 om 21:12 schreef Dan Albert ***@***.***>

**Comment by Starfire13** [comment]
A Hornet's 20mm cannon not having an effect on many ground units is to be expected. That is simply the way DCS is. If you can provide clear evidence of a specific ground unit that can be damaged outside of a Liberation mission but not in a Liberation (be it with guns or anything else), that can be looked at (but I will say I have not ever observed anything like that occuring). But as it is, I don't think this is a Liberation issue.
