### ISSUE TITLE
Intel @Kneeboard

### ISSUE THREAD

**Issue by DevastatorCM** [dcs-liberation/dcs_liberation#2041]
**Is your feature request related to a problem? Please describe.**
Not a problem but more a nice to have stuff to give more realism in regard to intel

**Describe the solution you'd like**
If a strike mission is selected to hit the buildings etc., it would be nice if the area where the buildings are added to the kneeboard as satellite and/or topographic image. 
Maybe the DCS object image frop top might be copied over the map which is liberation is using offline to create that kneeboard image.

If this thing is doable, maybe reconnaissance missions can be add later on to the game where such capable aircrafts do reconnaissance missions some turns before to get the necessary image.

**Additional context**
N/A

**Comment by DanAlbert** [comment]
It's not possible. We can't autogenerate these, and campaign authors can't include screenshots in their campaigns because the objective that gets generated is random.

**Comment by DevastatorCM** [comment]
I know it is random but I see that always same buildings are used by the campaigns, i.e. hangar, factory, comm tower. Their pictures might be taken from DCS and mapped over the existing map to generate a picture to be used in kneeboard. If not doable then fine. Was just an idea

**Comment by DanAlbert** [comment]
The satellite map in the liberation UI will not precisely match what it looks like in DCS. We don't have satellite imagery of WW2 Britain. Bad Intel is worse than no Intel.
