### ISSUE TITLE
Normandy campaign is being set in the Marianas

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#2042]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/1930817815

### Description

The Normandy campaign is showing up set in Marianas. The other campaign maps appear to be showing up fine, so it's just Normandy.

![Capture](https://user-images.githubusercontent.com/72491792/156682752-0f3c3141-9d99-4f9c-b4bb-3971b50ebe2f.JPG)

### Save game and other files

[Normandy in Marianas #3557.zip](https://github.com/dcs-liberation/dcs_liberation/files/8182357/Normandy.in.Marianas.3557.zip)

**Comment by Starfire13** [comment]
Attempting to load the save file generates this error:
2022-03-04 12:44:42,652 :: root :: ERROR :: Invalid Save game
Traceback (most recent call last):
  File "game\persistency.py", line 49, in load_game
  File "<string>", line 3, in __hash__
  File "game\theater\frontline.py", line 81, in __hash__
AttributeError: 'FrontLine' object has no attribute 'blue_cp'

**Comment by walterroach** [comment]
The Normandy showing in Marianas issue is a pydcs bug.  I'll submit a PR fixing it over there.

**Comment by walterroach** [comment]
https://github.com/pydcs/dcs/pull/209
