### ISSUE TITLE
Campaigns with Germany WW2 factions cannot be generated

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#2043]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/1930817815

### Description

Attempting to create a campaign using any of the Germany WW2 factions (1940, 1941, 1944, 1944 (free)) generates this error. Error occurs on multiple maps. Allies WW2 factions (including the Soviet 1943 faction) are fine, so it's just Germany.

![Capture2](https://user-images.githubusercontent.com/72491792/156683842-fa95ecce-cb11-48aa-8f4d-08ab9e70c628.JPG)

### Save game and other files

Unable to provide save file as campaign cannot be generated.

**Comment by RndName** [comment]
solved in latest dev build. As a layout was changed you need to re-import the layouts
![grafik](https://user-images.githubusercontent.com/6678803/158692135-cf562c2c-2813-4138-bb02-9b99a46e1ae4.png)
