### ISSUE TITLE
Frontlines / ground units / resource sites not drawn on map upon campaign generation

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#2045]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/1933175585

### Description

Upon campaign generation, only control points and supply routes are being drawn on top of the map. Frontlines, ground units, and resource sites do not show up.

![Capture](https://user-images.githubusercontent.com/72491792/156861970-04d8dc6a-d2ce-45ab-8b4c-f69b7eb4a82f.JPG)

Workaround is to right-click on map and click reload.

### Save game and other files

[Golan #3568.zip](https://github.com/dcs-liberation/dcs_liberation/files/8189572/Golan.3568.zip)

**Comment by DanAlbert** [comment]
(not assigning myself in case anyone else wants to pick it up, but I assume I'll be the one to fix it)

**Comment by Starfire13** [comment]
This is probably related to the same issue (let me know if not and I'll file it separately). When buying a SAM site (after CP capture), UI does not update to show the purchased units until a rightclick-reload is performed.

**Comment by DanAlbert** [comment]
Same cause in the sense that the cause is "Dan goofed", but almost definitely a distinct thing to fix. A second bug would help me keep track, if you don't mind.

**Comment by DanAlbert** [comment]
The new map is the default now so I'm going to call that good enough.
