### ISSUE TITLE
Old packages persist in Packages pane after end of turn/pass turn

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#2046]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/1937618376

### Description

Edit: It appears this can happen to any package, not just ferry packages. See comments.

Squadron transfer ferry flight persists till next turn, although with no destination.

In the same save file provided, I am swapping the location of two squadrons (1 F-16, 1 A-10) between 2 bases.

![Capture](https://user-images.githubusercontent.com/72491792/156882865-45bd900d-ebd2-4964-a4eb-f889fb53a077.JPG)

After hitting pass turn, there is still a ferry package for the A-10s, even though they have already arrived at their destination CP.

![Capture2](https://user-images.githubusercontent.com/72491792/156882916-c7e8280f-cb43-4e6d-ae17-34e781c3fd0e.JPG)

### Save game and other files

Hit Pass Turn. You'll see there is a ferry package remaining.

[Maykop #3573.zip](https://github.com/dcs-liberation/dcs_liberation/files/8190649/Maykop.3573.zip)

**Comment by DanAlbert** [comment]
Could be related (I need to follow up once I have save games that are usable by anyone but me), but I think the ferry might be a red herring here. I had a full ATO and disabled auto-ATO planning but it took several skipped turns for the planned packages to clear.

**Comment by Starfire13** [comment]
I think you're right that the ferry flight is a red herring. Looks like it can happen with any type of package. I just completed a campaign turn only to have 3 packages from the last turn still showing up in the packages pane (1 AEW&C, 1 CAP, 1 BAI)
