### ISSUE TITLE
on player plane spawn pilot veiw goes too outside veiw

### ISSUE THREAD

**Issue by headshothawkins** [dcs-liberation/dcs_liberation#2057]
### Affected versions

5.1.0

### Description

Bug when playing liberation, when loading the mission when you are supposed to be in the pilot seat at mission start the plane jumps of the deck in a random location then loads back in the hanger in a outside view and the player has no control over the plane,  using mouse player can pan the camera

### Save game and other files

files provided all that are asked no error message seen

**Comment by headshothawkins** [comment]
[dcs world liberation crash log 5.1.0.zip](https://github.com/dcs-liberation/dcs_liberation/files/8199875/dcs.world.liberation.crash.log.5.1.0.zip)

**Comment by Starfire13** [comment]
You are placed in an external view while waiting for your start time. This is as intended.

**Comment by headshothawkins** [comment]
thanks for replying. i feel like a tool in the back my mind when tuning the settings i always thought I'd forgot too change one


Sent from Outlook<http://aka.ms/weboutlook>
________________________________
