### ISSUE TITLE
Package flight paths invisible if "show all blue flight plans" is unticked

### ISSUE THREAD

**Issue by Hornet2041** [dcs-liberation/dcs_liberation#2058]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/1945159367

### Description

Unticked "show all blue flight paths", clicked on a package and it did not display any paths or waypoints.

![image](https://user-images.githubusercontent.com/55866858/157145795-939f3be2-7de0-43ac-8cd3-5c53efbb39f6.png)

### Save game and other files

[dust2dust2-3606.zip](https://github.com/dcs-liberation/dcs_liberation/files/8201864/dust2dust2-3606.zip)

**Comment by DanAlbert** [comment]
In other words, bring back the "selected only" option?

**Comment by DanAlbert** [comment]
If so, fixed
