### ISSUE TITLE
no weapon data for GBU 27

### ISSUE THREAD

**Issue by JeffreyCor** [dcs-liberation/dcs_liberation#2059]
### Affected versions

Development build

### Development build

6.0.0-3614

### Description

Year set to June 13, 1995 in the testing, tested on both F-15E and F-16C. Loadout includes GBU-12 bombs which show up correctly in the loadout with Restrict turned off to test. With it turned on, bombs are changed to Mk-82. However, if Use Custom Loadout is turned on the GBU-12 bombs are available. This issue is also in current release 5.1.0-3179.

### Save game and other files

![Bombs Restrict Off](https://user-images.githubusercontent.com/7409930/157170462-6969fefa-8e80-497d-9b37-03c26017531f.jpg)
![Bombs Restrict On](https://user-images.githubusercontent.com/7409930/157170602-b428b9a1-9179-4d75-8098-35596c325e82.jpg)
![Bombs Restrict On custom](https://user-images.githubusercontent.com/7409930/157170827-c8bd040d-a57d-4688-a110-bd3b0d6c1978.jpg)
[6-0 testing GBU-12.zip](https://github.com/dcs-liberation/dcs_liberation/files/8202963/6-0.testing.GBU-12.zip)

**Comment by DanAlbert** [comment]
The GBUs are disappearing because the loadout doesn't have a targeting pod. When date restrictions are on loadouts without targeting pods will be downgraded to iron bombs. Custom loadouts are exempt from this.

**Comment by JeffreyCor** [comment]
Since GBU-27's are not replaced it looked like a bug. Maybe the bug is the GBU-27's not being replaced :) 
![GBU-27](https://user-images.githubusercontent.com/7409930/157191908-d7067d7d-d5a0-454e-a932-67f16b4ed7fc.jpg)

**Comment by DanAlbert** [comment]
We have no data for the GBU-27, so we don't know it's an LGB.
