### ISSUE TITLE
Package flight path remains on map after package is deleted.

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#2062]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/1955044987

### Description

Deleting a package doesn't remove its flightpath until a manual refresh/reload.

### Save game and other files

[Uploading Normandy #3619.zip…]()

**Comment by DanAlbert** [comment]
> `[Uploading Normandy #3619.zip…]()`

The upload didn't work

**Comment by DanAlbert** [comment]
Repro's in a game I just generated. Will upload if I don't end up fixing it.

**Comment by DanAlbert** [comment]
Flight/package deletion events aren't being sent to the front-end. This used to work because deleting packages/flights would cause a full reset of the map. We no longer do that because it's pointlessly expensive, but the front-end needs to be notified.
