### ISSUE TITLE
FOB's behind front line change side at random

### ISSUE THREAD

**Issue by nickjzx** [dcs-liberation/dcs_liberation#2065]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/1797094266

### Description

When pushing forward in the campaign, some FOB's well behind the front line will change to red. Causing front line units to move to adjacent FOBs to the new front lines created. This pulls units from the most forward front line. Expected behavior is to have no base capture events well behind the front line with no enemies to capture it. To reproduce the error, click next turn. It appears to happen at random but a number of bases will go red, regardless of units on the base. All FOBs contain FARPs for helicopters. Mission was hosted on a dedicated server through multiplayer.

### Save game and other files

[f16camp.zip](https://github.com/dcs-liberation/dcs_liberation/files/8233251/f16camp.zip)

**Comment by Hornet2041** [comment]
I passed turns until I hit turn 70, on the linked build. No bases ever flipped.

Generated a mission from the turn saved and there are no blue units on any enemy control points. 
Can't reproduce.
