### ISSUE TITLE
Re-orientation of ground units (after capture event and via UI)

### ISSUE THREAD

**Issue by RndName** [dcs-liberation/dcs_liberation#2080]
In the current implementation the heading of ground units is loaded from the campaign miz. During a capture event this heading should be calculated to match the "Heading to the center of conflict" function so that the units are oriented correctly. Otherwise the units would face in the wrong direction.

Also there should be a possibility to change the heading manually via the UI

- [x] Automatically set orientation of TGOs which should head towards the conflict to do so if the campaign designer has not set a specific heading (a10e55cfd7834d01d472124bc0c0e7efdc4ebc86)
- [x] Re-orientate after CP Capture Event (2d39fb496cd0f76e2d9515ac263bd60d6a25a0d1)
- [x] Let the user allow to re-orientate manually (partially implemented)
- [x] https://github.com/dcs-liberation/dcs_liberation/issues/2479

The current implementation only changes the orientation of the ground objects connected with the CP that was captured. Any other ground obejcts will not change the orientation. This can be improved in another FR but for this Issue it should be fine as the general heading (either set by campaign designer or via the turn 0 automatic orientation) should still be correct. If this is not the case most likely the campaign designer did something special

**Comment by RndName** [comment]
2d39fb496cd0f76e2d9515ac263bd60d6a25a0d1

**Comment by DanAlbert** [comment]
Forked a bug for the UI bit since this is mostly done, and I suspect the UI is going to move to at least 7.
