### ISSUE TITLE
Key error 26

### ISSUE THREAD

**Issue by DevastatorCM** [dcs-liberation/dcs_liberation#2082]
### Affected versions

5.1.0

### Description

Getting key error 26 at the final mission (based on map situation assumed as it will be last mission) when I click "take off"

### Save game and other files

[donanma.zip](https://github.com/dcs-liberation/dcs_liberation/files/8256832/donanma.zip)

**Comment by DevastatorCM** [comment]
looks like campaign was finished... Would be nice if instead of the error this information was displayed

**Comment by DanAlbert** [comment]
See the pinned bug at the top of the issue page.
