### ISSUE TITLE
Enemy convoy causing KeyError: <<class 'game.theater.controlpoint.Fob'>: Creech FARP> on Take Off

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#2083]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/1975140649

### Description

Getting this error on hitting take off. Appears to be caused by an enemy convoy heading for Creech FARP.

![Capture](https://user-images.githubusercontent.com/72491792/158589824-eb3148cc-c0b9-4437-9b25-84a330d965c6.JPG)

### Save game and other files

[Vegas Nerve #3633a.zip](https://github.com/dcs-liberation/dcs_liberation/files/8262060/Vegas.Nerve.3633a.zip)

**Comment by Raskil** [comment]
I had a look into it, but was not able to fix it. From what I found out, the convoygenerator tries to get the front line between origin and destination. But front line generation has changed. I tried to call the front line creation inside of the front_line_with method of the controlpoint, but it seems one is not able to generate front lines between two control points of the same side (has that worked in the past?). I've now idea on how to proceed with it from here, but I thought I'd share my findings.

**Comment by Starfire13** [comment]
The convoy is moving from Nellis to Creech FARP, and there's no frontline in between the two though. The only frontline is between Creech FARP and Groom Lake. Have encountered this twice so far in two separate campaigns. Workaround is to pass turn till the convoy has arrived at its destination.

**Comment by RndName** [comment]
Cause seems to be #1662 as the calculation for the route end uses the Frontline class. Not had the issue so far as i do not deactivate this setting

**Comment by Starfire13** [comment]
Thanks for confirming the cause. I'll just turn that setting off for now on turns with convoys.
