### ISSUE TITLE
Campaign Miz which are saved with latest DCS patch will cause "transportable" KeyError

### ISSUE THREAD

**Issue by RndName** [dcs-liberation/dcs_liberation#2095]
### Affected versions

5.1.0, Development build

### Development build

all

### Description

As found out in a discussion on discord the latest open beta patch changes the way how the mission editor saves the mission file in the .miz. It removes the ["transportable"] from the mission.

Left one is pre-patch, right one is post-patch mission file (both attached)
![grafik](https://user-images.githubusercontent.com/6678803/159040093-f7c65629-ce5c-49eb-ac61-6a2be2fd2e6d.png)

Pydcs tries to acces this key in https://github.com/pydcs/dcs/blob/master/dcs/unit.py#L91 with
```python
self.transportable = d["transportable"]
```
which causes a KeyError
![grafik](https://user-images.githubusercontent.com/6678803/159040338-38c995c7-e523-4ad6-b2aa-470d41a11cc6.png)

In Development this can be fixed with a PR against pydcs to handle a non existant transportable key but for 5.2 we need another solution. One solution could be to branch from the current used version and just cherry-pick the changes there.

### Save game and other files

[transportable.zip](https://github.com/dcs-liberation/dcs_liberation/files/8306085/transportable.zip)

**Comment by RndName** [comment]
@MetalStormGhost also found out that the me_mission.lua has some changes regarding this:
![grafik](https://user-images.githubusercontent.com/6678803/159041061-56e547a0-895f-4ba3-9791-fc7e230dfa9d.png)

Question here is. do we ever need this "transportable" attribute anywhere :D

**Comment by DanAlbert** [comment]
https://github.com/pydcs/dcs/issues/214

**Comment by DanAlbert** [comment]
https://github.com/dcs-liberation/dcs_liberation/commit/bc39d5eaa8ccaded430231a90ccda93b8976389a
