### ISSUE TITLE
Syria campaigns not working with 5.X after they were saved in ME after the patch

### ISSUE THREAD

**Issue by RndName** [dcs-liberation/dcs_liberation#2096]
### Affected versions

5.2 preview (5.1.0 not tested but pretty sure also affected)

### Description

With the latest terrain updates to syria campaigns for this map do not work anymore when the campaign.miz is saved using the latest Open Beta Mission Editor.

![grafik](https://user-images.githubusercontent.com/6678803/159041796-25bd57ba-7e06-4a62-abde-ed087d81fbd9.png)

### Save game and other files

Campaign after save:
[golan_heights_lite.zip](https://github.com/dcs-liberation/dcs_liberation/files/8306154/golan_heights_lite.zip)

**Comment by DanAlbert** [comment]
Hmm, maybe I tagged the wrong bug?

**Comment by RndName** [comment]
potential fix with 48945c1ce98a6dfde75ce79889f34d32167aba37

**Comment by RndName** [comment]
just tested it - solved with the pydcs fork and the syria terrain update
