### ISSUE TITLE
Not enough helipads available at Shiraz Intl

### ISSUE THREAD

**Issue by Hornet2041** [dcs-liberation/dcs_liberation#2100]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/2005744967

### Description

Liberation thinks there are no helipads available at shiraz international and spawns apaches mid-air. Worked around by editing the .miz directly and adding them to Shiraz, worked no problem.

### Save game and other files

[george_cant_hover_at_shiraz_in_the_summer_beware.zip](https://github.com/dcs-liberation/dcs_liberation/files/8312147/george_cant_hover_at_shiraz_in_the_summer_beware.zip)

**Comment by RndName** [comment]
Should be fixed with 4a99b59a386398339da4e6521e43afc180eba0e8
