### ISSUE TITLE
Error on generating new campaign built using Syria expansion

### ISSUE THREAD

**Issue by sgtfuzzle17** [dcs-liberation/dcs_liberation#2101]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/2013327364

### Description

![oL1m0Eq](https://user-images.githubusercontent.com/49757384/159196052-9a136364-b468-45ee-ba5e-faeea035d7f8.png)

This error occurs when trying to generate a new campaign using my new campaign; this campaign uses the newer airfield on Syria which is where I assume the issue is coming from. Specifically, the error points out "Cannot find ControlPoint with airport ID 5" which refers to Tha'lah (this is not a new airfield itself I believe). Campaign files are attached below.

Files:
[tripoint_hostility.zip](https://github.com/dcs-liberation/dcs_liberation/files/8312651/tripoint_hostility.zip)
 

### Save game and other files

Liberation log file:
[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/8312653/liberation.log)

**Comment by RndName** [comment]
Issue is within your campaign miz. You set Thalah not as Red or Blue and left it on neutral. Therefore liberation will not count it as Controlpoint and it will not appear in the list of available CPs -> Therefore the KeyError as there is no ID 5
