### ISSUE TITLE
Removed units (SA-8 LD and M4_Tractor) break save-compat in 5.2.0

### ISSUE THREAD

**Issue by RndName** [dcs-liberation/dcs_liberation#2103]
### Affected versions

5.2.0

### Description

With the recent patch two units were removed from the game `Unarmed.M4_Tractor` and `AirDefence.SA_8_Osa_LD_9T217`. As they can be still in the save game of 5.1.0 running campaigns they will break save compat for 5.2.0

Correction: the M4_Tractor was not removed it was changed from Unarmed to `Armor.M4_Tractor`

`AttributeError: Can't get attribute 'AirDefence.SA_8_Osa_LD_9T217' on <module 'dcs.vehicles' from 'G:\\Programme\\Sonstiges\\DLCs\\DCS\\DCS Liberation\\dcs_liberation_pre\\dcs\\vehicles.pyc'>`

### Save game and other files

n.A.

**Comment by Hanninho** [comment]
Attached is the savegame of the campaign (zipped due to the requirement of github)
[georgia_1_new.zip](https://github.com/dcs-liberation/dcs_liberation/files/8323117/georgia_1_new.zip)

**Comment by RndName** [comment]
Solved in latest 5.2.0 build https://github.com/dcs-liberation/dcs_liberation/actions/workflows/build.yml?query=branch%3Adevelop-5.2+event%3Apush

**Comment by RndName** [comment]
linking the actual commit here https://github.com/dcs-liberation/dcs/commit/ef8cd82910ad86814da4cbfb5ca47f47d13e0e0a
