### ISSUE TITLE
New campaign: Tripoint Hostility

### ISSUE THREAD

**Issue by sgtfuzzle17** [dcs-liberation/dcs_liberation#2106]
* Campaign name: Tripoint Hostility
* Files: 
[tripoint_hostility.zip](https://github.com/dcs-liberation/dcs_liberation/files/8324547/tripoint_hostility.zip)

* Update summary (optional): A joint US Army/Air Force contingent must push Iraqi aggressors back through Jordan and Syria to the border, then pacify Iraq's nearby airbases. This campaign showcases the southeastern expansion to the Syria terrain, and incentivizes heavy usage of rotary from FARPs. Mid-sized.
* _Backstory: In an alternate 2006, Iraqi has seen a coup place a hardline national fundamentalist movement in power, who have ejected US forces from the country under threat from newfound Iranian allies. With their confidence unchecked, Iraq has invaded their Jordanian and Syrian neighbours to the west, pushing nearly to the Israeli border. To keep the region from falling to chaos, the US has redeployed a task force from Europe to defend Jordan and bring down Iraq's west-facing air power._

**Comment by sgtfuzzle17** [comment]
Getting an error upon hitting the Take Off button, screenshot attached. This is on dev build 6.0-3680, others have reported it on (at least) 5.2-3691:
![ZQhCok2](https://user-images.githubusercontent.com/49757384/159706151-e4a1aae3-adb2-471b-9d70-8ac53b9625a1.png)

**Comment by RndName** [comment]
> Getting an error upon hitting the Take Off button, screenshot attached. This is on dev build 6.0-3680, others have reported it on (at least) 5.2-3691: ![ZQhCok2](https://user-images.githubusercontent.com/49757384/159706151-e4a1aae3-adb2-471b-9d70-8ac53b9625a1.png)

reported as #2110
