### ISSUE TITLE
Odd flightplan passing through other airfield before ingressing

### ISSUE THREAD

**Issue by s3-chardonjf** [dcs-liberation/dcs_liberation#211]
- Load the attached saved file
[2020-10-16-1.zip](https://github.com/Khopa/dcs_liberation/files/5395108/2020-10-16-1.zip)
- Delete all packages to start fresh
- Right-click the frontline and create a new package and a CAS flight of AH-64 from Minakh (just next to frontline)
- Notice the flightplan makes them go all the way to Hatay in some weird thing, making the flight package arrive on frontline a full 100 minutes after mission start.
![image](https://user-images.githubusercontent.com/29724443/96330641-28583280-1057-11eb-80e9-faec6e259201.png)

**Comment by s3-chardonjf** [comment]
If you make them the only flight of the package it gives this, which isn't matching the frontline either and has some weird hold point at the frontline?
![image](https://user-images.githubusercontent.com/29724443/96330703-a9afc500-1057-11eb-8644-c04003391ca4.png)

**Comment by s3-chardonjf** [comment]
Notice also the fragged altitude of 21k feet for Apache helicopters
![image](https://user-images.githubusercontent.com/29724443/96330748-057a4e00-1058-11eb-9b3b-2156de519c6d.png)

**Comment by DanAlbert** [comment]
CAS and frontline CAPs no longer participate in joins (the CAP won't be in formation anyway), so this is now no worse than it was in 2.1. https://github.com/Khopa/dcs_liberation/issues/292 covers the improvement that we could do in the future.

https://github.com/Khopa/dcs_liberation/commit/88b9ed29ba1efda3dee7b1c43ae36b22c93f1c26
