### ISSUE TITLE
AH-64D Radio presets are not set correctly

### ISSUE THREAD

**Issue by RndName** [dcs-liberation/dcs_liberation#2111]
### Affected versions

5.2.0, Development build

### Description

The radio presets are not correctly set for the AH-64D. Only the flight frequency will be used. Any other frequency must be set manually in the helicopter.

Frequencies defined in the Mission Editor do not have any effect yet.

This is a known Issue with the model.

This GitHub Issue will be used as placeholder until ED fixes it. Then we can update the Support for this module.

### Save game and other files

-

**Comment by Raffson** [comment]
From what I can tell this has been fixed, the second radio's first channel matches the flight frequency when I look at Liberation's generated missions, though the Mi-24P #2238 is a different problem afaict.
