### ISSUE TITLE
JTAC names show up as strings of jumbled letters/numbers

### ISSUE THREAD

**Issue by Hornet2041** [dcs-liberation/dcs_liberation#2120]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/2037333473

### Description

see screenshot. clean 3707 install, JTAC autolase plugin enabled.

### Save game and other files

![image](https://user-images.githubusercontent.com/55866858/160207789-e1f9aff0-0f13-453e-90a8-cce13162053a.png)

[valley of rotary but im flying f14.zip](https://github.com/dcs-liberation/dcs_liberation/files/8354033/valley.of.rotary.but.im.flying.f14.zip)

**Comment by DanAlbert** [comment]
I agree it's weird, but does this actually cause any problems?

**Comment by Hornet2041** [comment]
uhhh... yea, not really.

**Comment by RndName** [comment]
Issue is due to the logic how the unit and group name are generated over here:
https://github.com/dcs-liberation/dcs_liberation/blob/c9df8cc803c9a1a1ddc5fe7e8f6425505b68c74d/game/missiongenerator/flotgenerator.py#L144
