### ISSUE TITLE
Update for Task Force Thunder

### ISSUE THREAD

**Issue by sith1144** [dcs-liberation/dcs_liberation#2121]
* Campaign name: Task Force Thunder
* Files: 
[Task Force Thunder.zip](https://github.com/dcs-liberation/dcs_liberation/files/8354271/Task.Force.Thunder.zip)
* Update summary (optional): An update for task force thunder, using the new H3 airfields in Iraq

**Comment by RndName** [comment]
@sith1144 is this campaign compatible with campaign version 10.0?
