### ISSUE TITLE
AI Apaches unable to take off with full fuel load

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#2125]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/2037333473

### Description

AI Apaches are often unable to take off with a full fuel load (even though players can). This is affected by loadout, height above sea level, and ambient temperature.

I've found that Apaches at 50% fuel have an operating time of about 1 hour 15 minutes (based on estimated consumption on fuel MFD page at ~90% collective), and can still take off from Kerman (the highest airfield in DCS at 5700 feet) in 40 degree weather with 2 racks of hellfires and 2 rocket pods. They can take off with 60% fuel (roughly 1 hour 25 minutes operating time) at 30 degrees, but not at 40 degrees.

My suggestion is to set all Apaches to spawn in with 50% fuel.

### Save game and other files

[Apache Max Weight Test.zip](https://github.com/dcs-liberation/dcs_liberation/files/8355010/Apache.Max.Weight.Test.zip)

**Comment by RndName** [comment]
#656 

IMO we need more to solve this correctly:  we need to show the user the amount of fuel set by liberation and give them the possibility to override this

Best thing would be to have a function calculating required fuel and the max takeoff weight which also includes OAT.

**Comment by Starfire13** [comment]
Yeah, I agree. I've actually been running all my campaigns in winter to get around this limitation. Perhaps some sort of warning if the temperature is over a certain threshold, and the ability to reduce Apache fuel load if the user wishes to.

**Comment by Starfire13** [comment]
Closing this old FR as it was actually caused by a DCS issue with the Apache APU that has since been fixed by ED.
