### ISSUE TITLE
Apache INU alignment

### ISSUE THREAD

**Issue by kevotosmart** [dcs-liberation/dcs_liberation#2126]
### Affected versions

Development build

### Description

Scenic route 2- dust to dust
Faction: NATO OIF

Apache refused to INU align on farps. Tested with and without liberation. 

I think the conflicting issue has to do with them being a neutral coalition, since in ME you cannot place a ramp start (cold or hot) Blue on a neutral invisible helipad 

I don't think I need anything else its easily reproduced and can be tested easily as well by changing the generated mission invisible farp to CJTF.

also I'm sure 5.2 generates FARPS helipads as neutral as well so I think it affects that build as well.

### Save game and other files

[save](https://www.mediafire.com/file/mniruht67za2vhj/autosave.liberation/file)

[miz file](https://www.mediafire.com/file/vayojc7m8eujf6r/liberation_nextturn.miz/file)

**Comment by Hornet2041** [comment]
its not a bug. The Apache and other US aircraft using GPS as INS sources need to have the USA in the player coalition or have the .miz option "unrestricted satnav" enforced.

https://discord.com/channels/595702951800995872/790195984105734165/903211350656946206 relevant discord discussion from a year ago from first encountering the issue

**Comment by Hornet2041** [comment]
NATO OIF/Desert Storm factions missing unrestricted_satnav options caused this

**Comment by RndName** [comment]
fixed with https://github.com/dcs-liberation/dcs_liberation/commit/f7f565477c1aed994333b12a6844785335fddd53
