### ISSUE TITLE
OCA/Aircraft flight RTBs before reaching targets

### ISSUE THREAD

**Issue by septagram** [dcs-liberation/dcs_liberation#2130]
### Affected versions

5.1.0

### Description

There was a 2x F-16 allied AI flight from Mozdok tasked at OCA/Aircraft at Minvody, each equipped with 6x AGM-65D (group name in TacView "Mineralnye Vody OCA/Aircraft|2|11|28|F-16CM Fighting Falcon (Block 50)|"). The flight took off, progressed halfway to Minvody, then turned around and landed. There doesn't seem to be any in-game reason for this.

I noticed a [very similar issue](https://github.com/dcs-liberation/dcs_liberation/issues/820) marked as resolved in February 2021, however, this happened to me just now in the version 5.1.

[bug-liberation-oca-rtb.zip](https://github.com/dcs-liberation/dcs_liberation/files/8358319/bug-liberation-oca-rtb.zip)

### Save game and other files

(can't drag-and-drop into this box, the file should be in the main description)

**Comment by DanAlbert** [comment]
> progressed halfway to Minvody

Possible that the earlier fix was accidentally removed. The other options I think are the flight plan being wrong (unlikely) or bingo fuel.

**Comment by septagram** [comment]
Probably not the bingo fuel case (default OCA/Aircraft loadout, homeplate not that far away). Another hypothesis is the flight realized it had no escort (there was a TARCAP in a separate DEAD package with the same TOT; it got decimated but cleared the skies successfully before that), got scared and went home (is it smart/dumb enough for that?).

**Comment by DanAlbert** [comment]
> Another hypothesis is the flight realized it had no escort (there was a TARCAP in a separate DEAD package with the same TOT; it got decimated but cleared the skies successfully before that), got scared and went home (is it smart/dumb enough for that?).

afaict the DCS AI has no awareness of friendly aircraft at all (aside from tankers), so presence/absence of escorts shouldn't make any difference. We don't add any RTB triggers on our end, and I believe the ROE is set such that they won't run unless they're bingo or winchester.

**Comment by Starfire13** [comment]
What was the weather like? I have noticed that A2G flights will RTB without engaging their targets when visibility is low.

**Comment by DanAlbert** [comment]
The target is supposed to be a flyover point though. Not seeing the target might _also_ be a problem (one we can't fix), but they aren't flying the flight plan we expect

**Comment by Starfire13** [comment]
Yeah, that's true. For OCA/aircraft it is a flyover point. Hmm.

**Comment by DanAlbert** [comment]
If you've just confirmed that in the ME (I haven't looked, I'm just making notes for whomever ends up looking at this), that's a pretty good indicator that this is a DCS bug. There's nothing we can do when the AI won't follow orders.

**Comment by Starfire13** [comment]
I just looked at the Liberation save file included in the zip. There are no packages planned. I think it's the wrong save.

**Comment by Starfire13** [comment]
> If you've just confirmed that in the ME (I haven't looked)

And yes, it is a flyover point in the ME. Running the .miz now.

**Comment by Starfire13** [comment]
The issue is fuel. Your Viper loadout has 6 Mavericks and 2 CBU-105s and no external tanks at all. This means they only have about 7000 lbs of fuel. By the time they are halfway to their target, they are already down to 1300 lbs of fuel. My F-16 loadouts typically have 2 external tanks, but I would consider at least one practically mandatory. The AI has no concept of fuel conservation and will happily use afterburner whenever they like, so it's important that you give them enough fuel.

**Comment by septagram** [comment]
> I just looked at the Liberation save file included in the zip. There are no packages planned. I think it's the wrong save.

I'm afraid that's a save *after* the mission has run :(

I accepted the results first and watched the TacView later, only then seeing that there was an issue. Would be awesome if Liberation also kept last autosave along with the current one just for the cases like this.

**Comment by septagram** [comment]
> The issue is fuel. Your Viper loadout has 6 Mavericks and 2 CBU-105s and no external tanks at all. This means they only have about 7000 lbs of fuel. By the time they are halfway to their target, they are already down to 1300 lbs of fuel. My F-16 loadouts typically have 2 external tanks, but I would consider at least one practically mandatory. The AI has no concept of fuel conservation and will happily use afterburner whenever they like, so it's important that you give them enough fuel.

Oh I see )) Duly noted, thanks for clearing that up. Note that this was the default loadout IIRC.

**Comment by Starfire13** [comment]
You don't have to adhere to the default loadouts. I setup my own defaults for all my aircraft instead of using the included ones, and alter them depending on my needs in different campaigns. There's info on the wiki on how to do this if you wish to as well.

**Comment by DanAlbert** [comment]
If that's the default it's a bad default though. If "you can fix it yourself" is a valid argument we wouldn't need to ship defaults at all :)

**Comment by Starfire13** [comment]
Well, many of the default loadouts are sub-optimal. And not just for the F-16.

**Comment by DanAlbert** [comment]
Yes. It's not practical for us to find and fix all of them, but the least we can do is keep the bugs open for the known issues.
