### ISSUE TITLE
Syria map targets deep in forest 

### ISSUE THREAD

**Issue by Fahad-Doctor** [dcs-liberation/dcs_liberation#214]
when generating a mission in Syria map , most if not all are in very dense forests , 

forests problems : 
1- acquiring targets in TGP is nearly impossible 
2- rockets and bombs 90% hit the trees leaving the target unscathed

**Comment by DanAlbert** [comment]
New campaign format fixes this. Campaigns are being migrated, but the problem itself is solved.
