### ISSUE TITLE
Waypoint TOT differences between kneeboard and aircraft

### ISSUE THREAD

**Issue by fizzle77** [dcs-liberation/dcs_liberation#2145]
### Affected versions

5.2.0

### Description

In the A-10C II (I'm not sure if it's unique to this aircraft) there is always a 2-4 minute mismatch between the kneeboard TOT and what's set in the aircraft:

### Liberation UI

![my-flight-liberation](https://user-images.githubusercontent.com/42720583/161350540-6e437830-2118-4775-8728-e749fba0d468.png)
![liberation-waypoints](https://user-images.githubusercontent.com/42720583/161350532-5aa33701-c4b7-4885-bade-a0537cf19554.png)

### Kneeboard

![kneeboard-flight-plan](https://user-images.githubusercontent.com/42720583/161350554-96ee07d5-cbbe-401d-9f07-7a88ecb2d2bb.png)

### Aircraft

Time/TOT adjustment (Not necessary for reproduction but because TOTs are Zulu by default this makes the issue easier to see.)

![time-adjustments](https://user-images.githubusercontent.com/42720583/161350594-6464945f-935b-492c-b189-cb8ce68a8e79.png)

### TOT Waypoints

It varies, but this roughly 2 minutes late is typical. It varies from 2 to 4 minutes, always late. Note that in this example it's exactly `2:06` slow. It should be 12:22:16 but it's 12:24:22.

![1](https://user-images.githubusercontent.com/42720583/161350606-3235378c-5c7b-46f6-a45c-517f4fc0a5f3.png)

### Non-TOT Waypoints

Additionally, any waypoints that don't have a TOT in Liberation have a value exactly `2:06` after mission time. This isn't always 2:06, but it always matches the offset above. Ideally these would have no TOT set.

![2](https://user-images.githubusercontent.com/42720583/161350610-9a6f600c-c652-4e98-8faa-faf9ee5f04d1.png)
![3](https://user-images.githubusercontent.com/42720583/161350614-60cd8b9f-ee52-452c-bba3-24a2f66c88a3.png)
![4](https://user-images.githubusercontent.com/42720583/161350616-e1ced3de-f2a2-4caa-864a-d7aad7b732d1.png)
![5](https://user-images.githubusercontent.com/42720583/161350619-c2ba46de-2fde-477e-946d-b0f57c93e2b8.png)
![6](https://user-images.githubusercontent.com/42720583/161350624-a721e32b-23dd-414c-9079-1c23c9189b31.png)

### Save game and other files

[liberation-savefile.zip](https://github.com/dcs-liberation/dcs_liberation/files/8401182/liberation-savefile.zip)

**Comment by Starfire13** [comment]
Possibly related to https://github.com/dcs-liberation/dcs_liberation/issues/1848 which was fixed?

**Comment by DanAlbert** [comment]
> Possibly related to https://github.com/dcs-liberation/dcs_liberation/issues/1848 which was fixed?

Seems likely, and if not it's probably a DCS issue. The only control we have is over the TOT for the waypoint in the ME, and if the jet it showing something different than the ME that's not a thing we can fix.
