### ISSUE TITLE
Missing map functions after migration

### ISSUE THREAD

**Issue by RndName** [dcs-liberation/dcs_liberation#2158]
### Affected versions

Development build

### Description

There are some functions missing after the migration. This issue is a placeholder for them. continue of #2039

- [x] Ruler
- [x] Culling can not be displayed
- [ ] The check boxes to hide and show UI stuff was not working for AAA/SAM threats

### Save game and other files

-

**Comment by Raffson** [comment]
Could you perhaps specify which checkboxes w.r.t. AAA/SAM threats aren't working? On my end I don't seem to have any problems, so perhaps it has been resolved already by someone else?

**Comment by DanAlbert** [comment]
> Could you perhaps specify which checkboxes w.r.t. AAA/SAM threats aren't working? On my end I don't seem to have any problems, so perhaps it has been resolved already by someone else?

Assuming yes. Can re-open if we get repro instructions.

**Comment by Raffson** [comment]
> > Could you perhaps specify which checkboxes w.r.t. AAA/SAM threats aren't working? On my end I don't seem to have any problems, so perhaps it has been resolved already by someone else?
> 
> Assuming yes. Can re-open if we get repro instructions.

It's far worse than that, see #2253

**Comment by RndName** [comment]
hey i'm not really sure what the exact issue was (was a report from discord) but it is likely that is part of the issue mentioned by @Raffson . So as long as no one reports any other issue it's fine to keep this one closed

**Comment by Raffson** [comment]
@RndName I already have another issue open, updated it with a task list, 1 PR already open to fix 2 of the issues
