### ISSUE TITLE
BAI missions

### ISSUE THREAD

**Issue by s3-chardonjf** [dcs-liberation/dcs_liberation#216]
![image](https://user-images.githubusercontent.com/29724443/96361325-0927d680-1125-11eb-9a96-2a19212ed8eb.png)

I find myself trying this often and feeling puzzled that it isn't possible.

The intent is to create a package that will go beyond the frontline and search and destroy ground units at the enemy airbase (or over any point of interest, ideally)

I would love ability to point at a spot on the map and say, search and destroy enemy units at that location, within this radius.

**Comment by s3-chardonjf** [comment]
If you need further incentive of why this would be needed, CAS flights have a tendency to get confused and be located in bad places that the user should be able to input instead of trying to generate it from logic. 
![image](https://user-images.githubusercontent.com/29724443/96361468-3032d800-1126-11eb-822c-547666dce037.png)

**Comment by DanAlbert** [comment]
Something I was planning on looking into soon, so assigning to myself.
