### ISSUE TITLE
AH-64D AI Wingman Explodes at mission start at FARP

### ISSUE THREAD

**Issue by fercyful** [dcs-liberation/dcs_liberation#2161]
### Affected versions

5.2.0

### Description

1. Start The Mission
2. AI Wingman Explodes on the left side of my own AH-64D
3. I want that both units survive for start the mission. I know the DCS AI is quite bad but I like to fly for some minutes with it :)

### Save game and other files

Hi there! Here the problem is that the wingman explodes beside me at the FARP. I check the mission and me and the AI try to take from the same helipad. Changed the AI one and now both stay alive at the start of the mission :) Also can be the sloped terrain if the system auto assign the starting position for the AI wingman (with bad luck at uneven terrain)... thanks
[AH-64_AI_Wingman_Explodes.zip](https://github.com/dcs-liberation/dcs_liberation/files/8459870/AH-64_AI_Wingman_Explodes.zip)

**Comment by DanAlbert** [comment]
Sounds the same as https://github.com/dcs-liberation/dcs_liberation/issues/2129, and according to that, the helipad is outside out control and handled by DCS, so not a thing we can fix.
