### ISSUE TITLE
Supply Route Colours Displaying Incorrectly

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#2167]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/2167015779

### Description

After starting up Liberation, if you then switch to a different save file or start a new campaign, the colours on the supply routes do not update properly. Right-click > reload is a workaround.

As an example, here's what the supply routes ought to look like at campaign start for Vegas Nerve. This is what you see if you start up Liberation and this campaign is the auto-loaded one. (essentially, the auto-loaded campaign save will display supply route colours correctly)
![Capture2](https://user-images.githubusercontent.com/72491792/163502845-a344bc35-9816-40bf-b556-1ed9b21f369f.JPG)

This is what they look like if Liberation loads up with a different save file in the beginning. And then afterwards, you either load up a different save file or start a new campaign.
![Capture](https://user-images.githubusercontent.com/72491792/163503010-77b0c1e3-ee14-4e6f-b68e-f11cfc1375c3.JPG)

To replicate:
1. Start up Liberation
2. Load Scenic Route #3786.liberation (included in zip below)
3. Hit Save
4. Exit Liberation
5. Start up Liberation (Scenic Route #3776 should now be auto-loaded)
6. Load Vegas Nerve #3786.liberation (included in zip below)

### Save game and other files

[Saves.zip](https://github.com/dcs-liberation/dcs_liberation/files/8493250/Saves.zip)

**Comment by DanAlbert** [comment]
This looks to be the same problem as https://github.com/dcs-liberation/dcs_liberation/issues/2078/. I wouldn't be surprised if we have the same issue elsewhere either.
