### ISSUE TITLE
3777 6.0 dev build - Map Options not working

### ISSUE THREAD

**Issue by holyorangejuice** [dcs-liberation/dcs_liberation#2169]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/2143326024

### Description

In 3777 the map options in the top left and top right have been changed. There is no longer a ruler or options to show culling. 

The options on the right such as 
-Control Points
-Aircraft
-Active Combat
-Air Defenses
-and so on...

These options do not appear to be functioning properly. I frequently use to disable most objects so I could focus on air defense. I can no longer do this. Most options, especially air defense, doesn't hide anything.

The threat zones on the left, the white box with three squares inside
-Blue Threat Zones
-Red Threat Zones

These do not update when swapping out air defenses until you pass turn. 

I know it is WIP but these are the issues I've noticed.

### Save game and other files

[3777.zip](https://github.com/dcs-liberation/dcs_liberation/files/8495666/3777.zip)

**Comment by Starfire13** [comment]
https://github.com/dcs-liberation/dcs_liberation/issues/2158
