### ISSUE TITLE
[Feature Request] Option for WWII Assets AAA in Modern Scenarios

### ISSUE THREAD

**Issue by Mustang-25** [dcs-liberation/dcs_liberation#217]
AAA plays a big role in many conflict areas especially in places like Syria and the PG but modern/Cold War assets are severely lacking. Have the devs considered adding an option (like the check box for the super carrier) to toggle the use of the WWII Assets pack AAA? The various German Flak guns and Bofors could be a good stand-in until we get better options down the road.

**Comment by DanAlbert** [comment]
This was added in 2.2.
