### ISSUE TITLE
Re-structure campaign wizard dialogue

### ISSUE THREAD

**Issue by rabauke80** [dcs-liberation/dcs_liberation#2173]
![image](https://user-images.githubusercontent.com/67376231/163805131-b1c2d0a3-6e4f-49e4-97f5-a3d4a43cf19f.png)

From a UI flow perspective, it seems weird that the user pushes a finish button, just to get a fresh dialogue, which has no accept button, but can only be closed by the X in the top right. I do know that the air wing configuration was added long after the initial campaign wizard flow - so my suggestion is.

- [ ]  remove the finish button on the "New Game" dialogue page and replace it with a next button

- [ ] adjust text on "New Game" dialogue page accordingly

- [x] add a finish button to the "Air Wing Configuration" dialogue page

**Comment by RndName** [comment]
As extension to a reworked design there should also be a dialog for Armed Forces Configuration like the AirWing dialog to allow to remove for example specific SAM Systems or ground vehicles from the faction accessible units. This is possible with the ground object refactoring done in develop branch.
This is especially handy if some one wants to use the high digit SAM mod and remove the default SAM systems for example.

**Comment by DanAlbert** [comment]
This was done some time ago.
