### ISSUE TITLE
CTLD - enable infantry transportation

### ISSUE THREAD

**Issue by rabauke80** [dcs-liberation/dcs_liberation#2174]
Related to #2163 , CTLD can be configured per helo, in order to reflect the IRL transport capacity, both in terms of unit count (infantrymen) and total weight loaded.

Out of the box, CTLD does not care about the individual helo loading capacity, so helo models need to be enabled to transport/load troops in general, plus a separate configuration.

**Maximum Units SETUP for UNITS**
https://github.com/ciribob/DCS-CTLD/blob/f70c6a7131be6e98d6335265f9a8475cd7ecf6df/CTLD.lua#L425-L432

Example (numbers below might not reflect the IRL values):

```
ctld.unitLoadLimits = {

    ["SA342Mistral"] = 2,
    ["SA342Minigun"] = 1,
    ["SA342L"] = 2,
    ["SA342M"] = 2,
    ["UH-1H"] = 6,
    ["Mi-24P"] = 6,    
    ["Mi-8MT"] = 12,
    ["UH-60L"] = 10,  

}
```

**Allowable actions for UNIT TYPES**
https://github.com/ciribob/DCS-CTLD/blob/f70c6a7131be6e98d6335265f9a8475cd7ecf6df/CTLD.lua#L435-L456

Example:

```
ctld.unitActions = {
    ["SA342Mistral"] = {crates=false, troops=true},
     ["SA342Minigun"] = {crates=false, troops=true},         
     ["SA342L"] = {crates=false, troops=true},
     ["SA342M"] = {crates=false, troops=true},
     ["Ka-50"] =  {crates= true, troops=false},
     ["Mi-24P"] =  {crates= true, troops=true},

}
```

**WEIGHT CALCULATIONS FOR INFANTRY GROUPS**
https://github.com/ciribob/DCS-CTLD/blob/f70c6a7131be6e98d6335265f9a8475cd7ecf6df/CTLD.lua#L458-L477

Defaults could be used to begin with

**INFANTRY GROUPS FOR PICKUP**
https://github.com/ciribob/DCS-CTLD/blob/f70c6a7131be6e98d6335265f9a8475cd7ecf6df/CTLD.lua#L478-L498

CTLD customization - potential implementation/use of a new function per helo:

Example: ctld.loadableGroupsByHelo

```
ctld.loadableGroupsByHelo = {}

ctld.loadableGroupsByHelo['UH-1H'] = {
                        {name = "Standard Group", inf = 4, mg = 1, at = 1 },
                        {name = "Anti Air", inf = 2, aa = 4  },
                        {name = "Anti Tank", inf = 3, at = 3  },
                        {name = "Mortar Squad", inf = 2, mortar = 4 },
                        {name = "JTAC Group", inf = 4, jtac = 1 },
                        {name = "Single JTAC", jtac = 1 },
                      }

```

Any type of infantry squad could be added and customized per helo for realism- something like a SpecOps squad, or pure infantry, etc.

**Comment by RndName** [comment]
Thanks for your input!

I've implemented the unitActions and the unitLoadLimits like you mentioned with #2163 . I've also openend a Pull Request to CTLD to make these also work for AI units (they actually still just load the amount defined with `ctld.numberOfTroops = 10` so every AI flight would pickup 10 units atm.) https://github.com/ciribob/DCS-CTLD/pull/75

The ctld.loadableGroupsByHelo i think is a bit too much for the first step. I've created 4 different Troop types for the first implementation:

```
ctld.loadableGroups = {
                { name = "Liberation SpecOps (6)", inf = 4, mg = 1, at = 1 },
                { name = "Liberation SpecOps (10)", inf = 5, mg = 2, at = 2, aa = 1 },
                { name = "Liberation SpecOps (12)", inf = 6, mg = 2, at = 2, aa = 2 },
                { name = "Liberation SpecOps (2)", inf = 2 }
            }
```

**Comment by rabauke80** [comment]
In case the topic of accurate maximum infantry group size per helo gets revisited, it might be a good idea to add parameters to the airframe yaml (example below) - so that in case CTLD is being used by the user

infantry_transport_capable: [boolean]
cabin_size: [int]


resources\units\aircraft\Mi-8MT.yaml

```
carrier_capable: true
description: The Mil Mi-8MTV2 is an upgraded version of one of the most widely produced
  helicopters in history and a combat transport and fire support veteran of countless
  operations around the world.
introduced: 1981
lha_capable: true
infantry_transport_capable: true
cabin_size: 12
manufacturer: Mil
origin: USSR/Russia
price: 5
role: Transport/Light Attack
variants:
  Mi-8MTV2 Hip: {}

```

Remeber, internal load, crate & infantry contributes to the total gross weight of the airframe.

**Comment by RndName** [comment]
>  it might be a good idea to add parameters to the airframe yaml

good point thanks, done with https://github.com/dcs-liberation/dcs_liberation/pull/2193/commits/5627951c0f791a06583d71e545a067eb01d32d21

**Comment by rabauke80** [comment]
> > it might be a good idea to add parameters to the airframe yaml
> 
> good point thanks, done with [5627951](https://github.com/dcs-liberation/dcs_liberation/commit/5627951c0f791a06583d71e545a067eb01d32d21)

awesome, looks good! might also come in handy for the C-130 mod, in case transporting troops/paratroopers and dropping them becomes a thing.

Q: will users ingame now only see one type of infantry squad, depending on their airframe capacity or receive an ingame error if they try to load a larger than supported squad size?

On the Rotorheads server, we only show the _compatible_ squads fitting the currently selected airframe, using ```ctld.loadableGroupsByHelo``` to prevent confusion using CTLD ingame


based on your example, that would translate into something like that below - presenting only a single equally named infantry squad, but differ in size (internally) depending on the airframe selected:

```ctld.loadableGroupsByHelo = {}

ctld.loadableGroupsByHelo['UH-1H'] = {
                        {name = "Liberation SpecOps", inf = 3, aa = 1, mg = 1, at = 1},
                      }

ctld.loadableGroupsByHelo['UH-60L'] = {
                        {name = "Liberation SpecOps", inf = 4, aa = 2, mg = 2, at = 2},
                      }

ctld.loadableGroupsByHelo['Mi-8'] = {
                        {name = "Liberation SpecOps", inf = 6, aa = 2, mg = 2, at = 2},
                      }
```

**Comment by RndName** [comment]
> Q: will users ingame now only see one type of infantry squad, depending on their airframe capacity or receive an ingame error if they try to load a larger than supported squad size?

They will see all groups with the size <= transport limit for the given airframe. And i think this is enough for our current use case we have within liberation at this time. I personally do not really see any benefit in restricting the loadable groups by helo type instead of defining few basic ones. Also i am personally in favor of having the own choice if i want to put in a troop of 6 or 10 soldiers in my helo instead of only having 10 available. Especially as you previously saif if gross weight and so on is a topic. maybe some one wants to fly a gunship with 4 inf soldiers only to capture the CP instead of transporting 10 soldiers without any armament on the hardpoints.

I think for the first implementation this is already good. If we want to improve it later - we can. But only after it come alive.

**Comment by RndName** [comment]
> might also come in handy for the C-130 mod, in case transporting troops/paratroopers and dropping them becomes a thing.

How would this be realized? C130 deploying paratroopers sounds awesome and would finally give this plane a sense within liberation.
- Troop Loading has to be ensured that the pickup zone can be used by the airplane (especially if it is an AI unit). As far as i know we do not know the gate where this plane will be placed so we have to think about a workaround. Pickup Zone with a huge radius for the whole Airport is also a thing as workaround
- Troop Extraction: How to tell the plane to troop the troops? Is this automatically done when it flies over the DropOff Zone?

**Comment by RndName** [comment]
I have added support for the fixed wing Air Assault tasking but i have not found out how to drop the troops from the air. It seems this is only possible with the Hercules mod and only by the player. Therefore for the first version it will only work for helos.
