### ISSUE TITLE
Game can not be saved after adding custom waypoint

### ISSUE THREAD

**Issue by RndName** [dcs-liberation/dcs_liberation#2180]
### Affected versions

Development build

### Development build

3804

### Description

Create a new flight with a player (DEAD in this case) and add a custom waypoint for another ground object to the list of waypoints. After that the game can not be saved anymore.

Reproduce:
- Create a new campaign (in this case Allied Sword)
- Buy some aircraft
- Begin Campaign
- Task a flight (DEAD against PUG in this example)
- Save -> Works (attached)
- Open the Flight and go to the Waypoint Tab
- Use Add Waypoint and add a different Ground Object (PRONGHORN in this case)
- Save -> Get the error message:

2022-04-20 17:58:16,270 :: root :: INFO :: Saving game
2022-04-20 17:58:16,312 :: root :: ERROR :: Could not save game
Traceback (most recent call last):
  File "D:\workspace\dcs_liberation\game\persistency.py", line 61, in save_game
    pickle.dump(game, f)
TypeError: cannot pickle 'QFlightWaypointTab' object
2022-04-20 17:58:16,321 :: root :: DEBUG :: Saving game took 0:00:00.040755

![grafik](https://user-images.githubusercontent.com/6678803/164400549-72750fd1-be25-4848-95eb-dea852bba372.png)

### Save game and other files

[Issue2180_Build3804.zip](https://github.com/dcs-liberation/dcs_liberation/files/8528589/Issue2180_Build3804.zip)

**Comment by Starfire13** [comment]
Possibly an unintended side effect of Raskil's fix here? https://github.com/dcs-liberation/dcs_liberation/issues/2063
