### ISSUE TITLE
Squadrons not availabe for tasking

### ISSUE THREAD

**Issue by EmoJack199** [dcs-liberation/dcs_liberation#2182]
### Affected versions

5.2.0

### Description

In some Rounds, there are some units that are just not available through the dropdown menu when planning the flights. 
The squadron airframes available, the desired task is viable for the airframe.
It happened to me before with different airframes, so this is just one example of a mission i am planning right now that has this problem:

Planning Phase: Bought 2x KA50 
Round 1: Ka50 BAI flight can be planned. Didnt use them.
Round 2: Ka50 is still in the Airport's inventory, but cant be assigned to any mission
--> Pass turn
Round 3: Ka50 is available for tasking again

I dont know if maybe i did something wrong, but i cant see why sometimes some squadrons are blocked. Pilots are available (12 active, 10 unassigned, 0 on leave)

### Save game and other files

[Bug_report.zip](https://github.com/dcs-liberation/dcs_liberation/files/8524811/Bug_report.zip)

**Comment by EmoJack199** [comment]
reproducibility not given: i just opened the old savegame, loaded the state.json and the next turn did not show the same result as the attached savegame from above.
Attached here is the mission savegame from before the first turn which can be executed with the state.json from the original report.
[ThaEmo_Lib1_start_MIZ1.zip](https://github.com/dcs-liberation/dcs_liberation/files/8524856/ThaEmo_Lib1_start_MIZ1.zip)
.

**Comment by RndName** [comment]
is this related to #1880 ? IIRC a similar issue was already discussed on discord 🤔

**Comment by EmoJack199** [comment]
> is this related to #1880 ? IIRC a similar issue was already discussed on discord 🤔

This could be connected. Though i can find the airframes in the air wing inventory and only miss them in the dropdown of tasking panels.
So not the same issue, but some parallels exist (from pure user perspective).

**Comment by Starfire13** [comment]
Are you certain you are seeing them in the Air Wing Inventory pane, because they do not show up for me at all.

![Capture](https://user-images.githubusercontent.com/72491792/164732219-24af310c-e9bd-498d-bc60-25a81e856c13.JPG)

**Comment by Hornet2041** [comment]
> Are you certain you are seeing them in the Air Wing Inventory pane, because they do not show up for me at all.
> 
> See here: https://cdn.discordapp.com/attachments/774700853507653672/967062893231214592/Capture.JPG

![image](https://user-images.githubusercontent.com/55866858/164731420-c286583e-12ca-44d3-ab49-cb91ac5c0645.png)

**Comment by EmoJack199** [comment]
When i wrote my notes before posting this i wrote down "Air Wing inventory: yes". I guess that was a mistake on my side. I can see the Pilots assigned to an airframe in the "air wing squadrons" section, but on the "air wing inventory" screen i have the same screen as you have postet. sorry for this. 
Seing that the #1880 issue is already on the to do list for 6.0, i guess that this topic can be closed/added to the #1880 point.

**Comment by DanAlbert** [comment]
Duplicate of #1880
