### ISSUE TITLE
AI ground unit selection at turn planning

### ISSUE THREAD

**Issue by Simba75013** [dcs-liberation/dcs_liberation#2188]
### Affected versions

5.2.0

### Description

Hi !
I see that the ground forces HQ will deploy 15 units max per side on the frontline.

Is there a way that I don't know to actually chose those units ?

Because right now I have LAVs on the front but I'd like to select and organize my ground forces.

I'm using Combined Arms.

Thx

### Save game and other files

.

**Comment by Starfire13** [comment]
You can't choose which of your ground units get deployed. This is not a bug report btw. Please don't use bug reports to ask questions. Discord is probably the best place for questions.

**Comment by DanAlbert** [comment]
Or the discussions tab on GitHub, which is the forum.
