### ISSUE TITLE
Opposing Front Line Forces Not Deploying SAMs (SA-19s)

### ISSUE THREAD

**Issue by Bensirpent07** [dcs-liberation/dcs_liberation#2194]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/suites/6211232269/artifacts/219508125

### Description

Liberation Version 6.0 Build#3811
Over the past few turns I have noticed the front line SAMs that the AI have been purchasing are not being deployed. 11 are shown as active but after a few turns I haven't seen them get deployed and upon checking the mission editor I don't see them anywhere on the front line. I believe I remember in the first turn there were active SA-19s that were engaging my CAS aircraft over the front line. However, after being destroyed they haven't reappeared. Attached is the save file and a screenshot of the FOB that supplies the front line units.

### Save game and other files

![image](https://user-images.githubusercontent.com/7932177/165621324-388c5e38-35e3-492d-9293-ac205c3b2035.png)
[Files.zip](https://github.com/dcs-liberation/dcs_liberation/files/8577421/Files.zip)

**Comment by Bensirpent07** [comment]
After starting a new campaign I noticed this problem actually starts on turn 1. When I started a new campaign, the SA-19s that were under the Russia 2020 faction were not spawning on the front lines.

**Comment by Bensirpent07** [comment]
Also noticed something from the logs as well:
`WARNING :: Unused front line vehicle at base SA-19 Grison (2K22 Tunguska): unknown unit class`

Attached is full log
[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/8595401/liberation.log)

**Comment by Bensirpent07** [comment]
I may have found a potential solution. When accessing the 2S6 Tunguska.yaml file (resources/units/ground_units), the class is set to AAA. I compared this to something like the SA-8 which had a class of "Logistics". After setting the 2S6 Tunguska class to "Logistics", restarting DCS Liberation, and creating a new campaign, the SAMs now spawn in as expected. Without knowing the logic behind the classes, I don't know why the AAA class does not work for the SA-19. This solution does not fix currently broken campaigns as far as I know.

In essence change 
`class: AAA`
to
`class: Logistics`

**Comment by RndName** [comment]
Thanks for the detailed bug report. The issue is in the wrong handling of AAA units for Frontline unit placement. Actually they were not used at all.

The correct unit class for the SA-19 would be `class: SHORAD` not Logistics (which you used from the SA-8 -LD- the Loader Unit).

The actual fix includes both: correct unit class for the SA-19 and also handling of AAA units for frontline placement
