### ISSUE TITLE
Ground unit direct control

### ISSUE THREAD

**Issue by lisaazra** [dcs-liberation/dcs_liberation#22]
Ignore

**Comment by Khopa** [comment]
Yes, i have noticed that the units that are spawned as airbase defense are not made controllable with CA, so i will try to fix this in the next version.

However, you should already be able to control the ground units spawned on the frontline with Combined Arms.

(Note : also be aware that all ground units in DCS are not compatible. For instance the M60 Patton tank can not be controlled with Combined Arms in DCS.)

**Comment by Khopa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Base defense ground units are not controllable with CA](https://trello.com/c/5POHmCY9/123-base-defense-ground-units-are-not-controllable-with-ca)
