### ISSUE TITLE
Generated flights, left untouched, result in error when hitting take off

### ISSUE THREAD

**Issue by s3-chardonjf** [dcs-liberation/dcs_liberation#220]
Latest develop build 1c4f255

[2020-10-17-1.zip](https://github.com/Khopa/dcs_liberation/files/5406640/2020-10-17-1.zip)

- Load the attached saved file
- Hit Take Off
- Notice the error

The flight packages were all automatically generated by the when entering this turn. The only change I made was to add a player slot to one of them. 

![image](https://user-images.githubusercontent.com/29724443/96547585-a6f9dd80-12ac-11eb-8800-f6e198a72467.png)

**Comment by s3-chardonjf** [comment]
Does not seem to occur if I start a new game. 
not a big issue since saves from release are already ditched

**Comment by DanAlbert** [comment]
Yes, this is just save game incompatibility. You can probably continue with your save by just skipping the turn or replanning all your flights.
