### ISSUE TITLE
Untasked aircraft summary UI

### ISSUE THREAD

**Issue by fizzle77** [dcs-liberation/dcs_liberation#2200]
Before filing, please search the issue tracker to see if this feature has already been requested.

If requesting a DCS AI feature, check If reporting a DCS AI bug, check https://github.com/dcs-liberation/dcs_liberation#dcs-bugs.

**Is your feature request related to a problem? Please describe.**
It takes more effort than it should to see what untasked aircraft I have left. You have to create a dummy flight and iterate through the tasking types to see what's left. Especially early in the campaign when I'm at a disadvantage, I want to make sure I'm making use of every aircraft I can.

**Describe the solution you'd like**
Near the top of the UI where we have weather, budget, etc. it would be nice to see a list of untasked airframe types and counts.

**Comment by Starfire13** [comment]
This is already available in the Air Wing pane, Inventory tab. Tick the checkbox so only untasked aircraft are shown.
