### ISSUE TITLE
Error when submitting results or passing turn: "AircraftType(dcs_unit_type=<class 'dcs.helicopters.AH_64D_BLK_II'> ... ) is not in list"

### ISSUE THREAD

**Issue by t-o-g-e** [dcs-liberation/dcs_liberation#2202]
### Affected versions

5.2.0

### Description

Error message is shown when trying to manually submit results, see full error message below. Save file, state.json and log file attached in zip. Same error happens when simply passing turn without a state file.

AircraftType(dcs_unit_type=<class 'dcs.helicopters.AH_64D_BLK_II'>, name='AH-64D Apache Longbow', description="The legendary 'Apache' is an US twin-turboshaft attack helicopter for a crew of two. It features a nose-mounted sensor suite for target acquisition and night vision systems. It is armed with a 30 mm (1.18 in) M230 chain gun carried between the main landing gear, under the aircraft's forward fuselage, and four hardpoints mounted on stub-wing pylons for carrying armament and stores, typically a mixture of AGM-114 Hellfire missiles and Hydra 70 rocket pods. The AH-64 has significant systems redundancy to improve combat survivability. American AH-64s have served in conflicts in Panama, the Persian Gulf, Kosovo, Afghanistan, and Iraq. Israel used the Apache in its military conflicts in Lebanon and the Gaza Strip. British and Dutch Apaches have seen deployments in wars in Afghanistan and Iraq.", year_introduced=2003, country_of_origin='USA', manufacturer='Boeing', role='Attack', price=20, carrier_capable=False, lha_capable=True, always_keeps_gun=True, gunfighter=False, max_group_size=4, patrol_altitude=None, patrol_speed=None, max_mission_range=Distance(distance_in_meters=92600), fuel_consumption=None, intra_flight_radio=Radio(name='AN/ARC-164', ranges=(RadioRange(minimum=RadioFrequency(hertz=225000000), maximum=RadioFrequency(hertz=400000000), step=RadioFrequency(hertz=1000000), excludes=frozenset()),)), channel_allocator=CommonRadioChannelAllocator(inter_flight_radio_index=2, intra_flight_radio_index=2), channel_namer=<class 'game.radio.channels.ApacheChannelNamer'>) is not in list

Traceback (most recent call last):
  File "widgets\QTopPanel.py", line 148, in passTurn
  File "game\game.py", line 320, in pass_turn
  File "game\game.py", line 397, in initialize_turn
  File "game\coalition.py", line 182, in initialize_turn
  File "game\coalition.py", line 203, in plan_missions
  File "game\commander\theatercommander.py", line 82, in plan_missions
  File "game\htn.py", line 82, in plan
  File "game\commander\tasks\primitive\dead.py", line 22, in preconditions_met
  File "game\commander\tasks\packageplanningtask.py", line 51, in preconditions_met
  File "game\commander\tasks\packageplanningtask.py", line 102, in fulfill_mission
  File "game\commander\packagefulfiller.py", line 158, in plan_mission
  File "game\commander\packagefulfiller.py", line 77, in plan_flight
  File "game\commander\packagebuilder.py", line 46, in plan_flight
  File "game\squadrons\airwing.py", line 73, in best_squadron_for
  File "game\squadrons\airwing.py", line 63, in best_squadrons_for
  File "game\squadrons\airwing.py", line 65, in <lambda>
ValueError: AircraftType(dcs_unit_type=<class 'dcs.helicopters.AH_64D_BLK_II'>, name='AH-64D Apache Longbow', description="The legendary 'Apache' is an US twin-turboshaft attack helicopter for a crew of two. It features a nose-mounted sensor suite for target acquisition and night vision systems. It is armed with a 30 mm (1.18 in) M230 chain gun carried between the main landing gear, under the aircraft's forward fuselage, and four hardpoints mounted on stub-wing pylons for carrying armament and stores, typically a mixture of AGM-114 Hellfire missiles and Hydra 70 rocket pods. The AH-64 has significant systems redundancy to improve combat survivability. American AH-64s have served in conflicts in Panama, the Persian Gulf, Kosovo, Afghanistan, and Iraq. Israel used the Apache in its military conflicts in Lebanon and the Gaza Strip. British and Dutch Apaches have seen deployments in wars in Afghanistan and Iraq.", year_introduced=2003, country_of_origin='USA', manufacturer='Boeing', role='Attack', price=20, carrier_capable=False, lha_capable=True, always_keeps_gun=True, gunfighter=False, max_group_size=4, patrol_altitude=None, patrol_speed=None, max_mission_range=Distance(distance_in_meters=92600), fuel_consumption=None, intra_flight_radio=Radio(name='AN/ARC-164', ranges=(RadioRange(minimum=RadioFrequency(hertz=225000000), maximum=RadioFrequency(hertz=400000000), step=RadioFrequency(hertz=1000000), excludes=frozenset()),)), channel_allocator=CommonRadioChannelAllocator(inter_flight_radio_index=2, intra_flight_radio_index=2), channel_namer=<class 'game.radio.channels.ApacheChannelNamer'>) is not in list

### Save game and other files

[liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/8613817/liberation.zip)

**Comment by RndName** [comment]
This looks like #1995
Have you added additional mission types? These were causing the problems in the issue linked.

**Comment by t-o-g-e** [comment]
I have, yes. Just confirmed it works after removing those added types in air wing view. So same issue. Tried to search for similar bugs, but didn't see that, sorry for the duplicate, and thanks for the help.
