### ISSUE TITLE
Skynet Bug

### ISSUE THREAD

**Issue by holyorangejuice** [dcs-liberation/dcs_liberation#2205]
### Affected versions

Development build

### Development build

3820 and above

### Description

We were running a mission, killed a SA-10 site partially. Next time mission was loaded it threw an error. Unknown liberation or skynet bug. It seems skynet is calling for something that isn't there. Turn skynet off in mission options and it works fine. 

### Save game and other files

https://www.dropbox.com/s/tc9vstp4p61q6p5/20220504_064451.jpg?dl=0

https://www.dropbox.com/s/5nfjnvlkc12igvg/3820mozdoktomaykop2.liberation?dl=0

My modified Mozdok to Maykop we're playing
https://www.dropbox.com/s/2znj3mfg98jl38e/mozdok_to_maykop.miz?dl=0

https://www.dropbox.com/s/itu0a8mh10573yj/mozdok_to_maykop.yaml?dl=0

**Comment by RndName** [comment]
@holyorangejuice thanks for the issue report i will have a look into it. You can also upload your save game and so on by just zipping it and drag and drop it over here in GitHub. This is the prefered way :)

**Comment by holyorangejuice** [comment]
[](url
[BUG.zip](https://github.com/dcs-liberation/dcs_liberation/files/8636438/BUG.zip)
)
