### ISSUE TITLE
Buy Replace base defense doesn't refresh available budget in the base window

### ISSUE THREAD

**Issue by s3-chardonjf** [dcs-liberation/dcs_liberation#221]
![image](https://user-images.githubusercontent.com/29724443/96547983-5b93ff00-12ad-11eb-819b-dc0e97b27887.png)

- Click a friendly airbase
- Access Base Defenses tab
- Click MANAGE on a unit
- Replace it with something with a different price tag
- Notice the main window budget has updated but the budget in the lower right corner of the base window did not

**Comment by root0fall** [comment]
@walterroach this should be able to be closed now, I think?

**Comment by walterroach** [comment]
Yes, thanks!
