### ISSUE TITLE
3841 6.0 - Not all purchased planes available for tasking

### ISSUE THREAD

**Issue by holyorangejuice** [dcs-liberation/dcs_liberation#2211]
### Affected versions

Development build

### Development build

3841 - 6.0

### Description

I bought a bunch of planes, 16 f15c and they could not be tasked. Bought 1 more, and passed turn, that 1 plane could be tasked. 

### Save game and other files

[Saves.zip](https://github.com/dcs-liberation/dcs_liberation/files/8656155/Saves.zip)

**Comment by Starfire13** [comment]
#1880
