### ISSUE TITLE
All DCS map objects marked dead by liberation

### ISSUE THREAD

**Issue by holyorangejuice** [dcs-liberation/dcs_liberation#2222]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/2324309577

### Description

Build 3851 - I'm testing my campaign called Up the Coast with my We Run Liberation group. We've been playing for days and were on the final stretch. We did some ground strikes against DCS map objects. I've added the triggers to turn them into objectives in liberation. After the mission we saw that over 200 map objects were declared dead by liberation.

Further review showed that every single map object that I converted into an objective building was marked dead. Any normal liberation objective buildings that are built off the Tech Combine placement were fine. 

Attached is the save prior to launching the mission, the miz file generated by that save, the json that made the objects dead and the tacview file. I can't explain how this happened. 

The latest DCS open beta update was used as well.
[BUG.zip](https://github.com/dcs-liberation/dcs_liberation/files/8725357/BUG.zip)
 

### Save game and other files

[BUG.zip](https://github.com/dcs-liberation/dcs_liberation/files/8725363/BUG.zip)

**Comment by Starfire13** [comment]
So you said you'd been playing for days. Did this problem not occur on earlier turns or did you guys just not attack any map objects before that?

**Comment by holyorangejuice** [comment]
We've had zero issues with this until now. Which is why it is posted now instead of days ago. This is a brand new problem I've never seen in DCS before. So yes, we've hit these targets before without issue.

**Comment by RndName** [comment]
Really strange one.
Some technical background: We track killed map objects with a DCS internal trigger event. Whenever this trigger is fired we add the name of the map object to the state.json file with a small lua script like this one here:
```lua
killed_ground_units[#killed_ground_units + 1] = "War Production-62"
```

So somehow dcs fired the event that all these map objects are dead. The question is: Why!? Never ever seen such a thing before. Are server and client on the same open beta?

Also one question i do not get is why did the dead events start coming in already like 20mins or so in the mission...

![bug](https://user-images.githubusercontent.com/6678803/169299539-ce0696b5-ea59-4a9c-befd-8d921696ae30.png)

**Comment by holyorangejuice** [comment]
We updated the server to the latest open beta with the recent AI changes and all clients of course had to update.

At first we thought something was fixed. Our experience has been either no ground targets are counted as killed or only some. Even if the building showed up as destroyed in the chat and battle damage box.

We quickly realized it wasn't just one objective area it was all of them.

**Comment by DanAlbert** [comment]
I don't know what to do with this one without repro instructions. @RndName, did you have more ideas to investigate? @holyorangejuice, have you seen this more than once? It seems most likely to me that this was a DCS bug that fired a bunch of false events. Garbage in, garbage out.

**Comment by holyorangejuice** [comment]
I have not seen it since. The save file is from 6.0 preview 3841 when that was the latest build.

**Comment by DanAlbert** [comment]
Well since it sounds like you play a ton, that's a pretty good indication that this was a fluke. Unless @RndName had any clever ideas for how to debug this, I think we just have to accept this as not reproducible.

**Comment by RndName** [comment]
@DanAlbert i was not able to reproduce it. I tried a lot of things and i was pretty sure at some point that this has something to do the recent Bugs ED introduced with how they trigger the DEAD Event.
I am 99% sure this is a DCS Issue as there is no way how we could mess up how the base game handles these events.
