### ISSUE TITLE
Caucasus - Up The Coast - New Submission

### ISSUE THREAD

**Issue by holyorangejuice** [dcs-liberation/dcs_liberation#2223]
---

* Campaign name: Caucasus - Up The Coast
* Files: 
[Up The Coast.zip](https://github.com/dcs-liberation/dcs_liberation/files/8745840/Up.The.Coast.zip)

* Update summary (optional)
This is a new campaign submission. I would like it considered to be added for DCS liberation campaigns. I built it to be different than current campaigns but offer a fun liberation experience. There are many ideas that I would like to implement at a later time. Perhaps in another campaign. This one functions as it should and provides a fun experience. 

In the files are yaml for default factions and my custom factions. The redfor faction matters the most. Primarily because it incorporates all Russian equipment, regardless of era. It also includes the silkworm. SA-5 is NOT included on purpose. It also doesn't put anything stronger than AAA on the frontlines as long as you have manpads off. No current redfor faction does what I want it to do for my campaign. I think the closest is Russia 1975 w/ MI24. Add a SA-10 and Silkworm and it would work just fine. 

There is a small note with our group's website in the mission description. There has been a lot of discussion over this matter. I feel it is no different than having my name as the author. My group grew out of necessity for someone to teach new players. My videos and posts on reddit brought many new people to liberation. I received zero monetization for my efforts. I only do this because I truly enjoy helping learn liberation and flying. I have another guy that does all our IT stuff. Without him, this would have never grew either.

I use to mission design for the 107th Through The Inferno back in 2016-17. 

I hope my mission will be considered. Please download and try it out before making any judgement. A lot of time an effort has been involved in this mission. It originally started out as a minor edit of Operation Vectron's Claw. Then the scope grew from there. I invested time to make sure it was a difference experience than Vectron's Claw. I wanted to test the concept of an economy driven campaign. I think I was successful with this.

**Comment by SchmokedPancake** [comment]
Is this for liberation or to advertise your group, not sure if branding your campaign to have it baked into liberation to be shipped would benefit liberation in anyway. 

Also this seems similar to an already present campaign off the coast 

If you take note you can brand your name on the campaign author part, I’d follow the structure how the other guys submitted the ones that come with liberation. This would fall more under the community campaign tab imo

**Comment by holyorangejuice** [comment]
I will leave it up to the liberation team. It has one mention of our group site which is at the end of the description.

I get nothing by having people join our group. It is a responsibility that just happened. I now make videos and teach people how to play liberation.

The videos aren't even monetized and neither is our group. Liberation needs people who are willing to show others.

It can be an overwhelming experience for some to try liberation for the first time. 

To say this is just a branding attempt is an insult. This campaign has taken many hours over several weeks to complete. Not to mention playing it and testing.

It is different than what is currently available and an enjoyable campaign. Well worth having it included.

**Comment by holyorangejuice** [comment]
Don't know why it closed.

**Comment by SchmokedPancake** [comment]
“ I have made a note branding the missions with my group's website. I started liberation solo, found a friend, then made some liberation tutorials that blew up. The numbers of our group are over 100 and we host regular events. I'm constantly teaching people who have just found liberation how to play. I enjoy teaching people and having them enjoy the liberation experience”

your insulting yourself, I have just stated on what you put on the PR. I am not sure where your going with that but like I said, look over the campaigns baked into liberation already to get an idea whats to be expected

**Comment by holyorangejuice** [comment]
Yeah i can read the other campaigns. I like mine the way it is. 

> “ I have made a note branding the missions with my group's website. I started liberation solo, found a friend, then made some liberation tutorials that blew up. The numbers of our group are over 100 and we host regular events. I'm constantly teaching people who have just found liberation how to play. I enjoy teaching people and having them enjoy the liberation experience”
> 
> your insulting yourself, I have just stated on what you put on the PR. I am not sure where your going with that but like I said, look over the campaigns baked into liberation already to get an idea whats to be expected

**Comment by holyorangejuice** [comment]
I really dislike this site. Somehow I keep hitting that button. I have used liberation a long time. I know what the other campaigns say and look like.

I mentioned my group in my original post because I already heard feedback of people getting bent about having a group in there.

In my opinion it is no different than having an author name. Author name could be We Run Liberation or I could have a tag in my name. It is all the same.

**Comment by SchmokedPancake** [comment]
It is very confusing that is for sure.
Besides what I said everything looks good and I’m running currently setting up first turn on my source build to test it out. I take back what I said about being similar to one present already. It is much different. 

Understood 👍

**Comment by DanAlbert** [comment]
I trimmed the description a fair amount to remove the "how liberation works" parts, and moved the bits about WRL to the author field. Description is now just the bits that make it different from the others (strong early red economy that should be targeted heavily).
