### ISSUE TITLE
Faction selection in new game wizard is severely limited

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#2225]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/2324309577

### Description

The factions available to select from the new campaign wizard do not match the number of factions in `dcs_liberation\resources\factions` by a large margin.

All of the available factions:
![image](https://user-images.githubusercontent.com/74509817/169603875-fb419a39-c8d2-4b23-b2cd-f63414b7f19c.png)

### Save game and other files

Not available.

**Comment by Starfire13** [comment]
Hmm. I am still seeing all the factions on #3851 just fine.

![Screenshot 2022-05-21 101849](https://user-images.githubusercontent.com/72491792/169626665-41652a69-2ec8-4162-99c0-4589df0c9a1f.jpg)

**Comment by SnappyComebacks** [comment]
Some strange dev environment issue on my end.  I have no idea why it happened.
I normally run the `Python: Main` vscode run.  I tried `Python: Debug` run it failed, but running `Python: Main` after worked fine.  I did also add the `PYTHONPATH=. python ./qt_ui/main.py;`, but if I remove `PYTHONPATH=. python ./qt_ui/main.py;` again, it still works.
