### ISSUE TITLE
Aircraft not appearing in mission on destroyed airfield despite 29 of them in Liberation

### ISSUE THREAD

**Issue by MiaFoxcat** [dcs-liberation/dcs_liberation#2228]
### Affected versions

5.2.0

### Description

The airfield (Bassel Al-Assad) has a destroyed runway, and since then there are no aircraft at that airfield even though there are 29 MiG-29s listed in Liberation, thus making it impossible to destroy them. The campaign in question is Syria full. The mission is running on a dedicated server, but the aircraft don't even show up in the mission editor.

### Save game and other files

[Save.zip](https://github.com/dcs-liberation/dcs_liberation/files/8777809/Save.zip)
[liberation_nextturn.zip](https://github.com/dcs-liberation/dcs_liberation/files/8777812/liberation_nextturn.zip)

**Comment by Starfire13** [comment]
I generated the mission using your Liberation save (with no changes made) and this is what I get. I count 29 jets.

![Screenshot 2022-05-27 074653](https://user-images.githubusercontent.com/72491792/170585649-5c532c27-0426-4dea-9808-591b8cc29a6b.jpg)
