### ISSUE TITLE
Add "Decoy" mission type

### ISSUE THREAD

**Issue by sgtfuzzle17** [dcs-liberation/dcs_liberation#2233]
**Is your feature request related to a problem? Please describe.**
In an upcoming update, the Hornet will be gaining access to the ADM-141 TALD. This munition acts as a glide decoy, with a noticeable RCS and (IRL at least) dispensing chaff to increase its visibility to radars. It's already implemented on the F-14, and is used by them when tasked for SEAD. The issue here is that rather than suppressing radars, TALDs are used to saturate an emitters scope such that it will begin engaging them (causing the radar to be left emitting for an ARM launch). The current "SEAD" designation doesn't make as much sense for them, especially given we'll be receiving them for the Hornet (which will conflict with its current SEAD loadout deploying AGM-88 HARMs).

**Describe the solution you'd like**
Once we receive the TALDs for the Hornet (or sooner, to give time to test the waypoints with the existing F-14 implementation), a new mission type "Decoy", specifically available to aircraft with decoy ordnance (currently the F-14, Hornet upcoming) should be added to differentiate from the actual Suppression mission and the very different Decoy tasking. This tasking could be paired with the autogenerated SEAD taskings to better enable AI to complete their missions.

**Additional context**
A sensible implementation would see either the current F-14 waypoint system brought across to the Hornet, or alternatively new waypoints could be set up for the aircraft type taking into consideration the differences in performance at given altitudes (important here as the TALD has no propulsion of its own; it is entirely reliant on the launch aircraft's speed and altitude). Generally they should be flying high and fast (as in a BVR/stand-off engagement) and dropping all loaded TALDs in quick succession just within the radar's range. This tasking should only be autogenerated against SAM sites/radars where it makes sense (MERAD and LORAD); sending TALDs against an SA-8 would be a waste of resources. It would probably also be an idea to include appropriate ship groups such as Moskvas etc. in this tasking as it would definitely improve the ability of a given force to engage this type of naval group (rather than 2x Harpoons, a single Hornet with wing tanks can potentially bring 6x TALDs to overwhelm a group's AD and help missiles get through). 

As an aside, [the Eagle Dynamics demo video](https://youtu.be/4_AjGjEF2-g) discussing the TALDs stated that they may be useful against AI CAP aircraft. I'm completely unsure of whether or not this statement has merit as I've never seen them deployed against AI, but generally I think it would be better for now to limit the scope of a Decoy mission to working against surface systems.

**Comment by DanAlbert** [comment]
What's wrong with SEAD?

**Comment by sgtfuzzle17** [comment]
As far as how functional it is, nothing, but SEAD isn't really the right term for a mission deploying decoys where the intention is to make an emitter go active rather than suppress it such that a strike package/other aircraft won't be engaged by it. As stated in the FR, there's also the issue that once we have TALDs for the Hornet, there's a conflict with the current SEAD tasking (using HARMs) - you'd need a new tasking type so that you can have both weapons deployed by the autogenerator. The most sensible option from where I'm sitting would be to make a new tasking built around the TALD specifically, add it to the Hornet, then switch the existing Tomcat "SEAD" tasking over to being labelled as Decoy for consistency.

**Comment by DanAlbert** [comment]
Adding new mission types for every possible loadouts is not practical. I think this is just another case of https://github.com/dcs-liberation/dcs_liberation/issues/270

**Comment by sgtfuzzle17** [comment]
I'm not saying add them for every possible loadout, I'm saying add them because this isn't functionality represented by any of the other mission types we have now. Decoy missions work alongside SEAD and are not the same thing.

**Comment by DanAlbert** [comment]
I think this falls under the umbrella of SEAD.

**Comment by sgtfuzzle17** [comment]
It is quite literally the opposite as the point of deploying TALDs is to make radars emit/lock so they're more vulnerable to actual SEAD weaponry. I don't think closing it for the above reasons is appropriate.
