### ISSUE TITLE
add radio config for mi-24

### ISSUE THREAD

**Issue by ataribaby42** [dcs-liberation/dcs_liberation#2238]
### Affected versions

Development build

### Description

I am unable to communicate with my AI wingman because Mi-24 radio is set wrongly. Flight is set to 251MHz but first radio channel is set to 127.5. Both should be in sync. Opening mission in editor and touch flight frq and save fix the problem.

In mission file:
["frequency"]=251.0, 
												{
["channels"]=
{
	[1]=127.5, <------------ should be same as flight frq
	[2]=135,
	[4]=127,
	[8]=128,
	[16]=132,
	[17]=138,
	[9]=126,
	[18]=122,
	[5]=125,
	[10]=133,
	[20]=137,
	[11]=130,
	[3]=136,
	[6]=121,
	[12]=129,
	[13]=123,
	[7]=141,
	[14]=131,
	[19]=124,
	[15]=134
} 

### Save game and other files

[savegame.ZIP](https://github.com/dcs-liberation/dcs_liberation/files/8839720/savegame.ZIP)

**Comment by ataribaby42** [comment]
It is not about Mi-24 only, AH-64D suffers from same issue.

**Comment by Starfire13** [comment]
> It is not about Mi-24 only, AH-64D suffers from same issue.

https://github.com/dcs-liberation/dcs_liberation/issues/2111

**Comment by Raffson** [comment]
> #2111

Not the same issue afaict, did a couple of quick tests and it seems the Apache no longer has this problem.

**Comment by Raffson** [comment]
> It is not about Mi-24 only, AH-64D suffers from same issue.

Double check the channels on the Apache's second radio. I found the first channel to be synced, though that could be a coincidence.

**Comment by obregman** [comment]
Hi,
Is there an update on this item? Is it likely to be fixed in upcoming releases?
Thanks

**Comment by zhexu14** [comment]
Closing as Mi-24 radio support is added in #3400
