### ISSUE TITLE
Falklands support

### ISSUE THREAD

**Issue by jasonmayr** [dcs-liberation/dcs_liberation#2242]
- [x] pydcs terrain export
- [x] update pydcs
- [x] airport data
- [x] landmap
- [x] icon for new game wizard
- [x] beacon data
- [x] daytime map
- [x] timezone
- [x] weather data
- [x] minor campaign version bump (do this once ready for campaigns)

**Comment by DanAlbert** [comment]
https://github.com/pydcs/dcs/issues/230 is a blocker. pydcs is no longer able to export terrain data.

**Comment by jasonmayr** [comment]
So you’re saying you cannot add south Atlantic? And eventually Liberation will become obsolete. 

Jason
904-335-7803
Sent from my iPhone

CONFIDENTIALITY NOTICE: This e-mail message including attachments, if any, is intended for the person or entity to which it is addressed and may contain confidential and/or privileged material. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message. Thank you.

**Comment by Starfire13** [comment]
What Dan is saying is that we have to wait till PyDCS is updated before support for the new map can be implemented in Liberation.

**Comment by DanAlbert** [comment]
Put up a PR to update pydcs. There's still a lot to do (I updated the OP with the checklist). Here's an example PR for when we added Marianas: https://github.com/dcs-liberation/dcs_liberation/pull/1406.

The biggest thing to do by a very wide margin is the landmap (manually mapping out terrain details so we know where vehicles can and can't go). The rest is pretty easy.

**Comment by DanAlbert** [comment]
https://github.com/dcs-liberation/dcs_liberation/pull/2423 adds beacon data.

**Comment by DanAlbert** [comment]
https://github.com/dcs-liberation/dcs_liberation/pull/2428 adds ATC data (and conveniently fixes some of our old mistakes as well)

**Comment by DanAlbert** [comment]
There's very little point in trying to make the time-of-day info accurate. Sunrise in winter is at 05:00 and in summer it's 09:30. That feature is never going to work well until it's season aware, so I'm just going to ignore that part for now.

**Comment by DanAlbert** [comment]
I added some new pydcs APIs that will get us out of the mess of maintaining ILS and TACAN details by hand. I have a patch locally (that needs a bunch of cleanup) that works with that. I think that's actually all we care about in our hand-edited airfield data, so that's probably done once I get it cleaned up and submitted.

**Comment by DanAlbert** [comment]
https://github.com/dcs-liberation/dcs_liberation/pull/2458 made the airfield data obsolete.

**Comment by DanAlbert** [comment]
https://github.com/dcs-liberation/dcs_liberation/pull/2459 makes the icon obsolete by loading it directly from the DCS install directory.
