### ISSUE TITLE
Not all map features updating properly

### ISSUE THREAD

**Issue by Raffson** [dcs-liberation/dcs_liberation#2253]
### Affected versions

Development build

### Description

I found that many functions on the map are not updating properly. Things like the `ThreatZones` and `NavMeshes` in the left menu only update once, after that it seems to be getting the same data over and over again. Options on right side like "Ships", "Factories", "Air defences", etc. seem to be FUBAR as well. Also supply routes were not being drawn in the correct color after a capture event. So yeah, I think I found a new issues to solve 🤣 

An overview:

- [x] ThreatZones not updating after first update
- [x] Navmeshes not updating after first update
- [x] SupplyRoutes not updating at all
- [x] Air defences: FUBAR
- [x] Factories: FUBAR
- [x] Ships : FUBAR
- [x] Other ground objects: FUBAR
- [x] Active combat: doesn't remove lines when combat ends (dead units should be erased after some period?)
- [x] Allied/Enemy IADS network: doesn't seem to do anything, using some debug messages I can see connections that are linked with themselves

### Save game and other files

Any campaign should do since it's mostly front-end stuff...

**Comment by Raffson** [comment]
Related to #2039 and #2158

**Comment by DanAlbert** [comment]
@RndName I'm not able to confirm if the IADS stuff is working or not. The only campaign that works right now that uses them that I found is Scenic Route, but afaict the IADS network will not display at all. I'm not sure if it's not working, or if there's just nothing to show, since I don't know what this is _supposed_ to look like.

**Comment by RndName** [comment]
> @RndName I'm not able to confirm if the IADS stuff is working or not. The only campaign that works right now that uses them that I found is Scenic Route, but afaict the IADS network will not display at all. I'm not sure if it's not working, or if there's just nothing to show, since I don't know what this is _supposed_ to look like.

@DanAlbert There were some refactors to the IADS system from raffson and i lost the track on the whole feature a bit. I have to look again how it works and if its working correctly. tbh i doubt that it works correctly. The map was completly refactored at the time i made that.
I used the golan heights camapign for testing. This should still work and if not than something changed :D but i will confirm

**Comment by DanAlbert** [comment]
Golan Heights is temporarily busted because it has quad triggers :(
