### ISSUE TITLE
Error with A-4 on carrier

### ISSUE THREAD

**Issue by JeffreyCor** [dcs-liberation/dcs_liberation#2278]
### Affected versions

Development build

### Development build

6.0.0.3985

### Description

Getting an error when trying to create an A-4 flight from a carrier. Ground based doesn't seem to have an problem. 5.2 isn't having this error. Issue has occurred with and without C-130 mod included. Save from most recent does have C-130 included. Seems to occur with all missions started from carrier when selecting what A-4 squadron to use to be from the carrier.

.

### Save game and other files

[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/8987706/liberation.log)
[Vietnam6.zip](https://github.com/dcs-liberation/dcs_liberation/files/8987707/Vietnam6.zip)
![A-4 SEAD from carrier](https://user-images.githubusercontent.com/7409930/175837826-f5bf00ed-798d-408e-be43-9d1715844a42.jpg)

**Comment by JeffreyCor** [comment]
Additional information, I have found this happens if in the mission planner another aircraft if selected first before the A-4. For example, if the A-4 is the aircraft automatically selected it can be changed to a squadron off the carrier without error. But if another aircraft comes up first, or if another aircraft is selected then changed back to the A-4, the error comes up when selecting a carrier based squadron.

**Comment by Raffson** [comment]
#2252 should fix this too
