### ISSUE TITLE
Squadron Limits & AI Purchasing

### ISSUE THREAD

**Issue by holyorangejuice** [dcs-liberation/dcs_liberation#2290]
Before filing, please search the issue tracker to see if this feature has already been requested.

If requesting a DCS AI feature, check If reporting a DCS AI bug, check https://github.com/dcs-liberation/dcs_liberation#dcs-bugs.

**Is your feature request related to a problem? Please describe.**
The AI planner for liberation doesn't understand squadron limits and how it should purchase aircraft. The AI will mass purchase the aircraft it thinks it needs. It might be 20, 30, or more aircraft of the same time. Yet it can only field by default 12. If it takes losses, which it should, then it can field even less next turn. Though since it didn't buy any other aircraft, they don't field very much.

**Describe the solution you'd like**
If the squadron pilot limit is selected, the AI should buy a wider variety of aircraft. This would allow them to field something when they lost a lot of pilots. It would also lead to more variety of aircraft in a mission if there are multiple squadrons to choose from.

**Comment by DanAlbert** [comment]
This was effectively addressed in 7. There's an option (still an option because it's new and we didn't want to force it on without more testing) to limit the sizes of squadrons. It's so far proven a much better system than pilot limits though.
