### ISSUE TITLE
Just an idea to implement recoinassance missions

### ISSUE THREAD

**Issue by Goliathus-21** [dcs-liberation/dcs_liberation#2305]
Hello to all gods of the DCS Liberation campaign,

I´m a huge fan of this project and I play DCS only in SP and with the Liberation campaign in my F/A 18 C.

I´ve been thinking recently if it is possible to implement recoinassance missions in the campaigns for there reasons:

- the "fog of war" is not implemented in the game planning, so since the beginning of the campaign there are missions planned against (even mobile) SAM systems, that would be probably situated on hidden places and the exact possiton would not be known the enemy
- if there is DEAD mission planned, you get precise GPS coordinates on your kneeboard, which sounds great at first, but if there was no previous recoinassance mission done, you shouldn´t know this exact coordinates to plan your strike
- having the exact GPS coordinates on the kneeboard means you don´t need to bring ATFLIR or datalink pod (with SLAM-ER), because you know where to shoot your missiles/drop GPS guided bombs.

I thought, that maybe recoinassance missions could be planned in the campaign (at least for the AI, because I think most players wouldn´t prefer to fly recoinassance missions) to reveal enemy positions or/and their exact GPS coordinates. Maybe this could be done as a mission where the recoinassance aircraft must pass the waypoint in a certain altitude (under cloud base) and successfully return to the base. If this mission is successfull, you get the exact GPS coordinates of the enemy position in the territory and can plan a precise strike on enemy poisitons where the recoinassance was done. 

This would implement something similar to the "fog of war" for the mission planning and force the players to search for the exact location of the enemy ground targets, that wouldn´t be revealed to us without sooner than they could be spotted by an recoinassance flight or by nearby friendly ground units.

I´m not sure if this could be done, but maybe it could make things more interesting and much harder to plan strikes on targets, where you didn´t do any recoinassance and thus you can´t know what to expect. At the moment we have too much information, that would be almost impossible to get in real life.

Thx,

Goliathus

**Comment by Starfire13** [comment]
Yes, there is an FR open for ELINT. https://github.com/dcs-liberation/dcs_liberation/issues/272

**Comment by DanAlbert** [comment]
Dup
