### ISSUE TITLE
Flights consisting of Bombers with escorts have to low airspeeds (50 nautical miles) 

### ISSUE THREAD

**Issue by ShinatroXD** [dcs-liberation/dcs_liberation#2315]
### Affected versions

5.2.0

### Description

It doesn t matter hwo many different missions you start when creating a missionm through liberation and looking at it in the mission editor in dcs the cas flights of the enemy side with escorts hass unrealistic low airspeeds adjusted (40 nm) for every waypoint. THis leads to the flights never starting  since their TOT is outside of the scope of the predetermined missiion time (1 h). THis leads to the enemy not having air support on the frontline and your side always winning the forontline engagement.

### Save game and other files

here is an created mission as u can see the airspeeds for neemy boimber at all waypoint sare unrealisticly low

**Comment by DanAlbert** [comment]
Nothing attached
