### ISSUE TITLE
Automatic ACLS Setup

### ISSUE THREAD

**Issue by ColonelCipher** [dcs-liberation/dcs_liberation#2316]
**Is your feature request related to a problem? Please describe.**
As someone who likes playing with ACLS enabled on the carriers, it's frustrating to have to dig through the pile of jets set up to spawn on the carrier to set up ACLS for each generated mission.

**Describe the solution you'd like**
Considering setting up ACLS is just adding two waypoint actions in the mission editor, I think it would be relatively simple to add this to every carrier spawn.

**Comment by DanAlbert** [comment]
What do we need to do?

**Comment by Raffson** [comment]
@ColonelCipher what version you on? I just generated a mission with a carrier using the dev-branch, inspected the mission and clearly see everything being set, i.e. TACAN, ICLS, DL & ACLS.

**Comment by ColonelCipher** [comment]
@Raffson I'm on 5.2.0, that might be why I'm not seeing it get set up.

**Comment by Raffson** [comment]
> @Raffson I'm on 5.2.0, that might be why I'm not seeing it get set up.

Then I recommend trying out the dev-builds, because I think what you're asking for is already implemented.

**Comment by ColonelCipher** [comment]
@Raffson Ok, I'll check it out.
