### ISSUE TITLE
'NoneType' object is not iterable

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#2321]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/2678854329

### Description

Trying to generate a campaign on build #4113 (it is an unmerged pull request that I'm testing - "Add livery selector in AirWingConfigurationDialog") results in this error.

![Screenshot 2022-07-16 091958](https://user-images.githubusercontent.com/72491792/179323537-8f17f76f-25d7-4e6b-9ebd-8b715f8b8754.jpg)

### Save game and other files

Save game not available as campaign cannot be generated.

**Comment by Raffson** [comment]
Solved, turns out Starfire was missing a registry entry, guards have been put in place to prevent exceptions from happening during the air wing configuration.
