### ISSUE TITLE
WW2 factions have no access to Building Oil

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#2322]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/2652273486

### Description

WW2 factions (Allies, Germany, and Soviet Union) on the aggressor side (player side works fine) will produce this error on campaign generation, but only on selected maps. Error seen on Caucasus, Marianas, Persian Gulf, and Syria (tried more than one campaign on each), but works fine on Normandy, Channel, and Nevada.

![Screenshot 2022-07-16 095814](https://user-images.githubusercontent.com/72491792/179327564-252389e9-81da-44a8-88e9-70f76c9d77e3.jpg)

### Save game and other files

Save file not available as campaign cannot be generated due to the error.

**Comment by Raffson** [comment]
Looking at https://github.com/dcs-liberation/dcs_liberation/blob/develop/game/data/building_data.py

It seems like it's defined that way, and if I had to guess, the maps you tried probably had campaigns with no oil platforms in it. But I wonder why because it looks like this was done intentionally 🤔

**Comment by Raffson** [comment]
I guess the first question we need to answer is the following:

Is every faction supposed to be compatible with any campaign? If so, we've got a problem to fix. If not, then it's a simple conclusion, i.e. the faction is simply not compatible with the campaign. In that case we could use a slightly more indicative pop-up, which is a simple fix...

**Comment by Starfire13** [comment]
Up till this point, all factions have been selectable for all campaigns.

**Comment by Raffson** [comment]
https://github.com/dcs-liberation/dcs_liberation/blob/52c0be63ea0d35837eb7b7c8fec6d9a97f9388b4/game/factions/faction.py#L245-L262

This is where I think I see a problem, I don't understand why there's a difference between "default buildings" and "required buildings", except maybe for "farp" but other than that I would think those buildings should all be "required".

**Comment by DanAlbert** [comment]
The map is irrelevant, it would break any campaign with offshore targets owned by WW2 factions.

https://github.com/dcs-liberation/dcs_liberation/pull/2478 fixes this by making the oil platform a required building type, so WW2 factions will be able to generate it as well. I haven't checked what 5.x did in this situation, but this seems to best match the designer's intent. The other options would be skipping generation of those target types for factions without oil platforms, or picking some alternative offshore target type for those factions.
