### ISSUE TITLE
'NoneType' object has no attribute 'location'

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#2323]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/2652273486

### Description

If you try to plan a flight on turn 0, you get this error.

![Screenshot 2022-07-16 145257](https://user-images.githubusercontent.com/72491792/179340045-441a83a9-33d6-44b9-8fc4-f11771d8d8a6.jpg)

In 5.2, the Create Flight window still pops up, but just shows you have no capable aircraft available.

![Screenshot 2022-07-16 145311](https://user-images.githubusercontent.com/72491792/179340046-92d9bf23-2be8-49c5-90ce-7bd45171654a.jpg)

If you've got flights planned and hit take off, and then abort and try to plan another flight, you get the same error. This is with fast forward turned off.

### Save game and other files

This save is on turn 0 with no aircraft. Try planning a package and you'll get the error.
[No Aircraft Turn 0 Save #4101.zip](https://github.com/dcs-liberation/dcs_liberation/files/9125187/No.Aircraft.Turn.0.Save.4101.zip)

For this save, hit take off, then abort, then try to plan a package. You'll get the error.
[8 Aircraft Turn 1 Save #4101.zip](https://github.com/dcs-liberation/dcs_liberation/files/9125190/8.Aircraft.Turn.1.Save.4101.zip)

**Comment by Raffson** [comment]
A new bug introduced by my bug-fix 🤣 

I should have a fix real quick for this...

Edit: this is for the first case though, I'd have to see what goes wrong in the second.

**Comment by Raffson** [comment]
Ok I think I can safely say that the second case is also normal, I don't even think it required hitting take-off and abort because you've only got 4x A-10's, and those are planned so you have no capable aircraft left, so it's all legit :p

PR coming up...

**Comment by Starfire13** [comment]
I also have 4 untasked F-15Cs in that second save.

**Comment by Raffson** [comment]
> I also have 4 untasked F-15Cs in that second save.

Hmmm, then what I was afraid of is actually the case. I'll have a closer look but this is definitely a separate problem...

**Comment by Raffson** [comment]
Ok here's something interesting, looking at the airwing dialog I see the following:

![image](https://user-images.githubusercontent.com/10977187/179431672-255479aa-5d7a-466c-9363-2586ce49028d.png)

So a flight of A-10s is planned, 4 pilots seem to be assigned. The same is true for the F15s, but there's no flight to be seen. Matter of fact if I open up the inventory, I only see 4 A-10s. At the same time when I open Ramat David, I can definitely see 4 F-15s 🤣

**Comment by Raffson** [comment]
Somehow those F-15s are allocated, can't say how but passing the turn brings them back...

**Comment by Starfire13** [comment]
My recollection is this is an old problem where if you plan a package and it fails for whatever reason, those aircraft are not freed up.

We've had multiple users encounter this, particularly in multiplayer where the aircraft don't show up in the air wing pane (though are visible in inventory) but are visible when clicking on an airfield, and then come back when you pass turn.

**Comment by Raffson** [comment]
That's definitely a separate issue then, once all the other things are done I might have a look at that.
