### ISSUE TITLE
Layout buildings.miz file has WWII asset pack dependencies

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#2324]
I was trying to view `dcs_liberation\resources\layouts\buildings\buildings.miz` and couldn't open the file due to not having `WWII Armour and Technics`.  Perhaps the WWII dependencies should be moved to their own file or another standard object should be used in their place?

**Comment by RndName** [comment]
It is completly okay to use a standard model in the miz file of the layout. The "real" unit type which will be used in the group will be determined using the layout yaml. The unit used in the miz file is just a placeholder to determine position (x,y) and the heading. The unit_type is not even used.
So this file can savely be updated to use standard dcs units.

**Comment by RndName** [comment]
And it is also good to split up large layout miz like the building.miz to one single miz per layout instead of having one miz for multiple layouts. But that was not done yet.

**Comment by Khopa** [comment]
It's easier to manipulate the template with the real units, so i'm going to split up the building.miz in two files : 
- original building.miz without the ww2 specific stuff
- www2building.miz with the ww2 stuff

For future layouts, let's keep making one miz file per template.
