### ISSUE TITLE
Squadren names added when starting a new campaign are not honored

### ISSUE THREAD

**Issue by sicwan** [dcs-liberation/dcs_liberation#2325]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/2652273486

### Description

when I started a new campaign, I noticed that all of the squadrons were using the same name, I changed them to be different, and added a few (added AH64's, added a F18 squad to Kobleti, and a few other minor changes to the default squads. When I got in the map the first time, placed orders for aircraft, upgraded sams, noticed that none of the new squads I put in were there, decided to just play and did the first round, and then noticed the squads all went back to defaults.

### Save game and other files

[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/9128780/liberation.log)
[autosave.zip](https://github.com/dcs-liberation/dcs_liberation/files/9128781/autosave.zip)

**Comment by Raffson** [comment]
Have you pressed the 'Accept' button? If so, I've already got an open PR to fix that. Until you see the button change into 2 separate buttons for accepting/discarding, only use the X button in the top-right, that'll still save your changes.

**Comment by sicwan** [comment]
I pressed the accept button at the bottom of the screen, Ok, I'll make note of that. Thanks!

**Comment by Raffson** [comment]
Fixed by #2318
