### ISSUE TITLE
MiG 15 and 19 Invalid radio frequencies

### ISSUE THREAD

**Issue by lardderigible** [dcs-liberation/dcs_liberation#233]
Both the MiG 15 and 19 have invalid radio frequencies (251MHz). This causes an error that does not allow the mission to be flown.

**Comment by DanAlbert** [comment]
Pushed a change to 2.2 to fix the error and assign preset channel 1 as the flight channel for the MiG-19P. Not able to preset ATCs because we don't have the VHF ATC data there, and AWACS only operates on UHF currently. https://github.com/Khopa/dcs_liberation/issues/300 covers the improvements.
