### ISSUE TITLE
Unhandled exeption in script

### ISSUE THREAD

**Issue by ED9TR** [dcs-liberation/dcs_liberation#2334]
### Affected versions

5.2.0

### Campaign name

liberation_main not even opening

### Blue faction

.

### Red faction

.

### Modifications to default settings

Not even modified DCS

### Description

When I try to run  liberation_main.exe it gives error.

### Log file

![image](https://user-images.githubusercontent.com/109707165/180110111-ee29c6b9-8ea3-43a9-bbc3-7af1a231f2c1.png)

**Comment by DanAlbert** [comment]
No clue based on the error message, and without being able to repro there's nothing we can do.
