### ISSUE TITLE
Mirage F-1

### ISSUE THREAD

**Issue by Raffson** [dcs-liberation/dcs_liberation#2335]
Before anyone else opens an issue for the newly released Mirage F-1, here's an overview on what needs to be done:

- [x] pydcs needs to be updated
- [x] creating yaml files in `resources/units/aircraft`
  * [x] Initially only the F1CE variant is available to fly
  * [x] BE, EE and M models will becomes available later, so preferably add support now...
  * [x] Making all AI assets available is quite a bit of work, for now I added the B, C-200, CT and EQ variants
- [x] create some squadrons for different variants
- [x] include variants of the aircraft in different factions (France, Spain, Iraq, Bluefor cold/modern)
- [x] add icons for air wing dialog
- [x] support for mission types (CAP/CAS/STRIKE/RUNWAY_ATTACK/OCA, except for C-200 being CAP only)
- [x] create banners
- [x] add payloads, special thanks to @Starfire13
- [x] radio support for Mirage-F1CE, special thanks to @jake-lewis 

As for the first point, I have a PR open at pydcs for the livery scanner which includes an export, so it shouldn't take too long until pydcs has updated either due to my PR or someone else's.

If I missed anything, feel free to point it out 👍

**Comment by Raffson** [comment]
Currently 9 variants were added in #2336:

- Mirage F1CE
- Mirage F1C-200
- Mirage F1CT
- Mirage F1B
- Mirage F1BE
- Mirage F1EE
- Mirage F1EQ
- Mirage F1M-CE
- Mirage F1M-EE

I've included these aircraft in  French, Spanish, Iraqi and 'Bluefor Coldwar/Modern' factions accordingly.

**Comment by magwo** [comment]
Pydcs has been updated.

**Comment by Raffson** [comment]
> Pydcs has been updated.

Checked! 👍
