### ISSUE TITLE
Flights of non-flyable aircraft can be given player slots

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#2339]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/2723309031

### Description

Note: This bug is present in both the dev build and in 5.2

This is a long-standing bug where flights of non-flyable aircraft can be given player slots. Doing so prevents mission generation. With the release of the Mirage F1 and its multiple variants (only one of which is currently flyable), I think this might be a good time to tackle the bug. Otherwise, we are going to get a bunch of folks asking why they can't fly their Mirage F1 (because they've given a player slot to a non-flyable variant).

### Save game and other files

[Non-flyable Aircraft with Player Slots Example #4151.zip](https://github.com/dcs-liberation/dcs_liberation/files/9173576/Non-flyable.Aircraft.with.Player.Slots.Example.4151.zip)

**Comment by Raffson** [comment]
Soooo, disable the "player" checkbox in the flight dialog?

**Comment by Raffson** [comment]
Ok I can already disable the player checkbox, but that's not enough. I think the whole "player textarea" in the air wing config dialog should be disabled if the aircraft in question isn't flyable.
