### ISSUE TITLE
Strikes attack dead buildings

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#235]
I'm noticing that AI aircraft are attacking just a single point on strike missions, even if there is a dead target or no target at that point. Let's say there are three APCs, at waypoints 3, 4, and 5. The AI flight will drop all their ordnance on waypoint 3, even if the vehicle there is already completely 100% dead (it might have been killed that mission or on a previous mission). Even on subsequent returns to the same target on later missions, they will still bomb that same wreck on that same site, leaving the rest alone.

**Comment by zelosos** [comment]
Also only the first aircraft of an formation is dropping its bombs.
