### ISSUE TITLE
SAM Sites Asset Pack & Massun92-Asset Pack

### ISSUE THREAD

**Issue by jasonmayr** [dcs-liberation/dcs_liberation#2353]
* Mod name: Massun92-Asset Pack
* Mod URL: https://massun92.gumroad.com/l/VTreS
* Update or new mod?

* Mod name: SAM Sites Asset Pack
* Mod Information URL: https://forum.dcs.world/topic/275571-sam-sites-asset-pack-a-3d-assets-mod-to-populate-you-sam-sites-farp-and-other-bases/
* Mod URL Download: https://drive.google.com/file/d/15STKuCIaQcbbjSO_xlDKvREtbYJ67an5/view
* Update or new mod?

I'm working on a FOB improvement's to the current FARPS for Helicopters. Which will include FOB Hesco Barrier Walls, Lighting, Guard booths, and other props to improve the look and overall effectiveness of FARP's.

**Comment by RndName** [comment]
#1939 is already about adding 2SAP

**Comment by zhexu14** [comment]
Closing as the Massun Asset Pack is now a part of DCS and there is a separate issue on 2SAP.
