### ISSUE TITLE
Build #147 fd96902 - New Package - Add flight results in error

### ISSUE THREAD

**Issue by s3-chardonjf** [dcs-liberation/dcs_liberation#236]
- Load a game (tested with creating a new one)
- Buy units and pass turn. Notice some flights were generated successfully by the app.
- Right click a target and create a new package
- Click Add Flight, notice the error

Traceback (most recent call last):
  File "qt_ui\windows\mission\QPackageDialog.py", line 157, in on_add_flight
  File "qt_ui\windows\mission\QPackageDialog.py", line 118, in game
AttributeError: 'Game' object has no attribute 'game'

**Comment by Kerbo416** [comment]
i am encountering this issue as well

**Comment by DanAlbert** [comment]
Fixed earlier today with https://github.com/Khopa/dcs_liberation/commit/cc61893bcacfb4bf8169f7c04fa11069f195f8ee
