### ISSUE TITLE
skynet not working

### ISSUE THREAD

**Issue by Tinchus2009** [dcs-liberation/dcs_liberation#2369]
### Affected versions

5.2.0

### Description

Not sure if it is a bug. I have the skynet plug in activated. I have unselected "start sam in red mode" option. 
To my understanding, all the synet network should start with all sams off, only the ewrs operational, and they should put the sams in red mode when enemies are in rage.
his is not happening. sams starts in green mode and they stay like that even with planes being way inside their firing range.
Ideas?

### Save game and other files

[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/9332724/liberation.log)

**Comment by DanAlbert** [comment]
Skynet integration has been pretty thoroughly redone in 6, so it's pretty unlikely any bugs in 5 are still present. We have confirmed that Skynet is working in 6.
