### ISSUE TITLE
A4-E Skyhawk not flyable

### ISSUE THREAD

**Issue by RWallaby** [dcs-liberation/dcs_liberation#2376]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/suites/7763649408/artifacts/326325729

### Description

What Went Wrong?
Whenever an A4-E Skyhawk is present in a mission (even just purchased idle on an airfield), once the "Take Off" button is selected, An unexpected Error Occurs and we are unable to fly that mission.

To Reproduce:
Load up Liberation 6.0.0-4215-preview
Create new Campaign
Select Caucasus Black Sea
Select Next
Select USAF Aggressors (Or any faction with A4-E Skyhawk)
Select Next
Enable A-4E Skyhawk (version 2.0.0) check box
Select Next
Select Next
Select Finish
Add a Squadron of A-4E Skyhawks to Sukhumi-Babushara (any airfield will do)
Select Accept Changes and Start Campaign
Purchase 1x A-4E
Begin Campaign
Select Take Off
Select Yes
Receive Error
![imgtotext](https://user-images.githubusercontent.com/58236123/184695819-637e185c-d5c9-4646-8c4a-915cee0af0cd.jpg)

### Save game and other files

[autosave.zip](https://github.com/dcs-liberation/dcs_liberation/files/9339141/autosave.zip)
[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/9339148/liberation.log)

**Comment by DanAlbert** [comment]
I believe for the moment it's all mods. They broke during a pydcs update and they haven't been update yet.

**Comment by Raffson** [comment]
@DanAlbert If you're interested, cherry-pick 9fbc2d2c58bdf1707e19815cfda4af2970b224f7 as a temporary solution till the next pydcs update, assuming it'll contain the initialization delay for the livery scanner. Either way those changes in pydcs aren't gonna cause real issues, it's just a matter of removing the line `Liveries = Liveries()["PlaneLiveryName"]` for each aircraft. A simple regex ought to do the trick once it's required.

**Comment by RWallaby** [comment]
Ah ok,
Glad it wasn't me being an idiot :)
