### ISSUE TITLE
Unable to open Mozdok to Maykop campaign in mission editor

### ISSUE THREAD

**Issue by NovaLogicDev** [dcs-liberation/dcs_liberation#2383]
### Affected versions

5.2.0

### Description

The mission editor reports that the mozdok to maykop campaign template mission file has a WWII assets pack dependency, despite the campaign being playable without the assets pack.
![image](https://user-images.githubusercontent.com/39929570/186516159-98109dda-e844-469b-8f1f-f7923e83e5e8.png)
![image](https://user-images.githubusercontent.com/39929570/186516186-6cd86095-f808-42ea-80ac-50c8b2b44a54.png)

### Save game and other files

[mozdok_to_maykop.zip](https://github.com/dcs-liberation/dcs_liberation/files/9419231/mozdok_to_maykop.zip)

**Comment by Starfire13** [comment]
This is due to a single M1 Garand infantry unit placed on the map, it appears by accident. I have removed it and submitted the fixed miz file here: https://github.com/dcs-liberation/dcs_liberation/issues/2391

**Comment by NovaLogicDev** [comment]
Perfect, thanks, I'll close this in favor of #2391
