### ISSUE TITLE
Beta Mission Generation Error

### ISSUE THREAD

**Issue by Bigs2013** [dcs-liberation/dcs_liberation#2384]
### Affected versions

Development build

### Development build

4225

### Description

https://gyazo.com/8e275e7e53d6ccda770b9fe96c4cd9cb

PS (After receiving this error my money is now at 3M even though the game is registering the proper amount (Under 5 Mil)

### Save game and other files

[Beta.zip](https://github.com/dcs-liberation/dcs_liberation/files/9422254/Beta.zip)

**Comment by Bigs2013** [comment]
Error was resolved by reloading save although money is still at 3Mil for whatever reason

**Comment by Starfire13** [comment]
I believe this error is caused by planning flights after having already triggered fast forward, either by pressing the fast forward buttons or hitting take off and then aborting.

**Comment by Bigs2013** [comment]
> I believe this error is caused by planning flights after having already triggered fast forward, either by pressing the fast forward buttons or hitting take off and then aborting.

It was a aborted mission so that might be it but still doesn't explain the money indicator

**Comment by Starfire13** [comment]
If you abort a mission, you have to reload the save before planning any new flights.

**Comment by Bigs2013** [comment]
> If you abort a mission, you have to reload the save before planning any new flights.

Yep but again keeping this report since the money glitch is attached

**Comment by Starfire13** [comment]
Known error caused by post-take off tasking successfully replicable. Money error not replicable after several tries. Money does not decrease after the error is encountered.

Please can you clarify what you mean by "the game is registering the proper amount (Under 5 Mil)"? Where are you seeing this 5 mil? I am only seeing 3 mil.

**Comment by Bigs2013** [comment]
> Known error caused by post-take off tasking successfully replicable. Money error not replicable after several tries. Money does not decrease after the error is encountered.
> 
> Please can you clarify what you mean by "the game is registering the proper amount (Under 5 Mil)"? Where are you seeing this 5 mil? I am only seeing 3 mil.

I'm a idiot disregard 🤦‍♂️
