### ISSUE TITLE
Death Hanger @ Ramat David Airbase

### ISSUE THREAD

**Issue by Bigs2013** [dcs-liberation/dcs_liberation#2387]
### Affected versions

Development build

### Development build

4225

### Description

Parking Space 37 is located in a hanger that instantly kills all objects that either attempt to enter or spawn inside
https://gyazo.com/22c39e7a29bbe78b72e8cdd90ee2d539
https://gyazo.com/d33df6844eee4f62d29b4d568b6ba8dd

### Save game and other files

None

**Comment by DanAlbert** [comment]
Allocation of specific parking spaces isn't something we're able to do currently. This should be reported against DCS so they can fix the map.
