### ISSUE TITLE
Causality Report Squished together

### ISSUE THREAD

**Issue by Bigs2013** [dcs-liberation/dcs_liberation#2389]
### Affected versions

Development build

### Development build

4225

### Description

Maybe make this a scrollable window?

https://gyazo.com/dce119dad25339b70a100852a515cba7

### Save game and other files

none

**Comment by Starfire13** [comment]
This is more of an FR than a BR.

You can drag the window down to expand it.

**Comment by DanAlbert** [comment]
Closing because no repro artifacts. No way for us to verify a fix without that. Upload those and we'll reopen.

**Comment by Bigs2013** [comment]
> Closing because no repro artifacts. No way for us to verify a fix without that. Upload those and we'll reopen.

Litterly just do /killall in any game to recreate this lmao, but as Starfire pointed out, it's more of a feature request as he taught me I could just expand the window

**Comment by DanAlbert** [comment]
Did not know about killall. Follow the template though. Our time is very limited and we have nearly unlimited bug reports. Anything that makes a bug harder to investigate will lower its priority. We want a repro case because it's the only way we can know that we've fixed _your_ bug and not _a_ bug.

**Comment by DanAlbert** [comment]
This also helps with triage, btw. Since we have so many bug reports, we can't fix them all. If the bug is not important enough to you to be worth the time of following the template, it's probably low priority for us to fix.
