### ISSUE TITLE
SAM sites with no launch capability should be marked on the map

### ISSUE THREAD

**Issue by unixwitch** [dcs-liberation/dcs_liberation#239]
when the enemy force is PMC American, SAM sites consist of several M1097 launchers and a single M818 supply truck.  when attacking these, i usually destroy the M1097s but don't bother with the M818.  this means the sites are effectively disabled, but because the M818 unit is still present, it shows on the map as an active SAM site.  instead, perhaps it could be shown with an 'X' over it or some other marker to indicate that it can't actually do anything.

**Comment by walterroach** [comment]
Also, should remove the engagement ring from disabled SAM sites.

**Comment by DanAlbert** [comment]
https://github.com/Khopa/dcs_liberation/commit/a6dc3d2affadaa2ee1472bf8af92d7a1c5db8799 and https://github.com/Khopa/dcs_liberation/commit/d946a9e526978cbe2a5868e0e549586f2cc3e7d5 did the bulk of this by removing the threat rings when they aren't threats.

Is that sufficient, or should the icon change as well?

**Comment by Malakhit** [comment]
New icon added, and thus this item should be complete.
