### ISSUE TITLE
Change of the Awacs pattern in order to limit the Link16 interruption

### ISSUE THREAD

**Issue by Maveric33** [dcs-liberation/dcs_liberation#2392]
Hello,

DCS Liberation v5.2
DCS World v2.7.17

The problem is the orbiting pattern of the Awacs in your mission generator, indeed, by modifying the mission in the editor to put the Awacs in Hippodrome I do not encounter the problem anymore

This has been very well analyzed in this post.
https://forum.dcs.world/topic/281416-awacs-blindstops-when-orbiting/

**Describe the solution you want**.

Can you please change this default setting to Hippodrome with the same criteria as the tanker, it will be perfect.

Thanks a lot in advance

Thanks again for this great tool and all your work

**Comment by DanAlbert** [comment]
This has already been done in 6.

**Comment by Maveric33** [comment]
Thanks
