### ISSUE TITLE
german 1944 faction not properly playable -> airfields swapped

### ISSUE THREAD

**Issue by ombrek4** [dcs-liberation/dcs_liberation#24]
Hi Khopa,
Thank you for your awesome work!
I have an issue to report:

when trying to play a german WWII campaign, the german Airbases are where the allied Bases should be and vice versa. Tried in multiple theaters.

edit: Version DCS.Liberation.2.0RC9

**Comment by Khopa** [comment]
This will be possible to swap positions in RC10, so you can properly play as Germany.

**Comment by Khopa** [comment]
Fixed in 2.0.10

You can use the "invert map" checkbox to setup german starting positions for campaigns in Channel and Normandy. 

Please re-open if you encounter the issue again.
