### ISSUE TITLE
Option to start campaigns at night time

### ISSUE THREAD

**Issue by Hornet2041** [dcs-liberation/dcs_liberation#2400]
It'd be a minor immersion improvement if we had the option to start campaigns at night time, as most invasions/campaigns of the modern area have typically begun at night time.

**Comment by DanAlbert** [comment]
We have a start date field... Did we forget time?

**Comment by Hornet2041** [comment]
i... think so? i don't remember seeing a time selection anywhere. That
would be cool though.

**Comment by Starfire13** [comment]
Yeah, there's definitely no time field. Would be nice because I like starting off with an early dawn attack and always have to set this manually in the mission editor.

**Comment by DanAlbert** [comment]
That should be just about no effort, so I'll do this in 6.

**Comment by DanAlbert** [comment]
https://github.com/dcs-liberation/dcs_liberation/pull/2401 technically does what you asked for, but turn 0 is not actually an interesting thing to control :) I'll have to fix it so that time doesn't advance between turn 0 and turn 1 before this is actually useful, but that'll have to be another night.

**Comment by DanAlbert** [comment]
https://github.com/dcs-liberation/dcs_liberation/pull/2404 fixes that issue, so #2401 is re-checking with autosubmit. I'll leave this open for UI and docs, bot for now, just do something like:

```yaml
recommended_start_date: 2004-01-07 06:00:00
```

**Comment by DanAlbert** [comment]
Forking the UI work to https://github.com/dcs-liberation/dcs_liberation/issues/2550 since I'm not planning to tackle that in 6.
