### ISSUE TITLE
Carrier killed in state.json but not being removed from game

### ISSUE THREAD

**Issue by Bigs2013** [dcs-liberation/dcs_liberation#2405]
### Affected versions

Development build

### Development build

4211

### Description

Carrier refuses to die. I believe it is a zombie carrier and is out to infect us all with SU-33 infection bullets! Watch out!

Lmao, in all seriousness though Star helped me confirm that it wasn't one sided

### Save game and other files

[Beta.zip](https://github.com/dcs-liberation/dcs_liberation/files/9481676/Beta.zip)

**Comment by DanAlbert** [comment]
We have no say in DCS's damage system.

**Comment by Bigs2013** [comment]
It's dieing in game and is registering but liberation keeps reserecting it

**Comment by Starfire13** [comment]
Yeah. If it's showing as killed in the state.json, it shouldn't come back again next turn, right?

**Comment by Starfire13** [comment]
Attaching two state.json files from 2 consecutive turns (Turns 2 and 3) where the Admiral Gorshkov was destroyed (blown up and sunk), and it's miraculously back the next turn. You'll see that the kill event is being recorded in both files.
[state.json.zip](https://github.com/dcs-liberation/dcs_liberation/files/9482484/state.json.zip)

Also attaching saves for turns 1 to 3 (#4211):
[Carrier Kill Test #4211 Turn 1 to 3.zip](https://github.com/dcs-liberation/dcs_liberation/files/9482489/Carrier.Kill.Test.4211.Turn.1.to.3.zip)

**Comment by DanAlbert** [comment]
That wasn't clear from the report. Reopening.
