### ISSUE TITLE
[feature request] Add weapon costs

### ISSUE THREAD

**Issue by zelosos** [dcs-liberation/dcs_liberation#241]
Weapons should cost also money.
This way the player gets insentives to use dumb bombs and not so powerfull weapons.
Enemy AI player should be limited as well to keep the balance.
Also the income has to be increased.

**Comment by jeetsukumaran** [comment]
One way to do this is for Liberation to track ordnance used in the previous mission and save it to the "state.json" file. The costs can then be deducted from the next round's budget. May result in a negative budget, but that's no big deal (we all go into debt now and then!).

**Comment by DanAlbert** [comment]
Has been discussed on discord a few times. The AI will not be able to handle this so it's unlikely that it could ever be done well. I don't think we'll ever do this, so being honest about that and closing this.
