### ISSUE TITLE
Possible minor bug - wrong ATC freq

### ISSUE THREAD

**Issue by Goliathus-21** [dcs-liberation/dcs_liberation#2416]
### Affected versions

5.2.0

### Description

Hey guys,

I was running the Syria - Operation Peace Spring campaign recently and I came across a possible minor bug.

After I captured the Damascus airbase I departed from this airport with my F/A-18C and I found out that I can´t reach the ATC via CH1 preset freqency on COMM2. This is because the mission generator generates wrong frequency 251.850 MHz (on the kneeboard as well), but the Damascus ATC is listening on frequency 252.650 MHz.

I´m not sure how the DCS Liberation mission generator works, I´m just a simple user of this great dynamic campaign generator, but I guess that the freq. of the Damascus ATC was different somewhere in the past, but now it should be updated to 252.650 MHz in the DCS Liberation files, so it could be generated correctly. Of course,  it is easy to overcome this "issue" by changing the preset frequency manually...

Please take a look at this issue somewhere in the future. I enclose screenshots of my kneeboard with wrong ATC frequency (as I said, I departed from the Damascus airport), screenshot from the mission editor, where there is stated wrong ATC frequency, and a picture of the F10 map with correct ATC frequency.

Thx,

Goliathus
![Kneeboard Damascus Freq](https://user-images.githubusercontent.com/84329357/188567513-9c1c4626-bd55-4a4c-adb2-ac0362d02da3.jpg)
![Mission editor](https://user-images.githubusercontent.com/84329357/188567516-bad5657c-5b1f-46a9-8531-2bbd5925bd58.jpg)
![Damascus Freq](https://user-images.githubusercontent.com/84329357/188567519-5f8d00b1-5d21-46a8-bcf6-bc84d1c4bd70.jpg)

### Save game and other files

[Liberation files.zip](https://github.com/dcs-liberation/dcs_liberation/files/9494153/Liberation.files.zip)

**Comment by DanAlbert** [comment]
https://github.com/dcs-liberation/dcs_liberation/pull/2428 fixes this by auto generating it.

**Comment by Goliathus-21** [comment]
Thank you :-)
