### ISSUE TITLE
Syria (Civil War) Blufor airfields have 0 fuel / liquids

### ISSUE THREAD

**Issue by RampantCoyote** [dcs-liberation/dcs_liberation#242]
Started a new Syria campaign (civil war setup IIRC) as Blufor (modern).  I couldn't figure out why no flights were spawning until I tied a warm start in parking... the airfields (both) were out of all liquids. 0% of 0.

Once I modified the scenario file by hand, things worked normally. Not sure if this is a regular thing, but it occurred for 2 turns in a row (after I 'passed' on a turn trying to figure out the problem).

I'd tried other Syria openings without problem. 

Note: I did create this campaign after loading / running another campaign (I decided to restart a new campaign). Maybe starting a new campaign while another campaign had been loaded is the cause?

**Comment by DanAlbert** [comment]
Most likely caused by the bug where we'd accidentally leave some airfields neutral in the mission. That was fixed recently.
