### ISSUE TITLE
[admin] Add Licensing documentation

### ISSUE THREAD

**Issue by justin-lovell** [dcs-liberation/dcs_liberation#243]
Howdy, this is just an administration task which I can only suggest instead of generate a pull request.

Adding an explicit license has many benefits for everyone, including your users:
* Players who use the DCS Liberation know the warranty and liabilities contributors have to them.
* The main core developers / custodians can set an expectation to other developers regarding trademarks
* Other developers know how their contributions into the main project would be employed.

Most open source projects use MIT or Apache licenses for projects similar to DCS Liberation. I found this site useful in performing a high-level comparison: https://choosealicense.com/licenses/

**Comment by Khopa** [comment]
I usually prefer using MIT license.

However, i just noticed that Shdwp (the original author of the first version of DCS Liberation) put the original version of liberation (liberation 1.5) to LGPL v 3.0 (See https://github.com/shdwp/dcs_liberation/commit/a4703f658df40007037a14ba072db26bccdbd993), even though it was after my fork was done so the license file did not make it here I'd suggest we keep this choice.

Our main dependency pydcs, is also under LGPL-3.0 License.

**Comment by DanAlbert** [comment]
No objections to LGPL. If we were making the choice now I'd also lean toward MIT/Apache/BSD.

**Comment by Khopa** [comment]
@DanAlbert @davidp57 @wrycu @shdwp 
Sorry to bother you guys.. What's your opinion on the subject ?

I personally would prefer to license DCS Liberation under MIT license.
Any objections to that ? Or do you prefer to go for LGPL-3.0, or even another license ?

Thanks.

**Comment by wrycu** [comment]
I'm indifferent - I've had good experiences with both LGPL v3 and MIT.

**Comment by DanAlbert** [comment]
I approve of relicensing as MIT.

**Comment by justin-lovell** [comment]
With pydcs being LGPL, it allows applications like Liberation to choose their own licensing.

The common restriction would be on the original fork because Liberation 2 modifies the original version it most likely needs to retain the LGPLv3 license it originally had. However, there is nothing wrong with a public statement from the original authors that Liberation 2 is licensed to continue their work as MIT (if that is the general concensus)

**Comment by DanAlbert** [comment]
I don't think @Khopa finished chasing down all the contributors for approval. Until then, we should add the LGPL license file to document the current state.

**Comment by MrMinimal** [comment]
I was about to ask what license this project has.

The use of LGPL makes me want to contribute to this even more. Given that Liberation can be considered a whole product, I think its a fitting choice.

For libraries, MIT is a great choice too.

**Comment by DanAlbert** [comment]
> makes me want to contribute to this even more

Drop in to our discord if you want any pointers or want to chat about ideas :)

**Comment by shdwp** [comment]
Since majority of the original code was licensed under LGPL by me you are obliged to keep the license as per its terms. 

The fact that you technically forked the repository prior to the licensing by me only means that at the time being you may not had the rights to do so since in that case code is licensed, based on the country, as "all rights reserved" by default.

**Comment by DanAlbert** [comment]
Sorry, probably wasn't clear enough: we had no intention of relicensing without the approval of every contributor (with permission of every contributor it is possible as I understand it).

We have a no now though, so that settles it. Closing as we do now document the license.

**Comment by shdwp** [comment]
Yeah, I don't have a personal stake in this anymore, that's just how licensing works :)
