### ISSUE TITLE
Frontline hard to click on. Suggest allowing clickthrough of flight path line and widen click zone.

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#2437]
Before filing, please search the issue tracker to see if this feature has already been requested.

If requesting a DCS AI feature, check If reporting a DCS AI bug, check https://github.com/dcs-liberation/dcs_liberation#dcs-bugs.

**Is your feature request related to a problem? Please describe.**
At the moment, the frontline is very difficult to click on, especially if there is already a CAS flight planned over it. This is because you can't click through the flight path line, so you have to be very precise to click on the smalll sliver of orange to either side.

**Describe the solution you'd like**
Would like to be able to click through the flight path line when you right click on it. Ideally, the "mouse click trigger area" should also be a little wider than the orange line, as it's rather tiny especially when zoomed out.

**Comment by DanAlbert** [comment]
> Would like to be able to click through the flight path line when you right click on it.

Hmm. This is working for me.

> Ideally, the "mouse click trigger area" should also be a little wider than the orange line, as it's rather tiny especially when zoomed out.

Do you mean longer, as in a wider front line, or a thicker line? The thickness of the line is constant regardless of the zoom level. The length of the line will eventually be the width of the front itself (and the position will be right too), and extending that hit box is actually quite non-trivial. Making the line thicker is quite easy though.

**Comment by Starfire13** [comment]
I mean thicker. It doesn't have to be visually thicker. It's just that right now, right clicking on the frontline requires multiple tries because more often than not, I get that forward/back/refresh popup instead.

**Comment by DanAlbert** [comment]
Cool, because that's easy. Try https://github.com/dcs-liberation/dcs_liberation/pull/2466.

**Comment by Starfire13** [comment]
Ok, definitely easier. Flightpath lines still cannot be clicked through (see screenshot below where I have clicked on the yellow line), but it is much less of a problem now because the frontline is thicker.

![Screenshot 2022-09-28 232029](https://user-images.githubusercontent.com/72491792/192789294-2c725f12-09c9-4a8e-8843-7b479ccdf438.jpg)

**Comment by DanAlbert** [comment]
Not a lot I can do about the other problem. I can't repro on my end, and the code says it shouldn't be happening :(
