### ISSUE TITLE
Request indication of damaged but still operational SAMs

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#2438]
Before filing, please search the issue tracker to see if this feature has already been requested.

If requesting a DCS AI feature, check If reporting a DCS AI bug, check https://github.com/dcs-liberation/dcs_liberation#dcs-bugs.

**Is your feature request related to a problem? Please describe.**
At the moment, only inoperational or destroyed SAM sites are indicated (yellow bar and red bar, respectively)

**Describe the solution you'd like**
 It would be helpful if partially destroyed but not inoperational SAM sites could be indicated in some manner, particularly for your own SAMs so you can easily tell which ones might require repair.

See https://discord.com/channels/595702951800995872/790195984105734165/1018285529084731443 for conversation on this issue.

**Comment by MetalStormGhost** [comment]
Proposal:
SAMs with all units operational show as "fully capable" (green bar). If units in the theater ground object are destroyed, the green bar is removed. If the SAM site no longer has a threat range, the "rendered ineffective" (yellow) bar is displayed. Operational SAM sites with some units destroyed will therefore not display any bar. Fully destroyed theater group objects display the red bar, as before.

![image](https://user-images.githubusercontent.com/89945461/189522499-7295bc76-3f36-463a-99e2-a53a74834de7.png)
![image](https://user-images.githubusercontent.com/89945461/189522452-04dbedf4-ab85-4398-a0a5-db2a1c94e238.png)
