### ISSUE TITLE
Strike flights don't attack as a group, only attacking first target

### ISSUE THREAD

**Issue by DanAlbert** [dcs-liberation/dcs_liberation#244]
Also only the first aircraft of an formation is dropping its bombs.

_Originally posted by @zelosos in https://github.com/Khopa/dcs_liberation/issues/235#issuecomment-715218025_

**Comment by SnappyComebacks** [comment]
I looked a little bit into this:
Bombing - Group Attack does not behave as described in the documentation.

If there are multiple bombing actions with "group attack" enabled for each structure, then each plane in the flight will drop one bomb on the first bombing action, make another pass and drop a bomb on the second bombing action, another pass and drop a bomb on the third bombing action, and so on.  So if each member of the flight has four bombs then only four bombing actions can be achieved.

If you disable "group attack", then the first element will drop the prescribed number of bombs (currently set to 1) on the first bombing action on the first pass, it will move to the next bombing action and drop the prescribed number on the second bombing action on the second pass, and so forth.  When the first element is out of A/G ordinance (tested with LGB and GBU-31) the next element of the flight will begin it's attack.  The next element will drop bombs on the next bombing action that has not been completed yet.  It will repeat the (set number of bombs) in one pass, until it is out of ordinance as well.  This is repeated until all bombing tasks are completed.  So if 4 elements of a flight each have 2 bombs, they can complete a total of 8 bombing actions.

If what is described above is unclear, you could think of a list of bombing actions like a checklist.  Each pass of ordinance dropped checks an entry on the list, top down.  If "group attack" is enabled, then all planes in the flight will bomb the entry on the list in the same pass as the other planes.  If "group attack" is disabled, then the first element will try to attempt as many passes/entries until it is out of ordinance, and it will be the next planes turn.

Here is a ED forum thread focusing on the "each plane drops a bomb on a different target in the same pass" idea.
https://forums.eagle.ru/topic/243234-no-buggroup-attack-not-assigning-one-target-per-aircraft

Someone in that thread wrote a script that will make the planes drop multiple bombs on different locations, all within one pass here:  https://forums.eagle.ru/topic/243234-no-buggroup-attack-not-assigning-one-target-per-aircraft/?do=findComment&comment=4464124.  The mission has the script within the "Set rules for triggers" page.  Perhaps this could be leveraged?
