### ISSUE TITLE
After taking 2 FOBs on the same supply route, front line units don't transfer

### ISSUE THREAD

**Issue by sandman1330** [dcs-liberation/dcs_liberation#2447]
### Affected versions

Development build

### Development build

#4211

### Description

 I had a very successful mission and managed to take 2 FOBs on the same supply route. They were relatively close together and not well defended so I was able to drive right through one to the other. However, none of my front line units transferred to the new FOB, and therefore aren't available on the front line. They're stuck 2 FOBs back, and therefore 2 turns worth of transfer away. On the other supply route in the mission, I only took one FOB and the units transferred as expected.

### Save game and other files

[iraq.zip](https://github.com/dcs-liberation/dcs_liberation/files/9570905/iraq.zip)

**Comment by Starfire13** [comment]
I think this is a duplicate of #2778. The issue occurs with all control points, not just FOBs.

**Comment by DanAlbert** [comment]
Yep, and that one has a newer save game so it'll be slightly easier to debug.
