### ISSUE TITLE
F-16: pylon 12 issue

### ISSUE THREAD

**Issue by rac3rX-886** [dcs-liberation/dcs_liberation#2449]
### Affected versions

5.2.0

### Description

When trying to launch mission with the takeoff button, an error appears saying the F-16 has no pylon 12. There isn't even a pylon 12 on the jet. The problem persists even with an empty loadout. The only way I could launch the mission is to remove any F-16, entirely.

### Save game and other files

![Screenshot (2)](https://user-images.githubusercontent.com/113927420/191064601-95d8b7e1-f29a-4c25-88f2-ded042ad233c.png)
![Screenshot (1)](https://user-images.githubusercontent.com/113927420/191064624-1a3c8b4f-504b-4c83-aad7-e2c58c5c17f1.png)

**Comment by Starfire13** [comment]
Do you have some F-16 mod like the Sufa installed? F-16Cs work fine for me on 5.2.

**Comment by rac3rX-886** [comment]
No... only mods I have are: 
**Aircraft**
- UH-60
- F15 MTD

**Other**

- Dice CMDS manager

- scratch pad

I'm gonna do a fresh install of the F-16, see if it helps

**Comment by Starfire13** [comment]
There is actually a pylon 12 by the way. It's for acrobatic smoke. Perhaps you have a custom loadout that uses that slot?

**Comment by rac3rX-886** [comment]
Ahh, that was it! You're awesome, thank you so much. Now I could finally enjoy it, haha

**Comment by Starfire13** [comment]
You're welcome.

Closing this as Pylon 12 is already selectable on the dev build, so this issue has already been fixed.
