### ISSUE TITLE
Dev build busted

### ISSUE THREAD

**Issue by mikef-phy** [dcs-liberation/dcs_liberation#2451]
### Affected versions

Development build

### Development build

4211 

### Description

4211 is the last working dev build.

### Save game and other files

[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/9630294/liberation.log)

no state file available

**Comment by DanAlbert** [comment]
No, that campaign is busted :)

Duplicate of https://github.com/dcs-liberation/dcs_liberation/issues/2377

**Comment by mikef-phy** [comment]
ok.  cool.
________________________________
