### ISSUE TITLE
Time acceleration in dedicated server 

### ISSUE THREAD

**Issue by CaptainKoloth554** [dcs-liberation/dcs_liberation#2467]
Hello all,

I always play Liberation SP and I often do so in a dedicated server on the same machine to improve performance. Given real life demands, however, it would be fantastic if I could use time compression in the dedicated server. At present I must choose between better performance in the dedicated server (where time compression is not possible) or chopper without the server but allowing me to use time compression and maybe realistically finish a mission. I'm sure there's lots of complexity on the ED side that probably makes this impossible, but the large contingent of "20 minutes between putting the baby to sleep and going back to work" pilots like myself would appreciate it greatly!

**Comment by DanAlbert** [comment]
We have nothing to do with this. Talk to ED.
