### ISSUE TITLE
can't jump into aircraft with CA

### ISSUE THREAD

**Issue by unixwitch** [dcs-liberation/dcs_liberation#247]
this might be a DCS limitation, or perhaps something i'm misunderstanding, but i expected that with CA i'd be able to jump into any aircraft (like you can with ground units) even when there are no client slots in that flight.  what i'd like to do is, for example, have my client slot start at T+0, fly the mission and rtb as normal, then take control of a later flight after it takes off.

possibly related: giving path or attack orders to AI aircraft doesn't seem to work - i tried instructing an A-10C on a CAS mission to fly towards an enemy unit and then attack it, but it kept flying the CAS pattern and ignored the unit.

**Comment by DanAlbert** [comment]
I don't think that's a feature of combined arms.

**Comment by unixwitch** [comment]
well... i tested with one of the instant action missions (F-16 - Caucasus - Takeoff) and i was able to jump into an A-10A from the F10 view, even though it wasn't configured as a client slot, so it seems like AI flights can be set up like that.  i can't see what's set up differently in that mission to allow it though - there's no obvious checkbox like 'allow player control'.

**Comment by Khopa** [comment]
It usually works for me, but only from the tactical commander slots. I'd have to test it more. 

There is also "player can control vehicle" option, that allow jumping from aircraft to CA vehicle or others aircraft if i'm not misleaded.  I believe we set this one correctly though

**Comment by unixwitch** [comment]
so i fiddled with this a bit more and found it's backwards for me: from the tactical commander slot i can't jump into an aircraft, but if i choose an aircraft client slot, i can.  which is the opposite to how i'd expect it to work, so i guess i was testing from the commander slot before.

i'll close this since it seems to be working - thanks :-)

**Comment by DanAlbert** [comment]
That's cool, I've never figured out how to do that :)
