### ISSUE TITLE
Cannot edit AH-64D properties after assigning BAI tasking v6.0.0-4345-preview

### ISSUE THREAD

**Issue by sevn10** [dcs-liberation/dcs_liberation#2470]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/3207843422

### Description

Whenever allowing Liberation to auto generate BAI tasking for the AH-64D or adding it manually to a package, once created it is no longer possible to edit the parameters of the flight and an error pops up. I could not reproduce this on other aircraft. 

### Save game and other files

![Screenshot 2022-10-08 141039](https://user-images.githubusercontent.com/71986910/194721735-81b211dc-ed2f-43f3-bb43-241300aa2b6d.png)
[baitest.zip](https://github.com/dcs-liberation/dcs_liberation/files/9740037/baitest.zip)
[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/9740045/liberation.log)

**Comment by DanAlbert** [comment]
The data that backs the AH-64 is... bizarre. The data that DCS itself has seems broken tbh. I tried my best to work around it for the latest export but I guess I missed a spot.

**Comment by sevn10** [comment]
I thought it might be that, especially since it seems to happen only to the Apache and with any type of tasking you give it.

**Comment by DanAlbert** [comment]
Apparently DCS implements some ME UI as fake unit properties: https://github.com/pydcs/dcs/issues/266.

**Comment by DanAlbert** [comment]
https://github.com/pydcs/dcs/pull/267 should fix it.
