### ISSUE TITLE
allow players to re-orient SAMs manually

### ISSUE THREAD

**Issue by DanAlbert** [dcs-liberation/dcs_liberation#2479]
Follow up to: https://github.com/dcs-liberation/dcs_liberation/issues/2080

**Comment by Starfire13** [comment]
This does not appear to be working. You can now set the heading, but it won't save. If you click on a SAM again, you'll see it's back to the old heading.

**Comment by DanAlbert** [comment]
Ah, I fixed the control but the control wasn't actually wired to anything yet.
