### ISSUE TITLE
hold points broken in DCS 2.8

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#2494]
### Affected versions

Development build

### Build information

DCS Liberation 6.0.0
Build 4382
Git revision 41fb28ae80271191c3bc20f064faf28a9877ed0e

### Description

All AI flights (blue and red) with a hold waypoint will circle that waypoint indefinitely until they are bingo fuel and then attempt to RTB.

It is a problem specifically with the hold waypoint rather than all waypoint timings in general, as deleting the hold waypoint will allow the flight to proceed (while obviously removing the ability for multi-package flights to form up properly) to its target.

### Save game and other files

[Vectron's Claw Hold Waypoint Test #4382.zip](https://github.com/dcs-liberation/dcs_liberation/files/9894573/Vectron.s.Claw.Hold.Waypoint.Test.4382.zip)

**Comment by SnappyComebacks** [comment]
This happens in `Liberation 5.2` as well.

**Comment by Starfire13** [comment]
> This happens in `Liberation 5.2` as well.

Yeah. This isn't due to a change in Liberation, it's due to a change in DCS 2.8.

**Comment by phntmknight321** [comment]
Chiming in here as well, felt like I was going insane and was wondering if this was just me. Good to know it's something broader and not user error on my part.

**Comment by Mmucha83** [comment]
same here with DCS 2.8 & DCS Liberation 5.2

Deleting the HOLD waypoint helps (ty Starfire13)

**Comment by DanAlbert** [comment]
We know. If you want updates, just click the subscribe button.

**Comment by DanAlbert** [comment]
[reduced.miz](https://github.com/dcs-liberation/dcs_liberation/files/9896887/reduced.miz.txt) has everything except one of the stuck flights (and a bunch of unused trigger zones) deleted and the problem is still present. The stop condition on the hold point is correct in the ME.

**Comment by DanAlbert** [comment]
The "time more" waypoint stop condition appears to be entirely broken in DCS 2.8. [loiter.miz](https://github.com/dcs-liberation/dcs_liberation/files/9896899/loiter.miz.txt) was not generated by Liberation. It has a single aircraft with an "orbit until T+10 minutes" starting waypoint, and the aircraft never stops loitering.

Will file a bug with DCS, but there isn't anything we can do to fix this without completely breaking package grouping. Hold points are the only way flights are able to synchronize with each other.

**Comment by DanAlbert** [comment]
A bug had already been filed. I added a track: https://forum.dcs.world/topic/311458-humvee-ground-unit-holdstop-conditiontime-more-bug-28-mission-editor/

That's the place to go. Upvote that bug.

**Comment by Raffson** [comment]
Here's my 2 cents on the issue, while the stop condition "time is more" is broken, it's not the only stop condition available.
Since this problem affects every version of Liberation out there using DCS 2.8, it's a real game breaker and imo deserves some more attention.
You could work your way around this by creating a "time more" trigger and setting a user flag, then use that flag as the stop condition.

**Comment by DanAlbert** [comment]
The DCS bug was reported today. We're going to give ED some time to respond before we make a painful implementation to work around a DCS bug.

**Comment by Raffson** [comment]
> The DCS bug was reported today. We're going to give ED some time to respond before we make a painful implementation to work around a DCS bug.

Painful? I'm not sure what you're talking about here...
Took me more time to figure out how to work around the bug in DCS itself than to implement it, which is why I'm throwing you this bone.

**Comment by DanAlbert** [comment]
Bizarre that the user flag version of that works but the waypoint action doesn't. Will merge later today.

**Comment by Raffson** [comment]
> Bizarre that the user flag version of that works but the waypoint action doesn't. Will merge later today.

Bizarre indeed! But I'm glad at least that work-around can be used as a backup in the meanwhile. Without holding points Liberation is basically a dud.

**Comment by DanAlbert** [comment]
I'm very wary that hold points are going to be a huge PITA to debug until we can remove the workaround. Have to jump through quite a lot more of the mission to see what the ME believes the depart time is :(

**Comment by DanAlbert** [comment]
@Raffson it sounds like you already have a patch to provide?

**Comment by Raffson** [comment]
@DanAlbert I see you found my secret stash 😁😂
