### ISSUE TITLE
Add Ice Halo weather effect.

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#2496]
There is a new weather effect in DCS 2.8, `Ice Halo`.  It also has presets to choose different Ice Halo forms when not in `Auto` or `None`.

![image](https://user-images.githubusercontent.com/74509817/198864189-c0db4230-56df-43e6-99a5-73dc13933ba2.png)

![image](https://user-images.githubusercontent.com/74509817/198864213-6b63c9b4-ef75-4166-9959-90bdf34d2951.png)

**Comment by DanAlbert** [comment]
We should make sure it's at least set to auto for 6, I assume.

**Comment by SnappyComebacks** [comment]
> We should make sure it's at least set to auto for 6, I assume.

That's what I was thinking too.  I don't know when to pick the others.

**Comment by SnappyComebacks** [comment]
I can probably get the PyDCS side done later today on this.

**Comment by SnappyComebacks** [comment]
A pull request is up for pydcs support here:  https://github.com/pydcs/dcs/pull/272
Once that is merged all we need to do is update the pydcs version here.

**Comment by DanAlbert** [comment]
Merged.

**Comment by SnappyComebacks** [comment]
> Merged.

Thank you.
