### ISSUE TITLE
File not Found Error Erno 2

### ISSUE THREAD

**Issue by Bob556a** [dcs-liberation/dcs_liberation#25]
I am not a coder so followed all the threads and really cannot make sense. 

Installed DCS Liberation and setup preferences per recommendations
DCS is on dedicated SSD      e:\program files\eagle dynamics\DCS World Openbeta

Liberation was setup on my Applications SSD 

Saved games location is at c:\users\Bob\saved games\DCS World Openbeta\Missions

Liberation opens fine
Can create Campaign
Can setup the mission planner
When I go to Fly it all stops and get the error
"FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/Bob/Saved Games/DCS.openbeta/Missions\\Missions\\liberation_nextturn.miz'"

So knowing nothing about python no matter what preferences I setup I still get this error... 

I even created a MIZ file with the Liberation_Nextturn.miz to see if it was an initial file creation message
The saved game files do however get created.
 
Liberation_Save
Liberation_Save_Tmp

Any steps I can take as a pure layman as to how to fix this please.

System is windows 10 64 Bit (Current release and patched)

LOG file attached

[liberation.log](https://github.com/Khopa/dcs_liberation/files/4976974/liberation.log)

**Comment by Khopa** [comment]
Hello, 

I think your "Saved Game" directory  should be "C:/Users/Bob/Saved Games/DCS.openbeta/"  

(Not "C:/Users/Bob/Saved Games/DCS.openbeta/Missions/") 

(You can modify it, in "File/Preferences" menu)

**Comment by Bob556a** [comment]
Ok I solved this,,,, looking at the error file it required under the target directory for saved games another folder called missions.

I created this folder and all seems to be well at this point it  created the file Liberation_Nextturn.miz in a folder called:

c:\users\username\saved games\DCS world Openbeta\Missions\Missions\Liberation_Nextturn.miz, 

The preferences is setup as c:\users\isername\saved games\DCS world Openbeta\Missions 

So all appears to be working now...
