### ISSUE TITLE
BUG: 2.1.5 - Coalition creation

### ISSUE THREAD

**Issue by IdefixRC** [dcs-liberation/dcs_liberation#250]
Hi,

I recently tested 2.1.5 in multiplayer and noticed that the coalition is created with no real countries included.
This resulted in the inability to select plane liveries during rearm&refuel.
Possible to fix this and build the coalition list based on the initial mission setup? Might also be nice to be able to select which countries are included in each coalition (and limit airframe/ground assets) based on that.

Thanks!

**Comment by DanAlbert** [comment]
https://github.com/Khopa/dcs_liberation/issues/106
