### ISSUE TITLE
Mirage F1 missing in 5.2.1 release

### ISSUE THREAD

**Issue by Niphoria** [dcs-liberation/dcs_liberation#2501]
### Affected versions

5.2.0

### Description

The Mirage F1 files seem to be gone in the release download

### Save game and other files

Taking a look at "\Resources\units\aircraft\" in the downloaded zip confirms my suspicion as the files for the mirage f1 are gone

**Comment by Starfire13** [comment]
Mirage F1 is not supported in 5.2.0, so the files are not "gone" in 5.2.1.
