### ISSUE TITLE
F14B ground crew communication malfunction

### ISSUE THREAD

**Issue by Goliathus-21** [dcs-liberation/dcs_liberation#2504]
### Affected versions

5.2.0

### Build information

- DCS version 2.8
- Liberation version 5.2
- Liberation campaign Northern Russia
- ground crew doesn´t respond if asked to turn on the ground power/connect air supply

### Description

Hi guys,

I came across a bug with F-14B playing the Northern Russia campaign. 

I was assign to take off from the Tbilisi-Lochni airport and begin the mission in a cold/dark F14B on the parking lot. I found out, that I can´t contact the ground crew and ask them to turn on the ground power and connect the air supply. I get no response from the crew, even if I´m a doing everything correctly and can hear my "pilot" asking them to connect the power/air. This happened after I updated to the DCS v. 2.8 (I generated the Liberation mission after the update, its not an old mission), it did work from the same airfield in the past missions before the update.

First I thought I´m having some issues with the Vaicom Pro, which broke after the DCS update, but after the community patch I can use Vaicom Pro now. I found out, that even asking for ground power/ air supply via comm menu doesn´t work, so its definitely something else causing the trouble. 

I tested my own missions made in mission editor and DCS training missions, but this bug doesn´t occur with them and ground crew responds correctly. I tried to run a new DCS Liberation campaign and mission from new campaign worked properly as well. 

So something is bugged with that particular "old" Liberation generated mission. Please give it a try and take a look into it someday. I enclose the liberation miz file and saved game.

Thx,

Goliathus

### Save game and other files

[liberation_nextturn.zip](https://github.com/dcs-liberation/dcs_liberation/files/9919464/liberation_nextturn.zip)

**Comment by Starfire13** [comment]
Is your canopy closed?

**Comment by Goliathus-21** [comment]
No, it's opened. Jester will close the canopy only after the external power is connected, but I can't get the crew to connect the ground power. 

This issue is strange, because I do everything the same as anytime before and I have this issue only with this Liberation generated mission and it is 100% reproducible. However it doesn't occur in other missions (created in mission editor). 

Maybe it is a DCS issue, but it's definitely connected to this Liberation mission only.

**Comment by Starfire13** [comment]
Are you using comms or the radio? If the radio, check if the freq is correct in the ME.

**Comment by Goliathus-21** [comment]
I can't use radio without ground power being on. In the F14 Zou can talk to the ground crew without radio if your canopy is open. But this seems bugged only in the Liberation  mission I attached in the original post.

Just to clear it out, I do the very same steps every time when contacting the ground crew and it did work in every other mission I tried. I don't know why...

**Comment by Starfire13** [comment]
Just tried F-14B, both on carrier and at land airfield. No issues contacting ground crew at all.

**Comment by Goliathus-21** [comment]
Ok thx, did you also try the mission attached in my first post? 

Because I can also run any other mission without having this problem.

**Comment by Starfire13** [comment]
If it's a problem with a specific mission file, why not just ditch it? It's probably just bugged. Ultimately, this isn't an issue with Liberation.

**Comment by Goliathus-21** [comment]
I´m OK with that, I just thought it could help. 

It´s not just this mission file, it´s that particular campaign that generates an invalid (?) mission for some reason, so I considered it being a bug. I´m not stubborn and am not insisting that this one particular file must work. So I tried to generate a new mission files with same campaign and had the same bug. That´s the only reason why I reported it. If it doesn´t help at all, no problem, I´m sure there are much more important issues to work on. I ll ditch the whole campaign and restart it, maybe something got corrupted in the files and it won´t occur again.

Thx.

**Comment by Starfire13** [comment]
The reason you can't use comms is because your save file is borked. Tbilisi-Lochini is an enemy base, so how is your F-14 flight taking off from there? Of course the ground crew are not going to respond. I have no idea how you transferred your squadron there. It is not even an option when attempting a squadron transfer. XD

![Screenshot 2022-11-04 221633](https://user-images.githubusercontent.com/72491792/199960178-fbacbeed-b88e-41f1-90a9-d5fbc01164e5.jpg)

**Comment by Goliathus-21** [comment]
Jeez I didn´t notice that at all :-D Yeah I captured Tbilisi-Lochni at least two times and lost it. 

So that´s what went wrong. Funny that my squadron remaind there. It probably went under cover, but got busted after it requested from crew to turn on the ground power and air supply :-P

**Comment by Starfire13** [comment]
If you lose an airfield, your squadron should either retreat to the next friendly airfield along that supply route, or get disbanded. The fact that it remained there might potentially be a bug. I'll test it out and see if I can replicate. It's one of those things I've simply never encountered because I've never managed to lose an airfield before!

**Comment by Starfire13** [comment]
Ok, I used the same campaign (Northern Russia) and let the AI capture Tbilisi-Lochni. My squadron retreated as expected to Kutaisi. So, not sure why that didn't happen on your campaign. But as far as I can tell, the issue is not replicable. Not saying you imagined it, of course. But if it's not replicable, then it can't be fixed. If you encounter it again, let us know.

**Comment by Goliathus-21** [comment]
Great, thank you for your time and help.
