### ISSUE TITLE
F14Tomcat throws error when trying to edit flight in 5.x with new install and new campaign

### ISSUE THREAD

**Issue by marcocom** [dcs-liberation/dcs_liberation#2505]
### Affected versions

5.2.0

### Build information

5.2.1 completely new unzipped install, new campaign. all maps show same issue

### Description

![image](https://user-images.githubusercontent.com/1529972/199558018-084bd0b7-0065-44f0-8142-9bf19c397abe.png)

Cannot edit F14B flights and only get this weapon loadout error.  cannot change it and cannot publish a miz file without choosing an aircraft.

### Save game and other files

[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/9922766/liberation.log)
[marianas.zip](https://github.com/dcs-liberation/dcs_liberation/files/9922773/marianas.zip)

**Comment by DanAlbert** [comment]
Already fixed in 6
