### ISSUE TITLE
Option to disable scud launchers firing 

### ISSUE THREAD

**Issue by Goliathus-21** [dcs-liberation/dcs_liberation#2508]
Is it possible to add option that will prevent scud launchers from firing their missiles?

I found out while I was playing a campaign in the Persian Gulf theatre, that there are plenty of enemy scud launchers and that they fire at the very beginning of the mission all their rockets. It kills the FPS very heavily for me. 

Scud launchers are not very accurate, so usually they don't hit a thing and most of their rockets gets shot down by the SAM defense. This means that there is almost no difference for the mission progress if there are scud launchers or not, but it takes a huge performance hit in the beginning of the mission if they fire their rockets.

In my instance I would prefer to have an option to prevent the scud launchers from firing to get better FPS performance. 

I tried to disable the "artillery fire" in options, but the scud launchers fired no matter what was checked or unchecked.

I can come this around in the mission editor, but it takes a lot of time to modify the mission manually. 

Thx for taking this into consideration. 

Goliathus

**Comment by Starfire13** [comment]
You can remove the scud launcher from the faction.

Go edit the iraq_1991.json and get rid of the "SSM SS-1C Scud-B". You will have to start a new campaign for the change to take effect.

**Comment by Goliathus-21** [comment]
Thx for your advice, I didn´t know about this. That should do the trick for me :-)

Goliathus
