### ISSUE TITLE
Add MB-339 support

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#2511]
The MB-339 was added with DCS 2.8.

- [x] pydcs update
- [x] aircraft yaml
- [x] faction updates
- [x] loadouts
- [x] roles in `ai_flight_planner_db.py`
- [x] radio config
- [x] icon
- [x] banner

**Comment by Starfire13** [comment]
Just to help save some work, I've made up a list (it's a short one) of existing factions that the MB-339 could be added to (meaning they were in use during the time period for that faction). They'd be Italy 1990, US Aggressors, and UAE 2005.

**Comment by DanAlbert** [comment]
All the required stuff is done aside from loadouts. Anyone want to volunteer to make loadouts?

**Comment by DanAlbert** [comment]
@Starfire13 has some here: https://discord.com/channels/595702951800995872/768556702068113449/1038342251560046623

**Comment by DanAlbert** [comment]
Once https://github.com/dcs-liberation/dcs_liberation/pull/2556 merges this is suitably done for 6. I don't actually have this jet yet, but the mission looks right in the ME.
