### ISSUE TITLE
Increased wind speed at elevation

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#2520]
**The feature request:**
Wind speed is generally pretty low in Liberation at altitude.  The wind speed at 26000 ft should probably be increased to an average of about 35 or 40 knots.

**Fluff:**
If anyone has a good model of "this is the distribution of wind velocity at X altitude" please share.

The three (of the four datapoints) that we have control over are 10m/33ft, 2000m/6600ft, and 8000m/26000ft, 

I found a [research paper](https://www.researchgate.net/publication/328173177_SMARTS_Modeling_of_Solar_Spectra_at_Stratospheric_Altitude_and_Influence_on_Performance_of_Selected_III-V_Solar_Cells#pf1) which included a graph of average wind speed vs altitude, but could not find a source on the [figure](https://www.researchgate.net/profile/Moritz-Limpinsel/publication/328173177/figure/fig1/AS:679889808154644@1539109770993/Average-wind-speeds-in-m-s-vs-altitude-in-km-On-an-average-wind-speeds-are-minimum-in.jpg).  I can't find the source of the figure but it's the most complete I've found.

**Other models:**
Wikipedia's [Wind Gradient](https://en.wikipedia.org/wiki/Wind_gradient) contains shear equations but are only valid up to 1000m, depending on context.

[Some random statistical [plot](https://www.centennialofflight.net/essay/Theories_of_Flight/atmosphere/TH1G3.htm) from NASA, no solid credits

Wind Forecast Charts can tell you what the wind is expected to be, these are used globally.  You can get a pretty picture of the current wind at different elevations [here](https://www.windy.com/).

In the USA and Canada we can use  [ _Winds Aloft_](https://en.wikipedia.org/wiki/Winds_aloft) to determine the current weather,  These provide data from 3000 feet to 39000 feet.  [Here ](https://www.aviationweather.gov/windtemp/data?region=slc) is an example (changes every four hours), current the wind in the region at 24000 ft varies between 23 knots and 112 knots.

KiteGen shared some [NOAA images](http://www.kitegen.com/en/technology/wind-data/) showing wind speed at sea level and at 32,800 feet.

(Anecdotal) It does appear that wind speed may be slower at the latitude of the sun.

**Comment by DanAlbert** [comment]
iirc @magwo actually put some research into the current values? He's the one that's done most of the weather stuff either way so I'll just CC him and show myself out :)

**Comment by magwo** [comment]
Yeah wind speeds at altitude were never very well researched I believe. Not by me nor by those who wrote the weather code that I built upon.

Simplest fix would be to increase the multiples that are used for the higher-altitude winds. I think.

**Comment by SnappyComebacks** [comment]
Adjustments to wind were made in #2539
