### ISSUE TITLE
Turbulance based on weather type

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#2521]
**Is your feature request related to a problem? Please describe.**
Presently, turbulence is always set to zero.

**Describe the solution you'd like**
Turbulence is dependent on the weather type (sunny, cloudy, thunderstorm, etc.).
Turbulance is dependent on time of day.  (Highest at Noon)

The Reflected Simulations developer posted a general guide [here](https://forum.dcs.world/topic/278776-m01-channel-extreme-turbulence-and-xwind/?do=findComment&comment=4742099).

Also maybe helpful?
https://forum.dcs.world/topic/282502-preferred-level-of-turbulence/

**Comment by Starfire13** [comment]
Turbulence is also greater in summer and winter.

**Comment by SnappyComebacks** [comment]
First pass completed in #2540
