### ISSUE TITLE
"list.remove(x): x not in list" error

### ISSUE THREAD

**Issue by Rozbiork** [dcs-liberation/dcs_liberation#2525]
### Affected versions

Development build

### Build information

version 5.2.1

### Description

I'm getting this error for any action I do in Liberation. Like buying SAM sites, passing turns and creating flight packages. It's version 5.2.1. I started to see that error after manually submitting with a state.json file.
![image](https://user-images.githubusercontent.com/112295485/201219649-4af03a87-38df-4690-aba7-ed1577ca982d.png)

### Save game and other files

[liberation save.zip](https://github.com/dcs-liberation/dcs_liberation/files/9985037/liberation.save.zip)

**Comment by DanAlbert** [comment]
Fixed in 6 already
