### ISSUE TITLE
Global Time on Target Coordination 

### ISSUE THREAD

**Issue by Steamthrower** [dcs-liberation/dcs_liberation#2532]
Before filing, please search the issue tracker to see if this feature has already been requested.

If requesting a DCS AI feature, check If reporting a DCS AI bug, check https://github.com/dcs-liberation/dcs_liberation#dcs-bugs.

**Is your feature request related to a problem? Please describe.**
I would like if you could set ToT globally. This is because a lot of the time I want a single, mass coordinated strike so my TARCAP flights, SEAD flights and Strike can happen all across the map simultaneously. At the moment, I have to go into every single flight plan and edit the ToT to whatever minutes I want them to be.

**Describe the solution you'd like**
I would like to be able to select flights and change all of their ToT's at the same simultaneously, to reduce workload of changing for every single flight. Maybe even a "Global ToT" or 'H-Hour' timer where all plans will be setup to that time.

**Additional context**
H-Hour could be an option in the settings menu, or more easily a part of the GUI with one of the push buttons at the top left of the Liberation menu. 

![image](https://user-images.githubusercontent.com/86273810/201789740-387527a9-1ec9-40b7-b569-c437132c25c2.png)

**Comment by DanAlbert** [comment]
Why though? The solution described sounds like a band aid for a deeper issue.

**Comment by Steamthrower** [comment]
> Why though? The solution described sounds like a band aid for a deeper issue.

How so? All I request is basically a multi-select TOT changer. I plan a whole lot of flights in my missions, it can get very tedious changing the TOT's (the timer can be a bit finnicky to change also) to the same time over and over again. It would save me a lot of time.

**Comment by DanAlbert** [comment]
I'm asking why you want them to all be simultaneous. Do you just want to ensure that the strike doesn't go in before DEAD is done?

**Comment by Starfire13** [comment]
This seems like a really great way to lose a ton of your planes each turn. In effect, you are forcing your LORAD/MERAD SEAD/DEAD to delay their take off till after your SHORAD/BAI/strike flights are already airborne, and that those SHORAD DEAD/BAI/strike flights arrive over their target while the MERADS/LORADS are just getting engaged. Which means you have already lost a whole bunch of them and are likely to lose even more very shortly.
