### ISSUE TITLE
Disable fast forward button in 6.0 release 

### ISSUE THREAD

**Issue by DanAlbert** [dcs-liberation/dcs_liberation#2535]
This stuff is nowhere near ready, and most UI interactions after the simulation begins will break the game, so we should remove that piece of UI before shipping.

**Comment by Starfire13** [comment]
Does this mean we lose the ability to fast forward to cold start? Or is that still available and we simply can't fast forward manually?

**Comment by DanAlbert** [comment]
Just the manual controls will be gone, because they cause the most fuckery. The "fast forward to first contact" option will be present in 6.

**Comment by DanAlbert** [comment]
(but still very, very much WIP)

**Comment by Starfire13** [comment]
> Just the manual controls will be gone, because they cause the most fuckery. The "fast forward to first contact" option will be present in 6.

Ah that's good. Fast forward to cold start is pretty much all I use it for anyway.

**Comment by DanAlbert** [comment]
Exactly. The rest is just prep work for #1680 (and a debugging tool).
