### ISSUE TITLE
CAP and SEAD flight plans reversed

### ISSUE THREAD

**Issue by davidp57** [dcs-liberation/dcs_liberation#255]
My CAP flight got assigned a SEAD target :
![image](https://user-images.githubusercontent.com/172286/97222424-b0180c80-17ce-11eb-977f-c50554994440.png)

and the SEAD flight for a CAP plan :
![image](https://user-images.githubusercontent.com/172286/97222453-b908de00-17ce-11eb-9a1c-b9b53adda087.png)

Here's the mission file : 

[liberation_nextturn.zip](https://github.com/Khopa/dcs_liberation/files/5441234/liberation_nextturn.zip)

**Comment by davidp57** [comment]
Added the liberation save : 
[0.zip](https://github.com/Khopa/dcs_liberation/files/5441264/0.zip)

**Comment by DanAlbert** [comment]
That's an escort, not a CAP. See https://github.com/Khopa/dcs_liberation/blob/839f163ac5cd77f6b180e0a11ebd66f4358d4714/gen/aircraft.py#L1247-L1272
