### ISSUE TITLE
Air Assault airfield capture is broken again

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#2566]
### Affected versions

Development build

### Build information

DCS Liberation 7.0.0
Build 4486
Git revision 4414853e4536c63a8a08af40aa5df8fc68ede566

### Description

Air assault airfield capture is broken again. Airfield was cleared of all enemy ground units in a 5+ mile radius, and capture didn't work.
![Screenshot 2022-11-22 003332](https://user-images.githubusercontent.com/72491792/203070743-ec71a5cf-dc6b-4283-b806-f8dcb7b5b2be.jpg)

### Save game and other files

Pre and post-mission saves and state.json attached.
[state.zip](https://github.com/dcs-liberation/dcs_liberation/files/10057035/state.zip)

**Comment by RndName** [comment]
We rely on the DCS internal capture event there. Only Fobs are using a custom trigger atm.

@DanAlbert is there any downside of adding a custom trigger zones for "normal" cps like airbases as well? 

`AllOfCoalitionOutsideZone` could maybe not work as intended... currently have no time to check if this would work at all

https://github.com/dcs-liberation/dcs_liberation/blob/ab64655f05c6085cc21f5e45cb0e06aca66365ca/game/missiongenerator/triggergenerator.py#L46-L48

https://github.com/dcs-liberation/dcs_liberation/blob/ab64655f05c6085cc21f5e45cb0e06aca66365ca/game/missiongenerator/triggergenerator.py#L136-L192

**Comment by RndName** [comment]
Hopefully ED did not change that event.

https://github.com/dcs-liberation/dcs_liberation/blob/ab64655f05c6085cc21f5e45cb0e06aca66365ca/resources/plugins/base/dcs_liberation.lua#L163-L166

**Comment by Starfire13** [comment]
I couldn't actually find a capture event in the state.json, but ran out of time to test further as I had to go to bed.

**Comment by RndName** [comment]
> I couldn't actually find a capture event in the state.json, but ran out of time to test further as I had to go to bed.

yeah there is none in the state.json unfortunately. That means that DCS itself did not fire that event `S_EVENT_BASE_CAPTURED` otherwise it would be captured from the liberation lua event listener and added to the state.json.

**Comment by DanAlbert** [comment]
> @DanAlbert is there any downside of adding a custom trigger zones for "normal" cps like airbases as well?

Seems reasonable.

**Comment by Starfire13** [comment]
Just tried moving tanks onto the base and it was captured. But the infantry I landed there earlier didn't cap it. So it looks like a problem purely with the air assault infantry.

**Comment by DanAlbert** [comment]
[infantry capture.zip](https://github.com/dcs-liberation/dcs_liberation/files/10070949/infantry.capture.zip) shows that infantry should have no problem capturing bases in general. I'm not sure how CTLD would break that, so I'm not sure what's going on with the liberation mission.

**Comment by RndName** [comment]
My guess would be dcs unable to recognize the capture because the Troops are spawned within the zone and not entering from the outside.

The capture zone trigger rule works as it should. Ive tried it

**Comment by ColonelAkirNakesh** [comment]
Not sure if this helps but yesterday (11/22) I cleared out all but a T-55 in a zone with the Hind then dropped some troops in it zone, then killed the last T-55 and it worked. If it matters I had to manually load the state.json.
