### ISSUE TITLE
Casaulty report for OPFOR not displaying

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#2567]
### Affected versions

Development build

### Build information

DCS Liberation 7.0.0
Build 4486
Git revision 4414853e4536c63a8a08af40aa5df8fc68ede566

### Description

Casualty report for OPFOR is blank.

![Screenshot 2022-11-22 004023](https://user-images.githubusercontent.com/72491792/203071773-5b3b458d-0658-4919-9b86-8ea2f2a38d65.jpg)

### Save game and other files

Pre and post-mission saves and state.json attached.

[state.zip](https://github.com/dcs-liberation/dcs_liberation/files/10057049/state.zip)

**Comment by RndName** [comment]
Interesting. You can resize that window and it will appear.

![grafik](https://user-images.githubusercontent.com/6678803/203153735-8a90be95-66c9-46a1-871c-eeb5a23b3d75.png)
![grafik](https://user-images.githubusercontent.com/6678803/203153745-c9c9dd1f-f210-4e58-831e-60a796471b40.png)
![grafik](https://user-images.githubusercontent.com/6678803/203153757-af9fd624-82ee-4397-a21a-2af4cd89ec72.png)

**Comment by Starfire13** [comment]
Ha! I guess this happens now because each side's losses only get half the screen real estate it used to. Previously when it was all one big list, it'd display but show up as a highly squished list, rather than not displaying at all.
