### ISSUE TITLE
Add South Atlantic Assets, eg HMS Invincible, Leander-class frigates, etc. to UK faction

### ISSUE THREAD

**Issue by ColonelAkirNakesh** [dcs-liberation/dcs_liberation#2571]
I'd like to add the South Atlantic assets, eg HMS Invincible as a helicopter carrier and Leander-class frigates escorts to the UK faction and Liberation as a whole.

Is there a tutorial on how to add new ships to Liberation someone can link?

**Comment by ColonelAkirNakesh** [comment]
I created .yamls for the Castle and Leander class frigates. The Invincible will need a pydcs update in order to function as a control point. 

... anyone got a link on how a noob submits new YAMLs? They aren't a supported filetype for me to load right here.

**Comment by DanAlbert** [comment]
Are those actually things in the game? I had assumed this was a mod request.

**Comment by Starfire13** [comment]
They were added along with the Falklands map.

**Comment by DanAlbert** [comment]
> ... anyone got a link on how a noob submits new YAMLs? They aren't a supported filetype for me to load right here.

Rename them `.txt`, or just use this button in github in whatever directory you want to add files to: 
![image](https://user-images.githubusercontent.com/315852/204110633-1370cb4f-d2d3-4c0c-a216-ee38d25fe59f.png)

**Comment by ColonelAkirNakesh** [comment]
> Rename them `.txt`, or just use this button in github in whatever directory you want to add files to: ![image](https://user-images.githubusercontent.com/315852/204110633-1370cb4f-d2d3-4c0c-a216-ee38d25fe59f.png)

Thanks Dan, I submitted pull requests for the YAMLs I just created under resources-ships.

**Comment by DanAlbert** [comment]
Most of this is in 6.1 now. Still a bit of work to do though. Looks like we have all the units now, but they still need to be added to the UK faction.

**Comment by DanAlbert** [comment]
I ended up adding those units as part of https://github.com/dcs-liberation/dcs_liberation/pull/2634, since I had to do that to get the invincible working anyway.

**Comment by DanAlbert** [comment]
Done in 7. https://github.com/dcs-liberation/dcs_liberation/pull/2636 cherry-picks the changes to 6.1.
