### ISSUE TITLE
Sunk carrier still has aircraft, AI might be buying more

### ISSUE THREAD

**Issue by DanAlbert** [dcs-liberation/dcs_liberation#2573]
@DanAlbert Ive reviewed & tested the code and it works as expected but there is one issue i found while testing killing enemy carriers:

When you kill an enemy Carrier the Autoplanner is not able to handle it any more. In the screenshot (Marianas campaign) you can see the result after submitting and skipping 2 turns. Seems that the ai is not buying anything else.
![grafik](https://user-images.githubusercontent.com/6678803/203363763-a05d20ac-b5cf-45ce-863f-ca3fe899d2b2.png)

Actually thats not an issue of this PR at all but i just wanted to mention it

_Originally posted by @RndName in https://github.com/dcs-liberation/dcs_liberation/issues/2570#issuecomment-1323913997_
      
@RndName, do you still have the save and state.json for that?

**Comment by RndName** [comment]
I already deleted the one from the screenshot but i recreated it:
[dead_carrier.zip](https://github.com/dcs-liberation/dcs_liberation/files/10079166/dead_carrier.zip)

commit eb997db7038368b06b6b75dcbddd7319ae13a74b

Turn1 AI bought 26 J-15 at the First Shandong. With the State.json that one is killed. Turn 2 that Carrier is dead and with the state "Runway damaged". After pass turn the original issue was that the Planner did not buy any more aircraft at different bases and just did nothing.

But when i now Pass turn (2nd to 3rd Turn) i get this result
![grafik](https://user-images.githubusercontent.com/6678803/203645722-baedb559-e477-4728-a754-79446175f697.png)

which is correct and as it should. So may be that there was something going on as i started that campaign pre-fix and applied that carrier sunk fix during that campaign. a fresh campaign seems to be working fine.

Trying to get the faulty result but atm i cant get it. So it would rather close that one and when we see that issue again we can reopen it?

**Comment by DanAlbert** [comment]
SGTM
