### ISSUE TITLE
Lau-115 - Aim 7P unecpected error will not allow me to acces the loadout/waypoint menu for the f/a-18c hornet 

### ISSUE THREAD

**Issue by MattyMartholomew** [dcs-liberation/dcs_liberation#2575]
### Affected versions

5.2.0

### Description

when trying to get into the menu that lets me edit the load out or the way-points for a given flight, i get an unexpected error cause by the lau 115
![ahhhhhhhhhh](https://user-images.githubusercontent.com/119029767/203907421-dd579ac9-6d2f-44c4-b619-eb411bf74323.png)

### Save game and other files

![ahhhhhhhhhh](https://user-images.githubusercontent.com/119029767/203907450-2f3a4a8f-7183-40be-a1d4-40411707c9e2.png)

**Comment by DanAlbert** [comment]
Duplicate, fixed in 6

**Comment by MattyMartholomew** [comment]
wait what do you mean fixed in 6

**Comment by DanAlbert** [comment]
6.0
