### ISSUE TITLE
was told my issue was "fixed in 6" but then wasnt told what that meant or directed to version 6 or whatever. am i sol until a new drop?

### ISSUE THREAD

**Issue by MattyMartholomew** [dcs-liberation/dcs_liberation#2576]
### Affected versions

5.2.0, Development build

### Description

is there a working version of liberation without the lau issue

### Save game and other files

![ahhhhhhhhhh](https://user-images.githubusercontent.com/119029767/203909273-aeddaec0-3a76-4fdc-9021-2c95c1c0f1d1.png)

**Comment by DanAlbert** [comment]
Info about preview builds is on the front page.

**Comment by DanAlbert** [comment]
(in the future, if you have a question, there's a help channel in discord, and there's a discussion tab on this site for a forum, please keep the bug tracker limited to bugs)
