### ISSUE TITLE
Syria full campaign - Zone east of Ramat David breaks units placement at frontline

### ISSUE THREAD

**Issue by s3-chardonjf** [dcs-liberation/dcs_liberation#258]
![image](https://user-images.githubusercontent.com/29724443/97258156-1bd29780-1818-11eb-932c-4823b82f4fe8.png)

As you can see, there is an exclusion zone on the route to the next enemy airbase.  Round 1 of the Full Syria campaign is ok. But when you reach round 2, the frontline advances right inside the exclusion zone and results in broken locators (bullseye, CAS waypoints, etc) due to the line going through the exclusion zone.

- Load Syria Full
- Win round 1
- Repro at round 2

**Comment by Mustang-25** [comment]
Just want to add that a similar situation happens with the frontline moving east out of Bassel Al Assad.

**Comment by DanAlbert** [comment]
https://github.com/Khopa/dcs_liberation/issues/385
