### ISSUE TITLE
F-15E should be DEAD capable by default

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#2592]
**Is your feature request related to a problem? Please describe.**
The `Air Wing Configurator` doesn't list the F-15E as DEAD capable by default, even though the squadron definitions for the F-15E have DEAD in their possible mission types.  In `ai_flight_planner_db` the F-15E is not listed as DEAD capable.

**Describe the solution you'd like**
Have the F-15E be DEAD capable by default.  I think it just needs to be added to `DEAD_CAPABLE` in `ai_flight_planner_db`?

**Comment by Starfire13** [comment]
But is the F-15E actually DEAD-capable? It can carry 2 mavericks, and has to give up its wing tanks to carry em. The AI F-15E cannot carry JSOWs or SDBs (though they will be available in the coming Razbam module). It has very poor stand-off capability, and is much more of a bomb truck than a wild weasel platform (the US version anyway; which is what we have modelled in DCS). I would not want to waste my F-15Es on DEAD and most likely lose a bunch of them.

**Comment by DanAlbert** [comment]
Standoff isn't a requirement for DEAD. CBUs are a perfectly good DEAD weapon. The SEAD in the package has already made sure that the target is suppressed.

**Comment by SnappyComebacks** [comment]
The F-15E performed DEAD in real life with GBU-10/12s and AGM-130s (and probably dumb bombs and clusters).  They relied on SEAD perform their mission.

Here is a real life example of an F-15E attacking an SA-3 with GBU-12s.

https://www.youtube.com/watch?v=HqvDLzU5DXQ
