### ISSUE TITLE
Battle Line GUI Issue

### ISSUE THREAD

**Issue by MedievalBunny** [dcs-liberation/dcs_liberation#26]
Playing on the Persian Gulf in the invade Iran scenario, the line between Lar and Shiraz is drawn incorrectly. 
![Capture](https://user-images.githubusercontent.com/19675397/88473463-5f4cfb00-cee3-11ea-953d-be458e3f14e0.JPG)

**Comment by Khopa** [comment]
Thanks,

This will be fixed in RC10 : 

![image](https://user-images.githubusercontent.com/2546901/88955437-37231a80-d29c-11ea-9d50-618295ef7c59.png)

**Comment by MedievalBunny** [comment]
Oooo, is that an updated map as well? Looks nice.

**Comment by Khopa** [comment]
Fixed in 2.0.10
Please re-open if you encounter this issue again.
