### ISSUE TITLE
DCS World hang on Graphics init only when using Liberation 6.0

### ISSUE THREAD

**Issue by Dirtywhiteboy317** [dcs-liberation/dcs_liberation#2600]
### Affected versions

6.0.0

### Build information

DCS World 2.7

### Description

Previous version worked fine.  Updated this morning and the program hangs on graphics init 97, no matter which map.

### Save game and other files

[Liberationbugzip.zip](https://github.com/dcs-liberation/dcs_liberation/files/10098441/Liberationbugzip.zip)

**Comment by Starfire13** [comment]
Try repairing your DCS installation.

**Comment by DanAlbert** [comment]
Unfortunately the attached mission works just fine on my machine, which means there's nothing I can do to debug. If repairing your DCS installation doesn't fix the issue, you'll need to file the bug with ED.

**Comment by Starfire13** [comment]
Someone noted in another BR that you're still on 2.7 (which I missed). That's probably the source of your problem. Liberation 6.0 was designed to work with DCS 2.8.
