### ISSUE TITLE
Mission cannot start me_mission.lua error

### ISSUE THREAD

**Issue by Celludriel** [dcs-liberation/dcs_liberation#2603]
### Affected versions

6.0.0

### Build information

DCS Liberation 6.0.0

### Description

From the logs, after switching from 5.2.1 to 6.0.0 I get following error on the first mission of a new campaign.  The mission won't start in DCS and is stuck on the terrain part ?

2022-11-28 22:44:19.963 ERROR_ONCE DX11BACKEND: render target 'cloudShadows' not found
2022-11-28 22:44:19.963 ERROR_ONCE DX11BACKEND: render target 'mainDepthBuffer_copy' not found
2022-11-28 22:44:19.963 ERROR_ONCE DX11BACKEND: render target 'DummyShadowMap' not found
2022-11-28 22:44:20.001 ALERT   LUACOMMON: Error: GUI Error: [string "./MissionEditor/modules/me_mission.lua"]:435: attempt to index field '?' (a nil value)
GUI debug.traceback: stack traceback:
	[C]: ?
	[string "./MissionEditor/modules/me_mission.lua"]:435: in function 'fixCountriesNames'
	[string "./MissionEditor/modules/me_mission.lua"]:1860: in function 'load'
	[string "./MissionEditor/modules/me_openfile.lua"]:674: in function 'func'
	[string "./Scripts/UI/ProgressBarDialog.lua"]:154: in function 'updater'
	[string "./Scripts/UpdateManager.lua"]:64: in function <[string "./Scripts/UpdateManager.lua"]:40>

### Save game and other files

[Missions.zip](https://github.com/dcs-liberation/dcs_liberation/files/10108170/Missions.zip)

I reverted to 5.2.1 and the missions work again

**Comment by Starfire13** [comment]
I would suggest repairing your DCS install. This is unlikely to be a Liberation bug as you are the only person who has reported it.

**Comment by ChocsRus** [comment]
I am experiencing the same issue and I think issue #2600 might be similar to this. I am running a fresh install of DCS 2.7 after a PC rebuild.

Does Liberation 6.0.0 require 2.8 Open Beta?

**Comment by Starfire13** [comment]
6.0 is intended to be used with DCS 2.8

If you don't want to update, stick with 2.5.1.

**Comment by ChocsRus** [comment]
Ah ok, that explains why it doesn't work.

Thanks!

**Comment by Celludriel** [comment]
Yeah it wasn't obvious to me I had to use DCS 2.8.  Then it's not a bug but a misunderstanding
