### ISSUE TITLE
SU-25s tasked to extremely slow ingress waypoints.

### ISSUE THREAD

**Issue by jelkand** [dcs-liberation/dcs_liberation#2604]
### Affected versions

6.0.0

### Build information

DCS Liberation 6.0.0

### Description

On Syria Full Map, Red SU-25s tasked to provide front line CAS are getting waypoint speeds of less than 80 kts. In this case, 21 kts. Expected behavior is a flyable speed.

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/11602317/204695026-179cadb5-ac0a-4c08-9914-165b14f8e162.png">

### Save game and other files

[bugreport-slow-su25.zip](https://github.com/dcs-liberation/dcs_liberation/files/10118902/bugreport-slow-su25.zip)

**Comment by Starfire13** [comment]
User closed issue as Snappy and I clarified on discord that it is not a bug.

**Comment by DanAlbert** [comment]
Thanks for confirming. I figured it was the usual "the ME lies to you" thing with post-hold waypoints, but was thrown off because it was ingress and not join. Forgot that CAS doesn't have those :)
