### ISSUE TITLE
Frontlines on Channel Map extend into the water

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#2612]
### Affected versions

Development build

### Build information

DCS Liberation 7.0.0
Build 4551
Git revision 3863b8ef4097a7c103834a529a5b6792a9b21913

### Description

This bug was first reported on Discord by Revi here: https://discord.com/channels/595702951800995872/595706079459934208/1046461341197664357

Since he hasn't filed it yet, I'll go ahead and do so as I've verified the bug exists.

I had a look at the channel_terrain.miz file in resources\tools\ and it looked fine to me AFAICT.

Map in Liberation
![Screenshot 2022-12-03 083440](https://user-images.githubusercontent.com/72491792/205395201-74d468ec-f210-46ea-8679-324a5c2f39ca.jpg)

Map in mission editor
![Screenshot 2022-12-03 083504](https://user-images.githubusercontent.com/72491792/205395271-0952080d-5631-48be-ae88-b2b5300f8263.jpg)

### Save game and other files

[Dunkirk #4551.zip](https://github.com/dcs-liberation/dcs_liberation/files/10144603/Dunkirk.4551.zip)

**Comment by DanAlbert** [comment]
During channel campaign creation:

```
2022-12-20 12:37:50,163 :: root :: ERROR :: Failed to load landmap resources\theaters\the channel\landmap.p
Traceback (most recent call last):
  File "C:\Users\dan\src\dcs_liberation\game\theater\landmap.py", line 34, in load_landmap
    return pickle.load(f)
_pickle.UnpicklingError: invalid load key, '\x0c'.
```

Checked 5.2.1, and this is a regression.

**Comment by DanAlbert** [comment]
```
(venv) ~\src\dcs_liberation [fix-front-line-extent]> git show --name-status 18f1048dc4226fbbfb532b30dc6c83508ec66f0f
commit 18f1048dc4226fbbfb532b30dc6c83508ec66f0f
Author: Dan Albert <dan@gingerhq.net>
Date:   Wed Sep 7 16:36:12 2022 -0700

    Migrate The Channel to YAML.

M       game/campaignloader/campaign.py
M       game/theater/conflicttheater.py
D       game/theater/seasonalconditions/thechannel.py
A       resources/theaters/the channel/info.yaml
R100    resources/thechannel.gif        resources/theaters/the channel/landmap.p
```

Oops. Bad rename.
