### ISSUE TITLE
Attacks planned against culled targets

### ISSUE THREAD

**Issue by RampantCoyote** [dcs-liberation/dcs_liberation#262]
If the "culling of distant units is enabled" setting is active, Strikes / DEAD / SEAD missions are still generated against the culled targets. There's nothing there when they arrive. While these "fake" missions are not a big deal for AI units, players should not be sent on these missions.

Possible solutions:

#1 - Objects are not culled if they are within range of any player/client start location or objective location. This requires smarter culling passes.

#2 - (Some?) Culled objects are not deleted but instead set inactive, activated by any player/client aircraft entering a zone.

#3 - (Easiest?) Any flight planned attacking a target that would be culled is flagged with a warning. This way the administrator knows not to assign this flight to human players.

**Comment by DanAlbert** [comment]
(more info in https://github.com/Khopa/dcs_liberation/issues/578)
