### ISSUE TITLE
Buildings destroyed in previous missions still appearing when "Include Destroyed Units Carcass" setting is turned off

### ISSUE THREAD

**Issue by RampantCoyote** [dcs-liberation/dcs_liberation#263]
Buildings destroyed in previous missions still appearing when "Include Destroyed Units Carcass" setting is turned off

Expected behavior: Even though a building is not a "unit," the "dead" buildings shouldn't appear when this setting is turned off.

**Comment by DanAlbert** [comment]
Do you mean mission specific buildings, or just the buildings usually present on the map?

If the former, are the buildings spawning in as rubble, or are they alive again?

**Comment by RampantCoyote** [comment]
These are mission-specific buildings - FARP tents, tank farms, tech hangars, etc. Buildings are spawning in as rubble, with the "dead" condition set to true in the Mission Editor.

I do not think this is a high priority, but it seems with this optimization setting, the "dead" structures should not spawn at all.

**Comment by DanAlbert** [comment]
https://github.com/Khopa/dcs_liberation/issues/322 is a dup, but it has the diagnosis so closing this one in favor of that.
