### ISSUE TITLE
code execution fail with liberation 6.0

### ISSUE THREAD

**Issue by HubFly35** [dcs-liberation/dcs_liberation#2642]
### Affected versions

6.0.0

### Description

when trying to run liberation 6.0, I get an system error that reads: 
"iscc.exe - system error
The code execution cannot proceed because ISC.mplr.dll was not found. reinstalling the program may fix this problem"

If I close it and try running it again, I don't get the error....but it endlessly tries to load with no result. 

I can run 5.2 with no errors or problems but 6.0 displays this error and stops. 

### Save game and other files

[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/10251105/liberation.log)

**Comment by DanAlbert** [comment]
Afaik that DLL is not something we produce or depend on. This is most likely an issue with your system that we cannot fix.

**Comment by DanAlbert** [comment]
iscc.exe, afaict, is part of inno setup, which we do not use. We're unable to reproduce this error (we wouldn't have shipped if this was obvious). Without instructions for how to do so, there unfortunately isn't anything we can do here.
