### ISSUE TITLE
Simulation has no unit map Error when ending a turn

### ISSUE THREAD

**Issue by M-Chimiste** [dcs-liberation/dcs_liberation#2643]
### Affected versions

6.0.0

### Build information

DCS Liberation 6.0.0

### Description

When using a standalone server and ending a turn I get "Simulation has no unit map.  Results processing began before a mission was generated.  This seems to happen for just about every mission I try to complete.  Even when trying to upload the state.json manually I receive this error.

Campaign: "The Falcon went over the mountain"

### Save game and other files

[Falcon Over The Mountain 1.zip](https://github.com/dcs-liberation/dcs_liberation/files/10252878/Falcon.Over.The.Mountain.1.zip)
[state.zip](https://github.com/dcs-liberation/dcs_liberation/files/10252879/state.zip)
![Screenshot 2022-12-17 175650](https://user-images.githubusercontent.com/37678080/208268998-6856c2e0-1315-4c2e-a626-1f26afaa81a4.png)

**Comment by DanAlbert** [comment]
What's your workflow?

**Comment by M-Chimiste** [comment]
Nothing fancy. Set up the mission in liberation then generate mission. Once mission is generated I start the server and launch DCS to join. Once I complete the mission I leave server and stop the server. Normally it ends without issue and recognizes the end of the mission. Historically with 5.2.x never saw any issues. This seems new after upgrading to 6.x.

**Comment by M-Chimiste** [comment]
I'm not familiar with a lot of the DCS related development but I do python development for a day job, if you have any suggestions on where to look to better understand this error I'm happy to help troubleshoot collaboratively.

**Comment by DanAlbert** [comment]
> Set up the mission in liberation then generate mission. Once mission is generated I start the server

Is all that happening on the same machine? Not sure if it would matter. Haven't had a chance to try your repro case yet but this error is one of those "the world doesn't make sense any more" assertions, so I'm looking for anything out of the ordinary.

> if you have any suggestions on where to look to better understand this error I'm happy to help troubleshoot collaboratively.

I'll do this myself when I find the time to try your repro case (probably in the next few days), but if you want to beat me to it, you should be able to step through with the debugger if you run from source (https://github.com/dcs-liberation/dcs_liberation/wiki/Developer's-Guide, if it helps).

Just poking around a bit, I don't see any obvious way this could happen. There doesn't appear to be any way to submit mission results that doesn't first generate and store that unit map, and the unit map will never be cleared (there's a `finish()` method that would clear it, but it's dead code, it seems).

**Comment by M-Chimiste** [comment]
So I'm in the process of looking at the track file and tacview.  One thing I did notice at mission start is that they waypoints in the hornet for the target SAM site I was trying to strike, don't align from the HSI data page to the JDAM when using TOO.  I did originally try to use Preplanned mode and got an error trying to transcribe the longitude.  Another thing when looking at the state file, it looks like it's the incorrect one, probably due to me trying to manually save after the initial error.  I'm going to run the track to completion to generate a new state.json and put it off to the side.

Example of waypoint miss match.
![Screenshot 2022-12-18 145906](https://user-images.githubusercontent.com/37678080/208316766-4660711d-bb38-4792-a3b6-252499fc6afa.png)

**Comment by DanAlbert** [comment]
I can't reproduce the issue in the OP. I downloaded the save, advanced to turn 1 (the attached save was on turn 0, so definitely isn't what you submitted the results for, so I haven't done exactly what you did), hit "take off", manually submitted the attached results. No issues.

Has the problem recurred, or was it a one time thing? I'm around to help you debug if you're able to repro, but I'm going to close this for now as I can't repro and afaict this is impossible, so there isn't anything we're able to do here :(

**Comment by M-Chimiste** [comment]
Let's keep it closed.  I've restarted the campaign and it seems fine so far.  Granted, I've got other issues I'm seeing (e.g. aircraft flying underground).  Though I'm going to count those and this as an ED problem for now.  I've also reinstalled the server and my base DCS in case something somehow was corrupted.  Will let you know.

**Comment by DanAlbert** [comment]
> Though I'm going to count those and this as an ED problem for now.

If they're underground in the ME, it's our fault, and worth filing. If they do it willingly after spawning above ground, that's probably ED :)
