### ISSUE TITLE
A10c ingame instead of A10c II 

### ISSUE THREAD

**Issue by Mmucha83** [dcs-liberation/dcs_liberation#2646]
### Affected versions

6.0.0

### Build information

DCS Liberation 6.0.0

### Description

Startet new campaign (persian gulf - scenic route 2 - dust to dust).
In the DCS liberation GUI i can add A-10c Thunderbolts II/2 for a sortie (me as a player and wingman), ingame all the planes are A10c (not C2). 
Same bug/error appears sometimes also in other DCS-L campaigns when the A10C2-pack is bigger then 8. GUI is always correct, in-game not.

### Save game and other files

[NATOvsIran1988.zip](https://github.com/dcs-liberation/dcs_liberation/files/10259190/NATOvsIran1988.zip)
[liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/10259199/liberation.zip)
![DCS-L6-wrong-ingame-a10](https://user-images.githubusercontent.com/96792758/208442974-54aa1de8-e275-497f-8790-b3626a391fca.PNG)
![DCS-L6-wrong-ingame-a10-briefing](https://user-images.githubusercontent.com/96792758/208447998-958a3175-09eb-426e-adfd-d02bd7e1f9a7.PNG)
![DCS-L6-wrong-ingame-a10-screenshot](https://user-images.githubusercontent.com/96792758/208444240-795147c8-fb2e-4990-9658-364b04a8063a.PNG)

**Comment by Starfire13** [comment]
You are in the Suite 3. The A-10C 2 is the Suite 7. It's called the "Thunderbolt II" because that's the name of the actual plane. The Thunderbolt I is from WW2.
