### ISSUE TITLE
"list index out of range"

### ISSUE THREAD

**Issue by Rozbiork** [dcs-liberation/dcs_liberation#2647]
### Affected versions

6.0.0

### Build information

DCS Liberation 6.0.0

### Description

I get this error when I click on take-off.
![liberation error](https://user-images.githubusercontent.com/112295485/208481794-e17cf511-1cbc-4876-b6d0-72af6f5d358a.png)

### Save game and other files

[liberation save.zip](https://github.com/dcs-liberation/dcs_liberation/files/10261316/liberation.save.zip)

**Comment by DanAlbert** [comment]
This is the old empty convoy problem. There's an opfor convoy that for some reason has a record of 0 units of BMP-3s. The bug has already happened in this save though. I need the save from the turn before so I can apply the state.json and debug that process. I can't do that with the information given, and we've been all over this code in previous releases trying to spot the issue without any luck. If someone can provide a save from the turn _before_ this happens and the state.json that'll break the save, please file that bug. Until then, there's nothing we can do.

One thing I am going to do that should make it easier to file those bugs though is make Liberation preserve the previous turn's save before applying the state.json to `last_turn.liberation`: https://github.com/dcs-liberation/dcs_liberation/pull/2656. If you see a new instance of this bug in 6.1, you'll have the data you need to file a bug report we can act on, so please do!
