### ISSUE TITLE
Blackshark 3 support

### ISSUE THREAD

**Issue by DanAlbert** [dcs-liberation/dcs_liberation#2657]
- [x] pydcs update
- [x] aircraft yaml
- [x] faction updates
- [x] loadouts
- [x] roles in `ai_flight_planner_db.py`
- [x] radio config
- [x] icon
- [x] banner

**Comment by DanAlbert** [comment]
@Starfire13 do you have loadouts already? You usually do :)

**Comment by DanAlbert** [comment]
I'm not familiar with the old or new blackshark. How significantly has it changed from the old version?

Is there a useful naming distinction in the UI like we have for the two A-10s? ("Suite 3" and "Suite 7"), or is this purely a gameplay update and I don't have an "in lore" name option and should just mark them "Blackshark 2" and "Blackshark 3"?

Does it use the same radios? (I'll go digging through the manual later if needed)

**Comment by Starfire13** [comment]
> @Starfire13 do you have loadouts already? You usually do :)

Not yet, but I'm happy to whip something up. I might be able to squeeze in time to do it tonight. If not, will have to wait till Friday.

**Comment by DanAlbert** [comment]
No rush.

**Comment by Starfire13** [comment]
Loadout file attached.

[Ka-50_3.zip](https://github.com/dcs-liberation/dcs_liberation/files/10276896/Ka-50_3.zip)
