### ISSUE TITLE
auto TOT planning wrong for TARCAP and CAS

### ISSUE THREAD

**Issue by DanAlbert** [dcs-liberation/dcs_liberation#267]
"Set earliest TOT" with CAS results in a start time greater than zero. For TARCAP, less than zero.

**Comment by walterroach** [comment]
Noticed other strangeness with TOT today while reworking the briefinggen.  Departure is always 0 in the briefing even if flight is late activated.  Something to do with when (if?) we're setting the departure_delay value on the flight.

**Comment by DanAlbert** [comment]
Fixed by https://github.com/Khopa/dcs_liberation/commit/88b9ed29ba1efda3dee7b1c43ae36b22c93f1c26
