### ISSUE TITLE
can't plan missions against base air defenses

### ISSUE THREAD

**Issue by DanAlbert** [dcs-liberation/dcs_liberation#268]
This was doable previously, but since they don't exist on the map they're not currently selectable package targets.

**Comment by walterroach** [comment]
I have an idea for this I'm playing with.  Basically clicking "new package" on red airbase will trigger a dialog similar to the base defense manager for the user to select the target group.

**Comment by DanAlbert** [comment]
My plan was to just add multiple "New package" entries to the context menu. Either works. Heads up, I'm working on refactoring a lot of the theater code atm to clean up some of the oddities.
