### ISSUE TITLE
Add support for CJS’ “SuperBug” unofficial mod(s)

### ISSUE THREAD

**Issue by sgtfuzzle17** [dcs-liberation/dcs_liberation#2681]
* Mod name: CJS SuperBug
* Mod URL: https://discord.gg/UajyuXtQzb
* Update or new mod? This is a new mod as far as Liberation is concerned.
* Notes: this mod works by replacing the existing official F/A-18C with a generic Super Hornet model, which then is split into E and F models, as well as a G model Growler. I *think* the best way to handle implementation would be to set up the E and F model to use the same loadouts as suitable, and then users can select the corresponding squadron to get E or F with squadron liveries, then have the G as a different “aircraft” such that it can have different loadouts (wingtip EWAR, ALQ pods etc.). Tag or DM Fuzzle in the Liberation Discord if you need an extra set of hands to set up squadron files as I’d love to help out.

**Comment by amn2be** [comment]
As someone who flies the bug solely with our crew this is going to be a big deal thank you.

**Comment by Mmucha83** [comment]
any progress with adding the SuperBug mod? Thanks in advance

**Comment by zhexu14** [comment]
Closing as this mod support was introduced in Release 11.
