### ISSUE TITLE
Multiple error dialogs on startup

### ISSUE THREAD

**Issue by loopium** [dcs-liberation/dcs_liberation#2688]
### Affected versions

Development build

### Build information

build 4671, 4673

### Description

1

unsupported format string passed to datetime.timedelta.__format__

Traceback (most recent call last):
  File "qt_ui\delegates.py", line 113, in sizeHint
  File "qt_ui\widgets\ato.py", line 255, in text_for
TypeError: unsupported format string passed to datetime.timedelta.__format__

x 20  times (OK)

### Save game and other files

[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/10349272/liberation.log)

**Comment by loopium** [comment]
Running on a Windows 11 Pro VM on Manjaro/VMware host. English language, tried setting region to English as well without any change

**Comment by DanAlbert** [comment]
Can't repro
