### ISSUE TITLE
AttributeError: module 'game.persistence' has no attribute 'mission_path_for'

### ISSUE THREAD

**Issue by Nosajthedevil** [dcs-liberation/dcs_liberation#2699]
### Affected versions

Development build

### Build information

Build 4687 -

https://github.com/dcs-liberation/dcs_liberation/actions/runs/3935218354

This occurs in both my local development environment and in a separate stand-alone instance of build 4687.

### Description

When beginning a new campaign on first turn, selecting the take off for the first time gives the following error -

module 'game.persistence' has no attribute 'mission_path_for'

Traceback (most recent call last):
  File "C:\Users\Jason\Documents\GitHub\dcs_liberation\qt_ui\widgets\QTopPanel.py", line 293, in launch_mission
    persistence.mission_path_for("liberation_nextturn.miz")
AttributeError: module 'game.persistence' has no attribute 'mission_path_for'

### Save game and other files

[Help.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/10521389/Help.liberation.zip)

[autosave.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/10521393/autosave.liberation.zip)

[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/10521396/liberation.log)

**Comment by DanAlbert** [comment]
Whoops. https://github.com/dcs-liberation/dcs_liberation/pull/2700 fixes it. Sorry about that!
