### ISSUE TITLE
Carrier Group Running Aground 

### ISSUE THREAD

**Issue by MedievalBunny** [dcs-liberation/dcs_liberation#27]
Playing in Persian Gulf in the invade Iran scenario, the carrier group ran into Larak Island. 
![Screen_200726_003332](https://user-images.githubusercontent.com/19675397/88473485-9f13e280-cee3-11ea-8b8f-78e3727a2a29.png)

**Comment by Raider1-1-Boo** [comment]
You might be able to adjust the waypoints in the Mission Editor before you fly. If that works, not sure if you would have to do that before each mission.

**Comment by Mustang-25** [comment]
carrier locations are moveable in the Liberation map. Closing this one out.
