### ISSUE TITLE
KS-19 not generated in .miz output

### ISSUE THREAD

**Issue by clutchtomcat** [dcs-liberation/dcs_liberation#2701]
### Affected versions

6.0.0

### Build information

DCS Liberation 6.0.0

### Description

Using a modified North Korea 1950s faction replacing the WW2 flak with KS-19 (among other edits). 

Initially KS-19 would not generate because the file in the unit resources is notated "null," so I replaced "null" with { } to match other unit resources. 

KS-19 is now generating in the Liberation software, but in the output .miz file they are not generated. Checking all of the AAA groups, they consist of a single unit: the logistics vehicle.

If I replace the KS-19 with another unit like the 88s or S-60s, they generate as advertised in the .miz file.

Attaching faction file, Liberation save file, and exported .miz file.

Issue with my .yaml edits or issue with Liberation?

### Save game and other files

[KS-19.zip](https://github.com/dcs-liberation/dcs_liberation/files/10525562/KS-19.zip)

**Comment by DanAlbert** [comment]
> Issue with my .yaml edits or issue with Liberation?

If they're showing up in Liberation but not the miz, most likely Liberation. It could be a country mismatch though. If the unit is being generated correctly but the faction is using a country that can't use that vehicle, DCS will replace the unit with something else (iirc).

**Comment by clutchtomcat** [comment]
Just checking for a country mismatch now. KS-19 is available for CJTF Red, and the faction is using CJTF Red. 

I've had country mismatches with factions like the Korean War DPRK, but instead of replacing the unit, the unit (WW2 asset in this case) is generated properly with the Mission Editor drop-down selections/unit type/etc. being all messed up.

**Comment by DanAlbert** [comment]
CJTF anything should be able to spawn anything, so yeah, that won't be it. (And yeah, I may not remember the mismatch behavior right, it's been a while)

**Comment by DanAlbert** [comment]
Apparently the KS-19 has just never worked? The unit ID for the KS-19 is `KS-19`, not `KS19`. I'm waiting for DCS to update so I can test it, but https://github.com/dcs-liberation/dcs_liberation/pull/2703 should fix the problem (you should be able to make that change locally in your 6.1.0 install if you don't want to wait for 6.1.1, btw).

**Comment by clutchtomcat** [comment]
So just rename KS19.yaml to KS-19.yaml?

**Comment by DanAlbert** [comment]
Yep
