### ISSUE TITLE
SHORADS for more locations

### ISSUE THREAD

**Issue by DanAlbert** [dcs-liberation/dcs_liberation#271]
Add some SHORADS to the front lines to make CAS more interesting.

**Comment by Mustang-25** [comment]
I'd also like to suggest doing something similar with infrastructure/logistics targets. Conceptually, I'd think that important installations would have some MANPADS/SHORAD/AAA on-site.

**Comment by DanAlbert** [comment]
Agreed. Updated the title.

**Comment by Khopa** [comment]
https://github.com/Khopa/dcs_liberation/commit/37e23f70d6d9c08cf499f61f6f8714c3a00d4a08
Some factions will now sometimes spawn manpads in their infantry squads on the frontline.

**Comment by DanAlbert** [comment]
Campaign designers can do this now.
