### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by redtop012000** [dcs-liberation/dcs_liberation#2710]
### Affected versions

Development build

### Build information

Was 6.1.0 Build 4632 when issue occurred, latest build tried to see if issue disappeared now:-
DCS Liberation 6.1.1
Build 4702
Git revision 938d6b4bdf9c29a1bab128868e8f1c2eed318e32

list index out of range

Traceback (most recent call last):
  File "qt_ui\widgets\QTopPanel.py", line 288, in launch_mission
  File "qt_ui\simcontroller.py", line 76, in generate_miz
  File "game\sim\gameloop.py", line 67, in pause_and_generate_miz
  File "game\sim\missionsimulation.py", line 51, in generate_miz
  File "game\missiongenerator\missiongenerator.py", line 107, in generate_miz
  File "game\missiongenerator\missiongenerator.py", line 255, in generate_air_units
  File "game\missiongenerator\aircraft\aircraftgenerator.py", line 110, in generate_flights
  File "game\missiongenerator\aircraft\aircraftgenerator.py", line 181, in create_and_configure_flight
  File "game\missiongenerator\aircraft\flightgroupconfigurator.py", line 78, in configure
  File "game\theater\controlpoint.py", line 1138, in active_runway
  File "game\runways.py", line 113, in get_preferred_runway
IndexError: list index out of range
[Saves.zip](https://github.com/dcs-liberation/dcs_liberation/files/10534907/Saves.zip)

### Description

At turn 7 the front line was too close so I advanced front line at both FOB. Added extra ground units.  Pass Turn then on clicking take off got the error "list index out of range"

Our squadron SHREK has had faultless Liberation 5.0 through to 6.1.0 (currently testing 7.0) experience (any glitches we had were down to user error).   The "list index out of range" has stopped us in out TRACKS :)
[Saves.zip](https://github.com/dcs-liberation/dcs_liberation/files/10535022/Saves.zip)

### Save game and other files

At turn 7 the front line was too close so I advanced front line at both FOB. Added extra ground units.  Pass Turn then on clicking take off got the error "list index out of range"

Our squadron SHREK has had faultless Liberation 5.0 through to 6.1.0 (currently testing 7.0) experience (any glitches we had were down to user error).   The "list index out of range" has stopped us in out TRACKS :)
[Saves.zip](https://github.com/dcs-liberation/dcs_liberation/files/10535022/Saves.zip)

**Comment by redtop012000** [comment]
I kept trying different scenarios and undid changes such as switch off smoke etc.
I "cheat captured" FOB Qalea > pass turn > same issue.  I cheat captured FOB Dhirae the issue was resolved, narrowing the investigation at this point.  Pass Turn again was possible only when adding each Ground Forces HQ vehicle at 0 or 1 but anything above 1 caused the "list index out of range".  After successfully carrying out "pass turn" to get a "take off" with no error the next "pass turn" with any entry including 0 or 1 in Ground Force HQ caused "list index out of range".

**Comment by DanAlbert** [comment]
At Tanf has no runways, but is an airfield. No idea why, but that's the cause of the problem. Liberation assumes that airfields have at least runway, because duh, but for some reason this one does not? I'm still digging.

**Comment by DanAlbert** [comment]
It's a heliport rather than a real airfield. I guess no one has ever tried using one of those until now, and we don't handle them correctly?

**Comment by DanAlbert** [comment]
Yeah, any use of heliports will break the game. I was able to get myself back into this situation by creating a new game on Tripoint Hostility, ensuring that I had a helicopter squadron, cheating my way to At Tanf, and moving a helicopter squadron there. If the helicopter squadron uses At Tanf as an arrival, departure, or divert field, the mission will not generate. Shouldn't be hard to fix.

**Comment by redtop012000** [comment]
If I hit save as  rename then restart Liberation I could then hit fly without the error occuring.  We have managed to complete the Campaign using this method.  Massive thanks to your efforts because it keeps a group of 12 of us very happy.
