### ISSUE TITLE
Recovery Tanking on/off toggle

### ISSUE THREAD

**Issue by marcantonio152** [dcs-liberation/dcs_liberation#2716]
With a tanker in the air, ALL of my aircraft automatically line up for the tanker regardless if there will be enough gas for them or not.... If I have 25 aircraft airborne and one single S-3 tanker in the air, I end up with 25 aircraft in line to do a recovery tanking, only a few of them get gas, and then all 25 of them try to join the stack to land on the boat. This leads to very long lines to land.

Respectfully requesting a feature to tell individual packages to go to the recovery tanker or not. A toggle switch or checkbox for the sortie for "recovery tanker before landing" would be nice.

Currently I am having to go to the Mission Editor and delete the "refuel" waypoint for all aircraft that I do not want to send to the recovery tanker.

**Comment by DanAlbert** [comment]
Uh, I think this might actually be a DCS bug. I don't think we tell any AI aircraft to refuel at the recovery tanker. They all have a refueling waypoint that's intended for them to use the package's tanker (if one is present). My guess is that the DCS task is not specific enough to specify which tanker they should use? I don't know if this is fixable.

**Comment by DanAlbert** [comment]
(not creating that task for packages that do not have a tanker would be a partial fix, but they will still be broken whenever the package's tanker does not have enough fuel for the whole package)

**Comment by DanAlbert** [comment]
I think this is really a bug. Every AI flight is getting a refueling task regardless of whether or not the package has a tanker, so every AI flight is just flying to an arbitrary (presumably the closest) tanker after leaving the combat area.
