### ISSUE TITLE
"Attempted to simulate flight that is not fully initialized" after aborting and adding new flights (not supported, but UI won't stop you)

### ISSUE THREAD

**Issue by Nosajthedevil** [dcs-liberation/dcs_liberation#2735]
### Affected versions

Development build

### Build information

Build #4746

### Description

In the development build if I delete all of the pre-generated packages and create my own packages, .miz generation (clicking the takeoff button) often fails with an "Attempted to simulate flight that is not fully initialized" error. If I save the campaign (even after the error) and then reopen it the problem goes away and I can run the mission for that turn - so there is a workaround. This has occured with campaigns on both the Marianas and Syria maps. Full error window text pasted below.

Attempted to simulate flight that is not fully initialized

Traceback (most recent call last):
  File "C:\Users\Jason\Documents\GitHub\dcs_liberation\qt_ui\widgets\QTopPanel.py", line 292, in launch_mission
    self.sim_controller.generate_miz(
  File "C:\Users\Jason\Documents\GitHub\dcs_liberation\qt_ui\simcontroller.py", line 90, in generate_miz
    self.game_loop.pause_and_generate_miz(output)
  File "C:\Users\Jason\Documents\GitHub\dcs_liberation\game\sim\gameloop.py", line 73, in pause_and_generate_miz
    self.sim.generate_miz(output)
  File "C:\Users\Jason\Documents\GitHub\dcs_liberation\game\sim\missionsimulation.py", line 50, in generate_miz
    self.unit_map = MissionGenerator(self.game, self.time).generate_miz(output)
  File "C:\Users\Jason\Documents\GitHub\dcs_liberation\game\missiongenerator\missiongenerator.py", line 107, in generate_miz
    self.generate_air_units(tgo_generator)
  File "C:\Users\Jason\Documents\GitHub\dcs_liberation\game\missiongenerator\missiongenerator.py", line 250, in generate_air_units
    aircraft_generator.generate_flights(
  File "C:\Users\Jason\Documents\GitHub\dcs_liberation\game\missiongenerator\aircraft\aircraftgenerator.py", line 111, in generate_flights
    group = self.create_and_configure_flight(
  File "C:\Users\Jason\Documents\GitHub\dcs_liberation\game\missiongenerator\aircraft\aircraftgenerator.py", line 167, in create_and_configure_flight
    ).create_flight_group()
  File "C:\Users\Jason\Documents\GitHub\dcs_liberation\game\missiongenerator\aircraft\flightgroupspawner.py", line 77, in create_flight_group
    return self.generate_flight_at_departure()
  File "C:\Users\Jason\Documents\GitHub\dcs_liberation\game\missiongenerator\aircraft\flightgroupspawner.py", line 99, in generate_flight_at_departure
    if self.start_type is StartType.IN_FLIGHT:
  File "C:\Users\Jason\Documents\GitHub\dcs_liberation\game\missiongenerator\aircraft\flightgroupspawner.py", line 93, in start_type
    return self.flight.state.spawn_type
  File "C:\Users\Jason\Documents\GitHub\dcs_liberation\game\ato\flightstate\uninitialized.py", line 35, in spawn_type
    raise RuntimeError("Attempted to simulate flight that is not fully initialized")
RuntimeError: Attempted to simulate flight that is not fully initialized

### Save game and other files

[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/10725648/liberation.log)
[Test 7 Develop Fail.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/10725653/Test.7.Develop.Fail.liberation.zip)

**Comment by Nosajthedevil** [comment]
It appears that after the first turn the issue goes away.

**Comment by DanAlbert** [comment]
@Nosajthedevil have you seen this again, or was it just the one time? If just once I'd like to move this to 8 so we can get the apache fix out faster.

**Comment by Starfire13** [comment]
My belief is this is due to hitting take off and then aborting rather than simply deleting auto-planned packages (which I have tested multiple times without encountering errors).

**Comment by Nosajthedevil** [comment]
It's still occurring. For example, I just pulled up my development build (I'm on 4911)- deleted the auto-planned packages, set up a few planned packages, and hit take off. I then aborted and added a strike package. When I hit take off again, I get the same "RuntimeError: Attempted to simulate flight that is not fully initialized". There's a simple workaround though, I just save the campaign and reload it, everything works fine.

**Comment by DanAlbert** [comment]
> set up a few planned packages, and hit take off. I then aborted and added a strike package. 

Ah, that old thing. Yeah, this is known broken and not new. I can't remember if we have a bug for this or not (strictly speaking it isn't a _bug_, the UI just won't stop you from doing it). I did actually want to try building in a reset, but with the new urgency of 7 I don't think that's going to happen yet.

Still, I'll repurpose this because I don't think we have anything tracking that.

**Comment by Starfire13** [comment]
> and hit take off. I then aborted and added a strike package.

Yeah, don't do that. Once you hit take off, you are past the planning phase. As you said, reload your save.

**Comment by DanAlbert** [comment]
Given how non-obvious this is to... everyone, I took a shot at adding a reset on abort: https://github.com/dcs-liberation/dcs_liberation/pull/2888. The option is off by default because quite frankly I'm surprised it works. @Starfire13 if you play with that on for a while and don't see any issues, lmk and I'll make it the default for 7.

Sooner or later that's going to have to go away because it's going to become less and less possible to keep it working as the RTS features get added (it will definitely never work with any sort of auto resolve), but since there's very little data (again, aside from auto resolve) right now and I don't plan on making a ton of progress on the stuff that'll break it any time soon, it's worthwhile in the short term (though I'm already not looking forward to dealing with the backlash when this eventually needs to be removed)

**Comment by Starfire13** [comment]
I'm concerned this is going to add further confusion in the long run.

1. It is off by default so lots of folks aren't going to even know it's there. And they'll therefore still encounter the problem and file a bug, or more likely, ask about it on discord.

2. The ones that do notice the new option and use it are going to be surprised when it either stops working at some point or is removed.

Would it be better to either:

1. Create a save when take off is clicked and auto load that after abort is clicked

2. Have a message box pop up after clicking abort with an "ok" button and a message saying "You will have to reload your last save before planning packages after aborting".

**Comment by DanAlbert** [comment]
If it were on by default, would you think otherwise? I think I actually also prefer not doing this because reason 2, but I had (wrongly) thought it would be the preferred outcome.

> Create a save when take off is clicked and auto load that after abort is clicked

First part is trivial. Second part might make the UI behave oddly, but I can try and find out.

> Have a message box pop up after clicking abort with an "ok" button and a message saying "You will have to reload your last save before planning packages after aborting".

Very easy.

**Comment by Starfire13** [comment]
Default on is better but still not ideal, I think. I feel that the message box is good enough. Unless the autosave and autoload thing is relatively easy to implement, the message box gets my vote.

**Comment by DanAlbert** [comment]
Works for me. Thanks for the feedback.

**Comment by DanAlbert** [comment]
Option 1 seems to Just Work? I find that pretty surprising, but it appears to. I've hacked it together atm but I'll build it properly and upload that soonish.
