### ISSUE TITLE
ATO uses first squadron for objective, causing mission generation to not utilize all aircraft

### ISSUE THREAD

**Issue by Lordeath19** [dcs-liberation/dcs_liberation#2736]
### Affected versions

6.1.1, Development build

### Description

There is an issue with the way mission generation and `best_squadrons_for` exchange information.

For example:
I have 3 enemy SA-10s, assuming DEAD is the only plan left to fulfill (barcap/CAS/OCA/etc have already been assigned with aircraft)

I have the following aircraft left for the DEAD package:
4xB-52H
12xF-16C

The issue I encountered is that the DEAD strikes would first get used up as follows:
1st, F-16C assign DEAD/ESCORT/SEAD ESCORT for themselves (I.E a 2xDEAD, 2xESCORT, 2xSEAD ESCORT comprised solely of F-16C).
2nd, F-16C assign DEAD/ESCORT/SEAD ESCORT for themselves (I.E a 2xDEAD, 2xESCORT, 2xSEAD ESCORT comprised solely of F-16C).
3rd, B-52 assign DEAD with no ESCORT/SEAD ESCORT at all (F-16C have been used up fragging their own DEAD).

this causes the B-52 flight to get completely cancelled and all 4 B-52 are left unused for the player. 

From looking briefly at the code, I see that `best_squadron_for` takes the first squadron, without any further consideration.

That means that multi-role aircraft like the F-16C/FA-18 would hog all the "Main flight" (The actual DEAD).

I am working currently on a fix with a point system (Primary task would have more points then secondary tasks, and DEAD capable aircraft with better performance would get used before mediocre multirole fighters) that would cause B-52/B-1/F-117 to be chosen before FA-18/F-16 or any other multirole fighter.

### Save game and other files

Note: in this mission i disabled barcap to demonstrate the issue, that means that if you skip turn without turning it off yourself. you would just get regular barcap mission and won't witness the bug at all

[example_SEAD.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/10727665/example_SEAD.liberation.zip)

**Comment by Lordeath19** [comment]
Also, for now a temporary fix is to switch the order of DEAD_CAPABLE and SEAD_CAPABLE.

In the end the `ai_flight_planner_db.py` should look like so:

`DEAD_CAPABLE = [LIST_OF_AIRCRAFT] + SEAD_CAPABLE`

instead of `DEAD_CAPABLE =  SEAD_CAPABLE + [LIST_OF_AIRCRAFT]`

😄

**Comment by DanAlbert** [comment]
> I am working currently on a fix with a point system

Yeah... I figured we weren't going to get away without that for much longer. Have a look at https://github.com/dcs-liberation/dcs_liberation/issues/2035, https://github.com/dcs-liberation/dcs_liberation/issues/2036, and https://github.com/dcs-liberation/dcs_liberation/issues/2037 while you're doing that and see if there's any overlap. Definitely do not try to solve those problems at the same time! just keep them in mind 😄

Might be a good time to extract that information out of Python and into the aircraft yaml files (`resources/units/air/...`). Up to you.

> Also, for now a temporary fix is to switch the order of DEAD_CAPABLE and SEAD_CAPABLE.
>
> In the end the ai_flight_planner_db.py should look like so:
>
> DEAD_CAPABLE = [LIST_OF_AIRCRAFT] + SEAD_CAPABLE
>
> instead of DEAD_CAPABLE =  SEAD_CAPABLE + [LIST_OF_AIRCRAFT]

If you want to send that PR, I'll have a look through the git history soon to make sure that is the obvious bug it appears to be and not a non-obvious feature.

What benefit would the point system offer over the simple fix?

**Comment by Lordeath19** [comment]
> Yeah... I figured we weren't going to get away without that for much longer. Have a look at https://github.com/dcs-liberation/dcs_liberation/issues/2035, https://github.com/dcs-liberation/dcs_liberation/issues/2036, and https://github.com/dcs-liberation/dcs_liberation/issues/2037 while you're doing that and see if there's any overlap. Definitely
do not try to solve those problems at the same time! just keep them in mind 😄

Yea these features address the things I wanna add, I am going to hold off on the fix itself and stay with the temp fix.

> What benefit would the point system offer over the simple fix?
Currently the theater can change with more emphasis on firepower/stealth/range/self protect. So a point system to reward the B-52 for its high range could be better the F-117 stealth. When SA-10/SA-5 sites are placed it makes much more sense to send in F-117 due to supreme stealth capabilities even though they don't have the firepower to destroy the entire site.

The temporary fix only has one snapshot of that ranking which is the overall ranking I gave it completely arbitrarily based on my preference (for example in DEAD: B-52>F-117>B-1>F-16>FA-18).

Hopefully I got the point (pun intended) across

**Comment by DanAlbert** [comment]
Are you just talking about making it moddable?

**Comment by Lordeath19** [comment]
I will continue talking based on DEAD alone but this apply for the rest of the objectives as well.
The point system addresses the fact that we want the *best* aircraft for the job at all times.
At the beginning of the campaign, there are a lot of long range SAMs, this causes DEAD to be forced into dangerous SAMs, the commander should prefer designated aircraft for those tasks (F-117 with extreme stealth and B-52 with cruise missiles have a higher chance of surviving and completing the objective).

After the long range SAMs are dealt with, range has no more impact on effectiveness, and the F-16 (for example) can become the best aircraft as it has self protect abilities and more firepower than the F-117.

Everything I wrote is the idea behind the point system, but I should note again. the temporary fix does an excellent job for the most part from the past 3 days of testing and playing around 15 turns on a heavy campaign

**Comment by DanAlbert** [comment]
https://github.com/dcs-liberation/dcs_liberation/pull/2838 should have largely fixed this.
