### ISSUE TITLE
Setting Player mission interrupt fast forward to "never" and also enabling auto-resolve results in fast forwarding forever and app freeze

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#2739]
### Affected versions

6.1.1

### Build information

DCS Liberation 6.1.1

### Description

Players who leave "Player mission interrupt fast forward" on "never" and also enable auto-resolve will encounter an app freeze as fast forwarding doesn't end.

### Save game and other files

[This mission will freeze if you click take off.zip](https://github.com/dcs-liberation/dcs_liberation/files/10776867/This.mission.will.freeze.if.you.click.take.off.zip)

**Comment by DanAlbert** [comment]
What did you want it to do?

**Comment by DanAlbert** [comment]
Short of raising an error ("hey, you told the sim that it should never pause, don't do that") I'm not sure what can usefully be done here. We could pause once all flights are in the completed state, but is that at all useful? The mission you generate would not have any missions to fly.

**Comment by Starfire13** [comment]
> What did you want it to do?

Not freeze with the user having no idea why it's freezing is the main thing. A couple of possibilities:

1. Error pop up if user tries to close the settings window while "Never" and auto resolve are both selected.
2. State explicitly in the description that "Never" should not be used with auto-resolve (this of course depends on folks actually reading the description, which is not ideal!).
3. Disable the auto-resolve checkbox until one of the options other than "Never" is selected.
4. Change the default from "Never" to "At Cold Start Time". While this won't get rid of the problem, it will prevent it occuring unless the user deliberately sets it to "Never".
5. Change "Never" to "At Ingress Time" or something like that. Essentially, when ingress waypoint is reached. Since there doesn't seem to be any point in creating a player aircraft and then auto-resolving it entirely.

**Comment by DanAlbert** [comment]
2 is trivial, and my suggestion (which would happen at the "take off" time, not settings close) is not too much more difficult. The rest of the suggestions might be fairly difficult actually, because the whole settings window is auto generated...

2 plus my idea (yell if you hit "take off" with these settings) will probably be enough to save anyone from this PITA. WDYT?

**Comment by Starfire13** [comment]
Sounds good to me.

**Comment by DanAlbert** [comment]
Not a regression. Punting.

**Comment by SnappyComebacks** [comment]
I just found this (as I had just encountered it I think), another possibility for "What should it do?"  I was anticipating fast forward until the first player flight enters the threat area of the navmesh (maybe a buffer is needed because sometimes that is right at some SAMs threat ring).  Progressing until the first player flight hits the join point would be reasonable as well.

**Comment by DanAlbert** [comment]
> I was anticipating fast forward until the first player flight enters the threat area

![image](https://github.com/dcs-liberation/dcs_liberation/assets/315852/241b6dec-6af9-4e42-89e4-9a1fdad57563)

Can't really add join as many flight types do not have a join point.

(navmeshes and threat areas are different things, btw; navmesh has nothing to do with the fast-forward simulation, it's purely for finding nav points)

**Comment by Starfire13** [comment]
Hmm. Perhaps rather than "never" as a default, have it trigger by default at some point x minutes before the player flight's ingress point?

That said, nowadays I have to be quite conservative about using fast forward and ensure it's my flight that interrupts fast forward rather than an AI flight (so I typically just set an earlier start time and wait at the airfield, or delay the AI flights triggering fast forward stoppage), to get around the bug where the AI flight gets generated with no target waypoints and just RTBs.

**Comment by DanAlbert** [comment]
Remember that this bug isn't about fast forward, it's about autoresolve, the thing that's 100% not ready.
