### ISSUE TITLE
Strike waypoint does not match on f-16

### ISSUE THREAD

**Issue by jcllore** [dcs-liberation/dcs_liberation#2741]
### Affected versions

6.1.1

### Description

My problem only affects the F-16, I describe the problem, I plan a strike or SEAD mission, everything is fine, but when I get to the Strike waypoint, the Strike object does not match on the tpod and if I center it with the tpod the bomb falls outside the object. It only happens to me with the F-16. not with the F-18 or the Harrier.
It only happens to me with version 6.1.1, if I use version 5.2.1 there is no problem, the waypoint of the strike coincides with the tpod, perfectly aligned. Thank you

### Save game and other files

[Desert Storm 1991.zip](https://github.com/dcs-liberation/dcs_liberation/files/10784284/Desert.Storm.1991.zip)

**Comment by DanAlbert** [comment]
Have flown strike missions in the viper recently and the tpod was aligned correctly, so most likely was fixed at some point (whether the bug was us or DCS, who knows?)
