### ISSUE TITLE
Unable to launch Liberation 6.11

### ISSUE THREAD

**Issue by con1245** [dcs-liberation/dcs_liberation#2747]
### Affected versions

6.1.1

### Description

Hi I have been unable to launch dcs liberation for several versions now, not sure what's going on or if its an issue with liberation itself. Advice would be appreciated as I don't know what else to do.

![Capture](https://user-images.githubusercontent.com/126765027/222381855-c9414614-7d4f-450f-bb9f-e4e201a82a95.PNG)

### Save game and other files

No other files available

**Comment by Starfire13** [comment]
A couple things to try:

1. Delete the contents of C:\Users\Username\AppData\Local\DCSLiberation\ when you reinstall.
2. Make sure you are extracting files fully. Don't just overwrite the old install.
3. Check that your antivirus isn't blocking the program.

Ultimately, it's a problem specific to your system so it is difficult for others to troubleshoot.

**Comment by DanAlbert** [comment]
Based on the error, 1 looks very likely. Something in the persistent preferences (which tracks things like your DCS install and saved games directory) seems to be corrupted, and liberation seems to not be tolerant of that.

If that does solve your issue, leave this open. We should reset that file if it's corrupt, not fail completely.

**Comment by Starfire13** [comment]
The file doesn't even have to be corrupt. We've seen this error pop up in the past when folks move their DCS installation drive or directory, so Liberation is simply looking in the old location (since that information is stored in the appdata folder).

**Comment by DanAlbert** [comment]
Liberation isn't doing anything here aside from trying to parse the settings file. It's failing to parse. Moving your DCS installation could not cause that.

**Comment by DanAlbert** [comment]
Oh, actually, there's something extra screwy in there. This might be related to the livery loading changes that were made in pydcs a while ago.

**Comment by DanAlbert** [comment]
Yeah, I misread earlier (`read_liberation_preferences` is, surprisingly, not something liberation is doing). It might actually still be the same root cause (busted liberation preferences), but the problem is actually in pydcs.

**Comment by Starfire13** [comment]
We've had a number of folks on Discord who had moved their DCS install that resolved their problems straight away after deleting that folder, so it seems that something or other gets screwy in there if the install location has changed.

Maybe the livery scanner in pydcs is reading that file? (Or is that what you meant above?)

**Comment by DanAlbert** [comment]
With exactly that error? Because that error does quite clearly say that the problem is an invalid JSON file. Hard to imagine how that could be wrong.

**Comment by Starfire13** [comment]
No, with the "failed to execute script main" error.

**Comment by DanAlbert** [comment]
That's not necessarily the same thing. That just means the game failed to load.

**Comment by Starfire13** [comment]
Ah, I see.

**Comment by Raffson** [comment]
> A couple things to try:
> 
> 1. Delete the ~contents~ folder of C:\Users\Username\AppData\Local\DCSLiberation\ when you reinstall (in a different folder).

Or simply delete `liberation_preferences.json` within that folder, and that _should_ fix the problem because Liberation will regenerate that file when you start up Liberation the next time. However, the livery scanner will likely not initialize properly, but since Liberation doesn't make use of it, it shouldn't be a problem. But suppose that would change in the future, then I believe rebooting the application will be necessary after the preferences have been regenerated.

> Based on the error, 1 looks very likely. Something in the persistent preferences (which tracks things like your DCS install and saved games directory) seems to be corrupted, and liberation seems to not be tolerant of that.

Sounds about right....

> If that does solve your issue, leave this open. We should reset that file if it's corrupt, not fail completely.

Agreed! But since the livery scanner will always try to read this file before Liberation, there needs to be a fix in 2 places. One being in pydcs to gracefully handle that error, and one in Liberation where a new preferences file is regenerated. Should be fairly easy...

**Comment by Farmer8cheese** [comment]
Seems i'm having the same issue. I must not be smart enough as i cant seem to find the files you mention to delete or change. Searching for them brings up nothing. Any suggestions for us mentally handicapped folk?

**Comment by Raffson** [comment]
> i cant seem to find the files you mention to delete or change.

Have you turned on "show hidden folders" in your explorer options? AppData is a hidden folder so that might explain things...

In case you're wondering how: https://support.microsoft.com/en-us/windows/view-hidden-files-and-folders-in-windows-97fbc472-c603-9d90-91d0-1166d1d9f4b5

**Comment by DanAlbert** [comment]
> However, the livery scanner will likely not initialize properly, but since Liberation doesn't make use of it

Initialization of the livery scanner is not optional. That happens at import time. It really ought to be fixed to not do that imo.

**Comment by Farmer8cheese** [comment]
unfortunately i still can't find the files after doing as you suggested. the hidden items box was not checked as you suspected but didn't seem to have an effect.

**Comment by Farmer8cheese** [comment]
I finally got my head on straight and found C:\Users\Username\AppData\Local\DCSLiberation\. Once i deleted that and reinstalled again it's working fine. Thanks for the help.

**Comment by Raffson** [comment]
> Initialization of the livery scanner is not optional. That happens at import time. It really ought to be fixed to not do that imo.

What do you suggest?

**Comment by DanAlbert** [comment]
Lazy loading. The work done during import should always be minimized.
