### ISSUE TITLE
Aircraft lost not being counted by imported state file

### ISSUE THREAD

**Issue by Houghitsdone** [dcs-liberation/dcs_liberation#2753]
### Affected versions

6.1.1

### Description

Ran a mission with 25ish human pilots on dedicated server, imported state file at the end and none of the aircraft losses for either side were recorded, nor were any ground unit losses on blue side.

### Save game and other files

[aircraft losses bug.zip](https://github.com/dcs-liberation/dcs_liberation/files/10952095/aircraft.losses.bug.zip)

**Comment by VRabadan** [comment]
I have stumbled over this very same problem, somehow :( 
The state.json file has content, I pass it over to Liberation and it just says "0 units lost" on both sides.

Is there a workaround for this maybe?

**Comment by Starfire13** [comment]
> I have stumbled over this very same problem, somehow :( The state.json file has content, I pass it over to Liberation and it just says "0 units lost" on both sides.
> 
> Is there a workaround for this maybe?

No known workaround as this is not a common problem. In fact, I have not encountered it recently at all. One thing to check is to make sure you are actually using the state,json from that turn instead of one from a different turn or a different campaign.

**Comment by DanAlbert** [comment]
The mission that's attached is quite different than the one that generates from that save. The mission you flew is not one that matches the save you uploaded. Blue has substantially more aircraft in the miz you uploaded and the state.json than are actually present in the liberation save.  The miz generated from the save looks consistently correct. They do appear to be the same turn (same start time), but the only explanations that make any sense are things like:

1. Generated the mission, deleted flights, flew the mission without regenerating (or perhaps did regenerate but forgot to copy it to the server if playing on a dedicated server)
2. Saved game, added flights, generated mission, closed liberation without saving, flew, opened liberation, applied state.json

There isn't a great way for us to detect and warn about this. We could potentially generate a hash of the game state and write that to the miz, which could then be written back out the state.json and verified, but generating that hash is actually quite difficult to do portably, reliably, and deterministically. I'm very doubtful that it's worth the effort.
