### ISSUE TITLE
Persistent squadrons

### ISSUE THREAD

**Issue by DanAlbert** [dcs-liberation/dcs_liberation#276]
Add "squadrons" that have persistent AI (and player) pilots. Squadrons could be given a specific aircraft type, a mission type preference, and a fixed livery. AI members of the squadron would increase in skill as they complete missions.

Squadrons:

- [x] Use a single type aircraft.
- [x] Have a specific set of mission types that they perform. This could be a very large set of missions (like VFA Hornet squadron) or could be a single type (an E-2C squadron).
- [x] Can be defined in files so that players can define their own
- [x] Can also be auto generated from a handful of archetypes when all the predefined squadrons for the faction are exhausted but more squadrons are needed.
- [x] Have a fixed livery.

Pilots:

- [x] Have names.
- [x] Have their mission history tracked to some extent (initially only the number of missions flown, since anything more than that requires a lot of in-mission lua work).
- [x] Can die.
- [x] Gain skill after successful missions, which improves the skill level for AI pilots.
- [x] Can be defined as part of the squadron file so players can add themselves to the game.
- [x] Can be either players or AI.

Planned flights would no longer have just a client count; they'd have an assigned pilot.

Player pilots:

- [x] Can be auto-resurrected
- [x] Can be preferred for auto-assignment during ATO generation
- [x] Can have their automatically generated missions set to ASAP
- [x] Can be excluded from auto-assignment
- [x] Can be put on leave to prevent any assignment (for players that are not available)

A handful of follow ups were forked out since they either make large changes to economic balance or require non-trivial AI work:

* Squadron size cap and limited replenishment rate: https://github.com/dcs-liberation/dcs_liberation/issues/1136
* Replacing aircraft purchase costs with pilot replenishment rates: https://github.com/dcs-liberation/dcs_liberation/issues/1137
* Squadron limit per coalition: https://github.com/dcs-liberation/dcs_liberation/issues/1138
* Single base operation: https://github.com/dcs-liberation/dcs_liberation/issues/1145

**Comment by HomeFries94** [comment]
One interesting idea with this: once an aircraft type at an airfield exceeds 12 (though this number may be changed), a second squadron is created with a different livery and skill level (if implemented).

**Comment by HomeFries94** [comment]
another thought: if skill levels are implemented, then a ferry command would make more sense than decommissioning units at one base, then using the $$ to commission units at a front line base.

**Comment by DanAlbert** [comment]
(merged into OP for task tracking)

**Comment by DanAlbert** [comment]
The pilot half of this work is now done (aside from a [UI improvement](https://github.com/dcs-liberation/dcs_liberation/issues/1143)) and [documented](https://github.com/dcs-liberation/dcs_liberation/wiki/Squadrons-and-pilots).

**Comment by DanAlbert** [comment]
Squadron side is now complete. Any remaining work was forked into separate bugs, but this is feature complete.

**Comment by Slowdive1123** [comment]
Perhaps the squadron feature is not totally complete? I created 4 squadrons of the same aircraft type and allowing liberation to autopurchase aircraft, it only populated the first squadron with around 26 aircraft and 0 for the others of that type.

**Comment by DanAlbert** [comment]
Aircraft do not belong to squadrons. It assigns missions to squadrons with available pilots first, and then creates new pilots as needed. If you have two squadrons of identical capability and haven't created any pilots then it creates the pilots all in one squadron because there's no reason not to. If you want to use the second squadron, give it pilots.
