### ISSUE TITLE
Dictionary changed size during iteration

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#2773]
### Affected versions

Development build

### Build information

DCS Liberation 7.0.0
Build 4771
Git revision 8523c113579d5e93df7a35986d029f10e071a9af

### Description

Got this error when hitting pass turn. There are two squadrons scheduled for transfer (F-16 and Huey). The squadrons appeared to transfer fine though, even with the error.

![Screenshot 2023-03-31 150033](https://user-images.githubusercontent.com/72491792/229019542-97b11858-24d3-4e31-b15e-fcc74b37bc15.jpg)

### Save game and other files

[Peace Spring Inverted #4771 Turn 2.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/11118027/Peace.Spring.Inverted.4771.Turn.2.liberation.zip)

**Comment by DanAlbert** [comment]
The squadrons transfered okay because the transfer mentioned in the error is the other kind of transfer: ground units. The turn stopped initializing after that error, so your game is probably corrupted after that.

**Comment by DanAlbert** [comment]
This is a bug caused by my fix for the other transfer bug I fixed (one that wasn't symptomatic in my test case). Fix looks easy enough, but it might be a few days before I have a chance.

**Comment by DanAlbert** [comment]
https://github.com/dcs-liberation/dcs_liberation/pull/2774. Sorry about that!
