### ISSUE TITLE
Enemy AI can deploy airplanes from airfields with damaged runways when "default start type" is "in flight"

### ISSUE THREAD

**Issue by FelipLemos** [dcs-liberation/dcs_liberation#2775]
### Affected versions

6.1.1

### Description

When the Settlings => Mission Generator => Default start type for AI aircraft is "In Flight"
The enemy will plan packages from air bases regardless of the runway status and they spawn normally in the air.

I believe that the intention of the settings is just to "speed up" the mission, and it should not render runway destruction meaningless.

I my case it is worst due to the fact that is impossible to create BARCAP/TARCAP when all air bases are destroyed

### Save game and other files

[bug.zip](https://github.com/dcs-liberation/dcs_liberation/files/11141530/bug.zip)

**Comment by DanAlbert** [comment]
It looks like this was fixed at some point. [This save](https://github.com/dcs-liberation/dcs_liberation/files/12046385/damaged-runways-in-flight-bug.liberation.zip) is a new game where blue (I know your report was red, but there's no unique behavior for that) has lost all runways at bases with aircraft, AI are set to in-flight, and no flights are planned until the runways are repaired.
