### ISSUE TITLE
Capturing two sequential control points on the same turn prevents ground units from being moved up to the new frontline

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#2778]
### Affected versions

Development build

### Build information

DCS Liberation 7.0.0
Build 4775
Git revision 5c72e0754a438af1ea1cb1643528da7ce1df4b42

### Description

Let's say there's 3 control points in a row, CP A, CP B, and CP C. You start off at CP A. You then capture CP B and CP C on the same turn using air assault. Your ground units remain at CP A instead of moving up to CP C like they ought to.

### Save game and other files

Turn played: 
[Vegas Nerve #4775 Turn 1.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/11187273/Vegas.Nerve.4775.Turn.1.liberation.zip)

Following turn (showing ground units not moved up):
[Vegas Nerve #4775 Turn 2.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/11187277/Vegas.Nerve.4775.Turn.2.liberation.zip)

state.json file:
[state.zip](https://github.com/dcs-liberation/dcs_liberation/files/11187280/state.zip)

**Comment by DanAlbert** [comment]
Really wanted to fix this for 7, but the apache bug is forcing me to punt anything that's not a regression, and I'm pretty sure this is a very old bug.

**Comment by zhexu14** [comment]
Closing as this issue is fixed in the latest development branch.
