### ISSUE TITLE
Weapon release type does not update when SEAD flight is recreated as DEAD

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#2779]
### Affected versions

Development build

### Build information

DCS Liberation 7.0.0
Build 4775
Git revision 5c72e0754a438af1ea1cb1643528da7ce1df4b42

### Description

When you plan a SEAD flight, weapon release type is set as guided (you can see this under the ingress waypoint in the mission editor). If you plan a DEAD flight, it's set as auto. However, if you plan a SEAD flight and then change your mind and recreate it as a DEAD flight (in the Waypoints tab under Edit Flight), weapon release type is not updated to auto and remains as guided. This might be a potential problem for AI DEAD aircraft that are using unguided weapons.

### Save game and other files

Here's a sample mission with 3 flights.

Two of them are named REALSEAD and REALDEAD. Those are unmodifed. There is a third flight called SEAD2DEAD, which was first planned as a SEAD flight and then recreated as a DEAD flight.

[TALD Test 2.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/11187450/TALD.Test.2.liberation.zip)

**Comment by DanAlbert** [comment]
That makes very little sense. The release type isn't decided until miz generation, and is done only based on the mission type (maaaaaybe target and load out, but I don't think we ever got around to that for anything but bombers) so the history of the flight should be irrelevant. Will need to dig a bit...
