### ISSUE TITLE
F-15E missing from Blufor Modern

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#278]
Mudhen is sad it is not invited to party.

**Comment by DanAlbert** [comment]
Shows up for me on develop
![image](https://user-images.githubusercontent.com/315852/97793920-fd6df280-1baf-11eb-8d34-325306a3dbf0.png)

**Comment by Starfire13** [comment]
It is not showing up for me on Build #270. Are you sure you are looking at Blufor Modern?
![Blufor Modern no Mudhen](https://user-images.githubusercontent.com/72491792/97992271-91e98680-1e36-11eb-97db-e461c066ed3e.PNG)

**Comment by Khopa** [comment]
https://github.com/Khopa/dcs_liberation/commit/968d9365d67a113855e3056fe4bde826a3d317f9
