### ISSUE TITLE
F-14 and F/A-18 flights carrying TALDs will overfly target site and die

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#2781]
### Affected versions

Development build

### Build information

DCS Liberation 7.0.0
Build 4775
Git revision 5c72e0754a438af1ea1cb1643528da7ce1df4b42

### Description

F-14 and F/A-18 flights carrying TALDs will not RTB after releasing their TALDs but instead overfly their target and most likely get shot down.

The reason for this is because they are relying on the waypoint command "RTB on out of ammo= .ASM" to turn around, but now that TALDs have been moved into their own category (Decoy), this flag does not get tripped when TALDs are depleted. Hornets carrying HARMs work just fine, so this is specifically a TALD problem.

To demonstrate this, I have setup a mission with three flights. One (named HARM) is just a standard SEAD flight with HARMS, to demonstrate that they are indeed RTBing after launching their HARMs as expected.

The second flight (named TALD) is one carrying TALDs. I have modified the weapon release type to Decoy so they will actually drop their TALDs (modified .miz attached below). This flight will not RTB after dropping its TALDs, continuing on to overfly the target.

The third flight (named NOA2A) is a flight modified to carry no A2A missiles, weapon release type changed to Decoy, and with "RTB on out of ammo= .ASM" changed to "RTB on out of ammo= all" (because it will not trigger if set to .ASM since TALDs are now in their own category, I tested this to make sure). This flight will launch its TALDs and RTB.

I have also tried setting  "RTB on out of ammo" to "guided", "bombs", and "guided bombs", none of which worked with TALDs. Unfortunately, ED did not create a  "RTB on out of ammo= decoy" option when splitting TALDs into their own category.

### Save game and other files

Here is the Liberation save in case you want to make your own modifications for testing. Note that without the changes in the mission editor described above, this save will not replicate the problem and workarounds. It is easier to just use the .miz below for replication.
[TALD Test 4.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/11188254/TALD.Test.4.liberation.zip)

This is the manually modified .miz file
[liberation_nextturn.zip](https://github.com/dcs-liberation/dcs_liberation/files/11188227/liberation_nextturn.zip)

**Comment by Starfire13** [comment]
Would like to add that AI TALD flights will launch their TALDs (provided weapon type is set to decoy) and RTB correctly as long as there isn't a waypoint over the target. That waypoint isn't necessary for AI TALD flights anyway. So the simplest way to fix this might be to just not plan that waypoint if it's an AI flight and carrying TALDs.

**Comment by Lordeath19** [comment]
Hey, I have an open PR at pydcs for a requirement on this issue (there is a decoy class in weapon types), after the PR is approved I will create a PR here as well that fixes the TALD issue.

The PR will create a specific task called "Decoy" that F14/F18 have, same as SEAD but with a higher altitude to grant the decoy more flight time. also fixes the expend issue you are describing. feel free to look at my fork in the meantime

https://github.com/Lordeath19/dcs_liberation/commit/84379c0f7b15ff126a28145ff46f934284a6f8a5

Small note though, they will only launch the decoys if they have a RWR warning from the site in question.

**Comment by DanAlbert** [comment]
Please, no more mission types. The maintenance on them has become a huge pain. I already suggested a different fix that will work fine.

**Comment by DanAlbert** [comment]
https://github.com/dcs-liberation/dcs_liberation/issues/270 is the answer for subtle variations in mission types.
