### ISSUE TITLE
Will not install

### ISSUE THREAD

**Issue by Thanrixx** [dcs-liberation/dcs_liberation#2783]
### Affected versions

6.1.1

### Build information

New PC  windows 11 downloaded unzip ok when go to install, keeps asking for a app ?? any ideas

### Description

Unzipp new download when go to run install exe keeps asking for app in microsft store any idea??

### Save game and other files

liberation_main.exe"

**Comment by Starfire13** [comment]
There is no need to install anything. Just unzip to a folder (I suggest C:\Users\<Username>\Saved Games\dcs_liberation) and run the executable.

Also, if you are unable to install apps except those obtained from the Microsoft Store, then that's a setting on your end and you have to fix it.

**Comment by Thanrixx** [comment]
Done that and keep getting the same error that it is looking for a app to open

**Comment by DanAlbert** [comment]
It's just an executable. If Windows is asking you how to open an executable your Windows install is FUBAR. If you're getting a different error, please include the exact test or some screenshots, because I don't know what you're trying to describe.
