### ISSUE TITLE
Path issue with dedicated server

### ISSUE THREAD

**Issue by zildac** [dcs-liberation/dcs_liberation#279]
Hi,

Just started to play with DCs liberation (2.1.5). I've noticed an issue (certainly in my setup) as follows:

Using dedicated server to host miz files at home.

1. Desktop PC - DCS liberation installed to G:\DCS Liberation.
2. Create new campaign, takeoff, and abort.
3. Open created liberation_nextturn.miz file on Desktop, Enter ME and save (as outlined in docs).
4. Transfer miz file to DEDICATED server.
5. Load miz in dedicated server and join from Desktop PC.
6. Immediately get numerous messages about "unable to write state.json to G:\DCS Liberation"

So it seems that the miz file assumes that the same directory structure will exist on the target server, which on a dedicated server is unlikelly to be the case.

Simple fix is for me to reinstall DCS Liberation to C:\DCS Liberation (or any other drive/path that exists on both the machine running Liberation and the target dediacted server.

Appreciate it may not be simple to fix, but could be worth mentioninng specifically for dedicated servers with differing drives/paths.

I did have a quick scout around but couldn't see a similar issue mentioned lesewhere.

Thanks Z

**Comment by slasse** [comment]
it's a known issue, they are working on it 

there seems to be a page on the wiki now: https://github.com/Khopa/dcs_liberation/wiki/Dedicated-Server-Guide

**Comment by zildac** [comment]
Hey, many thanks. Didn't see that, makes perfect sense.

**Comment by bgreman** [comment]
Looks like this was fixed with 2.2.0 (https://github.com/dcs-liberation/dcs_liberation/commit/57b7402753c56079e125c7fc41bffe4b82fde991#diff-49d7ac8aa1dff77cda35fcfc865bec2d0c3454f7923bcff5ff2e65fab3ea74c0) which fixed the order in which the script tries to resolve the output path of state.json.
