### ISSUE TITLE
Insurgent faction for Blue?

### ISSUE THREAD

**Issue by Krag6** [dcs-liberation/dcs_liberation#28]
Is there a way to add Insurgent faction for Bluefor? For scenarios like Russia vs ISIS on Syria map?

**Comment by Khopa** [comment]
Hello, 

Yes, this will be possible from version 2.0.10, since i removed the current factions restrictions (faction are not restricted to BLUEFOR/REDFOR side anymore) : 

![image](https://user-images.githubusercontent.com/2546901/89716488-ac35d480-d9ad-11ea-9a7d-64e34a6a6cac.png)

**Comment by Khopa** [comment]
Fixed in 2.0.10
Please re-open if you encounter this issue again.
