### ISSUE TITLE
Freezes when app is closed on non main monitor then reopened.

### ISSUE THREAD

**Issue by sicwan** [dcs-liberation/dcs_liberation#2800]
### Affected versions

Development build

### Build information

7.0.0-4813

### Description

When you open the app on your main screen, then move it over to a 2nd or 3rd monitor, and close the app. the next time you open it up, the app will freeze and never load w/ a white screen.
Only way for me to fix it is to delete the registry entries for it and settings files

### Save game and other files

[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/11268310/liberation.log)

**Comment by Starfire13** [comment]
Hmm. I frequently move the app between my screens (and have closed the app on a different screen from the one where I opened it countless times) and have not had this issue occur.

**Comment by DanAlbert** [comment]
I never use Liberation on my main monitor and there's nothing useful in the log. No action we can take here.

**Comment by Vultur6** [comment]
Im actually having the exact same problem. I just tried deleting the old file system with no luck. The splash screen pops up and then opens the window in my second monitor and stays white and unresponsive. I tried disconnecting all my other monitors and open, but now it just freezes on the splash screen.
Once I deleted the registry entry it worked fine (Time stamp 2023-06-02 18:27:59). Everything before that would not work. 
[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/11639497/liberation.log)

**Comment by DanAlbert** [comment]
What registry entry? I don't see anything about the registry in your log.

**Comment by Vultur6** [comment]
Sorry the time stamp was when it started working properly. I deleted all the registry entries in Computer\HKEY_CURRENT_USER\SOFTWARE\DCS Liberation

**Comment by DanAlbert** [comment]
👀 wtf? we do not set any registry keys

**Comment by sicwan** [comment]
2 keys get made under
HKLM\Software\DCS Lineration\Qt UI

Name: geometry
Type: REG_BINARY

Name: windowState:
Type: REG_BINARY

so far its been working for me, but I'm a little afraid to update, as that seems to be when it does it. currently on v8.0.0-4995

**Comment by DanAlbert** [comment]
Ah, Qt is creating them. I guess that's how it remembers where the window was on the previous launch.

@Vultur6 how did you track it down to the registry key? What does the error look like in the log?

**Comment by sicwan** [comment]
It's the same trick I have to do when TacView stops working (they have the fix on thier fourm) so I just did the same for Liberation

**Comment by DanAlbert** [comment]
Hmm. Well if there's no error for us to catch and no way for us to detect that the problem happened at all, nothing we can do. Qt will be gone one of these years.

**Comment by Vultur6** [comment]
> 

To be honest I just followed sicwan's fix with deleting the reg entry lol. I just searched for liberation in software and found that. And yeah must be something with QT. 
I cant really see any errors within the log thats the weird thing. Probably some back end stuff that isnt controlled by the liberation code but something it utilizes.

**Comment by DanAlbert** [comment]
My best guess is that the format of the data changed between Qt 5 and 6 (which was an upgrade liberation took between 6 and 7), and that that's what's causing the problem. I can't explain why it hasn't happened to _everyone_ though. I don't remember having that problem.
