### ISSUE TITLE
SAM sites do not engage Blufor Modern on dev build #232

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#281]
Have confirmed that this is an issue on build #232. REDFOR SAMs will engage if player faction is set to USA 2005, but will not do so when set to Blufor Modern. This is with skynet disabled.

**Comment by DanAlbert** [comment]
@davidp57 @Starfire13 also reported that they were seeing "SAM sites being a different coalition from IADS" in the game even though they have Skynet disabled. That message comes from Skynet. Sounds like the plugins aren't actually being disabled properly?

**Comment by DanAlbert** [comment]
We don't have EWRs yet, but instead use SA-10s as EWRs, so if the enemy doesn't spawn any of those I think the SAMs won't ever be active. https://github.com/Khopa/dcs_liberation/issues/66 includes adding EWRs.

**Comment by DanAlbert** [comment]
EWRs are in the latest build. If this is still a problem then I'm wrong about the cause. lmk
