### ISSUE TITLE
i cant seem to load pass Terrain Graphics Init : 97 caucasus.ng5 in the ME for the .miz file

### ISSUE THREAD

**Issue by CptRogers** [dcs-liberation/dcs_liberation#285]
tried deleting all shaders that are safe to delete fxo meta2 and metacache cant seem to get it to work attached the liberation file and the miz file in the zip wouldn't let me uploaded them as is 
[GAW.zip](https://github.com/Khopa/dcs_liberation/files/5468481/GAW.zip)

**Comment by CptRogers** [comment]
seems that the issue was when I captured senaki I rebuilt a sam location that was kinda close to the sea and might be under the map causing the issue as once I deleted the sam site I was able to load the mission

**Comment by DanAlbert** [comment]
Happens when the SAM is accidentally placed underwater. We're migrating campaigns to a new format where that's not possible.

**Comment by Adeadly1** [comment]
I fixed this Terrain Graphics Init : 97 caucasus.ng5 hang up.

I have dcs 2.5.5. Lets say your A-10C under training start up is freezing up once you start.

Goto where your game is installed, mods-aircraft A-10C-Missions-Training-A-10C Training-Start-Up.miz file, here you would test the file using WinRar or 7zip if it comes back corrupt it may say data error: 10n\upru.jpg or png, open the file and delete the files it shows was corrupt. start the game again and it will load up fine.

**Comment by Starfire13** [comment]
If your files are corrupted, you just have to run a repair. That is not related to this issue, which is caused by underwater units.
