### ISSUE TITLE
and error ocurred when you have a squad with  " Combined Joint Task Forces red" creating a new campaing

### ISSUE THREAD

**Issue by 5js-xifu** [dcs-liberation/dcs_liberation#2853]
### Affected versions

Development build

### Build information

7.0.0-4933

### Description

I have a squadron.yaw in a file resource/squadron/viper thas has this country: Combined Joint Task Forces red 
When I start a new camapaing I have an error. 

If I delete this squadron the problem dissapear.
![errorliberation](https://github.com/dcs-liberation/dcs_liberation/assets/82957753/ef99b8de-19b5-4512-a5f6-644b97b48ed9)

### Save game and other files

name: GV06-5JS ARGRESSOR
nickname: AGRESSOR RED
country: Combined Joint Task Forces red
role: Multirole Fighter
aircraft: F-16CM Fighting Falcon (Block 50)
livery: IAF_115th_Aggressors_Squadron
mission_types:
  - BAI
  - BARCAP
  - CAS
  - DEAD
  - Escort
  - Intercept
  - OCA/Aircraft
  - OCA/Runway
  - SEAD
  - SEAD Escort
  - Strike
  - Fighter sweep
  - TARCAP

**Comment by DanAlbert** [comment]
`Red`, not `red`
