### ISSUE TITLE
Improve Frontlines

### ISSUE THREAD

**Issue by walterroach** [dcs-liberation/dcs_liberation#287]
This is related to the exclusion zones for spawn locations, there are many situations which result in ground units not being generated at all.  For example, attached is the starting scenario for Caucausus Full Map campaign.  I have five of each ground unit type on the Kutaisi/Vaziani front line, but no tanks or IFVs are added to the mission.

The problem occurs when trying to find a valid starting location in gen/armor.py GroundConflictGenerator.get_valid_position_for_group

A valid position cannot be found for these units, because no valid position exists within the DISTANCE_FROM_FRONTLINE parameter for these unit types.

We may want to consider checking exclusion zones when placing the frontline.  Another solution would be to attempt to find a valid position at varying distances from the frontline until one is found or a max/min distance is reached.

[GroundUnitSpawnExample.zip](https://github.com/Khopa/dcs_liberation/files/5469613/GroundUnitSpawnExample.zip)

**Comment by walterroach** [comment]
Tested using develop branch at commit b642164

**Comment by DanAlbert** [comment]
The best fix would be to have the front line not go straight through excluded areas. It's probably actually not too much work to add vertices to the front line so it can go around mountains, now that I think about it.

Idk about front line unit placement, but for ground object placement we pick random locations in a whole area, so if the thousand or so samples we take all fall in an excluded area it fails to place (and takes a really long time; most of the time spent generating a campaign in the caucasus is actually spent trying to find positions for boats around inland CPs). If we were to use a proper random-point-in-polygon algorithm that'd be a non-issue: we'd always be able to spawn if a valid area existed and it'd be way faster.

**Comment by walterroach** [comment]
For front line unit placement we're randomly trying 25 locations along a fixed distance from the frontline.

**Comment by walterroach** [comment]
Also related to #334

**Comment by walterroach** [comment]
Closing, work is moving into #385
