### ISSUE TITLE
[Feature Request] Tanker and AWACs Tasking

### ISSUE THREAD

**Issue by Mustang-25** [dcs-liberation/dcs_liberation#288]
Currently, tankers and AWACs exist in Liberation but there is no real way to control them other than in the ME.

In the future, some great features to add would be:

1. The ability to task them like other aircraft so that we can dictate the general areas of their orbits
    - Probably best to make them air start or connect it to #274 and have them spawn "off-map" or they'll take a long time to get 
       up to altitude

2. Tie it into #270 and the ability to set different flight profiles so that you can have separate tankers at different speeds and altitudes ( e.x. a low and slow for the hogs and a high and fast for vipers)

3. Make tankers and AWACs a purchasable asset like other aircraft

4. Make tankers and AWACs optionally visible/killable for both factions
    - Would also require adding HAVCAP as a tasking to protect these assets

**Comment by Mustang-25** [comment]
A further request I'd like to add:

5. Recovery tanker for the LHA and carrier. Both are important aspects of carrier ops IRL. Harriers especially as they normally take off at a reduced fuel load then tank up before ingressing.

**Comment by steevivo** [comment]
Hi , just little add 
- There is 4 E2C Hawkeye by carrier , 5 in specials case
- Cruising speed 300 knots
- Possibility to launch the E2C from carrier ? the first from the carrier when launch the mission
- Operating from an altitude more than 25,000ft
- detecting aircraft at ranges greater than 550km , so ability to choice hypodrom aeras

**Comment by RoleplayingPleb** [comment]
A system to move / place tankers similar to the carrier groups, or make awacs and tankers purchasable and task-able is one of my most anticipated features for the project moving forwards. Adding some stakes to protecting assets and value to escort missions sounds like a blast. Any update on progress on this would be cool.

**Comment by clairmont32** [comment]
Experienced this as well in my first mission loaded when exploring how this would look like for a friends only campaign. It seems like the SAMs and CAP entirely ignored it.

![image](https://user-images.githubusercontent.com/6239004/103111077-0e1e7000-4617-11eb-887a-a8fd2533b4a4.png)

**Comment by siKruger** [comment]
I did a first implementation of AWACS flights. Currently they are based on BARCAP flights but will Circle around the Racetrack-end point

+ AWACS can be bought 
+ AWACS waypoints can be set above Carrier and LHA, friendly Airfield and above the frontline
+ AWACS altitude is dependent on the type of aircraft (Currently its just using some values we set)
+ AWACS will return after 4H or Bingo

> https://github.com/Khopa/dcs_liberation/pull/837

**Comment by DanAlbert** [comment]
There's room for improvement in the layout of the tanker flight plans (for example, placing tankers at join/split points for offensive missions), but this is implemented now.
