### ISSUE TITLE
Airfields able to have more than the max supported aircraft

### ISSUE THREAD

**Issue by JPierce09** [dcs-liberation/dcs_liberation#2908]
### Affected versions

7.0.0

### Build information

Running the new 7.0 build

### Description

Was running up the "Up the Coast" mission and I noticed that when you start turn 0 that Senaki-Kolkhi AF had way more aircraft than it could support. I fixed that by removing a lot of squadrons or lowering the max on my end which is no big deal to me. If you notice in the save though that the REDFOR airfield Sukhumi-Babushara has 72/23 aircraft. Unsure if this was the intended purpose, but wanted to bring attention to it anyways.

### Save game and other files

[15c.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/11561035/15c.liberation.zip)

**Comment by DanAlbert** [comment]
Not all campaigns support the new squadron rules out of the box. Very few do, in fact. It's not a requirement (yet).

**Comment by DanAlbert** [comment]
(https://github.com/dcs-liberation/dcs_liberation/issues/2909 and https://github.com/dcs-liberation/dcs_liberation/issues/2910 were supposed to be included in 7 but there was no time to do so)

**Comment by JPierce09** [comment]
Ahh okay thanks for the heads up. Was just trying to make sure it wasn't a bug. I'll just hold off on using the new squadron rules until campaigns support it.

**Comment by DanAlbert** [comment]
Just to be clear: it may not be supported by _all_ campaigns for a long time. 7.1 will make it obvious which do (and make it easier to fix those that don't yourself).
