### ISSUE TITLE
player adjustable TOT offsets

### ISSUE THREAD

**Issue by DanAlbert** [dcs-liberation/dcs_liberation#2912]
Flight plans have a TOT offset property that adjusts their TOT relative to the package's. There are default offsets for some mission types like SEAD. I meant to expose this to the UI ages ago but apparently never remembered to do so.

**Comment by Starfire13** [comment]
This would be very handy because the necessary offset for a SEAD flight with HARMs and a SEAD flight with TALDs is very different. 🙂
