### ISSUE TITLE
Unexpected error when accepting results on last turn of campaign

### ISSUE THREAD

**Issue by notheotherben** [dcs-liberation/dcs_liberation#2918]
### Affected versions

7.0.0

### Build information

DCS Liberation 7.0.0

### Description

Upon completion of the campaign (technically, accepting the results of the turn within which the last enemy bases were captured) I received the following pop-up:

![image](https://github.com/dcs-liberation/dcs_liberation/assets/1760260/fad1e582-3abd-4401-abe0-e0fd273833ba)

Glancing through the code, it seems this is a scenario where the `closest_blue` control point is not set (and presumably `closest_red` as well, however the first assert prevents the second from being hit. Giving the code a quick once over, it seems like this may not handle scenarios where `self.player_points` or `self.enemy_points` return empty lists (which presumably would be the case during the end of a campaign). That said, none of the code here appears to have changed recently (with most of it being ~3 years old) which makes me wonder if there might be something else at play, since I assume many have finished campaigns in the interim.

The code in question (which doesn't handle an empty list of control points) is [here](https://github.com/dcs-liberation/dcs_liberation/blob/257dabe4fa41c41bb86e0b88b2b0fda75ffbf007/game/theater/conflicttheater.py#L172-L196C41).

As such, I suspect that the more likely cause of the problem is that we're calling `game.game.set_bullseye` prior to evaluating the win conditions (which would otherwise have skipped this codepath altogether). This is done [here](https://github.com/dcs-liberation/dcs_liberation/blob/257dabe4fa41c41bb86e0b88b2b0fda75ffbf007/game/game.py#L424).

Hopefully that (and the attached state+saves) is helpful in tracking this down, and thank you for all the hard work that has undoubtedly gone into this project - it is a work of art.

### Save game and other files

[autosave.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/11580342/autosave.liberation.zip)
[state.json](https://github.com/dcs-liberation/dcs_liberation/files/11580346/state.json.txt)

![image](https://github.com/dcs-liberation/dcs_liberation/assets/1760260/b4198609-0293-4b5c-8d44-5771bd6f33bf)

**Comment by DanAlbert** [comment]
It's a pinned issue. There is no victory screen.
