### ISSUE TITLE
BAI no longer plannable against Scud and Silkworm missile sites

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#2922]
### Affected versions

Development build

### Build information

DCS Liberation 8.0.0 (and 7.0 release)
Build 5043
Git revision 257dabe4fa41c41bb86e0b88b2b0fda75ffbf007

### Description

In 6.1.1, BAI was plannable against scud and silkworm launcher sites. This is no longer possible in 7.x, likely an unintended result of this fix (https://github.com/dcs-liberation/dcs_liberation/issues/2618).

Both sites should be attackable by BAI as they comprise ground units (launchers and SHORAD), not buildings.

### Save game and other files

Scud Example:
[Scud Example #5043.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/11583845/Scud.Example.5043.liberation.zip)

Silkworm Example:
[Silkworm Example #5043.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/11583846/Silkworm.Example.5043.liberation.zip)

**Comment by zhexu14** [comment]
@Starfire13 : this is probably me being dense, but could you help point me to where I can find a Silkworm? I can see Silkworms in the campaign .miz file, but can't find any when I load the save you attached / start a new campaign. For example, I see a Silkwork due west of Hatay on the coast in the .miz file but there's nothing there in Liberation. 

I found a Scud in the other save, and the fix I'm testing works, but can't seem to find a Silkworm.

**Comment by Starfire13** [comment]
> @Starfire13 : this is probably me being dense, but could you help point me to where I can find a Silkworm? I can see Silkworms in the campaign .miz file, but can't find any when I load the save you attached / start a new campaign. For example, I see a Silkwork due west of Hatay on the coast in the .miz file but there's nothing there in Liberation.

I already have a mission planned on a Silkworm and a Scud in those two respective saves.

**Comment by zhexu14** [comment]
> > @Starfire13 : this is probably me being dense, but could you help point me to where I can find a Silkworm? I can see Silkworms in the campaign .miz file, but can't find any when I load the save you attached / start a new campaign. For example, I see a Silkwork due west of Hatay on the coast in the .miz file but there's nothing there in Liberation.
> 
> I already have a mission planned on a Silkworm and a Scud in those two respective saves.

Thanks, much appreciated, don't know how I managed to miss that one!
