### ISSUE TITLE
CH-47D Unable to be Purchased in the Airfield Command Menu of Helicopter Carriers.

### ISSUE THREAD

**Issue by Josh-Alley20** [dcs-liberation/dcs_liberation#2926]
### Affected versions

7.0.0, Development build

### Build information

8.0.0-5043-257dabe4fa41c41bb86e0b88b2b0fda75ffbf007-preview

### Description

   The CH-47D cannot be purchased for helicopter carriers. I went to the DCS mission editor and tested whether it was possible to deploy this aircraft on the deck of the LHA1 and the HMS Invincible, which it was possible.

I'm not sure if this is intentional for balancing purposes, but I would appreciate it if this issue could be addressed and or fixed.

### Save game and other files

[CH-47 Bug.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/11593693/CH-47.Bug.liberation.zip)

**Comment by Starfire13** [comment]
While Chinooks can land on the deck of the LHA and HMS Invincible (to drop off cargo or passengers before taking off again), they do not carry them as part of their complement of aircraft.

**Comment by Josh-Alley20** [comment]
Whoops makes sense, I will close this out.
