### ISSUE TITLE
App warns about bad TOT while UI doesn't show anything wrong

### ISSUE THREAD

**Issue by s3-chardonjf** [dcs-liberation/dcs_liberation#295]
EDIT: most likely a rounding issue. If you add a single second to the package TOT, it no longer complains.

![image](https://user-images.githubusercontent.com/29724443/97796117-78fe8c80-1c0e-11eb-8373-faa706d3f0ed.png)
Develop branch build.

- Load the save
[autosave.zip](https://github.com/Khopa/dcs_liberation/files/5470264/autosave.zip)

- Hit take off and notice it generates the miz without complaining, abort mission
- Edit package CENTIPEDE
- Add a human slot on the DEAD flight
![image](https://user-images.githubusercontent.com/29724443/97796138-bebb5500-1c0e-11eb-810f-aeacad1e8c74.png)

- Click ASAP to set tot to soonest.
- Notice the UI looks ok with positive departure times
![image](https://user-images.githubusercontent.com/29724443/97796146-ced33480-1c0e-11eb-8a5c-5a243fd12016.png)

- Attempt to take off and get the notification
![image](https://user-images.githubusercontent.com/29724443/97796154-da266000-1c0e-11eb-925b-8c02185a80de.png)

**Comment by s3-chardonjf** [comment]
The error isn't thrown anymore, but I notice that flights that would show 0:00:00 start time in previous build (and throw the error) are now showing 0:00:01 (and no longer throwing the error). 

![image](https://user-images.githubusercontent.com/29724443/97799311-c63e2680-1c2d-11eb-8b32-96f7b7dc42ae.png)

Load this save and take a look at Grizzly package both before and after fix.
[2020-10-27-1.zip](https://github.com/Khopa/dcs_liberation/files/5470482/2020-10-27-1.zip)

**Comment by DanAlbert** [comment]
https://github.com/Khopa/dcs_liberation/pull/296 might fix this. The issue doesn't happen on my machine, so not sure. If it does lmk and I'll merge it.

**Comment by s3-chardonjf** [comment]
One more info: If I press ASAP once, I get the decimals (new build that does not round), then I press it a second time and only then is it 0:00:00

**Comment by Starfire13** [comment]
Uploading at DanAlbert's request. Wonky flight start times.
[Why So Syrias, Turkey.zip](https://github.com/Khopa/dcs_liberation/files/5472993/Why.So.Syrias.Turkey.zip)

**Comment by DanAlbert** [comment]
https://github.com/Khopa/dcs_liberation/actions/runs/341488757 fixes this, I think. We were picking the actual target location differently depending on whether we were finding the ASAP TOT or the package waypoint timing, so if there was enough of a difference between the flight's first target point and the center of the objective area that caused the discrepancy. For now I've avoided rounding the shared waypoints in the UI for the moment since those were the issue. If it all looks good now I'll fix that.
