### ISSUE TITLE
UI during squadron set up squeezed if several airfields are over-filled.

### ISSUE THREAD

**Issue by Emdub01** [dcs-liberation/dcs_liberation#2974]
Please add resize bar to allow normal squadron set up.
![Untitled](https://github.com/dcs-liberation/dcs_liberation/assets/135866057/a95df0ce-f9c0-47ed-a939-031ea7b604df)

**Comment by DanAlbert** [comment]
What campaign was this? This didn't happen on any that I tested.

**Comment by Emdub01** [comment]
I've experienced this in several. Most recently, the full Syria campaign.

**Comment by DanAlbert** [comment]
It's already fixed.
