### ISSUE TITLE
Sinai Support

### ISSUE THREAD

**Issue by Druss99** [dcs-liberation/dcs_liberation#2979]
**Is your feature request related to a problem? Please describe.**
Sinai is released and is not yet supported by liberation.

**Describe the solution you'd like**
Support for the new Sinai map.

- [x]  pydcs terrain export
- [x] update pydcs
- [x]  landmap
- [x]  beacon data
- [x]  daytime map
- [x] timezone
- [x] weather data
- [x] minor campaign version bump (do this once ready for campaigns)

**Comment by DanAlbert** [comment]
_sigh_ Would be great if ED could release maps at the same time if they're going to come so close together.

@Druss99 feel like tackling another landmap?

**Comment by DanAlbert** [comment]
Tentatively triaging to 8. We won't know until we try the DCS export whether it will break save compat. If it doesn't well make it 7.2.0.

**Comment by Druss99** [comment]
I will work on it this week, hopefully will be done in a few days

**Comment by DanAlbert** [comment]
Great, thanks. I'll get started on the rest soonish (I probably will not be spending any time on liberation this weekend though).

**Comment by Starfire13** [comment]
I've started work on a campaign for the Sinai map, so we'll have at least one ready to go for 7.2/8.0

**Comment by Starfire13** [comment]
We also have no Egypt faction, so I'll look into putting one together.

**Comment by DanAlbert** [comment]
Only work that remains is the landmap, and I need to actually load into a plane and figure out what the UTC offset it for the map.

**Comment by DanAlbert** [comment]
This will be 8.0.0, btw. The DCS data export broke save compat, and working around that is quite time consuming and error prone.

**Comment by Druss99** [comment]
hopefully I will have the landmap done today

**Comment by Druss99** [comment]
Files are about double the size of the Normandy files (7mb instead of 3mb) because the map is significantly larger. Hopefully this will not cause any issues but let me know.
[FinalExclusionAreaSinai.zip](https://github.com/dcs-liberation/dcs_liberation/files/11726828/FinalExclusionAreaSinai.zip)
[FinalOceanSinai.zip](https://github.com/dcs-liberation/dcs_liberation/files/11726829/FinalOceanSinai.zip)
[FinalUsableLandSinai.zip](https://github.com/dcs-liberation/dcs_liberation/files/11726830/FinalUsableLandSinai.zip)

**Comment by DanAlbert** [comment]
So far so good. I need to build a trivial test campaign to verify that it imported correctly, but the import went quickly at least.

**Comment by DanAlbert** [comment]
Looks plausible enough to me.

![image](https://github.com/dcs-liberation/dcs_liberation/assets/315852/9f6ebb3e-c995-44fb-8b1e-ea89bd0af971)

Thanks again!
