### ISSUE TITLE
AI SEAD/DEAD Flight don't attack

### ISSUE THREAD

**Issue by dzambrano10** [dcs-liberation/dcs_liberation#298]
Looks like the AI SEAD flights do not get an attack task generated for their respective SAM group.

**Comment by walterroach** [comment]
@davidp57  - this problem appears to be a difference in the theater.TheaterGroundObject naming and the dcs.UnitGroup.VehicleGroup naming.  It looks like the dcs.UnitGroup naming was updated for IADS, but the corresponding theater objects were not.  The flight planning uses the name attribute to discover which groups are at a target point (Likely should change that as well, imo the only thing that should use the string names should be related to exporting the .miz and importing the state.json).

**Comment by DanAlbert** [comment]
In that case the problem is near a bunch of code I'm touching anyway, so I'll fix it up while I'm there. Thanks for the diagnosis!
