### ISSUE TITLE
Air Wing configuration window too small

### ISSUE THREAD

**Issue by ravenshadow68** [dcs-liberation/dcs_liberation#2982]
### Affected versions

7.1.0

### Description

The air wing configuration window is too small. Can the window be scalable?

![image](https://github.com/dcs-liberation/dcs_liberation/assets/136198746/a27e13c9-f0be-44b5-bee1-ff001bbcb000)

### Save game and other files

[test1.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/11713315/test1.liberation.zip)

**Comment by Starfire13** [comment]
It's already fixed in dev build. #2974
