### ISSUE TITLE
Getting many repetitive pop-ups with tracebacks

### ISSUE THREAD

**Issue by dwhysong** [dcs-liberation/dcs_liberation#2983]
### Affected versions

7.1.0

### Build information

DCS Liberation 7.1.0

### Description

Virtually any time I do anything I'm getting 2 or more pop-ups with tracebacks. 
### Save game and other files

![image](https://github.com/dcs-liberation/dcs_liberation/assets/38592617/4632120a-b111-44c9-8a54-87773d32cd96)
![image](https://github.com/dcs-liberation/dcs_liberation/assets/38592617/61b92988-b395-4025-b074-98c7a40f2644)
[
[temp.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/11713585/temp.liberation.zip)

**Comment by Starfire13** [comment]
This has been reported before, but so far, no one's provided a way to replicate the problem. If you know how to reproduce these errors in a consistent manner, please share so it can get fixed. https://github.com/dcs-liberation/dcs_liberation/issues/2272

**Comment by DanAlbert** [comment]
And until then there's nothing we can do. We obviously wouldn't have shipped if every UI element in the game was broken.
