### ISSUE TITLE
Pylon bug after Gazelle update

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#2984]
### Affected versions

Development build

### Build information

**DCS Liberation 8.0.0
Build 5147
Git revision c45ac50370459a5d8109abac2e269bbbab3f9951**

### Description

Gazelles can no longer be used in Liberation after the latest DCS update. The IR deflector is now on a seperate pylon, and the L version has gotten new weapons. The Mistral variant is now weaponless (while it remains in the game for compatibility reasons, the weapons have been moved to the L variant).

Gazelle changelog available here if needed: https://stormbirds.blog/2023/06/03/gazelle-update-details-significant-updates-change-log/

If the old default loadouts are used, the .miz is generated but Gazelle flights do not exist when the file is viewed in the mission editor. If the loadouts are updated, this error is encountered upon take off.

![Screenshot 2023-06-12 094512](https://github.com/dcs-liberation/dcs_liberation/assets/72491792/df18a467-613f-44fb-acc7-41f5e650774f)

I have created updated loadout files for all 4 variants of the Gazelle, attached below.

### Save game and other files

[Gazelle Pylon Bug Example.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/11716108/Gazelle.Pylon.Bug.Example.liberation.zip)

Updated loadouts:
[SA342 Gazelle New Loadouts.zip](https://github.com/dcs-liberation/dcs_liberation/files/11716110/SA342.Gazelle.New.Loadouts.zip)

**Comment by DanAlbert** [comment]
pydcs update breaks save compat, so this will have to be in 8. We'll get on that ASAP I suppose.
