### ISSUE TITLE
Delayed player slot dosen't work

### ISSUE THREAD

**Issue by ataribaby42** [dcs-liberation/dcs_liberation#3]
If player flight is anything more than +0 take off time it is set as late activation and activated with trigger. 

This method works for AI but not for player slot. It needs to be unchecked as Late activation without trigger and first waypoint time needs to be set to real start time instead 00:00:00.

Then Player will get notification about delayed start and then later his plane is activated.

I tested this with manualy change player flight in editor before flight.

**Comment by Khopa** [comment]
Thank you for your report. 

I intend to make player/client slots never delayed in the upcoming version. So players can just jump in their slots whenever they want, as a lot of people tend to forget to setup their flight at t+0.  

Then it would be players' responsibility to follow (or not) their schedule.

**Comment by ataribaby42** [comment]
That will be best solution.

Any posibility to randomize bort numbers of aircrafts? Line of migs with all have 10 on nose is bit strange :)

**Comment by SlainteMaith** [comment]
So how does one fly a mission that's scheduled in advance at the moment?
Every time I try to fly something, I'm allowed into my slot, but not allowed into a jet.

**Comment by Khopa** [comment]
Sorry, this is not really intuitive, you have to set explicitly your slot to T+0 minutes in the flight planner before takeoff.

![image](https://user-images.githubusercontent.com/2546901/84581436-0288fb80-ade1-11ea-9b53-7650df090259.png)

Otherwise you would have to wait for your plane to be allowed to spawn.


BTW, this won't be necessary anymore in the upcoming version.

**Comment by SlainteMaith** [comment]
I found that after doing some digging.
Thanks for the quick response!

**Comment by Khopa** [comment]
This is fixed in RC7+ versions, closing
