### ISSUE TITLE
Auto-purchaser not buying reinforcements for frontline when only air transportion is available

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#3001]
### Affected versions

Development build

### Build information

DCS Liberation 8.0.0
Build 5191
Git revision 1162e0aa29aa80b525c9a165f67fa64a796aff7f

### Description

Auto-purchaser is not buying ground units to ferry up to the control point with a frontline.

![Screenshot 2023-06-13 225512](https://github.com/dcs-liberation/dcs_liberation/assets/72491792/ca274b97-efaf-4497-aa5f-b90a4eda16fa)

The enemy has three CPs, labelled A, B, and C. C has a frontline, and currently has no ground units. They were all destroyed. B has no transport aircraft nor a factory, so it can essentially be ignored here. A has 8 C-130 aircraft and a factory. I had thought that the auto-purchaser would buy ground units at A, load them onto the 8 C-130s, and transport them to C. But it is not buying any ground units at all.

### Save game and other files

[Bright Star #5191 Turn 6.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/11739786/Bright.Star.5191.Turn.6.liberation.zip)

**Comment by DanAlbert** [comment]
The campaign you're building for Sinai is basically dead without this fix, right? If so I think we'll need to tackle this in 8, but doing so would put of the release a while longer.

**Comment by Starfire13** [comment]
Yep. Since there are no frontline reinforcements for OPFOR unless this is fixed.

**Comment by Starfire13** [comment]
Question. If there were a supply route between A and B (and a break between. B and C), should the auto-purchaser be smart enough not to convoy ground units up to B which has no transport squadron and instead just ferry the units direct from A by air? I had originally intended there to be a supply route between A and B but was concerned the auto-purchaser couldn't handle that and removed it. I can't place the transport squadron at B as there are no parking spots for larger aircraft there.

**Comment by DanAlbert** [comment]
Your save works for me. Loaded your save, skipped two turns, units appeared in Melez. Hacking the transfers dialog to show me red rather than blue, it's empty in the save you uploaded, here's +1 turn:

<img width="753" alt="image" src="https://github.com/dcs-liberation/dcs_liberation/assets/315852/daa86f24-f518-4b2e-8e68-bc6b844da99a">

I can keep digging if it's unexpected that there are no transfers scheduled on turn 6 (the turn the save is on).

**Comment by DanAlbert** [comment]
> Question. If there were a supply route between A and B (and a break between. B and C), should the auto-purchaser be smart enough not to convoy ground units up to B which has no transport squadron and instead just ferry the units direct from A by air?

Transport squadrons do not need to be based at the pickup location. A squadron at A can pick up units at B and move them to C.

But also yes, a connection is a connection. The only difference between an air/land/sea connection is the "cost" of that move that the shortest path algorithm sees. You can see this working in Abu Dhabi where the factory in Bhandar Abbas is able to supply bases across the straight even though they have to take both sea and land routes.

**Comment by Starfire13** [comment]
Hmm. That's odd. I passed turn up to I think turn 10 and saw no ground units being purchased. I will try it again tonight. 🤔

**Comment by DanAlbert** [comment]
For some reason the previous-turn checkpoint in the save file is also turn 6, so I can't investigate how things got the way they are. From the log I think it takes until turn 8 for reinforcements to arrive because on turn 5 Melez still had a functioning factory of its own. On turn 6 units were ordered, they were produced in Cairo West on turn 7 and arrive in Melez on turn 8.

**Comment by Starfire13** [comment]
Melez has never had a factory. From campaign start, the only way to get reinforcements to the frontline was from Cairo West.

**Comment by Starfire13** [comment]
The runway at Cairo West was bombed on turn 1. So I wasn't expecting any new frontline units for a while. The runway was down for turns 2 to 5. What I was expecting was that after turn 6 (buy on turn 6, become available at Cairo West on turn 7, then deliver to Melez on turn 8), it would buy ground units at Cairo West because by then, the frontline units at Melez had been completely wiped out.

**Comment by Starfire13** [comment]
Ok, the transfer is working. Sorry. I had been looking at the air wing inventory panel and the transfers panel and it appears the former doesn't update if left open when you hit pass turn, and the latter doesn't show air transfers. But the ground units do show up at the destination.

**Comment by DanAlbert** [comment]
The transfer panel doesn't show enemy transfers. My screenshot only did because I can change that :)
