### ISSUE TITLE
DCS log spammed with trigger errors

### ISSUE THREAD

**Issue by s3-chardonjf** [dcs-liberation/dcs_liberation#301]
EDIT: I believe this issue might be caused by myself as the size of the .miz file is suspiciously low, it would indicate that I missed the step of opening and saving it in Mission Editor. 

I'm not sure if this is something we doing wrong or a common DCS issue, but I noticed my DCS log was spammed with thousands like these:
`2020-11-02 07:40:50.738 ERROR   Trigger: can't execute trigger, err:"[string "?"]:1: attempt to call field '?' (a string value)"`

See attached miz
[liberation_nextturn.zip](https://github.com/Khopa/dcs_liberation/files/5473589/liberation_nextturn.zip)
liberation save 
[liberationsave.zip](https://github.com/Khopa/dcs_liberation/files/5473594/liberationsave.zip)
and the dcs.log
[dcs.log.zip](https://github.com/Khopa/dcs_liberation/files/5473587/dcs.log.zip)

Note: I used Combined Arms and I gave orders to ground units to clear the enemy units before I took flight myself.

**Comment by DanAlbert** [comment]
This happens if `MissionScrioting.lua` wasn't replaced before launching DCS, iirc.
