### ISSUE TITLE
Hatzor Airfield Bug

### ISSUE THREAD

**Issue by rhoadsy123** [dcs-liberation/dcs_liberation#3021]
### Affected versions

Development build

### Build information

8.0 Preview Build

### Description

No flights can take off from Hatzor Airbase. It gives an "error airfield20_0" message

### Save game and other files

[Sinai.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/11808979/Sinai.liberation.zip)
[Sinai Assault.zip](https://github.com/dcs-liberation/dcs_liberation/files/11809118/Sinai.Assault.zip)

**Comment by rhoadsy123** [comment]
Zipped Yaml and Miz files

**Comment by DanAlbert** [comment]
Will have a look before hitting the go button on 8 (you're just in time). Presumably a difference in how absent data is represented for that airfield than for others. The data in DCS is very inconsistently defined.

**Comment by DanAlbert** [comment]
Please make sure the save you upload actually repros the error you're reporting in the future. The attached save does not have any flights from that airfield. That's why we ask for saves: we need to know if we're fixing _your_ bug or just _a_ bug.
