### ISSUE TITLE
Error opening program

### ISSUE THREAD

**Issue by SlainteMaith** [dcs-liberation/dcs_liberation#3025]
### Affected versions

Development build

### Build information

DCS Liberation 8.0.0

No build information accessible, program does not load that far.

### Description

Seems like some folders weren't packaged with the build, or the readme.txt (which I couldn't find) didn't show what dependencies this program needs to work, namely the folder PySide6, although there are many many other folders missing from the 8.0.0 build that were in the 7.x build.

Does this need installed over top of an older version? 

### Save game and other files

Failed to execute script 'main' due to unhandled exception: [WinError 3]  The system could not find the path specified: 'C:\\DCS Liberation\\PySide6'

Traceback (most recent call last):
  File "qt_ui\main.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "PySide6\__init__.py", line 123, in <module>
  File "PySide6\__init__.py", line 111, in _find_all_qt_modules
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\DCS Liberation\\PySide6'

**Comment by DanAlbert** [comment]
Works for me (dcs_liberation.8.0.0.zip downloaded from https://github.com/dcs-liberation/dcs_liberation/releases/tag/8.0.0). Unfortunately when that's the case there's not really anything we can do aside from give the standard advice:

1. Install somewhere else (in case the infrastructure outside our control is trying to write to that directory, it may not have permission to do so). I always extract to my desktop and run from there
2. Check your antivirus
3. If you're a python developer, check that you don't have globally installed python packages that are interfering with Liberation

Beyond that the only things we can do without a way to reproduce the error ourselves (unlikely, as these things are often environment specific) is replace Qt, which we've been actively working on for quite a long time and it's going to still take quite a lot more time.

> there are many many other folders missing from the 8.0.0 build that were in the 7.x build.

tbh that sounds like you either downloaded the wrong thing or the extraction was incomplete. I just did this and mine has a PySide6 directory.
