### ISSUE TITLE
option to ask JTAC to turn the laser off

### ISSUE THREAD

**Issue by unixwitch** [dcs-liberation/dcs_liberation#303]
JTAC's laser is very helpful for finding targets, but sometimes the tracking can be a bit iffy - for example it lags behind moving vehicles, and especially on small targets it isn't always centered on the target, which can be a problem when using laser-guided rockets (which have a fairly small blast radius).

could we get a radio option to ask JTAC to turn the laser off and back on again, so we can self-lase with the TGP when needed?

**Comment by Starfire13** [comment]
Can't you just set your own laser to a different frequency code so you can use your own laser or the JTAC's as you wish?

**Comment by slasse** [comment]
not sure about other modules but the viper only has the ability to set bomb laser codes on the ground before startup.
as a workaround you could then set your own code at startup and use LSS to spot the JTAC's laser code and then lase yourself on you own code

**Comment by DanAlbert** [comment]
JTAC support comes from https://github.com/ciribob/DCS-JTACAutoLaze, which I don't think makes it possible to do this.
