### ISSUE TITLE
F-15E Suite 4+ squadrons not selecting assigned livery

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#3034]
### Affected versions

Development build

### Build information

DCS Liberation 9.0.0
Build 5258
Git revision 658a86dff57c411136adbcc4f8a242274c85f994

### Campaign name

Exercise Bright Star

### Blue faction

Blufor Modern

### Red faction

Egypt 2000

### Modifications to default settings

None

### Description

The way liveries are generated appears to be different with the F-15E, where there is a base texture (in the textures folder), with squadron markings overlayed. While other aircraft modules have each livery as a zip file, the F-15E has just a description.lua for most of the liveries, or sometimes a single .dds file along with the description.lua\

I have attached two test squadrons I created, one for a squadron that only has a description.lua, and another that has a description.lua and a .dds file.

### Log file

[liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/11859218/liberation.zip)

[F-15E Strike Eagle (Suite 4+).zip](https://github.com/dcs-liberation/dcs_liberation/files/11859220/F-15E.Strike.Eagle.Suite.4%2B.zip)

**Comment by DanAlbert** [comment]
I fixed your 17th WS squadron to use `usaf 17th ws af90 low vis clean` (the name of the livery directory in lower case) and it works. You had `USAF 17th Weapons Squadron AF90 Low Vis Clean`, which is both the wrong case and spelled wrong (the livery is "WS" not "Weapons Squadron").

In case you're looking in some other directory, the relevant one here is `<DCS install>\CoreMods\aircraft\F-15E\Liveries\F-15ESE\USAF 17th WS AF90 Low Vis Clean`

**Comment by Starfire13** [comment]
Ah I was using the name in the description.lua. I tried the folder name previously and still couldn't get it to work, but will try again. As in, the squadron gets recognised but it didn't have the correct livery (just the first one on the list). But I'll double check.

**Comment by DanAlbert** [comment]
If the livery selector showed anything but "Default", the livery was parsed correctly but a different bug (fixed by https://github.com/dcs-liberation/dcs_liberation/pull/3043, which I found while debugging this) accidentally replaced it with the wrong one. If it showed "Default" you used an ID with no matching livery (and possibly just a case issue).

**Comment by Starfire13** [comment]
The livery was showing default in Liberation and defaulted to the first livery in the mission editor (which is the Israeli one).
