### ISSUE TITLE
White Screen on Startup

### ISSUE THREAD

**Issue by JaalenASF** [dcs-liberation/dcs_liberation#3035]
### Affected versions

8.0.0

### Description

Installed Liberation 8.0.0; splash screen comes up and settings screen comes up. After selecting DCS World install location and continue; white loading screen and (not responding). I have tried verifying the files fro DCS, removing all traces of Liberation and reinstalling, and removing all trace of liberation 8.0.0 and installing 7.1.0. Nothing seems to fix this issue. 

Log file says no existing save game (haven't gotten far enough to create a save game).
No liberation_nextturn.miz file available
No state.json file available

### Save game and other files

[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/11860728/liberation.log)

**Comment by Starfire13** [comment]
Someone else had the same issue and reported they fixed it by using 7-zip instead of the Windows built-in unzip function to extract the Liberation files.

**Comment by JaalenASF** [comment]
I used WINRAR. I will try 7zip.

**Comment by JaalenASF** [comment]
7zip did not correct the issue

**Comment by Starfire13** [comment]
What's the size of your Liberation folder and how many files are in it?

**Comment by JaalenASF** [comment]
Size 447MB, Size on Disk 453MB, 4,969 Files, 1,427 Folder

**Comment by Starfire13** [comment]
That looks about right. Ultimately, your PC is not letting Liberation load properly for some reason and it's freezing (it's not crashing with an error, just stuck). Unfortunately, this sorta thing can be difficult to help troubleshoot because it is not replicable on our end and is specific to your system.

**Comment by JaalenASF** [comment]
Yeah I get it. I'll just have to figure something out or wait til the next update and see if it will do anything. I really love using Liberation.

**Comment by JaalenASF** [comment]
Here is a hang report if it helps.

[Hang report liberation-main.txt](https://github.com/dcs-liberation/dcs_liberation/files/11861715/Hang.report.liberation-main.txt)

**Comment by JaalenASF** [comment]
Run as administrator solved the issue.
