### ISSUE TITLE
WW2 campaigns using modern Handy Wind bulk carrier for sea transport

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#3039]
### Affected versions

Development build

### Build information

DCS Liberation 9.0.0
Build 5258
Git revision 658a86dff57c411136adbcc4f8a242274c85f994

### Description

This was reported by Spaniel on Discord, and I have confirmed it occurs.

Even on WW2 scenarios, the modern bulk carrier Handy Wind is still placed in the mission for sea transport. It looks out of place.

### Save game and other files

[Handy Wind Bug #5258.zip](https://github.com/dcs-liberation/dcs_liberation/files/11874021/Handy.Wind.Bug.5258.zip)

**Comment by DanAlbert** [comment]
What should be used instead? Not exactly difficult to make that a per-faction decision, but I don't play the WW2 half of DCS so idk what belongs there.

**Comment by DanAlbert** [comment]
(I'll pull this into 8.1.0 because I'm pretty sure it's trivial)

**Comment by Starfire13** [comment]
The LST Mk II is one option.

**Comment by DanAlbert** [comment]
Any idea if that's free or part of the asset pack? I'm actually not sure how to find out.

**Comment by DanAlbert** [comment]
https://github.com/dcs-liberation/dcs_liberation/pull/3045 enables this. I've tested as far as inspecting things in the debugger, but DCS won't fit on this computer so I haven't checked that it works for real yet. Once I've done that and confirmed that the LST Mk II is free, I can fix all the WW2 factions.

**Comment by DanAlbert** [comment]
Had forgotten that this would break save compat, so actually won't be doing this in 8.1.0.

**Comment by DanAlbert** [comment]
This is moddable in faction files by setting `cargo_ship` now (values are the `variant` keys in the ship yamls, defaults to `Handy Wind`).

https://www.digitalcombatsimulator.com/en/shop/modules/wwii_assets_pack/

> **Ships**
> E-boat Schnellboot type S-130 
> Uboat type 7 
> LST Mk2 
> USS Samuel Chase 
> LCVP Higgins

I think the factions that restrict to the free units are stuck with the Handy Wind, but the others can use the LST.

**Comment by Starfire13** [comment]
Could the Samuel Chase be used instead? That's a transport ship. Is that available free? It's not as realistic as using an LST but still better than Handy Wind.

**Comment by DanAlbert** [comment]
No, that's in the list too.

**Comment by Starfire13** [comment]
Oh sorry, reading comprehension fail. I didn't realise that list was OF the ships in the asset pack. 🤦‍♂️
