### ISSUE TITLE
Naval Combat/Control?

### ISSUE THREAD

**Issue by rhoadsy123** [dcs-liberation/dcs_liberation#3040]
Being able to move ships not attached to carrier groups, assign naval strikes, etc.

**Is your feature request related to a problem? Please describe.**
Not really an issue, but the naval units in Lib are basically just floating SAM sites instead of assets.

**Describe the solution you'd like**
Have them be almost like squadrons where you can set up what naval groups there are, where they move to, and assign strikes for them. Would be cool to utilize the naval units in the game a bit more!

**Comment by Starfire13** [comment]
Potentially covered under #565

**Comment by DanAlbert** [comment]
And the rest by https://github.com/dcs-liberation/dcs_liberation/issues/563
