### ISSUE TITLE
collapsable special options in mission generator

### ISSUE THREAD

**Issue by Moguy164** [dcs-liberation/dcs_liberation#3044]
Before filing, please search the issue tracker to see if this feature has already been requested.

If requesting a DCS AI feature, check If reporting a DCS AI bug, check https://github.com/dcs-liberation/dcs_liberation#dcs-bugs.

**Is your feature request related to a problem? Please describe.**
On aircraft with tons of options like the AV-8B (don't know if there are others, but this is the one I am experiencing the issue with, I imagine the F-15E would also be affected) the list stretches out so long that half the payload selection window is hidden below the screen. as can be seen in the following image: 
![image](https://github.com/dcs-liberation/dcs_liberation/assets/48189450/ee21eadf-5502-403d-a94c-878a86e84b76)

**Describe the solution you'd like**
Perhaps having an option to collapse special options would solve the issue, 

**Additional context**

**Comment by DanAlbert** [comment]
Collapsible is quite hard in our UI framework. I can move it to another tab, or I can make the window scrollable (and possibly move that part to the bottom). wdyt?

**Comment by Starfire13** [comment]
I discussed with Kerbo on discord and we both feel scrollable is best.
