### ISSUE TITLE
Waypoint pathing gets messed up when dragging and dropping waypoints. 

### ISSUE THREAD

**Issue by habibivoodoo** [dcs-liberation/dcs_liberation#3055]
### Affected versions

Development build

### Build information

latest preview build 6/27/23

### Description

When creating packages, the flight plan paths get messed up if you drag and drop the waypoints somewhere else. 

### Save game and other files

errors appear in mission planner/setup for liberation.

**Comment by habibivoodoo** [comment]
![image](https://github.com/dcs-liberation/dcs_liberation/assets/116920043/2e07d379-0c40-400b-905e-c9c910af2a25)

**Comment by DanAlbert** [comment]
> errors appear in mission planner/setup for liberation.

What error?

Also, that field is for a save game, which is required. Attach that.

**Comment by DanAlbert** [comment]
(closed until details are provided)
