### ISSUE TITLE
F-15E not human flyable

### ISSUE THREAD

**Issue by Peaches99** [dcs-liberation/dcs_liberation#3063]
### Affected versions

8.0.0

### Build information

DCS Liberation 8.1.0

### Description

When adding the F15E to a mission and making it a player slot. The error "*RuntimeError: Unittype 'F-15E' is not human flyable*" pops up after pressing Take off. 

### Save game and other files (save game required, bugs without saves will be closed)

[syria.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/11911432/syria.liberation.zip)

**Comment by Starfire13** [comment]
Make sure you're selecting the Suite 4+, not the AI F-15E.

**Comment by DanAlbert** [comment]
Yeah, I checked the save. Wrong F-15E.
