### ISSUE TITLE
Only lead aircraft in harpoon anti-ship flights is firing harpoons unless "group attack" is checked in mission editor

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#3068]
### Affected versions

Development build

### Build information

DCS Liberation 9.0.0
Build 5307
Git revision de8d42e3e5205dc669c17a619135405905986924

### Description

I suspect this might be due to some change in DCS as it wasn't happening before, but only the lead aircraft in antiship flights carrying harpoons are firing their harpoons unless "attack group" is checked in the mission editor.

Group Attack unchecked:
![Screenshot 2023-07-03 144336](https://github.com/dcs-liberation/dcs_liberation/assets/72491792/5c448624-a56e-457b-93c6-cfff28459e09)

Group Attack checked:
![Screenshot 2023-07-03 140428](https://github.com/dcs-liberation/dcs_liberation/assets/72491792/12765630-9798-49cc-bf5d-0e6a352ff85f)

You can see here how only the lead aircraft in each flight (the three aircraft in the middle) are firing their harpoons when Group Attack is not checked.
![Screenshot 2023-07-03 143254](https://github.com/dcs-liberation/dcs_liberation/assets/72491792/df8c823f-1d47-4a6b-94f6-a9bd00d8e19c)

This issue occurs with harpoon anti-ship flights using both the Hornet and the B-52.

### Save game and other files (save game required, bugs without saves will be closed)

[Antiship Test.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/11933117/Antiship.Test.liberation.zip)

**Comment by DanAlbert** [comment]
Are you sure this is new behavior? This matches what I'd expect of DCS for that flag. Seems likely that this is off because it's generally not wanted for BAI (because one maverick is plenty, and it's better to hit many targets than one with four mavericks), and the anti ship code was probably just copied from the BAI code...

**Comment by Starfire13** [comment]
They definitely fired more Harpoons previously. I used to regularly kill the Kuz with 16 hornets. This is pretty much impossible now as only one quarter of the hornets fire their harpoons, which all easily get shot down before reaching their target.

The issue isn't that each aircraft is only firing 1 harpoon. It's that one aircraft per flight is firing all 4, and the other 3 aircraft do nothing. It's quite possible this is caused by some change on DCS's end.

**Comment by DanAlbert** [comment]
Weird. I think that was actually a DCS bug.

**Comment by DanAlbert** [comment]
@Starfire13 in case you can beat me to verifying it, https://github.com/dcs-liberation/dcs_liberation/pull/3075 ought to fix this. The miz file looks right but I don't have DCS on this machine so can't do more than that.

**Comment by Starfire13** [comment]
Sure, I'll give it a test-run tonight.

**Comment by Starfire13** [comment]
Ok, it's fixed. Working well.
