### ISSUE TITLE
F-15 not usable

### ISSUE THREAD

**Issue by DevastatorCM** [dcs-liberation/dcs_liberation#3074]
### Affected versions

8.0.0

### Build information

DCS Liberation 8.1.0

### Description

F-15E Strike Eagle (Suite 4+) are not usable by the player although set. When mission starts, player can select the slot but cannot sit inside the cockpit. Player is able to see only the airplane from outside (there is no flight delay message or so).

### Save game and other files (save game required, bugs without saves will be closed)

[rotorhead.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/12001085/rotorhead.liberation.zip)
[liberation_nextturn.zip](https://github.com/dcs-liberation/dcs_liberation/files/12001086/liberation_nextturn.zip)

**Comment by Starfire13** [comment]
I just spent the evening flying about in the Suite 4+, so it is definitely working. You are not using Fast Forward and you have set your start time for 17 mins+. That's why you are not able to get in.

**Comment by DevastatorCM** [comment]
What it has to do at all with "Fast Forward" which is a WIP funcitonality?

 IF that was the case why all other human flights worked out but not the F15s?
There are 3 human flights in the mission (AH64, F16, F15) and they all are set with ASAP schueduling as well as the campaign setting is set for "Automatically generated packages with players are schueduled ASAP)

Now after some further checks I see where the issue is. F15 gots a TOT value, as you said in future 17 minutes although the checkbox ASAP is selected. 
If you unselect that and reselect, it fixes the ASAP. So somehow the initial TOT is set via the code incorrect. My assumtion is, 
1-Liberation generates the flight as an AI flight
2-After pilots are set as human, it calculates the TOT and picks the ASAP flag but it does it incorrect

Workaround is de-select and re-select to fix that but real solution is in backend. Therefor this still looks to me as a BUG

**Comment by Starfire13** [comment]
If you set an AI flight to player, you will have get a slightly longer start up time (as humans may not be as quick as the AI in starting up). The TOT not changing is by design, because if you have set up the flight to coordinate the TOT with other flights before you set it to a player flight, changing the TOT can screw up those plans. Waiting a few minutes is the lesser evil, I think. If you do not wish to wait, you can either toggle off and on the ASAP button as you said, or use Fast Forward (which is what I do).

**Comment by DanAlbert** [comment]
The screen that shows up when you press takeoff explains this.
