### ISSUE TITLE
Liberation 8.1.0 and F-15E missions

### ISSUE THREAD

**Issue by oliverw** [dcs-liberation/dcs_liberation#3080]
### Affected versions

8.1.0

### Description

Is Liberation 8.1.0 supposed to generate packages containing flights of Strike Eagles or do I currently have to create missions manually by right-clicking a potential target? I've advanced to Turn 20 in the screenshot below using "Pass turn", yet no flights have been generated. 

![image](https://github.com/dcs-liberation/dcs_liberation/assets/51688/e671b78e-09ea-4f8d-86ee-634a01004044)

### Save game and other files (save game required, bugs without saves will be closed)

[f-15.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/12040824/f-15.liberation.zip)

**Comment by DanAlbert** [comment]
If you have strike eagles in your air wing and they're the best tool for the job, they get used.

**Comment by oliverw** [comment]
> If you have strike eagles in your air wing and they're the best tool for the job, they get used.

So should I keep advancing turns until they get utilized?

**Comment by DanAlbert** [comment]
If you're just skipping turns that won't make any difference. Your air wing either doesn't have them or the current state of the theater doesn't need them. Skipping turns won't change either of those.

If your air wing doesn't have them, start a new campaign. If they just aren't needed, play the game until they are.

If you really want them used this turn, plan that manually. The auto planner has no reason to pick specific aircraft. It picks the aircraft that were tasked with the missions it needs to accomplish that turn.

**Comment by oliverw** [comment]
> If you're just skipping turns that won't make any difference. Your air wing either doesn't have them or the current state of the theater doesn't need them. Skipping turns won't change either of those.
> 

Thanks. That's why I attached the screenshot showing Senaki-Kolkhi. All the DEAD and CAS Slots appear to be snatched by the Warthog and Viper Squadrons stationed at the base. Perhaps they simply got higher priority.  I checked this for every turn up until Turn 20 and they always got all the missions. The Strike Eagles have been idle the entire time.

> If your air wing doesn't have them, start a new campaign. If they just aren't needed, play the game until they are.
> 
> If you really want them used this turn, plan that manually. The auto planner has no reason to pick specific aircraft. It picks the aircraft that were tasked with the missions it needs to accomplish that turn.

Out of curiosity: So there is no change for some kind of a deep strike mission popping up that would employ them?

**Comment by Starfire13** [comment]
If they don't get those missions on turn 1, they won't get them on turn 20. Skipping turns makes no difference. Vipers are better for DEAD, Hogs are better for CAS. The best plane available gets picked. If you actually run out of either, then Mudhens might get tasked. If you want your Mudhens used on a specific mission, plan it yourself. I always plan all my own flights.

**Comment by oliverw** [comment]
Roger. Thanks @Starfire13 @DanAlbert

**Comment by DanAlbert** [comment]
(slight correction: the squadron with a matching primary task gets priority even over best-choice; the air wing config picks most of this behavior and yours apparently has chosen to not use mudhens)

**Comment by Starfire13** [comment]
Yeah, if you turn on new squadron rules and set a Mudhen squadron to DEAD for primary task, then that means they get priority. But that might also not be what you want if you just want to use Mudhens for longer range deep strikes. Ultimately, Vipers *are* better for DEAD right now (due to limited weapons selection for Mudhen), and if you are wanting to use them only for deep strike missions, plan those manually.

**Comment by DanAlbert** [comment]
> if you turn on new squadron rules

It happens regardless. The primary priority vs rank priority was only an option temporarily while we waited to see if there were any horrible side effects :)

**Comment by Starfire13** [comment]
Oooh gotcha. I thought that was still only a new squadron rules thing. I haven't turned that off at all since I started using it cos it's so good!
