### ISSUE TITLE
(ww2) The A-20G always spawn with an empty loadout.

### ISSUE THREAD

**Issue by Balthyx** [dcs-liberation/dcs_liberation#31]
"A_20G: COMMON_OVERRIDE," is missing from the PLANE_PAYLOAD_OVERRIDES section in db.py (line 745, I guess)

**Comment by Khopa** [comment]
Thanks
This will be fixed for RC10

**Comment by Khopa** [comment]
This should be fixed in 2.0.10

Please re-open if you encounter the issue again.
