### ISSUE TITLE
Lose ground on frontline as well as all your ground units when you captured a base?

### ISSUE THREAD

**Issue by s3-chardonjf** [dcs-liberation/dcs_liberation#310]
I just had this happening to me, I was on Syria Full map, I had captured King Hussein airbase and started a mission with my eyes on 
![image](https://user-images.githubusercontent.com/29724443/98344279-50620280-2013-11eb-8db7-180fa134f2b8.png)

I used Combined Arms and captured that airbase, eliminating all enemy units.

Liberation processed the results, presented somehow 2 base capture events, and when going to next turn, frontline had gone backwards, the enemy base was still enemy, and I had lost all my ground units.

Here is the state.json that gave in this bugged result:
[state.zip](https://github.com/Khopa/dcs_liberation/files/5500087/state.zip)

BEFORE THE MISSION:
![image](https://user-images.githubusercontent.com/29724443/98344660-d67e4900-2013-11eb-8c48-08433d5ea928.png)
Liberation save: [before.zip](https://github.com/Khopa/dcs_liberation/files/5500097/before.zip)

AFTER THE MISSION:
![image](https://user-images.githubusercontent.com/29724443/98344775-0594ba80-2014-11eb-9856-3bdd28802426.png)
Liberation save: [after.zip](https://github.com/Khopa/dcs_liberation/files/5500101/after.zip)

THE MIZ FILE:
[liberation_nextturn.zip](https://github.com/Khopa/dcs_liberation/files/5500104/liberation_nextturn.zip)

Steps to repro:
- Load the liberation save file called "before"
- Run the mission and make sure that you capture the enemy airbase north of King Hussein
- End the mission, and hope for a 100% repro.

**Comment by walterroach** [comment]
The state.json is showing that the base was captured by Blue, then captured again by Red.  If this is not what occurred, then the problem lies either in DCS or in the Liberation script to export those events.  Do you happen to have a track file or TacView of the mission?

**Comment by Khopa** [comment]
Oh I think i understand what is happening.

When liberation see the blue base capture event, it considers that the base has been captured, and auto-move all the units to the newly captured base. 

Then it interprets the red base capture event, and delete all the blue units from the base.

This is a bug.
