### ISSUE TITLE
Add support for new Argentine carrier ARA Veinticinco de Mayo

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#3123]
There is now a new carrier available, the ARA Veinticinco de Mayo. Could potentially be used for Falklands campaigns with the A-4.

**Comment by DanAlbert** [comment]
@Nosajthedevil, you've handled a lot of the data stuff recently, interested?

**Comment by Nosajthedevil** [comment]
Sure. 

Do you know off the top of your head if this is as simple as just creating a data file for it in dcs liberation\resources\units\ships and adding it to a faction (I don't see one for Argentina, I might try to make one eventually), or is there something more to it since it's a carrier?

**Comment by DanAlbert** [comment]
That's a good point, I'll need to check.

**Comment by Nosajthedevil** [comment]
I'll see what was added in the british carrier's pull request. I didn't know this carrier was added to DCS, but I just ran a quick test ( 2 a-4s take off, sink a ship, and land) and so far it looks really well modelled. Has Tacan and ILS in the options, so I'm assuming both are functional. The propellers even turn, which is a silly pet peeve of mine with the forrestal. Hats off to Razbam.

**Comment by Nosajthedevil** [comment]
Looks like I just need to add it as a control point to game/theater/controlpoint.py and we should be good.

**Comment by Nosajthedevil** [comment]
Pull Request #3124 - is in draft for now. pydcs needs to be updated to include the ARA Vienticinco de Mayo

**Comment by Starfire13** [comment]
@Nosajthedevil Oops, it's Veinticinco, not Vienticinco. I realise I got it wrong in the title. Sorry about that. Also, could we add in the HMAS Melbourne under variants? While there are a bunch of other ships in the class, these two were the only ones that carried aircraft we can use in DCS (Skyhawk).

**Comment by Nosajthedevil** [comment]
Will do. Note that it's misspelled in the game as well....

**Comment by Nosajthedevil** [comment]
So to avoid or probably add to confusion - I've including both ARA Veinticinco de Mayo (the correct spelling) and ARA Vienticinco de Mayo (the incorrect spelling that's in the game) as variants along with the Melbourne. I have a pull request in to pydcs to update the ships to include this, once that goes through I'll resubmit this pull request. It won't work until then.

**Comment by DanAlbert** [comment]
Thanks! I've put up a PR to update the changelog as well.
