### ISSUE TITLE
FOB as main CP (control point)

### ISSUE THREAD

**Issue by slubbermand** [dcs-liberation/dcs_liberation#3147]
**Is your feature request related to a problem? Please describe.**

As an avid fan of making custom campaigns, I have come across a limitation in Liberation. It is not possible to set up a campaign without having to designate an airfield for each side. 

Besides the geographical limitations in campaign creation (front is always from one airfield to another, and airfields are static locations), it also limits the creativeness of campaign makers, as it is not possible to make truly asymmetric warfare scenarios, such as rebellions, insurgencies and civil war scenarios. 

It just feels a bit off when your insurgents apparently managed to occupy a huge strategic and logistical asset.

**Describe the solution you'd like**

Make FOB's a CP at the same level as airfields, so that a campaign can be imagined spanning from a blufor FOB to a redfor FOB. When all FOB's on one side has been captured, the campaign ends.

Benefits:
More creative options for campaign makers (nation VS insurgent strongholds, city VS city, S. Ossetia VS Georgia, etc.)
True asymmetric warfare, as seen in most modern conflicts
Small-scale campaigns possible, making them easier for campaign creators to maintain through update cycles
Helo-centric campaigns (should be popular)
Combined Arms-centric campaigns (taaaaanks!)

**Comment by zhexu14** [comment]
A campaign can now be created with FOBs (with FARPs) only. Here's a simple example:

[fob_test.zip](https://github.com/user-attachments/files/17974514/fob_test.zip)

I'll close this issue for now, but if there are more specific enhancements that are needed please open another issue/reopen this issue.
