### ISSUE TITLE
Feature request: Option to disable automatic Blufor flight planning

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#315]
The automatic flight planning for my own aircraft is useless for me as I always delete everything and generate my own packages.

**Comment by currenthill** [comment]
> The automatic flight planning for my own aircraft is useless for me as I always delete everything and generate my own packages.

Good idea! And maybe the possibility to multiselect flight plans to delete them, if you don't want all of them removed.
