### ISSUE TITLE
Frontline ground units can be transferred to carriers via air transport

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#3154]
### Affected versions

Development build

### Build information

DCS Liberation 9.0.0
Build 5470
Git revision eebb1723335cc7353da60bbc4cf819b32f6437d0

### Description

Frontline ground units can be transferred to carriers via air transport, although this would never happen in real life. Doing so doesn't break anything so it's not a priority bug.

![Screenshot 2023-08-20 103833](https://github.com/dcs-liberation/dcs_liberation/assets/72491792/f49265fb-b0dd-4109-83ae-60dc770d08e5)

### Save game and other files (save game required, bugs without saves will be closed)

[Bright Star #5470 Turn 4 (Air Transport to Carrier).liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/12386941/Bright.Star.5470.Turn.4.Air.Transport.to.Carrier.liberation.zip)

**Comment by DanAlbert** [comment]
Not a regression (right?), and I haven't found any time to work on Liberation in the last week so we probably shouldn't wait for this.

**Comment by Starfire13** [comment]
Not a regression and definitely a very minor issue.

**Comment by zhexu14** [comment]
Fixed in latest development build.
