### ISSUE TITLE
Issuer with COOP F14 Rio having inactive briefing button after DCS update  2.8.8.43489

### ISSUE THREAD

**Issue by NicodemusRa** [dcs-liberation/dcs_liberation#3158]
### Affected versions

8.1.0

### Build information

DCS Liberation 8.1.0

### Description

Friend joins mission and gets assigned RIO seat. Show him in the slot. I can hit briefing button and proceed, his briefing button is inoperable, causing him to be stuck in the select role screen. I can proceed forward, all text messages indicate he is indeed in the RIO slot, but he remains unable to hit briefing button, and stuck

### Save game and other files (save game required, bugs without saves will be closed)

[liberation_nextturn.zip](https://github.com/dcs-liberation/dcs_liberation/files/12387330/liberation_nextturn.zip)

**Comment by DanAlbert** [comment]
It's quite unlikely that this is a liberation bug (we have no control over things like this), but there's a small chance that the miz format changed and we're generating something subtly invalid...

**Comment by DanAlbert** [comment]
(Though if that were the case, all missions created with earlier versions of DCS should be similarly broken)

**Comment by NicodemusRa** [comment]
Ya, it's very odd, but other new and old DCS missions work fine for me for some reason.  Should have also added, it's not just occurring on my current campaign, started one from scratch and this behavior's occurred.  Finally, I deleted LIb. and downloaded from scrach, same dice, all of this after this update 2.8.8.43489

Should I add my Lib. save file here as well?

**Comment by DanAlbert** [comment]
I didn't realize you hadn't. Yes. Always. 
![image](https://github.com/dcs-liberation/dcs_liberation/assets/315852/1c3de52c-0ef6-46c8-b372-84602e46f424)

**Comment by NicodemusRa** [comment]
[Uploading Mo and Bj New.liberation.zip…]()

**Comment by Wouter-5824** [comment]
I have the same issue, RIO can not enter the airplane. For me, this issue only appears in liberation missions, not in other missions created with the mission editor.

**Comment by Starfire13** [comment]
> I have the same issue, RIO can not enter the airplane. For me, this issue only appears in liberation missions, not in other missions created with the mission editor.

Is this a problem specific to the F-14 or does it happen with any two-seater aircraft?

**Comment by DanAlbert** [comment]
https://www.reddit.com/r/hoggit/comments/s18io4/issue_with_f14_rio_slot_access_in_multiplayer/ was suggested on discord but OP never followed up. I don't know what it means for the briefing button to be "inoperable" so I don't know if that's describing the same problem or not.

**Comment by NicodemusRa** [comment]
Hello, I am OP, for me my RTO coop buddy could not click the briefing button, and thus could not advance into the mission, all clicks on the button were ignored , for me I saw the issue only in F14

**Comment by Starfire13** [comment]
> for me I saw the issue only in F14

Do you mean you only encountered the issue in the F-14 as that was the only two-seater you had tried, or that other two-seater aircraft you've tried don't have this problem? If the latter, which modules did you try?

**Comment by Wouter-5824** [comment]
Thanks for the quick response guys. I'll run some tests tonight or tomorrow, if my RIO is available. Will follow up.

**Comment by NicodemusRa** [comment]
Only tried f14, did not test other planes

**Comment by RWallaby** [comment]
A player in my Liberation have also run into this issue on the F-15E (though he is not the only F15E WSO just the only one with the issue)

**Comment by Wouter-5824** [comment]
We have done some tests today with interesting results.

Error that occurs is that RIO gets unresponsive Briefing button, preventing him from entering the cockpit, after Pilot accepted his join request.

Test 1: Liberation scenario with 1 player aircraft (rest of the flights AI)
Error occurs, both when RIO join request is accepted before Pilot presses Briefing button and when join request is accepted when the Pilot is already in the cockpit. Workaround suggested (Reddit link) with denying or cancelling RIO join request does not work in both cases.

Test 2: Liberation scenario with 2 player aircraft (rest of the flights AI)
Error occurs, also in both cases as described above.
But, the following workaround worked for us. After error occurs, RIO (still in select role screen) selects different aircraft, does not enter the aircraft, selects RIO seat again, then after Pilot accepts join request, RIO successfully enters cockpit.

Test 3: SPQR Dynamic Modern PvP Server
Error occurs here also, same as described above. 
And also the workaround described in Test 2 worked and RIO successfully enters cockpit.

Test 4: Own multiplayer scenario from mission editor
Error does not occur and RIO directly enters cockpit.

My conclusion is that this is not a Liberation specific error. But it is still strange that this does not occur with our own multiplayer scenario. Maybe loading and resaving a liberation mission in the mission editor is a next test?
Also testing this with other multicrew aircraft is still on the list to do.

**Comment by DanAlbert** [comment]
> But it is still strange that this does not occur with our own multiplayer scenario.

Liberation missions are huge compared to anything you'd make by hand in the ME. I wouldn't be particularly surprised if a lot of the "only in Liberation" bugs are actually "only in big missions" DCS bugs.

Feel free to continue discussing/testing here, but I'm closing this as it looks like there isn't anything we can fix here. It's easy to reopen if further testing finds otherwise. Thanks for the help 👍
