### ISSUE TITLE
Feature request: Option to limit number of redfor ground forces as they can really kill framerates

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#316]
I'm already barely able to play at 15 to 20 fps with only 12 ground units on my side. Only appears to affect modern scenarios. I get nice framerates on WW2 scenarios.

**Comment by Mustang-25** [comment]
should we close this one out? YOu can kinda limit ground forces with the new ammo depot mechanic.

**Comment by DanAlbert** [comment]
Making the cap-per-depot adjustable is probably still worthwhile.

**Comment by DanAlbert** [comment]
Does this matter anymore, or did multhreading fix this? I've had no issues.

**Comment by Starfire13** [comment]
Yeah, no longer relevant as multithreading has pretty much gotten rid of performance issues.
