### ISSUE TITLE
Unable to load save file, AttributeError: 'Squadron' object has no attribute 'settings'

### ISSUE THREAD

**Issue by JdCR927** [dcs-liberation/dcs_liberation#3166]
### Affected versions

8.1.0

### Build information

DCS Liberation 8.1.0

### - **Describe the bug**

Cannot load the save file, when reviewing the log as to what caused the error, it determines it to be:

### - **What went wrong?**

 "Traceback (most recent call last):
  File "qt_ui\windows\QLiberationWindow.py", line 355, in openFile
  File "game\persistence\savemanager.py", line 101, in load_player_save
  File "game\persistence\savegamebundle.py", line 77, in load_player
  File "game\persistence\savegamebundle.py", line 94, in _load_from
  File "game\ato\flight.py", line 109, in __setstate__
AttributeError: 'Squadron' object has no attribute 'settings'"

It may have something to do with me going haywire and using invincibility and unlimited ammo, and fuel to destroy that damned Kuznetsov.

### - **What did you expect to happen instead?**

For it to load the save file, I guess?

### - **What steps should we take to reproduce the error?**

Try to load the save file.

### - **Error dialog**

None whatsoever.

### Save game and other files (save game required, bugs without saves will be closed)

[Spain.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/12565787/Spain.liberation.zip)
[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/12565788/liberation.log)
[state.json.zip](https://github.com/dcs-liberation/dcs_liberation/files/12565792/state.json.zip)
[liberation_nextturn.miz.zip](https://github.com/dcs-liberation/dcs_liberation/files/12565797/liberation_nextturn.miz.zip)

**Comment by DanAlbert** [comment]
This kind of thing is pretty much always loading an old save in a new version of liberation (or vice versa). Other than that, save corruption.

**Comment by JdCR927** [comment]
Well I'll be damned, definetely didn't change version unless it does so automatically, other than that I'll be sure to keep back-ups of the saves just in case the save file decides to do some funny business while I'm not watching, thanks a lot mate.

**Comment by Starfire13** [comment]
> Well I'll be damned, definetely didn't change version unless it does so automatically, other than that I'll be sure to keep back-ups of the saves just in case the save file decides to do some funny business while I'm not watching, thanks a lot mate.

I typically will create a separate save file for each turn in a campaign. That said, that's just me playing it safe because save file corruption is really quite rare. I haven't run into it myself, and I've been using Liberation for years.
