### ISSUE TITLE
Mossie loadout with rockets are no longer working

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#3171]
### Affected versions

8.1.0, Development build

### Build information

DCS Liberation 9.0.0
Build 5502
Git revision e43874e55338c1c3f23c3f1724715962c5adab81

### Description

It appears that at some point, Mosquito loadouts with rockets stopped working again. I can see that back in Jan 2022, Ghosti confirmed that it was working, but now Liberation will no longer load loadouts with blank CLSIDs (which DCS puts in to prevent ordnance being placed on certain pylons if rockets are being carried.

https://github.com/dcs-liberation/dcs_liberation/pull/1926/commits/ff1c6fb6a7d58869a90939d9a23c216a00361c57

### Save game and other files (save game required, bugs without saves will be closed)

This save file contains a single planned mossie CAS flight. You can see that the Liberation CAS loadout is not available on the list.

[Mossie Test #5502.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/12683960/Mossie.Test.5502.liberation.zip)

**Comment by Starfire13** [comment]
Linking this here as it's related. https://github.com/dcs-liberation/dcs_liberation/issues/2000

**Comment by DanAlbert** [comment]
I don't really know what I'm supposed to do with this save. It loads fine and generates fine. If I try equipping the `400 lb GP Mk.V*2, 500 lb GP Short tail*2` loadout it does emit a similar error, but those aren't rockets so I'm not really sure if that's the same error or not. If that's the same problem, https://github.com/dcs-liberation/dcs_liberation/pull/3205 fixes it.

**Comment by Starfire13** [comment]
The mission will generate, but the  mossies with rockets will have empty loadouts. At least, that was the case in 2.9. Are you seeing different behaviour now?

**Comment by DanAlbert** [comment]
The Mosquito in that save doesn't have a loadout at all. This error will prevent that loadout from ever making it into the save, so repro steps are needed here as well. Which loadout were you expecting to have rockets?

**Comment by Starfire13** [comment]
The default loadout for whatever mission type that Mossie is on.

**Comment by DanAlbert** [comment]
Got it. Not fixed then.
