### ISSUE TITLE
Definition of patrol duration by tanker

### ISSUE THREAD

**Issue by Maveric33** [dcs-liberation/dcs_liberation#3183]
Hello,
I would like to know if it would be possible to modify the duration of the tanker patrol either by removing the stop condition that ends it without having to go through the ME or in the flight settings define the duration.

We often find that the tanker stops its patrol when we need it.

Thanks in advance.

**Comment by DanAlbert** [comment]
It isn't. All "I'd like to customize this part of the flight plan" issues are https://github.com/dcs-liberation/dcs_liberation/issues/270 (you don't need to mention this issue specifically on that bug).
