### ISSUE TITLE
Tanker and JTAC no longer responding if we have respawned

### ISSUE THREAD

**Issue by Maveric33** [dcs-liberation/dcs_liberation#3184]
### Affected versions

8.1.0

### Build information

DCS Liberation 8.1.0

### Description

Hello,

We've noticed on several occasions that when we use our aircraft's respawn function, the tanker and JTAC no longer answer us on the radio.

Example: 
I enter the cockpit and realize it's not my plane, so I perform a "Role selection" => "Spectator" => "Plane".
Or
I take off and I'm shot down, I take the same plane back, switching to "Spectator" and then back to "Aircraft".

When this has been done once, if I try after X number of flights to contact Tanker or the JTAC, they will never answer the radio again.

At this stage I haven't found any reason for this, apart from a possible trigger that activates only once, and when the aircraft is reset it doesn't reactivate and I no longer exist for these AI entities.

We've obviously checked the radios and frequencies, and all are correct.

This is not related to any particular campaign.

Could you please give us an idea of the problem?

Best Regards

### Save game and other files (save game required, bugs without saves will be closed)

[File.zip](https://github.com/dcs-liberation/dcs_liberation/files/12796921/File.zip)
[(v8.1) Up the Coats -CAU v1 Started.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/12796926/v8.1.Up.the.Coats.-CAU.v1.Started.liberation.zip)
[dcs.log](https://github.com/dcs-liberation/dcs_liberation/files/12796931/dcs.log)

**Comment by DanAlbert** [comment]
Liberation has no control over whether the AI talks to you or not. That's a DCS thing.

But I should also mention that respawning will just plain break Liberation. Death tracking does not work if you reuse a slot.

**Comment by DanAlbert** [comment]
> At this stage I haven't found any reason for this, apart from a possible trigger that activates only once, and when the aircraft is reset it doesn't reactivate and I no longer exist for these AI entities.

It's not that, fwiw. That's not how tankers work in DCS. There are no triggers involved, it's just a task attached to the tanker itself. There's no connection between the tanker and other planes in the mission.

**Comment by Maveric33** [comment]
Hello,

Thank you for your feedback.

I can confirm that respawn does consume aircraft and is taken into account in the release.

For example, if I break 3xF18 and end the mission, it does indeed show 3xF18 lost.

**Comment by DanAlbert** [comment]
And if you only had two, you're now in a broken state. The game might continue fine, might crash, or it might corrupt your save.

**Comment by Maveric33** [comment]
Thx for your becareful
