### ISSUE TITLE
Editing WP altitudes is off by one and shifts all previous altitudes up

### ISSUE THREAD

**Issue by ali4000** [dcs-liberation/dcs_liberation#3188]
### Affected versions

Development build

### Build information

Present in 9.0.0-preview from git, but present since quite long

### Description

This is a long-standing bug that I haven't gotten around to figure out the exact pattern to until now.
What happens is, when you edit a waypoint altitude, the GUI looks right at first, but if you close the waypoint window and re-open it, you will see that the edit is now placed on the wp above the one you edited, and all waypoint altitudes have been shifted one step up in the list.

Graphic example with steps to reproduce from an all new campaign:

We set up a flight to attack an EWR FERRET with a pair of Vipers. The default waypoints end up looking like:
![wp_before](https://github.com/dcs-liberation/dcs_liberation/assets/48153528/49f12495-8823-4066-86de-b258a8811622)

Weather is bad with rain and heavily overcast with cloud base at 8812ft, so we want to make sure our flight approaches the target at 8000ft so they will see and attack the target. To be sure I want to set them to 8000ft already at the join wp. It looks correct in the GUI at first:
![wp_edit_start](https://github.com/dcs-liberation/dcs_liberation/assets/48153528/21cc09b0-71de-4c06-9443-2607609b442f)

But when we close the window and look at the map bubbles, we see that the altitude ended up on the preceeding waypoint instead, and when we open up the waypoint window again the other altitudes are also wrong:
![wp_edit_result](https://github.com/dcs-liberation/dcs_liberation/assets/48153528/604d4b8b-da9a-41a8-8aa2-dd118c3c63e8)
So what has _actually_ happened is that when a waypoint's altitude has been modified, the entire _column_ of altitudes is shifted one step up in the list, filling in with zeroes at the end.
(We ignore for now that 8000ft is somehow rounded to 7999ft, I assume it's a float->int rounding error and doesn't usually happen)

The "funny" thing is that this enables us to temporarily work around the problem simply by filling in all desired altitudes by repeatedly editing e.g. the "Land" waypoint (any waypoint where all the remaining wps should be zero anyway), as confirmed here; let's say we want to edit "Join" and "Ingress" to 8000ft. So we enter all desired waypoint altitudes from the top, one at a time, on the "Land" waypoint, closing the window between each edit and re-opening it to enter the next. First off is the "Hold" altitude of 25k:
![wp_edit0](https://github.com/dcs-liberation/dcs_liberation/assets/48153528/7a065db2-7e96-48a3-b217-16417abc371e)

When we reopen it, all altitudes have shifted up:
![wp_edit1](https://github.com/dcs-liberation/dcs_liberation/assets/48153528/63f7f71f-90a5-48bf-99e7-83e1f261ab92)
![wp_edit2](https://github.com/dcs-liberation/dcs_liberation/assets/48153528/e7ce50dd-7562-4af1-9776-f3cf47c9fcaa)

Next, we enter "8000" on the "Land" waypoint and re-open the waypoint window:
![wp_edit3](https://github.com/dcs-liberation/dcs_liberation/assets/48153528/8e8ef864-3847-419b-a695-cbcfe2f99d6f)

We repeat the process until the end, adding 18k for the "Split" and "Refuel" waypoints, and upon reopening the window, we have the desired waypoint altitude list:
![wp_edit4](https://github.com/dcs-liberation/dcs_liberation/assets/48153528/64537253-b9a9-4a56-8358-e4a1757bbfed)

### Save game and other files (save game required, bugs without saves will be closed)

UI bug, no actual savegame required to reproduce, but here is the fresh example from which the first images were taken:

[wp_bug.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/12802814/wp_bug.liberation.zip)

**Comment by Starfire13** [comment]
Possibly an unintended consequence of this fix? https://github.com/dcs-liberation/dcs_liberation/issues/3037

**Comment by ali4000** [comment]
Possibly related, but ISTR seeing this quite some time ago, so I think this has been present for more than a major release version. But I rarely muck around with altitudes, so I could also be entirely wrong. :-)

I never got around to file a report the first time I noticed it because I couldn't quite figure out what the actual pattern was for the other messed up waypoints, but now I really wanted to not have to edit out bad weather in the ME so I started looking more closely at what the heck is going on with all the other altitudes, and it turns out it's quite simple, it just looks confusing when all waypoints become wrong.

**Comment by Starfire13** [comment]
> Possibly related, but ISTR seeing this quite some time ago, so I think this has been present for more than a major release version. But I rarely muck around with altitudes, so I could also be entirely wrong. :-)

Changing waypoint altitude in the Edit Flight window was only implemented on June 16. https://github.com/dcs-liberation/dcs_liberation/pull/2981

**Comment by DanAlbert** [comment]
That field is editable? 🤯
