### ISSUE TITLE
Adding waypoints throws AssertionError on Take Off

### ISSUE THREAD

**Issue by ali4000** [dcs-liberation/dcs_liberation#3189]
### Affected versions

Development build

### Build information

Present in 9.0.0-preview from git as of Oct 3

### Description

Simply adding a waypoint to e.g. a player-only flight will cause Liberation to throw an AssertionError on Take off:

![wp_added](https://github.com/dcs-liberation/dcs_liberation/assets/48153528/c77c075a-3f1d-4906-86d7-740b393638c9)

![wp_assertion](https://github.com/dcs-liberation/dcs_liberation/assets/48153528/8a035270-65e6-4c47-af9c-01992a775fa5)

The order of waypoints doesn't appear to be immediately relevant - I tried e.g. first deleting "Land" and "Bullseye" and then adding an RTB waypoint last, so that the sequence would make sense (even if it was a player only flight), but the same error occurs regardless.

### Save game and other files (save game required, bugs without saves will be closed)

Trivial example of a single waypoint added attached:

[wp_added_error.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/12806947/wp_added_error.liberation.zip)

**Comment by DanAlbert** [comment]
In case anyone beats me to this, the problem appears to be that the flight plan isn't degrading from whatever this is to custom.

**Comment by DanAlbert** [comment]
Actually no, it did degrade, the problem is that the hold point still has a hold task with a reference to the old flight plan. I'm going to have to think a bit on how that ought to be cleaned up.

**Comment by DanAlbert** [comment]
(if nothing else, purging all waypoint tasks/options when degrading the flight plan would restore the old behavior)
