### ISSUE TITLE
Player pilot not always shown as player in create flight dialogue

### ISSUE THREAD

**Issue by ali4000** [dcs-liberation/dcs_liberation#3192]
### Affected versions

Development build

### Build information

Present in 9.0.0-preview from git as of Oct 3

### Description

The "create new flight" package planner window has a little corner case refresh problem when the auto-planner is active:

If you plan a flight, mark the first pilot as player and close the flight window, then close and cancel the package, and then try to plan an identical flight/package again, the same pilot will be first in the list again, but without the player checkmark. If you then click the arrow to reduce the number of planes in the flight, the checkmark appears when the pilot list is refreshed. For this to happen, auto planning must not be disabled, otherwise player pilots are never suggested for new flights. It doesn't matter if the original flight is cancelled immediately before saving the package, or the package saved first and then removed, before trying to replan the flight. As long as the converted pilot appears again in the new flight window, it happens. With auto planning set to "No preference", it appears to happen consistently. I haven't seen a correponding issue with opening the pilot list in the flight window of an existing package, only the "new flight" creation window.

### Save game and other files (save game required, bugs without saves will be closed)

UI bug, no savegame needed, but here's the example used:
[player_pilot_bug.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/12817434/player_pilot_bug.liberation.zip)

**Comment by DanAlbert** [comment]
I can't repro. Using your save I:

1. Right click RABBIT
2. Add flight
3. Check "Player" next to Brandon Jacobs
4. Click X to close the flight window
5. Click X to close the package window
6. Right click RABBIT
7. Add flight

Brandon Jacobs is marked as a player.

**Comment by ali4000** [comment]
I just tried as well on 376c1137d7b5465d2e673d0e4785f9f5689f76c2 and I cannot reproduce it either, so something must've fixed this along the way in the mean time.

**Comment by Starfire13** [comment]
> I just tried as well on [376c113](https://github.com/dcs-liberation/dcs_liberation/commit/376c1137d7b5465d2e673d0e4785f9f5689f76c2) and I cannot reproduce it either, so something must've fixed this along the way in the mean time.

The repro would have been attempted on the specific build you reported the bug in, so it's not because it got fixed along the way.

**Comment by DanAlbert** [comment]
I tried on today's HEAD. I didn't back up to the old build.
