### ISSUE TITLE
Auto-planned CAP flights not generating correctly if fast forward is used

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#3195]
### Affected versions

Development build

### Build information

DCS Liberation 9.0.0
Build 5508
Git revision 69ec9adec763bf734623fbd733bec2fa2e065dc3

### Description

This was quite a mystifying bug and took a while to figure out how to replicate. It was Maveric on the Discord who first brought it to our attention.

If a CAP flight is generated by the autoplanner and fast forward is turned on (meaning the flight gets generated in mid-air), it is not editable in the mission editor. You can't click on it properly, not even in the unit list. It shows up like this:

![Screenshot 2023-10-15 163420](https://github.com/dcs-liberation/dcs_liberation/assets/72491792/aa042ebd-c969-41cf-8240-4edda457ae80)

As far as I can tell, this only appears to affect CAP flights. Contrast this with a non-CAP flight in the same mission which shows up correctly.

![Screenshot 2023-10-15 163442](https://github.com/dcs-liberation/dcs_liberation/assets/72491792/233a472e-9f1f-41a1-870b-b79de883938d)

However, if I plan the CAP flights myself rather than letting the autoplanner do it, they work fine (which I'm guessing is the reason I've never noticed this before, since I do all my flight planning myself).

![Screenshot 2023-10-15 164812](https://github.com/dcs-liberation/dcs_liberation/assets/72491792/90b6d901-d7bc-4ea2-accc-ae5d0c52da32)

One clue as to the cause is that in the bugged flights, the GS checkbox is not ticked, whereas they all are in the non-bugged flights.

### Save game and other files (save game required, bugs without saves will be closed)

Example with autoplanned flights exhibiting the problem:
[Maveric Test 2 Auto Plan #5508.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/12908736/Maveric.Test.2.Auto.Plan.5508.liberation.zip)

I then deleted the autoplanned flights and planned some of my own. Problem is gone:
[Maveric Test 3 Self Plan #5508.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/12908737/Maveric.Test.3.Self.Plan.5508.liberation.zip)

And here are the generated .miz files, both the autoplanned version with the bug and the self planned version without:
[liberation_nextturn.zip](https://github.com/dcs-liberation/dcs_liberation/files/12908739/liberation_nextturn.zip)

**Comment by Starfire13** [comment]
FYI, Maveric says he's encountered the same problem with tanker flights as well as CAP. I haven't had any success replicating it with tanker flights, but I imagine the root cause (whatever it is) would probably be the same.

**Comment by DanAlbert** [comment]
Not likely a regression and is tied to an experimental feature... but points to a problem in our miz serialization that might have symptoms elsewhere, so I'm keeping this in 9 for the time being.

**Comment by DanAlbert** [comment]
I don't think auto/manual planning has anything to do with it. If I delete the Hatzerim BARCAP and replace it with the identical aircraft (and do not delete other flights), I get the same result. Your manually planned turn switch to an F-15C, which travels at different speeds than the M-2000, and you deleted several other flights, which changed the time at which the mission was generated (9:20 for the original, 9:13:26 for your self-planned turn). This is much more likely something to do with where the BARCAP is in its flight plan at the time of generation.

**Comment by DanAlbert** [comment]
It definitely is the lack of the ground speed lock on waypoint 0. If I fix that by hand in the miz and reload it works. DCS has some complex rules around when ground speed and time need to/can be locked, but I think "waypoint 0 must always lock both" is true (maybe not for anything late activation?)
