### ISSUE TITLE
OPFOR does not plan CAS flights

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#3197]
### Affected versions

Development build

### Build information

DCS Liberation 9.0.0
Build 5533
Git revision 32b379308225c05a92d666d7768a72fd6c9a6672

### Description

I've tried this on every single one of my campaigns (apart from Noisy Cricket that has no frontline) and it appears OPFOR will no longer plan CAS flights even though OWNFOR does so consistently. OPFOR does have a dedicated CAS squadron. It's just not being used.

Looking at the log, CAS planning is only showing up for OWNFOR.

![Screenshot 2023-10-16 094241](https://github.com/dcs-liberation/dcs_liberation/assets/72491792/60ae4a7f-384d-4a48-ab02-5c5174e974db)

### Save game and other files (save game required, bugs without saves will be closed)

[No enemy CAS #5533.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/12910827/No.enemy.CAS.5533.liberation.zip)

**Comment by DanAlbert** [comment]
There are no blue units at the front line. Red CAS has no targets, so it isn't planned. If I buy a bunch of tanks at Hatzerim, red will plan CAS:

```
2023-10-20 11:57:27,727 :: root :: DEBUG :: red CAS planning 1 times took 0:00:00.042010 (0:00:00.042010 average)
```

This happens whenever the AI commander chooses a "breakthrough attack". That happens whenever there are no longer any garrison objectives within capture distance of the opposing base, and when there's at least a 2x advantage in front line strength. The rationale is that if the front line battle is going to be that one sided that turn, there's a good chance the fight will be over before CAS even shows up.

Could argue over the tuning of those rules, but this is the expected behavior.

**Comment by Starfire13** [comment]
Ah, gotcha. I always assumed CAS was like CAP and got planned regardless. Well, problem solved. Thanks.

Regarding breakthrough attack, does this only apply if the AI commander selects it? If say, I manually set my own frontline forces to breakthrough, would the auto planner plan a CAS flight?

That said, I rarely use breakthrough. I usually set frontline forces manually to defensive so that they don't kill all the enemy ground units before CAS arrives.

**Comment by DanAlbert** [comment]
BARCAP yes (though that's just a tuning thing that was never done, there's no need to plan BARCAP when the enemy has no planes), CAS no.

**Comment by DanAlbert** [comment]
> That said, I rarely use breakthrough

The AI does though.

**Comment by DanAlbert** [comment]
> Regarding breakthrough attack, does this only apply if the AI commander selects it? If say, I manually set my own frontline forces to breakthrough, would the auto planner plan a CAS flight?

Auto-planning happens before you can make any changes in the UI. Changing the stance after won't replan your ATO.

**Comment by Starfire13** [comment]
Btw, this is the save from Reddog who first reported this issue (it's an 8.1 release build save). It's a custom campaign he made and does have units on the frontline, and I can't replicate the issue with my campaigns. I suspect it's because he's made the distance between control points very short (only 14 miles for the two with a frontline in between). Potentially due to threat zones?

[LibTurn1.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/13062042/LibTurn1.liberation.zip)

**Comment by DanAlbert** [comment]
> 2023-10-21 21:47:14,730 :: root :: DEBUG :: Red: not enough aircraft in range for Front line Rene Mouawad/FOB DANCER capable of: TARCAP

**Comment by Starfire13** [comment]
Ah. So if there are no aircraft available for frontline TARCAP, then no CAS will be planned?

**Comment by DanAlbert** [comment]
Correct.

**Comment by DanAlbert** [comment]
(that's true for every type of package: if it can't plan the whole package it will not)
