### ISSUE TITLE
SEAD/DEAD 

### ISSUE THREAD

**Issue by dzambrano10** [dcs-liberation/dcs_liberation#320]
The SEAD flights now have an attack task, however, the flights still ignore the task and fly from Ingress to Egress and RTB.

**Comment by walterroach** [comment]
I saw this tonight when the package target was static buildings.  It worked correctly when target was an air defense site.

**Comment by DanAlbert** [comment]
That's expected, right? Or were there SAMs in range that should have been engaged?

**Comment by walterroach** [comment]
There were SAMs in range for me.  May be a different issue than @dzambrano10 posted, as in my case on closer inspection it appears the static unit wasn't found by the ingress sead builder method, and there was no "Search and Engage in Zone" task set on the ingress waypoint.

**Comment by DanAlbert** [comment]
Seems to be fixed on the latest build. Created a strike package against a building target and included a SEAD flight. I see the Search Then Engage in Zone task for the SEAD flight's ingress point.
