### ISSUE TITLE
AI unlimited fuel option

### ISSUE THREAD

**Issue by DanAlbert** [dcs-liberation/dcs_liberation#3201]
DCS 2.9.0.46801 implemented https://forum.dcs.world/topic/330452-per-group-or-per-aircraft-unlimited-fuel-option/

> NEW: Advanced Waypoint Action for Unlimited Fuel Option for AI. Please note the task must be at the top of Advanced Waypoint Actions list to make sure it works properly.

Which means we can now add an option to set AI aircraft to have unlimited fuel. I can't think of any time the AI running out of gas has made Liberation more fun, so it'll probably be the default, but I expect it's easy enough to make it an option for players that don't want it.

We should also check on afterburner behavior when we do this, I can never remember where we landed on that,. If we still have it off for fuel reasons we should re-enable it for unstupiding-the-AI reasons.

**Comment by Starfire13** [comment]
Afterburner restriction was trialed but the AI still flew like it could use afterburner and it led to crashes. So that got reverted. That said, afterburner use hasn't been as much of a problem since that waypoint speed issue got fixed.
