### ISSUE TITLE
Munitions restrictions as part of Factions or Squadrons

### ISSUE THREAD

**Issue by 7e21** [dcs-liberation/dcs_liberation#3204]
**Is your feature request related to a problem? Please describe.**
Especially with the new Sinai map there is many instances where certain weapon restrictions would apply that aren't related to the date.
As an example: Egypt was never allowed to purchase amraams and only uses the aim-9 on their F16s, While Isreali F16s in the same year would have them.

**Describe the solution you'd like**
Munitions restriction and/or Loadouts as part of the faction or squadron yaml.

**Comment by zhexu14** [comment]
Closing as the enhancement is implemented in the latest development version.
