### ISSUE TITLE
ACLS issue as of DCS 2.9 with F-14

### ISSUE THREAD

**Issue by JeffreyCor** [dcs-liberation/dcs_liberation#3222]
### Affected versions

8.1.0

### Description

Specifically testing in the F-14, ACLS is not working due to datalink frequency issue. Liberation sets carrier datalink at 226. However as of 2.9 it appears datalink frequencies cannot go lower then 300. Jester setting datalink to carrier set to 326 not 226 and no ACLS signal was received. Changed carrier datalink to 326 in the mission editor for testing and ACLS worked properly. 
![wrong dl frequency](https://github.com/dcs-liberation/dcs_liberation/assets/7409930/64e0fa10-19e7-4c81-acc6-a5ed0d88ade0)

### Save game and other files (save game required, bugs without saves will be closed)

[1991 Gulf War Navy.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/13197458/1991.Gulf.War.Navy.liberation.zip)

**Comment by DanAlbert** [comment]
If memory serves, the F-14's datalink doesn't even have a knob for the first digit? This was probably somewhat broken always, but jester worked around it by accident?

I don't think we actually set the datalink frequency at all, so it might be that the defaults are just incompatible.

**Comment by JeffreyCor** [comment]
Carriers don't have datalink set without it being set in the mission editor only tacan. Default for adding Link 4 datalink is 336.0 so something has to be getting specified somewhere. I agree it's very likely DCS/Jester was just compensating before. Maybe something that's been in there and long forgotten creeping up to goof things.

**Comment by DanAlbert** [comment]
Funny enough the PR that added that had a note asking whether the generic UHF allocator was the right way to do that :) https://github.com/dcs-liberation/dcs_liberation/pull/2196

https://www.heatblur.se/F-14Manual/general.html#link-4-controls

> The allowable frequency range is 300.0 MHz to 324.9 MHz.

**Comment by DanAlbert** [comment]
[Updated test case for current development builds](https://github.com/dcs-liberation/dcs_liberation/files/13233098/link4.liberation.zip)

**Comment by DanAlbert** [comment]
And https://github.com/dcs-liberation/dcs_liberation/pull/3229 is the fix.
