### ISSUE TITLE
fog of war failing

### ISSUE THREAD

**Issue by Tinchus2009** [dcs-liberation/dcs_liberation#3226]
### Affected versions

8.1.0

### Build information

DCS Liberation 8.1.0

### Description

This is happening with version 2-9 beta multithread at least. Before this fog of war showed in F10 map enemy units detected by any means by friendly units.
Now that is not happening: surface units in the front are completly invisible to F10 map. I can see my tanks firing at them, and and they are not shown in the map. Also the reaper is lasing targets and those targets are invisble too in the map.
Gound unit WAY FAR from the front line are shown (they shouldnt)

### Save game and other files (save game required, bugs without saves will be closed)

[state.json](https://github.com/dcs-liberation/dcs_liberation/files/13221634/state.json)
[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/13221635/liberation.log)

**Comment by DanAlbert** [comment]
> save game required, bugs without saves will be closed
