### ISSUE TITLE
Increase default height for Air Wing Configuration window

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#3232]
The Air Wing Configuration window has to be manually resized each time a new campaign is generated in order to see its full contents. It would be good if it could have a larger default window size so it doesn't have to be resized each time.

This is what it currently looks like:
![Screenshot 2023-11-05 144556](https://github.com/dcs-liberation/dcs_liberation/assets/72491792/07038c01-03f9-4658-88ed-caa65c220d8f)

This is what it has to be resized to in order to view all contents:
![Screenshot 2023-11-05 144629](https://github.com/dcs-liberation/dcs_liberation/assets/72491792/a5507de2-bc97-4575-85fc-85a4bc22ba91)

**Comment by zhexu14** [comment]
Closing this issue as it has been resolved in the development build.
