### ISSUE TITLE
Making/Deleting waypoints is not working right.

### ISSUE THREAD

**Issue by MattyMartholomew** [dcs-liberation/dcs_liberation#3234]
### Affected versions

8.1.0

### Build information

DCS Liberation 8.1.0

### Description

When i go to add/remove a waypoint it dosn't act as intended, replacing the deleted waypoint with another random waypoint or deleting the wrong waypoint until all of them are gone 

### Save game and other files (save game required, bugs without saves will be closed)

[liberation_nextturn.zip](https://github.com/dcs-liberation/dcs_liberation/files/13291330/liberation_nextturn.zip)

**Comment by Starfire13** [comment]
I think this is already fixed in #3188.
