### ISSUE TITLE
AI is not atacking with correct weapon

### ISSUE THREAD

**Issue by Tinchus2009** [dcs-liberation/dcs_liberation#3252]
### Affected versions

9.0.0

### Build information

DCS Liberation 9.0.0

### Description

AI flights , some of them, atack with incorrect weapon. For example if oyu assing a CAS JF17, it will have laser guided weapons on the loadout, but AI will always atack using ONLY canons. Same for CAS missions using S30 or 33: they have rockets, instead of using them, they go first for bombs, and if they dont have it, guns.

### Save game and other files (save game required, bugs without saves will be closed)

[ultima.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/13402109/ultima.liberation.zip)
[dcs.log](https://github.com/dcs-liberation/dcs_liberation/files/13402117/dcs.log)
[state.json](https://github.com/dcs-liberation/dcs_liberation/files/13402121/state.json)

**Comment by Starfire13** [comment]
Liberation doesn't exert any control over what weapons CAS flights use. That is completely up to the DCS AI. We can GIVE them the weapons, whether they want to use them is up to them.

**Comment by DanAlbert** [comment]
There is a small amount of control, but it'd be odd for it to not work for just this aircraft. Worth looking at the task to make sure it didn't for some reason get set up as gun-only, but I expect @Starfire13 is right and this is a DCS AI problem.

**Comment by Starfire13** [comment]
That's easy enough to test. I'll try it out and report back.

Edit: I am also seeing the problem with JF-17s not using smart weapons, but as mentioned below, this is not a Liberation issue but a DCS issue.

**Comment by Starfire13** [comment]
There is actually no control over weapon type for CAS. It's just a search then engage in zone command. This is precisely why mixed loadouts work fine with CAS. It is completely up to DCS to determine what weapon to use.

The issue with JF-17s not using smart weapons was already reported to Deka, who said it is an ED problem with their handling of third party targeting pods. https://forum.dcs.world/topic/295776-reported-jf-17-ai-unable-to-utilise-smart-weapons/

Also, if you are using laser-guided rockets, they are also currently bugged. https://forum.dcs.world/topic/337803-ai-jf-17-will-not-attack-with-brm-laser-guided-rockets-even-when-equipped-with-wmd7-targeting-pod/

**Comment by DanAlbert** [comment]
Oh really? All the other task types offer that option, I thought Search and Engage or whatever it is did too. Guess I remembered wrong. Thanks for checking!
