### ISSUE TITLE
"Abort Mission/Accept Results" results in an error message every time.

### ISSUE THREAD

**Issue by cj3273** [dcs-liberation/dcs_liberation#3255]
### Affected versions

9.0.0

### Build information

DCS Liberation 9.0.0

### Description

I installed the newest release version of liberation, started a new campaign, set everything up, and realized I set some of the package times wrong. When I clicked "abort mission" in order to change them, it gave me this error message.
![DCS Liberation - v9 0 0 - Campaign1 11_19_2023 7_14_16 PM](https://github.com/dcs-liberation/dcs_liberation/assets/151482234/cb9c018f-a49c-4419-a4fc-3c9b5962234b)

I closed liberation with the task manager because when I tried to close the window, the error message just reappeared, then tried the same with a different campaign, and the same thing happened. I uninstalled/reinstalled liberation, and still got the same results. When I tried to fly the mission, the usual "accept results button" doesn't appear after the mission is over.

### Save game and other files (save game required, bugs without saves will be closed)

[Campaign1.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/13405430/Campaign1.liberation.zip)
[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/13405433/liberation.log)
[state.json](https://github.com/dcs-liberation/dcs_liberation/files/13405441/state.json)
[dcs.log](https://github.com/dcs-liberation/dcs_liberation/files/13405448/dcs.log)

**Comment by Starfire13** [comment]
I cannot open the campaign save you attached. It appears to be corrupted.

I'd like you to follow the steps below to troubleshoot.
1. Start up Liberation
2. Start a new campaign, pick Operation Vectron's Claw
3. Don't change anything. Just keep clicking Next until you can click Finish.
4. Click Accept Changes and Start Campaign.
5. Click Begin Campaign
6. Click Take Off
7. Click Yes to Continue without player pilots
8. Click Abort Mission.

Do you still get the error? If so, save and attach that save file.

**Comment by DanAlbert** [comment]
If we can get a rerpo case, that looks rather serious, so I'd want to look at it for the next releas.

**Comment by cj3273** [comment]
> I cannot open the campaign save you attached. It appears to be corrupted.
> 
> I'd like you to follow the steps below to troubleshoot.
> 
> 1. Start up Liberation
> 2. Start a new campaign, pick Operation Vectron's Claw
> 3. Don't change anything. Just keep clicking Next until you can click Finish.
> 4. Click Accept Changes and Start Campaign.
> 5. Click Begin Campaign
> 6. Click Take Off
> 7. Click Yes to Continue without player pilots
> 8. Click Abort Mission.
> 
> Do you still get the error? If so, save and attach that save file.

There's no error when I follow those steps. Works as expected.

**Comment by Starfire13** [comment]
Ok, so what are you doing different? Something you're doing is causing the error, and we just have to try to nail down what that is. What settings are you changing, for example?

**Comment by cj3273** [comment]
I decreased the enemy income multiplier to 0.7, enabled the supercarrier module and splash damage, and added a few more squadrons for the A-10, F-16, and F-18.

**Comment by cj3273** [comment]
Weirdly enough I've just tried a few different campaigns, with a few different settings, including the exact same ones I was getting that error with, and I can't seem to reproduce that error message again. Everything is working fine now?

**Comment by Starfire13** [comment]
> Weirdly enough I've just tried a few different campaigns, with a few different settings, including the exact same ones I was getting that error with, and I can't seem to reproduce that error message again. Everything is working fine now?

The problem very likely still exists. There's about 4 different people who have encountered it so far. We just don't know how to replicate it yet. Something you guys are doing is triggering it, but we just don't know what that is.

**Comment by cj3273** [comment]
Yeah what's really weird is that yesterday nothing I tried would work, and now today it works just fine every time.

**Comment by Starfire13** [comment]
Something ends up corrupting the save file. Which is why it works, until it doesn't.

**Comment by Starfire13** [comment]
For now, just create separate saves so you can always go back to a previous one if the bug occurs. I always create a separate save per turn.

**Comment by DanAlbert** [comment]
If anyone works out repro steps, please include them here (with the save) or file a new bug. Closing since there's nothing we can do until that happens.
