### ISSUE TITLE
Aircraft from even-numbered flights in cancelled packages go missing

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#3258]
### Affected versions

Development build

### Build information

DCS Liberation 10.0.0
Build 5628
Git revision 183d6df8bfd4dd44fb6026de0b7e8ae53381c374

### Description

I am filing this as a separate bug but I'm guessing it is likely the root cause of #3257 and fixing this will probably fix that one too. I'm guessing it is also the cause of #2745.

We have had a veeeery long-standing bug where planes mysteriously vanish into the Bermuda Triangle or something and aren't available for tasking even though they show up in Air Wing and you can get them back if you pass turn. I think I've finally figured out why it happens.

If you plan a multi-flight package and then cancel it (with the X button), the aircraft in all even-numbered flights will disappear.

So if you plan a package like this one and cancel it, you will lose all 16 of your F-15Es.
![Screenshot 2023-11-21 113343](https://github.com/dcs-liberation/dcs_liberation/assets/72491792/7dc9be81-672a-4d76-8b1c-8cddf76ff7f3)

You'll see at that point that the "sell aircraft" button for the F-15Es is greyed out even though it shows you have 16, because they're actually all gone.
![Screenshot 2023-11-21 114039](https://github.com/dcs-liberation/dcs_liberation/assets/72491792/ef397c5b-6de2-419f-b8ef-c27361f60b22)

And if you try to plan more flights, the F-15Es are no longer available, though the aircraft from the odd-numbered flights in the cancelled package (the A-10s and B-1s) are still available.
![Screenshot 2023-11-21 114134](https://github.com/dcs-liberation/dcs_liberation/assets/72491792/d267e67a-4af3-4a73-8e5c-e60db7c1b5ff)

### Save game and other files (save game required, bugs without saves will be closed)

This save file demonstrates the package I made to trigger this bug.

[Bright Star #5628 Turn 1 Bug 2.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/13420576/Bright.Star.5628.Turn.1.Bug.2.liberation.zip)

**Comment by DanAlbert** [comment]
It's actually a little bit more nuanced than that even. If I delete the flight in your save it works as expected. It's only if you cancel while created a _new_ package (the x in the top right, rather than saving and then deleting it) that the bug happens.

**Comment by DanAlbert** [comment]
Though looking at the code, I think that if you were to manually fast forward such that at least one flight member was active, all the even numbered flights would still disappear.

The cause looks to be more or less what we guessed: we're deleting things from a list that we're iterating over (whyyyyyy doesn't Python invalidate the iterator and turn that into an error?), so the fix should be easy.

**Comment by Starfire13** [comment]
Yes, that's why I specifically mentioned the x button in the bug report. It only happens when you cancel the flight while planning it.

**Comment by DanAlbert** [comment]
Yeah, I just hadn't expected it to be any different for a planned package :)

Damn good find. Thanks a lot for figuring that one out. The fix is up (https://github.com/dcs-liberation/dcs_liberation/pull/3267). As you suspected it does fix both issues.
