### ISSUE TITLE
[Bug] Units misplacement 

### ISSUE THREAD

**Issue by Nomadzy** [dcs-liberation/dcs_liberation#327]
Sometimes this happen, its not blocking but its weird : 
![Screen_201017_105615](https://user-images.githubusercontent.com/23081223/98454110-228ad400-2161-11eb-8ff7-1bac5ea9797b.png)
![Screen_200811_220635](https://user-images.githubusercontent.com/23081223/98454119-35050d80-2161-11eb-9b6c-622820b53bb7.png)
![Screen_201017_103922](https://user-images.githubusercontent.com/23081223/98454130-4e0dbe80-2161-11eb-95fa-19dfe274ec79.png)

**Comment by DanAlbert** [comment]
Issues are fixed by the new campaign format. Still migrating campaigns, but the problem itself is solved.
