### ISSUE TITLE
Graphical artifacts and disappearing icons/routes on map

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#3276]
### Affected versions

Development build

### Build information

DCS Liberation 10.0.0
Build 5663
Git revision 9271717a5be3b3df1b9e4af2f0782d9bbe90c85e

### Description

Icons and flight routes on the map periodically disappear and reappear when the map is moved or a different package is clicked on. Also seeing white graphical artifacts on the map area.

Possibly related to this warning message in the log. This problem didn't occur in previous build I was on (#5628).

WARNING :: WARNING: L.esri.BasemapLayer uses data services that are in mature support and are not being updated. Please use L.esri.Vector.vectorBasemapLayer instead. More info: https://esriurl.com/esri-leaflet-basemap

![Screenshot 2023-12-02 084203](https://github.com/dcs-liberation/dcs_liberation/assets/72491792/d5a885e9-3bb6-4a47-aaee-49be58905128)

### Save game and other files (save game required, bugs without saves will be closed)

[Noisy Cricket #5663 Turn 1.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/13532159/Noisy.Cricket.5663.Turn.1.liberation.zip)

**Comment by DanAlbert** [comment]
> WARNING :: WARNING: L.esri.BasemapLayer uses data services that are in mature support and are not being updated. Please use L.esri.Vector.vectorBasemapLayer instead. More info: https://esriurl.com/esri-leaflet-basemap

This has been there since we first switched to the new map. The alternative it wants us to use requires a subscription fee that we obviously can't afford. It's unlikely to be the cause though.

**Comment by DanAlbert** [comment]
I don't see the same artifacting, fwiw. I do see white boxes around the edges while I pan around before the tiles load in, but that's to be expected. I don't see the disappearing icons either.

**Comment by DanAlbert** [comment]
> Build 5663

That was not actually a submitted build, btw. That was from a PR, so it may just not have been in a good state.

If any of the recent changes broke this, 5652 seems the most likely, with 5650 being the one that worked (5651 was a PR build). 5652 updated qt, so it's possible that it included some fun new bugs in the web engine. If you still see it on a non-PR build, it'd be worth trying those two to test my theory. Since it doesn't happen on my machine I can't do the legwork.

**Comment by Starfire13** [comment]
Ah, yeah. I dunno why I installed 5663. Clearly was not fully awake yet when I did it. I updated to 5665, and the problem is no longer there.

**Comment by DanAlbert** [comment]
Good, but also weird. /shrug

**Comment by Starfire13** [comment]
Looks like I spoke to soon. I am still encountering the graphical artifacts on 5665. I'm heading out soon, but will play around with it more when I get home.

![Screenshot 2023-12-02 131754](https://github.com/dcs-liberation/dcs_liberation/assets/72491792/f0a8ddb7-2fda-464e-b991-741bb72252f9)

By the way, this is a different thing from the white boxes around the edge when you pan about. That has always been there and I assume it's just the map getting loaded in and not a bug.

You can kinda sorta manually "encourage" the bug to appear by moving your mouse about and mousing over the icons on the map. I've also seen it when selecting different packages. It looks like the issue occurs sometimes when it's trying to render or remove the little white info box that pops up when you mouse over a target.

For example, this happened once I mouse-over'd an icon.

![Screenshot 2023-12-02 133736](https://github.com/dcs-liberation/dcs_liberation/assets/72491792/a80cb029-268c-4a46-b6cc-103dd016d4a1)

It does appear to happen significantly more on my ultrawide screen compared to my secondary 16:9 monitor.

**Comment by DanAlbert** [comment]
> By the way, this is a different thing from the white boxes around the edge when you pan about. That has always been there and I assume it's just the map getting loaded in and not a bug.

Correct.

> It does appear to happen significantly more on my ultrawide screen compared to my secondary 16:9 monitor.

That'd be damned odd, but I'll have to try that.

**Comment by Starfire13** [comment]
I did a bit more testing and can confirm the issue does not exist in 5650.

I was not able to run 5652 and 5656 because I get the error below. That's due to the shift of all build files apart from the executable into _internal, which is why you downgraded pyinstaller to fix this, I believe.

![Screenshot 2023-12-02 181842](https://github.com/dcs-liberation/dcs_liberation/assets/72491792/d4fae70c-dabc-4242-9d23-90997db82328)

I tried 5658 which is the one where the pyinstaller is downgraded, and the graphical artifact issue exists in that build.

**Comment by DanAlbert** [comment]
Okay, I'll try downgrading qt tomorrow and let you try that. Will also try the ultra wide on my end.

**Comment by Mmucha83** [comment]
same issue exists with build 5660

**Comment by DanAlbert** [comment]
Well we haven't done anything to fix it, so that's expected :)

**Comment by DanAlbert** [comment]
Two PRs to try (it still doesn't repro on my machine):

https://github.com/dcs-liberation/dcs_liberation/pull/3280 reverts just the Python upgrade. https://bugreports.qt.io/projects/PYSIDE/issues/PYSIDE-2230?filter=allopenissues suggests that Qt might not be quite ready for 3.12, even though they publish a wheel for 3.12.

https://github.com/dcs-liberation/dcs_liberation/pull/3281 downgrades Python and Qt. I can't downgrade Qt without downgrading Python, unfortunately.

lmk if either fixes it.

**Comment by Starfire13** [comment]
#3281 fixed it. Problem is still present in #3280.

**Comment by DanAlbert** [comment]
Thanks for confirming. Merged.
