### ISSUE TITLE
World Map Not Appearing

### ISSUE THREAD

**Issue by DeanSellas** [dcs-liberation/dcs_liberation#3285]
### Affected versions

9.0.0

### Build information

DCS Liberation 9.0.0

### Description

I do not see the Map panel when launching DCS Liberation, or creating a new template version. I followed the Getting started guide and from what I can tell this map should be appearing so I believe it is a bug. 

![image](https://github.com/dcs-liberation/dcs_liberation/assets/12126966/b02051d3-56cf-4855-ac41-aae6791b2b12)
When launching

![image](https://github.com/dcs-liberation/dcs_liberation/assets/12126966/b5c4a902-3b68-40b0-b060-ae863c8156ce)
after creating a mission from a template.

### Save game and other files (save game required, bugs without saves will be closed)

[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/13541476/liberation.log)

**Comment by Starfire13** [comment]
If you are running Liberation in admin mode, try not running it in admin mode. That has resolved the problem for others.

**Comment by DeanSellas** [comment]
> If you are running Liberation in admin mode, try not running it in admin mode. That has resolved the problem for others.

these screenshots were taken in admin mode.

**Comment by Starfire13** [comment]
Ok. So try what I suggested and see if it works.

**Comment by DeanSellas** [comment]
> Ok. So try what I suggested and see if it works.

my bad misread, this happens in both admin and regular launch

**Comment by Starfire13** [comment]
Go to this link. Does the map load?

https://leafletjs.com/

**Comment by DeanSellas** [comment]
> Go to this link. Does the map load?
> 
> https://leafletjs.com/

loads fine on my computer

**Comment by Starfire13** [comment]
This is an issue that has very occasionally been reported by users. The last time was 2 years ago (see #1281). Unfortunately, it has proven impossible for us to replicate thus far, and even the few folks who have reported and resolved it have done so via different means. So far, none of the "fixes" mentioned in the other bug report has worked for anyone else other than the person who originally fixed it that way on their end.

Essentially, the Liberatiom map is a browser window and the map data is streamed in. Something on a few folk's computers is preventing that from happening, but we don't know what that is.

**Comment by DanAlbert** [comment]
Make sure your AV isn't screwing things up is one of the other occasional fixes, iirc.

Like @Starfire13 says, we've got no idea how to help on this one. It sucks but it is what it is. Closing for now, but will reopen if someone can figure out the cause and it's something we can fix.
