### ISSUE TITLE
FOB window shows "runway operational" even though FOBs have no runways

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#3290]
### Affected versions

Development build

### Build information

DCS Liberation 10.0.0
Build 5677
Git revision b014f2e543260d2112f3499da7a17b3e05039bb0

### Description

Minor UI bug, where FOBs still show the "runway operational" line like airfields, even though FOBs don't have runways.

![Screenshot 2023-12-10 090108](https://github.com/dcs-liberation/dcs_liberation/assets/72491792/a531f205-a0a3-4b71-96e1-c1ed482ad51b)

### Save game and other files (save game required, bugs without saves will be closed)

[FOB Runway.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/13625755/FOB.Runway.liberation.zip)

**Comment by DanAlbert** [comment]
Most likely just old wording that was never tweaked. Should probably say "FARP operational".

**Comment by Starfire13** [comment]
The runway operational line is there for non-FARP FOBs too.

**Comment by DanAlbert** [comment]
https://github.com/dcs-liberation/dcs_liberation/pull/3311 changes this to describe each type of "runway" more appropriately. e.g. "FARP operational" or "Flight deck operational". FOBs (that is, non-FARPs) will omit the line entirely.

**Comment by Starfire13** [comment]
Nice. Is it actually possible to damage a flight deck? I didn't think it was. The carrier's either functional or sunk, isn't it?

**Comment by DanAlbert** [comment]
If the flight deck is at the bottom of the black sea, it's not operational ;)

**Comment by DanAlbert** [comment]
(it's not possible to damage a FARP either)
