### ISSUE TITLE
Click-through on frontline not working consistently

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#3295]
### Affected versions

9.0.0, Development build

### Build information

DCS Liberation 10.0.0
Build 5677
Git revision b014f2e543260d2112f3499da7a17b3e05039bb0

### Description

Unlike the icons on the Liberation map (e.g. for control points, SAMs, resource sites, static targets, etc), the the orange line depicting the frontline is on a layer behind the flight paths. This makes is difficult to right-click on when you're trying to plan flights (typically CAS or TARCAP) to the frontline.

You end up getting this menu instead.

![Screenshot 2023-12-13 073544](https://github.com/dcs-liberation/dcs_liberation/assets/72491792/359c7c4e-17c6-46e6-bcd1-067d12afd680)

You can see in the picture below that the flight paths are below the icons on the map (see orange circle) rather than on top of them, unlike when they pass over the frontline.

![Screenshot 2023-12-12 231902](https://github.com/dcs-liberation/dcs_liberation/assets/72491792/5daa15b5-ed0e-4ac2-a664-851b4413c516)

When you first start Liberation, the campaign save that is auto-loaded on startup, will have a frontline that you can click-through to. However, if you load a different save file (it has to be a different one, not just reloading the one that auto-loaded), you will find that you can no longer click through to the frontline.

I don't think it really matters if the frontline is visually on the top layer. What is important is that you're able to click on it easily. At the moment, you can only get that functionality for the auto-save that gets loaded on Liberation startup.

### Save game and other files (save game required, bugs without saves will be closed)

[Bright Star #5677 Turn 1.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/13653025/Bright.Star.5677.Turn.1.liberation.zip)

**Comment by DanAlbert** [comment]
> When you first start Liberation, the campaign save that is auto-loaded on startup, will have a frontline that you can click-through to. However, if you load a different save file (it has to be a different one, not just reloading the one that auto-loaded), you will find that you can no longer click through to the frontline.

Ah, yeah, that's the trick here. I can repro now.

**Comment by DanAlbert** [comment]
The plot thickens: it only does that when the map is not run in dev mode... which would be the other reason I hadn't been able to repro this before.
