### ISSUE TITLE
Flight route of selected flight now displays under all non-selected flights instead of above them

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#3305]
### Affected versions

Development build

### Build information

DCS Liberation 10.0.0
Build 5700
Git revision 1efce862fb2cc3330a3cfaae372ffd6aefbf63a9

### Description

The flight route of a selected flight used to get displayed above non-selected flights, allowing you to see the entire flight route in yellow.

This is what it used to look like:
![Screenshot 2023-12-20 223914](https://github.com/dcs-liberation/dcs_liberation/assets/72491792/4a202cd0-9ae9-4ca2-bf04-0356b2e0b87c)

This behaviour has now changed, I'm guyessing as a side effect of the fix for #3295. Now the selected flight's flight route always displays behind the flight routes of non-selected flights.
![Screenshot 2023-12-20 223954](https://github.com/dcs-liberation/dcs_liberation/assets/72491792/04b71ba9-0e47-4bfe-899e-308d5eb4dd42)

### Save game and other files (save game required, bugs without saves will be closed)

[Bright Star #5700 Turn 2.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/13726852/Bright.Star.5700.Turn.2.liberation.zip)

**Comment by DanAlbert** [comment]
I believe this can only be fixed by bringing the selected flight plan back to the front (on top of the front line). That's probably okay. It'll bring back the previous bug in a much smaller way.

**Comment by Starfire13** [comment]
Ah. Yeah, that should be fine. It's only one route. Incidentally, the extra thick frontline you implemented as the initial fix for the unclickable frontline issue can be reverted if you like, since the root of the problem has been resolved.
