### ISSUE TITLE
Does not generate a campaign or get to air wing configurations, crashes when I push finish

### ISSUE THREAD

**Issue by Bob09031960** [dcs-liberation/dcs_liberation#3333]
### Affected versions

10.0.0

### Build information

DCS Liberation 10.0.0

### Campaign name

any

### Blue faction

any

### Red faction

any

### Modifications to default settings

None

### Description

Create new campaign,, go through any initial setup as default (no changes) when I press finish to generate campaign the application closes (I assume crashes out)

### Log file

[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/14109751/liberation.log)
my build is:
DCS Open Beta  2.9.2.49940
MSI MEG Z790 Ace Motherboard
Intel 13900KF
128GB RAM
ASUS RTX 4090
Dedicated O/S and Apps Drive Samsung 990Pro 2TB
Dedicated Gaming Drive  Samsung 990 Pro 2TB
Windows 11 23H2  version 10.0.22631

**Comment by Starfire13** [comment]
Does this happen with a specific campaign or any campaign?

**Comment by Starfire13** [comment]
Can you reinstall Liberation to ensure that it's not a corrupt install causing this? From the log, it appears the crash is occurring while loading the miz file. Do you have any custom campaigns (i.e. not the ones bundled with Liberation) installed?

**Comment by Bob09031960** [comment]
Thankyou for the information,, 

 

I have several Campaigns installed that I have purchased over time…..these are in my  Saved Games Folder,, 

 

I will remove them (relocate to see if this helps) 

 

Thank you

 

Bob

**Comment by Bob09031960** [comment]
Hi Starfire 13…

 

Thank you it appears as though keeping campaign files within the Saved Games\DCS OpenBeta\Missions\Campaigns\en Folder is not a great idea.. 

 

Copied these off to an archive,, reinstalled DCS Liberation and it appears to be working now.. 

 

Thank you for your advice and assistance….. 

 

Regards

 

Bob

**Comment by Starfire13** [comment]
Normally, those shouldn't be an issue. I was referring more to Liberation campaign templates that you had either created yourself or had downloaded from somewhere.

But regardless, I am glad you got it working!
