### ISSUE TITLE
Script Error on Entering Plane

### ISSUE THREAD

**Issue by SteelSkeleton** [dcs-liberation/dcs_liberation#3346]
### Affected versions

10.0.0

### Description

When I launch mission and hit fly to go in plane - I receive the following error:

![image](https://github.com/dcs-liberation/dcs_liberation/assets/109772893/34aa71c2-18d9-4dec-90cc-ddd6d7383a17)

If I quite the mission, I don't have any mission results to accept and do not have a state.json.

### Save game and other files (save game required, bugs without saves will be closed)

[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/14412669/liberation.log)

**Comment by Starfire13** [comment]
Rather than closing it with no comment, we would prefer if you could let us know how you resolved the problem, assuming you are closing it as it is resolved. This would help others who encounter the same error in the future. Thanks.

**Comment by SteelSkeleton** [comment]
Human error! I think I had my game location path incorrectly identified. A reinstall and correct pathing seemed to fix the issue. I would have just deleted the bug report but didn't see way to do that.
