### ISSUE TITLE
Could not create a Syria campaign using Lebanon War 1982 era

### ISSUE THREAD

**Issue by s3-chardonjf** [dcs-liberation/dcs_liberation#335]
I was in develop build and did the following:

- Start new game
- Select Syria Full Map, Russia 1990 and USA 1990
- Select "Lebanon War 1982"
- Complete the wizard and notice the error:
![image](https://user-images.githubusercontent.com/29724443/98518735-10e42200-2270-11eb-8851-a40ea08f507c.png)

**Comment by DanAlbert** [comment]
Working for me. The new game wizard has been changed a lot since you initially reported this so I'm guessing it was already fixed.
