### ISSUE TITLE
F-15E S4+ and F1-EE no longer human flyable

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#3358]
### Affected versions

Development build

### Build information

DCS Liberation 11.0.0
Build 5841
Git revision b0a8d53fa6cee3577029a4a005208d339257d80a

### Description

This bug was reported by SaabFAN86 on the Discord.

The F-15E S4+ and F1-EE are no longer human flyable in the newest dev build (though the issue is likely a bit older). I suspect this might have occurred when we switched to a local fork for Pydcs?

![Screenshot 2024-03-17 090136](https://github.com/dcs-liberation/dcs_liberation/assets/72491792/39efc990-06e3-44c4-b84b-518a70ff31bb)

![Screenshot 2024-03-17 090204](https://github.com/dcs-liberation/dcs_liberation/assets/72491792/60081e5f-1fec-4cba-82a6-48b5ffeca1f5)

### Save game and other files (save game required, bugs without saves will be closed)

[F15E and F1EE not human flyable #5841.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/14625412/F15E.and.F1EE.not.human.flyable.5841.liberation.zip)

**Comment by zhexu14** [comment]
Thanks for looking into this @Starfire13 . It looks like this error started when I did the pydcs export for the latest DCS version. I don't own the Strike Eagle or Mirage-F1, which in conjunction with the export script being somewhat dated, meant it didn't export correctly.

**Comment by zhexu14** [comment]
Fixed in #3360

**Comment by Raffson** [comment]
> Thanks for looking into this @Starfire13 . It looks like this error started when I did the pydcs export for the latest DCS version. I don't own the Strike Eagle or Mirage-F1, which in conjunction with the export script being somewhat dated, meant it didn't export correctly.

I had a quick look at pydcs and noticed you didn't add those aircraft to the "flyables" map (starts at line 214).
So if my assumption is correct, you manually added the properties in planes.py?
If so, you might want to explicitly add those aircraft to that "flyables" map because if you don't own a module, it will never export as a flyable aircraft, hence the "flyables" map... 😅

**Comment by zhexu14** [comment]
> > Thanks for looking into this @Starfire13 . It looks like this error started when I did the pydcs export for the latest DCS version. I don't own the Strike Eagle or Mirage-F1, which in conjunction with the export script being somewhat dated, meant it didn't export correctly.
> 
> I had a quick look at pydcs and noticed you didn't add those aircraft to the "flyables" map (starts at line 214). So if my assumption is correct, you manually added the properties in planes.py? If so, you might want to explicitly add those aircraft to that "flyables" map because if you don't own a module, it will never export as a flyable aircraft, hence the "flyables" map... 😅

Thanks for the call out @Raffson , I have added these modules to the flyables map in this PR on pydcs :)
https://github.com/pydcs/dcs/pull/375
