### ISSUE TITLE
Not sure if it´s a bug, but the mission generator always buys units automatically

### ISSUE THREAD

**Issue by Goliathus-21** [dcs-liberation/dcs_liberation#3367]
### Affected versions

10.0.0

### Build information

DCS Liberation 11.0.0

### Description

Hi,

I´m not sure if there was something changed intentionally since the 10.0 version, but after I installed the version 10.0 I noticed, that I can´t buy any units anymore in any new campaign I try to run and units are always autopurchased by the mission generator. Yes, I tripple checked if I did turn the autopurchase off and it is off. This is very same for me with the 11.0 version, so I´m stucked with the 9.0 version at the moment.

This behavior is very same for any campaign I try to begin, I get to the first step and I get gray-ish "+" symbol, so I can´t buy any units (please note that I´ve got enough money to buy the unit). So my only option is to begin the campaign, which seem´s okey because I get plenty of units, but I´m still unable to buy any units by myself. 

This is frustrating for more reasons. First of all - the AI buys tons of units that kills my performance and I can´t avoid that by reducing the income. Secondly, I don´t wan´t the AI to buy units, that are useless and spend the money on something that is only killing my CPU performance.

What am I missing please?  

The enclosed savegame file is made by the 11.0. version.

Thx, 

Goliathus

### Save game and other files (save game required, bugs without saves will be closed)

[Beginning.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/14863822/Beginning.liberation.zip)

**Comment by Starfire13** [comment]
The autoplanner isn't spending any money buying units. You now start out with your squadrons at full strength at campaign start. If this is too many aircraft, reduce the number of squadrons or the number of aircraft in the squadrons. Alternatively, just disable the option during campaign generation.
