### ISSUE TITLE
problem with V11 creating mission

### ISSUE THREAD

**Issue by Tinchus2009** [dcs-liberation/dcs_liberation#3379]
### Affected versions

11.0.0

### Build information

DCS Liberation 11.0.0

### Description

Hi. Well, seems like V11 and me are having relationship troubles jajajaja. Can someone help me learn what Im doing wrong. It has been several days since I have not been able to create missions in a campaign without having troubles.
I will upoad a mission, basically now for the moment the mission just cant start from the  very beginning. there are 2 Heli mission taking off from kustnezof, they start, they try to take off... and then they stop engines. Then I close the mission, I try to abort the mission from liberation and I get this error:

{'id': 'WrappedAction', 'auto': False, 'enabled': True, 'params': {'action': {'id': 'Option', 'params': {'name': 5, 'value': 65538, 'formationIndex': 1, 'variantIndex': 2}}}, 'number': 1} is not a valid Formation

Traceback (most recent call last):
  File "qt_ui\windows\QWaitingForMissionResultWindow.py", line 139, in reject
  File "qt_ui\windows\QLiberationWindow.py", line 377, in reset_to_pre_sim_checkpoint
  File "game\persistence\savemanager.py", line 89, in load_pre_sim_checkpoint
  File "game\persistence\savegamebundle.py", line 89, in load_pre_sim_checkpoint
  File "game\persistence\savegamebundle.py", line 94, in loadfrom
  File "enum.py", line 712, in call
  File "enum.py", line 1135, in __new
ValueError: {'id': 'WrappedAction', 'auto': False, 'enabled': True, 'params': {'action': {'id': 'Option', 'params': {'name': 5, 'value': 65538, 'formationIndex': 1, 'variantIndex': 2}}}, 'number': 1} is not a valid Formation

### Save game and other files (save game required, bugs without saves will be closed)

[liberation_nextturn.zip](https://github.com/dcs-liberation/dcs_liberation/files/14985080/liberation_nextturn.zip)
[ultima.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/14985086/ultima.liberation.zip)
[state.json](https://github.com/dcs-liberation/dcs_liberation/files/14985091/state.json)
[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/14985095/liberation.log)
[dcs.log](https://github.com/dcs-liberation/dcs_liberation/files/14985096/dcs.log)

**Comment by Starfire13** [comment]
It appears it is the Su-33s on the Admiral Kuznetsov that are causing the error. If you transfer the Su-33 squadron to a land base and plan a mission, you can abort just fine. So this is specific to Su-33s on the Kuz.

**Comment by Tinchus2009** [comment]
I erased that flight completly, and the propblem persists: the heli flighs still abort take off, and the abort mission gives error:

{'id': 'WrappedAction', 'auto': False, 'enabled': True, 'params': {'action': {'id': 'Option', 'params': {'name': 5, 'value': 65538, 'formationIndex': 1, 'variantIndex': 2}}}, 'number': 1} is not a valid Formation

Traceback (most recent call last):
  File "qt_ui\windows\QWaitingForMissionResultWindow.py", line 139, in reject
  File "qt_ui\windows\QLiberationWindow.py", line 377, in reset_to_pre_sim_checkpoint
  File "game\persistence\savemanager.py", line 89, in load_pre_sim_checkpoint
  File "game\persistence\savegamebundle.py", line 89, in load_pre_sim_checkpoint
  File "game\persistence\savegamebundle.py", line 94, in _load_from
  File "enum.py", line 712, in __call__
  File "enum.py", line 1135, in __new__
ValueError: {'id': 'WrappedAction', 'auto': False, 'enabled': True, 'params': {'action': {'id': 'Option', 'params': {'name': 5, 'value': 65538, 'formationIndex': 1, 'variantIndex': 2}}}, 'number': 1} is not a valid Formation

**Comment by Starfire13** [comment]
Ok, this is weird because now it works if I delete the Foxhound fighter sweep from Al Minhad. But earlier, it would only work if I deleted the Su-33 BARCAP package. Ultimately, something's screwy going on and Xray will have to take a look at it.

As for the helicopters not taking off, they take off fine if dragged over to a land base in the mission editor, which suggests it's a DCS bug. I suggest you set them to air start to avoid the issue.

**Comment by zhexu14** [comment]
Definitely something screwy going on. I've made a short term fix in the development preview build that fixes this issue, but will keep this issue open as we need to actually find and fix the root cause.

@Tinchus2009 : in case you wanted to try out the development preview build: https://github.com/dcs-liberation/dcs_liberation/wiki/Preview-builds

Your saves should be compatible for now.

**Comment by Tinchus2009** [comment]
Ok, thanks. If you need me to provide some extra info or do some test, will be glad to
I downloaded latest of those builds and tried the same mission I gave you. Even after deleting the su33 flight, still there is something that prevents the heli flight to take off, and seem s the same happend on the bases with planes
Abort works

**Comment by Starfire13** [comment]
The issue with your KA-50s not taking off is because of temperature. Mission temperature is 38 degrees Celsius. The KA-50 can't do vertical take offs when it's that hot. So either lower the temperature manually or operate them from a land base (where they can do a running takeoff on the runway).
