### ISSUE TITLE
MOD-SUPPORT - CurrentHill Asset Packs

### ISSUE THREAD

**Issue by SaabFAN** [dcs-liberation/dcs_liberation#3388]
With the new Kola Map, the "Blue" side of any potential campaign looks to be quite boring (No swedish boats, only some generic tanks, almost no SAMs and AAA) and at least in the boat-department, the "Red" side is severely lacking in terms of visual fidelity on many models. 

So I was wondering if its possible to add support for CurrentHill's Asset Packs in Liberation.

**Comment by Starfire13** [comment]
Duplicate of #3130

**Comment by zhexu14** [comment]
Closing as duplicate.
