### ISSUE TITLE
have the waypoint be past the enemy when the enemy is retreating 

### ISSUE THREAD

**Issue by Kerbo416** [dcs-liberation/dcs_liberation#339]
![image](https://user-images.githubusercontent.com/66778107/98585710-605a3a80-22d0-11eb-8146-f3877661f994.png)
for example here by the time the friendlies catch up the enemy would've gotten out of reach

**Comment by DanAlbert** [comment]
What stance were they in?

**Comment by Kerbo416** [comment]
mine were in elimination

**Comment by DanAlbert** [comment]
https://github.com/Khopa/dcs_liberation/issues/385
