### ISSUE TITLE
Certain assets not loaded into game

### ISSUE THREAD

**Issue by KrissJot** [dcs-liberation/dcs_liberation#3407]
### Affected versions

Development build

### Build information

11. (Dcs 2.9.5 (#3393) #5922 preview build). The same happens in Retribution.

### Description

Certain assets, including carrries and almost all frontline assets, does not load into game. They are visible in mission planner but does not appear in game. 

### Save game and other files (save game required, bugs without saves will be closed)

[Syria1970.liberation.zip](https://github.com/user-attachments/files/15841730/Syria1970.liberation.zip)
[liberation_nextturn.zip](https://github.com/user-attachments/files/15841734/liberation_nextturn.zip)

**Comment by zhexu14** [comment]
The two files seem to come from different campaigns. The Liberation save (Syria1970.liberation.zip) is centered around the north of the map while the .miz file (liberation_nextturn.miz) is centered around the south. When I load the missions in DCS, both show a Blue CVN group and front line units in both the DCS Mission Editor and in-mission.

I notice the CVN is a Supercarrier - do you have that module? Other than that, looks like an issue with your DCS install.

**Comment by Raffson** [comment]
@KrissJot , perhaps a stupid suggestion but have you tried running a repair on your DCS installation? It's known to sometimes solve strange issues like these 😅

**Comment by zhexu14** [comment]
Based on the discussions on Discord, looks like this got resolved, with the root cause being the Su-30 mod.
