### ISSUE TITLE
Error loading latest save game

### ISSUE THREAD

**Issue by dugrass** [dcs-liberation/dcs_liberation#3416]
### Affected versions

11.1.1

### Build information

DCS Liberation 11.0.0

### Description

I have faced this issue multiple times.  After flying several missions in a campaign randomly when I open up Liberation it cannot load my latest campaign (or any previous campaigns I have started).  I looked through the log and found this error listed when it happened again today:
2024-06-26 21:01:41,810 :: root :: ERROR :: Error loading latest save game
[liberation.log](https://github.com/user-attachments/files/16006755/liberation.log)
[Black Caucases_2024-06-07.liberation.zip](https://github.com/user-attachments/files/16006775/Black.Caucases_2024-06-07.liberation.zip)

### Save game and other files (save game required, bugs without saves will be closed)

[dcs.log](https://github.com/user-attachments/files/16006819/dcs.log)
[state.json](https://github.com/user-attachments/files/16006826/state.json)

**Comment by zhexu14** [comment]
Looks like the same issue as #3379 except that the corrupted state made it to the Liberation save.

A fix is in the next build 11.1.1 that prevents Liberation getting into a corrupted state, but unfortunately this save is corrupted and you'll need to start a new campaign.
