### ISSUE TITLE
[Feature Request] Alternate/Divert Airfields

### ISSUE THREAD

**Issue by Mustang-25** [dcs-liberation/dcs_liberation#342]
Adding an additional waypoint in flight planning or at least having the airfield info on the kneeboard for a divert option would be a great addition for QoL and realism. Some aircraft like the Jeff and Hog have this ability built in but it can be tricky for other modules without having to 'cheat' by using the F10 map.

**Comment by DanAlbert** [comment]
The kneeboard and radio planning are actually already built for this and we just need to add the planning option.

**Comment by DanAlbert** [comment]
Not quite done yet. The planning is all there, but the aircraft don't actually move to the new airfield after the mission, and we should automatically configure divert airfields when available.

**Comment by Mustang-25** [comment]
I suppose it could go either way. Conceptually we can frame it as just landing to fuel up and then returning to your parent airbase between turns. But also I see where what you're talking about plays into the ferry flight feature.
