### ISSUE TITLE
DCS 2.9.6 support

### ISSUE THREAD

**Issue by geofffranks** [dcs-liberation/dcs_liberation#3420]
### Affected versions

11.1.1

### Build information

Reproduced on 11.0.0 and 11.1.1.

### Description

Missions generated by liberation seem to be incompatible with DCS 2.9.6's new spawning logic. I've tried 11.0.0 and 11.1.1, in both single player and multiplayer modes. The main issue is that I never get spawned into a plane, even after waiting for 3-4 minutes in a mission set to fast forward until player start. When multiple player slots are defined in single-player mode, DCS crashes (i had never tried this prior to today, so not sure if this is new or not). But even when only one player slot is defined, I never get put in a plane on single or multi-player modes, despite being able to F2 around and watch AI planes in the mission carry out their duties.

### Save game and other files (save game required, bugs without saves will be closed)

[state.json](https://github.com/user-attachments/files/16191880/state.json)
[liberation.log](https://github.com/user-attachments/files/16191885/liberation.log)
[taking-cyprus.liberation.zip](https://github.com/user-attachments/files/16191864/taking-cyprus.liberation.zip)
[liberation_nextturn.zip](https://github.com/user-attachments/files/16191906/liberation_nextturn.zip)
[dcs.log](https://github.com/user-attachments/files/16192288/dcs.log)

**Comment by 0bservator** [comment]
I did some experimenting with this bug, and it seems that opening a mission in the mission editor fixes the spawning logic. As you describe, if you just open the mission as normal then no flights will spawn other than the ones set to start in the air. However, if you open the mission in the editor, and then either save and run it from the mission menu or just run it directly from the editor, everything seems to work fine. Not sure why this is or if it actually fixes everything, but I can at least spawn in using this method, as can other AI flights set to cold start.

**Comment by geofffranks** [comment]
Thank you for the workaround! That works for me as well.

**Comment by geofffranks** [comment]
I think this is fixed with DCS 2.9.7. I'm still on Liberation 11.1.1, and no longer need to open mission editor before launching the mission for proper spawning.

**Comment by zhexu14** [comment]
This issue is fixed in the latest development build #3431
