### ISSUE TITLE
Liberation mission became too slow (low FPS)

### ISSUE THREAD

**Issue by Mashhor14** [dcs-liberation/dcs_liberation#3423]
### Affected versions

11.1.1

### Build information

DCS LIBERATION 11

### Description

my pc:
windows 11
cpu i7 12th Gen
gpu GF RTX 4090
ram 32

only when i play missions from liberation, it get too slow , 
but DCS missions really smooth with high max configurations.
i tried all options, but still, big campaign or small
there is no many AI flights or ground units
it was working will, but i think after DCS updates it became like this

[liberation.log](https://github.com/user-attachments/files/16462215/liberation.log)
 [turn 2.zip](https://github.com/user-attachments/files/16462232/turn.2.zip)
[cef_log.zip](https://github.com/user-attachments/files/16462295/cef_log.zip)
[DCSLOG.zip](https://github.com/user-attachments/files/16462300/DCSLOG.zip)

### Save game and other files (save game required, bugs without saves will be closed)

[liberation.log](https://github.com/user-attachments/files/16462333/liberation.log)

**Comment by Starfire13** [comment]
Known issue for ED to fix.

https://forum.dcs.world/topic/353750-horrible-simulation-time-after-last-update-same-mission-unplayable-fps/
