### ISSUE TITLE
OCA/Runway Not Registering Runway Destruction

### ISSUE THREAD

**Issue by geofffranks** [dcs-liberation/dcs_liberation#3425]
### Affected versions

11.1.1

### Build information

DCS Liberation 11.1.1
DCS 2.9.6

### Description

We have tried and tried to get OCA/Runway to work to no avail. Not sure if this is a bug in DCS or Liberation, or if we're just doing things wrong or have the wrong expectations of what should happen.

In the attached mission, we dropped 12x 2k bombs on Akrotiri with direct hits. There was no feedback in-game of runway destruction, however AI planes were prevented from taking off. When exiting the mission + returning to Liberation, the runway was still marked as operational.

Bombs used:

4x GBU-31(V)2/B
4x GBU-31(V)4/B Penetrator
4x GBU-24B/B Paveway III

Craters left on the runway were very small, despite the huge bombs. 

### Save game and other files (save game required, bugs without saves will be closed)

[state.json](https://github.com/user-attachments/files/16560850/state.json)
[test-runway-bombing.liberation.zip](https://github.com/user-attachments/files/16560854/test-runway-bombing.liberation.zip)
[liberation_nextturn.zip](https://github.com/user-attachments/files/16560869/liberation_nextturn.zip)
[dcs.log](https://github.com/user-attachments/files/16560871/dcs.log)

**Comment by geofffranks** [comment]
Did more testing and was finally able to get it to register a damaged runway in liberation. This seems to be DCS issue. The JDAMs just fail to explode properly most of the time for us, despite using the same fuse and release settings.

**Comment by Starfire13** [comment]
Yeah, fuzes are borked in DCS. Delayed fuzes don't work, so penetration isn't possible. You have to use the instant fuzes.

**Comment by geofffranks** [comment]
Looks like the 2.9.7 update fixed the problems we were having where even instant fuzes were duds.
