### ISSUE TITLE
DCS update causes mist.lua to report an error

### ISSUE THREAD

**Issue by Pil-Nick** [dcs-liberation/dcs_liberation#3426]
### Affected versions

11.1.1

### Description

After DCS updated the new version, the mission files using mist.lua, including my own missions and liberation, all had errors. Although the missions can be played normally after this error is turned off, there may be other unknown problems. After modifying the latest version of mist.lua 4.5.126, this error was eliminated, which may be related to DCS deleting some functions or variables. After I changed the name of mist.lua and replaced the mist.lua resource in the liberation file, the missions generated by liberation can also be played normally. Now I attached the repaired mist.lua below.

### Save game and other files (save game required, bugs without saves will be closed)

[mist_4_5_126debug.zip](https://github.com/user-attachments/files/16594026/mist_4_5_126debug.zip)

**Comment by zhexu14** [comment]
MIST has been updated to the latest version in the development build.
