### ISSUE TITLE
Server crashes after loading mission

### ISSUE THREAD

**Issue by attylapl** [dcs-liberation/dcs_liberation#3443]
### Affected versions

11.1.1

### Description

server crashes after loading mission, 5800x3d 64gb ram every time after loading mission file server not responding

### Save game and other files (save game required, bugs without saves will be closed)

[liberation_nextturn.zip](https://github.com/user-attachments/files/17179309/liberation_nextturn.zip)

**Comment by zhexu14** [comment]
The mission has a very large number of units (1400-ish) which is probably too many even for the largest of servers. The crash is probably DCS not being able to handle this mission. I'll close this issue for now, but if you try and smaller campaign and still have issues, please re-open the issue and we can look into it further.
