### ISSUE TITLE
Carrier start

### ISSUE THREAD

**Issue by fullmetalfelix** [dcs-liberation/dcs_liberation#3450]
### Affected versions

11.1.1

### Description

I was trying the Marianas - Pacific Repartee campaign with custom factions (USA 70s vs NVA) and noticed that blue planes do not spawned on the carrier (Stennis), nor spawn at all, regardless of start type (cold/warm/runway).
The only way I get to have a plane is to manually edit the map, set the plane start to runway, and jerk it a bit so that the two planes in the group automatically go to parking 1 and 2.

### Save game and other files (save game required, bugs without saves will be closed)

[navalbattle.liberation.zip](https://github.com/user-attachments/files/17602631/navalbattle.liberation.zip)
[dcs.log](https://github.com/user-attachments/files/17602639/dcs.log)
[liberation_nextturn.zip](https://github.com/user-attachments/files/17602643/liberation_nextturn.zip)

**Comment by zhexu14** [comment]
This sounds like an issue that was fixed in the latest release (12.0).
