### ISSUE TITLE
Add/update CH-47F Chinook

### ISSUE THREAD

**Issue by krazyj83** [dcs-liberation/dcs_liberation#3466]
* Mod name: CH-47F Chinook
* Mod URL: 
* Update or new mod - Official DCS mod. 
Please update Liberation to include CH47F mod from DCS as well as the logistic system to support it

**Comment by zhexu14** [comment]
CH-47 support added to the latest development build.

**Comment by krazyj83** [comment]
@zhexu14 thanks could I request a compiled version update please so we can enjoy the new feature over xmas

**Comment by zhexu14** [comment]
> @zhexu14 thanks could I request a compiled version update please so we can enjoy the new feature over xmas

If there is another DCS release before Christmas, it's likely that 12.1 will get released. Having said that, you can always download the development build: https://github.com/dcs-liberation/dcs_liberation/wiki/Preview-builds
