### ISSUE TITLE
Persian Gulf. USS Arleigh Burkes spawn on island

### ISSUE THREAD

**Issue by EagleMountainDK** [dcs-liberation/dcs_liberation#35]
In my first mission on the Gulf two Arleigh Burkes are spawned on the island between CQ84 and CQ94.

I have attached the generated mission if it can be of any assistance. 
[liberation_nextturn.zip](https://github.com/Khopa/dcs_liberation/files/5011199/liberation_nextturn.zip)

**Comment by jake-lewis** [comment]
Have had the same with the tawara on Syria, don't have a copy of the save though

**Comment by DanAlbert** [comment]
Shouldn't happen with the new campaign format. Not everything has been converted, but the general issue is fixed.
