### ISSUE TITLE
Setting coalition skill in Liberation doesnt change the skill of the AH64D (Blufor Modern)

### ISSUE THREAD

**Issue by TinuzzWasTaken** [dcs-liberation/dcs_liberation#353]
![DCS Lib](https://user-images.githubusercontent.com/74241776/98668746-98a15d80-2350-11eb-9a90-469668574edc.png)

**Comment by FlameDraken84** [comment]
This is actually an issue with all helicopters on Blufor.  I'm not sure if it also applies to Redfor choppers as well but I think that may be the case.

**Comment by DanAlbert** [comment]
It affects all aircraft. Possibly ground units as well
