### ISSUE TITLE
Add ISIL/ISIS as a faction

### ISSUE THREAD

**Issue by Hoodaya** [dcs-liberation/dcs_liberation#356]
With the appropriate units, as an alternative to the insurgent faction.

**Comment by Kerbo416** [comment]
you could probably do it yourself with the factions modding introduced in 2.2

**Comment by Hoodaya** [comment]
Ok thanks mate. Any clues that m how I can come me an it doing that?

**Comment by Kerbo416** [comment]
https://github.com/Khopa/dcs_liberation/wiki/Custom-Factions
but you need to be on the dev version

**Comment by Hoodaya** [comment]
Ok thanks mate
