### ISSUE TITLE
Some airports in Persian Gulf and Caucasus don't spawn base defences

### ISSUE THREAD

**Issue by RoleplayingPleb** [dcs-liberation/dcs_liberation#359]
Some bases in North East Caucasus and south Persian Gulf don't spawn base defenses, If the player captures these bases and attempts to order front line units at these airports the game cannot be loaded in the mission editor.

this essentially breaks the campaign, i haven't found a workaround besides reloading a previous save. This bug makes the Persian Gulf full map essentially unplayable starting in the south.

I included a screenshot, i can include a copy of the .liberation if it helps. 

let me know if i can help in any way.

Known broken airports:
Persian Gulf
Al Dhafra
Al Maktoum
Dubai International
Khasab

Caucasus:
Nalchik

Steps to reproduce.
Generate a campaign for Full Map Persian Gulf, Caucasus or north Caucasus

![1](https://user-images.githubusercontent.com/74385702/99011231-c4665280-259f-11eb-96cc-7334d7e72807.jpg)

**Comment by DanAlbert** [comment]
What version of liberation?

**Comment by RoleplayingPleb** [comment]
Current release 2.1.5

**Comment by DanAlbert** [comment]
There's a pretty good chance the bug is no longer present in the next release. Most of that code has been rewritten.
