### ISSUE TITLE
RC9 Tanker Issues

### ISSUE THREAD

**Issue by MysticDaedra** [dcs-liberation/dcs_liberation#36]
Specifically that TACAN does not work at all, and the tankers are going waaaaaaaaaaaaay too slow. Both the KC-135 and the KC-130 were going only about 180-190kts, which is much too slow for refueling. 200-300 knts are perfect, 250 being most ideal.

**Comment by Khopa** [comment]
Indeed there was an issue with Tanker Tacan. 
However they should be setup for 220knots, it's possible that they are losing speed on turn though, i will experiment and increase speed to 260 knts for RC10.

**Comment by MysticDaedra** [comment]
Cool. I'm thinking the bug isn't related to turn speed loss, as they are holding steady at around 180-190 or lower sometimes (seems fairly random after starting the mission from ME) when flying straight. Looking forward to the new update regardless :) Thanks for your time on this fantastic mod!

**Comment by Khopa** [comment]
In fact i believe this an issue with CAS/IAS speed conversion, when i set them up for 220knots, their IAS end up being ~190knots at 15k feet which feels really slow. I now them up so the IAS is 245knots. And it works fine for me with the Hornet.

**Comment by Khopa** [comment]
But now i'm worried it might be too fast for A-10C... 🤔

**Comment by MysticDaedra** [comment]
I don't fly the A10, so I couldn't say. I can say that if the jet is pitched up 10 degrees or more just to maintain level flight, it's probably going too slow lol.

According to [this](https://www.globalsecurity.org/military/systems/aircraft/kc-130.htm#:~:text=The%20air%2Dto%2Dair%20refueling,extraction%20speed%20is%20120%20KIAS.), the standard refueling speed of the KC-130 is between 200-250kts. for "high-speed" fixed-wing aircraft. It quotes a low-speed of 130kts for helicopter refueling... which is still crazy slow and right on the full-flaps stall edge of that plane, but the plane is built for it. Slower than 200kts though and fighters like the F-18 will have a very high level of difficulty due to significantly smaller lift area on the wings.

The conversion thing might be the issue. I usually start to pay more attention to my mach speed at around 15000 feet anyways, which stays more "constant" in relation to actual ground speed than the IAS does.

**Comment by wrycu** [comment]
FYI @Khopa speed set in the ME is IAS, not TAS, resulting in unexpectedly slow speeds at higher altitudes.

It may be worth adding a conversion function, e.g. https://aviation.stackexchange.com/questions/43998/how-to-convert-ias-cas-to-tas-up-to-mach-3 so that they can move at a consistent speed.

**Comment by Khopa** [comment]
Should be Ok in latest version.

Please re-open if it is not;
