### ISSUE TITLE
Lines between capture points missing in WW2

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#363]
Frontlines and lines between capture points are missing when playing UK 1944 vs Germany 1942

[Whatever You Do, Don't Mention The War.zip](https://github.com/Khopa/dcs_liberation/files/5536281/Whatever.You.Do.Don.t.Mention.The.War.zip)

**Comment by DanAlbert** [comment]
https://github.com/Khopa/dcs_liberation/pull/360
