### ISSUE TITLE
aircraft spawn where they shouldn't due to incorrect parking data

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#371]
I bought 8 A-10s at Khalkhala and once the mission began, they all spawned one on top of the other above the runway and exploded.

Example screenshots
https://steamuserimages-a.akamaihd.net/ugc/1671360457885241710/6D2324D86DFC5EBBF66D092CCD409BCFF38700C8/
https://steamuserimages-a.akamaihd.net/ugc/1671360457885229594/E4231DCD2D2EFA54354629448EEF8816E87465FB/

In the Mission Editor, they spawn with Waypoint 0 set to "Turning Point" rather than "Start from ramp". Liberation file attached. The issue occurs consistently when the mission is generated from it.
[Viggen or Ovo Lacto Vegetarian .zip](https://github.com/Khopa/dcs_liberation/files/5542167/Viggen.or.Ovo.Lacto.Vegetarian.zip)

**Comment by DanAlbert** [comment]
Trying to place aircraft at that airfield in the ME snaps them to another airfield, so it seems there isn't actually parking for jets there. Need to send the fix to pydcs to correct the parking data, and also need to differentiate jet and help parking when buying aircraft.

**Comment by DanAlbert** [comment]
Repurposing this as a catch all for all parking related bugs.

All of the problems here come in one of two shapes:

1. A map bug: DCS told us the parking space was compatible, but it isn't.
2. Incomplete map data: the parking data lacks the fidelity to tell us if the parking space is compatible.

Problem 1 we can't fix. Problem 2 is maybe fixable, but pydcs doesn't have the data for us and we can't fix it without that data.

**Comment by DanAlbert** [comment]
Infeasible except for the parts that are covered by https://github.com/dcs-liberation/dcs_liberation/issues/1391 (which are quite narrow due to lack of data)
