### ISSUE TITLE
MiG 21 Default frequency doesn't work on VHF

### ISSUE THREAD

**Issue by Kerbo416** [dcs-liberation/dcs_liberation#377]

**Comment by DanAlbert** [comment]
Can you point me at documentation on the fishbed's radios? The current information came from https://github.com/Khopa/dcs_liberation/issues/49#issuecomment-723648915, which was apparently wrong.

**Comment by DanAlbert** [comment]
@Mustang-25 played around a bit and came up with 118MHz to 140 MHz. I adjusted to that. It's still stepping in MHz because I'm not sure what granularity it tunes in.
