### ISSUE TITLE
Ramat David Slot 31 and 32 Spawn on top of each other

### ISSUE THREAD

**Issue by Mustang-25** [dcs-liberation/dcs_liberation#379]
Placing a client aircraft in slot 31 will spawn it at slot 32 at Ramat David. I am not sure if it does the same for AI placement but I have tested it multiple times with client slots and different airframes with the same result.

**Comment by DanAlbert** [comment]
Pretty sure this is a map bug but I haven't been able to test yet.

**Comment by Khopa** [comment]
It might be worth to make a new pydcs export of the map as soon as possible since ED/Ugra has fixed some bugs.
I'll try to do one today, and see if there any differences in the parking slots.

**Comment by DanAlbert** [comment]
Duplicate of #371
