### ISSUE TITLE
Request: Ability to select start type for individual AI flights

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#387]
Would lolve the ability to select if each individual flight starts cold/warm/on runway/airborne.

**Comment by jeetsukumaran** [comment]
Just a note for the records that allowing for runway starts is one way to solve the uncoordinated package issue, in which flights do not begin taxing until parts of the taxiway are clear (which results in up to 20-25 minute delay in take-off times and packages arriving piecemeal on target). DCS nicely handles multiple runway starts and landing by AI, so there are no collisions etc.
