### ISSUE TITLE
Toggling culling zones on will hide all the units on the liberation map and just display a blank map

### ISSUE THREAD

**Issue by DanAlbert** [dcs-liberation/dcs_liberation#389]
From https://github.com/Khopa/dcs_liberation/issues/386

**Comment by Khopa** [comment]
If it was an issue with the current develop branch only, I think I fixed it here : https://github.com/Khopa/dcs_liberation/commit/fcf45554efa92b2b9baa2b981b995dd0be2e4743#

**Comment by DanAlbert** [comment]
It was. Thanks!
