### ISSUE TITLE
S-300 / SA-10 Sites Non-Functional

### ISSUE THREAD

**Issue by MedievalBunny** [dcs-liberation/dcs_liberation#39]
Currently playing against Russia 2010 on Caucuses and the SA-10 sites are all generated without tracking radars and cannot engage targets. They have both search radars and a CP, plus plenty of launchers, but are toothless without the TR.

**Comment by Khopa** [comment]
Thanks, indeed the tracking radar was missing.

This will be fixed in RC10

**Comment by Nomadzy** [comment]
Related to the s300, when I order a flight to strike the group (s300/strella/AAA) the flight keep bombing the central truck that have been bombed in a previous mission

**Comment by Khopa** [comment]
This is fixed in 2.0.10. So i'm closing this issue. 

@Nomadzy Feel free to open a new one for your specific issue with strike missions.
