### ISSUE TITLE
Ships no longer display their SAM ranges even when all the other SAM ranges are displayed

### ISSUE THREAD

**Issue by DanAlbert** [dcs-liberation/dcs_liberation#390]
From https://github.com/Khopa/dcs_liberation/issues/386

**Comment by DanAlbert** [comment]
@Mustang-25 works for me. Upload a liberation save if you see it again.

**Comment by Mustang-25** [comment]
@DanAlbert I just tested it on the latest build (Preview 429) and it still shows up. Seems to be inconsistent though, I wonder if it happens with groups with mixed ranges. Also the Molniyas never seem to show their range but it's pretty short so it might just be smaller than the icon itself. Two different Liberation saves attached below.

[no_ship_SAM_range.zip](https://github.com/Khopa/dcs_liberation/files/5568587/no_ship_SAM_range.zip)
