### ISSUE TITLE
on quit mission script error

### ISSUE THREAD

**Issue by Psych084** [dcs-liberation/dcs_liberation#4]
![immagine](https://user-images.githubusercontent.com/66530436/83951984-e4962680-a835-11ea-95b2-29ca910055dc.png)
when i quit the mission this error pop up and liberation still in state "waiting for mission completion"

**Comment by DBBR406** [comment]
You have to edit the mission scripting lua in the folder Scripts in the DCS main directory. There are three lines you have to comment out, like with the DCE campaigns for DCS. DCS liberation should do this automaticly but i don't know if only at first start or at every start, as if an update to DCS is made, the old file gets restored.
There is an ready to use file in the liberation directory at resources\Scripts\MissionScripting.lua that can be copied to the DCS scripts folder.
See [this](url) comment from Khopa at the ED forum.

**Comment by Psych084** [comment]
ok, thank you. now it work perfectly
