### ISSUE TITLE
Save / Load Functionality

### ISSUE THREAD

**Issue by Gekko312** [dcs-liberation/dcs_liberation#40]
I love Liberation and have tried to play through a campaign with a group, however post-mission hangs and other issues have made us decide to stop for now, since any issue cause us to lose all campaign progress. Is there any possibility of a save / load functionality so that if something hangs we would only lose one mission? Liberation is awesome, thanks for making it!

Gekko

**Comment by MedievalBunny** [comment]
There is a save button in the upper left next to New Game, and a save option under the File drop down. Do those not do what you want?

I've not been having any issues with post-mission hangs or lost progress.

**Comment by Gekko312** [comment]
Thanks for the response. I do see and use the save option, the issue is if there is an error and the liberation process does not complete, an earlier state can't be loaded, which means the campaign has to be restarted. If it was possible to have multiple states saved, and choose which to load, that would be ideal.

Thanks!

**Comment by MedievalBunny** [comment]
Huh, interesting, I've never had that kind of problem so didn't know it was an issue. 

A possible workaround for you: the campaign state is entirely contained within the DCS Liberation folder (where the liberation_main.exe is), so copying that folder to a backup location should save the campaign in it's current state and allow restore to that point should something go wrong. I assume there's only one file there that would really need to be backed up, state.json? I'm not sure about that, Khopa would need to verify that.

**Comment by Khopa** [comment]
In 2.0.10 there is an autosave generated after the end of each turn, you can use it to restore your progress if you forgot to save and a crash occurs.
(You can also save your progression to multiple files.)

Closing, feel free to re-open if you consider the issue unresolved.

**Comment by Gekko312** [comment]
Absolutely! Releases 10 and 11 look great. I just became a Patreon backer
too, thank you!

Greg
