### ISSUE TITLE
CAS boundaries Syria map

### ISSUE THREAD

**Issue by CaptMikeDK** [dcs-liberation/dcs_liberation#400]
Hi

After the new polygon mapping for the  CAS is off the plan, as you see in the picture.

You have to move the frontline, you boundaries, beyond the you no mapping zone.
![caszone](https://user-images.githubusercontent.com/65250502/99671262-16ace500-2a72-11eb-9af8-27ccaea76979.JPG)

**Comment by walterroach** [comment]
I'm seeing this for the frontline between Bassel Al and Hama as well. 

Save game reproducing the issue in v2.2.0 attached here, will have to investigate further later as I don't have a PC with Syria installed accessible to me at the moment.
[Bug400.zip](https://github.com/Khopa/dcs_liberation/files/5568619/Bug400.zip)
