### ISSUE TITLE
Request: Super Hercules gets implemented like the A-4E please and thank you

### ISSUE THREAD

**Issue by ToKeNeRd** [dcs-liberation/dcs_liberation#401]

**Comment by DanAlbert** [comment]
Would it serve any purpose other than looks? We don't currently have any support for logistics missions.

**Comment by Khopa** [comment]
Yes, this will depend on #383 being implemented.

**Comment by DanAlbert** [comment]
Figured. Thought maybe it carried a MOAB or something :)

**Comment by ToKeNeRd** [comment]
It would serve a purpose with Combat Drops with combined arms I can give the units orders

**Comment by ToKeNeRd** [comment]
Same purpose as the Huey

**Comment by ToKeNeRd** [comment]
> Would it serve any purpose other than looks? We don't currently have any support for logistics missions.

What about the fact you can load vehicles then cargo drop them with combined arms you can then give them orders on the fly it would serve more of a purpose than the Huey

**Comment by ToKeNeRd** [comment]
#383 talks about supply I'm more looking at combat air drops to get IFV Hummers etc on the battlefield

**Comment by Khopa** [comment]
Oh, you can do that with the current version of the mod ?
Or that would require a custom script ?

**Comment by ToKeNeRd** [comment]
> Oh, you can do that with the current version of the mod ?
> 
> Or that would require a custom script ?
> 
> 
 Darn unfortunately it needs its own trigger at mission start "C-130 Cargo" needs to be active it comes with the mod but thinking about it I would be worried about compatibility issues but yes you can cargo drop vehicles and with Combined Arms give those said vehicles waypoints or targets

**Comment by HighwaymanEd** [comment]
Heres the lua to make the cargo drops spawn the dropped item as a unit 
[Hercules_Cargo.lua.zip](https://github.com/Khopa/dcs_liberation/files/5587990/Hercules_Cargo.lua.zip)
