### ISSUE TITLE
Map UI displays 2.2.0 in 2.2.1

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#404]
![Title](https://user-images.githubusercontent.com/74509817/99745336-a9f81180-2a96-11eb-8420-9620ba50bb93.png)

Help > About dropdown also shows 2.2.0.  This is with the zip file uploaded here: https://github.com/Khopa/dcs_liberation/releases/tag/2.2.1

I'm pretty certain i'm running 2.2.1 as I can't make the size of a flight zero anymore (thanks btw).

**Comment by DanAlbert** [comment]
Not actually fixable since 2.2.1 has already shipped.
