### ISSUE TITLE
Request:  Inform the user of the Weather.

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#406]
As far as I'm aware, there's no information of the weather in the upcoming mission.  It would be nice to know what the weather is going to be in the next mission for planning purposes (Low Overcast, Foggy, Rain/Snow, Cloudy, Sunny, etc).

**Comment by DanAlbert** [comment]
I'd fiddled with briefly but gave up when I couldn't come up with a UI that I liked. If we can't find a good way to fit it into the top bar we should just make a "forecast" button that pops up a dialog with the details.

**Comment by SnappyComebacks** [comment]
I threw together some Paint magic for fun and came up with a possibility.  The little blue square in the images would be a simple picture representing the general weather outlook, like a cloud for cloudy, sun/moon for clear weather, etc.  I'm sure the spacing could be better but the general idea is there.

Without Weather Label:
![Unnanotated](https://user-images.githubusercontent.com/74509817/99889742-68da3b80-2c15-11eb-9364-fa17e5d7f089.png)

With Weather Label:
![Unnanotated2](https://user-images.githubusercontent.com/74509817/99889743-6972d200-2c15-11eb-8f4a-f80aaeac1dc2.png)

**Comment by DanAlbert** [comment]
Yeah, something like that would work well I think. I'd been trying to cram all the details into the bar and that didn't fit, but putting the details in a window sounds good.
