### ISSUE TITLE
differentiate air defenses in faction data

### ISSUE THREAD

**Issue by DanAlbert** [dcs-liberation/dcs_liberation#407]
Currently factions only have SHORADs and SAMs. Since we're missing the middle grade of air defense, we're treating SA-10s and SA-6s as equivalent during mission generation.

We should probably be defining these as long, medium, and short range air defenses, since the faction and era will determine what the use is.

**Comment by Mustang-25** [comment]
It might also be worth differentiating EWRs if you guys haven't already. Having them distributed across the map and not just at airfields gives the IADS some cushion and also gives players more mission variety.

**Comment by DanAlbert** [comment]
EWRs are already differentiated in 2.2.

**Comment by DanAlbert** [comment]
https://github.com/Khopa/dcs_liberation/commit/0e807d84c2e60c1b717053dc00f8b04b382144bd did this globally, no need for factions to adapt.
