### ISSUE TITLE
AI flights won't spawn on aircraft carrier

### ISSUE THREAD

**Issue by Rizn-Nuke** [dcs-liberation/dcs_liberation#413]
No AI flights spawning on the carrier. Harrier flights from the LHA work fine.
The flights do not appear in the DCS mission editor.
Problem present both when using delayed start and start ASAP.
AI wingman in a flight with a client will spawn normally.
AI flights will not spawn whether in a 1-flight-package or in combination with other flights (even with clients in the other flight)

**Comment by DanAlbert** [comment]
Can you upload your liberation save? I fly with AI off the boat all the time and haven't seen the issue.

**Comment by walterroach** [comment]
I've not been able to reproduce this issue.  Can you upload the save game where you're seeing it?

*Too slow.

**Comment by Rizn-Nuke** [comment]
[Mission_1_Iran_Light.zip](https://github.com/Khopa/dcs_liberation/files/5576575/Mission_1_Iran_Light.zip)
Here's the file.

**Comment by DanAlbert** [comment]
> 2020-11-20 17:32:05,383 :: INFO :: Flight not generated: culled

The flight was culled because it's too far from the front line.
