### ISSUE TITLE
Mig-21 has invalid frequency by default

### ISSUE THREAD

**Issue by Boozdeuvash** [dcs-liberation/dcs_liberation#418]
When saving the Liberation mission in the editor with a playable Mig-21, we are now served with an error that 100 or 101MHz is not a valid frequency. This refers to the frequency listed with "radio" in the unit main panel. The correct frequency should be the same as the one listed in channel 0 of the "Radio Preset" tab for the same unit, for instance 118MH.

Workaround: change the frequencies manually in the editor before saving. Not a huge deal but here you go.
![DCSradiobug](https://user-images.githubusercontent.com/11238791/99888037-99d46380-2c49-11eb-99a1-53d4000f9637.PNG)

**Comment by DanAlbert** [comment]
https://github.com/Khopa/dcs_liberation/issues/377

**Comment by Boozdeuvash** [comment]
@DanAlbert sorry for the duplicate, I searched for "Mig-21" but forgot to remove the "is closed" switch...

**Comment by DanAlbert** [comment]
No worries. Now you'll know for next time :)
