### ISSUE TITLE
no "you won" message at the end of a campaign

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#419]
I have reached the end of the "Invasion Of Iran" campaign.  When I click "Accept Results" on the mission status screen, nothing happens, and the terminal throws an error.  I can't finish the campaign (What happens when you finish, anything?  Just curious.).  I started the campaign in Liberation 2.2.0, switched to 2.2.1 halfway through, and have Skynet enabled.

![CampaignScreen](https://user-images.githubusercontent.com/74509817/99889214-2c581100-2c10-11eb-9993-9e7e96f1adae.png)

I have attached the campaign (from right before starting the last mission), the last mission, the state.json (after completing the last mission) and the terminal output (after spam clicking Accept Results a few times).

[CantCompleteInvasionOfIran.zip](https://github.com/Khopa/dcs_liberation/files/5578574/CantCompleteInvasionOfIran.zip)

**Comment by DanAlbert** [comment]
There isn't any fancy "you won" at the end, it just ends like that. Will turn this into an FR.
