### ISSUE TITLE
AI Su-33 from carrier crash on takeoff

### ISSUE THREAD

**Issue by entropyembrace** [dcs-liberation/dcs_liberation#42]
AI operated SU-33s following missions generated by Liberation crash immediately on takeoff from the Russian aircraft carrier. They jump off the ramp and crash into the water with an ejection attempt just before impact. 

I do not have supercarrier.

**Comment by Khopa** [comment]
Hi, 

I have also noticed it, and fixed the issue for the upcoming release by reducing their startup fuel level so they can actually takeoff.

(It also seems that the AI Su-33 will also always use the short runway on the Kuznetov, but i can't really do anything about this.)

**Comment by Khopa** [comment]
This should be fixed in 2.0.10

Please re-open if you encounter the issue again.
