### ISSUE TITLE
Request:  Consider Terrain Geometry When Placing SAMs

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#423]
In the most recent campaign I played (Invasion of Iran), long and medium range SAM's had some interesting placements.  It might be a good idea to implement something that enforces where a SAM can and cannot be placed in relation to the terrain.  This would benefit the SAM's threat circle coverage.

See the two following examples:

1) Here is an SA-2 on the side of a mountain:
![SA-2_Mountain](https://user-images.githubusercontent.com/74509817/99893283-43602880-2c3b-11eb-877d-2e1ac136aad1.png)

2) Here are three pictures of an SA-10 nestled in crevice of a hill/mountain:
![SA-10_Nestled](https://user-images.githubusercontent.com/74509817/99893338-fdf02b00-2c3b-11eb-923c-3b11fef85ff5.png)
![SA-10_Context_1](https://user-images.githubusercontent.com/74509817/99893351-182a0900-2c3c-11eb-9882-9da25bd9cc84.png)
![SA-10_Context_2](https://user-images.githubusercontent.com/74509817/99893353-20824400-2c3c-11eb-9da8-c8c1e0b7a66b.png)

**Comment by DanAlbert** [comment]
We don't (and practically can't) _know_ the terrain geometry at mission creation time, so we can't make decisions based on it.

The problem itself is being solved by having preset spawn locations though.

**Comment by SnappyComebacks** [comment]
> We don't (and practically can't) _know_ the terrain geometry at mission creation time, so we can't make decisions based on it.

Bummer, I guessed that was a strong possibility and the reason it hadn't been done.

**Comment by DanAlbert** [comment]
If someone knows how to get terrain data out of the DCS campaign files there's a lot we'd like to do with it, but without that we have no way to do it :( We could try using real world altitude data, but I don't know how well that matches to DCS data (or what date the DCS data is from)
