### ISSUE TITLE
Additional aircraft inventory views

### ISSUE THREAD

**Issue by DanAlbert** [dcs-liberation/dcs_liberation#428]
Should add:

- [x] A UI showing all unused aircraft
- [x] A UI showing *all* aircraft, with their assignments

**Comment by jeetsukumaran** [comment]
As per discussion on Discord, a "big picture" overview of tasking (showing assigned and unassigned) aircraft would be useful
![Screenshot from 2020-11-22 04-05-21](https://user-images.githubusercontent.com/26183/99903377-d7041a00-2c78-11eb-8022-3c04ce58507b.png)
Above is much more complex than needed, but gives an idea of what mission planning software shows. For this case, maybe just aircraft type/ base/ mission type/ flight assingment/ mission objective (target)/ client or AI would be good enough? Bonus would be if, e.g, mission type / flight is clickable to take you to edit dialog!

**Comment by walterroach** [comment]
For this: 
> A UI showing all aircraft, with their assignments

I'd also recommend adding the previous turn inventory.  Often I just want to replace what is lost, but can't remember.

**Comment by DanAlbert** [comment]
Better yet: https://github.com/Khopa/dcs_liberation/issues/539
