### ISSUE TITLE
Option to Add Resupply Vehicles to SAM batteries

### ISSUE THREAD

**Issue by jeetsukumaran** [dcs-liberation/dcs_liberation#429]
Would it be possible to have an option to add vehicles capable of resupply near SAM batteries? They need not be the same group, but need to be close.

GAZ-66
KAMAZ-43101
GAZ-3308
KrAZ-6322
M818
Ural-375
Ural-4320 (either)

This would allow SAM's to rearm. 

Information on rearming: 

> https://forums.eagle.ru/forum/english/digital-combat-simulator/dcs-combined-arms/136642-what-is-an-ammunition-truck/page2
> 
> "FARP, warehouses (anything in warehouse static object category), and "warehouse" ground units radius appears to be 200m.
> 
> Ground units that can rearm other ground units: KAMAZ-43101, Ural-375, Ural-375 PBU, Ural-4320-31, Ural 4320T, Gaz-3308, Gaz-66, M818. If placed as static objects they can also be used to rearm ground force"

And info on SAM battery composition/organization: https://www.airgoons.com/w/DCS_Reference/Air_Defences

**Comment by HighwaymanEd** [comment]
These would be good re-supply missions for Helicopters too to take underslung loads out to some of the 'lighter' missile sites, although it might be run trying to watch a Gazelle lift an SA-2 reload ;)

Conversely, they'd make good BAI missions from the other side as well to prevent re-supply of defenses, artillery, and front line units, and prevent Artillery from firing for a turn for example if they don't get their re-supply.

**Comment by DanAlbert** [comment]
@HighwaymanEd https://github.com/Khopa/dcs_liberation/issues/383

**Comment by walder** [comment]
fyi: with skynet sam sites will not rearm when dark since ai is turned off. however once they are out of ammo they go dark with ai on allowing them to
rearm.

**Comment by RndName** [comment]
This can now be easily achieved with the new Layout system introduced with #1989

You can add an optional Group to a layout with the unit_class "Logistics". Whenever the faction has access to one of these units it will be added to the layout. To bring in some randomisation it is also possible to set the Unit_count to [0, 1] which will randomly pick either 0 or 1 logistics units.

Example on how we already use it: https://github.com/dcs-liberation/dcs_liberation/blob/develop/resources/layouts/anti_air/6_Launcher_Site.yaml#L33-L39
We already have a unique (generalized) Layout like this 6_Launcher_Site layout linked here. But as this is still an ongoing process not all SAM sites have been adopted to this new system yet. You can see all Anti Air layouts in this folder: https://github.com/dcs-liberation/dcs_liberation/tree/develop/resources/layouts/anti_air

It is also possible to buy them via the UI if an existing SAM Site does not have the logistics unit (if randomization chosen 0). This requires the Layout to have the logistics group defined in the first place!

More info about the Layout system is in the WIKI: https://github.com/dcs-liberation/dcs_liberation/wiki/Layouts
