### ISSUE TITLE
AWACS not being generated

### ISSUE THREAD

**Issue by scottrhoyt** [dcs-liberation/dcs_liberation#431]
Just started a new campaign on a build of 29d3b5dfc630faea8e9a5be7b469757a2b6daf2b. 2005 USA vs 2010 Russia on Western Georgia. My (2005 USA) AWACS isn't present in missions. Given the lack on AWACS info on the kneeboard, I'm guessing it isn't getting generated. Attached is my save.

[AWACS Bug.zip](https://github.com/Khopa/dcs_liberation/files/5580982/AWACS.Bug.zip)

**Comment by walterroach** [comment]
This is fixed in build 502
