### ISSUE TITLE
Syrian faction uses aircraft it does not have access to

### ISSUE THREAD

**Issue by DanAlbert** [dcs-liberation/dcs_liberation#433]
The current Syrian factions are using a handful of aircraft that they don't actually have access to according to DCS:

* MiG-29S (though they can use the A)
* MiG-25
* Su-17
* Su-24
* Mi-24
* Mi-8

Could either change the aircraft they have access to or move them to CJTF Red.

**Comment by Khopa** [comment]
As discussed on discord, changed the country of Syria 2011 to CJTF Red

68818ae50dccda7557a8b18f904679dc6fdd4693
