### ISSUE TITLE
AI CAS acts as CAP with racetrack waypoints and do not engage targets in 2.2.0

### ISSUE THREAD

**Issue by JaySpidey** [dcs-liberation/dcs_liberation#434]
AI CAS acts as CAP with racetrack waypoints and do not engage targets in 2.2.0
They have 2 waypoints called racetrack start and end, and they have an orbit in the advanced waypoint options. They are set to CAS

[tmpsave.liberation.txt](https://github.com/Khopa/dcs_liberation/files/5582009/tmpsave.liberation.txt)
[liberation_nextturn.txt](https://github.com/Khopa/dcs_liberation/files/5582012/liberation_nextturn.txt)

**Comment by DanAlbert** [comment]
Planned at the wrong objective. 2.2.1 would not have allowed this to be planned.
