### ISSUE TITLE
[REQUEST] Add USA 2020 and include F-22 Raptor mod

### ISSUE THREAD

**Issue by TrueCrazyMan** [dcs-liberation/dcs_liberation#435]
Making USA 2020 with the F-22 Raptor would be great so it can compete with Russia 2020.

**Comment by Khopa** [comment]
Do you have the link of the latest version of the mod ?
I think there was two variants of this mod by different modders at some point, which one should be favored ?

**Comment by TrueCrazyMan** [comment]
https://drive.google.com/file/d/1aLDbSvkgOnwv4C-xtdc_dfMXNROynl_c/view?usp=sharing
This is the most current version released by Growling Sidewinder.

**Comment by DanAlbert** [comment]
Would recommend making a "USA 2005 (modded)" and "Bluefor Modern (modded)" rather than USA 2020. Raptor has been flying for a long time and we don't have F-35s to add :)

**Comment by Khopa** [comment]
Done on dev branch in ed96bc83b4481b4fc7477fd99aeb95624c9714f4
