### ISSUE TITLE
Generate Air Support for red

### ISSUE THREAD

**Issue by walterroach** [dcs-liberation/dcs_liberation#436]
https://github.com/Khopa/dcs_liberation/blob/24844571833b70bb577fe8519c28b1349c00952b/game/operation/operation.py#L61-L61

**Comment by walterroach** [comment]
Currently red doesn't get AWACS or refueling.

**Comment by Mustang-25** [comment]
The implementation is half complete now with the introduction of taskable AWACS. If someone wanted to apply the same to tankers we could close this FR out.

**Comment by DanAlbert** [comment]
Assigning @SnappyComebacks because https://github.com/dcs-liberation/dcs_liberation/pull/1180 finishes this.
