### ISSUE TITLE
AI flights crash

### ISSUE THREAD

**Issue by BigBoss329** [dcs-liberation/dcs_liberation#44]
AI flights do not RTB when they are running low on fuel/run out of proper weapons. They keep engaging enemies until they crash, also the pilots never eject.

Example 1:
Pair of F-15Cs on CAP move in to engage enemy fighters, drop the fuel tanks during BFM. Shoot down all bandits, then go back to continue original flight path. If an enemy air asset spawns in the meantime they turn back to engage until they run dry. If they do not have missiles, they go in for a dog fight.

Example 2:
A-10s on CAS mission never give up, they keep engaging enemies until the last bullet in the 30 mm. They last longer than the F-15s, but I have infantry enabled, so they go after each and every foot soldier until they loose all fuel and crash. 

Edit: I understand this issue is likely caused by DCS AI being inconsiderate of fuel levels, so I suggest giving AI flights unlimited fuel, if possible and there is no other solution. It is rather annoying that I have to waste money on restocking flights, because they were stupid and let themselves run dry.

**Comment by Khopa** [comment]
In 2.0.10, the AI should be setup to RTB on Bingo fuel; 
In 2.0.11, the AI is setup with restriction on Afterburner use. (They will only use it when they need too)

This should improve their behaviour.

**Comment by BigBoss329** [comment]
Their behavior did improve a lot. Thank you!
Finally I see sorties returning to base. 

However, CAS flights still stray away from their intended AO, as they insist on attacking whatever ground units they can detect, even far behind enemy lines. A-10s are especially suicidal, but they usually end up getting shot down, before they run out of fuel. I am not sure if it would be possible, to limit CAS engagement range, to strictly encompass the front line. This would prevent flights from attacking heavily entrenched targets deep within enemy territory.

**Comment by DanAlbert** [comment]
Wandering CAS is fixed in 2.2.
