### ISSUE TITLE
briefing waypoint indices off by one

### ISSUE THREAD

**Issue by foxwxl** [dcs-liberation/dcs_liberation#441]
JF-17 WPT in aircraft system does not match the briefing. (ie. TGT at WPT4 on aircarft will show as WPT5 in briefing)
Note, Jeff's WPT0 is only for INS alignment.

ALSO, the turn number in the briefing is one round less than that on the GUI. First round will alreay be the buying round and mission begins at 'turn 2', but the briefing will shows 'turn 1'.

**Comment by DanAlbert** [comment]
Not unique to the JF-17. All briefings start numbering at 1, and the kneeboard (and aircraft) start at 0.
