### ISSUE TITLE
AI tasking improvement for ai_flight_planner_db.py

### ISSUE THREAD

**Issue by foxwxl** [dcs-liberation/dcs_liberation#443]
I've edit the https://github.com/Khopa/dcs_liberation/blob/17fe977b06cb3c29561239636cf16636a14cd84e/gen/flights/ai_flight_planner_db.py to for more suitable AI tasking.
I mainly focused on Modern era.

[ai_flight_planner_db_v2.zip](https://github.com/Khopa/dcs_liberation/files/5588679/ai_flight_planner_db_v2.zip)

**Comment by foxwxl** [comment]
#442 AJS37 anti-ship mission included in this file.

**Comment by Khopa** [comment]
Thanks, I integrated most of your changes on dev branch.

**Comment by HighwaymanEd** [comment]
Late to the party, but I'd drop the Harrier from the updated SEAD preferred section. Whilst it is SEAD capable, the Sidearms are not going to do much for an AI pilot that is tasked with them as they wont employ such a short range SEAD weapon properly and you'll end up with a lot of dead (pardon the pun) Harriers.

**Comment by Khopa** [comment]
> Late to the party, but I'd drop the Harrier from the updated SEAD preferred section. Whilst it is SEAD capable, the Sidearms are not going to do much for an AI pilot that is tasked with them as they wont employ such a short range SEAD weapon properly and you'll end up with a lot of dead (pardon the pun) Harriers.

I agree, they should be a last resort SEAD flight choice.
