### ISSUE TITLE
A2A Refueling Interim Request

### ISSUE THREAD

**Issue by Mustang-25** [dcs-liberation/dcs_liberation#444]
Before #288 is fully fleshed out, I'd like to request some adjustments to the current tanker tracks.

Currently, the tankers are all set to 250kts and result in them being either too slow or too fast for basically all the jets that can/need to refuel. The boom for fast jets should be 310kts (the Viper dash 1 details 310 KIAS at 30k ft) while the boom for the A-10 should be about 200-220 KIAS (the A-10 dash 1 states 220 KIAS at 15k ft). Similarly, the basket should should be around 260-270 (Harrier NATOPS recommends 275 KIAS and altitudes above 10k ft while the Hornet NATOPS only provides a range of 200-275 KIAS without a specific recommendation. The Tomcat NATOPS says 240 KIAS is recommended but has a range of 170-300). 

Additionally, both tankers right now fly at the same altitude and, since they fly at the same speed, also fly relatively close to each other. This can make navigating to them and identifying the correct tanker slightly harder given the current limitations of the tanker implementation in Liberation.

Thus my recommendations are as follows:
1. Increase the speed of existing tankers to reflect the speeds above
2. Separate the tankers by at least 1k-2k ft of altitude
3. Add a third slow boom tanker for the A-10

**Comment by HighwaymanEd** [comment]
Not sure if adding yet another script to this is even feasible, but the Recovery Tanker within Moose is fantastic for having an S-3 over the Carrier Battle Group, or even having any tanker anywhere (over a stationary or moving unit). It also has the benefit that if the tanker runs low on gas, another would launch to take its place.

**Comment by walterroach** [comment]
KC130, KC135, and KC135 MPRS will now be separated by altitude.  Airspeeds for these three have been adjusted as you noted above as well.   

Adding a second boom tanker for the A10 isn't easy to do with the current way they're generated since the generator makes one of each tanker type available to the faction.  Probably won't get anything in for the A10 to drink from until we overhaul the air support generation in #288

**Comment by Mustang-25** [comment]
To reiterate our conversation in the discord, based on my conversations with pilots, the MPRS should be set at 270kts as a good compromise between the Harrier and Hornet. And given the speed limitation, leave the KC-130 at the previous 250kts.
