### ISSUE TITLE
Can placement of AWACs be tuned - Often the AWACs aircraft are placed deep in enemy territory

### ISSUE THREAD

**Issue by qwertymanisalive** [dcs-liberation/dcs_liberation#445]
This is a low priority request - I understand the AWACs are immortal/invisible to enemy aircraft but their placement looks strange on the map when they are patrolling deep in enemy territory. 

Is there a way to place them more realistically in friendly airspace?

Playing 2.2.1

**Comment by DanAlbert** [comment]
https://github.com/Khopa/dcs_liberation/issues/288 covers this, I think.

**Comment by qwertymanisalive** [comment]
Sounds good, I will close this out
