### ISSUE TITLE
A_I will not engage 

### ISSUE THREAD

**Issue by walkingtallem** [dcs-liberation/dcs_liberation#45]
First of all, let me give you a million at-a-boy's for having the mind set to create such an engine for DCS, that enables us as single players to play at this level. You will one day, perfect this engine, and hopefully allow us in the DCS world to give you the ideas to help you make it better. In the long run you will be the one to remember after all is said an done. So, let me thank you for a job well done and an idea well thought of. 
Now to help make this better, you have a master piece in the making but, there are some glitches. Microsoft was not made in one day or year and still has updates and glitches. So, the issue I encountered is that the A_I that fly's as a wingman with you refuses to engage targets both in the air and on land. He just calls out targets and gets annoying if you get my drift. There is already plenty of that going on. If I may suggest, and if it could be done, could the person entering the mission set up his wingman the way he or she want to set them up? I mean like in the mission editor? That way we could get him to engage or attack air defenses or airborne targets. Second thing I encountered was that the carrier for some reason when I asked to land it told me to divert to secondary and not knowing what my secondary was I chose the closest to me, why I don't know so I did. The very next mission I guess I was supposed to take off from the base I landed on but I was back on the carrier. No big deal just a simple question. I mean with all you've done so far I'm really asking too much.  The third thing I noticed and this is because I was on a carrier was that the small ships were right on top of the carrier. What I mean is that there was no spacing, when the aircraft take off from the Bow they normally break right and travel at 500 feet AGL for 7 nm for a case one launch and recovery so they don't interfere with the marshal stack or the incoming aircraft breaking to enter the pattern at 800 feet above and to the right of the carrier. It was kind of hard to do this with the small ships so close, I mean sitting in the cockpit I could not see the water between the carrier and the small ships. Small corrections but again let me congratulate you on a fantastic idea and job that will get better. My email is walkingtallem@gmail.com I am former US Navy I worked on F-14's as an ordnanceman, so if you have questions feel free to email me and ask me questions. Also the small ships did not travel that close to the carrier while out at sea they were only that close only for pictures.

**Comment by DanAlbert** [comment]
I don't think there's anything left to do here. We can't fix the DCS AI, and I don't think the other issues exist any more.
