### ISSUE TITLE
[Request] Training

### ISSUE THREAD

**Issue by HighwaymanEd** [dcs-liberation/dcs_liberation#452]
I've been wondering about having training as an option to spend your budget on to increase the skill of your pilots and units, and or if they score so many victories, or fly so many missions their skill would increase naturally.

default = Trained
$10m = Veteran, delivered in 3 turns (occurs naturally after 10 missions)
$30m = Ace, delivered in another 6 turns (occurs naturally after 30 missions)

Of course, if a unit is killed, the replacement comes in as Trained, and you start again...

**Comment by DanAlbert** [comment]
https://github.com/Khopa/dcs_liberation/issues/276
