### ISSUE TITLE
Tanker not usable

### ISSUE THREAD

**Issue by FgPunisher** [dcs-liberation/dcs_liberation#453]
I noticed that I am unable to perform the refuel request. When I try to contact the Tanker regardless of my current aircraft I get no answer from the tanker. Double checked my frequencies etc. but this issue seems to be not on my side.

**Comment by DanAlbert** [comment]
Did someone move them using combined arms? It's very easy to do accidentally. Combined arms completely interrupts the group's flight plan, and refueling is part of the flight plan. If you order a tanker to move there's no way for it to resume its mission.

**Comment by FgPunisher** [comment]
no as I am not owning Combined Arms so this seems not be related to it

**Comment by DanAlbert** [comment]
Upload the mission file please. Let us know what aircraft you tried, what version of liberation you're using, and if you're using any mods.

**Comment by FgPunisher** [comment]
ok I included my mission file. I was trying this one with the A10Cv2 but I already tried it also in other missions with F16C and FA18C. 
I am using the latest liberation version.

[Mission File.zip](https://github.com/Khopa/dcs_liberation/files/5603884/Mission.File.zip)

**Comment by DanAlbert** [comment]
Texaco is responding on UHF using the frequency shown on the kneeboard. Check that your radio is set correctly, that you're using the right one to make the call, and calling the right tanker.

**Comment by FgPunisher** [comment]
well thanks for your help but I am not a beginner. I have more then 1000h in DCS so I might know how to contact the tanker. I double checked that everything is set right in the radio panel including that I contact the right tanker. As every other mission is working for me right and I am able to contact there the tanker I am 100% sure that this issue is not on my site.

I am only using vr shader mod and as this one alters only shaders I do not know how it would interference with liberation in this particular case.

**Comment by DanAlbert** [comment]
> I am 100% sure that this issue is not on my site.

It worked for me, so it definitely is something in your configuration that isn't in mine. The usual answers in this situation are that easy comms are interfering or that you've keyed the wrong radio (depending on your settings you might be expecting `\` or the equivalent "all of the radios" menu to work; afaik it doesn't), used a preset channel for the wrong radio (not an issue for the A-10), or are using a mod that is breaking radios (vaicom has been known to).

If it's none of those things I'm out of ideas. It works for me and I've followed your workflow as described. If I can't see the problem there's nothing I can do to fix it.
