### ISSUE TITLE
[Request] Option for having Dot labels but only for aircraft

### ISSUE THREAD

**Issue by FinnSwede** [dcs-liberation/dcs_liberation#455]
As title says. Attached is a liberation generated .miz file where the labels were set to dot only and then an additional .lua file added manually into the miz that disables the dots for ground units while leaving the dots for air units.  Greatly helps with seeing air targets and doesn't make the ground warfare a cakewalk.

[liberation_nextturn.zip](https://github.com/Khopa/dcs_liberation/files/5599651/liberation_nextturn.zip)

**Comment by walterroach** [comment]
This would need to be added to pydcs since that's what saves our mission files, and it doesn't have any API for inserting the "Config" folder. 

I guess we could unzip, inject, then rezip, but I think that's asking for trouble.

**Comment by Mustang-25** [comment]
This can be done at the user end by editing the labels lua. Should we close this one out? I don't think Liberation should really have any effect on which labels the user wants to display.
