### ISSUE TITLE
Add Bingo and Joker to Kneeboards

### ISSUE THREAD

**Issue by kavinsky** [dcs-liberation/dcs_liberation#463]
Issue opened for discussion and keep track of the feature.

Make Kneeboards show bingo and joker fuel calculation on the kneeboard.

### Formula calculation
Since every jet has his own formula to calculate both values, we make a "universal" formula.

**Bingo:**
```
Fixed Value for Minimum Emergency Fuel
+ Fixed Value  for (Visual Traffic Navigation OR IMC Traffic Navigation)
+ Distance(nm) from (Egress WP OR Farthest TGT WP) to Arrival APT * Fuel per mile at MIL power
+ Divert Margin: Distance(nm) from (Egress WP OR Farthest TGT WP) to divert APT
```

**Joker:**
```
Joker:
Bingo + Minimum Emergency Fuel
```

**Example for F16**

```
Distance from TGT WP to Arrival APT: 100nm
Distance from TGT WP to Divert APT: 130nm

1000lb
+ 250lb (Visual Traffic applied)
+  100 * 15lb
+  130 * 10lb

Bingo: 4050lb
Joker: 5050lb
```

**Comment by walterroach** [comment]
For the hornet, the bingo chart in the dash 2 basically translates to the below.  This assumes a specific configuration *and* that you fly the bingo profile (which is way more efficient than flying MIL power at some lower altitude- the bingo profiles range from 7k to 40k feet depending on distance, and the speeds are highly variable with drag index). 

**F/A-18C (30k pounds zero fuel weight, 250 drag index, no headwind component):**
*This is draggier and heavier than most pilots will be on RTB*

"Rule of Thumb": 1500 lbs (minimum emergency fuel) + 15 lbs per nautical mile

For the example flight you gave, and assuming adding 1k pounds for joker is appropriate:

```
Distance from TGT WP to Arrrival APT: 100nm
Distance from TG WP to Divert APT: 130 nm

1500 lb
+ 100 * 15
+ 130 * 15

Bingo:  4950
Joker: 5950
```

**Comment by DanAlbert** [comment]
Initial implementation of this has merged into develop. It's not aircraft specific yet.
