### ISSUE TITLE
[REQUEST] Make AI resign option

### ISSUE THREAD

**Issue by jojom4n** [dcs-liberation/dcs_liberation#467]
I think that it could be realistic to include a "Make AI resign" option, when AI has no possibility to come back from a doomed situation (usually when it owns only one control point and it has no more defences and A/A aircrafts).

**Comment by DanAlbert** [comment]
There is no "you won" screen. What would that button do?

**Comment by jojom4n** [comment]
I missed the non-existance of the "you won" screen, since I was still completing first campaign :)

Anyway, I wasn't talking about a button, but about the possibility for AI to resign - on its own - if it should think to be unable to recover from a doomed situation.

**Comment by DanAlbert** [comment]
Sounds like nothing to do in the absence of game end conditions. Lmk if I've misunderstood.
