### ISSUE TITLE
Request:  Flight plans should minimize time in hostile SAM coverage.

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#475]
A few of the flights I make enter threat circles of multiple SAM systems at the same time, I think it would benefit the package if the flight plan minimized time/distance within threat circle coverage.  The flight path would consider the overlapping threat circles, as well as threat circles in the ingress/egress path.  

![Example](https://user-images.githubusercontent.com/74509817/100488414-5788a780-30cb-11eb-8d93-fcdc058f4eb9.png)

**Comment by DanAlbert** [comment]
Related to https://github.com/Khopa/dcs_liberation/issues/292
