### ISSUE TITLE
Strike target waypoints are below terrain on Syria Map

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#476]
On the Syria Map with a cold started A10C_2, the strike target waypoints appear underground.  The "Land" waypoint at the starting airfield appears at the correct elevation however.

This has happened to me on two different Syria strike missions, one target was a SAM, and the other a factory.

![ZoomedIn](https://user-images.githubusercontent.com/74509817/100488840-cd8e0e00-30cd-11eb-9795-8272c41a89cc.png)
![ZoomedOut](https://user-images.githubusercontent.com/74509817/100488842-cf57d180-30cd-11eb-9009-8eb374b6e4a3.png)

**Comment by DanAlbert** [comment]
https://github.com/Khopa/dcs_liberation/issues/425
