### ISSUE TITLE
Units don't always progress after a capture event.

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#477]
In two different campaigns (Invasion of Iran and Inherent Resolve) a base capture doesn't move the ground forces to the next airbase in the line, and leaves them at previous airfield in the line.  This requires purchasing new ground units and selling the old ones, and leaves the newly captured base defenseless until new ground units are purchased.  When this scenario happens, the tankers don't advance to the most recently captured airfield as well.

The only thing I can think that's common between these two cases are that I purchased air + ground units at the last friendly airfield in the same turn as I capture the next one.

I have a before/after campaign/states if needed.

**Comment by DanAlbert** [comment]
Was mostly fixed in 2.4, with a small remaining broken case in the report you linked.
