### ISSUE TITLE
Cleanup heading references and formulas

### ISSUE THREAD

**Issue by walterroach** [dcs-liberation/dcs_liberation#478]
https://github.com/Khopa/dcs_liberation/blob/45361b57a7f7b9405c1422cd01ee4f7251876c9b/game/utils.py#L47-L54

> I think this is equivalent to `(h + a) % 360`.
(if you wanted to get really fancy, you could make a `Heading` class that hides all this and gives us some extra type safety)

_Originally posted by @DanAlbert in https://github.com/Khopa/dcs_liberation/pull/474#discussion_r531809700_

**Comment by walterroach** [comment]
https://github.com/Khopa/dcs_liberation/pull/474#discussion_r531809798

**Comment by bgreman** [comment]
#1386 will go into 4.x, #1387 is a breaking change so will go to 5.x

**Comment by bgreman** [comment]
Closing as the associated PR will not be merged.

**Comment by bgreman** [comment]
Reopening as PR might be merged.
