### ISSUE TITLE
More JTAC Options/Autolaze Smoke Blacks Out Targets on TGP @ Night

### ISSUE THREAD

**Issue by furiouscaulks** [dcs-liberation/dcs_liberation#48]
While you can disable it in the config files, an option to disable smoke at night in the settings would be nice.  The smoke on target blacks out the tgp at night, it's a graphical glitch.  Conversely, having a predator designated as an invincible JTAC as opposed to using Autolaze for those of us who still like to go through the process of reading the 9line.

**Comment by Khopa** [comment]
Good idea, in 2.0.11, it will be possible to disable JTAC smoke markers : 

![image](https://user-images.githubusercontent.com/2546901/90323114-078f3600-df5d-11ea-8e26-d2f6f769179a.png)

**Comment by furiouscaulks** [comment]
A bug report pertaining to JTAC - Laser codes above 1688 will not work, the second JTAC laser can't be entered with the code of 1689

**Comment by furiouscaulks** [comment]
Also, it's next to impossible to track JTAC targets that are moving.  First, the JTAC message screen disappears too fast, you don't have time to enter in the MGRS info, so you have to continuously reopen the prompt to get all the info.  As a result of this, moving ground vehicles MGRS will change each time you open the window rendering the coordinates next to useless unless you wait for the vehicle to stop moving.  As a result, you have to use smoke in order to discern which laser is painting which target without being able to input the coords.

**Comment by Khopa** [comment]
Thanks for reporting all these issues. 

> A bug report pertaining to JTAC - Laser codes above 1688 will not work, the second JTAC laser can't be entered with the code of 1689

Indeed, fixed in 2.0.11. 

> Also, it's next to impossible to track JTAC targets that are moving. First, the JTAC message screen disappears too fast, you don't have time to enter in the MGRS info, so you have to continuously reopen the prompt to get all the info. As a result of this, moving ground vehicles MGRS will change each time you open the window rendering the coordinates next to useless unless you wait for the vehicle to stop moving.

I see, I Increased JTAC message duration to 25s instead of 10s in 2.0.11.

**Comment by Khopa** [comment]
I'm closing this one, but feel free to open a new issue if you have other problems with JTAC.
