### ISSUE TITLE
Ground unit routes move 1.3nm, not 13nm, in aggressive stance.

### ISSUE THREAD

**Issue by Techiastronamo** [dcs-liberation/dcs_liberation#481]
Running v2.20 on the persian gulf full map with USA 2005 and USSR 1975 coalitions, noticed this as an issue on other maps as well so I think this is just an error in the program. It seems that ground unit routes are set a tenth of what they're supposed to be (according to the wiki which says 13nm or 16km, yet they only advance 1.3nm or 1.6km).

Screencap: https://imgur.com/a/GqSyWMx

**Comment by walterroach** [comment]
It's more likely I wrote it wrong in the wiki and the existing behavior is what was intended.

**Comment by Techiastronamo** [comment]
Ah ok, 1.3nm seems a bit close anyhow if I can somehow modify that but that makes sense then I suppose.
