### ISSUE TITLE
[Request] Resource capper

### ISSUE THREAD

**Issue by HighwaymanEd** [dcs-liberation/dcs_liberation#483]
To help those with frame rate issues and DCS performance problems (I'm looking at you(me) VR players), I'd like to request a resource CAP that would apply to both the AI and the Human player.

My initial idea was based around a Marine Expeditionary Unit (MEU) deployment with a single LHA and support ships, or ground-based depending on the map, with 6 Harriers, 6 Hueys/CH-53 & 6 KA-50/AH-1 and 1 company of armor, 1 of mech inf, and 1 of supporting units like SAM's and Artillery.

With this Idea, the player gets a 'template' of units deployed at the start point, and money would be used to purchase supporting units only, such as E-3 coverage, or a KC-130, or every 2 days, they can replace losses, but no additional units beyond the starting scope are allowed.

The opposing AI would need an equal constraint on the limit of deployable units, along with similar unit makeups, but it should lead to some interesting limited conflict scenarios.

**Comment by DanAlbert** [comment]
@walterroach is this similar to the companies feature?

**Comment by walterroach** [comment]
Not explicitly, but it could be incorporated.  The way I see that working would be an option to disallow both red and blue to add new companies.

#586 is what we're referring to @HighwaymanEd

**Comment by HighwaymanEd** [comment]
> #586 is what we're referring to @HighwaymanEd

Yep, I think that would work 👍
