### ISSUE TITLE
Get rid of weird lines on CP

### ISSUE THREAD

**Issue by walterroach** [dcs-liberation/dcs_liberation#484]
This is related to something going wrong with https://github.com/Khopa/dcs_liberation/blob/29b894f8b0be983bc1fc93055b730eb18536a074/qt_ui/widgets/map/QLiberationMap.py#L451-L464

I've played with a few different algorithms, but haven't been able to get rid of the line artifact while preserving a decent curve for the rest of the frontline path.

![image](https://user-images.githubusercontent.com/37820425/100529226-cee13880-31aa-11eb-9e56-485417a09739.png)

**Comment by DanAlbert** [comment]
I got rid of that whole UI, so done :)
