### ISSUE TITLE
Dev Build 596 Testing Feedback

### ISSUE THREAD

**Issue by Mustang-25** [dcs-liberation/dcs_liberation#486]
1. Su-30s die on spawn at the HASes in Khalkalah. Probably they are too big for the space so it's more of an Ugra problem than a Liberation one. Recommend limiting their spawn there if possible or, since there are also issues with the A-10s at that airbase, bypassing that base in general for the campaigns.

2. mission results page improperly recording deaths. It will reflect more deaths than what actually happens, the inventory screens do show the correct numbers though. I suspect it is recording landings as deaths but can't confirm it.

3. Are off-map spawns implemented yet? If not then disregard this point. But if so, purchasing and generating a flight plan in Liberation does not generate any units in the ME. Also see the Liberation save for the flight plan itself, having an in-line flight plan does not generate efficiently, likely because it is trying to generate a plan on the logic of taking off and landing from the same location.

[Build 596 Test 1.zip](https://github.com/Khopa/dcs_liberation/files/5613948/Build.596.Test.1.zip)

**Comment by DanAlbert** [comment]
> Recommend limiting their spawn there if possible or, since there are also issues with the A-10s at that airbase, bypassing that base in general for the campaigns.

I don't think we can practically do this. We *do* already limit to the spaces that fit the aircraft, but if DCS is giving bad data it's not feasible for us to fix every case. We don't currently handle parking assignments at all; that's delegated to pydcs.

> mission results page improperly recording deaths. It will reflect more deaths than what actually happens, the inventory screens do show the correct numbers though. I suspect it is recording landings as deaths but can't confirm it.

https://github.com/Khopa/dcs_liberation/issues/485

> Are off-map spawns implemented yet? If not then disregard this point. But if so, purchasing and generating a flight plan in Liberation does not generate any units in the ME. 

You have culling enabled.

> Also see the Liberation save for the flight plan itself, having an in-line flight plan does not generate efficiently, likely because it is trying to generate a plan on the logic of taking off and landing from the same location.

What I see looks like a mission planned that takes off from the UAE and leaves via Europe. It's a weird mission, but it's as-planned, right?

**Comment by Mustang-25** [comment]
> I don't think we can practically do this. We _do_ already limit to the spaces that fit the aircraft, but if DCS is giving bad data it's not feasible for us to fix every case. We don't currently handle parking assignments at all; that's delegated to pydcs.

Fair enough! In that case it might be best to avoid that air base until Ugra fixes it.

> You have culling enabled.

Oh of course! Silly me for missing that. Since they're pretty far away from the other culling zones are there any plans to always let them spawn units?

> What I see looks like a mission planned that takes off from the UAE and leaves via Europe. It's a weird mission, but it's as-planned, right?

Yeah it was as planned. I wanted to see what the waypoints would look like if the the departure and arrival points were different. I'm not sure if long range bombers would actually follow a flight path like this or not but at least the high altitude surveillance aircraft like the U2 would fly long linear paths like that so I thought it was at least somewhat plausible.

I also had in mind situations where it is explicitly planned that you take off from one airbase and have to land at another due to fuel considerations. These would be the flight plans where the waypoints can start getting a little funky. Maybe I'm just wrong about how flight planning goes in real life but since we now have the option to pick a different arrival airbase, it might be worth looking at optimizing the waypoint generation for situations like that. 

![WP Generation](https://user-images.githubusercontent.com/72566076/100641273-17ecd600-32ec-11eb-9564-e49d3e0334a6.jpg)

**Comment by DanAlbert** [comment]
The flight stays with its package from join to split, then goes home. There's already an FR open for being able to avoid rendezvous flight plans for single flight packages, and there's already an FR open to plot waypoints more intelligently.
