### ISSUE TITLE
Redfor faction

### ISSUE THREAD

**Issue by RobertPeary** [dcs-liberation/dcs_liberation#488]
Add Redfor as new faction

Similar to the Bluefor faction which comprises of the assets of different (NATO) nations, a Redfor faction should be created. I am specifically thinking about a faction with access to Russian and Chinese assets. 
As a JF-17 player it would greatly enhance the experience to also have access to all the Russian hardware when choosing RedFor as the player faction. 
Thank you for your consideration.

**Comment by walterroach** [comment]
In case anyone would like to step in and add this faction as a PR: https://github.com/Khopa/dcs_liberation/wiki/Custom-Factions

**Comment by RobertPeary** [comment]
Thanks for the hint. I created the following two factions as per the above instruction:
- Redfor (Russia) 2010
- Redfor (China) 2010
I sent an email with the two .json files to Dan Albert. I would appreciate if someone within the DCS Liberation team could test the factions, and if found satisfactory, include them in an official release. If I missed something or for any further inputs, please feel free to contact me.

**Comment by DanAlbert** [comment]
> I sent an email with the two .json files to Dan Albert

If you don't know how to make a pull request, send them to the #factions channel on our discord. I didn't get them afaict, and my email is a great way for things to go missing forever :)

**Comment by DanAlbert** [comment]
Or, better yet, just attach it to this bug.

**Comment by RobertPeary** [comment]
[redfor_china_2010.txt](https://github.com/Khopa/dcs_liberation/files/5792481/redfor_china_2010.txt)
[redfor_russia_2010.txt](https://github.com/Khopa/dcs_liberation/files/5792482/redfor_russia_2010.txt)

**Comment by RobertPeary** [comment]
I could only attach the files as .txt files (since .json files are not accepted), hope that still works.

**Comment by Malakhit** [comment]
@RobertPeary At first glance, these look like reasonable factions. I'd consider combining them into one file and making the "country" field 'Combined Joint Task Forces Red' however, as the BLUFOR factions already included with Liberation are 'Combined Joint Task Forces Blue', and that would add a little bit of consistency and also allow you to simplify it into one joint faction - unless you have a specific reason for wanting them to be Russia/China specifically?

**Comment by RobertPeary** [comment]
There are indeed only small differences in the two factions I created (e.g. AWACS, JTAC A/C, naval assets created at the beginning.) One of my main reasons for creating two factions was the voice-overs: with China you should get Chinese voice-overs and with Russia you should get Russian voice-overs. At least that's how I think it's implemented (currently don't have a rig for testing). I imagine there'd be players who prefer to play as either one of them. Any thoughts?

**Comment by Malakhit** [comment]
Okay, both have now been added. Thank you for your contribution!
