### ISSUE TITLE
Cant tune radio's to GCI. (mig21, most likely mig19, possibly 15)

### ISSUE THREAD

**Issue by Krag6** [dcs-liberation/dcs_liberation#49]
You need to add additional frequencies that are compatible with Mig21/19/15 radio's to GCI/AWACS. Even with simple radio you can't tune it that high. Possibly set a channel for those planes with dedicated GCI.

**Comment by Khopa** [comment]
Hi, 

Do you know what the range of compatible frequency is for these planes ? 
(I'm not very familiar with them.)

Thanks.

**Comment by Krag6** [comment]
Hey bud. Sorry it took so long, I don't own Mig19 and 15 so i had to do
some outside research.

Mi-8 and KA-50 have tunable radios that you can set for anything.

Mig 19 and Mig 21 have preset only radios, a lot of em share frequencies.
121 Mhz AM is Channel 1 and Channel 2 on default Mig 19 and 21 respectively.
I would use that as your GCI.

Mig 15 has a very old radio that tunes to super low freq's
its 3.750 ro 5.000 Mhz
3.750 Mhz is the lowest on the dial and I'd advise that as the GCI freq.
[image: Screen_200814_151856.png]

**Comment by Khopa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Mig-19,21,15 radios...](https://trello.com/c/AZ8R5BoK/129-mig-192115-radios)

**Comment by DanAlbert** [comment]
I did most of these recently but I think I missed the fishbed.

**Comment by DanAlbert** [comment]
I can't find any data on the capable range of the MiG-21s radio. Any ideas?

**Comment by Krag6** [comment]
Same as mig19. 121mhz am

**Comment by DanAlbert** [comment]
What's the _range_? We need a range of valid frequencies to be able to allocate channels.

For the MiG-15 you said:

> Mig 15 has a very old radio that tunes to super low freq's its 3.750 ro 5.000 Mhz

What's the range of the MiG-21s radio?

**Comment by Krag6** [comment]
Mig 19 has a RSIU-4V and Mig 21 has RSIU-5V Radio.
They are essentially the same. You can't tune them manually. They have
presets.
Range is 100-150 Mhz

Attached is literally ingame screenshot from editor with radio freq's

**Comment by DanAlbert** [comment]
> Attached is literally ingame screenshot from editor with radio freq's

The screenshots aren't showing for me. I just see `[image: Screen_200814_151856.png]`. I'll take your word for it on 100-150, but we had no way of knowing that.

**Comment by DanAlbert** [comment]
Added the radio data so the flight channel doesn't cause a mission error. https://github.com/Khopa/dcs_liberation/issues/300 means that the ATC info in the kneeboard isn't helpful (but aiui the fishbed has channels 3-20 preset to ATCs anyway), and all the coalition wide things like AWACS and tankers are currently restricted to UHF so you can't tune those either: https://github.com/Khopa/dcs_liberation/issues/330
