### ISSUE TITLE
[Feature Request] Era-Specific Loadouts

### ISSUE THREAD

**Issue by andreyzh** [dcs-liberation/dcs_liberation#490]
**Issue Description**  
At the moment the aircraft loadouts are valid for all eras. This may become a problem when playing campaign that involves US Forces from e.g. 1980s. While the aircraft are effectively the same as they would be in early 2000s, their weapons have been very different.  

For example when considering conflict around 1985:  

- F-15C should use only AIM-7 and not AIM-120B/C
- F-16C should not use AIM-120, HARMs, GPS-Based weapons
- F/A-18C should not use AIM-120, GPS-based weapons, instead the loadouts need to have AIM-9 and LGBs for precision strikes 

While the loadouts do not need to be 100% accurate for the era, we need to have the ability to define them relatively easily.

**Current Implementation**  
Based on my understanding of the setup in resources/customized_payloads folder I can make the following conclusions:

- The era-specific loadouts are customizeable enough in a sense that we're setting each weapon per pylon, and not the name of the specific loadout
- The program expects the _unitPayloads_ object which consists of one loadout applicable for one or multiple tasks (CAS/CAP/Antiship/Strike/DEAD). 
- The unitPayloads is currently applicable for all eras and sides of the conflict

Based on this, I can conclude that implementation of the era-specific loadouts will require both:

- Changing the structure of the loadout files or folders
- Changes in the parsing implementation in the back-end so that the program is able to differentiate between different eras

**Design Input**  
Ideally we want the design to be flexible enough to

1. Apply the era-specific loadouts to all coalitions who use given aircraft
2. Apply era-specific loadouts to a particular coalition with further limitations
3. Maintain decent level of maintainability for the loadout files. I don't think it's going to be very easy for maintainers if we have all era- and coalition-specific loadout definitions in one .lua file
4. Have the fallback scenarios in place, so that if the era loadout is not defined, we will always fall back to standard loadout

One _option_ to implement this would be to:

- Create a subfolder for each aircraft in resources/customized_payloads e.g. resources/customized_payloads/A-10A
- In the aircraft subfoder we will have a "dispatcher" .lua which will contain paths to the different loadlout files, can be named as current .lua file e.g. A-10A.lua
- We should always have a default payload file. Existing files can be renamed e.g. A-10A-default.lua The structure of the file shall remain the same to minimize changes in the application
- Additional payloads files can be added to aircraft folders e.g. A-10A-70s.lua
- Add new property to coalition: "Era". Values can be e.g. 1970, 1980, 1990, 2000

The dispatcher file could look as follows:
{
 "aircraft": "A_10A"
 "default": "A-10A-default.lua"
 "1970": "A-10A-70s.lua"
}

The selection logic would be as follows:
IF coalition file defines era AND loadout dispatcher has entry for this era
  => Use the era loadout   
ELSE
 => Use default loadout

Now here I need to think how to also include era-and counry-specific loadout, but I ran out of juice :)

**Comment by DanAlbert** [comment]
> Maintain decent level of maintainability for the loadout files. I don't think it's going to be very easy for maintainers if we have all era- and coalition-specific loadout definitions in one .lua file

The size of the file is the smallest part of the cost. It's already extremely painful to have to do this per aircraft whenever a new mission type is added or per mission type whenever a new aircraft is added. Adding another dimension to that problem would make adding new mission types or aircraft slow to a crawl.

Instead, keep the loadout files as is and have each weapon designate a fallback weapon for when that one is not available. For example, AIM-120C -> AIM-120B -> AIM-7, or GBU-38 -> GBU-12 -> Mk 82. We'd design for the latest equipment and degrade the loadout as needed.

**Comment by Khopa** [comment]
> It's already extremely painful to have to do this per aircraft whenever a new mission type is added or per mission type whenever a new aircraft is added.

Yes, it's a very time consuming task.

> Instead, keep the loadout files as is and have each weapon designate a fallback weapon for when that one is not available. For example, AIM-120C -> AIM-120B -> AIM-7, or GBU-38 -> GBU-12 -> Mk 82. We'd design for the latest equipment and degrade the loadout as needed.

This is a great idea; it will be way less work for us in the end.

A potential shorctoming of this approach however, is what do we do, if for instance, AIM-120B is allowed on a station, but its replacement AIM-7MH isn't ? In that case, you'll end up with an empty station. But i think this should be rare enough, that it won't really be an issue ?

***

We can also keep the idea of the "era" parameter in the faction file, and have a list with the introduction date of most important weapons :

```
WEAPONS_AVAILABILITY = {
      LAU_115___AIM_120C: 1996,
      LAU_115_2_LAU_127_AIM_120C : 1996,
      LAU_115___AIM_120B: 1994,
      LAU_115_2_LAU_127_AIM_120B: 1994, 
      R_77: 1994,
      R_77_: 1994
      [...]
}
```

So that a faction with the parameter : 

```
"era":1995,
```

would have access to AIM_120B, but not 120C.
The goal is to avoid having to maintain a gigantic list of banned weapons ids in each faction file.

**Comment by DanAlbert** [comment]
> A potential shorctoming of this approach however, is what do we do, if for instance, AIM-120B is allowed on a station, but its replacement AIM-7MH isn't ?

Because it's still a theory I have my doubts, but I think in that case it's just a matter of adding more fallbacks? If it can't fit AIM-7 but can fit AIM-9, AIM-7 would then fall back to AIM-9 (F-16 is a real case where this would happen).

I think the only thing we really lose are cases where the loadout might prefer to replace weapons with a wholly different type of weapon in the fallback case, such as replacing an AIM-7 with a GBU-12 rather than an AIM-9. I doubt that's common though.

**Comment by andreyzh** [comment]
Thank you for your comments! Obviously you know much more than I do what are the main pains in the application maintenance, and thank you for pointing this out! 

I also like the "fallback" idea, it seems quite elegant.

~~Thinking out loud: is there any way we could use the DCS information available in game? Recently, ED has introduced an "era" of their own where based on the mission date, they have an option to limit not just the units, but their weapons as well. I've had a look at the F-15. If you set the date to 1984 you only get AIM-7M as MRM. Go up to 1987 and you get AIM-7MH in addition to that. In 1994 you get AIM-120B.~~

~~There might be some problems with this approach though, because even in example above you would not get the Hornet until 2000s and AIM-120 is only available since 1994, though the first "A" versions were already available during the Desert Storm.~~

UPD: Unfortunately the database file is encrypted, so we cannot use it :(

**Comment by DanAlbert** [comment]
We should tackle this in 2.4.

**Comment by DanAlbert** [comment]
More or less have this implemented. The data entry is going to take an extremely long time and I won't be doing all of it right away. Will handle the air to air missiles which are likely all anyone really cares about.

**Comment by DanAlbert** [comment]
Guts are submitted. Only handles the following weapons currently:

```
_WEAPON_FALLBACKS = [
    (Weapons.AIM_120C, Weapons.AIM_120B),
    (Weapons.AIM_120B, Weapons.AIM_7MH),
    (Weapons.AIM_7MH, Weapons.AIM_7M),
    (Weapons.AIM_7M, Weapons.AIM_7F),
    (Weapons.AIM_7F, Weapons.AIM_7E),
    (Weapons.AIM_7M, Weapons.AIM_9X_Sidewinder_IR_AAM),
    (Weapons.AIM_9X_Sidewinder_IR_AAM, Weapons.AIM_9P5_Sidewinder_IR_AAM),
    (Weapons.AIM_9P5_Sidewinder_IR_AAM, Weapons.AIM_9P_Sidewinder_IR_AAM),
    (Weapons.AIM_9P_Sidewinder_IR_AAM, Weapons.AIM_9M_Sidewinder_IR_AAM),
    (Weapons.AIM_9M_Sidewinder_IR_AAM, Weapons.AIM_9L_Sidewinder_IR_AAM),
]


WEAPON_INTRODUCTION_YEARS = {
    Weapon.from_pydcs(Weapons.AIM_120C): 1996,
    Weapon.from_pydcs(Weapons.AIM_120B): 1994,
    Weapon.from_pydcs(Weapons.AIM_7MH): 1987,
    Weapon.from_pydcs(Weapons.AIM_7M): 1982,
    Weapon.from_pydcs(Weapons.AIM_7F): 1976,
    Weapon.from_pydcs(Weapons.AIM_7E): 1963,
    Weapon.from_pydcs(Weapons.AIM_9X_Sidewinder_IR_AAM): 2003,
    Weapon.from_pydcs(Weapons.AIM_9P5_Sidewinder_IR_AAM): 1963,
    Weapon.from_pydcs(Weapons.AIM_9P_Sidewinder_IR_AAM): 1978,
    Weapon.from_pydcs(Weapons.AIM_9M_Sidewinder_IR_AAM): 1983,
    Weapon.from_pydcs(Weapons.AIM_9L_Sidewinder_IR_AAM): 1977,
}
```

All the different weapon racks are treated as entirely unrelated weapons by pydcs, so there are still a lot of places where AIM-120s are available in 1950.

**Comment by DanAlbert** [comment]
Added data for more variants of the AIM-120, AIM-7, and AIM-9. Enough to cover the F/A-18, F-16 (which is pretty pointless given that the block we have in DCS doesn't get sparrows), F-15C, and F-15E.

Also added the R-77. I couldn't find any data on when the ER and ET variants of the R-27 were introduced.

There are almost a thousand weapons in DCS. We won't be doing all of these. I'm pretty sure all anyone really cares about here is the fox 3s, and those are now covered. If someone wants to contribute a patch covering more we'd be happy to accept it, but probably not the best bang for buck on our effort to do more here. Filed https://github.com/Khopa/dcs_liberation/issues/723 to document that we probably won't do more here.

**Comment by andreyzh** [comment]
Just wanted to say big "thank you" for this. Terrific work!
