### ISSUE TITLE
TGOs and CPs require double click to activate

### ISSUE THREAD

**Issue by DanAlbert** [dcs-liberation/dcs_liberation#491]
The click behavior for TGOs and CPs changed. Where previously a single click was sufficient, I now have to double click those elements to view them (and cursor does not change to indicate that there even is a click action). Reverting 72ac806cb87b9165773e570a5da0d63d53ac2d4b causes the problem to go away.

**Comment by Khopa** [comment]
Fixed in https://github.com/Khopa/dcs_liberation/commit/2012ad0aa35bc1f9295e459d658664371d73c8e6
