### ISSUE TITLE
C101 Issues - Request: starting fuel load set to 50%, Bug: cannon/machine gun pods only firing single shots

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#492]
The C101 doesn't actually fly with a full fuel load except when being ferried. The design requirements stipulated that no external tanks were allowed, so the internal fuel tanks are actually quite a lot larger than needed for standard missions. Once you load up a C101 with a standard combat load, it can't actually take off from regular runways with a 100% fuel load. After some testing, it appears 50% is a pretty good number that allows C101s to take off from standard runways with a variety of different loads, while still holding enough fuel for the average Liberation sortie.

Also, The C101 appears to only fire single shots from its cannon when attacking ground targets. This might possibly be because it only has external gunpods rather than an internal gun, and it's being treated similar to a rocket? The Viggen, for example, also only fires single rockets from its rocket pods in Liberation.

**Comment by DanAlbert** [comment]
Forked part 2 into https://github.com/Khopa/dcs_liberation/issues/493
