### ISSUE TITLE
[Bug Report] Build 614 Kills Not Registering

### ISSUE THREAD

**Issue by Mustang-25** [dcs-liberation/dcs_liberation#494]
As discussed on discord, in the latest build I attacked a SA-10 site but the kills did not get recorded. Attached are the json and liberation save.

[Build 614 No Kills Registered.zip](https://github.com/Khopa/dcs_liberation/files/5646554/Build.614.No.Kills.Registered.zip)

**Comment by DanAlbert** [comment]
Merging into https://github.com/Khopa/dcs_liberation/issues/485.
