### ISSUE TITLE
Adding the Hercules mod by Anubis

### ISSUE THREAD

**Issue by CaptMikeDK** [dcs-liberation/dcs_liberation#497]
Could you add this mod to the database should be for all blue factions.

http://www.mediafire.com/file/8p2knd0q70iaox3/Hercules_ver_5.9.zip/file

https://discord.gg/qXmTBGGRvm

thanks :)

**Comment by DanAlbert** [comment]
https://github.com/Khopa/dcs_liberation/issues/401
