### ISSUE TITLE
Request:  Display which airbase each location belongs to.

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#498]
On some campaigns (Golan Heights Battle) the airbases are so close together that you don't know which airbase owns each location.  It would be nice to know which SAM/Factory/Command Centers/Oil/Other belong to each airbase.  That way you can choose to avoid destroying a SAM/Factory/Command Center/Oil if you are about to capture the airbase it belongs to.

**Comment by walterroach** [comment]
It's possible with the direction we're going that these won't end up tied to the airbases.  As long as they are though, I agree it does make sense to display who their owner is.
