### ISSUE TITLE
Viper fuel seems to start at 0 regardless if the fuel is set to 100%

### ISSUE THREAD

**Issue by ToKeNeRd** [dcs-liberation/dcs_liberation#499]

**Comment by DanAlbert** [comment]
I know one of the developers flies the Viggen without issue, so we need more information. Upload your save game and the miz.

**Comment by DanAlbert** [comment]
I misread. _I_ fly the viper all the time and don't have this problem, so we'll need that info.

**Comment by walterroach** [comment]
Viper also has a bug with cold start where the fuel gauge says zero but it isn't.  Once electric gen comes online during startup, the fuel gauge reads correctly.

**Comment by DanAlbert** [comment]
Is that actually a bug? I thought the totalizer just needed electrical power.

**Comment by walterroach** [comment]
It's a bug in th sense that it would practically never show zero.  Supposedly the real jet totalizer stays at the shutdown fuel level until electric power is applied.  Also, the totalizer doesn't come alive on ground power, only gen.  

Either way, I don't think Liberation has a bug here. @ToKeNeRd  If the fuel shows zero in mission editor or the ground crew menu, then maybe it is ours.  I haven't seen that though.

**Comment by DanAlbert** [comment]
> Supposedly the real jet totalizer stays at the shutdown fuel level until electric power is applied. Also, the totalizer doesn't come alive on ground power, only gen.

I see. I thought the zeroing was the real behavior.

**Comment by ToKeNeRd** [comment]
I tried it with Invasion From Turkey Turkey 2005 vs Syria 2011 set in spring 2010 I tried messing with it in editor making sure my fuel was at 100% even fired up a instant action cold start as well as my own training map and only found the issue with liberation I resorted to 2.20 and everything works fine

**Comment by DanAlbert** [comment]
Share the miz and liberation save? Until we can see the bug we can't help.

**Comment by DanAlbert** [comment]
Closing for lack of information.
