### ISSUE TITLE
AI Strikes often only target one structure.

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#500]
When I create Strike tasks for AI to target Factories or Ammunition Depots, the AI will drop all of their bombs only on one of the structures, and not hit all of them.  At Factory targets this is usually the Factory, and at Ammunition Depots this is usually the Ammo depot and not the hangars.

**Comment by DanAlbert** [comment]
Related to https://github.com/Khopa/dcs_liberation/issues/244
