### ISSUE TITLE
Tank 3s are invincible?

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#501]
I've never been able to destroy Tank 3s.  Are they invincible?

![Tank3](https://user-images.githubusercontent.com/74509817/101261932-faf34100-36f7-11eb-95ce-9dfabca3d5d4.png)

**Comment by SnappyComebacks** [comment]
These appear to be just really difficult to destroy.  Requires a 2000lb bomb dropped directly on them.

**Comment by Starfire13** [comment]
Yeah, it appears they are completely immune to splash damage as well as gun rounds. Only drict bomb hits will take em out. They're kinda like that big FARP tent in that regard.
