### ISSUE TITLE
some issues about the campaign on the north-west of Caucasus map

### ISSUE THREAD

**Issue by scplo2753** [dcs-liberation/dcs_liberation#503]
Gelendzhik and Novorossiysk are located far away from the sea on the Caucasus map.
The Caucasus map is not friendly for the north-western's campaigns
![101233648-a3a39f80-36fc-11eb-9330-10163d32af75](https://user-images.githubusercontent.com/8475845/101269128-baa2ca00-37ae-11eb-9117-bc55f6d7a140.png)

**Comment by DanAlbert** [comment]
https://github.com/Khopa/dcs_liberation/issues/91
