### ISSUE TITLE
AI Aircraft Purchasing Oddities 

### ISSUE THREAD

**Issue by MedievalBunny** [dcs-liberation/dcs_liberation#507]
I'm playing a campaign against Russia in Syria right now, and they've loaded up on Tu-22s and Tu-95s, but I've never seen a single one of them sortie. 

The same campaign they bought almost nothing but MiG-31s on the fist turn, not a single MiG-29 or Su-27 in sight.

**Comment by DanAlbert** [comment]
https://github.com/Khopa/dcs_liberation/issues/361
