### ISSUE TITLE
Apaches/Helos hover still between Base and Waypoint 1

### ISSUE THREAD

**Issue by J-5015** [dcs-liberation/dcs_liberation#512]
Apaches set to CAS or other missions stop inflight to a hover half way between Airfield and Waypoint 1 . Hover at altitude defined by waypoint 1. PG Iran Invasion. Observed in both MP and SP. Apaches in a single package. No connection to other units.

**Comment by DanAlbert** [comment]
Are they at a hold point?

**Comment by J-5015** [comment]
No holding Point. Double checked in Mission Editor. First Waypoint is Ingress. They never make it there.

**Comment by DanAlbert** [comment]
Upload the liberation save and the generated mission.

**Comment by Mustang-25** [comment]
helos perform CAS task as fragged in current release.
