### ISSUE TITLE
Redfor ground unit losses showing up as Blufor in end of mission screen

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#513]

**Comment by Starfire13** [comment]
Looks like it's not just ground units either. Redfor air assets can also appear in blufor list.

**Comment by DanAlbert** [comment]
Additional context: https://discord.com/channels/595702951800995872/595706079459934208/785069318907494400

@Starfire13 did you happen to capture a base in that round? I don't have enough info to dig at all here. The `state.json` and liberation save would be helpful.

**Comment by DanAlbert** [comment]
~~Ah, no, I spotted it. Just not actually filtering for player vs opfor.~~ I think it's also broken after a base capture though.

(I misread earlier; if it's not a post-capture issue I don't know what the problem is)

**Comment by Starfire13** [comment]
Yeah, it happens both with and without base captures.

**Comment by DanAlbert** [comment]
Then it's unlikely that I fixed it, but changes did happen in that area today. Currently I don't have the data I'd need to work on this. I don't see the problem on my end.

**Comment by DanAlbert** [comment]
Assuming my fix the other day did fix it. If not I'll reopen, but I have no idea how to proceed here if that's the case.
