### ISSUE TITLE
A-10 blowing up at Nellis AFB

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#516]
Spawns in mid air and crashes straight into the ground. Happens on every mission start.

**Comment by Hornet2041** [comment]
On Liberation v4..... have 150+ A-10s at Nellis. none have blown up

![image](https://user-images.githubusercontent.com/55866858/124023493-feb02300-d9bb-11eb-953f-5ad9d909d169.png)
