### ISSUE TITLE
Feature Request: Possible Recovery Mode?

### ISSUE THREAD

**Issue by loneregister** [dcs-liberation/dcs_liberation#52]
Is there any remote possibility of reading the mission results file (if saved), to then "recover" a failed mission?  i.e. read the mission results file, interpret into a format that can then be used by the Liberation system to update the campaign to reflect the mission results?

This would be a pretty cool feature, and offer some good redundancy.

**Comment by justin-lovell** [comment]
I didn't see this feature request when I started navigating the repository yesterday evening, but I thought of the scenario when hosting multiplayer missions. This was integrated as a `LIBERATION_EXPORT_STAMPED_STATE` environment variable in this PR: https://github.com/Khopa/dcs_liberation/pull/224

Would that line up to solve the use case you are presenting?

**Comment by DanAlbert** [comment]
What mission results file are you referring to?

**Comment by loneregister** [comment]
When you finish a mission, you are given the option to save some files.  I think one of them is the "replay" of the mission, and another contains the events of the mission.  Given that file, it might be possible to decode it, and come up with the results and mission attrition values.

**Comment by DanAlbert** [comment]
I see, but it's not automatic?

**Comment by loneregister** [comment]
I don't believe so.  I am pretty sure you have to manually save the two logs.  This could be a good process to ask players to use, just in case they get a fail, or failure to connect to DCS, they can use these logs to recover the information.  Also - perhaps a simpler solution might be to allow the player an 'edit' option for crashed games.  They could tally up the lost vehicles themselves, and enter that into a dialog box?

**Comment by DanAlbert** [comment]
I think this actually Just Works. Watching a DCS replay is the same as playing a mission, so just watching the replay and submitting the state.json should work.
