### ISSUE TITLE
DEAD Loadout

### ISSUE THREAD

**Issue by walterroach** [dcs-liberation/dcs_liberation#520]
Give DEAD flights a unique loadout so they can be set independently from SEAD.

**Comment by Mustang-25** [comment]
Just a suggestion: cluster munitions like the CBU 87, 97, rockeyes, and GB-6SFW (on the Jeff) would be good options for DEAD.

**Comment by walterroach** [comment]
I looked into this a bit today, and it doesn't fit nicely into the existing system since the loadouts are based on the DCS Task type (where DEAD is not option, SEAD and DEAD flights both get SEAD).

I don't particularly want to special case DEAD, nor do I want to uproot the existing system.  

Relevant sections are https://github.com/Khopa/dcs_liberation/blob/473cda971a1f224a5da25882b344cdcea9ea8758/gen/aircraft.py#L713

and 

https://github.com/Khopa/dcs_liberation/blob/473cda971a1f224a5da25882b344cdcea9ea8758/game/db.py#L977

**Comment by DanAlbert** [comment]
> nor do I want to uproot the existing system.

Agreed for the short term, but planning based on the DCS task type isn't going to work long term since they have fewer mission types than we do.

**Comment by clutchtomcat** [comment]
I'd argue that the mission type in the Liberation generator be changed from DEAD to SEAD. AFAIK, all real-world operations center around SEAD, with DEAD being secondary.

**Comment by DanAlbert** [comment]
There are two mission types.

**Comment by DanAlbert** [comment]
> nor do I want to uproot the existing system.

Apparently I did. `Liberation <mission type>` loadouts (e.g. "Liberation DEAD") are now preferred for every mission type: https://github.com/dcs-liberation/dcs_liberation/commit/f2e3ccd18c0e814c050452c2d4f60eb64906dd4d

**Comment by Mustang-25** [comment]
DEAD and SEAD are now differentiated. Do we still want to keep this one open?

**Comment by DanAlbert** [comment]
I think it's fairly impractical to provide a unique loadout per aircraft for every mission type at this point. Given that DEAD now falls back to the CAS loadout (eventually, through some others) I think this is as one as it will get given the constraints imposed on us by customizable loadouts.
