### ISSUE TITLE
More settings for enemy strengths and weaknesses

### ISSUE THREAD

**Issue by Galwran** [dcs-liberation/dcs_liberation#522]
It would be nice that at the start of the game you could set the strengths of the airforce, air defence, ground forces and navy. So you could have a scenario where the enemy has modern fighters, but no S-300s. Or a scenario in which the enemy has masses of tanks, and maybe even modern medium range sams, but just a few modern fighters.

**Comment by DanAlbert** [comment]
That's just a custom faction. There's a guide on how to make those on the wiki.
