### ISSUE TITLE
More EWRs outside bases

### ISSUE THREAD

**Issue by DanAlbert** [dcs-liberation/dcs_liberation#524]

**Comment by walterroach** [comment]
We should add other air defenses far from CPs too.

**Comment by DanAlbert** [comment]
For some types of SAMs that's already doable in the campaign. I didn't elaborate in the report here like I should have (it was mostly a reminder for myself), but we don't actually make it _possible_ to put an EWR outside a base currently (and only one per base as well).

The other types of AA fall into a handful of other bugs:

* SHORADS for TGO defense: https://github.com/Khopa/dcs_liberation/issues/271
* AAA (and probably MANPADS) should be all over the place: https://github.com/Khopa/dcs_liberation/issues/347

**Comment by DanAlbert** [comment]
https://github.com/Khopa/dcs_liberation/pull/967 addresses this and is in review.
