### ISSUE TITLE
SU-27 Blue Faction with Russian Liveries

### ISSUE THREAD

**Issue by Melt-DownZx** [dcs-liberation/dcs_liberation#526]
SU-27 and SU-25 on blue Combined Joint Task Force are flying Russian skins. 
Not able to change them in ME either. 

Makes it pretty hard to identify friends vs foe in a big 100+ planes mission. 

Thx

**Comment by walterroach** [comment]
No skins are available for these units on CJTF blue (in DCS).  You would have to modify the liveries for your DCS installation to enable this.
