### ISSUE TITLE
Air Assault Missions (for helos)

### ISSUE THREAD

**Issue by jeetsukumaran** [dcs-liberation/dcs_liberation#527]
(Based on my comment on the discord)

Could we consider air assault missions for helos?

Users would target an objective on the map for the package -- e.g., an airbase.
Helo flights assigned to the package would get one additional mission choice: "Air assault".
This mission would be available to both AI's and players.

It can be done simply:

(1) An air assault mission would require the helo flight to successfully land in a zone near or around the objective. (Technically, it should also land in a pick-up zone to get troops, but presumably this will be the home air base).
(2) Upon landing in the predefined zone, infantry will automatically spawn. Number of infantry would depend on help type (e.g., Mi-28 would carry more than UH-1H). After spawning they would do their thing. IIRC in DCS, infantry _should_ automatically attack nearby enemy? Not sure if additional scripting is required.
(3) Other flights in package behave normally -- SEAD etc. Strike/BAI/CAS can be used to suppres ground units.
(4) Tanks/arty etc. cannot be lifted to air assault like this: just infantry
(5) To keep things simple, we can assume that infantry are unlimited. So not part of budget. 
(6) Need to make sure that multiple landings != multiple infantry drops, and each helo only gets to land troops once (unless we allow for "reloads" when helos return to the base).

Advantages:

(1) Provides a very, very, very nice mission for players! Can be in highly asymmetrical environment (e.g., insurgent style -- no OPFOR air / non-MANPAD SAMs), or semi-assymetrical (e.g., no OPFOR air and "primitive" SAMS), and full symmetrical.  Role for Mi-24 / Ka-50 as supporting gunships etc.

(2) Allows for capture of bases by "leap-frogging" over frontlines. Capture of resources such as oil, factories, warehouses (rather than just destruction).  

Implementation:

The base DCS in principle allows for embarking/disembarking of troops. But it keeps going in and out of broken state. No idea what the state is now, and no guarantee it will not break.

So it might actually be more reliable and easier to bundle CTLD as Skynet is bundled now. 

https://github.com/ciribob/DCS-CTLD

With CTLD, all you need is to let CTLD know the name of the units doing the lifting, and the pick-up / drop zone names. As long as helos land in the zones It (Should All) Just Works.  Works with AI units as well --- with automatic pick-up and drop-off --- , and broad range of units (including C-130 paratroopers if you want to go there!).

Other considerations:

(a) Do we want to allow multiple trips? I.e., if helos return to base / pick-up zone they can load more troops and then can drop again? Should not be a problem with CTLD.
(b) Do we want to allow smoke in drop zones? pick up zones?
(c) Do we want to allow infantry budgeting?

**Comment by walterroach** [comment]
Adding your note to the existing task for this mission type.  #382

**Comment by jeetsukumaran** [comment]
Hi @walterroach I guess I would classify this as a combat mission rather than a logistic/resupply/reinforcement, which #382 seems to imply?

Supporting flights in the package would include SEAD/DEAD, strike, CAS, etc. The purpose is to attack (and capture or destroy) an enemy objective rather than reinforce a friendly one.

**Comment by walterroach** [comment]
It's a helicopter transport mission right?  Transport units to a spot?

**Comment by jeetsukumaran** [comment]
It is, but it is an *assault* mission.

The "spot" is held by enemy who will be shooting back.

It's less "transport" and more "attack". I think "troop transport/ferry" and "air assault" are very, very, very, very, different missions, though both use helicopters to move troops! :) Think of it as the post-WW2 version of paratroopers. Or WW2 glider troops.  Instead of parachuting / gliding in, you are using helicopters. It is not logistical, but tactical.

Another analogy: you can use ships to transport troops. But you can also use them to assault beaches (amphibious attack). Two different missions.

You would use the "transport/ferry" mission to move troops from one friendly objective to another (or, at best, a from a friendly base to the frontline).

You would use the "air assault" mission to use troops to attack and capture an **_enemy_** location (whch may be beyond the frontline on theenemy side)

https://military.wikia.org/wiki/Air_assault

**Comment by walterroach** [comment]
Right- I'm understanding what you're meaning, but it's both.  It's logistics (Ground units are tracked in Liberation, but can't be moved by a unit, that needs to be solved for this in the linked issue).  Then after the logistics piece it's new ground unit tasking #385 .

The groundwork has already been started to allow CTLD take care of some of these pieces by removing some of the naming restrictions that were incompatible with Liberation #412 , but it isn't complete yet.  

I think the input you've provided here is great, I just want to track it in the existing related issues.

**Comment by jeetsukumaran** [comment]
Yep, I can totally see how the background code infrastructure would be the same, or at least have a large overlap, so solving one problem would be solving the other. From the user perspective, the air assault mission might be different from the ferry mission, but under the hood they would be largely the same.

**Comment by DanAlbert** [comment]
Reopening since I don't think this work fits with #382. The need to give any departing ground units tasks makes it enough additional effort compared to the rest that I don't think it'll fit in the same release.
