### ISSUE TITLE
Incorrect waypoint name id

### ISSUE THREAD

**Issue by adamdoda** [dcs-liberation/dcs_liberation#528]
The id of the WP is set to the name e.g. "INGRESS".
The id is the key in the translations dictionary and it should look like something like this: "DictKey_WptName_1" and the value should be set to "INGRESS". Each WP name key should be unique.

The result is when I rename a WP in Project Tauntaun all INGRESS WP's name (across all flights) will change.
Not perfect example how to handle it properly: https://github.com/UOAF/project-tauntaun/blob/develop/live_editor/backend/tauntaun_live_editor/camp.py
Line 213, 179.

**Comment by DanAlbert** [comment]
That branch is either private or was deleted. Got a fresh link or a snippet?

I'm guessing this is our problematic piece of code: https://github.com/Khopa/dcs_liberation/blob/6524286f04c0aac0f2ff33d099a926eaea0fe354/gen/aircraft.py#L1260-L1264

Looking at the definition of `String` in pydcs, I'm not really sure why the code we have works at all, so clearly I've misunderstood that API 😄 At a guess, `add_waypoint(..., mission.string(self.waypoint.name))` is the fix, but I'd like to be able to confirm that doing so fixes the bug before submitting.

**Comment by DanAlbert** [comment]
Ah, nvm, found it https://github.com/UOAF/project-tauntaun/blob/e7152a0b5decd72e366efb5f07070f0b10a89d7a/tauntaun_live_editor/camp.py#L202-L209

Yes, looks like I've guessed correctly. Here's a PR with a probable fix: https://github.com/Khopa/dcs_liberation/pull/546. It appears to work, but if you could verify that https://github.com/Khopa/dcs_liberation/actions/runs/416819338 fixes the issue for you that'd help :)

**Comment by adamdoda** [comment]
Sorry I merged that branch since :) Thanks for the quick fix, I'll test it in the next couple of days.
