### ISSUE TITLE
Version 10, Missing units after turn ?

### ISSUE THREAD

**Issue by lisaazra** [dcs-liberation/dcs_liberation#53]
I have just upgraded from vs9 to vs10, great improvements thank you.
Started a new campaign, took my first turn (turn 2). During this I used Combined Arms and moved my ground troops forward destroying enemy vehicles and Sam sites. Ended my turn and saw the report, lost planes and 2 ground units which were destroyed under my control during the push. When I came to play turn 3 the only ground vehicles I had listed and visible in the mission editor were ones I had not moved all others were missing (which had not been stated destroyed in the end of turn report) also some of the Sam sites I had destroyed had respawned but with different Sam systems. 
I am going to play another round to see if this occurs again. I did not have this happening in version 9
Lisa

**Comment by lisaazra** [comment]
Ok, after playing a few more turns, not sure the units are missing but the liberation script/mission editor redistributes allied ground units randomly on the next turn which makes moving units to advantage points on one turn for attacks on airfields the following turn not viable. For example on turn 3 the majority of my ground forces were approaching an enemy held airfield to the south. Turn 4 had enemy APC's approaching my airfield and all of my ground forces were located around the airbase with the exception of Sam sites. The enemy attack was stopped and turn 5 had my forces distributed evenly along both front lines

**Comment by lisaazra** [comment]
Another thing noticed the mission result is inaccurate. For example in turn 4 of the above I lost two Hmmvv's to enemy fire, this was not documented in the end losses and when I started turn 5 I still had a full squad of 4

**Comment by DanAlbert** [comment]
Getting the transfer just plain wrong was fixed in 2.4.x. control over transfers has other FRs open, so closing this one.
