### ISSUE TITLE
Update Default Campaign Frontline Paths to Avoid Exclusion Zones

### ISSUE THREAD

**Issue by walterroach** [dcs-liberation/dcs_liberation#535]
Some of these may already be complete, but I checked off the ones I know are for certain:

- [x] Desert War
- [x] Dunkirk
- [x] Emirates
- [X] Full Caucausus
- [x] Golan Heights
- [X] Inherent Resolve
- [x] Invasion from Turkey
- [x] Invasion of Iran
- [X] Invasion of Iran Lite
- [x] Normandy
- [x] Normandy Small
- [x] North Caucasus
- [X] Russia Small
- [x] Syria Full Map
- [x] Syrian Civil War
- [x] Western Georgia

**Comment by DanAlbert** [comment]
Was dealt with a veryong time ago.
