### ISSUE TITLE
[Request] Waypoint Timing on Briefing Page

### ISSUE THREAD

**Issue by clutchtomcat** [dcs-liberation/dcs_liberation#536]
The briefing page only gives waypoint names/tasks, but no times. In the Liberation app, the waypoints on the map have times displayed, but they are illegible due to cluttered icons. The flights window only gives a ToT, no takeoff time, no push/rejoin time, no off time. 

The only way I can get waypoint timing info is after I'm in the jet and open the kneeboard, but since I don't know when my takeoff time is, I don't know when I can even get in my jet. This makes mission planning difficult.

**Comment by DanAlbert** [comment]
Is this what you're looking for? 
![image](https://user-images.githubusercontent.com/315852/101876599-811ce680-3b41-11eb-875f-b1acdb52dfcc.png)

**Comment by clutchtomcat** [comment]
Yes, but on auto-generated flights, not flights created by the user.

**Comment by clutchtomcat** [comment]
Yes, but takeoff time is still missing. I don't know when I can jump in my jet, and attempting to join a slot just results in an indefinite "delayed to start" message long past my Join/ToT time.

**Comment by DanAlbert** [comment]
I see, we include the departure time for AI flights in the briefing but not player flights. Simple oversight. Will get that added.

Should also include takeoff time on the view I posted above.

**Comment by clutchtomcat** [comment]
Gotcha, thanks.

On a side note, is it possible to generate the mission, edit it, save it, close Liberation, then open Liberation and run that mission at a later date without regenerating the mission (and thus overwriting all edits)? The program seems to want me to fly the mission as soon as possible in order to update the campaign progress. It often takes me an hour to fix the carrier path/speed/weather conditions for proper CV operations and fix all the aircraft payloads, so I often don't have time to fly the mission the same day I create it.
