### ISSUE TITLE
[REQUEST] No Player Delay = No AI Asset Delay

### ISSUE THREAD

**Issue by clutchtomcat** [dcs-liberation/dcs_liberation#537]
If we don't want to wait for our takeoff time, we can select "no delay for player," but any AI assets in the player's package will be delayed, thus making this feature rather useless in the big picture. If the AI assets included in the player's package are also started without delay, that would be perfect.

**Comment by DanAlbert** [comment]
Click ASAP. Any delays that exist after clicking ASAP is because taking off sooner won't do anything but waste gas. There's no point loitering 20 minutes while they wait for the slowest member of the package.

**Comment by clutchtomcat** [comment]
Is there no way to get ASAP to 00:00:00? Multiplayer servers have no time accelerate capability and waiting around 20 minutes for assets to takeoff isn't practical.

**Comment by DanAlbert** [comment]
https://github.com/Khopa/dcs_liberation/wiki/Mission-planning#mission-timing is worth reading if you haven't. If you're seeing behavior that doesn't match that, I'll need more details to offer any help.

**Comment by clutchtomcat** [comment]
I think I figured it out. All the windows were showing ToT while I was looking for a takeoff time of 00:00:00, but since clients/players cannot see their takeoff time anywhere I wasn't seeing it. With a ToT of T+00:25:00 or so I assume takeoff time would be 00:00:00 or close to it.
