### ISSUE TITLE
Feature Request:  Moving Map or Battlefield Information In Liberation Program Window

### ISSUE THREAD

**Issue by furiouscaulks** [dcs-liberation/dcs_liberation#54]
Since the battlefield stats update in real time, is it possible to integrate some sort of moving map feature into the main game window?  First, allow us to minimize the mission completion window,  so we could see the map?  Does the fact that the k/d is updating in real time allow for some sort of map overlay showing battle hotspots, or areas where current known battles are occurring?  Conversely, can flightplans and a moving map be integrated?

**Comment by DanAlbert** [comment]
I'm not sure this is worth doing. Tacview does this way better than we ever could.

If anyone disagrees we can reopen.
