### ISSUE TITLE
Coastal Defense Site

### ISSUE THREAD

**Issue by Khopa** [dcs-liberation/dcs_liberation#540]
There should be coastal defenses site generated by Liberation on the shore :

**New group generators :** 
- [x]  Silkworm Missiles (Modern scenarios)
- [ ] Artilery Bunker (WW2)

**Start generator:** 
- [x] Start generator should create coastal defense tgo.

**Map:** 
- [ ] Display ranges of such sites

**Comment by SimonC6R** [comment]
Breaking this down into a more granular to-do list to make it easier for me to keep track of what I've done:

- [ ] Add new group generator for Coastal Defense Missiles.
- [ ] Add new group generator for Coastal Defense Artillery.
- [ ] Add generation of the correct type of site to the start generator.
- [ ] Add preset locations for these sites to the campaign miz files.
- [ ] Gather the range info for the weapons from PyDCS and add the sites to the list of threat zones generated and drawn.

**Comment by CMGolden** [comment]
In Operation Allied Sword campaign, the Silkworm site is protected by a single SA-9, but that SA-9 does not cause a threat-ring to be shown on the map (like a stand-alone SA-9 sites have). Might be better if it did.
![image](https://user-images.githubusercontent.com/89716523/142343437-c5e5fcc3-41a1-4bb3-9915-17a9843ec6fd.png)
