### ISSUE TITLE
Some Custom Payloads Not Working

### ISSUE THREAD

**Issue by clutchtomcat** [dcs-liberation/dcs_liberation#541]
Not sure if it's me or something else going on, but following the Wiki instructions I can get custom payloads working for most aircraft and roles, except for the following:

1. F/A-18C Lot20 won't accept any custom payloads, and spawns empty.

2. STRIKE and GROUND ATTACK don't appear to work for their respective roles. Are the payload names case-sensitive to match with the role names in the ME? The Wiki lists all examples in caps.

**Comment by clutchtomcat** [comment]
Bump. Lot20 Hornet payloads still don't work. I have named them correctly "SEAD" and "CAP HEAVY" according to the db.py, but they still load with whatever default Liberaiton gives them.

**Comment by DanAlbert** [comment]
We'll get to it when we have time. We have hundreds of other bugs open that also need our attention. If you're interested in helping out check the wiki for the development guide.

**Comment by Mustang-25** [comment]
The next release of Liberation will have a different system for custom payloads. Closing this one out since this relates to the old system. If you find any similar issues with the new one please go ahead and file a new bug report. Thanks!
