### ISSUE TITLE
High digit SAMs support

### ISSUE THREAD

**Issue by DanAlbert** [dcs-liberation/dcs_liberation#542]
https://github.com/Auranis/HighDigitSAMs has exciting things like SA-20, SA-17, and an SA-22 is in progress. Support for these systems is being added to skynet currently.

Rather than needing to duplicate every faction to make use of these, we should probably make a number of things in the faction definition optional and add mod selection to the new game wizard so we can instead automatically filter our unavailable SAMs, planes, etc (would also work for our duplicate WW2 factions because of the free/paid asset split).

**Comment by Khopa** [comment]
I already added the units from the High Digit Sam mod in a pydcs extensions a while ago, but we do not have SAM generators for these yet.

And yeah the factions files are becoming unmaneagable with all the optional mods. 

> Rather than needing to duplicate every faction to make use of these, we should probably make a number of things in the faction definition optional and add mod selection to the new game wizard so we can instead automatically filter our unavailable SAMs, planes, etc (would also work for our duplicate WW2 factions because of the free/paid asset split).

Yep this could work. I had been thinking of something similar to include the C-130 mod in the existing factions.

Ideally, in the long run there should be a way to customize which units are available to the selected faction in the wizard, in an "advanced" faction selection screen. And the existing factions files would just be used as preset setups.

We could move this to a new issue.

**Comment by DanAlbert** [comment]
> We could move this to a new issue.

Done: https://github.com/Khopa/dcs_liberation/issues/545

**Comment by bgreman** [comment]
For HDSM in particular, it could probably stand to be updated as there have been a number of changes since the last time we exported.

**Comment by DanAlbert** [comment]
@Khopa did this a while ago
