### ISSUE TITLE
always drive into the wind

### ISSUE THREAD

**Issue by DanAlbert** [dcs-liberation/dcs_liberation#543]
https://github.com/Khopa/dcs_liberation/blob/babfd4abda61ba9bd028f0ba6a2a19dd0ca6d6c3/gen/groundobjectsgen.py#L207-L210

There's a ton of time between turns that can account for the carrier moving to the target, so the mission can be thought of as a recovery window and should steam into the wind.

Related, it seems we're never setting the waypoint speed. Should set to 25kt - wind speed.

**Comment by clutchtomcat** [comment]
Would it be possible to change "brc = self.steam_to_target_position(ship_group)" to something like "brc = self.steam_**North/South/East/West**" or even a degree heading? The carriers should be running more-or-less parallel to shore, not straight at it.

**Comment by DanAlbert** [comment]
They should be aimed into the wind for recovery, shouldn't they? Not sure why you'd want to force a cross-wind landing.

**Comment by clutchtomcat** [comment]
The code says "steam_to_target position," not into the wind, though. This has the ship steaming straight towards the shore.

Alternatively, it would be nice for the user to be able to set wind speed/directions in the Liberation menu to prevent situations where the ship would steam towards shore for extended periods.

**Comment by DanAlbert** [comment]
> The code says "steam_to_target position," not into the wind, though.

Yes, and the bug here was to not do that any more. It's fixed.

**Comment by clutchtomcat** [comment]
Oh, I didn't see the bug/solution clarified. Sorry.
