### ISSUE TITLE
SuperCarrier

### ISSUE THREAD

**Issue by daniele777** [dcs-liberation/dcs_liberation#549]
First my appreciated fort this great job ...can i add SuperCarrier??

**Comment by paranoid102** [comment]
Can you find a tag for the SC in option menu.

**Comment by daniele777** [comment]
ah there is option?

**Comment by Khopa** [comment]
You can setup the mission generator to replace the regular carrier with the supercarrier module here : 

![image](https://user-images.githubusercontent.com/2546901/101983082-cbed4a00-3c78-11eb-936a-f835a242ef4f.png)
