### ISSUE TITLE
Feature Request: Realistic Loadout Selections For Specific Mission Types

### ISSUE THREAD

**Issue by furiouscaulks** [dcs-liberation/dcs_liberation#55]
Is it possible to allow us to choose from preset, and realistic weapons loadouts for each flight?  Conversely, can loadouts be integrated into the economy, costing money to replace

**Comment by MedievalBunny** [comment]
In the interim, this is a pretty easy thing to tweak during the necessary mission editor phase of flying the mission in DCS. I usually give all friendly flights a once-over to tweak loadouts and waypoints before flying the mission.

**Comment by furiouscaulks** [comment]
Absolutely, its the tweaking in the editor that made me think how great it would be to do it all from the mission planner menu!!! I think if we all contribute ideas, Khopa could  make this great program even better!!

**Comment by DanAlbert** [comment]
https://github.com/Khopa/dcs_liberation/issues/383 covers the supply system for ammo/fuel.

https://github.com/Khopa/dcs_liberation/issues/273 covers presets.
