### ISSUE TITLE
F18C Not playable

### ISSUE THREAD

**Issue by daniele777** [dcs-liberation/dcs_liberation#553]
Dear i created my first campaign but great work ok!!! Fantastic.. but can't fly with hornet .... in war room on factory there is only F18C and not .. F18 lot 20 so can't fly inside game....  how to change aircrasft so fly ...?

![err](https://user-images.githubusercontent.com/8341788/101986669-7c664880-3c8f-11eb-866c-358ba82bdebb.PNG)

**Comment by Gogopex** [comment]
Hey @daniele777 , no worries, the F18C mentioned in DCS: Liberation is the same as the F18 A/C Lot 20 from DCS. If you open a player slot on that flight, you'll be able to fly the F18.

**Comment by daniele777** [comment]
Unfortunally not ...i load Mission in dcs and can't pilot F18...maybe i wrong something .. Cockpit not ready .. maybe i Need to create new campaign ?

**Comment by daniele777** [comment]
Sorry i forget to make slot at player at  all ok!!!!
