### ISSUE TITLE
liveries_overrides only works on skins in DCS install folder, not Saved Games\DCS

### ISSUE THREAD

**Issue by HomeFries94** [dcs-liberation/dcs_liberation#555]
I was unable to get the liveries_overrides to work on any custom skins in the User DCS folder.  I tried both ensuring "USA" was in the list of countries as well as commenting out the countries line altogether (so the skin works with any country).  However, assigning skins in the DCS install folder (e.g. CoreMods\aircraft\F-16C\Liveries\F-16C_50) worked just fine.

I'm using the Openbeta version of DCS, so my saved games folder is Saved Games\DCS.Openbeta if this make any difference.

**Comment by dimkzr** [comment]
This is a bummer. Can it be addressed?

As a good boy, I'm following ED's advice by keeping all my mods & liveries outside of the DCS install folder.

**Comment by dimkzr** [comment]
@DanAlbert it seems that this issue can now be closed. At least I have no problems loading custom skins from the Saved Games folder with v2.3.4.

**Comment by DanAlbert** [comment]
Works for me :)
