### ISSUE TITLE
DCS ME fails to load 

### ISSUE THREAD

**Issue by nreim1** [dcs-liberation/dcs_liberation#556]
I just DLed DCS L and created first campaign and once I load DCS and enter ME, open the Liberationnextmove.miz, the splash screen comes up and loacks up at .97, I read that this was a mod issue, but I cant figure out what else to do, Ive removed all mods and unofficial files and still get no where. Anyone have a fix?

**Comment by daniele777** [comment]
Unfortunally not ...i load Mission inside dcs Eagle dinamics and can't pilot F18... Cockpit not ready ..

**Comment by DanAlbert** [comment]
Usually it means some unit spawned underwater. Regenerate the campaign and try again.
