### ISSUE TITLE
Editable Waypoints in GUI

### ISSUE THREAD

**Issue by sgentile** [dcs-liberation/dcs_liberation#560]
First off, fantastic work, very well done!

One nice feature would be the ability to move the waypoints on the GUI, select and drag them.   Also perhaps a right click to add them as well.

Would like a good 80's desert storm with realistic weapon loadouts!

Thanks again

**Comment by Techiastronamo** [comment]
Dragging and dropping waypoints like how you can do that with the carrier would be great

**Comment by DanAlbert** [comment]
Waypoints are draggable in 3.0.
