### ISSUE TITLE
Request:  Have buildings that are part of the map be targets.

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#574]
I don't know if this is possible within DCS, but can buildings/factories that are build into maps by map developers be strike targets?  For example, there are lots of factories/ports/hangars that are part of a maps design, and they would be great strike targets.

**Comment by MedievalBunny** [comment]
You can bomb them and they can explode, but there's no way that I'm aware of to track their health, register when they've been destroyed, or set them to be destroyed at missions start of continuity. There are some ways to tie into this using scripting, but it's something that DCS natively supports.

**Comment by SnappyComebacks** [comment]
I think there is a possible solution that I've found, but I don't know much about scripting in the context of DCS.

If you create a trigger zone, you can get a building's object id.  You can also use trigger zones to set a building destroyed at the start of a mission.

Getting a destruction event of a building in Mist:
https://forums.eagle.ru/topic/227551-how-do-i-detect-when-scenery-bridges-and-buildings-are-destroyed/?do=findComment&comment=4195309

Getting a destruction event of a building in Moose:
https://forums.eagle.ru/topic/226209-new-right-click-actions-in-me/?do=findComment&comment=4175475

Setting a building / area to destroyed at mission start with trigger zones:
https://www.youtube.com/watch?v=RzgvXuvJGnQ

How I envision this working would be a trigger zone per building/target.  I tested setting a zone to "Scenery destruction event" with a percent value of 100 and only that building was destroyed.

![TriggerZoneTest](https://user-images.githubusercontent.com/74509817/105283546-f1218200-5b6d-11eb-8591-f9f92a8a8c7f.png)

In addition you can completely remove objects in a trigger zone.  Limited to "objects only, trees only, objects and trees".

**Comment by DanAlbert** [comment]
https://github.com/dcs-liberation/dcs_liberation/pull/1065
