### ISSUE TITLE
Missing Lost Ground Unit titled "BOARD_CRASH"

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#575]
On the page with the "Accept Results" page listed, there is one ground unit reported as lost.  However, when you accept the results, the ground unit lost is not shown.

State file refers to the dead unit as `"type":"BOARD_CRASH"`

On `Version 2.2.1`
Here is the campaign at the state of the offending mission, and it's state file.
[MissingLostGroundUnit.zip](https://github.com/Khopa/dcs_liberation/files/5685436/MissingLostGroundUnit.zip)

**Comment by Mustang-25** [comment]
No further reports of this issue since this was first reported in Dec. Going to assume the problem has been resolved since and closing this bug report.
