### ISSUE TITLE
FR: "Wild Weasel" Mission

### ISSUE THREAD

**Issue by jeetsukumaran** [dcs-liberation/dcs_liberation#577]
Following some experiments described here:

https://github.com/Khopa/dcs_liberation/issues/374#issuecomment-744095684

I think it might be useful to have a "Wild Weasel" mission. This would pretty much be identical to a STRIKE carried out against a SAM/AD site, with the following important modifications:

(1) Loadout defaults to Antiradiation missiles (or ARM's + cluster)
(2) Flight has "TARGET" waypoint set on top of SAM group (or maybe "close enough", where "enough" => to trigger the SAM radars under skynet with some margin of error), toward which they will fly.
(3) Waypoint action at INGRESS should be something that will make them engage the group the moment they detect it at any point in the route, particularly between INGRESS-TARGET-EGRESS. So some sort of "enroute task".

and MAYBE

(4) only radar units as target waypoints.

This would get around major weakness in DCS AI with SEAD/escorts when using SkyNet which probably won't be fixed soon: basically the SEAD/DEAD flights do not do anything if the SAM site radars are not active, and it is very difficult to coordinate the SEAD/DEAD attacks with the SAM's being active. 

The Wild Weasel mission will/should "self-trigger" the SAM's as the flying into the range of the SAM site, which makes them effective even if Skynet is used.

**Comment by jeetsukumaran** [comment]
So, update.

It seems the above approach does not work, because F-16's, at least, do not fulfill the "bombing" action waypoint when loaded with HARMs.

But the following _DOES_ work!

(1) Give the flight a "SEAD" tasking (in DCS ME), with ARM's as loadout.
(2) At the INGRESS waypoint, create an action "Start Enroute Task" > "Search Then Engage Group". assign the SAM.
(3) Create a _new_ waypoint in _after_ the INGRESS waypoint, toward the SAM group. We can refer to this as IP? or WWAP :) (Wild Weasel Action Point) Can be on top of the SAM group, or very close. Must be close enough the trigger the SAM site going active (with margin of error).

This will reliably activate the SAM site somewhere between the INGRESS and IP/WWAP, and the Wild Weasel group will fire their HARM's, either taking out the SAM radars or having them shut down. 

This allows the strike to do their mission.

We might want to take into account timing. The radars should shut down sometime _before_ the package's TOT. Ideally, it should the radars should be suppressed (or killed) for the full span of time between the INGRESS and EGRESS of the strike. So the Wild Weasel's mission TOT (e.g., at the IP/WWAP) should == the strike's INGRESS time point.
[Missions.zip](https://github.com/Khopa/dcs_liberation/files/5687135/Missions.zip)
[Tacview.zip](https://github.com/Khopa/dcs_liberation/files/5687138/Tacview.zip)

**Comment by MedievalBunny** [comment]
This would be called a DEAD mission, and there is already a DEAD tasking in Liberation.

Search and Engage Group works fairly well, DCS also allows a Search and Engage In Zone action for SEAD tasked flights (in DCS missions, SEAD and DEAD both use the SEAD mission tasking). This would be a way to effectively tell a DEAD flight to attack multiple groups, for example around an airbase which may have SAM and AAA groups in close proximity. 

DCS AI does not handle attack actions with mixed weapon loadouts very well (ARMs and CBUs on the same jet, for example). This can be overcome with triggered actions, but that adds a lot of complexity, and more points of failure in a dynamic system, especially with Skynet.

**Comment by Mustang-25** [comment]
I believe all the recent changes to SEAD/DEAD behavior cover all the requested outcomes of this FR. Closing this out unless there were action items missed.
