### ISSUE TITLE
culling behavior improvements

### ISSUE THREAD

**Issue by DanAlbert** [dcs-liberation/dcs_liberation#578]
- [x] Don't cull flights (smarter planning AI has rendered this all but useless for actually limiting unit counts).
- [x] Add non-culling regions around all package targets.
- [x] Document behavior, especially advice for using the income modifier to limit opfor air.

Discussed earlier but decided against:

- ~~Remove non-culling zones around departure airfields.~~ Only done at the airfields attached to the front line anyway, and those are potentially threatened regardless of range.
- ~~Never cull CP groups (carriers, LHAs)~~ This is already optional

**Comment by DanAlbert** [comment]
https://github.com/Khopa/dcs_liberation/wiki/Performance-Options

**Comment by MrMagicMan** [comment]
@DanAlbert I experienced the culled target not being there issue in 2.4.2 after planning a strike mission to a target that had been culled > 100nm from the front line, I will see if I can find the mission file for it for you.

**Comment by MrMagicMan** [comment]
Image attached 

![image](https://user-images.githubusercontent.com/10494948/110892967-0f307680-82c3-11eb-9004-7ff2d2a0d882.png)

As well as miz file File
[liberation_game3_turn6.zip](https://github.com/Khopa/dcs_liberation/files/6127647/liberation_game3_turn6.zip)
