### ISSUE TITLE
Reinforcements captured following loss of a base

### ISSUE THREAD

**Issue by WipeUout** [dcs-liberation/dcs_liberation#58]
After managing to capture a base in Caucasus, a lot of my ground and air units were destroyed.  as a result I planned a substantial reinforcement for the next turn.  Unfortunately, I lost the base during the current turn.  My planned reinforcements went into a twilight zone and re-appeared in the RED team on the following turn!  All of the sudden, I was facing F/A-18C airplanes Leopard II tanks!!

From a realism perspective, this would be very unlikely as there is substantial training and logistics requirement to operate modern weapon systems.  The enemy would definitely study the captured units for weaknesses but operating the equipment is a different ballgame.  Also, from a gameplay perspective, why a reinforcement would be sent to a captured base?  As soon as the situation would deteriorate, the assets would not be sent there in the middle of a fight unless there are crewed battle-ready units.

I suggest that when player reinforcement are planned for a base that is not longer on the player side, the money should come back for the following turn.

Many Thank for an outstanding campaign engine!

WipeUout

**Comment by Khopa** [comment]
Thanks for reporting this, i hadn't experienced this issue yet. 
The enemy shouldn't be using or receiving these units. 

> I suggest that when player reinforcement are planned for a base that is not longer on the player side, the money should come back for the following turn.

I agree

**Comment by DanAlbert** [comment]
This was all rewritten a few releases back and a bunch of bugs with this description were fixed. If you're still seeing it we'll need a save game (before ending the turn) and the state.json that goes with it.
