### ISSUE TITLE
CAP flights don't engage

### ISSUE THREAD

**Issue by etra-co** [dcs-liberation/dcs_liberation#592]
Any flights assigned to CAP on either side will aren't engaging each other, regardless of distance to an enemy flight. In the attached mission (turn 1, all air defences deleted for simplicity), all CAP flights just orbit around each other for 40+ minutes without firing a shot.

It looks like in 2.2.1, the Search and Engage task was assigned to waypoint 0 while now it's on the racetrack start waypoint. If I move it back to waypoint 0, the flights will engage.

[liberation_bug_no_shots.zip](https://github.com/Khopa/dcs_liberation/files/5699550/liberation_bug_no_shots.zip)

**Comment by holyorangejuice** [comment]
I've been playing a few hours and noticed this too. Had 2-3 enemy flights and friendly flights. They would fly their patterns and not engage. I have combined arms so I was making them do what I wanted.
