### ISSUE TITLE
No parking spaces warning

### ISSUE THREAD

**Issue by martinruefenacht** [dcs-liberation/dcs_liberation#594]
While trying out the new automated purchase feature I came across this issue and was very confused for a while.

When all parking spots are taken up in the purchase window it doesn't give a warning unlike trying to sell an aircraft from a set of 0 aircraft.

My suggestion is that a warning window similar to the selling non-existent aircraft is added.

**Comment by Khopa** [comment]
Fixed here for version 2.3.1 : https://github.com/Khopa/dcs_liberation/commit/e3b13f7b4a53e0856c9fc1db0b8b3cc1c1838491

![image](https://user-images.githubusercontent.com/2546901/102401555-d0e92b00-3fe3-11eb-913d-a82b71edba19.png)

**Comment by martinruefenacht** [comment]
Good response time!
