### ISSUE TITLE
Harrier BAI strikes crash into ground

### ISSUE THREAD

**Issue by holyorangejuice** [dcs-liberation/dcs_liberation#600]
https://www.dropbox.com/s/g2m990rmy9jrcye/Tacview-20201216-183642-DCS-liberation_nextturn.zip.acmi?dl=0

https://www.dropbox.com/s/hi32g5do3ak9jop/Tacview-20201216-172803-DCS-liberation_nextturn.zip.acmi?dl=0

Harrier 2 ship, takes off, strikes package, and immediately dives to the dirt both scenarios.

**Comment by DanAlbert** [comment]
We have zero control over the AI during their attack, so this is probably a DCS issue. I can't say for sure without a miz.

**Comment by ciastoman** [comment]
I had exactly the same issue. Three harriers, CAS mission. After firing mavs, they hit the ground hard. 
MIZ File: 
https://www.dropbox.com/s/hves0muncwgt91t/liberation_nextturn.miz?dl=0

**Comment by DanAlbert** [comment]
I don't think there's anything we can do about this FWIW. The AI is entirely under their own control when performing an attack task. We can take a look at the miz (thanks), but I'm pretty sure this is just DCS AI being DCS AI. They get too low in an attack run and can't figure out how to pull up and turn around in time for their second run.
