### ISSUE TITLE
Ground units set to aggressive don't move forward

### ISSUE THREAD

**Issue by holyorangejuice** [dcs-liberation/dcs_liberation#601]
My units, set to aggressive stance, haven't been moving forward. When checking the waypoint using combined arms, it is behind them and they don't move without combined arms input.

**Comment by walterroach** [comment]
Save and .miz provided on Discord to review later
[groundwaypointbug.zip](https://github.com/Khopa/dcs_liberation/files/5706996/groundwaypointbug.zip)

**Comment by walterroach** [comment]
666858f fixed *a* problem, but there's also something else going on I'll need to look at tomorrow.  Waypoints are set properly in ME, but behavior is different in mission; perhaps something with morality/retreat trigger is going wrong.

**Comment by walterroach** [comment]
Note to self: there's a stray "hold" task getting applied to tanks and IFVs on waypoint zero with nothing to trigger it off.

**Comment by Hornet2041** [comment]
Personally did not see this issue occur anymore as of build #873. Aggressive stance worked ok again.
