### ISSUE TITLE
liberation_nextturn.miz not created with 2.31 while created with 2.3

### ISSUE THREAD

**Issue by SagalSagal** [dcs-liberation/dcs_liberation#605]
liberation_nextturn.miz not created with 2.31 while created with 2.3
Therefore v 2.31 is not working for me

**Comment by DanAlbert** [comment]
Not enough information. We'll need the liberation save game.

**Comment by SagalSagal** [comment]
Hi,
I had in the background a "Dos" windows with at the end of the "script"
some error messages like not finding the "liberation_nextturn.miz" in the
C/Users.etc
In fact a littel bit as "Rhino 1217" described on 4 December on this topic
https://forums.eagle.ru/topic/183194-all-modulesspco-op-liberation-dynamic-campaign/page/37/

So I have not a lot more to share as nothing was happening. However once I
downloaded version 2.3.0 (instead of 2.3.1) everything was fine (with
regards to that part I cannot comment so much on the rest as it is my first
time with Liberation). So the conclusion is clear, something in 2.3.1
prevents my computer to work with Liberation while version 2.3.0 is ok
I don't play a lot so I do not intend to test more a version (2.3.1) where
I lost already 1h 30 of my time...
Regards,
Sagal

**Comment by DanAlbert** [comment]
Check your settings. It sounds like you set the path your DCS saved games incorrectly.

**Comment by DanAlbert** [comment]
(if not, we need that log)
