### ISSUE TITLE
OCA Strike Results Ignored

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#607]
Effects version `2.3.1`

In a campaign I started in 2.3.0 but continued in 2.3.1, I created OCA/Runway and OCA/Aircraft missions.  The results of either mission did not carry over into the next round.

Scenario:

- Player uses F/A-18 with four GBU-31(V)/3 bombs, and dispenses the bombs along the runway (Al Maktourn, Persian Gulf map), evenly spaced.  DCS's BDA tool-tip reports `destroyed` a minute later.  The debriefing also shows that something was `hit` on every bomb impact.  And the fourth hit resulted in `kill`.  The runway is still reported as operational in Liberation.

- An AI flight performs an OCA/Aircraft task at the same airport, with only two aircraft at that airport.  The debriefing reports that hits were made on the parked aircraft.  No aircraft are lost in the Liberation campaign.

- An AI flight performs a strike on two submarines.  DCS debriefing reports both as `kill`, Liberation reports as "Other ground units destroyed" but no information is shown after accepting the results.  (Liberation does recognize that the units are dead in the campaign map.)

At the end of the mission after accepting the results, Liberation reports that no units related to OCA were destroyed, and the runway is still functional.

I have attached as much information from DCS and Liberation as I could think of.  (Track, Debriefing, Campaign, State.json)

[OCA_Not_Accepted.zip](https://github.com/Khopa/dcs_liberation/files/5713296/OCA_Not_Accepted.zip)

![debrief_1](https://user-images.githubusercontent.com/74509817/102567187-3d286500-409e-11eb-9285-c007c2125445.png)
![debrief_2](https://user-images.githubusercontent.com/74509817/102567191-3f8abf00-409e-11eb-86b2-3cb1655a9c5d.png)
![Waiting_For_Mission_Results](https://user-images.githubusercontent.com/74509817/102567206-43b6dc80-409e-11eb-88c3-f1d3e3182241.png)
![Debriefing](https://user-images.githubusercontent.com/74509817/102567199-41548280-409e-11eb-9117-8fec0df75b6a.png)

**Comment by holyorangejuice** [comment]
I've noticed an issue with aircraft on the ground, they can take a ton of damage and often the only way to get the 'kill' is to completely blow them up with a bomb. Guns, ground units, light missiles, will destroy the static plane but not 'kill' it. I am certain that is just a DCS issue. I also think dumb bombs used on strike style missions should be replaced by default with smart bombs.

**Comment by DanAlbert** [comment]
https://github.com/Khopa/dcs_liberation/issues/544

**Comment by SnappyComebacks** [comment]
I just ran the mission again with infinite ammo on.  I put 18 GBU-31(V)3/Bs onto different parts of the runway.

Is there anything I should look for in either DCS/Liberation to know if a runway has been deemed destroyed?  Liberation states that the runway is still operational.

**Comment by DanAlbert** [comment]
You can look at the log, but it sounds like DCS just doesn't think you killed anything. The bug I duped this to covers tracking damage rather than kills, but that's not a feature yet.
