### ISSUE TITLE
runway start all shore AI flights to avoid taxi congestion

### ISSUE THREAD

**Issue by DanAlbert** [dcs-liberation/dcs_liberation#613]
The taxi AI at airbases causes a lot of takeoff delays significant enough that the 7 minute ground ops and 5 minute hold times are not always enough. To avoid this, we could runway start all AI that takeoff from the shore.

We shouldn't make these purely runway starts because then there would be no targets for OCA strikes. Instead, we'd need to spawn in a flight on the ramp. When the flight's takeoff time arrives, we'd remove that flight and spawn a new one on the runway. We'd need to be careful to add both of these to the unitmap and ensure that the runway group spawns only the number of non-killed ramp units.

Ideally we can get improved taxi behavior before we need to fix this. Triaging to 2.4 for us to ensure that bug reports are reduced and filed with ED by then, not necessarily to complete the feature for 2.4.

**Comment by qwertymanisalive** [comment]
This works quite well. I do this in Mission editor for now.

**Comment by DanAlbert** [comment]
This was added as an option in 2.5.
