### ISSUE TITLE
Culling not effective (2.3.1)

### ISSUE THREAD

**Issue by Mr-7** [dcs-liberation/dcs_liberation#615]
**Describe the bug**
When enabling culling on Syria Full Map Campaign Default Culling option causes nothing to be culled and thus negating the usefulness of this feature

**To Reproduce**
Start a new Campaign (Blufor Cold War vs Russia 1970 Limited Air, super carrier enabled)
Enable Culling.
Pass Turn so first wave of purchases are made.

**Expected behavior**
Units far from the front line shall be culled. I note that the updated wiki says mission targets shall not be culled but presume that is only if there is a package assigned to them. As it is, the AI buys aircraft all over the place and thus massively extends the culling exclusion zones. which adds in all the ground units around them,

**Additional information**

We will usually need more information for debugging. Include as much of the following as you are able:

[liberation_nextturn.zip](https://github.com/Khopa/dcs_liberation/files/5719332/liberation_nextturn.zip)
[231 cold new.zip](https://github.com/Khopa/dcs_liberation/files/5719339/231.cold.new.zip)

**Version information (please complete the following information):**
 - DCS Liberation [2.3.1]
 - 
![image](https://user-images.githubusercontent.com/6165617/102688357-3577d600-41ee-11eb-8ff9-9d85864ee126.png)
![image](https://user-images.githubusercontent.com/6165617/102688496-f5652300-41ee-11eb-9638-c4ca37a3f403.png)

**Comment by DanAlbert** [comment]
Already fixed, just not released.
