### ISSUE TITLE
Flight Radio is same as a ADF frequency.

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#616]
- I have searched the issue tracker to check if this issue has already been reported.

**Describe the bug**
VHF radio for the F16 will be tuned to the flight on warm start, however you will also be listening to an (what I think is) ADF/VOR pattern in the form of static.
If you change VHF to something else you will no longer hear static.

**To Reproduce**
1. Create Syria - Full Map Campaign (USA 2005, Libya 2011)
2. Add some F-18s, A-10s, and F-16s at Incirlik to use for your first playable turn.
3. Make first player flight a F-16 BARCAP with Warm Start.

**Expected behavior**
Radio frequencies that are used by the player in missions  (Flight, ATC, AWACS, Tankers) should not be the same as navigation aid frequencies (ADF, ILS, etc).

**Additional information**

We will usually need more information for debugging. Include as much of the following as you are able:

Campaign and mission:
[Radio_ADF.zip](https://github.com/Khopa/dcs_liberation/files/5719976/Radio_ADF.zip)

**Version information (please complete the following information):**
 - DCS Liberation 2.3.1

**Additional context**
I have seen this in other missions on Persian Gulf as well.  Unfortunately I didn't save them.

**Comment by DanAlbert** [comment]
I can't load your save to verify it, but I've pushed the probable fix. The code that was supposed to prevent this was accidentally dropped during a cleanup at some point, but it's back now.
