### ISSUE TITLE
SAM Launcher spawned in middle of runway.

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#617]
I have searched the issue tracker to check if this issue has already been reported.

Describe the bug
    A SAM unit has been placed on the runway center-line at Incirlik.  This might be preventing AI flights from taking off.

To Reproduce

    Create Syria - Full Map Campaign (USA 2005, Libya 2011)
    Add some F-18s, A-10s, and F-16s at Incirlik to use for your first playable turn.
    Make first player flight a F-16 BARCAP with Warm Start.

Expected behavior
    Runways and taxiways are clear of friendly ground unit obstructions.  AI flights taxi and takeoff on runways.

Additional information

We will usually need more information for debugging. Include as much of the following as you are able:

Campaign and mission:
[Obstructed_Runway.zip](https://github.com/Khopa/dcs_liberation/files/5719985/Obstructed_Runway.zip)

Version information (please complete the following information):

    DCS Liberation 2.3.1

Additional Context

    When manually moving the ground units off the runway, AI flights taxi an use the runway.

**Comment by SnappyComebacks** [comment]
I went back to the mission to look for other units in runways/taxiways.

- A `Shillka` is spawned on center of taxiway at `Allepo`.
- `IFV BMP-2s` are on runway 17L at `Bandar-Al-Assaid`.
- `IFV BMP-1s` are on taxiways at `Ramat David`
- A `Strela-1` and `MBT T-55s` (different groups) are on the runway at `Palmyra`
- `ARV BRDM-2` is on runway at `Rayak` (not on centerline)

Edit:  Happened to notice location Centipede northwest of Ramat David is in the water.

Edit 2:  Abu-Al-Dahur has apc's in the middle of the taxiway.

**Comment by DanAlbert** [comment]
Fixed more cases of this. It still might happen randomly because this campaign doesn't have a complete set of preset locations, but it at least won't be _forced_ to happen now.
