### ISSUE TITLE
[BUG] Invalid frequency when playing F-22A on Persian Gulf Full

### ISSUE THREAD

**Issue by TrueCrazyMan** [dcs-liberation/dcs_liberation#621]
Cannot play the mission due to DCS disallowing the "invalid frequency" occurring. F-22A frequency is 251 Mhz and trying to change it still doesn't fix it. Not sure if it is the Raptor or Liberation causing the issue, although spawning the F-22A in an empty map causes no issues. 

On the latest open beta version.

[lib.zip](https://github.com/Khopa/dcs_liberation/files/5720500/lib.zip)

**Comment by DanAlbert** [comment]
The F-22 doesn't have a UHF radio? What frequencies _can_ it use?

Are you sure it's the F-22 that's having the problem and not something else in the game?

**Comment by TrueCrazyMan** [comment]
Positive, only the F-22A and its "invalid frequency" are preventing the mission from playing (which is weird because it works when placing the F-22 in an empty mission and using the same frequencies).

Video of the issue (please excuse the music):
https://youtu.be/_b1On2ReVhg

**Comment by michael-davenport** [comment]
Encountered this bug on a south georgia campaign as well. Only impacted the player F-22A slot. Was able to change it to a frequency it accepted and flew the mission.

**Comment by Mustang-25** [comment]
Is this still a problem on the latest release?

**Comment by Mustang-25** [comment]
Closing this bug report. If the problem still persists we can re-open it.
