### ISSUE TITLE
Option to restrict AI use of afterburner out of combat

### ISSUE THREAD

**Issue by jake-lewis** [dcs-liberation/dcs_liberation#624]
The mission editor has an option to restrict AI use of afterburner outside of combat, this would be a useful option to add to flight options to extend operational time. Might even make sense to enable by defualt depending on mission type e.g. CAP will likey need the fuel for extended time on station

**Comment by DanAlbert** [comment]
We used to enable this by default. It was worse. The AI will regularly get themselves stuck in high AoA conditions in a turn and cannot recover without AB. They'd make a turn and then sit at 15 AoA slowly descending until they crashed.

I don't think we should do this.
