### ISSUE TITLE
Add a must buy option for automatic purchase

### ISSUE THREAD

**Issue by mkoorn** [dcs-liberation/dcs_liberation#626]
- [x] I have searched the issue tracker to check if this feature has already been requested.
Add a must buy option for a unit when enabling automatic purchase

**Is your feature request related to a problem? Please describe.**
When progressing with the first step the ai often doesn't buy the A10 which I’d like to fly.

**Describe the solution you'd like**
A must buy option so that the autmatic buy will include my unit.

**Comment by walterroach** [comment]
The auto-buy isn't committed until you pass turn.  This means that you can edit the AI purchase before committing.  Does that meet your needs, or do you think having a separate "must-buy" option would add additional value? @mkoorn

**Comment by mkoorn** [comment]
@walterroach this is then only an issue at turn 0, where you don’t have money to buy your first plane and the auto buy spends all your money.

I fixed this by using the cheat and get some more money and then buy the A10.
But the log then mentions that I am a cheater and I should be ashamed. Which my OCD dislikes. 😄

not a very big issue, I have no idea how much work this would be, so maybe put on the backlog and see if this issue gets some thumbs up from other users.

**Comment by DanAlbert** [comment]
Turn 0 behaves no differently than the others in this regard. You can cancel individual auto purchases.

**Comment by mkoorn** [comment]
I see now, issue solved. 
Thanks for your responses.
