### ISSUE TITLE
have an alt slider for packages 

### ISSUE THREAD

**Issue by Moguy164** [dcs-liberation/dcs_liberation#627]
- [x] I have searched the issue tracker to check if this feature has already been requested.

**Is your feature request related to a problem? Please describe.**

the Jf-17 has a somewhat limited range when flying at low alt (<30,000) and that can cause it to miss out on long range missions

**Describe the solution you'd like**
a slider in the flight creation screen which would set the alt at which the flight flys 
**Additional context**

**Comment by Moguy164** [comment]
could also help for proper viggen strikes

**Comment by DanAlbert** [comment]
https://github.com/Khopa/dcs_liberation/issues/560

**Comment by HILOK** [comment]
#1307
