### ISSUE TITLE
Ground units have waypoint that involves them driving through water - PG Full Map

### ISSUE THREAD

**Issue by Drew-Dodson** [dcs-liberation/dcs_liberation#629]
Before filing, please search the issue tracker to see if the issue has already been reported.

**Describe the bug**
I am playing the full PG map and my HMMWV front line units that are attacking have a way point from the front line on the main land on the UAE side to Sir Abu Nuayr which is an island. This causes them to go into the water and "drive" to the island. Their next waypoint after the island is the come back to the mainland on the UAE side.

**To Reproduce**
Not sure how to reproduce as I just noticed it happened by itself.

**Expected behavior**
Ground units should not have a waypoint at an island to move to then back to the mainland as the waypoint after the island.

**Additional information**
.liberation file, .miz file, and screenshots:
https://publicfilesanddata.s3-us-west-2.amazonaws.com/files.zip

**Version information (please complete the following information):**
 - DCS Liberation  2.3.1

**Comment by walterroach** [comment]
Probably a landmap issue, as all ground waypoints now avoid exclusion zones.  Assigning myself to update.

**Comment by walterroach** [comment]
Actually, this issue is the result of improper zero handling which was fixed in 666858f for 2.3.2

Update to 2.3.2 and this won't happen anymore (saves from 2.3.1 are compatible).
