### ISSUE TITLE
Teach AI to buy artillery

### ISSUE THREAD

**Issue by DanAlbert** [dcs-liberation/dcs_liberation#631]
https://github.com/Khopa/dcs_liberation/blob/a2f218d56dc36765bbc5378eaece968e4b82b701/game/procurement.py#L79

The front line units list does not include artillery, so the AI will never buy artillery. They probably should.

**Comment by Khopa** [comment]
Quick fix in https://github.com/Khopa/dcs_liberation/commit/60f837d0b98b14326fdce4ac0e494e895d6bf370

I think it was a bad idea from me to put them in a separate list in the factions file. This just add unnecessary complexity to the code - and we can already check if the type inherit from "Artillery" class.
