### ISSUE TITLE
SA-2 generator is missing the command center

### ISSUE THREAD

**Issue by DanAlbert** [dcs-liberation/dcs_liberation#632]
https://github.com/Khopa/dcs_liberation/blob/a2f218d56dc36765bbc5378eaece968e4b82b701/gen/sam/sam_sa2.py#L19

SA-2 generator doesn't generate an command center unit. I'm pretty sure that's required. https://www.airgoons.com/w/DCS_Reference/Air_Defences#S-75M1_Divina_.2F_SA-2_.E2.80.9CGuideline.E2.80.9D

**Comment by DanAlbert** [comment]
SA-3 is as well.

**Comment by Khopa** [comment]
The sites can definitely fire without one of those, this is not a required unit.
These looks like units added for RP to me.

SA-2 and SA-3 could use a few ZSU/ZU as shorad though, and an ammo truck would help to reload them during mission time.

**Comment by DanAlbert** [comment]
Confirmed not required. Probably just bad placement on an old campaign that caused the issue (I think they were in the trees pretty well), but they definitely never fired:
[Tacview-20201221-004404-DCS-liberation_nextturn.zip.acmi.txt](https://github.com/Khopa/dcs_liberation/files/5729034/Tacview-20201221-004404-DCS-liberation_nextturn.zip.acmi.txt)
