### ISSUE TITLE
Differentiate SAM's into Short and Medium Ranged Categories

### ISSUE THREAD

**Issue by Nhawk2174** [dcs-liberation/dcs_liberation#635]
Currently the SA3 and SA2 can be spawned at the same site.  But the range capabilities of these systems are very different.  There should be two categories here a "Short" and "Medium" ranged. 

Short:
SA3
SA6
SA8
HQ7

Medium
SA2
SA11
HAWK

**Comment by DanAlbert** [comment]
This is already in 2.3.
