### ISSUE TITLE
Time Sensative Targets of Oppurtunity

### ISSUE THREAD

**Issue by Nhawk2174** [dcs-liberation/dcs_liberation#636]
Investigate adding time sensitive targets.  Such as a tanker convoy heading for a port.  Or maybe an engineer battalion heading to a destroyed target.  There will be a limited amount of time to hit these high value (and often highly defended) targets.  Failure to do so will give the AI a small boost of resources, an instant repair to a facility, or units.  Doing so will prevent this.  Also the ability to control the rate that these happen or if they happen at all should be given to the player at the start as well.

**Comment by DanAlbert** [comment]
This is an inherent part of https://github.com/Khopa/dcs_liberation/issues/383
