### ISSUE TITLE
SAM sites in forest around Ramat David (Syria Map)

### ISSUE THREAD

**Issue by MedievalBunny** [dcs-liberation/dcs_liberation#638]
SAM sites are spawning in the forest southwest of Ramat David in the Golan Heights Battle scenario on Syria. 
![Capture](https://user-images.githubusercontent.com/19675397/102818545-76f7b500-4397-11eb-834a-f060867f11bf.JPG)

**Comment by Khopa** [comment]
Yes, this campaign has not been migrated to the new format with preset locations as of 2.3.2, it has been fixed for version 2.3.3, which is coming soon.

There are still a few campaigns that needs this to be done, and some of the "full maps" even lack preset positions.

**Comment by MedievalBunny** [comment]
Awesome! Looking forward to 2.3.3

**Comment by clairmont32** [comment]
Should this also be fixed for other units on the frontlines? I noticed last night that I wasnt able to see MANPADS and SAMs in the woods nearby Hatay.

![Screen_201224_230436](https://user-images.githubusercontent.com/6239004/103139204-da3f5b00-46a7-11eb-9179-594612422dba.png)

**Comment by Mustang-25** [comment]
Based on the previous comments I'm assuming that this has been fixed in a previous release so I'm going to close this bug report.
