### ISSUE TITLE
Players are not synchronized

### ISSUE THREAD

**Issue by DevastatorCM** [dcs-liberation/dcs_liberation#639]
**Describe the bug**
We started a new campaign and in the second mission players are not able to see each other. Example, I attach myself to cat 1 and nobody sees it. Same applies to all other planes. They all look like in park but actually we are at catapults.

**To Reproduce**
No idea how to reproduce... I can send the mission file if it helps

**Expected behavior**
players see each other.

**Additional information**

We will usually need more information for debugging. Include as much of the following as you are able:

- DCS Liberation save file (the `.liberation` file you save from the DCS Liberation window). By default these are located in your DCS saved games directory (`%USERPROFILE%/Saved Games/DCS`).
- The generated mission file (the `.miz` file that you load in DCS to play the turn). By default these are located in your missions directory (`%USERPROFILE%/Saved Games/DCS/Missions`).
- A tacview track file, especially when demonstrating an issue with AI behavior. By default these are locaed in your Tacview tracks directory (`%USERPROFILE%/Documents/Tacview`).

**Version information (please complete the following information):**
2.3.2

**Comment by DanAlbert** [comment]
Extremely unlikely that this is a Liberation issue. DCS is responsible for multiplayer synchronization, not us. Maybe the host or client isn't able to keep up with the simulation and can't send or receive the state quickly enough to sync up?

**Comment by DevastatorCM** [comment]
here is a sample log file from the problematic mission (https://drive.google.com/file/d/1vcKpBLXSdfCR6IoamcxxAuiMGXFcSJ1C/view?usp=sharing)

there are errors like "ERROR   SCRIPTING: DCSLiberation|127: Unable to find where to write DCS Liberation state" although json file is created
and there are other errors like

2020-12-23 18:49:01.684 ERROR   SCRIPTING: Mission script error: [string "C:\Users\ADMINI~1\AppData\Local\Temp\2\DCS.openbeta_server\/~mis00002B38.lua"]:31: attempt to index global 'io' (a nil value)
stack traceback:
	[C]: ?
	[string "C:\Users\ADMINI~1\AppData\Local\Temp\2\DCS.openbeta_server\/~mis00002B38.lua"]:31: in function 'write_state'
	[string "C:\Users\ADMINI~1\AppData\Local\Temp\2\DCS.openbeta_server\/~mis00002B38.lua"]:160: in function 'f'
	[string "C:\Users\ADMINI~1\AppData\Local\Temp\2\DCS.openbeta_server\/~mis00002C21.lua"]:1618: in function 'onEvent'
	[string "Scripts/World/EventHandlers.lua"]:13: in function <[string "Scripts/World/EventHandlers.lua"]:11>

**Comment by Mustang-25** [comment]
@DevastatorCM Are you still seeing this problem in more recent Liberation builds or can we close this one?

**Comment by DevastatorCM** [comment]
at the moment I do not face this issue anymore, so it can be closed
