### ISSUE TITLE
new AAA ZSU-57-2 generates non-gamebreaking bug error in cmd prompt display

### ISSUE THREAD

**Issue by Hornet2041** [dcs-liberation/dcs_liberation#640]
2020-12-21 17:29:18,307 :: ERROR :: Unable to determine target dict for <class 'dcs.vehicles.AirDefence.AAA_ZSU_57_2'>
AAA ZSU-57-2 cause issue

On build #838, PG Emirates invasion scenario
Save and .miz attached
[miz and save.zip](https://github.com/Khopa/dcs_liberation/files/5726873/miz.and.save.zip)

**Comment by Hornet2041** [comment]
now that I think about it, I haven't actually seen this unit spawn in the scenario.

**Comment by DanAlbert** [comment]
Problem is that we added the ZSU-57 to the Iraq 1991 faction as a front line unit, but that's not supported yet.
