### ISSUE TITLE
selling SAMs needs to cancel opfor missions planned against them

### ISSUE THREAD

**Issue by teun1het** [dcs-liberation/dcs_liberation#641]
**Describe the bug**
clicking take-off doesn't do anything in new savegame. The 'abort flight' etc. screen does not show up. The command prompt shows the following error: IndexError: list index out of range

**To Reproduce**
click on take-off in the added savegame. (haven't found a trigger for this to happen)

**Expected behavior**
basically, nothing.

**Additional information**
https://drive.google.com/file/d/13Sr2KI3EYiZqDsZSj2hcSgeYr-BUAMHA/view?usp=sharing - savegame

**Version information (please complete the following information):**
 - DCS Liberation v2.3.3-840-preview

**Comment by jeetsukumaran** [comment]
I've had this happen before. Usually Liberation has crashed behind the scenes. You can check the crash log in the shell window that is open in the background. Might be useful to copy and paste the stack trace you will find there into this report.

**Comment by DanAlbert** [comment]
It looks like opfor planned a mission against a SAM and then you sold that SAM, leaving them with no targets. Seems we need to rerun all of opfor's planning whenever the player sells/replaces/buys a SAM. Preferably selling SAMs would not be instant, but that's a much more involved change.
