### ISSUE TITLE
Strange workflow required to get easy setup of package with clients

### ISSUE THREAD

**Issue by martinruefenacht** [dcs-liberation/dcs_liberation#642]
**Is your feature request related to a problem? Please describe.**

When creating a package with a flight which has clients in it we can choose whether we want a warm start, etc, but when we the user doesn't do this in a specific order it leads to wrongly setup packages with clients in it. This situation has happened multiple times already either we have to wait 10 minutes or restart the server with a redone mission.

When creating a package and then a flight one sometimes remembers, but often forgets to set the warm *start type*. If one forgets and clicks ASAP first since with clients we typically want to take off ASAP then the switch from cold -> warm causes 
an easily overlookable 10 minutes to be added to the start time. (I assume this is the liberation assumed startup time)

A similar situation would happen with Runway and Flying starts. This also involves the TOT being to early causing flight starts before mission start time. This is already detected and offered to be fixed automatically.

**Describe the solution you'd like**

Any of these should work:
- Record ASAP having been clicked per package and therefore "reASAP" the package when any flights are modified.
- Automatically subtract the 10 minutes from the TOT of the package when switching a client flight from cold to warm/runway. (loads of corner cases potentially)
- Give a warning when client flights start more than (arbitrary number of seconds) after mission start time. Give an option to accept per package to save it if someone is wanting realism instead of fun.
- Make mission start time default for any client flights, except when explicitly set.

**Additional context**

I can't imagine many people are wanting to wait around for 10 minutes while they watch others or AI fly around, so really the default should be for client flights to begin at mission start, and the exceptional case of starting after mission start should be an edge case.

**Comment by DanAlbert** [comment]
Thanks for filing. Bugs me quite a bit too but I usually only notice when I'm already in the middle of fixing something else :)

Seems like a good candidate for when we're looking for UX polish to add toward the end of a release cycle.
