### ISSUE TITLE
Include S-300 sites as EWRs

### ISSUE THREAD

**Issue by DanAlbert** [dcs-liberation/dcs_liberation#645]
[Skynet recommends using S-300s as EWRs](https://github.com/walder/Skynet-IADS#act-as-ew-radar). While it would make the SAM more easily targeted, it has point defense so isn't very vulnerable. Its search radar has better range than the dedicated EWRs (55G6 and 1L13) and it can keep the IADS functional for short and medium range systems even after the dedicated EWRs are knocked out, so that seems worth the trade off.

**Comment by Hornet2041** [comment]
i think Skynet intends you to just place the Search Radar as the EWR unit rather than the whole search,track, launcher setup.

**Comment by Mustang-25** [comment]
Feature added in #1400
