### ISSUE TITLE
Feature Request: More TASK/ROLE options for missions

### ISSUE THREAD

**Issue by furiouscaulks** [dcs-liberation/dcs_liberation#65]
If this is still valid, it seems there are a lot of different task/role types that could be integrated into mission planning.

https://forums.eagle.ru/showthread.php?t=81246

Can all of these mission types, such as deep strike, FAC etc be integrated into mission planning?

**Comment by DanAlbert** [comment]
https://github.com/Khopa/dcs_liberation/issues/277 covers all the things we plan on adding.
