### ISSUE TITLE
Actions with long names truncate kneeboard info pages

### ISSUE THREAD

**Issue by jmyoung** [dcs-liberation/dcs_liberation#651]
Thanks very much for all the work with Liberation, it's great and given a huge new lease on life with DCS.

I've noticed in my campaign that very long action names, like with this example;

![page00](https://user-images.githubusercontent.com/16272847/103061768-46fd1b80-45fc-11eb-9b23-1a3f5c445da2.png)

Result in the Flight Plan table being truncated, and therefore missing critical information such as the arrival/departure times.  They probably simply need the table to have that column trimmed if it's over a certain number of characters.

**Comment by DanAlbert** [comment]
https://github.com/Khopa/dcs_liberation/issues/588
