### ISSUE TITLE
Display a performance warning for complex generated missions

### ISSUE THREAD

**Issue by Khopa** [dcs-liberation/dcs_liberation#653]
After the mission has been generated, we should display the number of units, buildings, aircraft, waypoints added in the miz file. 

Then we could display a performance warning, pointing to performance and culling settings if the mission is particularly complex. 

![image](https://user-images.githubusercontent.com/2546901/103096306-d8bc5700-4603-11eb-894a-6730085173c3.png)
*mockup*

**Comment by DanAlbert** [comment]
Button names look good 😆

Should include the common advice like "turn off wrecks, smoke, and infantry".
