### ISSUE TITLE
Mobile TACAN on Airfields

### ISSUE THREAD

**Issue by clairmont32** [dcs-liberation/dcs_liberation#657]
**Is your feature request related to a problem? Please describe.**
For ease of navigation for airframes that prefer TACAN navigation, it would be very helpful to have a mobile TACAN. The F/A-18C is unable to use ground based navigation systems.

**Describe the solution you'd like**
Place a mobile TACAN nearby the runway to provide a means of locating the airfield for visual approach.

**Comment by Hornet2041** [comment]
by what do you mean when you say the F/A-18C is unable to use ground based navigation systems? It can use both airfield TACAN and VOR systems in the game. Only Syria is devoid of any actual TACAN beacons since its still a WIP map.

**Comment by clairmont32** [comment]
I'll get more specific details from our CAP members. I know they repetitively said that Navy planes don't have ground based ILS systems for airport ILS systems but only ICLS for carrier landings.

**Comment by Hornet2041** [comment]
Putting mobile TACANs at airfields isn't going to fix that problem, though....

**Comment by clairmont32** [comment]
I was told it'll at least guide them to the airport and they can land visually from there. We were playing on Syria so it may be solved by ED over time. The only other alternative they had was to punch in a waypoint for the GPS cords when they're sitting at the numbers so they had it for the return trip but that's a much longer way than being able to put in a mobile TACAN on the field.

**Comment by DanAlbert** [comment]
Why not just set your arrival/divert airfields so you'll have a waypoint for the airfield?

**Comment by clairmont32** [comment]
We'll use the flight programmed WPs since you made that point and we're new to the platform. F/A-18Cs dont have equipment for VORs but the preprogrammed waypoints is basically an automated way of what he had stated for a manual WP on the numbers. Thanks for giving us the proper way of using the tool!

**Comment by Hornet2041** [comment]
You are incorrect, F/A-18Cs ingame are perfectly capable of utilizing VOR. Just punch in the VOR frequency on either comm radio and a symbol will appear on your HSI. Don't believe you get range though. But you get bearing and audio tones.
