### ISSUE TITLE
Feature Request: Integration of EWRS / Skynet

### ISSUE THREAD

**Issue by furiouscaulks** [dcs-liberation/dcs_liberation#66]
https://github.com/Bob7heBuilder/EWRS

**Comment by Khopa** [comment]
I was thinking of doing this with Moose and/or use the popular Skynet script.

**Comment by furiouscaulks** [comment]
Sorry ive been away MSFS2020 has me in deep.  Look forward to trying it out!

**Comment by Starfire13** [comment]
If possible, would prefer the Skynet SAM feature to be a toggleable option, because while it can be fun and challenging in singleplayer, it can also be frustrating in multiplayer sessions with a strike flight not able to proceed till the SEAD flight has successfully taken down all the SAMs. Thanks.

**Comment by davidp57** [comment]
That's how I planned to do it.
I already prepared a PR with an option for selecting a "LUA plugin" from a catalog, atm there is only (my) VEAF framework, but I intend to use this as a generic basis for integrating other frameworks (Skynet being the next one)

**Comment by DanAlbert** [comment]
This is partially implemented in develop. Skynet can be enabled in the plugin options and will affect SAM sites, but we're still working on generation of EW radars, C2, power, and communications nodes.

**Comment by DanAlbert** [comment]
I think we need EWRs for this to work, so that'll be in 2.2, but the rest has been forked into https://github.com/Khopa/dcs_liberation/issues/324

**Comment by DanAlbert** [comment]
EWRs added.
