### ISSUE TITLE
Huey spawning with low ammo?

### ISSUE THREAD

**Issue by clairmont32** [dcs-liberation/dcs_liberation#660]
Might fall under an enhancement but it seems to fall under a bug description as well.

**Describe the bug**
Without a custom loadout, various airplanes and helicopters come with either an excessive loadout (F/A-18C has missiles stacked to the brim), an odd loadout (A10-C II carrying only double rack 9Ms), or a partial ammo count (UH-1H with 300 bullets in each minigun but side gunner with full ammo), instead of an entirely blank loadout like they should have upon joining the mission.

**To Reproduce**
1. Create flight and edit it with desired waypoints/tasks
2. Do not set a custom loadout
3. Take-off and load mission (either SP or MP)
4. Load into F/A-18 or other plane and observe loadout not being blank.

**Expected behavior**
Loading into an empty airship or rotor craft. 

We will usually need more information for debugging. Include as much of the following as you are able:

- DCS Liberation save file (the `.liberation` file you save from the DCS Liberation window). By default these are located in your DCS saved games directory (`%USERPROFILE%/Saved Games/DCS`).
[Test Mission 2.zip](https://github.com/Khopa/dcs_liberation/files/5742248/Test.Mission.2.zip)

- The generated mission file (the `.miz` file that you load in DCS to play the turn). By default these are located in your missions directory (`%USERPROFILE%/Saved Games/DCS/Missions`).
[liberation_nextturn.zip](https://github.com/Khopa/dcs_liberation/files/5742249/liberation_nextturn.zip)

**Version information (please complete the following information):**
 - 2.3.2

**Comment by DanAlbert** [comment]
> instead of an entirely blank loadout like they should have upon joining the mission.

This is what custom loadouts are for. Empty would be a terrible default because it'd take a huge amount of effort to set up every AI flight. Most people don't want to do that.

Beyond that, a future release is going to have different flight plan behavior based on your loadout, since different weapons will have different engagement distances and different target waypoint requirements. Some day DCS will make it possible to set up PP targets in the mission. None of those things work if your jet starts empty.

The reality is that no matter what the defaults are someone is going to think they're terrible. Our defaults are what work well for the AI because most of the game is the AI. Additional units harm performance, additional missiles do not.

> A10-C II carrying only double rack 9Ms

Not the behavior I've seen. Do you have them tasked to the wrong mission type?

> UH-1H with 300 bullets in each minigun but side gunner with full ammo

But this might be a bug.

**Comment by clairmont32** [comment]
Ahh from an AI perspective I can understand the FA18s load out. I'll forward this along to our CAP members since they had complained of the bird being entirely full of missiles.

For the single A10 flight, I made it a client slot and loaded a flight with tanks to kill but nothing else. It may have been loaded with you only 9Ms since BARCAP was the only thing I could select for a task type. 

This was the same situation for the Huey but instead of tanks it was a pair of BTRs and infantry as the target.

Let me know if you need screenshots or other logs. More than. Happy to provide them for you.

**Comment by clairmont32** [comment]
Also, on the BARCAP note, we've been seeing Hueys only allowed to select BARCAP missions as well. Should I open a second issue for this?

**Comment by DanAlbert** [comment]
> It may have been loaded with you only 9Ms since BARCAP was the only thing I could select for a task type.
>
> we've been seeing Hueys only allowed to select BARCAP missions as well. Should I open a second issue for this?

Your package target matters: https://github.com/Khopa/dcs_liberation/wiki/Mission-planning

**Comment by DanAlbert** [comment]
>> UH-1H with 300 bullets in each minigun but side gunner with full ammo
>
> But this might be a bug.

Guns are on or off. We don't seem to have any control over the ammunition quantity. Are you sure it loads more ammo than that?

**Comment by clairmont32** [comment]
> > A10-C II carrying only double rack 9Ms
> 
> Not the behavior I've seen. Do you have them tasked to the wrong mission type?

Unfortunately, when we went to set up the flight for the turn all we had was BARCAP for a tasking. Here's a screenshot of when I first loaded in showing the 9Ms onboard with nothing else on the pylons.

![image](https://user-images.githubusercontent.com/6239004/103144478-cae7fe00-46f7-11eb-99d8-e2ed347d45b4.png)






> > > UH-1H with 300 bullets in each minigun but side gunner with full ammo
> > 
> > 
> > But this might be a bug.
> 
> Guns are on or off. We don't seem to have any control over the ammunition quantity. Are you sure it loads more ammo than that?

Looks like that the ammo count is abbreviated by default when you load in without setting the payload in Liberation but when you replace them or remove/re-add the miniguns to the pylons it doesnt display the ammo count so this turns into a non-issue.

**Comment by DanAlbert** [comment]
> Unfortunately, when we went to set up the flight for the turn all we had was BARCAP for a tasking

As I said, your package target matters. Depending on what position you chose when creating the package BARCAP may have been the only option.

> Looks like that the ammo count is abbreviated by default when you load in without setting the payload in Liberation but when you replace them or remove/re-add the miniguns to the pylons it doesnt display the ammo count so this turns into a non-issue.

Ack.
