### ISSUE TITLE
Unable to Generate Packages (Build 893 & 894)

### ISSUE THREAD

**Issue by Mustang-25** [dcs-liberation/dcs_liberation#668]
**Describe the bug**
Packages will not auto-generate. Attempting to manually generate packages also do not work and the log says that it cannot estimate TOTs and an error with the navmesh. See image and attached save. I've tried it with multiple maps and they all have this issue.

**To Reproduce**
1. generate any campaign
2. try to create a package

**Additional information**
This looks like the same problem as #650 maybe?

![unknown](https://user-images.githubusercontent.com/72566076/103157945-71bab180-476d-11eb-8916-93a7cc654dbf.png)

[Turkey_test.zip](https://github.com/Khopa/dcs_liberation/files/5743555/Turkey_test.zip)

**Comment by DanAlbert** [comment]
> This looks like the same problem as #650 maybe?

Yup. Same problem, but this time the range was right and scuds were wrongly blowing the threat zones way out. https://github.com/Khopa/dcs_liberation/issues/666 is the root cause here. Thanks for the save for testing, made it easy!
