### ISSUE TITLE
Planes not landing on Supercarrier?

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#675]
**Describe the bug**
Planes that take off from the Supercarrier module do not appear to be landing on it and ejecting instead.  This might be a DCS bug?

**To Reproduce**
1. Generate a mission with 12+ F-A/18Cs launching from the Supercarrier.
2. Play the mission (I also used Combined Arms after I had returned to the carrier)
3. Watch almost every aircraft eject after running out of fuel (presumably).

**Expected behavior**
Planes that launch from the supercarrier, land on the supercarrier, and don't eject.

**Additional information**

Campaign/Mission/Track/Tacview here:
(File hosted by WeTransfer, I know the link looks sketchy AF but I've successfully used the service in the past, only in the email delivery though, not in the "get a link" form.)
https://we.tl/t-8ARJZ1lcTy

**Version information (please complete the following information):**
 - DCS Liberation 2.3.2

**Additional context**
I told my wingman to RTB when they reached bingo status.  They flew around then ejected when running out of fuel.
I was using Combined Arms / Controlling units after I had landed.

**Comment by Hornet2041** [comment]
this is definitely a DCS bug.

**Comment by DanAlbert** [comment]
> I told my wingman to RTB when they reached bingo status. They flew around then ejected when running out of fuel.

Yeah, once you do that it can't be our bug because they're no longer under our control.

**Comment by SnappyComebacks** [comment]
Do you feel the same way about the AI only flights?  (Like that it's a DCS bug?)

**Comment by DanAlbert** [comment]
If they have a landing waypoint in the mission and they aren't landing it's a DCS bug. If they don't have a landing point it's our bug.

**Comment by clutchtomcat** [comment]
AI land on the Supercarrier as normal for me in my own missions, and there are no reports of this bug on the ED forums, so it is unlikely to be a DCS bug.

**Comment by Hornet2041** [comment]
Try creating a blank mission where 12-40 aircraft have to return to the carrier all at once. You may see them start circling the carrier at something like 200 feet and 400 knots endlessly in some sort of broken logic loop.

**Comment by clutchtomcat** [comment]
That sounds more like an error on the part of the mission designer than a game issue. It works fine with 4~8 aircraft in the stack, and there really shouldn't be any more than that in our missions.

**Comment by Hornet2041** [comment]
I'm telling you how to reproduce the bug. You can see it happen either in liberation missions or out of them. Therefore, it is a DCS bug.

**Comment by DanAlbert** [comment]
And if you want to avoid it, mission planning is within your control. If you don't want to have to worry about it (and IMO you shouldn't have to) you should be filing bugs against Supercarrier. That's a paid module that's supposed to handle carrier ops, and it sounds like it isn't prioritizing low-fuel flights in the marshal stack. It's not possible for mission designers to fix that with the limited control we have over the AI.
