### ISSUE TITLE
Channel Map performance

### ISSUE THREAD

**Issue by clutchtomcat** [dcs-liberation/dcs_liberation#678]
I get good performance on the Channel Map without running DCS Liberation, but with Liberation running the Dunkirk mission and relatively few units, I get 7~10 frames per second. Comparatively, a much more complex scenario with way more units in Syria runs fairly well for me.

Can anyone confirm whether this is a Liberation issue or a Channel map issue?

**Comment by Starfire13** [comment]
I actually get noticeably better performance on Channel map than Syria map in Liberation.

**Comment by clutchtomcat** [comment]
I tried the Battle of Britain scenario and got flyable performance, but still terrible performance around Manston. Syria ran smoother for me for some reason.

**Comment by DanAlbert** [comment]
If your performance issues are local to an airport I think that's probably just something in the new OB. The way I understand it adding more units to the game causes global performance load, not local.

**Comment by clutchtomcat** [comment]
We have control over how many own-faction ground units to purchase, but could we get control over how many enemy units to purchase so that we can better tweak performance to our individual systems? Even culling to 100km isn't enough to mitigate the performance hit of ground units.

**Comment by DanAlbert** [comment]
> but could we get control over how many enemy units to purchase

I thought this was in 2.3 but maybe it's not until 2.4, but you can control the income of the enemy faction. There's an FR open already for setting a CAP on ground units.

**Comment by DanAlbert** [comment]
Unit cap is a campaign property now via ammo depots.
