### ISSUE TITLE
2.0.11 Bug: Player aircraft still spawning in air when runway start is picked.

### ISSUE THREAD

**Issue by furiouscaulks** [dcs-liberation/dcs_liberation#68]
Possibly tied to having the start time set to 0 minutes.

**Comment by rabauke80** [comment]
Or the airfield over capacity at the given start time? Also happened to me when picking cold start, but all parking slots where used by AI, so I spwawned mid-air.

**Comment by ToKeNeRd** [comment]
This is big for me too I have tried all suggestions nothing works

**Comment by ToKeNeRd** [comment]
This is a bug for me as well tried all suggestions but nothing works

**Comment by rabauke80** [comment]
> This is a bug for me as well tried all suggestions but nothing works

try reducing the total number of aircraft departing, incl. yours, to lower/equal the total number of parking lots on the airfield - you will start in the desired mode then

**Comment by ToKeNeRd** [comment]
> > This is a bug for me as well tried all suggestions but nothing works
> 
> 
> 
> try reducing the total number of aircraft departing, incl. yours, to lower/equal the total number of parking lots on the airfield - you will start in the desired mode then


I've tried the same mission on two different version the alpha-2 and 2.10 and with 2.10 no issue but alpha it forces me in the air even tried reducing aircraft on airfield but no change.

**Comment by Khopa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Big issue with air start in current version](https://trello.com/c/TKLptLE5/131-big-issue-with-air-start-in-current-version)

**Comment by DanAlbert** [comment]
This was fixed in one of the 2.1 releases. Don't remember which one.
