### ISSUE TITLE
Certain guided weapons should have a cost associated to them

### ISSUE THREAD

**Issue by Galwran** [dcs-liberation/dcs_liberation#688]
**The problem:** 
Over use of precision guided weapons. The player has no reason to use less precise munitions.

**The solution:**
There should be a cost associated to the guided weapons. This would motivate the player to not spam the battlefield with expensive munitions.
The cost of the used weapons would be deducted from the next turn's budget. This is simpler to the AI than the DCS warehouse system, as the weapons can not run out.

As an example I suggest the following three categories of cost per weapons. These cost are not prohibitive, but you would still think twice before wasting a JSOW on a truck. Air to air weapons could be categorized the same way.

Category A, cost 3 million per use of a weapon.
HARM, JSOW-A and JSOW-C

Category B, cost 2 million per use of a weapon.
JDAMs, Mavericks

Category C, cost 1 million per use of a weapon.
LGBs

**A suggestion for the technical solution:** 
Use of such weapons is parsed from the DCS mission logs. Total amount of uses per faction are tallied together, and the sum of costs is deducted from the next turn's budget.

**Limitations:**
This solution is a simple one, and will only count the weapons that were used (ie. if you are shot down while carrying 4 HARMS, you will not have to pay for them)

**Comment by DanAlbert** [comment]
Other FRs have already been filed for this.
