### ISSUE TITLE
Mission Preparation: Departure time not updating

### ISSUE THREAD

**Issue by rabauke80** [dcs-liberation/dcs_liberation#69]
If you change the "At T+" for an existing flight, it's time is only updated on the list of flights, once you add/remove a flight. Either dynamically updated the changes made to the flight, or add a save button which updates it.

If the time is actually updating in-game, or it's just a display but, needs to be tested/verified.

**Comment by Khopa** [comment]
Thanks, should be fixed in 2.1.0. 
Please re-open if you encounter the issue again with the new version.
