### ISSUE TITLE
add a scroll function to the intel window

### ISSUE THREAD

**Issue by Hornet2041** [dcs-liberation/dcs_liberation#691]
Right now if there are a lot of different aircraft and units displayed in the intel window, the text will be compressed eventually into nothingness until the window is expanded. If scrolling was enabled, I assume it wouldn't be crushed at start and would be readable. Pics attached for clarity.
![image](https://user-images.githubusercontent.com/55866858/103245041-e12acf80-492c-11eb-97eb-f36777ce24f2.png)
![image](https://user-images.githubusercontent.com/55866858/103245056-f0118200-492c-11eb-9304-3fb24c23c844.png)
![image](https://user-images.githubusercontent.com/55866858/103245068-fe5f9e00-492c-11eb-8b10-4028121ca97b.png)

**Comment by Malakhit** [comment]
Added for 2.4.
