### ISSUE TITLE
Possible to change default altitudes? 

### ISSUE THREAD

**Issue by clutchtomcat** [dcs-liberation/dcs_liberation#694]
I'm having fun with the WW2 Liberation, but I find the auto-generated flight plans to be way too low: 8,000 to 13,000ft range. With flak the AI will get torn to shreds that low. Editing all the flight plans to bring them up to a more realistic 15,000 to 20,000ft would take forever. Is there a .lua file that can be edited to change the default altitudes?

Also, is there an updated Wiki somewhere? The one here doesn't explicate enough on creating custom payloads or include anything about chosing default liveries, which I believe was introduced in the latest release.

**Comment by DanAlbert** [comment]
Duplicate FR.

**Comment by clutchtomcat** [comment]
What about an updated guide? There is no documentation on some 2.3.0 features like setting default liveries, proper payload naming, etc. I've asked around a dozen places over the last month and gotten no clarification.
