### ISSUE TITLE
Wind direction on DCS Liberation menu bar is depicted incorectly

### ISSUE THREAD

**Issue by qwertymanisalive** [dcs-liberation/dcs_liberation#695]
![lib winds](https://user-images.githubusercontent.com/39744809/103261867-ddf90900-4957-11eb-8d08-905cf6139695.PNG)
![mission editor wind](https://user-images.githubusercontent.com/39744809/103261874-e7827100-4957-11eb-972e-8635fb43bbed.PNG)

Before filing, please search the issue tracker to see if the issue has already been reported.

**Describe the bug**
Wind should be depicted as wind from a direction, not wind to a direction. 353 degrees at 2 knots is wind from the north, not wind blowing to the north. This would be in line with the way aviation weather reports describe wind direction

DCS mission editor describes wind in the same weird way.

https://en.wikipedia.org/wiki/METAR#International_METAR_codes

**Comment by clutchtomcat** [comment]
DCS issue. We've complained about it for nearly a decade now and ED refuses to fix it.

**Comment by DanAlbert** [comment]
Consistency with DCS is the desired behavior IMO.

**Comment by HILOK** [comment]
what about an option for "western wind notation" that shifts the display in the top bar by 180 degrees? i.e. wind direction FROM as opposed to TO (a tooltip showing "to" or "from" could come in handy)

while we are at it: any chance we could get the wind direction rounded to the nearest tens IN THE REPORT? -more realistic. personally i would suggest only rounding in the report/kneeboard, and leaving the wx generator as is -also more realistic.
