### ISSUE TITLE
Unable to sell OPFOR aircraft after capturing base - 2.3.2

### ISSUE THREAD

**Issue by gatorman22** [dcs-liberation/dcs_liberation#697]
**Describe the bug**
As blufor in SP, capture a red airbase containing aircraft, the aircraft are also captured and can be tasked, but if I don't want them taking up parking spaces at that base I cannot sell them (they do not show in the inventory).  Right now if I don't have a use for them, I relocate them to a base behind the front lines, or one with a lot more parking.

**To Reproduce**
1. Capture red base
2. Cannot sell red aircraft

**Expected behavior**
I would like to sell these captured aircraft from inventory so that I may reuse those funds elsewhere.  This would also provide incentive to capture a base without destroying all its parked aircraft.

**Version information (please complete the following information):**
 - DCS Liberation 2.3.2

**Comment by DanAlbert** [comment]
The bug is that you're capturing redfor aircraft. Another report is already open for that.
