### ISSUE TITLE
custom flight plans for tankers-go to tanker waypoint for ai wingmen

### ISSUE THREAD

**Issue by KeeseAF** [dcs-liberation/dcs_liberation#699]
Before filing, please search the issue tracker to see if this feature has already been requested.

**Is your feature request related to a problem? Please describe.**
**Describe the solution you'd like**

**Additional context**

**Comment by KeeseAF** [comment]
Adding a custom flight plan by click and drag, similar to naval movement for tankers.

**Comment by Mustang-25** [comment]
Editable flight plans for tankers have been added in the latest release.
