### ISSUE TITLE
Ground Units Could Do With Some SHORAD

### ISSUE THREAD

**Issue by TezzaCourtney** [dcs-liberation/dcs_liberation#7]
It would be a nice enhancement to have the ground groups on the front-line to have some SHORAD associated with them.

For example groups of infantry sometimes have some shoulder launched MANPADS and the armoured groups have AAA\SAM such as ZSU-23-4 or SA-13\SA-8\SA-9 moving along with them.

Of course it would be great if they were part of the purchasing system, but that could potentially end up with SHORAD spamming. If there were a limit in place for the amount that can be purchased for a group, that might keep it interesting but not over the top.

**Comment by Khopa** [comment]
I agree, i intend to add this in the future.

**Comment by Khopa** [comment]
https://github.com/Khopa/dcs_liberation/commit/37e23f70d6d9c08cf499f61f6f8714c3a00d4a08
Some factions will now sometimes spawn manpads in their infantry squads on the frontline.
