### ISSUE TITLE
Let the user choose between NVG, HMCS, and None

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#706]
**Is your feature request related to a problem? Please describe.**
If a user is playing a night mission and has to choose between NVG, HMCS, or none, they must do this in the DCS mission editor or while playing.

**Describe the solution you'd like**
Let the user choose between NVG, HMCS, and None in Liberation, on player flights if available.

**Additional Context**
This might be plane specific, as things like HMCS does not exist for WWII planes.

**Comment by HighwaymanEd** [comment]
Agreed, this would be useful, as well as options to set laser codes for the F-16

**Comment by SnappyComebacks** [comment]
> Agreed, this would be useful, as well as options to set laser codes for the F-16

I agree, see the linked issue.

#718

**Comment by DanAlbert** [comment]
I don't see an option to do this in the ME for the Viper or Hornet.

**Comment by DanAlbert** [comment]
Oh! A whole bunch of other tabs showed up when I made it a player slot :) Never mind
