### ISSUE TITLE
Feature Request: Client Network Connectivity/Gamemaster Mode

### ISSUE THREAD

**Issue by furiouscaulks** [dcs-liberation/dcs_liberation#71]
Although I'm not a multiplayer, and I'm not sure if this is possible, but perhaps you'd be interested in this as a feature?  Networking between Liberation and the existing multiplayer framework, or between the Liberation client and a DCS server to allow one user to be a gamemaster, setting tasks for users on the server to play out the mission, the results of which could then be sent back to each Liberation client updating the game map?

**Comment by DanAlbert** [comment]
Duplicate of #104
