### ISSUE TITLE
Upgrade to SKYNET 2.0.0 and HighDigitSAMs

### ISSUE THREAD

**Issue by qwertymanisalive** [dcs-liberation/dcs_liberation#717]
SKYNET  2.0.0 has been released by Walder. Can it be updated in Liberation?

https://github.com/walder/Skynet-IADS/releases/tag/2.0.0

The new SKYNET also supports HighDigitSAMs which contains several upgraded and more lethal SAM units.

https://github.com/Auranis/HighDigitSAMs

**Comment by DanAlbert** [comment]
Upgrade was already on my todo list, but thanks for filing :) Plan to do that in the next day or two.

High Digit SAMs already has an open FR.
