### ISSUE TITLE
Allow the user to change laser codes in the UI

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#718]
**Is your feature request related to a problem? Please describe.**
Depending on the aircraft used, laser codes must be set before the mission begins.  This can require setting laser codes within the ME.

**Describe the solution you'd like**
Ability for the user to set the laser codes of aircraft/weapons in the UI.  Ability to handle individual aircraft.  Perhaps also being able to set JTAC laser codes.

Laser codes for player flights should also be in the briefing.

**Additional context**
Depending on the aircraft, there is a valid range of numbers for the laser code.  It would be desirable to restrict laser codes to the valid range.  If changing the JTAC codes is to be implemented it may be a good idea to restrict laser code values to values that every aircraft can support.

**Comment by dimkzr** [comment]
@SnappyComebacks 

> Depending on the aircraft used, laser codes must be set before the mission begins.

Can you please provide an example? I mean, I know that with the F-16 and F-14 you must do it via kneeboard. But I'm not aware of any aircraft that forces you to do this in the ME.

**Comment by gatorman22** [comment]
Pasted and linked for resource: https://forums.eagle.ru/topic/211574-valid-laser-codes

> Like radio frequencies, certain laser codes (PRF's) are assigned to specific agencies/equipment.
> 
>  
> 
> These (1111-1788 ) are further subdivided into blocks for use by artillery, air and ground forces to prevent interference with each others operations.
> 
>  
> 
> Some equipment/weapons support a wide range of codes, others do not and are designed to make setting a 'wrong' code impossible.
> 
>  
> 
> A GBU-12 laser code is set on the bomb using selector switches
> 
>  
> 
> • 1st digit = 1
> 
> • 2nd digit = 5-7
> 
> • 3rd and 4th = 1-8
> 
>  
> 
> It is physically impossible (i.e. there is no switch position) to set a non-allowed code.
> 
>  
> 
> The same is true of some electronic designators i.e. it's in the specs, and the unit will only accept an allowed range of codes.
******

> I suspect the real reason for no nines or zeros is that it is octal. 8 is what you can get out of 3 bits of memory. Memory is stored in binary, there are only 8 combinations of 3 zeros and ones. in order to add an additional 2 numbers requires an extra bit of memory and its a waste of memory when 8 values is enough to do the job. It's the same with transponder codes, except they use 0-7 instead of 1-8.
******

> The 1688 code?
> It's just the default. Only reason I can think of it being that way is for LTD from AC-130H, which is hard-set to 1688 and cannot be changed (according to JP 3-09.1).

**Comment by gatorman22** [comment]
I modified armor.py locally to add random generated JTAC laser codes conforming to the above info.  Should output 1511 thru 1788.  I'm sure there are better ways, I just like to tinker.
```
bit_b = random.randint(5, 7)
bit_cd = random.randint(1, 8)
code = "1" + str(bit_b) + str(bit_cd) + str(bit_cd)
```

**Comment by DanAlbert** [comment]
> Depending on the aircraft used, laser codes must be set before the mission begins.

I don't see how to do this in the ME for anything but the Harrier's APKWS and the Mirage's GBU-12s. Is that all you had in mind, or did I just miss the option in the ME?

**Comment by DanAlbert** [comment]
> did I just miss the option in the ME?

Yes! A few more tabs show up for player slots that don't for AI flights. It looks like we can set the _weapon_ codes for everything but the A-10 and hornet. Don't know if the TGP changes to match.
