### ISSUE TITLE
AH-1W cost is too high

### ISSUE THREAD

**Issue by HighwaymanEd** [dcs-liberation/dcs_liberation#722]
The AH-1W attack helicopter is priced at $20M in liberation, the same price as an F-16C. Pricing per unit for the Whiskey model was around $10M according to a couple of sources circa 2007.

**Comment by Starfire13** [comment]
Liberation don't use actual real world costs. It's not like you're actually buying them from the manufacturer's webstore when you run out.

**Comment by HighwaymanEd** [comment]
I appreciate that we can’t use real world costs, but the price of this unit in comparison to others is excessive.

**Comment by Starfire13** [comment]
Oh, definitely. Some tweaking is needed. My point is that you can't use real world costs as the reason for the change.

**Comment by jake-lewis** [comment]
Prices rebalanced https://github.com/dcs-liberation/dcs_liberation/blob/2c859bf280ec9b8d9f84e0cc4eb8f7a203254160/resources/units/aircraft/AH-1W.yaml
