### ISSUE TITLE
add more weapon data

### ISSUE THREAD

**Issue by DanAlbert** [dcs-liberation/dcs_liberation#723]
I handled fox 3 missiles inhttps://github.com/Khopa/dcs_liberation/issues/490, but there are almost 1000 more weapons in DCS (every type of rack, every multiple of weapon per rack, every variant of the weapon, etc). Happy to accept patches, but don't plan to pursue this further.

**Comment by Mustang-25** [comment]
Most of this was resolved a few months ago so I'm going to close this one out.
