### ISSUE TITLE
Show default loadout in UI when not using custom loadout

### ISSUE THREAD

**Issue by DanAlbert** [dcs-liberation/dcs_liberation#725]
Should show the default loadout in the UI when the flight doesn't have a custom UI. Will help avoid empty flights for the cases where we're missing a default, and make it cleared when people want a custom loadout.

**Comment by Malakhit** [comment]
Completed by #732.

**Comment by Hornet2041** [comment]
Minor quality of life issue, but is it possible that when selecting "use custom loadout", the loadout list doesn't clear every payload but just allows the stations to be edited? Most of the default payloads have the basic a2a self defense loaded properly, it gets a bit tedious having to re-do it 😋

**Comment by Malakhit** [comment]
@Hornet2041 Okay, I've now implemented this! Thanks for the suggestion.
