### ISSUE TITLE
AI takeoff hampered by spawned vehicle on taxiway

### ISSUE THREAD

**Issue by currenthill** [dcs-liberation/dcs_liberation#728]
During a mission I noticed a lack of red air assets. It turned out that their QRA was hampered by a spawned vehicle blocking the taxiway.

![QRA hampered by spawned vehicle on taxiway](https://user-images.githubusercontent.com/69079101/103715194-45e6c980-4fc0-11eb-8b8a-96a203a3a4c6.jpg)

**Comment by DanAlbert** [comment]
We need to know what airfield that is.

**Comment by currenthill** [comment]
Sorry, it's at Mineralnye Vody.

**Comment by Mustang-25** [comment]
Is this still a problem in the latest release? If it is, which campaign? If not we can go ahead and close this one out.

**Comment by DanAlbert** [comment]
If it is today it won't be when 3.0 releases since the campaign needs to be redone with non-random spawns anyway. Always a chance that the campaign designer that reworks it makes a new mistake, but that'd need a bug with different details than this one since it'd be campaign specific.
