### ISSUE TITLE
Disabling AI planes parking start does not effect friendly planes.

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#729]
**Describe the bug**
Friendly planes are starting from ramp when `AI planes parking start (AI starts in flight if disabled)` is disabled.

**To Reproduce**
1. Create Syrian Civil War Campaign (USA 2005, Libya 2011)
2. Disable `AI planes parking start (AI starts in flight if disabled)`
3. Load up `Bassel Al` with F16s and F18s
4. Have player flight _not_ at `Bassel Al`
5. Make all packages TOT's `ASAP`
6. Watch traffic at `Bassel Al`

**Expected behavior**

- Friendly planes should start in air instead of at ramp when disabling `AI planes parking start (AI starts in flight if disabled)`
- When `AI planes parking start (AI starts in flight if disabled)` is enabled, planes shouldn't be taxiing into each other.

**Additional information**

Ran into this on the first mission of a campaign:
![Standoff](https://user-images.githubusercontent.com/74509817/103724202-0654b900-4f91-11eb-9433-c7f09198e06f.png)

With `AI planes parking start (AI starts in flight if disabled)` **enabled** planes were taxiing to block each other.  So I disabled  `AI planes parking start (AI starts in flight if disabled)` and planes are still using `Takeoff From Ramp`, leading to this situation.

Tacview, Campaign, and Mission:
[Standoff.zip](https://github.com/Khopa/dcs_liberation/files/5773744/Standoff_2.zip)

**Version information**
 - DCS Liberation 2.3.4

**Comment by br34k0r** [comment]
Can confirm - with every version of DCS Liberation the friendly planes at Bassel Al start to block each other when entering the runway via taxiway B and C on runway 17R. So no missions are carried out from the whole airport

**Comment by DanAlbert** [comment]
The setting is labeled incorrectly for some reason. What it actually does is choose between cold and warm starts.
