### ISSUE TITLE
Feature Request: add budget preview to purchase dialogue

### ISSUE THREAD

**Issue by root0fall** [dcs-liberation/dcs_liberation#73]
Currently when purchasing vehicles, there is no live update to the available budget.

User must wait until committing to the purchases to see remaining budget, or reach the point where further vehicles are unable to be purchased to determine insufficient funds. 

see pull request #72

**Comment by Khopa** [comment]
Thanks for the PR, this was indeed a much needed missing feature. 👍 
I merged it, and this will be included in the next version.

**Comment by root0fall** [comment]
excellent, thanks!

**Comment by Khopa** [comment]
This has been integrated in 2.1.0, closing the issue.
