### ISSUE TITLE
"Unable to write DCS Liberation state to [nil]"

### ISSUE THREAD

**Issue by eyildirir** [dcs-liberation/dcs_liberation#730]
Previously filed issues related to this: #141 

**Description**
I am having the exact issue with #141, same messages in-game and the error message when I quit DCS World.

![Screenshot 2021-01-05 224741](https://user-images.githubusercontent.com/24274786/103727166-a0742b80-4fa8-11eb-97a2-118e063b093c.png)

![Screenshot 2021-01-05 224756](https://user-images.githubusercontent.com/24274786/103727176-a36f1c00-4fa8-11eb-93db-1b58fc494b92.png)

I have checked the MissionScripting.lua in DCS installation folder, and I have noticed that it reverts back to its original state.

**Additional Information**
- DCS Liberation save file: [Syrian_Uprising.zip](https://github.com/Khopa/dcs_liberation/files/5773846/Syrian_Uprising.zip)
- The generated mission file: [liberation_nextturn.zip](https://github.com/Khopa/dcs_liberation/files/5773830/liberation_nextturn.zip)

**Version information:**
 - DCS Liberation: 2.3.4

**Additional context**
- I have a few mods I usually run: Twitch2DCS, SRS-Mod, TacView, VAICOMPRO, DCS-Presence (Discord)
- I have tried reinstalling DCS and the issue went away for the first launch, and then came back after.
- I've tried not using VAICOMPRO, but to no avail.
- I don't have Liberation installed under Program Files. It's not even on the OS drive, it's on the same secondary drive with DCS World.

**Comment by HighwaymanEd** [comment]
The MissionScripting.lua will revert after every update or repair of DCS, and often it's best to just follow the instructions to manually copy the file from Liberation\resources into your DCS\Scripts folder.

**Comment by eyildirir** [comment]
But is it normal for it to revert at every DCS launch? Because even if I don't repair or update, every single time I launch DCS, it reverts...

**Comment by DanAlbert** [comment]
It patches the file when you launch liberation and reverts it when you close liberation. If you launch DCS first DCS won't see the change (which is why the instructions say to restart liberation **and then** restart DCS).

**Comment by eyildirir** [comment]
I don't know why you closed it as if it's resolved, but I followed the instructions and launched Liberation first. When I launch DCS **AFTER** Liberation, it overwrites the file on launch. I have managed to make the file read-only so that it can't, but it is only a stop-gap solution as it cannot revert after I close Liberation. Maybe you should focus on making Liberation turn it read-only while running instead of dismissing a legitimate issue claim, so that the issue can be **ACTUALLY SOLVED**.

**Comment by DanAlbert** [comment]
No need to get angry, I just misunderstood. Reopening is easy so no harm done.

**Comment by eyildirir** [comment]
I'm sorry, but I have been trying to figure out how to fix this since early December, and the nonchalant dismissal of my issue, both here and on discord has not helped at all. 

I have been digging into it a bit further over the last hour, and the most probable culprit is VAICOMPRO, hooking into DCS. Or some other mod. To stop this, I have coded something that works for me for now, and I can share it if you want. I basically created a couple of batch files that I run after I run Liberation, and before I exit it. They automatically set and unset read-only.

[liberation_batch.zip](https://github.com/Khopa/dcs_liberation/files/5775375/liberation_batch.zip)

`liberation_main_fix.bat` starts Liberation, and sets the file read-only after 5 seconds (rudimentary misuse of ping function...)
`liberation_set_read-only.bat` and `liberation_unset_read-only.bat` do what the names say.

Mind you, the paths are hard-coded, but it shouldn't be too hard to add a variable for that.

You guys might be able to use this as a starting point.

**Comment by DanAlbert** [comment]
If the issue goes away without mods you should probably raise the issue with whatever mod is causing it. Fiddling with read-only properties sounds like a good way to get very surprising behavior out of DCS when it updates.

**Comment by DanAlbert** [comment]
Also for what it's worth last I heard vaicom doesn't work with Liberation anyway (though that's been reported by only one person and none of the developers use it so we have no idea), so if disabling that fixes the problem it may be something you'd need to do anyway.

**Comment by HighwaymanEd** [comment]
Our squad all use VAICOM with it without issues, although the missions are running on our Dedicated server, but the MP save and tests all run fine on my PC with VAICOM.

I also set the MissionScripting file to read only, but DCS replaces the file still after an update, so I simply copy it back from the liberation/resources and make it read only again...

**Comment by DanAlbert** [comment]
It occurred to me that since no one else has reported DCS reverting these changes on every launch, it's likely one of your mods doing it, and it likely isn't a revert so much as its own modifications that it needs to operate. Can you post the "reverted" file here so we can compare it with the stock file?

**Comment by KeeseAF** [comment]
Hey, i too had this problem and also got annoyed with the nonchalant dismissal from the discord. It seems that whenever i run as admin, it keeps the luascripting file where its supposed to be. So I suggest running as admin, So try that bud!

**Comment by KeeseAF** [comment]
And I run Vanilla DCS Open Beta and Lib, i have no mods.

**Comment by eyildirir** [comment]
> Hey, i too had this problem and also got annoyed with the nonchalant dismissal from the discord. It seems that whenever i run as admin, it keeps the luascripting file where its supposed to be. So I suggest running as admin, So try that bud!

I have actually tried it before, and it still does it. As I've mentioned, the only thing that worked without any hiccups was the read-only enforcement.

**Comment by eyildirir** [comment]
> It occurred to me that since no one else has reported DCS reverting these changes on every launch, it's likely one of your mods doing it, and it likely isn't a revert so much as its own modifications that it needs to operate. Can you post the "reverted" file here so we can compare it with the stock file?

I have already compared it to the original, it seems to be a match, byte-by-byte. I can send it if you want, but I don't really see the point.

**Comment by Hornet2041** [comment]
is this still an issue on 2.5.1?

**Comment by DanAlbert** [comment]
Being caused by some mod seems like the most likely answer here (and the problem fixed by running as admin is a lack of permissions problem, which is different than our overwrite being clobbered). Without knowing what is causing the problem I don't think there's anything for us to investigate.
