### ISSUE TITLE
Carrier SAM Threat Rings Don't Move

### ISSUE THREAD

**Issue by Mustang-25** [dcs-liberation/dcs_liberation#735]
**Describe the bug**
SAM threat rings for the carriers do not follow them when they move.

**To Reproduce**
1. create a campaign with carriers
2. move the carriers

![image](https://user-images.githubusercontent.com/72566076/103797677-a3e5d200-4ffd-11eb-8ad9-560ff80539a7.png)

![image](https://user-images.githubusercontent.com/72566076/103798850-228f3f00-4fff-11eb-8fd5-b20a2c6a2754.png)

**Comment by SimonC6R** [comment]
From a quick test, it looks like the threat radius is being redrawn regularly, so I think that what's happening here is the ground object that represents the threat is not being moved along with the carrier group. Will check further.

**Comment by Malakhit** [comment]
Should be fixed now, thanks for spotting this!
