### ISSUE TITLE
Culling not working anymore

### ISSUE THREAD

**Issue by xXxRiddickxXx** [dcs-liberation/dcs_liberation#739]
Culling seems to have no effect since the latest DCS OB patch

Just enable culling, load the mission in the ME and see that culling has no more effect.

**Version information (please complete the following information):**
 - DCS Liberation v2.3.2

**Comment by DanAlbert** [comment]
DCS has no say in culling; the units do not exist at all. Please provide some more information. If this is new behavior in 2.3, make sure you've read the changelog, as it did change.

**Comment by xXxRiddickxXx** [comment]
If I enable "culling of distant units" in the liberation campaign generation it is not working anymore. I was playing with Liberation 2.3.2 before and it was working until the latest DCS Open Beta patch.
![DCS](https://user-images.githubusercontent.com/77078109/103826598-69b91680-5077-11eb-84d3-2a2987263abf.PNG)

**Comment by DanAlbert** [comment]
What do "working" and "not working" mean?

**Comment by xXxRiddickxXx** [comment]
OK, there is only one way this should work. If you activate culling units out of the defined radius shouldn't spawn, right. If you activate culling it has no effect, so all the units still spawn.

**Comment by DanAlbert** [comment]
That's not correct. Culling behavior changed in 2.3. Are you seeing behavior inconsistent with [the manual](https://github.com/Khopa/dcs_liberation/wiki/Performance-Options)?

**Comment by xXxRiddickxXx** [comment]
Yes, the behavior changed with the latest **DCS OB patch**. Before ground units out of the defined zone have been removed. In the case of my campaign the behavior changed after the latest patch (**DCS **Patch**** not Liberation patch!). It's not removing the ground units anymore out of the zone. I will try to start a new Liberation campaign with a fresh save. Maybe this will resolve the issue.

**Comment by walterroach** [comment]
Culling happens in the .miz generation, when a unit is culled, the unit isn't sent to DCS at all; DCS patch and culling inherently cannot be related.

**Comment by DanAlbert** [comment]
Just tested and with a new campaign in 2.3 culling is working exactly as described in the manual. We can help if you can provide more information that shows otherwise.
