### ISSUE TITLE
Feature Request: Ease of Use

### ISSUE THREAD

**Issue by marlboro** [dcs-liberation/dcs_liberation#74]
The following are some fairly minor livability improvements that I think everyone might appreciate...

1. Please add the name text to the Ground Objects shown on the map.  It's really hard to setup a mission when you don't know the ground object names.

2. Please allow aircraft type (F-15, F-18, etc...) to be changed for exiting missions.  For example, an auto generated CAP mission is using F-18's and I want it to use F-15's.  It sucks to have to delete the mission and recreate it all from scratch.

3. Add some way to identify (or visualize) where a mission will be flown.  For example, I can look at the way points for a STRIKE mission to know where it will be flown, but I don't know any way to see where a CAP mission will be flown.  Maybe add Area of Operation (or similar) attribute that could show the Ground Object, Airport, or Front Line over which mission will be flown.  This is really important for auto generated missions.  Showing it on the map would be even better. 😁

Thank you to everyone involved in this project! Great job all around!

**Comment by furiouscaulks** [comment]
As to point 2, you can delete the autogenerated missions and create new ones for each base, assigning whatever planes are available to whatever mission you want, don't forget to give it waypoints etc.

**Comment by marlboro** [comment]
@furiouscaulks, yes that is what I do now.  However, it would be much easier to just change the aircraft type.  As it stands (see point 3) I can't even really recreate certain types of missions (like CAP) because I don't know where they are being flown.

**Comment by Khopa** [comment]
For 1, you can hover the mouse on the ground object icon, it will make a tooltip appear with the name of the objective and the list of building or units to destroy there. 

But I know it's not the most practical right now.

**Comment by DanAlbert** [comment]
Aside from 2 (please file multiple issues when you have multiple issues), these are done I think, and 2 sounds impractical to implement. It's easier than it was in 2.1 anyway since only the flight needs to be replaced, not the whole mission.
