### ISSUE TITLE
Destroyed/Dead Runways Still Registered As Operational

### ISSUE THREAD

**Issue by jeetsukumaran** [dcs-liberation/dcs_liberation#741]
Before filing, please search the issue tracker to see if the issue has already been reported.

**Describe the bug**

Runway is destroyed (= dead event) in mission.

``state.json`` also registers death of airbase.

But Liberation does not -- runway is still operational.

**To Reproduce**

(1) Generate a Liberation mission, with (player) assigned OCA strike. Loadout requires > 6000lb of iron bombs, or probably better at least 1x GBU-31(V)4B. Here I used King Hussein College as target. Not sure if other airbases will work or not work yet.
(2) For testing purposes, I removed all RED and BLUE groups except player a/c.
(3) Deliver ordnance.
(4) Watch ordnance hit.
(5) See "dead" event in briefing.
(6) Exit mission.
(7) Accept results in Liberation.

Note that:

(a) ``state.json`` correctly registers the airfield as destroyed, twice under "killed_ground_units" and twice under "destroyed_ground objects".
(b) Yet Liberation incorrectly does not recognize anything destroyed or lost, and declares the runway still operational.

**Expected behavior**

Liberation should declare runway as inoperational.

**Additional information**

We will usually need more information for debugging. Include as much of the following as you are able:

- DCS Liberation save file (the `.liberation` file you save from the DCS Liberation window). By default these are located in your DCS saved games directory (`%USERPROFILE%/Saved Games/DCS`).
- The generated mission file (the `.miz` file that you load in DCS to play the turn). By default these are located in your missions directory (`%USERPROFILE%/Saved Games/DCS/Missions`).
- A tacview track file, especially when demonstrating an issue with AI behavior. By default these are locaed in your Tacview tracks directory (`%USERPROFILE%/Documents/Tacview`).

**Version information (please complete the following information):**

 - DCS Liberation [e.g. 2.3.1]: e174c1b (build #956)

**Additional context**

Maybe there is a disconnect between the airfield name in DCS vs Liberation's internal database? I recall that a recent patch in DCS may have changed a number of airfield names.

[rwy1.zip](https://github.com/Khopa/dcs_liberation/files/5780479/rwy1.zip)

**Comment by Mustang-25** [comment]
Just to add to the sample size, I also tested (build 970) King Hussein using Type 200As. Got the same result. Dead event but no runway disabled in Liberation. I have successfully disabled runways at Aleppo and Minakh (also on build 970) so it seems to be runway/airbase specific.

**Comment by jeetsukumaran** [comment]
I think Sochi-Adler is also affected by this bug. It shows up as destroyed in the state.json, but Liberation does not recognize it as dead.

[state.zip](https://github.com/Khopa/dcs_liberation/files/5861697/state.zip)

**Comment by Malakhit** [comment]
I believe this should now be fixed, please verify and re-open if needed.

**Comment by Starfire13** [comment]
This issue has not been fully fixed, unfortunately. Check the .json file in the zip file. Incirlik's runway was killed 6 times but Liberation only lists it as damaged, not inoperational.
[OPS Test 3A.zip](https://github.com/Khopa/dcs_liberation/files/5907790/OPS.Test.3A.zip)

**Comment by DanAlbert** [comment]
> damaged, not inoperational.

Those are the same thing in Liberation.

**Comment by Starfire13** [comment]
Ok, so the old "inoperational for 3 turns message" is no more? Gotcha.

**Comment by DanAlbert** [comment]
> Ok, so the old "inoperational for 3 turns message" is no more? Gotcha.

It only says that if they've started to repair the runway. If they aren't actively repairing it there's no timer because it's just broken. Not new behavior FWIW.

**Comment by HighwaymanEd** [comment]
Same result here for Sukhimi runway too, plenty of others destroyed successfully in our Georgian campaign (Kobuleti, Kutaisi, Senaki), but despite 2 successive missions with 16,000 lbs of Mk-83's per mission dropped on the runway (2 x FA-18C x 8 Mk-83's each, all hit down the center, no overlaps) and both DCS and the state file showing the runway was destroyed, it still showed as operational on the next turn.

**Comment by DanAlbert** [comment]
Can't do anything without the save game and the state.json.

**Comment by DanAlbert** [comment]
Though if you're playing 2.3 do note that this bug is marked fixed in 2.4...

**Comment by HILOK** [comment]
**Describe the bug**
problem seems to persist in 2.4.3-2

**To Reproduce**
see OP

**Additional information**
- DCS Liberation save file: attached
- The generated mission file: attached
- A tacview track file: attached
- The state.json file: attached

**Version information:**
 - DCS Liberation 2.4.3-2

**Additional context**
at least 3 hits with Mk84 (JDAM) observed from external weapon view. after mission: runway shows operational in UI.

[liberation_nextturn.zip](https://github.com/Khopa/dcs_liberation/files/6175709/liberation_nextturn.zip)
[invasioniranlite_summer90.zip](https://github.com/Khopa/dcs_liberation/files/6175711/invasioniranlite_summer90.zip)
[Tacview-20210320-125527-DCS-liberation_nextturn.zip.zip](https://github.com/Khopa/dcs_liberation/files/6175712/Tacview-20210320-125527-DCS-liberation_nextturn.zip.zip)
[state.zip](https://github.com/Khopa/dcs_liberation/files/6175713/state.zip)
