### ISSUE TITLE
Liveries for DCS modules only from DCS install, not saved games

### ISSUE THREAD

**Issue by HighwaymanEd** [dcs-liberation/dcs_liberation#743]
.**Describe the bug**
When creating custom liveries for factions, Liberation successfully inserts skins for aircraft such as the AH-1W, MiG-23, IL-78 without any issues from the Saved Games\DCS\Liveries folder. For aircraft that are DCS Modules however, such as the F-16, MiG-19, and so on will not work, even though they can be seen in the Mission Editor. If the skins are placed in the Liveries folder in the DCS Mods folders, they work fine.

**To Reproduce**
1. Add skin to liveries folder in Saved Games\DCS\Liveries
2. Select the skin in DCS Mission Editor to check it’s ok
3. Edit a faction and enter the skin for the aircraft
4. Create mission in liberation with specified aircraft
5. Skin will not be present when flown
6. Add skin to liveries folder in DCS\Mods\aircraft\etc... 
7. create mission in liberation with specified aircraft
8. Skin will now work when flown

**Expected behavior**
Unsure if this is a liberation issue, or something within DCS, but if the skin can be seen in the ME, I’d expect it to be usable in liberation.

**Comment by DanAlbert** [comment]
Duplicate, already fixed.
