### ISSUE TITLE
Captured planes filling airports capacity without a proper way to remove them. 

### ISSUE THREAD

**Issue by Aigle-2** [dcs-liberation/dcs_liberation#746]
Before filing, please search the issue tracker to see if the issue has already been reported.

**Describe the bug**
When capturing airbases, some planes are captured and fill the airport capacity. Because they are not part of your coalition, you can't properly remove them with the resupply menu. I highly suspect those planes are planned reinforcements by the enemy arriving at the same turn you capture the airport.

**To Reproduce**
1.Capture airport
2.Commander will plan flights with captured aircraft

**Expected behavior**
There should be either no captured aircrafts at all/an option to remove them.

**Additional information**

In this savegame, captured 2 mig-29s are located in bandar.
 
We will usually need more information for debugging. Include as much of the following as you are able:

[campagneIranLite2.zip](https://github.com/Khopa/dcs_liberation/files/5783884/campagneIranLite2.zip)

**Version information (please complete the following information):**
 - DCS Liberation 2.3.4

**Comment by DanAlbert** [comment]
Already fixed in 2.4.
