### ISSUE TITLE
Give the user the choice between the new game wizard or preset campaigns.

### ISSUE THREAD

**Issue by Malakhit** [dcs-liberation/dcs_liberation#747]
A user currently has access to a comprehensive list of options for setting up their DCS Liberation campaign. However, this may be a little intimidating for a new user, and they may also wish for something historically authentic but may not know what to pick in order to achieve this. Therefore, I propose that the new game wizard have two branches - one that leads them down the current path, and one that gives them a selection of 5-10 preset campaigns that we've tested and confirmed work well.

To-Do:
- [ ] Decide on what campaign settings are appropriate for a good preset, and store these in a file in a resources subdirectory.
- [ ] Capture an appropriate screenshot and some details for each campaign, for the UI.
- [ ] Branch the new game wizard after the introduction screen, which will have two buttons - one for preset, one for custom.
- [ ] Add a preset page with an appropriate layout to hold the screenshots, which will function as clickable buttons which set the campaign settings according to the preset file.
- [ ] Link the preset page back to the confirmation page at the end.

Feasible campaign ideas:
- Early Second World War campaign on the Channel map - Spitfires/109 only (Shame we don't have an earlier 109!)
- Late Second World War campaign on the Normandy map - full Allies vs Axis.
- Korea campaign in the Caucasus mountains area - USA/North Korea 1955.
- Yom Kippur War in the Syrian Golan Heights area - Syria/Israel 1973, though Israel would need the user to have the A-4 mod if they want to fly anything.
- Afghan War somewhere on the Syrian map - Russia/Insurgents 1980s
- Gulf War somewhere on the Persian Gulf map, maybe in the North? - USA/Iraq 1991
- Something more modern somewhere on the Caucasus map?
- Red Flag on NTTR - Combined Joint Task Force Blue vs US Aggressors

**Comment by DanAlbert** [comment]
It you wanted to fit this into the existing UI, just a "recommended" label on up to date campaigns and adding faction recommendations to the campaign metadata would go a long way.

**Comment by Malakhit** [comment]
> It you wanted to fit this into the existing UI, just a "recommended" label on up to date campaigns and adding faction recommendations to the campaign metadata would go a long way.

I was looking to make it even more simple for the end-user than this - it would also specify the correct map inversion setting, a reasonably well balanced budget level for each faction, and specify the right kind of naval settings.

**Comment by Starfire13** [comment]
I wonder if this FR should be closed, now that we have default factions, preset squadrons, and recommended campaign economy settings.
