### ISSUE TITLE
Feature Request: More Time JTAC message

### ISSUE THREAD

**Issue by furiouscaulks** [dcs-liberation/dcs_liberation#75]
Maybe this could be merged with my request for more JTAC options?  The 25s good for the message, but still not enough time.  At least 60 seconds is needed to get the coords while flying under fire.  It's too much button mashing to get that message up again for those of us who want more of a realistic experience.  The autolase is great for just getting up and bombing stuff, but makes it way too easy, without all the secondary steps required to acquire a target IRL.  Perhaps a slider to adjust message length time in settings?

**Comment by Quax456** [comment]
Or a Field do type it to the own prefered time?
