### ISSUE TITLE
Carrier launched aircraft should have first waypoint ahead of carrier

### ISSUE THREAD

**Issue by jeetsukumaran** [dcs-liberation/dcs_liberation#750]
Before filing, please search the issue tracker to see if this feature has already been requested.

**Is your feature request related to a problem? Please describe.**

At least for US-based carrier operations, there is a specific pattern an aircraft needs to follow when launching, where the aircraft needs to hit the following marks before turning onto its mission course:

(1) Case I: 7nm / 500' / 300 KIAS
(2) Case II: same, followed by climbing to incercept 10nm aaaarc
(3) Case III: 5nm / 1500' / 300 KIAS

**Describe the solution you'd like**

The first waypoint for any carrier-launched aircraft should be 7nm ahead of the carrier @ 500' (i.e., just accommodate Case I for now).

**Additional context**

This is less for traffic control as much as for allowing mission planning TOT's etc. And for aesthetics. So definitely very much a "fluff" thing, and not a priority with much functional significance. Just filing it in case it happens to be some low-hanging fruit for someone or its easy to do as part of a larger more important effort.
![Screenshot from 2021-01-08 21-33-08](https://user-images.githubusercontent.com/26183/104084154-e3790d80-51f9-11eb-81f4-9cd2b07b242a.png)

**Comment by DanAlbert** [comment]
We used to do this and it really screwed with the AI.

**Comment by clutchtomcat** [comment]
Problem is the DCS AI will not respect those speeds/altitudes/waypoints after launch, and will do whacky stuff between launch and referencing the waypoint. Ever since we got the Hornet I've tried to get the AI to play nicely on departures and nothing I've tried has worked.
