### ISSUE TITLE
Add the possibility to not spawn any long range SAM sites at a certain airbase 

### ISSUE THREAD

**Issue by Moguy164** [dcs-liberation/dcs_liberation#751]
Before filing, please search the issue tracker to see if this feature has already been requested.

**Is your feature request related to a problem? Please describe.**
I'm trying to do a campaign that isn't so heavy on the Sa-10 spamming, and i found one that works except liberation spawns random ones weather i like it or not. 

**Describe the solution you'd like**
a way to disable SAMs at an airfield, either by creating a trigger zone where SAMs won't be spotted, or placing a unit at the airbase that clears it from having to spawn SAMs

**Comment by Mustang-25** [comment]
The new campaign generation system allows you to explicitly pick which type of air defense to generate so this shouldn't be an issue as long as the campaign creator didn't go crazy with LORADS. And even if they did, the campaigns can be modified to remove the specific Air Defense generator. I'm going to mark this as feature ready/closed.
