### ISSUE TITLE
ANTI SHIP - B-1B missing target assignment

### ISSUE THREAD

**Issue by rabauke80** [dcs-liberation/dcs_liberation#753]
As you can see in below's list of WPs, there is no target assignment, hence they will fly in and out, doing essentially nothing.

Strike Package:
![image](https://user-images.githubusercontent.com/67376231/104117584-947ac780-5322-11eb-8d9e-0b7662666bb2.png)

Targets:
![image](https://user-images.githubusercontent.com/67376231/104117582-8af15f80-5322-11eb-95fb-aa32cdf87a6d.png)

WP0
![image](https://user-images.githubusercontent.com/67376231/104117612-ca1fb080-5322-11eb-9c52-a5584cc58322.png)

WP1
![image](https://user-images.githubusercontent.com/67376231/104117614-d60b7280-5322-11eb-881e-e150b92eed42.png)

WP2
![image](https://user-images.githubusercontent.com/67376231/104117620-e885ac00-5322-11eb-945f-c4cb8e49e0fb.png)

WP3
![image](https://user-images.githubusercontent.com/67376231/104117622-ede2f680-5322-11eb-9f61-266a45c44b89.png)

WP4
![image](https://user-images.githubusercontent.com/67376231/104117626-f3d8d780-5322-11eb-96de-c3f6116ca5f4.png)

WP5
![image](https://user-images.githubusercontent.com/67376231/104117631-ffc49980-5322-11eb-9373-ade7f0962534.png)

WP6
![image](https://user-images.githubusercontent.com/67376231/104117635-094e0180-5323-11eb-8d46-0462848ee73a.png)

It seems to be assumed, that the fleet is static, by using the following payload:
![image](https://user-images.githubusercontent.com/67376231/104117647-2f73a180-5323-11eb-99d2-e7b3d50b6ab2.png)

Looks like the B-1B is missing the required "Attack Group" advanced waypoint action in comparison to e.g. an F/A-18C Anti Ship Strike.

B-1B:
![image](https://user-images.githubusercontent.com/67376231/104117768-1ddec980-5324-11eb-9b25-38458f2c74ca.png)

F/A-18C:
![image](https://user-images.githubusercontent.com/67376231/104117798-5383b280-5324-11eb-888d-5ee8ccaccbec.png)

**Comment by DanAlbert** [comment]
I don't think B-1s are capable of Anti-Ship in DCS. They don't carry Harpoons, do they?

**Comment by rabauke80** [comment]
can't comment from an IRL perspective since I lack the knowledge. maybe it should be removed from the ANTI SHIP list then? Just saw the same behavior for the F-15E. Seems to me, as long as they have a viable loadout for the task type (DCS Liberation\resources\customized_payloads), you can select it - even tough the ME doesn't provide the required waypoint action.

**Comment by Hornet2041** [comment]
ingame they can carry the AGM-84A version of the Harpoon, so they should be able to do anti-ship

Center station only though

Although they *can* target ships with AGM-86C too so....... idk

**Comment by rabauke80** [comment]
@Hornet2041 when you say ingame, are you talking about a Liberation generated mission which is based on "DCS Liberation\resources\customized_payloads" ? Or just a plain custom ME mission?

In my Liberation campaign which uses Blufor Modern in 2010 on Caucasus, the B-1B can not carry any AGM's other than AGM-154C

/update: I also just tried a custom made mission without Liberation and the B-1B in DCS vanilla (no payload or aircraft mods) is only capable of AGM-154C in regards of AGM's, independently from the station. Furthermore, if you select the task type "Anti Ship" in the ME, it will filter a list of aircraft capable by default - the B-1B is not on that list. --> @DanAlbert which btw. is the same for a liberation_nextturn.miz -> there's no B-1B or F-15E on the list when using the task type filter "Anti-Ship Strike"

![image](https://user-images.githubusercontent.com/67376231/104418024-9937b980-5576-11eb-97e0-5e154c06db24.png)

**Comment by Hornet2041** [comment]
Oops, I derped. I was thinking of the B-52 this whole time. my bad D:

**Comment by Mustang-25** [comment]
B-1 has been removed from the Anti-ship capable task. Closing this bug report.
