### ISSUE TITLE
[QoL]: Resize "Create Flight" window - same as "Mission Package" window

### ISSUE THREAD

**Issue by rabauke80** [dcs-liberation/dcs_liberation#754]
Current:
![image](https://user-images.githubusercontent.com/67376231/104118225-ad39ac00-5327-11eb-9210-44ed68dae19d.png)

Preferred:
![image](https://user-images.githubusercontent.com/67376231/104118238-c9d5e400-5327-11eb-8d0b-66fe63d14b9c.png)

Makes reading strike target names much more convenient, especially when having a long list.

**Comment by Malakhit** [comment]
Okay, I've now implemented this - thanks for suggesting!
