### ISSUE TITLE
use the best available aircraft from the airfield for the mission rather than the first found

### ISSUE THREAD

**Issue by DanAlbert** [dcs-liberation/dcs_liberation#755]
We have a priority list of aircraft for missions now that is used when buying new aircraft, but this doesn't affect aircraft selection in mission planning. In [this save](https://github.com/Khopa/dcs_liberation/files/5793652/no.a10.liberation.txt), the planner continues to use hueys instead of A-10s for CAS because it sees the Hueys first and returns without considering the A-10s.

**Comment by HighwaymanEd** [comment]
Seeing a similar thing in a 1973 Israeli aircraft set with A-4E's being chosen for BARCAP over F-4E's

**Comment by DanAlbert** [comment]
Yes, it affects everything. It's not implemented.
