### ISSUE TITLE
Mission not able to generate when culling enabled. 

### ISSUE THREAD

**Issue by MedievalBunny** [dcs-liberation/dcs_liberation#764]
Attempting to fly the first mission in a new campaign in the PG. 

When culling is enabled, the mission fails to generate when TAKE OFF is clicked. 

The error produced is: AttributeError: 'NoneType' object has no attribute 'position'

When culling is disabled, Liberation is able to generate a mission file. 

Liberation save file and log attached. 

[liberation.log](https://github.com/Khopa/dcs_liberation/files/5813044/liberation.log)

[AlexSteve.zip](https://github.com/Khopa/dcs_liberation/files/5812955/AlexSteve.zip)

**Comment by Malakhit** [comment]
Hello - do you happen to have a log file with the error message in? I do not see the error you've mentioned in the log file included.
I also note that your save game is not compatible with either the latest release version or the latest preview version. Which version of Liberation are you running?

**Comment by MedievalBunny** [comment]
Welp, that's weird. I'm running 2.3.3 

Maybe I should just try reinstalling Liberation. So far I've always updating it by extracting the zip file into the folder for the previous version, maybe that's not the best way to do that ...

![Capture](https://user-images.githubusercontent.com/19675397/104667565-fb3e0f00-569b-11eb-889c-612178016b5f.PNG)

**Comment by DanAlbert** [comment]
Is this still a problem?

**Comment by Mustang-25** [comment]
closing because no response from OP. Can be reopened if bug still persists.
