### ISSUE TITLE
Tankers are flying too fast for the A-10

### ISSUE THREAD

**Issue by dimkzr** [dcs-liberation/dcs_liberation#765]
While we have multiple requests to overhaul tankers in Liberation ( [example 1](https://github.com/Khopa/dcs_liberation/issues/468), [example 2](https://github.com/Khopa/dcs_liberation/issues/288) ), I would like to isolate one particular problem: the tanker's speed.

Currently, all boom tankers in Liberation are flying at their default speed of 330 kts. Which renders them useless for slower aircraft (namely, the A-10C & A-10C II).

Reducing their speed to something in the area of 230 kts should solve this issue without any visible consequences. And this fix is much simpler than adding a separate "slow" tanker or completing the aforementioned overhaul requests 😉

**Comment by clutchtomcat** [comment]
Just for reference, typical tanker speeds for USAF in real life are:

275KIAS for pointy noses.
230KIAS for Hogs.

**Comment by Floydii** [comment]
This is still an issue. The Tanker below is doing about 375kts indicated. it should be about 230-270kts.

And although you can now task them they still fly way too fast. Its also too high for A10s. A refuel high/low task would be good 16000ft/23000ft.

![](https://cdn.discordapp.com/attachments/853177959657766922/860137135104458752/Image_223733.jpg)

**Comment by mikef-phy** [comment]
Yea i couldn't keep up with a loaded f16 without using afterburner.  They are def flying too fast.
