### ISSUE TITLE
[WW2]Cannot shoot down enemy planes

### ISSUE THREAD

**Issue by norsetto** [dcs-liberation/dcs_liberation#768]
**Describe the bug**
For the life of me, I can't shoot down enemy planes unless I manage to put their engine on fire. They end up flying very slowly, their propellers hardly spinning, sometime one wheel down, sometime inverted (as if the pilot was trying to bail out?). No matter how may .50 rounds I put on them, even if I go back to base, rearm and repeat.
AI wingman can indeed down them but I can't.

**Expected behavior**
Enemy fighters should crash to the ground singing the nazi party anthem.

**Additional information**
None that I can think of. Maybe I should record a video?

**Version information (please complete the following information):**
 - DCS Liberation 2.3.5

**Additional context**
Could possibly be an issue with the new damage model? But in Instant Action I can down them pretty easily (tested against Kurst, Dora and Anton)

**Comment by Hornet2041** [comment]
don't see how this is a Liberation bug. seems pretty clear you need to report this on the DCS forums?

**Comment by norsetto** [comment]
> don't see how this is a Liberation bug. seems pretty clear you need to report this on the DCS forums?

As I mentioned in the **Additional context** I've never seen any problem in Instant Action, so I'm not sure that DCS only is at fault. Perhaps some setting Liberation uses?

**Comment by DanAlbert** [comment]
There are no settings I know of that cause the described behavior. Things either take damage or don't. We're definitely not setting them to invulnerable on purpose, and the description doesn't fit that anyway. The fact that your wingmen are getting kills points pretty strongly toward your shots just not being killing shots.

**Comment by Starfire13** [comment]
I play DCS WW2 and can shoot down aircraft just fine in Liberation missions.

**Comment by DanAlbert** [comment]
I think in absence of evidence of a Liberation issue there isn't anything we can do here. @norsetto, if you find an incorrect setting in the generated mission, let us know what and upload the data that was requested by the bug template.
