### ISSUE TITLE
Killed units not shown. "Death of untracked ground unit ....."

### ISSUE THREAD

**Issue by ccuh** [dcs-liberation/dcs_liberation#769]
[Missions.zip](https://github.com/Khopa/dcs_liberation/files/5823566/Missions.zip)

Before filing, please search the issue tracker to see if the issue has already been reported.

**Describe the bug**

We flew multiplayer mission. When the last person leaves the server I stopped the mission. Then came to DCS Liberation window. Clicked on Accept. It showed what we killed for 2 seconds and then crashed. Then I reopened the same .liberation file and loaded the state.json again. None of the killed units were shown. Only 3 base capture events. In fact there was only 1 base capture I think. But the main problem is that killed units were missing.

**To Reproduce**

Load the .liberation file and click takeoff. Then submit the state.json. You will get many errors in debug terminal saying that "death of untracked ground unit .........."

**Expected behavior**

All results shown nicely.

**Additional information**

As additional information, after I got the miz file, I opened it with DCS and resaved. What I modified was mission options, birds civilian traffic etc. Also I changed mission start time from 15:00 to 11:00 for better view.

**Comment by ccuh** [comment]
This bug is still going on. We tried two campaigns. First three turns work fine. On the fourth turn results page we get "death of untracked unit" messeage for all killed units. Nothing registers as dead and it goes to next turn.

**Comment by DanAlbert** [comment]
Are you still doing what you said you were doing in https://github.com/Khopa/dcs_liberation/issues/780?

**Comment by DanAlbert** [comment]
> Load the .liberation file and click takeoff. Then submit the state.json

Yes. I told you this doesn't work in 2.3 and is fixed in 2.4. Stop refiling the same bug. We already fixed it.
