### ISSUE TITLE
Option for stable/beta generation, allow setting paths to both installs

### ISSUE THREAD

**Issue by loneregister** [dcs-liberation/dcs_liberation#77]
Can the program be modified to ask for the installation directories of both Production DCS and Beta DCS?

And then cause the system to wait for a return of mission from either program?

As you can see, trying to eliminate the possibility of issues with the wrong script running.

Thank you,
Kevin

**Comment by DanAlbert** [comment]
Supporting stable isn't something we can afford to do. Note that the entire purpose of 2.5 was to support DCS 2.7. We can't maintain parallel support for two versions of DCS.
