### ISSUE TITLE
Western Georgia: F-16 Fighter Sweep has empty default loadout

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#770]
**Describe the bug**
F-16s as part of a fighter sweep start with a clean loadout (pylons, but no stores.)

**To Reproduce**
1.  Generate the following campaign: Caucasus - Western Georgia, Player: USA 2005, Russia 1990
2.  Generate a strike mission for yourself
3. Add AI F-16 fighter sweep.
4. Create the mission
5. View stores of the AI fighter sweep

**Expected behavior**
Weapons on F-16 Fighter Sweep planes.

**Additional information**

We will usually need more information for debugging. Include as much of the following as you are able:

Campaign and Mission
[WesternGeorgia_EmptyF16_FighterSweep.zip](https://github.com/Khopa/dcs_liberation/files/5823790/WesternGeorgia_EmptyF16_FighterSweep.zip)

**Version information**
 - DCS Liberation 2.3.4

**Comment by Malakhit** [comment]
Hi @SnappyComebacks - would you be able to try this with the latest preview builds? I think I've already fixed this bug but it's not yet in the public release version.

**Comment by SnappyComebacks** [comment]
> 
> 
> Hi @SnappyComebacks - would you be able to try this with the latest preview builds? I think I've already fixed this bug but it's not yet in the public release version.

I haven't looked for preview builds in Liberation before so tell me if I'm looking at the wrong spot.

https://github.com/Khopa/dcs_liberation/actions/runs/485725298

On Build 1045, the F16 Fighter Sweep spawns with 4x AIM-120c, 2x AIM-9(x?), and 3x Fuel tanks.

**Comment by Malakhit** [comment]
Would you be happy to mark this as resolved, in that case?

**Comment by SnappyComebacks** [comment]
Yes, thanks.
