### ISSUE TITLE
Can't plan TARCAP over redfor CP if it is their last CP (#1040)

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#771]
I believe Roach mentioned previously that this was likely due to not being able to determine the proper axis for the TARCAP because there was no other redfor CP available.

**Comment by SnappyComebacks** [comment]
I just encountered this in 2.4.1.  I figured I would add a campaign file in case it's useful, though this can be recreated using cheats.

[Isreal_vs_Syria_GolanHeights.zip](https://github.com/Khopa/dcs_liberation/files/5956106/Isreal_vs_Syria_GolanHeights.zip)

**Comment by Starfire13** [comment]
Btw, this is an issue on the Operation Dyamo scenario because OPFOR only has one airfield. This means there is no way to ever plan a TARCAP over the enemy airfield.
