### ISSUE TITLE
Western Georgia: Units spawned are intersecting / same Lat Long

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#772]
**Describe the bug**
Units in the Western Georgia USA 2005, Russia 1990 campaign are intersecting each other.  On the F10 map you can't see any displacement between the objects.

**To Reproduce**
1.  Create the campaign: Western Georgia USA 2005, Russia 1990
2.  Create a mission
3.  Search along the map for intersecting units.

**Expected behavior**
Units should not be intersecting, or on top of one another.

**Additional information**

[Campaign and Mission](https://github.com/Khopa/dcs_liberation/files/5823944/UnitsSpawnOnEachother.zip)  (Mission was modified, but only by adding weapons to fighter sweep at Kobuleti).

I have track and Tacview if needed.  They are just large (17MB each, so didn't upload.)

**Version information (please complete the following information):**
 - DCS Liberation 2.3.4

**Additional context**
![CommTower](https://user-images.githubusercontent.com/74509817/104798742-69f79700-5786-11eb-9994-2abb420d38e7.png)
![SA_2_SearchRadar](https://user-images.githubusercontent.com/74509817/104798746-6ebc4b00-5786-11eb-9611-2613aff249ee.png)
![Tank1](https://user-images.githubusercontent.com/74509817/104798747-70860e80-5786-11eb-9f0b-5a305e397105.png)
![Tank2](https://user-images.githubusercontent.com/74509817/104798748-72e86880-5786-11eb-9313-dc366a19db3d.png)
![Annotated](https://user-images.githubusercontent.com/74509817/104798750-754ac280-5786-11eb-96d6-cd7012c9150a.png)

**Comment by DanAlbert** [comment]
Your liberation save appears to be broken. It won't load on either develop or 2.3:

```
2021-01-16 12:08:33,450 :: ERROR :: Invalid Save game
Traceback (most recent call last):
  File "C:\Users\dan\src\dcs_liberation\game\persistency.py", line 38, in load_game
    save = pickle.load(f)
_pickle.UnpicklingError: invalid load key, 'n'.
```

**Comment by SnappyComebacks** [comment]
Hi, unsure what happened.  Please try this one: 
[GeorgiaWesternSmall.zip](https://github.com/Khopa/dcs_liberation/files/5833386/GeorgiaWesternSmall.zip)

**Comment by Malakhit** [comment]
I seem to be able to replicate this to some extent, though not to a point where buildings are collapsing.

![Screen_210130_194535](https://user-images.githubusercontent.com/31387062/106366548-87a32f80-6334-11eb-9f71-fd675726a1aa.png)
![Screen_210130_194654](https://user-images.githubusercontent.com/31387062/106366550-8a058980-6334-11eb-977f-6b227026d4f6.png)
![Screen_210130_194738](https://user-images.githubusercontent.com/31387062/106366551-8b36b680-6334-11eb-8a31-6b6dc2104a68.png)
![Screen_210130_194854](https://user-images.githubusercontent.com/31387062/106366555-8d991080-6334-11eb-8a62-8fcf7bb06b70.png)

**Comment by Malakhit** [comment]
It looks like this is a result of this being one of the older types of campaign in use in Liberation. Having tested this extensively, it seems like it's somewhat rare but can be repeated when generating older campaigns. We're currently working on a fix.

**Comment by SnappyComebacks** [comment]
>
> I seem to be able to replicate this to some extent, though not to a point where buildings are collapsing.

The damaged structures are all due to player/AI attacks, not due to unit collision, apologies for the confusion.


> 
> It looks like this is a result of this being one of the older types of campaign in use in Liberation. Having tested this extensively, it seems like it's somewhat rare but can be repeated when generating older campaigns. We're currently working on a fix.

Thanks for investigating.

**Comment by DanAlbert** [comment]
It seems this problem was unique to a fallback behavior that was only commonly used in this campaign. We're removing that fallback behavior and also the campaign. Black Sea (and its "lite" equivalent) are quite similar to Western Georgia, but if you're interested in recreating Western Georgia to use the new system that wouldn't have this bug, follow https://github.com/Khopa/dcs_liberation/wiki/Custom-Campaigns. If you do, please upload it and we'll include it :)

Campaign has already been removed from develop, but we still need to remove the fallback behaviors.

**Comment by DanAlbert** [comment]
> but we still need to remove the fallback behaviors.

But we'll do this in 2.5 so we don't catch everyone off guard at the last minute :)

**Comment by Mustang-25** [comment]
marking this as closed since the campaign itself is deprecated.
