### ISSUE TITLE
Added Weapon Date Restriction Info

### ISSUE THREAD

**Issue by Mustang-25** [dcs-liberation/dcs_liberation#775]
I have done some research to expand the weapon restriction database as well as provide some corrections. Almost all the date info has been sourced from official Air Force/Navy documentation or the manufacturers themselves. As much as possible, I have presented the IOC date rather than initial testing dates but ambiguity within the wording of some sources may exist.

CBU-105 (2000) fallback to CBU-97 (1992)
*The few sources of info I could find on the 97 indicate that it entered production in 1992. While ambiguous, it seemed to imply that it was full rate production so '92 seems like a more accurate date than '95.

CBU-103 (2000) fallback to CBU-87 (1986)

AIM-9M (1982)
*Currently set at 1983 but the Navy training doc I found lists its IOC at '82.

Mavericks:
- AGM-65A (1972)
    *The USAF/USN A model currently does not exist in DCS but the Viggen's RB-75 is a Mav A
- AGM-65D (1986)
- AGM-65E (1990/1991)
    *'90 for the Harrier and '91 for the Hornet.
- AGM-65F (1991)
- AGM-65G (1989)
- AGM-65H/K (2002)
    *Same upgraded guidance package so the dates for both H & K should be the same.
    *the H/K were the hardest to find IOC info on and I could not find any official docs with an accurate date so take this one with 
      a grain of salt. 

Given the lack of Mav A/B's, I recommend using the H model as a placeholder since they are both EO/CCD versions. My suggestions are as follows:
    - K to G to H
    - D to H
    - No fallback for laser Mavs E's or Mav F's

**Comment by Mustang-25** [comment]
I'd also like to request an additional year be added to the current selection: 1995. It allows for the 120B, laser guided PGMs, and CBU-97s but still restricts things like the 120C, 9X, and GPS guided munitions.

**Comment by DanAlbert** [comment]
There's an FR open for just adding a date picker.

**Comment by Mustang-25** [comment]
More Fallback info and dates:

AGM-84K SLAM-ER: 2000 (SLAM-ER isn't released yet but it's worth noting down for the future whenever ED releases it)
AGM-84E SLAM: 1990
AGM-62 ER/DL WALLEYE II: 1972

**Comment by Mustang-25** [comment]
APKWS II: IOC in 2012 for helos, operational for fast jets like Harrier, A-10, and F-16 in 2016.

**Comment by Mustang-25** [comment]
JDAM:
GBU-31: IOC 2001
GBU-32: IOC 2002
GBU-38: IOC 2005 (currently in Liberation it's set at 1998 but from my research, the 38 was the last of the JDAM guidance kits to be developed and IOC'ed. I believe the '98 date is the IOC for the 2000lb JDAM kits on large bombers and 2001 was the integration for fighters.)

GBU-54: IOC in 2012 but the first combat use was in 2008 so I guess it's dev's choice on what date to use

Paveway III:
GBU-24: IOC 1986

Fallback:
GBU-54 to GBU-38 to GBU-12 to Mk-82
GBU-32 to to GBU-16 to Mk-83
GBU-31 (all variants) to GBU-24 to GBU-10 to Mk-84
