### ISSUE TITLE
UI Bug for Date Restriction Feature [Build 1041]

### ISSUE THREAD

**Issue by Mustang-25** [dcs-liberation/dcs_liberation#776]
Turning the date restriction feature on will show empty pylons in the payload screen of the Liberation UI. BUT the units will still be generated in the DCS ME with the appropriate fallback weapons.

@Malakhit this is related to the feature you added that has the custom payload screen start with the default loadout. It seems that the fallback options are not being updated to the payload screen.

**Expected Behavior:**
Activating date restrictions should be reflected in the payload screen by showing the appropriate fallback weapon

**Before Date Restricion:**
![image](https://user-images.githubusercontent.com/72566076/104818897-2f6e1880-57df-11eb-8cad-32060ca42a2a.png)

**After Date Restriction:**
![image](https://user-images.githubusercontent.com/72566076/104818911-46146f80-57df-11eb-8978-060f5bb3caa7.png)

**After Date Restriction in ME:**
![image](https://user-images.githubusercontent.com/72566076/104818955-8b38a180-57df-11eb-863d-3b6aea958e85.png)

**Comment by Malakhit** [comment]
Noted, and it looks like the fix would be to look at how the weapon fallbacks are set up [here](https://github.com/Khopa/dcs_liberation/blob/develop/game/data/weapons.py#L114). This is going to persist as an issue at some level until we get a full list of weapon dates, however, which could be a while away yet.

**Comment by Malakhit** [comment]
I think I've now fixed this in 883f233c09abefa3a57e9c6965d22a5e97340035.
