### ISSUE TITLE
FOBs don't generate Strike Targets

### ISSUE THREAD

**Issue by HighwaymanEd** [dcs-liberation/dcs_liberation#779]
Whilst designing a campaign, and reading through the Wiki, I found that the FOBs that are placed do not generate Objective locations and strike targets like airfields do. The Wiki didn't state explicitly that they would, but it was implied from how the article was written that this should be the case as a FOB is a Control Point, and later it states that Control Points will generate Objective Locations.

I couldn’t find another request for this whilst performing a quick search on my phone, but it would be a useful feature for creating more strike targets for flights to go after where there are not many airfields, such as central Georgia between Tbilisi and Kobuleti. 

Or potentially another type of unit to dictate a mandatory strike target as you can with LR/MR SAMs

**Comment by DanAlbert** [comment]
They do now.
