### ISSUE TITLE
Feature Request: Show version in the About DCS Liberation Dialog Box

### ISSUE THREAD

**Issue by loneregister** [dcs-liberation/dcs_liberation#78]
Makes it easy to check to make sure I am on the right version.

FYI - I installed 2.0.11 twice, and the CMD prompt script still shows 2.0.10.

**Comment by Khopa** [comment]
Hello, 

Yes it looks like i forgot to increment version number for this version.. 
So even if you see 2.0.10 in your 2.0.11 version, it's the good version. 

I'm going to add the version number in the about dialog in the future.

Thanks.

**Comment by Khopa** [comment]
Done in 2.1.0, closing.
