### ISSUE TITLE
DCS Lib 2.3.4 - Carrier / Tarawa missing from Desert War Campaign (Persian Gulf) - Bug or Feature?

### ISSUE THREAD

**Issue by Rook-US** [dcs-liberation/dcs_liberation#781]
Went hunting for issues related to Carrier spawns, but could only find a suggestion for Carriers on all maps, so I'm posting this just in case it's a bug.

**Description**:
Noticed that a new Desert War campaign was not generating the carrier groups. Looks like the carrier spawns in the base desert_war.miz file have been replaced by speed boats. Not sure if this was done to remove carrier spawns from Desert War, or if its a bug.

**Steps to reproduce the behavior**:
1. Create a new Desert Campaign in DCS Lib 2.3.4
2. Enable Supercarrier / Or not(haven't tested this part)
3. Observe no carrier groups on Liberation campaign map, or in the mission editor when loading up next turn.

**Additional info**:
Using other .miz files as reference, swapped in the Stennis and Tarawa on the Speedboat units. After doing this, a new Desert War campaign generated the carrier groups and seems to be adding them to mission files correctly. Ran through the mission in DCS, everything seemed to function normally. TACAN and ICLS worked on the Carrier, and both Carrier and Tarawa were properly named.

**Information for debugging**:

- [DCSLibCarrierIssue.zip](https://github.com/Khopa/dcs_liberation/files/5826877/DCSLibCarrierIssue.zip)
- Above .zip contains original desert_war.miz (included with 2.3.4) and a modified version used for my testing purposes.

**Version information:**
 - DCS Liberation 2.3.4

**Additional context**
Nothing I can think of, but if any additional info or testing is needed, I'm standing by.

**Comment by crashbar** [comment]
I cant get supercarrier or any other carrier to spawn on Desert War.  The Syria: Inherent Resolve when I Check to use supercarrier module only gives me Stennis.

**Comment by DanAlbert** [comment]
Not present on dev.

> when I Check to use supercarrier module only gives me Stennis.

The name of the carrier in the Liberation map means nothing.
