### ISSUE TITLE
Hercules Issues (18JAN-2021)

### ISSUE THREAD

**Issue by Haydz192** [dcs-liberation/dcs_liberation#782]
DCS Liberation Version: v2.4-1052-preview

Quick couple bug reports for the Hercules Plugin/Mod.

The most impactful bug so far is the Hercules_Cargo.lua being outdated and non-functional - this prevents deployments of any cargo or paratroopers from the C-130. Should be a simple fix, all that needs replacing is the Hercules_Cargo.lua file located in \dcs_liberation\resources\plugins\herculescargo . I've sent the replacement file in #bug-report channel in the Discord, but you can also DM me at Haydz#0444 on Discord if you want me to send the file directly that way.

The other (more minor) bug is the radio frequency that the Hercules is tuned to by default in DCS Liberation - it attempts a NATO UHF frequency, however the Hercules mod can only accept frequencies from 118 to 143 MHz AM. This is not a major issue as the Hercules mod currently has non-functioning radios, so players will be unable to send/receive transmissions from the aircraft anyway

**Comment by Malakhit** [comment]
Fixed, thanks!
