### ISSUE TITLE
Cap gets sent away from the conflict

### ISSUE THREAD

**Issue by NagisaShota** [dcs-liberation/dcs_liberation#783]
**Describe the bug**
Caps of both sides get sent away from the fight being useless to the war effort

**To Reproduce**
1. Generate campaign
2. Toggle red tasking in cheat menu and Show all flight paths. 
3. See error

**Expected behavior**
Cap should be At the frontlines or at the objectives not 50nm behind the action

**Version information**
 - DCS Liberation v2.4-1052 preview

**Comment by DanAlbert** [comment]
Can you elaborate? Everything looks fine to me. Please provide the liberation save game like the template asked for.

**Comment by NagisaShota** [comment]
![Screenshot (516)](https://user-images.githubusercontent.com/75280728/104937529-2b442580-59ae-11eb-8869-886b6663be90.png)
![Screenshot (517)](https://user-images.githubusercontent.com/75280728/104937539-2e3f1600-59ae-11eb-92dd-d4ea80367521.png)
[buggedcap.zip](https://github.com/Khopa/dcs_liberation/files/5831227/buggedcap.zip)

As you can see the Cap flies away from the fight and conducts its racetracks outside of interceptions range

**Comment by DanAlbert** [comment]
![image](https://user-images.githubusercontent.com/315852/104962075-849b5d00-598c-11eb-920b-d7f43ba5de71.png)

Looks right to me. BARCAP is defensive. If they went any further they'd be an offensive mission.

**Comment by DanAlbert** [comment]
The carrier BARCAP is avoiding the S-300: 
![image](https://user-images.githubusercontent.com/315852/104962256-e78cf400-598c-11eb-80c5-e12a515cd868.png)
