### ISSUE TITLE
Instead of Individual Vehicles, buy battalions/divisions

### ISSUE THREAD

**Issue by NeelKulkarni6** [dcs-liberation/dcs_liberation#785]
Basically, as the title says. Instead of buying individual tanks/vehicles, you could buy Divisions or Battalions. These would have a set amount of vehicles/infantry in them and can be seen on the map with the [Nato symbols.](https://en.wikipedia.org/wiki/NATO_Joint_Military_Symbology) As they go through combat they may sustain losses and can be replenished for an amount of money. This would make liberation a bit more realistic and by seeing your divisions push back the enemies' divisions on the map you would get a better sense of the war. Perhaps in the future, you could even manually move these divisions around -to an extent, not too far from the frontline- in order to do ambushes and such. 

This would also open up the possibility of a logistics system and the aircraft could strike at enemy convoys/trucks to destroy their supplies and weaken their fighting strength. 

Hopefully not too far outside the realm of what DCS  liberation is trying to do but I think it would make this dynamic campaign much better. Would also make it similar [to BMS (divisions seen on campaign map, obviously dcs probably cant handle this many).](https://i.ytimg.com/vi/SMQyF5nThBo/hqdefault.jpg) 

EDIT: would also work well with [this suggestion](https://github.com/Khopa/dcs_liberation/issues/784)

**Comment by DanAlbert** [comment]
[Duplicate](https://github.com/Khopa/dcs_liberation/issues/439)
