### ISSUE TITLE
Document Ground Force Elimination Type

### ISSUE THREAD

**Issue by clairmont32** [dcs-liberation/dcs_liberation#791]
This document covers nearly all of the ground force's modes but misses the Elimination. Can you write something up describing it's characteristics and/or use cases?

https://github.com/Khopa/dcs_liberation/wiki/Mission-planning

**Comment by Khopa** [comment]
Hello, 

Ground forces stances, including Elimination, are documented here :

https://github.com/Khopa/dcs_liberation/wiki/Frontline-Strategies-Stances
