### ISSUE TITLE
Disable gun run for non-attack aircraft with CAS and OCA/aircaft task on modern era

### ISSUE THREAD

**Issue by foxwxl** [dcs-liberation/dcs_liberation#794]
Before filing, please search the issue tracker to see if this feature has already been requested.

**Is your feature request related to a problem? Please describe.**
Plz disable gun option for aircraft that is not SU25/SU25T/SU25TM/A10A/A10C/A10CII with CAS and OCA/aircaft task on modern era. As we all know, the IFV(like BMP-2/BMP-3) in DCS actually have very powerful&accurate main cannon for any aircraft who dare to dive for a gun run. And modern fighters(like F16/F18/JF17) do not have any armor to hold even one 30mm round, AI dive for gun run usually result a certain death if some IFVs are down there.
As for the OCA/aircraft task, fighter's gun will only damage and set fire on parked A/C, the damaged A/C will just spawn off the battlefield after few mins and THIS DOES NOT COUNT FOR AIRCRAFT KILL. So without powerful guns, stop wasting time on gun parked A/Cs. 

**Describe the solution you'd like**
Disable gun option for aircraft that is not SU25/SU25T/SU25TM/A10A/A10C/A10CII on CAS and OCA/aircaft task on modern era. Let them just RTB when winchester no more suicide gun run.

**Additional context**
No more, thanks.

**Comment by Mustang-25** [comment]
69299d395cff56ae842927e215f1b8b14175937e should solve this. Marking this as feature completed/closed.
