### ISSUE TITLE
BullsEye - Coordinates be added to the kneeboard and or waypoints 

### ISSUE THREAD

**Issue by falcon76** [dcs-liberation/dcs_liberation#796]
i did not see this one on the issues log 

**Is your feature request related to a problem? Please describe.**
the squad was flying a mission and we were unable to find the bullseye coordinate on the briefing or the kneeboard 

**Describe the solution you'd like**
Putting the bullseye coordinate in the briefing and the kneeboard would allow the flights to enter it in waypoints and refer to it

**Additional context**
It would be nice to have in dms

**Comment by DanAlbert** [comment]
Duplicate

**Comment by falcon76** [comment]
Dan,

 

Thanks for looking at this.  Your tool is awesome, I have been flying for the last two days and can’t stop using this tool. So much the wife is wondering what happen to me.  Thank you so much for putting all this work in, it is truly awesome.

 

 

Thanks 

 

Falcon – JTF-191
