### ISSUE TITLE
Ground Units do not move correctly when set on Aggressive

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#797]
**Describe the bug**
Ground Units do not move forward when stance is set on Aggressive. Breakthrough appears to work fine. On the F10 map, they have a single waypoint a short distance behind them, although previously they had 3 waypoints (two forward, and one fallback waypoint).

**To Reproduce**
Set frontline ground units on Aggressive

This bug has appeared consistently on my end since at least #1065 (though it probably first occured a couple builds before that). It is still occuring on #1077.

**Expected behavior**
Ground units should move forward.

**Additional information**

The issue should be easily replicable, but if you'd like an example, grab the zip file I uploaded for https://github.com/Khopa/dcs_liberation/issues/793. The bug definitely exists on that turn.

**Version information (please complete the following information):**
Has occured from #1064 to #1077 but likely first occured a bit before that.

**Comment by Malakhit** [comment]
Investigating this one now, I'm not able to reproduce it immediately on my end.

Here's what I have in Liberation:
![image](https://user-images.githubusercontent.com/31387062/106354585-d3c98200-62ea-11eb-954e-e5bc13a95463.png)

And here is what that translates to in-game. 
![image](https://user-images.githubusercontent.com/31387062/106354558-a5e43d80-62ea-11eb-91c2-7ab24226410e.png)

Fujairah's stance for the Northern front line with Al Minhad is set to Aggressive, and it appears as though the correct set of waypoints is being generated for those units.

I'll keep investigating - I'll try out your save file next.

**Comment by Malakhit** [comment]
Looking at the save file you included over in #793, I'm also unable to recreate. It looks like all 3 waypoints are still being generated - 2 forward, and 1 fallback.
![image](https://user-images.githubusercontent.com/31387062/106354724-d11b5c80-62eb-11eb-967a-108e1fcf82a5.png)

It looks like the morale manager triggers are all set up as I'd expect, too:
![image](https://user-images.githubusercontent.com/31387062/106354800-3a9b6b00-62ec-11eb-8577-e1e97536c03c.png)

Would you be happy to confirm whether this is still happening on your end? If so, what exact steps are you taking to reproduce it?

**Comment by ccuh** [comment]
I also experienced same thing. We did some defense at first 2 turns, then switch to aggressive. Nothing moves for capturing the enemy base from our side...

**Comment by Malakhit** [comment]
I think I've now fixed this one by adding a 1 degree offset to the 2nd waypoint, as there seems to be a DCS bug with waypoints that have 0 heading change. It now seems to work reliably on my end.

@Starfire13 and @ccuh - when you have the free time, would you mind testing this with the latest preview build?
