### ISSUE TITLE
Label flights that have been set to arrive at different airbase

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#798]
**Is your feature request related to a problem? Please describe.**
At the moment, there is no way to tell from the Flights window (after a flight has been planned) if that flight has been set to arrive at a different airbase. There is also no way to edit the arrival airbase after flight creation, meaning you have to delete the entire flight and replan it.

**Describe the solution you'd like**
On the flight list display on the left of the screen, it would be nice if a flight showed, for example "From Damascus to Bassel Al" instead of just "From Damascus" if a flight has been set to arrive at a different arport.

Also, if you edit a flight, there is a section for departure but no arrival info is shown. It would also be nice if there were a way to set the arrival info here, because I often move many aircraft forward to a newly captured base during a turn, and sometimes forget to set the option on a flight or two when I create a whole bunch of flights. This means I have to click on each and every flight to check the flight path on the map, then delete and recreate the flights that I messed up.

Everything I suggested above could also be expanded to show/edit divert info as well..

**Comment by DanAlbert** [comment]
Split into two bugs. In the future please file two reports when you have two FRs. Github only lets us handle a whole bug at a time.
