### ISSUE TITLE
Have a slider for Aircraft Tasked per turn

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#799]
**Is your feature request related to a problem? Please describe.**
AI simply tasks every plane they have available in a turn, which can lead to performance issues. Having a slider for maximum number of aircraft the AI can task for a turn (32, 48, 64, 80, 96, 112, 128, 144, 160, Unlimited) means performance can stay predictable. It also means you can set the income slider higher for the AI and let them stock up aircraft that they can use on subsequent turns.

**Comment by clutchtomcat** [comment]
This would also be useful for players, since we wouldn't have to then delete flights/packages to free up aircraft for our own use.

**Comment by Hornet2041** [comment]
seems like this was implemented via #832 ? mostly anyway

**Comment by DanAlbert** [comment]
DCS multi threading made this irrelevant
