### ISSUE TITLE
Bug: AI Helicopters missing payloads

### ISSUE THREAD

**Issue by NBNoot** [dcs-liberation/dcs_liberation#80]
I have noticed that certain unflyable helicopters (AH-64A, AH-64D, Mi-24V, Mi-28N) are missing a loadout of missiles/rockets during missions. I can happily add a loadout to my own flights through the mission planner, but obviously the enemy attack helicopters cannot, and that makes them a little less threatening than they should be haha.

Looking through the customized_payloads folder, I notice those helicopters haven't got a loadout defined.

My thanks to you for all your dedication and hard work for this amazing addition to DCS!

**Comment by DanAlbert** [comment]
Is this still an issue?

**Comment by DanAlbert** [comment]
Guess not.
