### ISSUE TITLE
More Strike Targets

### ISSUE THREAD

**Issue by Ryanwtod** [dcs-liberation/dcs_liberation#800]
Is it possible to generate more targets for strike missions at the beginning of a campaign? I prefer strike missions myself and find myself running out of targets. I had two separate thoughts. #1 a slider at the beginning of the campaign to choose the number or density of targets such as the factories, bunkers, FARPs, fuel depots etc. #2 Maybe new targets could be added along the course of a campaign to simulate the enemy bringing new facilities online.

**Comment by HighwaymanEd** [comment]
I've suggested something similar [here #779 ](https://github.com/Khopa/dcs_liberation/issues/779) that would be an easy way to implement them, but I like the idea of the slider too as it may help people with lower systems prevent too many objects from being spawned and slowing everything down.

**Comment by DanAlbert** [comment]
Random generation is going away, so there's nothing for the slider to do. This is up to the campaign designer.
