### ISSUE TITLE
AI CAP & Fighter sweep spawning with clean loadouts

### ISSUE THREAD

**Issue by jake-lewis** [dcs-liberation/dcs_liberation#801]
**Describe the bug**
AI Flights spawning with no loadout, when default loadouts for CAP & Fighter Sweep should be used

**To Reproduce**
Load liberation campaign attached.
Inspect loadout for fighter sweep flights on carrier & CAP at Palmyra

**Expected behavior**
Task specific loadouts should be present on spawn, but jets are clean

**Additional information**
Files in zip:
[Syrian Civil War.zip](https://github.com/Khopa/dcs_liberation/files/5882821/Syrian.Civil.War.zip)

**Version information:**
 - DCS Liberation 2.3.4:
 - DCS Version - DCS 2.5.6.60645 Open Beta

**Comment by Malakhit** [comment]
Hi @jsjlewis96 - I believe this is already fixed in the upcoming 2.4 release. Would you be happy to test with the preview build?

**Comment by jake-lewis** [comment]
@Malakhit  Absolutely :)

**Comment by Ryanwtod** [comment]
I noticed this as well, a quick work around until 2.4 is released is creating a custom loadout for those flights.

**Comment by Mustang-25** [comment]
Bug does not seem to be present on the latest builds. Issue can be reopened if the problem persists.
