### ISSUE TITLE
Add E-2C as AWACS into Liberation DB

### ISSUE THREAD

**Issue by ataribaby42** [dcs-liberation/dcs_liberation#802]
Please add E-2C as AWACS into Liberation DB. I would like to use it as israeli Awacs. 

Currently only E-3A is known to Liberation. 

Thank you.

**Comment by DanAlbert** [comment]
https://github.com/Khopa/dcs_liberation/issues/630

**Comment by ataribaby42** [comment]
I missed already existed request, sorry. Thanks for adding it ;)
