### ISSUE TITLE
USA 2005 with c-130 Faction doesn't mention the mod in the required mods note below.

### ISSUE THREAD

**Issue by NeelKulkarni6** [dcs-liberation/dcs_liberation#803]
![image](https://user-images.githubusercontent.com/77650484/106233084-88a85580-61aa-11eb-97f8-e60f53cae20a.png)

Picture of what i mean, it talks about the c-130 mod without actually having the mod linked in the required mods section

**Comment by Malakhit** [comment]
Fixed, thanks! 🙂
