### ISSUE TITLE
dedicated package frequency & AI comms

### ISSUE THREAD

**Issue by HILOK** [dcs-liberation/dcs_liberation#804]
any chance we could get a dedicated package frequency where own package AI sort of transmits what they are doing?

just saw this clip https://youtu.be/pPCDfGQtpoc about a really cool mission creation tool called briefing room, which can be found here https://github.com/akaAgar/briefing-room-for-dcs. 

and what impressed me most was the fact that AI CAP and SEAD flights from within the client's package would transmit text & voice messages about what they are up to. this would dramatically increase the clients' SA during missions in dcs_liberation.
the devs seem to use their own script (not DCS native radio comms) for this. maybe there is a chance you guys could team up or borrow their code?

**Comment by DanAlbert** [comment]
https://github.com/Khopa/dcs_liberation/issues/331
