### ISSUE TITLE
Invalid face handle error

### ISSUE THREAD

**Issue by AvatarBoB** [dcs-liberation/dcs_liberation#805]
**Describe the bug**
When trying to press the take off button nothing happens on the main Window, but the console shows a "OSError: invalid face handle" error. Pressing the take off button a second time crashes the application

This issue happens most of the time for me, but not every time. In about 1 in 20 cases it procedes normally to the mission window

**To Reproduce**
1. Load Mission
2. Press the green take off button
3. Nothing happen on the main window
4. Checking the console it shows "OSError: invalid face handle"
5. pressing the take off button again crashes the application
**Expected behavior**
Pressing the take off button should lead normally to the next window

**Version information (please complete the following information):**
 - DCS Liberation v2.3.6

screenshot of console (Error doesn't appear in logs)
![grafik](https://user-images.githubusercontent.com/78223707/106300805-33764d80-6257-11eb-9660-b0e93b26a5a0.png)

Liberation save file:
https://drive.google.com/file/d/1hsnlU0T_f5i253-AUNwGplToxmHHLexi/view?usp=sharing

**Comment by shomke** [comment]
Same issue reported in error [#531 ](https://github.com/Khopa/dcs_liberation/issues/531)
