### ISSUE TITLE
Bug: AI flights culled when new base captured

### ISSUE THREAD

**Issue by NBNoot** [dcs-liberation/dcs_liberation#81]
Regarding the closed issue #19 I believe I have run into a slight issue regarding this and I hope I'm able to explain it well enough:

In the current release if I capture a new base 80km away from my previous base, it becomes the new "frontline base" as you put it, but I obviously cannot populate this new base with new aircraft until the next turn. So if my culling distance is 79km or less for example, the flights from the previous base are culled and no friendly flights will spawn but my own.

I figure the center point for the culling is on this frontline base? If so, would it perhaps be better to set it only if there are friendly flights available?

**Comment by BigBoss329** [comment]
I wonder, if it would be possible to set the culling bubble's center point, on the player's (client's) location instead of the frontline?

**Comment by DanAlbert** [comment]
@Khopa I think you fixed this and the culling zone now includes attached control points?

**Comment by DanAlbert** [comment]
Obsolete with 2.3. Flights will not be culled any more.
