### ISSUE TITLE
Desert War Aircraft Carrier/LHA

### ISSUE THREAD

**Issue by Ryanwtod** [dcs-liberation/dcs_liberation#811]
The Desert War map used to have a carrier and LHA, they were removed. Can they be put back please?

**Comment by Starfire13** [comment]
I am still seeing the carrier and LHA in the Desert War campaign.

**Comment by Khopa** [comment]
It depends on your faction. Some faction do not have access to an aircraft carrier or a LHA.
Which version of Liberation were you running, and which faction did you select ?

**Comment by Ryanwtod** [comment]
2.34 BluFor Modern

**Comment by Ryanwtod** [comment]
I just tried it with the US 2005 on 2.3.4 and same results

**Comment by DanAlbert** [comment]
Works in 2.4.
