### ISSUE TITLE
Set F-14 DEAD flights to ingress at 40,000 feet

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#814]
F-14 DEAD flights using TALDs need a higher altitude than normal to be effective as they are launched at 50 miles. Otherwise, they are too low by the time they are within the target SAM's kill range. At the moment, I have to manually set waypoint altitude so they launch at 40,000 feet instead of 20,000 feet. Having this set as as the default would be nice.

**Comment by clutchtomcat** [comment]
Additionally, tasking this as SEAD would be much better. TALD's are decoys, and thus suppression (SEAD) not destruction (DEAD). The tasking for aircraft is quite odd, honestly.

**Comment by DanAlbert** [comment]
https://github.com/Khopa/dcs_liberation/issues/270
