### ISSUE TITLE
WW2 Units empty payloads

### ISSUE THREAD

**Issue by clutchtomcat** [dcs-liberation/dcs_liberation#816]
So far I have noticed the following units/roles have empty default payloads:

B-17G: Runway Attack
Bf109 K-4: CAS

Will update with more as I find them.

**Comment by Malakhit** [comment]
Hi @clutchtomcat - which build are you running?

**Comment by clutchtomcat** [comment]
Currently v2.3.4. I don't recall having this in one of the early v2 builds but I can't remember which one. I skipped a couple builds somewhere in the middle.

**Comment by Mustang-25** [comment]
Default payloads for above mentioned aircraft/taskings are working as intended in 2.6+, bug can be closed.
