### ISSUE TITLE
Liveries override appears dependent on role

### ISSUE THREAD

**Issue by clutchtomcat** [dcs-liberation/dcs_liberation#817]
Example:

P-47D-40 CAS takes the proper livery from the liveries override function, however P-47D-40 CAP does not take the proper livery.
P-51D CAP also fails to take the proper livery, though I suspect CAS will work. Spitfires, on the otherhand, take proper liveries regardless of roles. Somewhat inconsistent bug.

**Comment by DanAlbert** [comment]
Liveries were reworked in 3.0 and are now attached to squadrons.
