### ISSUE TITLE
B-17's don't respect altered waypoint altitudes

### ISSUE THREAD

**Issue by clutchtomcat** [dcs-liberation/dcs_liberation#818]
B-17 flightplan defaults to about 9,000ft. In the Mission Editor I changed all waypoints to 20,000ft for a more realistic experience, and also changed the bombing action to "above 20,000ft" because otherwise the AI try dive-bombing and blow themselves up with their own bombs.

Upon flying the misison, B-17s flew their waypoints at the default 9,000ft, and then circled over the target area trying to gain 20,000ft before dropping their payload.

**Comment by DanAlbert** [comment]
If you changed it in the ME it's by definition not a Liberation bug. DCS AI doesn't fly well.

**Comment by clutchtomcat** [comment]
I've never had AI refuse to fly their assigned altitudes outside of Liberation.

**Comment by DanAlbert** [comment]
I have, and you just did. It's quite easy to create flight plans in the ME that the AI can't do, especially with heavier aircraft, or aircraft without afterburners.

Regardless, we didn't create this flight plan, so we can't fix it.

**Comment by clutchtomcat** [comment]
I specifically said it never happens OUTSIDE OF LIBERATION. Hence I did NOT "just did."

CAPS since no one can read. Getting tired of the terse, "my word is god" way these bug reports are being handled. If it's a DCS issue, then direct me to an acknowledged bug report on the ED forums, because I do not see one. Until said bug report is filed with ED, I maintain that this is a Liberation issue as, I say again, it does not happen outside of Liberation.

All I'm trying to do here is create a realistic campaign because those who are scripting these flight plans don't understand how reality works.

**Comment by DanAlbert** [comment]
There are reports on the forum that aircraft are sensitive to flight plans that don't give them adequate time or space to turn, climb, etc. IIRC ED's stance is that mission creators should just not make that flight plan. Liberation did not create the flight plan. You're welcome to search the forums, but I'm not going to do it for you.

> All I'm trying to do here is create a realistic campaign because those who are scripting these flight plans don't understand how reality works.

Don't be a jerk. Liberation is a work in progress maintained by volunteers. There are open requests to adjust flight planning behavior based on mission profile that we haven't had time to fix yet. These aren't trivial fixes. If they were, they'd be done already. If this is important to you we're happy to review PRs that address it.
