### ISSUE TITLE
AV8B Harrier - Default SEAD loadout wants to use AGM-65G that are not available anymore

### ISSUE THREAD

**Issue by skeletonwburg** [dcs-liberation/dcs_liberation#821]
**Describe the bug**
The default loadouts for the harrier that ship with Liberation tries to fit the Maverick G for SEAD. The G variant is not available since the latest OB patch for DCS. It should use the F for example instead.

**To Reproduce**
Create DEAD or SEAD flight with the Harrier.

**Expected behavior**
Sidearms, DECM Pod and some empty stations where the Mavs should be.

**Version information (please complete the following information):**
 - Develop Build 1117

I added my customized loadout file. It is the original version with a changed SEAD loadout that consists of 2 Sidearms, 4MAV-F, DECM Pod. It's the same loadout for SEAD/DEAD that Starfire uploaded in his customized loadout files.
[AV8BNA_loadout.zip](https://github.com/Khopa/dcs_liberation/files/5899907/AV8BNA_loadout.zip)

**Comment by Khopa** [comment]
Thanks, should be fixed in build 1119 (https://github.com/Khopa/dcs_liberation/actions/runs/525565275)
