### ISSUE TITLE
Ground units purchased during a turn where a base is captured don't get moved to the new frontline

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#828]
**Describe the bug**
If you have pending ground unit purchases and capture an enemy base on that turn, the newly purchased ground units do not move across to the control point with the new frontline along with the other ground units at the start of the next turn.

#1127

**Comment by SnappyComebacks** [comment]
It's possible that [this](https://github.com/Khopa/dcs_liberation/issues/477) is the same bug?

**Comment by DanAlbert** [comment]
No, the behavior that's broken here (attempting to refund unfulfilled purchases) didn't exist in November. They're definitely related, but I closed the old one since that particular issue was fixed and am leaving this one open to track the specific broken case.
