### ISSUE TITLE
Option to disable civilian road traffic

### ISSUE THREAD

**Issue by ccuh** [dcs-liberation/dcs_liberation#834]
Before filing, please search the issue tracker to see if this feature has already been requested.

**Is your feature request related to a problem? Please describe.**
The civilian road traffic is FPS killler. It would be very nice to add option to disable it in campaign settings.

**Comment by Starfire13** [comment]
You can disable this in DCS itself. It's in the video settings. There's really no good reason to leave it on anyway.

**Comment by DanAlbert** [comment]
As long as the Liberation mission isn't overriding the user's global settings I think the DCS settings are the way to go here. (lmk if Liberation _is_ overriding your settings, but that seems unlikely)
