### ISSUE TITLE
Auto Purchase of Sea based planes are placed on airfields and not carriers

### ISSUE THREAD

**Issue by xxmozartxx** [dcs-liberation/dcs_liberation#839]
as the title states:
Auto purchase of Sea based planes (f18's, f14's, AV8B's) are placed on airfields and not carriers.
the harrier i can understand and not so much of a concern.

**Comment by DanAlbert** [comment]
They also get purchased on carriers. It doesn't happen on the first turn because of https://github.com/Khopa/dcs_liberation/issues/674.

This is the intended behavior. It buys aircraft at the airfield that needs them.
