### ISSUE TITLE
BUG: Enemy forces explode on tarmac

### ISSUE THREAD

**Issue by loneregister** [dcs-liberation/dcs_liberation#84]
Possible that the units are too close together? TacView ACMI attached.
Navigate to roughly 23:37:03, and look at the units around Shiraz.  Specifically 
F-14B unit|34|35|19|F-14B|Pilot #1 and the group around him.

[Tacview-20200820-181410-DCS-liberation_nextturn.zip.zip](https://github.com/Khopa/dcs_liberation/files/5106734/Tacview-20200820-181410-DCS-liberation_nextturn.zip.zip)

**Comment by Khopa** [comment]
Yes, they look quite close indeed... 

![image](https://user-images.githubusercontent.com/2546901/90880198-5ea36980-e3a8-11ea-982f-cba747d1d634.png)

If filled the Shiraz airbase with F-14 in the mission editor, but it doesn't look like there is any incompatibility with parking slots though, so not sure what happened...

Do you still have the miz file by any chance ?

**Comment by rabauke80** [comment]
I've seen a lot of Mig23 2-ships killing each other by collisions in the "mission results" screen. Didn't check at what stage of the mission they collided, but might be the same/similar issue.

**Comment by loneregister** [comment]
WOOPS - just saw that you asked for the miz file.  Where can I find that?

**Comment by DanAlbert** [comment]
In your DCS missions directory. It's the file you loaded to start the mission in DCS.

But I think this is probably a map or aircraft bug that we can't fix. I assume this hasn't happened again since no one else has reported. If you see it again upload the miz and we'll reopen.
