### ISSUE TITLE
Some Factions Cause Culling to break

### ISSUE THREAD

**Issue by RoleplayingPleb** [dcs-liberation/dcs_liberation#850]
Some Factions Cause Culling to break, causing all airbases to act as culling reference points. This means that a huge amount of ground units are spawned on large maps. Only some factions cause this problem, i included my testing.

**To Reproduce**
1. Create new campaign using Syria 2011 or Iran 2015 or Germany 1944 as the enemy team
2. Turn on Culling
3. Notice Culling Zones cover all hostile airbases, not just ones near the frontlines

**Expected behavior**
If you create a campaign with Russia 1990 as the enemy it doesn't seem to have this issue

**Additional information**

The issue doesn't seem to arise when you play as the affected factions, only when you play against them. Map / campaign selection doesn't seem to affect the issue.

**Version information (please complete the following information):**
 - DCS Liberation [e.g. 2.4.0]:

**Additional context**
![image](https://user-images.githubusercontent.com/74385702/107115379-65735980-68c0-11eb-9558-504822b06408.png)
![image](https://user-images.githubusercontent.com/74385702/107115396-83d95500-68c0-11eb-8f2f-669c6014deba.png)

**Comment by DanAlbert** [comment]
Attach the save game? That's sort of the most important piece of information here.

**Comment by RoleplayingPleb** [comment]
here's one
[bug report.lib.zip](https://github.com/Khopa/dcs_liberation/files/5936692/bug.report.lib.zip)

**Comment by Malakhit** [comment]
This might be related to the tweaks around missile site culling.

**Comment by DanAlbert** [comment]
Ah, do missile sites generate a non-culling zone? I think we should just exclude them from culling rather than creating a non-culling zone for them.

**Comment by Malakhit** [comment]
They get added to the list of non-culled points of interest like carriers do. However, it looks like it was the location of the control point that owned that missile site theatergroundobject that was being added, not the missile site location.

I've now changed this to use the missile site's point, and added a smaller culling point object (that only covers 2.5km) to handle these:
![image](https://user-images.githubusercontent.com/31387062/107130802-167df200-68c9-11eb-99c2-eea6bf6936a6.png)
![image](https://user-images.githubusercontent.com/31387062/107130811-20075a00-68c9-11eb-986e-d35c9ef815c5.png)

**Comment by Malakhit** [comment]
Fixed in 2.4.1.
