### ISSUE TITLE
Ground units move to wrong airport on "dessert war"

### ISSUE THREAD

**Issue by zelosos** [dcs-liberation/dcs_liberation#851]
**Describe the bug**
Friendly ground units move to Sir Abu Nuayr instead of Al Ain in the dessert war campaing on the golf map.

**To Reproduce**
1. Campaign on dessert war
2. Frontline is before capture of Al Ain with blue force
3. Units are on "breakthrough" (also with "agressive")
4. generate mission

**Expected behavior**
Units should move towards Al Ain and capture it.

**Additional information**
- zip with files will follow

**Version information (please complete the following information):**
- DCS Liberation version: 2.3.1

**Comment by zelosos** [comment]
For the files download: https://cdn.discordapp.com/attachments/595706079459934208/807638185794207764/BugFilesDessertWar.zip

**Comment by Starfire13** [comment]
I would suggest moving to the latest release build. 2.3.1 is almost 2 months old.

**Comment by zelosos** [comment]
Was it fixed in the last 2 months?

**Comment by DanAlbert** [comment]
We don't know. A lot changed in the last few months and we've never heard this reported before. It's possible that one of the other changes in 2.4 fixed this.

**Comment by zelosos** [comment]
ok I will have a look. I will close the issue for now
