### ISSUE TITLE
Campaign Money is Not rounded in v2.4 like the changelog says it was.

### ISSUE THREAD

**Issue by NeelKulkarni6** [dcs-liberation/dcs_liberation#852]
Changelog for 2.4 said the budget was rounded to I think 2 decimals. I created a _new_ Syria campaign and my budget wasn't rounded. I clicked the next turn a couple of times too and it wasn't rounding. Multiplier was .8

![image](https://user-images.githubusercontent.com/77650484/107127884-100e5c80-686e-11eb-94df-6903c583b494.png)

**Comment by Malakhit** [comment]
Huh, that's weird. I couldn't manage to get the budget to do this, only the income - hence the changelog only mentioning the income display. Will add to the 2.4.1 patch.

**Comment by Malakhit** [comment]
Pushed fix.
