### ISSUE TITLE
Adjust FARP to add helos to site instead of just have it as only a vehicle site

### ISSUE THREAD

**Issue by techdr1ve** [dcs-liberation/dcs_liberation#856]
Could we change FARP to a 'circle' place where Helos can be spawned like the air base / aircraft carrier instead of ONLY vehicles? 

Extra: Add option to add harrier to the FARP as well :)

**Comment by DanAlbert** [comment]
Please search for existing issues: https://github.com/Khopa/dcs_liberation/issues/186
