### ISSUE TITLE
PLACEMENT: Ships Placed on Land in PG

### ISSUE THREAD

**Issue by MedievalBunny** [dcs-liberation/dcs_liberation#86]
Naval units placed off the Dubai coast can be placed on islands. They are located here in the mission planner and cannot be moved, then spawn at that location in game. 
![Screen_200819_003600](https://user-images.githubusercontent.com/19675397/90859926-b8774580-e34e-11ea-9c01-4cf757415486.png)
![Screen_200819_023953](https://user-images.githubusercontent.com/19675397/90859933-bad99f80-e34e-11ea-9a78-8991bfbffe92.png)

**Comment by DanAlbert** [comment]
Can't happen with the new campaign structure. Not all have migrated, but I think we've also fixed this issue already.
