### ISSUE TITLE
Errerno 13, cannot use 'Take Off' button, Kneeboard related?

### ISSUE THREAD

**Issue by chanosiaan** [dcs-liberation/dcs_liberation#866]
Hi there, I've had a quick look to see if this has already been solved but cannot see a solution. Apologies if it has been already.

After creating a mission for SP use and hitting 'Take Off', nothing happens and I get the error below.

My saved game directory is: C:/Users/Chano/Saved Games/DCS
My installation directory is: K:/SteamLibrary/steamapps/common/DCSWorld 

In the saved games directory I have a subfolder named 'Missions' as directed by another thread. Didn't seem to change anything.

Might be related to kneeboard generation? I have no idea, I'm a total noob at this.

I've tried it on different maps, with different aircraft/factions/missions to no avail...

1. Create mission with 1 client slot.
2. Click Take Off
3. Nothing happens...
4. Gets error:
5. Traceback (most recent call last):
  File "qt_ui\widgets\QTopPanel.py", line 243, in launch_mission
  File "game\game.py", line 213, in initiate_event
  File "game\event\event.py", line 58, in generate
  File "game\operation\operation.py", line 346, in generate
  File "game\operation\operation.py", line 191, in notify_info_generators
  File "gen\kneeboard.py", line 356, in generate
  File "gen\kneeboard.py", line 292, in write
  File "gen\kneeboard.py", line 95, in write
  File "lib\site-packages\PIL\Image.py", line 2155, in save
PermissionError: [Errno 13] Permission denied: 'kneeboards\\Su-27\\page00.png'

- DCS Liberation 2.4.1

Any help would be appreciated, thanks!

**Comment by DanAlbert** [comment]
Either Liberation doesn't have permission to write to the directory you've installed it to, or some other program is preventing it from writing that file.

**Comment by chanosiaan** [comment]
You were totally right, it was an anti-virus software that was blocking it. I've made an exception for it and now it runs fine.

Thanks very much!

**Comment by fushti** [comment]
Oh shit. Thanks so much. I had the same thing with AVG but it was set to silent so I didn't get the notification. Spent a day changing permissions before I found this. Thanks again.
