### ISSUE TITLE
decouple loadouts from DCS task type

### ISSUE THREAD

**Issue by Jara4** [dcs-liberation/dcs_liberation#867]
AI flight performing OCA/Airfield strike uses cluster bombs for runway bombardment . Create, pls, proper loadout for OCA/Airfield strike with BETAB500Shp bombload. TY

**Comment by Jara4** [comment]
Just found article how to create custom loadout.

**Comment by DanAlbert** [comment]
Repurposing this one to cover the broader problem with loadouts that we currently have.

We can't actually create loadouts for each Liberation mission type, only the underlying DCS group type. This is why things like BAI _must_ be the same loadout as CAS. We need to start using the Liberation mission type on our end. That part's easy, but doing so is going to break every loadout configuration and that's going to create a ton of work.
