### ISSUE TITLE
AI plans blufor AEW&C above redfor carrier group

### ISSUE THREAD

**Issue by skeletonwburg** [dcs-liberation/dcs_liberation#868]
**Describe the bug**
The AI planning for AEW&C seems to be wrong. It plans the flight for the blufor mission above the redfor carrier. 

**To Reproduce**
1. Choose blufor faction with AWACS plane and redfor faction with a carrier.
2. Buy E-2C
3. Pass Turn

**Expected behavior**
The E-2C flight will be planned to orbit above the enemy carrier group.

**Additional information**

We will usually need more information for debugging. Include as much of the following as you are able:

Liberation Save File: 
[dawaiDawai.zip](https://github.com/Khopa/dcs_liberation/files/5955002/dawaiDawai.zip)

**Version information (please complete the following information):**
 Dev-Build 1172

**Comment by SnappyComebacks** [comment]
I didn't download your mission or anything, but wouldn't the expected behavior be Blue AWACS flight is planned near the Blue bases, and a RED AWACS planned near RED bases?

**Comment by siKruger** [comment]
Most likely caused by 

gen/flights/ai_flight_planner.py

Line 444 (nice number btw)
>https://github.com/Khopa/dcs_liberation/blob/8e51b7fc1d745cec392895716c30d4ddcf7beb78/gen/flights/ai_flight_planner.py#L444


should be
>  if c.is_carrier & c.is_friendly(self.is_player):

**Comment by skeletonwburg** [comment]
> I didn't download your mission or anything, but wouldn't the expected behavior be Blue AWACS flight is planned near the Blue bases, and a RED AWACS planned near RED bases?

Sorry, the title was misleading. I edited it for better understanding. The description explains the problem.

**Comment by siKruger** [comment]
> https://github.com/Khopa/dcs_liberation/pull/872
