### ISSUE TITLE
F16C Block 50 Missing for USA 1990 Faction

### ISSUE THREAD

**Issue by AustinLeath** [dcs-liberation/dcs_liberation#87]
The F16C block 50 was released for service at some point between 1990 and 1991. That being said shouldn't it be added to the USA 1990 and above factions seeing as it (not specifically the block 50 version, but others) are still seeing use today?

![image](https://user-images.githubusercontent.com/32113014/90861805-fd50ab80-e351-11ea-82b3-eba8d085d2dd.png)
![image](https://user-images.githubusercontent.com/32113014/90861847-1194a880-e352-11ea-8dc5-3c14e5680fdf.png)

**Comment by Khopa** [comment]
I agree it could be put in USA 1990.
It will be in USA 1990 in 2.1.1

**Comment by AustinLeath** [comment]
Excellent, I will definitely be taking advantage of this addition.

**Comment by Khopa** [comment]
Fixed in 2.1.1 and 2.1.2. Closing this issue.
