### ISSUE TITLE
Night mission is generated, when in options disabled

### ISSUE THREAD

**Issue by zelosos** [dcs-liberation/dcs_liberation#877]
**The bug:**
Night mission is generated, when night disable option is set.

**To Reproduce:**
1. start new campaign
2. play missions, until the first night mission will be the next one
3. disable night mission in options
4. generate next mission (it will be a night one in DCS)

**Expected behavior:**
The night mission should be skipted and the next mission should be on the next day.

**Version information:**
 - DCS Liberation 2.4.1:

**Comment by DanAlbert** [comment]
Please search for duplicates before filing. https://github.com/Khopa/dcs_liberation/issues/357

**Comment by zelosos** [comment]
Thats not what I have meant. The mission time was not at 07:00 pm or so. It was 03:00 am.
So this is not the same issue.

**Comment by DanAlbert** [comment]
That's pretty important info. Thanks.

**Comment by DanAlbert** [comment]
Although do upload the save game that has the problem so we can investigate.

**Comment by zelosos** [comment]
[NightTest.zip](https://github.com/Khopa/dcs_liberation/files/5971816/NightTest.zip)

This is liberation file. Generated like discripted in the beginning.
Notice the night disable is only clicked on this turn. Still it will generate a night mission if takoff is pressed now.

**Comment by zelosos** [comment]
I had to recreate it. The original mission where i notice it, is allready overridden. But no problem since you can recreate it 100%

**Comment by zelosos** [comment]
Notice also: the next following night will be skipt like intended.

**Comment by DanAlbert** [comment]
> Notice the night disable is only clicked on this turn. Still it will generate a night mission if takoff is pressed now.

Expected behavior then. The mission time is set when the turn starts, so that option can only affect later turns.
