### ISSUE TITLE
Carrier Recovery Tanker

### ISSUE THREAD

**Issue by DevastatorCM** [dcs-liberation/dcs_liberation#879]
Hi Guys,
is it possible to code an S3 to take off like 15 minutes later from the carrier(s) which will stay at 10.000 ft and do legs over the overhead pattern? 
This is the standart way by navy as far as I know to secure the recovery operations as after a long mission even with sufficient fuel several bolters or wareoffs or delays in approaches (case 3) might cause re-fuel demands

Regards

**Comment by DanAlbert** [comment]
Now possible to do by hand, but the flight planner should probably automatically schedule a recovery tanker and make sure its path is aligned with the carrier's travel direction.

**Comment by DanAlbert** [comment]
2.8.0.32937 added an AI task for this that should make it much more tractable.

**Comment by SnappyComebacks** [comment]
I looked into how to do this in DCS.
The minimum waypoints needed is a takeoff and land waypoint (meaning no intermediate waypoints required).  If you choose to do it this way, the duration option is not the duration of time in racetrack.  It includes the time to start up / hook up to the catapult.  "Time more" may be the preferred time control option.

![image](https://user-images.githubusercontent.com/74509817/202881483-9471de13-4a22-4267-9944-3fa911eb7b80.png)

**Comment by DanAlbert** [comment]
> If you choose to do it this way, the duration option is not the duration of time in racetrack. It includes the time to start up / hook up to the catapult. "Time more" may be the preferred time control option.

Unless we plan more than one cycle, I think it'd be fine to skip the end condition altogether. Let it run until it's out of gas. Any reason not to?

**Comment by SnappyComebacks** [comment]
> Unless we plan more than one cycle, I think it'd be fine to skip the end condition altogether. Let it run until it's out of gas. Any reason not to?

The only reason I know _for_ having a stop time depends on planning multiple cycles.  We don't know when the tanker will be out of gas, as its a factor of how many aircraft will use the tanker.

However, if the end time were scheduled, we would still not know if the tanker is empty before its expected stop time.
I could go either way (planned stop vs rtb on bingo).  As long as missions aren't several hours long having one run is probably fine.

**Comment by DanAlbert** [comment]
> As long as missions aren't several hours long having one run is probably fine.

Agreed. Seems like a problem we can ignore.
