### ISSUE TITLE
WW2 AAA sites have the "Dead SAM" icon although undamaged

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#883]
**Describe the bug**
WW2 AAA sites (e.g. Flak, Bofors) spawn in with the "Dead SAM" icon, probably because they do not have a radar.

**Expected behavior**
Air defence that does not have a radar should not trigger the Dead SAM icon.

#1118 preview

**Comment by DanAlbert** [comment]
This is because flak has a detection range of 0 according to DCS. This is unique to the WW2 flak, it seems.

I'm not sure what to do about this. The data we get from DCS is wrong and we don't have a way to signal that this particular piece of data is lying.

**Comment by DanAlbert** [comment]
ddd6e7d18f22de5471d5b9beb322fa81b9dea9bc fixed this incidentally.
