### ISSUE TITLE
Real Time Mid-Mission Kills Tracker (the "Waiting for mission completion" window) stops updating

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#886]
**Describe the bug**
Log produces this error mid-mission and the Kills Tracker stops updating. Manually submitting state.json at the end of the mission works, however.

Exception in thread Thread-131:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "game\debriefing.py", line 266, in run
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

 - DCS Liberation [e.g. 2.3.1]: #1193 preview

**Comment by DanAlbert** [comment]
Without knowing how to cause the problem I don't know what we can do about this. Some invalid JSON got written, but without knowing what we don't have any way to investigate.

**Comment by Starfire13** [comment]
Is there any way to tell which JSON got written? What additional info can I provide that would help in this case?

**Comment by DanAlbert** [comment]
Not if you didn't back up the broken copy that you had mid mission. I'm guessing you spotted this after the fact so that's really unlikely.

**Comment by Starfire13** [comment]
Do you mean you want the state.json as it exists at the point where the problem occurs?

**Comment by DanAlbert** [comment]
Correct.

**Comment by Starfire13** [comment]
Ok. I'll do so the next time I spot it.

**Comment by DanAlbert** [comment]
If you can that'd be great. Difficult to do so.

**Comment by Starfire13** [comment]
Got it. This is the state.json file from about 3 seconds after this error popped up:

Exception in thread Thread-211:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "game\debriefing.py", line 266, in run
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

[state.zip](https://github.com/Khopa/dcs_liberation/files/5975708/state.zip)

**Comment by Starfire13** [comment]
In case you need them, I am also including here the state.json as it was when I ended the mission a couple minutes later, the liberation_nextturn.miz file, and the .liberation file.

[Files.zip](https://github.com/Khopa/dcs_liberation/files/5975718/Files.zip)

**Comment by DanAlbert** [comment]
Awesome, thanks!

**Comment by Starfire13** [comment]
Btw, I am getting this error consistently on every single turn on this WW2 campaign.

**Comment by Starfire13** [comment]
After the enemy's runway was repaired, the error no longer occured. It was occuring on every single one of the 4 turns while the enemy runway was down, on turn 5 with the runway repaired, error did not occur.

**Comment by DanAlbert** [comment]
The supposedly broken one works fine for me so unfortunately still nothing we can do here. Closing as not reproducible for now.

My best guess would be that the file is getting read by liberation while DCS is still writing it, but the fact that it's happening as often as you say it is makes that hard to believe.
