### ISSUE TITLE
font scaling problems in purchase menu

### ISSUE THREAD

**Issue by Pil-Nick** [dcs-liberation/dcs_liberation#887]
In the purchase aircraft screen, the "Add Unit" button is obscured and no lateral scaling is found, so many times I can't click the "Add Unit" button when the number of planes I purchase reaches double digits.

**Comment by Starfire13** [comment]
Are you saying it doesn't look like this on your end? Can you provide a screenshot? 
![Capture](https://user-images.githubusercontent.com/72491792/107864439-39536c00-6eb0-11eb-9d0e-5cdb06e5f406.JPG)

**Comment by Pil-Nick** [comment]
![image](https://user-images.githubusercontent.com/79027768/108025316-3a77cb00-7061-11eb-812c-63df9f7b2b09.png)
This is what I have here.Once the purchase reaches double digits, the button to increase units is completely unclickable, and the window zooms in only to the height, not the width.My monitor has a resolution of 1920X1080.

**Comment by Zelin2001** [comment]
Screenshots here. The buttons won't be displayed properly when the name of some unit is to long.
![未标题-1](https://user-images.githubusercontent.com/52376510/108025438-6f841d80-7061-11eb-8ead-1bf107ca3095.png)

**Comment by Starfire13** [comment]
I wonder if this has something to do with the font used. As you can see, it fits fine on my screen (2560x1440) but it appears Liberation is using a different font on my system.

Edit: I think Liberation just uses the standard Windows 10 font (Segoe). For some reason, this is not the case on your system.

![Capture](https://user-images.githubusercontent.com/72491792/108164632-43da6380-7145-11eb-90e8-8819a43e129a.JPG)

**Comment by Pil-Nick** [comment]
The system I am using is the Chinese version of Win10, which may affect the default font of the system.Can we solve this problem by increasing the horizontal scaling of this window?Thank you very much.

**Comment by DanAlbert** [comment]
We size almost nothing explicitly. It's all sized automatically based in the contents, but the UI framework we use doesn't do that well.

We should just ship the font so it's consistent (though it's really weird that you get such a different font just for having a Chinese Windows install).

**Comment by foxwxl** [comment]
![purchasing window](https://user-images.githubusercontent.com/74572837/108613557-0bc96e00-742e-11eb-8b3a-0c77565a41db.png)
Could be a font problem on Chinese windows version, since only Chinese players have this issue.

If the width of purchase windows can be adjusted(only the length of window can be adjusted now) then it should be fine.

**Comment by DanAlbert** [comment]
Upgrading to Qt6 fixed all the font scaling problems I've seen. Lmk if that's not the case.
