### ISSUE TITLE
Effect of damaged runway

### ISSUE THREAD

**Issue by Pil-Nick** [dcs-liberation/dcs_liberation#888]
After destroying an airstrip in the previous turn, you can add some smoke effects to the airstrip in subsequent rounds, and reduce the smoke effects to zero as the turn progresses.And this function can be switched on and off along with the front smoke or controlled separately.This can add a sense of substitution to the task.

**Comment by Starfire13** [comment]
I understand you're looking to provide some visual sign that the runway is out of commision, but damaged runways don't actually produce smoke because they're not burning.

**Comment by Mustang-25** [comment]
Are we planning on keeping this FR open? @Starfire13 is correct, damaged runways don't really smoke.
