### ISSUE TITLE
Aircraft destroyed on the ground at airfield without functional runway not staying dead

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#889]
**Describe the bug**
There were 12 aircraft on the ground at Abberville Drucat after I disabled the runway. I have been destroying these aircraft on the ground each turn, but they are not staying dead. The 12 aircraft come back on the next round. Since you can't buy aircraft for an airfield with a disabled runway, this isn't due to replenishment. I suspect this might be related to issue #886, and you can use the files uploaded on there to test this.

Running #1193 preview

**Comment by Mustang-25** [comment]
Are you still seeing this problem on the latest builds?
