### ISSUE TITLE
Make Strategic bombers (e.g B52& B1) Fly Higher

### ISSUE THREAD

**Issue by NeelKulkarni6** [dcs-liberation/dcs_liberation#891]
I think the bombers are flying too low. Sometimes if i send them to bomb a factory or oil well they get shot down by AA on the front line or lower range SAMS. Most the time they fly at 3000 ft asl which is far below their 50k and 30k flight ceilings. Also i think this might already be in the works but their flight paths should avoid known sam sites and other dangerous areas.  

on version 2.4.2

**Comment by DanAlbert** [comment]
Everything related to mission-specific flight plans is https://github.com/Khopa/dcs_liberation/issues/270
