### ISSUE TITLE
AI OCA/runway flights cannot attack runways with guided bombs like GBU-31

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#894]
**Describe the bug**
AI flights tasked with OCA/runway and equipped with guided bombs like GBU-31s will fly up to the runway and RTB without dropping their bombs. They behave properly with unguided bombs.

Potential workaround if this is due to some DCS AI bug, is to allow runways to be selectable as a strike target, since that works fine with guided bombs.

**Comment by DillieKoe** [comment]
Has been fixed to work with gbu 31 and gbu 38 but not with lgbs
