### ISSUE TITLE
Anti-ship flights and their escorts being sent in different directions when attacking enemy carrier

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#902]
**Describe the bug**
#1201 preview
I set up a package to go attack the Russian carrier, and the waypoints for the escort flights correctly point to the carrier but my Hornets are flying to another group. The .liberation file is attached.

[Black Sea Lite.zip](https://github.com/Khopa/dcs_liberation/files/6013639/Black.Sea.Lite.zip)

![Capture](https://user-images.githubusercontent.com/72491792/108572408-51baff00-7366-11eb-8d58-27c783e187ae.JPG)

**Comment by Mustang-25** [comment]
Is this bug still valid in the latest builds?

**Comment by Mustang-25** [comment]
closing because no response from OP. Will reopen if bug is still valid.
