### ISSUE TITLE
Ability to include multiple tactical commanders

### ISSUE THREAD

**Issue by ccuh** [dcs-liberation/dcs_liberation#905]
Would be nice to have option to have more than one tactical commander slots for CA users.

Best regards

**Comment by rurounijones** [comment]
+1 on this request. The ability to have a configurable number of Bluefor _and_ Redfor Tactical commanders (To allow a "Dungeon Master" role) would be great.

**Comment by Mustang-25** [comment]
Closing this and consolidating together with #1481 under the general umbrella of being able to select the amount of observers and commander slots.
