### ISSUE TITLE
Write Terminal Output To File

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#907]
**Is your feature request related to a problem? Please describe.**
Writing out the console to a file might help with debugging issues like: https://github.com/Khopa/dcs_liberation/issues/886 and https://github.com/Khopa/dcs_liberation/issues/904 due to verbose console output hiding early errors.

**Describe the solution you'd like**
Have the Liberation console output to a file.  Data only exists for one Liberation session, file is overwritten on new Liberation sessions.  Best place to put the file might be where the Liberation install is?

**Comment by DanAlbert** [comment]
This is what the `logs` directory in the Liberation install directory is. However, it looks like it was logging at the INFO level instead of DEBUG, so the console would have some messages that the file didn't. Made them match.
