### ISSUE TITLE
B-17G flightplan missing bombing triggers

### ISSUE THREAD

**Issue by clutchtomcat** [dcs-liberation/dcs_liberation#909]
B-17G tasked with SEAD through Liberation (Ground Attack in DCS) are given a waypoint over the target, but are missing the bombing triggers necessary for the B-17s to employ their bombs. Typically there is no waypoint over the target, with the IP waypoint tasked with an advanced action "Bombing", and the target triangle positioned over the desired target. To my knowledge, B-17s can't (or at least have difficulty with) attacking targets without the bombing advanced task set.

**Comment by DanAlbert** [comment]
Attach the files the template asked for so we can investigate.

**Comment by clutchtomcat** [comment]
[Mustang-Channel.zip](https://github.com/Khopa/dcs_liberation/files/6017785/Mustang-Channel.zip)

Here's the save file. I already edited the flightplans in the generated .miz file, but if it happens again I can send that one later.

**Comment by DanAlbert** [comment]
6ca175345f508143da27cd46821b565ad8559be3 (though you want DEAD, not SEAD)
