### ISSUE TITLE
Map projection is imperfect

### ISSUE THREAD

**Issue by MedievalBunny** [dcs-liberation/dcs_liberation#91]
Many of the airbases on the Invasion of Iran map are located incorrectly. 

Bandar Abbas, Havadarya, Qeshm Island, and Shiraz are all too far north, while Khasab is too far west. 

It looks like it may effect satellite units as well, as several naval units are being drawn on land. 

![Capture](https://user-images.githubusercontent.com/19675397/90865643-486dbd00-e358-11ea-8e40-abf976e1fb40.JPG)

**Comment by Khopa** [comment]
Yes, the current code use an approximation to plot stuff on the map background. 

The DCS X,Y coordinates that i am using are not for use on a 2D plan, so it's not really precise.
I'm still looking for a way to accurately project the coordinates on the map, and also to convert them to Lat/Lon and/or MGRS.

Also see : https://github.com/pydcs/dcs/issues/38

**Comment by Mustang-25** [comment]
Liberation 3.0 will have a new map system and this will no longer be an issue so I am marking this as resolved/closed.
