### ISSUE TITLE
F-14's assigned to too small parking hangars at King Husseins Air College

### ISSUE THREAD

**Issue by chrisofsweden** [dcs-liberation/dcs_liberation#916]
Syria, King Husseins Air College

Liberation will buy F-14's to this base and put them in parking spots (small hangars) that are too small.
The F-14's is destroyed on mission start.

**Comment by Khopa** [comment]
F-14A or F-14B ?

**Comment by Khopa** [comment]
It is possibly the same issue as : 

https://github.com/Khopa/dcs_liberation/issues/438

https://forums.eagle.ru/forum/english/licensed-third-party-projects/heatblur-simulations/dcs-f-14a-b/bugs-and-problems-bf/7151390-taxi-issue-on-al-minhad-airbase-for-the-f-14a-135-gr

**Comment by chrisofsweden** [comment]
I'm not sure. I thought it was bravos, but might have been alphas. Anyway, they spawned with wings fully extended right away.
I discussed this with one of the guys on discord and it's not really a Liberation problem, it's a map / aircraft problem. So I hereby close my issue, and we'll wait for a proper map fix instead.
