### ISSUE TITLE
F-22A Mod

### ISSUE THREAD

**Issue by chrisg117** [dcs-liberation/dcs_liberation#918]
An F-22 package cannot be double clicked or edited in order to add a client slot. Only way I could get a client slot is by adding a whole new flight entirely to package. 

It also does not have an image preview like all the other aircraft.

**Comment by Khopa** [comment]
Thanks for reporting this, it will be fixed in the upcoming 2.4.4 patch

(Fixed in commit 58d5aa9944a888357f0150f15fd5d9eb48780481)
