### ISSUE TITLE
Recenter map when loading game

### ISSUE THREAD

**Issue by MedievalBunny** [dcs-liberation/dcs_liberation#92]
The Nevada map can be zoomed out far further than it is drawn, and scrolled in several directions until it is completely off the page. When I started a new game on it, the default view contained nothing but empty space. 

![Capture](https://user-images.githubusercontent.com/19675397/90866135-0ee98180-e359-11ea-86e7-683cdfde22fc.JPG)

**Comment by DanAlbert** [comment]
This was done in 3.0.
