### ISSUE TITLE
application exits when takeoff button pressed

### ISSUE THREAD

**Issue by Hornet2041** [dcs-liberation/dcs_liberation#921]
**Describe the bug**
dcs_liberation.exe exits suddenly when pressing takeoff button

**To Reproduce**
unable to consistently reproduce. seems random

**Expected behavior**
the program to not exit.

**Additional information**

log of the game session attached

**Version information (please complete the following information):**
 - DCS Liberation build #1235
[crash log liberation.txt](https://github.com/Khopa/dcs_liberation/files/6038562/crash.log.liberation.txt)
2021-02-24 12:39:57,947 is when it exits

**Comment by DanAlbert** [comment]
I'm guessing Qt is the source of the crash, because we stop logging. Unfortunately we don't have any information to go on so nothing we can do here.
