### ISSUE TITLE
BARCAP Plotting

### ISSUE THREAD

**Issue by Ryanwtod** [dcs-liberation/dcs_liberation#924]
When planning missions BARCAP seems to be plotted on useless paths. BARCAP for instance over an area should plot in the area of the airport and between the enemy and the airport. Often Times BARCAP will be plotted over friendly units away from the enemy and not in any proximity to it's "target" 

To reproduce start a campaign and select a BARCAP mission over a friendly unit. BARCAP will  not be plotted in an area that is effective

**Comment by DanAlbert** [comment]
> To reproduce start a campaign and select a BARCAP mission over a friendly unit. BARCAP will not be plotted in an area that is effective

This isn't what we see. Include the information the template asked for so we can see what you're talking about.

**Comment by clutchtomcat** [comment]
> This isn't what we see. 

This was brought up on Discord a week or two ago. If I recall correctly the CAPs are planned to stay outside of SAM zones. It's easily reproducible for me on Channel, Dunkirk scenario: A TARCAP over the frontline south of Dunkirk is fragged with a flight plan well north of Dunkirk every single time.

**Comment by DanAlbert** [comment]
This title says BARCAP, not TARCAP. The two have entirely different flight planning.

**Comment by DanAlbert** [comment]
Closing for lack of info. If OP tells us what they meant we can reopen.

**Comment by clutchtomcat** [comment]
Issue affects both BARCAP and TARCAP in the same manner. See attached save file.

BARCAP Dunkirk (x2) are both planned severely north, making them useless. TARCAP front line (x2) also both planned severely north.
[CAP bug.zip](https://github.com/Khopa/dcs_liberation/files/6080242/CAP.bug.zip)

**Comment by DanAlbert** [comment]
With threat zones and commit ranges enabled: 
![image](https://user-images.githubusercontent.com/315852/109897433-8cb31180-7c47-11eb-9919-ce137a71856d.png)

This is the expected behavior. CAPs are defensive. If they were any closer they'd start being a sweep.

**Comment by clutchtomcat** [comment]
Now I see the issue. WW2 aircraft don't have radars or weapons to deal with that commit range. I'll have to adjust those manually. 

TARCAP should be more "offensive" in nature as those are defending assets over the target area and not a BARCAP by a different name, as they currently are. Do the threat zones interfere with pushing those up more aggressively?
