### ISSUE TITLE
Add new setting for mission generation to limit mission time and TOT for generated flights

### ISSUE THREAD

**Issue by plemtom** [dcs-liberation/dcs_liberation#925]
In my experience with Liberation campaign, all missions I fly end in about an hour or sooner than that. Mission generator adds flights with TOT later than one hour. I can delete/edit such flights generated for my side, but OPFOR probably also has similar flights generated which leads to waste of resources on their side. 

I think it might be useful to be able to define time limit for missions you intend to fly so that the generator knows how to plan flights to reduce the waste.

**For example:** if you'd set a limit to 1 hour, only 2 barcaps would be needed for every defended resource instead of default three and that would allow OPFOR to buy more offensive aircraft and plan more offensive missions sooner in the campaign. Also all offensive flights would have to be generated with TOT below 1 hour to make sure they have a chance to hit their targets or die trying. 

Also since different people may have different preferences and different maps require different TOTs I think the best solution would be the additional value in settings so that everyone could calibrate the experience to their preferences.

**Comment by DanAlbert** [comment]
https://github.com/Khopa/dcs_liberation/issues/832
