### ISSUE TITLE
Period Accurate weaponry and aircraft

### ISSUE THREAD

**Issue by PangolinWranglin** [dcs-liberation/dcs_liberation#927]
On the F-5, using the period accurate weapons in both the US 1965 and 75 lineups, there are very few weapons to choose from in terms of air to air missiles. In 1965 the GAR-8 (Aim-9B) would technically be the only choice as it was in service since the late 50s, however the Aim-9P should also be included as it is lacking in capability compared to the Aim-9P5 mainly lacking in the all aspect capabilities that the P5 has. Equivalents to the Aim-9P also saw service in the Vietnam war making it a good fit. The USA 1975 should also be limited to the P to my knowlegde (I was unable to find a source talking specifically about the P5 and its intro date) The F-4 should be similarly limited to its earlier weapons in the 1965 lineup to the Aim-9L and the Aim-7E (1963)
[See this for info on Aim-9 variants](http://www.designation-systems.info/dusrm/m-9.html)

The Mig-29 should not be in the 1975 Russia line up at all. It entered service in the 1980s and wasn't even flying until 1977. If it is still kept in the line up the default loadout needs to be addressed as it does not spawn with any weapons at all. If included it should at the very least NOT be using R-73s. 
[See this, page 112, sources at the bottom of the page](https://apps.dtic.mil/sti/pdfs/ADB165245.pdf)

B-52s in the 1965 and 75 USA lineups shoudl also be limited to dumb bombs only, as the AGM-86 did not enter service until 1983
[See this](https://www.af.mil/About-Us/Fact-Sheets/Display/Article/104612/agm-86bcd-missiles/)

**Comment by Mustang-25** [comment]
The only real issue from this is that the GAR-8 is not included in the Liberation fallback database.

As discussed on discord, OP had not enabled the fallback.

**Comment by DanAlbert** [comment]
Weapons are done (some data is missing, patches welcome) and aircraft are just a matter of designing the faction correctly, so looks done.
