### ISSUE TITLE
B52s not performing DEAD with AGM-86Cs

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#929]
**Describe the bug**
B-52s are not deploying AGM-86Cs at the target (SA-10).  This happens both with Skynet enabled or disabled.  When the B52 reaches the Ingress point it turns directly towards the egress point.

**To Reproduce**
1)  Generate "Nevada - Exercise Vegas Nerve" campaign.
    - USA 2005, Russia 1990,
    - No carriers/LHA
    - Start date: Mid-90s Summer [1995]
    - Culling of distant units enabled (100 km) + No cull around aircraft carriers
    - Restrict Weapons by date enabled
    - Jtac Autolase, Skynet (as desired)
    - All the money
    
2)  Create a DEAD mission on an SA-10 that is isolated (3 Tors + 2 SA-10 TRs) with the following
    
    - 4 ship DEAD F18 (1x Player, Runway Start)
    - 2 ship DEAD B-52 (Air Start)
    - 2 x 4 ship SEAD F18 (Air Start)
    - 2 x 4 ship ESCORT F16 (Air Start)

3)  Play the mission and watch the B52s.

**Expected behavior**
B-52s to launch ordinance at prescribed target.

**Additional information**
Campaign, Mission, Tacviews for Skynet + No Skynet:
[B52_Bailed_Skynet.zip](https://github.com/Khopa/dcs_liberation/files/6056294/B52_Bailed_Skynet.zip)
[B52_Bailed_NoSkynet.zip](https://github.com/Khopa/dcs_liberation/files/6056295/B52_Bailed_NoSkynet.zip)

Skynet + No Skynet Tracks:
[B52_Bailed_Tracks.zip](https://github.com/Khopa/dcs_liberation/files/6056298/B52_Bailed_Tracks.zip)

**Version information (please complete the following information):**
 - DCS Liberation 2.4.2

**Additional context**
![NoSkynetAnnotated](https://user-images.githubusercontent.com/74509817/109408993-1616cb00-794c-11eb-8555-2440918a348c.png)

**Comment by DanAlbert** [comment]
This was 6ca175345f508143da27cd46821b565ad8559be3
