### ISSUE TITLE
F-117As only attack SAMs when set as Strike mission

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#930]
**Describe the bug**
Assigning F117As to attack a SAM site in SEAD or DEAD will cause the flight to not attack the SAM.  Skynet on/off does not appear to change the result.

When flight is DEAD, flight will turn direct from ingress to egress.
When flight is SEAD, flight will overfly SAM but not attack.

**To Reproduce**
1)  Generate Campaign with player faction USA 2005, enemy faction: Iran 1988
    - Maximize player income
    - Minimize opposition faction starting money and income for ease of testing
2)  Buy lots of F117As
3)  Pass time until night
4)  Generate SEAD, DEAD, Strike F-117A flights on different SAMs (Like one SAM site gets a DEAD flight, one SAM site gets a SEAD flight, one SAM gets a Strike flight)
5)  Observe
    - DEAD flight will turn direct from Ingress to Egress waypoint, bomb bay closed
    - SEAD flight will overfly SEAD waypoint, bomb bay closed
    - Strike opens bomb bay after passing Ingress, with all planes in the flight bombing WP1 on first pass then bombing WP2 on second pass.

**Expected behavior**
F117As to attack SAMs when configured as DEAD or SEAD flight.

**Additional information**

Campaign, Mission, Tacviews:

[F117a_SAM_attack_DEAD_NoSkynet.zip](https://github.com/Khopa/dcs_liberation/files/6057776/F117a_SAM_attack_DEAD_NoSkynet.zip)
[F117a_SAM_attack_SEAD_NoSkynet.zip](https://github.com/Khopa/dcs_liberation/files/6057778/F117a_SAM_attack_SEAD_NoSkynet.zip)
[F117a_SAM_attack_SEAD_Skynet.zip](https://github.com/Khopa/dcs_liberation/files/6057779/F117a_SAM_attack_SEAD_Skynet.zip)
[F117a_SAM_attack_Strike_Skynet.zip](https://github.com/Khopa/dcs_liberation/files/6057780/F117a_SAM_attack_Strike_Skynet.zip)

**Version information (please complete the following information):**
 - DCS Liberation 2.4.2

**Additional context**
 - When Skynet is disabled, the SAMs detect the F117s a couple of miles away.  If the SAM is powerful enough it will fire before the flight overflies the SAM.
 - When Skynet is enabled, the SAMs aren't on, so only point defenses detect them when nearby.

**Comment by DanAlbert** [comment]
Any reason to believe this isn't a dup of https://github.com/Khopa/dcs_liberation/issues/774?

**Comment by SnappyComebacks** [comment]
> 
> 
> Any reason to believe this isn't a dup of #774?

#774 specifically calls out the case when the SAMs are not emitting.  However in this case specifically:

[F117a_SAM_attack_DEAD_NoSkynet.zip](https://github.com/Khopa/dcs_liberation/files/6057776/F117a_SAM_attack_DEAD_NoSkynet.zip)
[F117a_SAM_attack_SEAD_NoSkynet.zip](https://github.com/Khopa/dcs_liberation/files/6057778/F117a_SAM_attack_SEAD_NoSkynet.zip)

The SAMs are emitting and not being attacked.  In the responses of #774, the general consensus appears to be that if the SAMs are emitting, they should be valid targets for SEAD/DEAD.

**Comment by DanAlbert** [comment]
But based on your report it's because they're dead before they get to the target, not because they aren't trying:

> When Skynet is disabled, the SAMs detect the F117s a couple of miles away. If the SAM is powerful enough it will fire before the flight overflies the SAM.

Is that not the case?

**Comment by SnappyComebacks** [comment]
> 
> 
> But based on your report it's because they're dead before they get to the target, not because they aren't trying:
> 
> > When Skynet is disabled, the SAMs detect the F117s a couple of miles away. If the SAM is powerful enough it will fire before the flight overflies the SAM.
> 
> Is that not the case?

I see how that could be misleading.  I was specifically referring to SAMs like SA-10s and Tors.  No, that is not the case in this scenario.  In the two different Non Skynet cases I attached, there are two flights.  One set to attack an SA-2, another set to attack a Hawk site.  Both SAM sites are active the whole scenario, due to Skynet being disabled.

When the flights are set to SEAD, the flights overfly the targets, when this happens:
 - The Hawk site fires after the flight has overflown the target.
 - The SA-2 turns it's missiles towards the flight before the flight arrives but never fires.

When the flights are set to DEAD, the the flights turn from Ingress to Egress and are never fired upon.

If my description of events is confusing feel free to look at the Tacview attached here:
[F117a_SAM_attack_SEAD_NoSkynet.zip](https://github.com/Khopa/dcs_liberation/files/6057778/F117a_SAM_attack_SEAD_NoSkynet.zip).

Also F-117As are tanks and can take lots of missile hits but that is a DCS issue.

**Comment by DanAlbert** [comment]
Gotcha. Same problem, as #774 then, just different circumstances. All of these are just another case of "AI can't see the target so they go home". We still don't know how to fix it other than planning suicide missions.

Duping this bug into that one, but going to link this there since there's a lot of good data here.
