### ISSUE TITLE
AI does not fill front lines with ground units even if they have money

### ISSUE THREAD

**Issue by ssg-dev** [dcs-liberation/dcs_liberation#931]
**Describe the bug**
AI even when they have money, in this case 2000 million, AI does not fill front line with ground units. This might be more of an feature request than bug report depending on what behaviour devs have intented. After a turn where you destroy most, or all AI ground units on the next turn AI only has few units on the frontline even if they had more than enough money to fill the front line.

**To Reproduce**
Play a turn. Plan some CAS missions to destroy enemy ground units. Finish the mission.
Observe that even if the AI has money they have not filled front line with new units.

**Expected behavior**
If AI has resources, AI should utilize them by always having units in the frontline.

**Additional information**
AI front line purchases are governed by same rules as players so there is not buffer for ground units where AI could pull units to frontline every turn even if they had resources to do it.

Suggestion: Allow AI to pull more units from FOBs connected to frontline and make sure AI purchases FOBs full of units (30 units)for FOObs that are not active on frontline so if AI has money they can always fill the frontline with new units.

We will usually need more information for debugging. Include as much of the following as you are able:

Liberation file
[frontlineunits.zip](https://github.com/Khopa/dcs_liberation/files/6057812/frontlineunits.zip)

**Version information (please complete the following information):**
 - DCS Liberation 2.5.-1201-preview:

**Additional context**

**Comment by Nosajthedevil** [comment]
In addition, consider changing the desired unit count from 30 total to 30 per front, or 30 per base / FOB along front lines. 30 units total spread among 2 to 4 fronts on a large map is kind of thin. I know it's rare, but on Iran full map for instance it's possible to have 2 fronts in the north and 2 in the south at the same time. Redfor unit count on each front can be really low and pretty easy to steamroll.

**Comment by DanAlbert** [comment]
@Nosajthedevil file a new bug. We can't track an individual comment so requests that pile on to existing bugs are easy to forget.

**Comment by DanAlbert** [comment]
Ground unit purchase was redone in 3.0 so should be gone.
