### ISSUE TITLE
Flight plan not drawn on map

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#932]
**Describe the bug**
Any attempt to plan a flight generates this error and the flight plan is not shown on the map. However, it is still listed in the Package window. Restarting Liberation gets rid of the error.

Traceback (most recent call last):
  File "qt_ui\widgets\map\QLiberationMap.py", line 156, in update_package_selection
  File "qt_ui\widgets\map\QLiberationMap.py", line 674, in draw_flight_plans
  File "qt_ui\widgets\map\QLiberationMap.py", line 667, in clear_flight_paths
TypeError: 'PySide2.QtWidgets.QGraphicsScene.removeItem' called with wrong argument types:
  PySide2.QtWidgets.QGraphicsScene.removeItem(QWidgetItem)
Supported signatures:
  PySide2.QtWidgets.QGraphicsScene.removeItem(PySide2.QtWidgets.QGraphicsItem)

**Version information (please complete the following information):**
#1238 preview

**Comment by DanAlbert** [comment]
Checked all the code paths that got here and this should be impossible from what I can tell. Without repro steps I don't think we can fix this.

Closing since there's nothing we can do as-is. If someone knows how to repro this let us know and we'll reopen.
