### ISSUE TITLE
Tanker positioning

### ISSUE THREAD

**Issue by Meyomyx** [dcs-liberation/dcs_liberation#933]
I see there is a suggestion that is related to tanker placement. However, the existing placement algorithm seems patchy. I'm going to need a tanker to get to the tanker! The bullseye locations seem similarly unusual.
![Untitled](https://user-images.githubusercontent.com/70166005/109770951-25b83d00-7bf4-11eb-9232-fffe498ee200.jpg)

**Comment by SnappyComebacks** [comment]
I encountered this as well.  Once Palmyra was captured the tankers went back to their usual positions for me.

Since Liberation does not manage tankers besides spawning them somewhere (and putting their info in the kneeboard), you are able to move them wherever you want to, or delete them.  In this campaign I put some at Incirlik and some behind the front line.  If you make multiple, be sure to give them unique callsigns.

**Comment by clutchtomcat** [comment]
Biggest issue is the tanker's waypoints being off the map entirely. This forces the user to delete the flightplan and rebuild it from scratch.

**Comment by DanAlbert** [comment]
There isn't a wall at the end of the map, it's just lower detail terrain.

**Comment by clutchtomcat** [comment]
> There isn't a wall at the end of the map, it's just lower detail terrain.

There is a wall in the Mission Editor. The user is unable to move some of the waypoints because they are outside the clickable area. That's clear in the above screenshot.

**Comment by DanAlbert** [comment]
> This forces the user to delete the flightplan and rebuild it from scratch.

Okay, I guess you mean "you can't modify the flight plan", not "the mission will not load".

**Comment by clutchtomcat** [comment]
> Okay, I guess you mean "you can't modify the flight plan", not "the mission will not load".

No one made that insinuation anywhere in this thread.

**Comment by DanAlbert** [comment]
It wasn't clear and I wanted to clarify. It was confusing to me because no one is _forced_ to modify the flight plan at all, so I thought you meant the mission could not be played without deleting the flight plan.

**Comment by clutchtomcat** [comment]
It's amazing anything gets fixed when extremely clear and straightforward topics go into mental gymnastics....

**Comment by Meyomyx** [comment]
Clutchtomcat - its worth remembering that these guys make this remarkable software in their own time for our enjoyment and it costs you absolutely nothing. Cut them some slack bud?

Only the last waypoint is off the editor. You can delete that one and remake it. Slightly fiddly but a bit easier than creating a tanker from scratch.

Happy Easter hols one and all.

**Comment by clutchtomcat** [comment]
Contributing to the community excuses an abrasive attitude? I won't be a part of such toxicity then.

**Comment by HILOK** [comment]
any chance we could have a tanker icon added to the liberation UI that could be moved freely on the map? maybe with a little context window for ALT & TRACK?
(it is possible of course to do this in DCS's ME, but you would have to move 4 items and assign the desired ALT 4x for every turn)
thanks

**Comment by Mustang-25** [comment]
The latest release has taskable and movable tankers, closing this FR.
