### ISSUE TITLE
Ineffective BARCAP Plotting

### ISSUE THREAD

**Issue by Ryanwtod** [dcs-liberation/dcs_liberation#934]
Mentioned this earlier. The topic was closed due to no information. I was out of town. BARCAP missions are not being plotted in an effective area. BARCAPs are often not plotted between the friendly unit they are assigned to and the enemy. Often they are not even plotted anywhere near where they would be able to protect the unit. I'm using 2.4.3. This can be reproduced by starting a new mission and plotting a BARCAP mission on a friendly unit. You can see neither the carrier BARCAP, nor the Gudauta BARCAP missions are plotted where they could act as a barrier before they units they're protecting are attacked

![BarCap](https://user-images.githubusercontent.com/77306573/109897768-318e1880-7c61-11eb-962a-7ec05b19da7b.PNG)

[Liberation Caucus.zip](https://github.com/Khopa/dcs_liberation/files/6080300/Liberation.Caucus.zip)

**Comment by DanAlbert** [comment]
Raced with me updating the other bug.

![image](https://user-images.githubusercontent.com/315852/109898815-ad7c6680-7c49-11eb-9d4f-f180876a32a9.png)
![image](https://user-images.githubusercontent.com/315852/109898830-b2d9b100-7c49-11eb-8b8f-e31458373f1d.png)


Both of these are correct. They're defensive so they stay out of enemy territory.
