### ISSUE TITLE
"Search then engage" conditions interfere with AI engagement

### ISSUE THREAD

**Issue by clutchtomcat** [dcs-liberation/dcs_liberation#935]
Redirected from Discord. 

Search then engage (in zone) and similar advanced waypoint actions have conditions set to "fighters" only. After having a multitude of issues with my AI wingmen and AI patrols/sweeps not engaging enemy aircraft, I did some digging into this setting and, upon changing it to allow engagment of all aircraft, the AI wingman, patrols, and sweeps engaged normally. 

In my current campaign the majority of bandits are Fw190 A-8s, so it looks like whatever database used by the AI does not classify the A-8 as a "fighter," thus they never engaged.

**Comment by DanAlbert** [comment]
https://github.com/dcs-liberation/dcs_liberation/issues/1124
