### ISSUE TITLE
F-14A has incorrect weapons in 1978

### ISSUE THREAD

**Issue by PangolinWranglin** [dcs-liberation/dcs_liberation#937]
Before filing, please search the issue tracker to see if this feature has already been requested.

(My current campaign is set in 1978 for the record)

The F-14A needs access to the Aim-7F Sparrow [(entered service in 1976)](https://www.globalsecurity.org/military/systems/munitions/aim-7.htm) (I can provide a few more sources for that if requested, I could not find 1 solid source, but all of the ones talking about the 7F specifically said 1976) and the Aim-54s should be limited to the A, as the C didn't enter service until [around 1981 or 82](https://www.navy.mil/Resources/Fact-Files/Display-FactFiles/Article/2168381/aim-54-phoenix-missile/)

**Comment by Mustang-25** [comment]
I just checked in Liberation and the F-14A does already have access to the 7F and is properly date restricted to 1976.
