### ISSUE TITLE
Aircraft at airport does not match number of aircraft reported by intel at Tonopah Test Range Airfield

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#938]
**Describe the bug**
The Liberation campaign reports 36 aircraft at Tonopah Test Range Airfield, however upon inspection of the mission file, a total of 14 aircraft (8 on ground, 6 air starts) are found.  This makes OCA/Aircraft strikes considerably less effective.

**To Reproduce**
1.  Generate 1995 era, Nevada "Exercise Vegas Nerve" campaign (USA 2005 vs Russia 1990).  Weapon Restrictions on.
2. Play the campaign a couple of turns for Russia to build up their forces.
3. Observe the difference between number of aircraft reported, and number that actually exists.

**Expected behavior**

The number of aircraft reported by the Liberation campaign should match the number of aircraft starting from that airfield.

**Additional information**

Campaign and Mission:
[Tonopah_Wrong_Aircraft_Count.zip](https://github.com/Khopa/dcs_liberation/files/6088037/Tonopah_Wrong_Aircraft_Count.zip)

**Version information (please complete the following information):**
 - DCS Liberation 2.4.2

**Comment by Mustang-25** [comment]
Have you noticed this issue still on the latest build or can we close this one out?

**Comment by SnappyComebacks** [comment]
I haven't noticed this recently, but I also haven't played a Nevada campaign in a while.  I can reopen or make a new issue if I see it again.
