### ISSUE TITLE
Feature Request: Assignable Carrier Routes

### ISSUE THREAD

**Issue by jake-lewis** [dcs-liberation/dcs_liberation#94]
I'm unsure if carriers move by themselves (other than normal movement to enable recovery), but it would be nice to be able to assign a movement task, maybe it would resolve after the turn has passed. Currently for something like the Syria Operation Inherent Resolve, the carrier is pretty far out from Jiroft, which makes sense at the start but would be good to be able to change as bases are captured

**Comment by DanAlbert** [comment]
@Khopa done, right?

**Comment by Khopa** [comment]
Yes, closing.
