### ISSUE TITLE
Can't capture oil fields, not clear what ordnance is required to destroy

### ISSUE THREAD

**Issue by ccuadrado** [dcs-liberation/dcs_liberation#942]
Before filing, please search the issue tracker to see if the issue has already been reported.

**Describe the bug**
Mission: Cacuses Lite 
Landed a helo on the oil field pad. Couldn't capture, only destroy with bombs. 

**To Reproduce**
See an oil field with a helipad on it, land on it with a helo. After ending the mission the item remains uncaptured.

**Expected behavior**
Shouldn't we be able to capture this unit if we land a friendly unit close enough to it?

**Additional information**

**Version information (please complete the following information):**
 - DCS Liberation [e.g. 2.3.1]: 2.4.3

**Additional context**

**Comment by Starfire13** [comment]
Resource points are automatically captured when the control point (airfield, FOB) they are associated with is captured. You cannot capture resource points on their own.

**Comment by ccuadrado** [comment]
OK cool, I thought I'd have to plan separate cleanup/capture events, but now i can just attack the airfield and capture it and reap the benefits.
