### ISSUE TITLE
F-86 Sabre has no custom loadout file

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#943]
**Describe the bug**
F-86 does not come with a loadout file in Liberation. I have created one, but it doesn't appear to be working right. Liberation will read and use the loadouts from the file fine (they show up correctly when flight planning), but doesn't transfer them to the generated liberation_nextturn.miz file

Here's the loadout file I generated.
[F-86F Sabre.zip](https://github.com/Khopa/dcs_liberation/files/6104729/F-86F.Sabre.zip)

**Comment by Khopa** [comment]
Thanks :+1: 
Fixed on develop branch.
