### ISSUE TITLE
Simple logistics system.

### ISSUE THREAD

**Issue by FlankerDude** [dcs-liberation/dcs_liberation#944]
Something that always bugged me a little bit about DCS-Liberation, was that one of the most important things in war is not simulated: Logistics

My idea is to include a very simplistic but still enjoyable logistics system that consist of ammo and fuel. Both ammo and fuel are going to be used for your aircraft and their planned sorties. This would also force the player to provide security for already captured areas and their supply lines. It would also encourage the player to overthink their strategy from a economic point of view, and let them prioritise certain targets over others and prevent a rather wastefull use of ordnance. This would also push the player to plan their strategy further in advance, and include a sort of preperation time for big missions and strikes.

In practise it could work like this:
Both ammo and fuel would be added in certain ammounts round by round (comparable to money), both resources will arrive in certain locations on the map (for example ports or airports). The players task will now be to distribute these resources across his airbases, either by air or by road (so the player would have to choose between either a fast but not as big delivery, or a slower but rather big delivery of resources) The player would also have to acquire the needed logistics vehicles and assign them with their escort vehicles to their logistic missions. (so we would get an air-transport and convoy mission) This would also be a great chance for adding a helicopter escort mission. To make it not as boring, i would add a chance for the convoy to be ambushed or a cargo aircraft to be intercepted when conducting supply missions in unsecured territories.

**Comment by DanAlbert** [comment]
Duplicate.
