### ISSUE TITLE
transfer aircraft out of captured bases

### ISSUE THREAD

**Issue by HILOK** [dcs-liberation/dcs_liberation#945]
**Before filing, please search the issue tracker to see if the issue has already been reported**
see #693

**Describe the bug**
capturing a base, where the opponent has most of its air assets can basically break OPFOR. despite the fact that there would be space available on other AB in range, air assets are currently not transferred before a base is taken, and thereafter registered as lost. the campagin goes on, but without real air resistance.

**To Reproduce**
1. start invasion of iran lite as bluefor modern
2. wait for shiraz to be filled with dozens of a/c by redfor
3. capture shiraz
4. See error: all air assets from shiraz are lost, although kerman has plenty of parking space left

**Expected behavior**
simple: after base capture (runtime), air assets are transferred to the closest AB with available parking slots until filled up. then to the next closest AB, a.s.o. (assuming the evacuation process had taken place before the actual capture during turn; assuming a well organized evacuation where distance is no factor thanks to AAR)

more elaborate: define a radius (tbd) around any base that, if crossed by a number (tbd) of OPFOR ground forces, will trigger transfer of air assets. player would be able to see this during runtime.

**Additional information**
We will usually need more information for debugging. Include as much of the following as you are able:
- DCS Liberation save file: attached
- The generated mission file: attached, but the one after the turn (shiraz already taken)
- A tacview track file: attached
- The state.json file from the finished mission: attached

**Version information (please complete the following information):**
 - DCS Liberation 2.4.3-2

**Additional context**
N/A

**Comment by HILOK** [comment]
![kerman](https://user-images.githubusercontent.com/76898536/110659218-aa8df280-81c2-11eb-803f-6b37d7ccbdc9.JPG)
[invasioniranlite_summer90.zip](https://github.com/Khopa/dcs_liberation/files/6117225/invasioniranlite_summer90.zip)
[liberation_nextturn.zip](https://github.com/Khopa/dcs_liberation/files/6117226/liberation_nextturn.zip)
[Tacview-20210307-093906-DCS-liberation_nextturn.zip.zip](https://github.com/Khopa/dcs_liberation/files/6117227/Tacview-20210307-093906-DCS-liberation_nextturn.zip.zip)
[state.zip](https://github.com/Khopa/dcs_liberation/files/6136302/state.zip)

**Comment by Zarbas** [comment]
Would this make sense though? I would image that if you lose control of a base and you have all your airplane in it then your opponent owns them and he can do whatever he likes with them. It should be up to you (or up to the AI) to manage your resources properly and protect your units.

**Comment by HILOK** [comment]
yes, but this here refers to **THE PLAYER taking an AI BASE,** and AI being incapable of protecting their assets.

**Comment by Zarbas** [comment]
I get that, but just my two cents here: while they're moving towards some kind of realism wouldn't be better to plan for missions to evaquate the bases instead of just making units disappear? 

You have to be mindful of your resources, and somehow it would be cool if the AI could do it as well. There are so many little tricks that could be use to give us even just the resemblance of some smart choices in the automated planning.

Look at situations like the one below:

![kuzn](https://user-images.githubusercontent.com/33418102/111005232-53368080-8382-11eb-98b0-96360aa8c9be.png)

Wouldn't you do anything in your power to send $1.5B of planes to the bottom of the ocean? Would you put any extra effort if you know that they just disappear?

**Comment by HILOK** [comment]
> wouldn't be better to plan for missions to evaquate the bases instead of just making units disappear?

that's why i called it a simple solution assuming that an evacuation had taken place (much more likely than OPFOR just sitting there and watching their destruction). the devs have limited resources, and i think starting with simple solutions is more sensible.
if you read further on in my suggestion, there's also a more realistic approach...

> Wouldn't you do anything in your power to send $1.5B of planes to the bottom of the ocean?

personally? no. mainly because, i want an ongoing exciting campaign. if the main target is a carrier or base that, in case destroyed, lets you win the campaign, we could also just set up a single mission, take the C130 mod and nuke them.

**anyway, the easiest solution would be making the "AI evacuates assets before capture" an option. so players can decide how they want to play their campaign.**

**Comment by Zarbas** [comment]
> personally? no. mainly because, i want an ongoing exciting campaign. if the main target is a carrier or base that, in case destroyed, lets you win the campaign, we could also just set up a single mission, take the C130 mod and nuke them.

That's exactly it. Forcing the AI to have flights for 20 planes to save the day is more exciting than "I'll have just 2, if I lose the base they'll be teleported to safety anyway". The mechanics are already there, it's just about deciding when it's a good moment and creating the missions. No one is talking about nuking anything here, it's just more rewarding to push yourself to the limit to achieve something. If there is no gain no one would fly at 50ft between multiple sam site just to take down a specific target.

**Comment by DanAlbert** [comment]
We need the `state.json` from the mission that caused the problem. The template didn't mention that, unfortunately. I've fixed the template.

**Comment by HILOK** [comment]
updated 1st 2 posts, state file added

**Comment by DanAlbert** [comment]
Shiraz and Kerman are too far apart to allow the retreat. Retreating aircraft have a range limit of 200nm. They're more like ~240nm apart.

Updated the docs: https://github.com/Khopa/dcs_liberation/wiki/Base-Capture#unit-retreat-behavior
