### ISSUE TITLE
Missing culling exclusion zone

### ISSUE THREAD

**Issue by DanAlbert** [dcs-liberation/dcs_liberation#946]
Image attached 

![image](https://user-images.githubusercontent.com/10494948/110892967-0f307680-82c3-11eb-9004-7ff2d2a0d882.png)

As well as miz file File
[liberation_game3_turn6.zip](https://github.com/Khopa/dcs_liberation/files/6127647/liberation_game3_turn6.zip)

_Originally posted by @MrMagicMan in https://github.com/Khopa/dcs_liberation/issues/578#issuecomment-797229329_

**Comment by DanAlbert** [comment]
`.miz` file isn't helpful. We need the liberation save.

**Comment by DanAlbert** [comment]
Seems to be a duplicate of https://github.com/Khopa/dcs_liberation/issues/926. Neither have the data we need to investigate though, so please attach your save there.

**Comment by MrMagicMan** [comment]
@DanAlbert recommend closing this as it is a duplicate.

**Comment by DanAlbert** [comment]
Based in the history here I think the reopening was accidental :) thanks
