### ISSUE TITLE
AI CAPs (red & blue) starting in CAP zone

### ISSUE THREAD

**Issue by Spartan111sqn** [dcs-liberation/dcs_liberation#948]
**Describe the feature**
At turn starts all aircrafts are on ground and run to occupy their asigned routes (CAP, SEAD, etc), it would be more immersive if at turn start some AIs (CAPs at minimum) are already on their CAP zone.

**Describe the solution you'd like**
The solution would be for example for CAPs, if CAPs are for 45minutes, such CAPs start their 45 minutes in CAP zone, then the players can start their engines and when they are in flight they can see other planes already performing their tasks. 

**Additional context**
After 45 minutes of the first CAP wave, they RTB and other aircrafts are taking off relieving them as they are working now. With that the immersion is bigger. Same looks happening with tanker and awacs, they start on their working zone.
In addition is would make lighter the Airbase traffic during turn commence.
It could be also done for SEADs, but doing it for CAPs would be very interesting.

**Comment by DanAlbert** [comment]
#1680 supercedes this
