### ISSUE TITLE
Send Message to Screen when blue captures an airbase or a FOB

### ISSUE THREAD

**Issue by techdr1ve** [dcs-liberation/dcs_liberation#949]
Please add message to notify when you capture airbase or FOB.
It's easy to do and would be really nice addition.

If it's controversial, please make it a selection checkbox.
that way we all can have our cake and eat it too  =)

![](https://cdn.discordapp.com/attachments/595706061126631424/822341582120026162/unknown.png)

Also you can add it for any high value objective static structure if you want too. (would be nice to have an option to turn that on and off too).

![](https://cdn.discordapp.com/attachments/595706061126631424/822342553738936380/unknown.png)

**Comment by DanAlbert** [comment]
Agreed would be useful for the current capture behavior, but we don't actually _like_ the current behavior. IMO the time spent on this would be much better spent on changing the capture behavior to not depend on DCS's built-in behavior, which would render this infeasible.

**Comment by techdr1ve** [comment]
this just notifies in GAME that you captured something, it doesn't actually mean this changes the capture behavior via DCS. 
It's still being captured 100% by how DCS Liberation has it setup...
It's simply a message so people know. Super simple... but okay.

**Comment by DanAlbert** [comment]
Yes, but if the capture mechanics are not based on the DCS capture mechanics displaying that message is not feasible.

**Comment by techdr1ve** [comment]
understood

**Comment by techdr1ve** [comment]
What about this one (you guys use ZONES right?)
Or people will not capture this via zones anymore (this one is just illumination flare, called illumination bomb)

![image](https://user-images.githubusercontent.com/61528637/111749556-32bd6900-884f-11eb-91e0-8c3e29855681.png)

**Comment by techdr1ve** [comment]
I'm guessing what you are saying is you won't use ANY mechanics at all in the future not even zones so nothing will matter in regards to that because DCS Liberation won't use zones in the future either.

**Comment by techdr1ve** [comment]
So actually it would work more like this.
![image](https://user-images.githubusercontent.com/61528637/111749840-9b0c4a80-884f-11eb-92d7-c5733fc4cba3.png)

**Comment by techdr1ve** [comment]
If you wanted to add a message to everyone then this one
![image](https://user-images.githubusercontent.com/61528637/111750036-ede60200-884f-11eb-9a9a-4367120cdba5.png)

**Comment by DanAlbert** [comment]
Yes, I'm saying if zones don't matter we can't do this in any reliable manner.

**Comment by techdr1ve** [comment]
gotcha, i'll just add it as a plug-in that people have to configure if they want to use it and i'll leave it at that. 
thanks for the prompt response.

**Comment by techdr1ve** [comment]
oh man! that's right you can only inject a file for a plug-in!
Do you know if it's possible to do any of the rest of these triggers through the plugin file?

![image](https://user-images.githubusercontent.com/61528637/111752068-7b2a5600-8852-11eb-98e5-afb9b76c0aeb.png)

**Comment by techdr1ve** [comment]
anything other than "file"?
Or could you point me to the dcs liberation code to this or the pydcs code to this?

**Comment by techdr1ve** [comment]
Wait a second, okay i looked at how you guys are doing triggers now ... it's Exactly the same way.
Literally you would have to add one line .... 
![image](https://user-images.githubusercontent.com/61528637/111754288-0efd2180-8855-11eb-8305-9caefd2f6a38.png)

**Comment by techdr1ve** [comment]
okay i looked at the pydcs code and the dcs liberation code ... what needs to happen is plug-ins need to have the ability to easily add anything from the triggers menu. I'll see if i can translate the pydcs code to the dcs liberation code and do it myself. 
Will be my first one, but worthwhile to me! meanwhile it won't affect any of your guys code bc it would only be enabled as a mod in plug-ins section.

**Comment by ucnanoman** [comment]
I see though you are running some sort of action script instead ... i see what you mean
![image](https://user-images.githubusercontent.com/61528637/111760274-c09f5100-885b-11eb-87a9-63fa46dc25fd.png)

**Comment by techdr1ve** [comment]
I see what you mean though ... you are running some sort of script additionally for the action trigger...
![image](https://user-images.githubusercontent.com/61528637/111760426-edebff00-885b-11eb-8e28-5a84f93100d0.png)
