### ISSUE TITLE
Flights coming back from the previous turn

### ISSUE THREAD

**Issue by Spartan111sqn** [dcs-liberation/dcs_liberation#954]
**Is your feature request related to a problem? Please describe.**
There are flights planned 3-4h after the turn starts, it should be great to start a turn and, according the previous ATO and time of the day, see the flights where they should be, in the air, landing, RTB.

**Describe the solution you'd like**
Take into account the previous ATO, and accordig the time of the day of the next turn and where they should be (using statistic), they could be dead, or they could be delivering ordenance, RTB, landing, spawn them doing exactly what they should be.

**Additional context**
On that manner you can take a real dynamic campaign alive very similar to BMS campaign

**Comment by DanAlbert** [comment]
Superceded by #1680
