### ISSUE TITLE
Generate LotAtc drawings for threat circles

### ISSUE THREAD

**Issue by drsoran** [dcs-liberation/dcs_liberation#956]
We (as a squad) use a human GCI/AWACS for our Libration missions. For this we use the well known LotAtc. Currently we have the problem that the GCI needs to draw the threat circles of known red SAMs manually after mission start. This is quite cumbersome and error prone. LotAtc already provides a feature to import threat circles, or more general drawing, via a JSON file.  

See [LotAtc Drawings](https://www.lotatc.com/documentation/client/drawing.html#add-draws-automatically-at-start).

**Describe the solution you'd like**
It would be really nice if I had the possibility to export such a file from Liberation or that such a file is generated by "Takeoff" as the circles are known by Liberation.

If possible, I would like to help implementing this feature if I get a go from you.

**Comment by DanAlbert** [comment]
> If possible, I would like to help implementing this feature if I get a go from you.

Sounds reasonable. Let us know what you need.

**Comment by drsoran** [comment]
Thanks! Just forked and added an export button to the UI (see screenshot). Worked flawless. I need to have some look into the LotAtc file format.

I keep you up with the changes so that we are aligned with the result. Feedback is welcome.
![Screenshot 2021-03-25 085232](https://user-images.githubusercontent.com/897403/112438320-0ec6bf80-8d48-11eb-9906-b36a8cff3034.png)

**Comment by drsoran** [comment]
@DanAlbert For LotAtc I need the center positions of the threats as GPS (WGS84). Currently I'm struggle with converting internal `Point` coordinates of a `TheaterGroundObject` to GPS coordinates. Could you give me some hints here? 

I think the internal coords are DCS like? How can I convert them to GPS?

**Comment by DanAlbert** [comment]
Can't be done currently. See my comments on https://github.com/Khopa/dcs_liberation/issues/915 if you're interested in solving that problem.

**Comment by drsoran** [comment]
Ah OK, that sounds really complicated and brittle. Didn't know that is is kept so internal by ED. Just asked the LotAtc if they can use DCS internal coords.

**Comment by DanAlbert** [comment]
If they can that's easiest. I don't think it's actually brittle, just a pain in the ass (and possibly hard).

**Comment by drsoran** [comment]
So, had an answer from the LotAtc guys. They have the same problem and integrate via scripting in a running DCS. They then use DCS converter functions to render their map. I think this could also be a solution for me. The idea is:

- have a lua script as plugin that runs exactly once during mission startup on the server
- this script generates the JSON once in a specific folder. LotAtc already autoloads JSONs found in that folder. Plus the threat circles are instant there when the client connects.
- the integration in Liberation would then be much more lightweight

To do this it would be nice to generate a list of unit names with threat circles which should be exported when compiling the mission file. This list would be the configuration for the export lua script. I saw that lua plugins have an option for configuration and all of them get a "dcsLiberation" instance. 

Does this instance has all information? Couldn't find any docs for it.

**Comment by drsoran** [comment]
The lua script attempt worked for me. Export at mission start works and writes the correct drawings.
