### ISSUE TITLE
Add fixed income with sliders in addition to the existing multipliers.

### ISSUE THREAD

**Issue by Nosajthedevil** [dcs-liberation/dcs_liberation#957]
Before filing, please search the issue tracker to see if this feature has already been requested.

**Is your feature request related to a problem? Please describe.**
I find myself adjusting the income sliders more than I would like as the battle shifts. Giving myself a higher multiplier in the  beginning and the "defending" faction more towards the end to keep the missions somewhat competitive.

**Describe the solution you'd like**
Don't change the current economy, since the various assets that can be destroyed need to matter, however also add period income with a slider between say, $0M and $200M. This would reflect the fact that the attacking faction and possibly the defending faction would have income streams from outside the war zone.

**Additional context**
I realize there are cheats, but using them feels like cheating and they don't apply to the AI factions. Also, this is really low priority on my wish list of changes, this just saves us from having to spend a few seconds adjusting the income slider before each round. But it would be nice to decide on a level of funding and then not feel like we're arbitrarily changing it as time goes on.

**Comment by Nosajthedevil** [comment]
I forgot I opened this. Campaign designers can already do this by adding as many income producing assets as they would like near the final base.

**Comment by DanAlbert** [comment]
Good point :)
