### ISSUE TITLE
Allow additional AI ground units on front lines

### ISSUE THREAD

**Issue by Nosajthedevil** [dcs-liberation/dcs_liberation#958]
**Is your feature request related to a problem? Please describe.**
AI front line ground units seem to max out at 30 in total regardless of number of fronts, cash on hand, and blue force counts. Some maps can have 4 fronts with very few (4 to 7) Opfor units on each. Easy to steamroll, since I try to make sure each of my fronts have at least one or two of each unit type , so 15 + each for the US faction.

**Describe the solution you'd like**
Add a slider that sets the cap or checkbox that allows the cap to be removed, allowing ground forces to scale up to what Opfor can afford and requires.

**Comment by Mustang-25** [comment]
Marking this feature as implemented. The new ammo depot feature allows the campaign designer to adjust the size of each frontline.
