### ISSUE TITLE
Remove invincibility and placement recommendations for AWACs and Tankers

### ISSUE THREAD

**Issue by Nosajthedevil** [dcs-liberation/dcs_liberation#959]
Parallel thoughts to Spartan111sqn 's request from several days ago!!!

**Is your feature request related to a problem? Please describe.**
AWACs and Tankers provide an immense benefit that can't be taken away. Let's change that.

**Describe the solution you'd like**
Remove Invincibility from AWACs and Tankers and force sides to defend or lose them as an assett. I realize placement would be the primary issue. There are a number of approaches you could take for placement and utilization that get to the same result. Whichever is easier to implement.

1) Consider making them like a non-capturable capital asset where they have a repair / replacement  cost if destroyed, and have them orbit fixed points on the map that move to new fixed points as the battlefronts move.

2) Same as above, but give them a movement mechanic similar to carriers where the user draws a line to where they should re-deploy.

3) Have the player purchase like any other aircraft and create refueling / AWACs missions for them.

My preference would be one or two, a bit less active management involved.

**Comment by DanAlbert** [comment]
Duplicate.
