### ISSUE TITLE
Limit aircraft to airports that can fit them.

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#961]
**Is your feature request related to a problem? Please describe.**
B52s and the upcoming E-3s are large aircraft that cannot fit into a parking spot at every airbase.

**Describe the solution you'd like**
Prevent the purchase of aircraft that are too large for the parking at an airbase.  Prevent Arrivals/Diversions of too large aircraft at said airport as well.

**Additional context**
An example:  You can purchase a B52 and E-3 at Palmyra in the Syria map.

The one downside of limiting this would be that the large aircraft take longer to get in their final position, but that is a limitation of Liberation/DCS in general due to it's turn based nature.

**Comment by DanAlbert** [comment]
DCS maps include this data and we follow it. Unfortunately the Syria map is not finished yet so a lot of the data is wrong. Nothing for us to do but wait.

**Comment by clutchtomcat** [comment]
> DCS maps include this data and we follow it. Unfortunately the Syria map is not finished yet so a lot of the data is wrong. Nothing for us to do but wait.

Would this also cause issues with aircraft spawning in parking spaces too small for them, thus causing collision/destruction on mission start? I've been getting a consistent issue with this at the King Hussein Air College and was about to file a bug report on it.

**Comment by DanAlbert** [comment]
Yes.
