### ISSUE TITLE
Allow player to delay start of friendly ground forces' advance on front line

### ISSUE THREAD

**Issue by Floydii** [dcs-liberation/dcs_liberation#964]
**Is your feature request related to a problem? Please describe.**
Currently, friendly ground forces will often be decisively engaged (or dead) before CAS/BAI has a chance to get to the front line. This doesn't reflect reality where ground manoeuvre and supporting aircraft are closely synchronised in time.

**Describe the solution you'd like**
It would be good to allow the player to set a delay ground units starting their advance (utilise the same format as setting 'TOT' for aircraft packages). This would only need to apply to  '"aggressive, ""breakthrough" and "elimination" Frontline operations. "Defensive", "Retreat" and "Ambush" would not be effected by this and the enemy would conduct their operations per whatever timeline they have established. 
I have attached an image to show where this would be in the UI. The time should grey out if a Frontline Operation is selected that doesn't allow a delay to be implemented.

**Additional context**
To be clear, this is simply when the units *start* to move from initial positions, rather than arriving at a location (as per TOT).
![delay timer](https://user-images.githubusercontent.com/40154322/112711735-c7465c00-8f1e-11eb-8333-148694044d30.jpg)

**Comment by HILOK** [comment]
very good idea!
and why not have a TOT (as arrival at the frontline) for ground troops, if you dont mind my asking? -i think it would make planning a bit easier

**Comment by Floydii** [comment]
I didn't think stipulating a TOT for ground units would be viable as we're talking about multiple units which need a fair bit of work to arrive into contact at the same time even if the enemy stays still.

A defined start time for the advance is easier to script and at least then you can have CAS overhead (and CAP for that matter) before units start to move.

**Comment by HILOK** [comment]
i see, thanks : )

**Comment by nosv1** [comment]
Should the AI have this ability then, and then what would its logic be?

**Comment by DanAlbert** [comment]
Irrelevant with #1680
