### ISSUE TITLE
Buy replacement EWR sites

### ISSUE THREAD

**Issue by entropyembrace** [dcs-liberation/dcs_liberation#968]
**Is your feature request related to a problem? Please describe.**
Frequently during the campaign EWR sites are destroyed and cannot be replaced.

**Describe the solution you'd like**
The option to spend money from the budget to replace destroyed EWR sites similar to how we can replace destroyed SAM sites and ground units.

**Comment by DanAlbert** [comment]
They're _supposed_ to be replaceable. This is a bug.
