### ISSUE TITLE
Feature Request: Add loadout dropdown on top of custom selection in mission preparation

### ISSUE THREAD

**Issue by rabauke80** [dcs-liberation/dcs_liberation#97]
How about adding a "presets dropdown field" on top of the custom "loadout dropdowns per station" in the UI ? That way, we would have access to the presets more easily, but still can assign custom loadouts.

Bonus: if the documentation would describe how to add additional custom presets, people would less and less use the actual custom loadout menu.

**Comment by DanAlbert** [comment]
https://github.com/Khopa/dcs_liberation/issues/273
