### ISSUE TITLE
Anti Ship strike missing a target waypoint.

### ISSUE THREAD

**Issue by MrMagicMan** [dcs-liberation/dcs_liberation#971]
Before filing, please search the issue tracker to see if the issue has already been reported.

**Describe the bug**
Created a large formation of F18's set for anti ship operation. They Took off, flew to the ingress point, then went to the egress point and landed no anti shipping was done.

**To Reproduce**
I have had one successful anti shipping strike, but it was at the start of a new game.

I think this is based on the fact that it seems to redirect my anti ship strike to a second group when I plan to attack the Admiral Kuznetov. 
![image](https://user-images.githubusercontent.com/10494948/112789001-15945180-902a-11eb-9f6b-71e4394948b9.png)

Here is the first time it happened, it shows the missing target point more clearly.
![image](https://user-images.githubusercontent.com/10494948/112789172-7cb20600-902a-11eb-95a8-ba8090ccb053.png)

**Expected behavior**
Add  Admiral Kuznetov as a target at waypoint 4.

**Additional information**
Note that the F16 escort in the same package was given the ship coordinates as a flyover point.

Here is the liberation file and the mission file.
[AntiShipIssue.zip](https://github.com/Khopa/dcs_liberation/files/6219320/AntiShipIssue.zip)

Let me know if you need more information.

**Comment by MrMagicMan** [comment]
not sure if this is related to #820

**Comment by Starfire13** [comment]
Already filed here: https://github.com/Khopa/dcs_liberation/issues/902

What weapons were your antiship flight using? Harpoons?

**Comment by MrMagicMan** [comment]
Crap missed that one, Yes harpoons
