### ISSUE TITLE
mission date increment

### ISSUE THREAD

**Issue by HILOK** [dcs-liberation/dcs_liberation#973]
**Describe the bug**
the mission date is not incremented in PG invasion of iran lite.
![Capture](https://user-images.githubusercontent.com/76898536/113483603-9c22b600-94a4-11eb-8aa3-a7dcb8d6ba90.JPG)
(campaign started at exactly that date)

**To Reproduce**
- - -

**Expected behavior**
increment the date after each day passing by

**Additional information**
- - - 

**Version information (please complete the following information):**
 - DCS Liberation 2.4.3-2

**Additional context**
sorry if this has already been addressed -couldnt find anything using search...thanks

**Comment by DanAlbert** [comment]
Attach your save game.

**Comment by HILOK** [comment]
[invasioniranlite_summer90.zip](https://github.com/Khopa/dcs_liberation/files/6254134/invasioniranlite_summer90.zip)

**Comment by DanAlbert** [comment]
Fixed. Has no effect when you load, but will fix starting on the next turn.
