### ISSUE TITLE
Move fleets the same way you can move carriers

### ISSUE THREAD

**Issue by Moguy164** [dcs-liberation/dcs_liberation#974]
Before filing, please search the issue tracker to see if this feature has already been requested.

**Is your feature request related to a problem? Please describe.**
I would like to be able to use my destroyers and my naval fleet to have more control over the naval action

**Describe the solution you'd like**
have fleets be capable of being moved the same way carriers are, this can coerce them into engagements with the enemy fleet.
perhaps later on they could also be assigned specific fleets to attack and maybe have the AI as well manage their fleets, for example if the situation in an upcoming battle is unfavorable then he'll try to retreat, but if a carrier is left undefended he'll try to push, and so on 

**Additional context**

**Comment by DanAlbert** [comment]
Duplicate

**Comment by Moguy164** [comment]
> Duplicate

is there a link to the original?
