### ISSUE TITLE
JTAC does not transmit the altitude

### ISSUE THREAD

**Issue by SpartanEsp** [dcs-liberation/dcs_liberation#975]
JTAC does not transmit the altitude of the target when you request the coordinates on the F10 Menu

**Comment by DanAlbert** [comment]
JTAC plugin isn't ours. I'm guessing it's the plugin that needs to be fixed. There's nothing to configure here afaik.

**Comment by SpartanEsp** [comment]
i have noticed that the coord given by the JTAC are not precise, sometimes is a completly empty area, and the Laser doest not guide the GBU-12 on the Hornet and other planes, i think sometimes the Laser just not tuning ON.

If the JTAC script is the problem... disabling it should fix it, but without the script, missions will be generated without JTAC right ?

**Comment by DanAlbert** [comment]
Yes, the script is what probably needs fixing here. That's not our code.

**Comment by HILOK** [comment]
it works fine with laser-mav / hornet on my end. laser-mav's advantage: it indicates, if it sees a laser spot. sometimes what happens though is that the time i arrive at the front, there's nothing left to shoot at ; )

**Comment by Fededale** [comment]
> it works fine with laser-mav / hornet on my end. laser-mav's advantage: it indicates, if it sees a laser spot. sometimes what happens though is that the time i arrive at the front, there's nothing left to shoot at ; )

Some here with A10-C 2.
