### ISSUE TITLE
KeyError; 17

### ISSUE THREAD

**Issue by Tribillowl** [dcs-liberation/dcs_liberation#976]
Before filing, please search the issue tracker to see if the issue has already been reported. Cannot find

Having got to nearing end of campaign, will not load with the message "KeyError; 17"
[autosave.zip](https://github.com/Khopa/dcs_liberation/files/6258912/autosave.zip)
No MIZ file, as will not load to DCS.
[state.zip](https://github.com/Khopa/dcs_liberation/files/6258919/state.zip)
Using version 2.4.3
Many thanks.

**Comment by DanAlbert** [comment]
https://github.com/Khopa/dcs_liberation/pull/972 seems related, but that's masking the symptom rather than fixing the bug, so needs more investigation.

**Comment by DanAlbert** [comment]
Also a dup of https://github.com/Khopa/dcs_liberation/issues/898
