### ISSUE TITLE
improve UI for win/loss

### ISSUE THREAD

**Issue by DanAlbert** [dcs-liberation/dcs_liberation#978]
Currently just a message in the info panel. Ought to have a pop up and disable the next turn/takeoff buttons.

**Comment by alcmann** [comment]
and a nice slash screen for a WIN ! / and a nice humiliating screen for a loss.

**Comment by KeeseAF** [comment]
Without adding another Issue request, is it possible to just get rid of the "insuffecient" messages?

**Comment by Raffson** [comment]
With the transition to a "turnless" campaign, the question remains regarding the behavior of `SimSpeedControls`. Would it be preferable to disable them as well?
