### ISSUE TITLE
Russian AA missile tweak.

### ISSUE THREAD

**Issue by BabyGreen89** [dcs-liberation/dcs_liberation#980]
Playing DCS Liberation dynamic campaign, I noticed that US made planes completely dominate in AI vs AI scenarios, 
since the AMRAAMs trounce any "comparable" Russian missile in terms of kinematic performance. 
Due to how the AI acts in BVR, even the Sparrow has an edge due to its lofting capability. 

To make AI matchups more interesting, I've given the R-27ER the ability to loft in a manner similar to the Sparrow. 
Range, mass, drag, etc. weren't changed. 

The R-77 also received the ability to loft, alongside getting extra mass and a boost phase, again along Sparrow lines.
ECM resistance tweaking is WiP.

The results so far have been promising - both missiles give Russian built aircraft a fighting chance against AMRAAM carriers,
without being blatantly broken like the R-77M from the Su-35 mod.

Ranges of the Vikhr, Kh-25ML and Kh-58 also got tweaked.

Could this modified .lua file be integrated into the overall DCS Liberation mod? That would be great :)

https://drive.google.com/file/d/1ZxytfKwUTxODKt4H8oZs4JFJ9GqjgUnB/view?usp=sharing

**Comment by Khopa** [comment]
Hey, this seems like an interesting mod.

But, as this require modifying game files (in the DCS installation folder), it is up to the user to mod/update his game.

The "plugins" system we added in liberation only let us add "scripts" to the mission files, but not to modify files in the game folder, I consider this out of scope for liberation, it is up to the user to install such mods.

For instance if you use a faction that has a modded aircraft such as the A-4E-C, it is still up to you to download and install the latest mod version.

Feel free to share your mod on Discord on either #off-topic, #general channel to let other users know about it.

**Comment by BabyGreen89** [comment]
Alright, thanks for the reply!
