### ISSUE TITLE
[Dead] units have different names than the alive versions.

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#988]
**Describe the bug**
When a unit is marked as dead, it's name changes.

Before:
![Oryx_before](https://user-images.githubusercontent.com/74509817/115179143-e3599b00-a08f-11eb-9198-49bb36fca981.jpg)

After:
![Oryx_after](https://user-images.githubusercontent.com/74509817/115179152-e5bbf500-a08f-11eb-8013-b07a49d195ac.jpg)

**To Reproduce**
1)  Perform a SEAD mission on a SA-11, SA-10, etc
2)  Observe that target names change when they have the [Dead] label in front of them.

**Expected behavior**
Alive and dead unit name to be consistent.

**Additional information**

Observe location ORYX before and after applying state.  The SA-10 tracking radar changes name.
[Consistent_Names.zip](https://github.com/Khopa/dcs_liberation/files/6333124/Consistent_Names.zip)

**Version information (please complete the following information):**
 - DCS Liberation 2.5 preview.

**Comment by Starfire13** [comment]
Looks like it's using the old naming style after dying

**Comment by Mustang-25** [comment]
This doesn't seem to be an issue on the latest builds, verified by looking at partially destroyed SA-11 and SA-15 sites. Closing this report but we can reopen it if the problem persists with other units.
