### ISSUE TITLE
Feature Request: Save / Edit loadouts for the custom loadout screen

### ISSUE THREAD

**Issue by loneregister** [dcs-liberation/dcs_liberation#99]
Hi Khopa!

Feature request - Allow the player to setup, per plane, loadouts they can save that they can select in the custom loadout screen.  This would include the default loadouts that you use, which would not be editable, but would be selectable.  If a user then changes the loadout from your default loadout, it would then allow the player to then save that as a new option for loadouts.  (Player to provide name of loadout).

Basically this:
Custom loadout screen.  Player checks the checkbox for a custom loadout.  Next to this drop down is an enabled save button.
Drop down box would contain a list of the default loadouts that the player could select from.  If the player changes a default loadout, and saves it with the same name, all default loadouts for that plane, for that mission type, going forward will use the new loadout.

If the player saves it as a new name, it's a loadout that the player can select.  But would never be used by the DCS Liberation engine as a default.

Bonus points for detecting matching loadouts, and notifying the user if the loadout they have chosen matches another loadout that already exists.

**Comment by DanAlbert** [comment]
https://github.com/Khopa/dcs_liberation/issues/273 is the even more user friendly form of this.
