### ISSUE TITLE
Deleting autogen packages generates error

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#990]
**Describe the bug**
Multiple lines of variants of "QGraphicsScene::removeItem: item 0x1d323bbe9c0's scene (0x0) is different from this scene (0x1d31f347780)" when deleting autoge flight packages.

At the end of the deluge of lines, this is generated:
Traceback (most recent call last):
  File "qt_ui\widgets\map\QLiberationMap.py", line 145, in <lambda>
  File "qt_ui\widgets\map\QLiberationMap.py", line 675, in draw_flight_plans
  File "qt_ui\widgets\map\QLiberationMap.py", line 668, in clear_flight_paths
TypeError: 'PySide2.QtWidgets.QGraphicsScene.removeItem' called with wrong argument types:
  PySide2.QtWidgets.QGraphicsScene.removeItem(QWidgetItem)
Supported signatures:
  PySide2.QtWidgets.QGraphicsScene.removeItem(PySide2.QtWidgets.QGraphicsItem)

**To Reproduce**
1. Delete autogen package

**Version information (please complete the following information):**
#1377

**Comment by Mustang-25** [comment]
Problem seems to have been fixed awhile back. Closing this one out.
