### ISSUE TITLE
Loadouts in payload editor have underscores instead of spaces

### ISSUE THREAD

**Issue by Hornet2041** [dcs-liberation/dcs_liberation#993]
Present in build #1385

![image](https://user-images.githubusercontent.com/55866858/115322315-ceded680-a153-11eb-9f64-46d553b7e5e7.png)

**Comment by DanAlbert** [comment]
@Khopa is already on this, it looks like https://github.com/pydcs/dcs/pull/126

**Comment by DanAlbert** [comment]
(marking for both 2.5 and 2.6 because while this is only broken in 2.6 we should pull the ME l10n fixes into 2.5 because they break custom campaigns)

**Comment by Hornet2041** [comment]
![image](https://user-images.githubusercontent.com/55866858/122552063-d27fc400-d003-11eb-8c8a-c97554d0790d.png)
issue has reappeared in build  1971 :(

**Comment by DanAlbert** [comment]
That _is_ the "name" from pydcs. @Khopa I don't think there's anything to be done here? Or did the exporter break?

**Comment by Khopa** [comment]
That's weird, weapons stuff shouldn't have changed in pydcs. :/

**Comment by DanAlbert** [comment]
Definitely did though: https://github.com/pydcs/dcs/commit/23567d060c6968f666cd982f7ffeb926c3f0ef7b#diff-65da24dc2ec61a9eb2c9b7a88cb3d76d9a5218698ea4f4c9206f6fc292b50990 (haven't looked for the cause)

**Comment by DanAlbert** [comment]
Ah: https://github.com/pydcs/dcs/commit/23567d060c6968f666cd982f7ffeb926c3f0ef7b#diff-9dad93553ce80f476d086421867d7ce9cad26dc58bf76786f913bb3b4bf2bf52R205

**Comment by DanAlbert** [comment]
https://github.com/pydcs/dcs/pull/157

**Comment by Khopa** [comment]
> [pydcs/dcs#157](https://github.com/pydcs/dcs/pull/157)

Ugh, sorry, I didn't correctly reverted my changes on pydcs export after messing with weapons id.

**Comment by DanAlbert** [comment]
No worries. Easy fix.
