### ISSUE TITLE
Loading state.json from network drive

### ISSUE THREAD

**Issue by alexkrebiehl** [dcs-liberation/dcs_liberation#994]
**Describe the bug**
I'm trying to run a dedicated server on another computer on my LAN to try and improve performance, and I have a network drive mounted on both computers. I'm saving state.json to the network drive, but when I try to manually submit it in Liberation, I cannot browse to the networked drive in the dialog presented. Trying to manually enter the path in the address bar results in a "not found" error, though I can browse to the location just fine in File Explorer.

**To Reproduce**
1. Mount a network drive
2. Try to manually submit a state.json located on the network drive

**Expected behavior**
The "manually submit" state.json dialog allows browsing to network drives.

**Version information (please complete the following information):**
 - DCS Liberation 2.4.3

**Comment by DanAlbert** [comment]
> I cannot browse to the networked drive in the dialog presented. Trying to manually enter the path in the address bar results in a "not found" error, though I can browse to the location just fine in File Explorer.

That'll be a Qt bug that's likely outside our control. Qt has been through quite a few updates since this was filed so this may already be fixed, if it isn't there's not a lot we can do other than continue working toward replacing it.
