### ISSUE TITLE
Add More Functionality to Air Defense Generation

### ISSUE THREAD

**Issue by Mustang-25** [dcs-liberation/dcs_liberation#999]
I've been thinking about how to flesh out the IADS environment more and have thought of a couple related ideas:

1. Have air defenses generated semi-randomly at locations defined in the campaign miz. This would be a similar system to how an EWR is currently generated on a CP with the ability to define multiple locations but only have a certain portion of them generate actual units.

2. To further expand on this new feature, give the campaign creator the ability to define the min or max number of each type of air defense unit (LORAD, MERAD, SHORAD, AAA). In practice, I would think that defining it as a percentage total would be the easiest way to do this in order to account for the varying number of locations for each CP. This also dovetails into the 'More AAA' FR (#347) and tangentially related to more SHORAD locations (#271).

This feature would also add some infrastructure to the future intel system (#272) by allowing for the relocation of mobile SAM systems (#538) between the unused sites designated in the campaign miz.

This could also be part of the solution to #194 by making the proportion of SAMs generated be user adjustable.

**Comment by DanAlbert** [comment]
We already more or less do 1, btw. I think the on tweak there would be to make the "random SAM" and "random building" separate entities in the campaign.

That is essentially how #538 is going to work, FWIW. We'd put mobile SAMs in some.of the random SAM slots.

**Comment by Mustang-25** [comment]
> We already more or less do 1, btw. I think the on tweak there would be to make the "random SAM" and "random building" separate entities in the campaign.

So my understanding is that this is only for the SAMs placed within 2NM of the CP, right? My experience with the those freestanding objectives (the ones outside of 2NM) is that every unit you put down in the campaign miz for the corresponding SAM will always generate a SAM unit group.

**Comment by DanAlbert** [comment]
Outside 2nm is handled by https://github.com/Khopa/dcs_liberation/wiki/Custom-Campaigns#strike-targets. They are often SAMs but that's also how the building strike targets (the money generating things) are generated.

To clarify: I agree that we should split these two things. It's been a nice-to-have to a while now, it's just a thing we've held off on because it'll break every existing campaign to do it. Since I've just done that with the convoy system now might be a good time though...

(assigning part 1 to 2.6, idk about part 2 yet)

**Comment by Mustang-25** [comment]
> Since I've just done that with the convoy system now might be a good time though...

I mean... if you're already tearing stuff up under the hood might as well add AAA, mobile/fixed MERADS, and SHORADS as separate generators while you're there. lol

**Comment by DanAlbert** [comment]
Added support for AAA specific sites, and the rest is either obsolete by removing random spawns or covered by the mobile SAM FR.
